### ISSUE TITLE
Is the tesselation done in OpenGL?

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#10]
Hi!
I'm working on Linux machine so it's important for me to know - is the tesselation in Armory Engine done in OpenGL? I hope so. Because if the engine uses DX12 and does it's tesselation only there, than the tesselation would become Linux-uncompatible(like it's currently in Unreal Engine 4 where Linux/Mac users don't have tesselation). So I just wanna find out if you have written the tesselation in OpenGL and I'm hoping for the best;)

**Comment by zauberparacelsus** [comment]
Armory is based on Kha, which uses whichever API is appropriate for the host platform.

**Comment by adriansnetlis** [comment]
That sounds good!:)

**Comment by luboslenco** [comment]
Yup, tessellation works on OpenGL and will work on other APIs supported by Kha. No graphics API specific code in Armory. :)
