### ISSUE TITLE
spawning armature

### ISSUE THREAD

**Issue by antomicek** [armory3d/armory#1000]
Hi,
If I try to spawn armature from hidden layer, this is what I get from console.
![console](https://user-images.githubusercontent.com/42112273/48065454-1020dd00-e1cb-11e8-91be-c09b3d4dbd52.JPG)

workaround is,
If armature is on visible layer(with simple node setup, on init - play action, on timer - remove object),but

every time the new armature is spawned, it resets animations on all allready spawned armatures.
Also if one of the spawns is removed, all other spawns on scene stops playing animation.

[SPAWN ARMATURE FROM HIDDEN LAYER.zip](https://github.com/armory3d/armory/files/2553251/SPAWN.ARMATURE.FROM.HIDDEN.LAYER.zip)
[SPAWN ARMATURE FROM VISIBLE LAYER.zip](https://github.com/armory3d/armory/files/2553252/SPAWN.ARMATURE.FROM.VISIBLE.LAYER.zip)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/5d8e7125a4ce17935861270b3faff8bc80073a9f, thanks!
