### ISSUE TITLE
Gate Node "and" works like "or"

### ISSUE THREAD

**Issue by BrahRah** [armory3d/armory#1003]
[Mood Door amy 001.zip](https://github.com/armory3d/armory/files/2565398/Mood.Door.amy.001.zip)
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Armory will print `Sockets do not match in logic node tree "Door001" - node "Gate" - socket "Value"` now. Will turn it into compile error once it gets tested. https://github.com/armory3d/armory/commit/c850aa0e268216f8a372a9d2bf9ac5ccc3fa2c09
