### ISSUE TITLE
"Array Loop" Logic Node Only shows last Index on HTML/Browser

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#1004]
[SpawnTest.zip](https://github.com/armory3d/armory/files/2566042/SpawnTest.zip)

When spawning an object that is referenced on another layer in HTML (Browser) it doesn't spawn each object, only the last.

To test run this project as Krom or C++ works as intended (four torus) 

Then run in browser and only one torus will show.

Version 0.5 Blender 2.79

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Fixed, thanks for report! https://github.com/armory3d/armory/commit/20697b495f8a119d760dc63c4be4df33fc25be55
