### ISSUE TITLE
Armory pbr material issues

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#1005]
When we create a new Armory pbr material assigning textures in the right panel
There is two issues : 

1) Looking in the material nodes, a new material automatically uses Alpha channel of roughness and metallic textures instead of using the grey color.

2) Reflections doesn't seem to work with Armory pbr, it needs some reflection probes.

**Comment by luboslenco** [comment]
Link https://github.com/armory3d/armory/issues/624 https://github.com/armory3d/armory/issues/649.
