### ISSUE TITLE
Request: on change single signal node

### ISSUE THREAD

**Issue by Gedankenexper1ment** [armory3d/armory#1009]
It would be very nice to have a node that sends a single pulse (red output) when a value (bool, number, etc) changes. This would be useful in many situations, but especially so for converting constant signals (like keyboard down or on overlap) to single pulses (like keyboard started). This allows us to use set variable to count, and send signals to nodes that work best with a single pulse (like print or sequence).

**Comment by BlackGoku36** [comment]
You can use Event nodes.
