### ISSUE TITLE
Screen Scaling With Preserved Aspect Ratio

### ISSUE THREAD

**Issue by zicklag** [armory3d/armory#1010]
There should be an option that you can set so that scaling the game window resizes the viewport while preserving the aspect ratio. See [this](http://forums.armory3d.org/t/blender-ui-and-3d-scene-scaling-question/2182?u=zicklag) post.

**Comment by luboslenco** [comment]
Patched at https://github.com/armory3d/iron/commit/1ab1fef246c93d106dc5a45a397d2f09290de687, not doing black bars (yet) though, instead it rebuilds the camera projection to match the window size perfectly.

**Comment by zicklag** [comment]
Yay! My brothers are working on a simple app and they really needed this. Thanks! :smiley:

**Comment by luboslenco** [comment]
Hoho, super cool to hear it will come to use! Can add more options there eventually. 🙂
