### ISSUE TITLE
All Events are firing twice - Browser + Krom

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#1013]
Unable to reproduce this bug at this time, however this project: https://github.com/Defaultsound/TiltBall has the issue in the latest version of 0.5 in Blender 2.79. 

In the console you can clearly see every event regardless of when or what it is, is called twice: 
![image](https://user-images.githubusercontent.com/5720489/48735836-5d786200-ec41-11e8-8b5d-df4fd6e9afc5.png)

So far I've been unable to reproduce said bug, I've tried to drawn some conclusions to whether or not it is due to:
 
- Spawning nested objects
- Animations
- Volume Overlap events
- Parented Objects
- Custom events

Yet to test:

- Spawning objects in an array
- Armature objects parented to a mesh

While none of these things seem plausible, I had to check them to make sure. Will be continually exploring this issue to try and reproduce it. For now it is a mystery. 

*(drag & drop zipped .blend file here)*

**Comment by Defaultsound** [comment]
I have found the culprit! I was partially my fault. 

It seems that if any object shares the same trait that the events double up. The solution was to remove the matching trait from the other object and sure enough it works at intended. Not sure if this a bug or intended functionality.

**Comment by BlackGoku36** [comment]
Armory doesn't have ECS for now(it coming in 0.7 builds), In other game engines there are things like Pawn, PlayerController, and stuff, while armory doesn't have those, so there is no declaration of who controls what and so the player run everything script is attached to.
@luboslenco  You can close this one.
