### ISSUE TITLE
Prefab System , any solution ? 

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#1014]
read discussion 
[http://forums.armory3d.org/t/armory-prefabs-discussion/2133/10](url)

Linked objects doesn't support child objects, only two objects can be linked in Blender.
Two Groups can't have same child object name.

Will Blender 2.8 have a solution, or should Armory make it's own prefab system ? 

Prefab is not possible in Armory and must have for 3D engine
[https://www.youtube.com/watch?v=ibmdm_PoyMA](url)

**Comment by luboslenco** [comment]
Please do not re-post issues multiple times. Will investigate at https://github.com/armory3d/armory/issues/436.
