### ISSUE TITLE
Objects gravity does not work

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#1015]
After updating SDK, object gravity does not work.
(With continuous collision detection it's better, cube does not pass through moving platform)

[https://github.com/DevMagicLord/Godot3/blob/master/bugs/A/physicsWeirdAgain.gif](url)

Project download
[https://github.com/DevMagicLord/Godot3/blob/master/bugs/A/third_person%20bug.zip](url)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/922.
