### ISSUE TITLE
C++ building

### ISSUE THREAD

**Issue by nxrighthere** [armory3d/armory#1016]
Greetings. I've recently tried to build [templates](https://github.com/armory3d/armory_templates) using MSBuild, and despite the fact that the projects built successfully, after launching the application the runtime throws an unknown exception:

![exception](https://user-images.githubusercontent.com/8279330/48789132-2c199800-ed0e-11e8-9d19-2ab84553e27e.PNG)

Krom works without any problems.

Armory_05b_win64_b27
Command `msbuild first_person.sln /p:Configuration=Release /p:Platform=x64`

**Comment by AttSee** [comment]
What is your operating system?

Are there any error messages؟

**Comment by nxrighthere** [comment]
Yea, the content files are placed in another directory, and the compiled binary is not moved/copied automatically to this folder like when you building Krom standalone.

**Comment by nxrighthere** [comment]
I think it would be better to throw an appropriate exception if possible to avoid some confusion for newcomers.

Auto moving/copying the exe file to the directory with data after the building should be considered as well.
