### ISSUE TITLE
logic nodes not live patching

### ISSUE THREAD

**Issue by bibleuspro** [armory3d/armory#102]
I was attempting to live patch a node change, and nothing seems to happen.

I am using this logic node on ballie
https://github.com/armory3d/armory_docs/issues/1

![image](https://cloud.githubusercontent.com/assets/19825051/21564536/fdc33d54-ce4b-11e6-8bfe-dea2f44f3202.png)

X vector to 10 should update ballie, it doesn't

Was going to add here https://github.com/armory3d/armory/issues/95 but closed

**Comment by luboslenco** [comment]
Fixed in upcoming Build 12 (needs to be played in viewport for now though).
