### ISSUE TITLE
Shader Compiler Error - Incorrect Code Generated?

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#103]
I'm getting the following error output when Armory attempts to compile the fragment shader for an eyeball, and it doesn't seem to make much sense to me, so I'm guessing that maybe it's generating incorrect shader code?

```
ERROR: 0:66: 'texCoord' : undeclared identifier 
ERROR: 0:66: '=' :  cannot convert from 'temp float' to 'temp 2-component vector of float'
ERROR: 0:66: '' :  syntax error
ERROR: 3 compilation errors.  No code generated.


SPIRV is not generated for failed compile or link

Shader compiler error.
Build failed, check console
```

Attached below is an example .blend file that has the problem.  In the node editor UI, I have highlighted the nodes that seem to cause the problem, as the shader compiles when they are deleted.
[EyeballShader.blend.zip](https://github.com/armory3d/armory/files/679325/EyeballShader.blend.zip)

**Comment by luboslenco** [comment]
Should now build & run without errors.

Materials are still a bit complicated for Armory so results are not ideal yet. The camera is also off, will take care of that too.
