### ISSUE TITLE
Bake broken in 2.8

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1030]
1) Open official example material_baked, select Krom as Runtime (but probably doesn't matter)
2) Make right wall blue
3) Hit bake and wait
4) Press Play, see materials are broken
5) Try apply, get the error:

Traceback (most recent call last):
  File "/home/trsh/Downloads/Armory/armsdk//armory/blender/arm/props_bake.py", line 224, in execute
    bpy.data.materials.remove(mat, True)
TypeError: BlendDataMaterials.remove(): required parameter "do_unlink" to be a keyword argument!

6) Press Play - see only cube in middle got baked material
7) Overall process is unusable

System Ubuntu 18.x

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/12330e6f618ea3422f5215a6f4ec4d371191ed70.
