### ISSUE TITLE
Translucency is broken

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#1032]
Tested with 2.79 and 2.8, if the scene has translucent material, it will fail to compile:
![image](https://user-images.githubusercontent.com/17811339/49329113-7116b780-f5b5-11e8-8679-9dd93fabb989.png)

**Comment by luboslenco** [comment]
Will be back soon, upgrading lots of stuff for 0.6. :slightly_smiling_face:

**Comment by FuriouZz** [comment]
Temporary fix in `make_transluc.py`

```
	# sh = tese if tese != None else vert
	# sh.add_out('vec4 wvpposition')
	# sh.write('wvpposition = gl_Position;')

	# Remove fragColor = ...;
	frag.main = frag.main[:frag.main.rfind('fragColor')]

	frag.write('\n')
	# frag.write('vec4 premultipliedReflect = vec4(vec3(direct * lightColor * visibility + indirect * occlusion) * opacity, opacity);')
	frag.write('vec4 premultipliedReflect = vec4((direct + indirect * occlusion) * opacity, opacity);')
```

`wvpposition` is declared twice (Declared in the `make_cluster` too)
`lightColor` and `visibility` are no longer declared

**Comment by luboslenco** [comment]
Should at least compile now. Additional improvements soon.
