### ISSUE TITLE
Plz fix animation

### ISSUE THREAD

**Issue by BrahRah** [armory3d/armory#1037]
*(drag & drop zipped .blend file here)*
Ive been using armory for a while now and no animation whatsoever is working. Here is a packacke with all the tests I did of which none worked without any major bugs: [Blend files.zip](https://github.com/armory3d/armory/files/2662985/Blend.files.zip)
  

I suggest you fix up animation in armory if users cant even animate simple shapes like cubes rotating without armory bugging out there is nothing that can be done with armory right now.

**Comment by luboslenco** [comment]
If you feel Armory is not yet useful to you and you are annoyed by bugs please wait for 1.0. For what is working as of now, you can check the tutorial tanks game or the templates. :)

**Comment by FuriouZz** [comment]
Working on fixes here https://github.com/armory3d/iron/issues/53

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/iron/issues/53.
