### ISSUE TITLE
Imported Items Not Showing

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#104]
I've modeled a stormtrooper helmet on another Blender build, but it seems to not render even with the Armory PBR node

![bugarmory_1](https://cloud.githubusercontent.com/assets/15276930/21608715/89d447b4-d1be-11e6-884f-39a5d3647b09.png)
![bugarmory_2](https://cloud.githubusercontent.com/assets/15276930/21608720/8d74ab70-d1be-11e6-8e39-e5d1f1ec4b01.png)

**Comment by luboslenco** [comment]
Heyo,

Is the helmet linked or appended from different blend file? If possible, please attach/send me the blend file, thanks!

**Comment by MagicalPaladin** [comment]
The Helmet is appended, here is the file 
http://pasteall.org/blend/index.php?id=44905

**Comment by luboslenco** [comment]
Dammit, seems to work here. Can you try clicking:
*Properties - Render panel - Armory Build - Clean - Clean Project*

If that helps then something got wrong with the cache.

**Comment by MagicalPaladin** [comment]
Work great thanks !
