### ISSUE TITLE
Bug - object is multiplied When I just set "active" in the physics settings and compile

### ISSUE THREAD

**Issue by EtsHasade** [armory3d/armory#1044]
#bug

[Bug - multi object.zip](https://github.com/armory3d/armory/files/2677753/Bug.-.multi.object.zip)

 helo.
I just defined the physics of an object as "active". Compiling, And when the game is run, the defined object is multiplied.(For example, instead of a cube falling to the surface, two cubes fall on top of each other, and the top is placed "in the air" above the lower cube).

![image](https://user-images.githubusercontent.com/45859983/49969216-b382b180-ff30-11e8-8ac9-935ba9a279fb.png)

Run on the viewport:
![image](https://user-images.githubusercontent.com/45859983/49969336-fd6b9780-ff30-11e8-833e-6cf6b088ae1e.png)

it happen in all my test file...
I dont know if it Because of my computer or something in the blender setting.

My computer:
ASUS - X556URK
Intel i5-7200U CPU
NVIDIA GEFORCE 930MX
Windows 10 Home

**Comment by BlackGoku36** [comment]
Try clean building

**Comment by EtsHasade** [comment]
thank you. but not work...

**Comment by luboslenco** [comment]
Should be resolved in the 0.6beta build.
