### ISSUE TITLE
Volumetric Lighting not Showing

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#105]
Hi there, do i need i specific lamp or setup to have those lights ? I activated the option in camera properties.
![bug_armory3](https://cloud.githubusercontent.com/assets/15276930/21639876/c11c2d5e-d272-11e6-9cb4-2231701d8563.png)

**Comment by luboslenco** [comment]
Volumetrics still suck as there is no real control over it, but should now show up - simple example:
https://github.com/armory3d/armory_examples/tree/master/lamp_volumetric
