### ISSUE TITLE
setLinearVelocity + gravity created weird additional velocity z

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1052]
I set `body.setLinearVelocity(0.0, 0.0, 0.0);` in `notifyOnUpdate` and object is still falling slowly due gravity.

**Comment by luboslenco** [comment]
Use `body.setLinearFactor(0,0,0)` or `body.disableGravity()` to prevent gravity. (Armory usually maps 1:1 to Bullet with these calls.)

**Comment by trsh** [comment]
Linear factor 0 disables collisions. Will try that other option.

**Comment by luboslenco** [comment]
Not aware of linear factor 0 disabling collisions, can you paste a blend file for that?

**Comment by trsh** [comment]
1) Open first_person template
2) Replace line 

```
body.setLinearVelocity(0.0, 0.0, btvec.z - 1.0);
```
with

```
body.setLinearVelocity(0.0, 0.0, 0.0);
body.setLinearFactor(0.0, 0.0, 0.0);
```
and 

```
body.setLinearVelocity(dir.x, dir.y, btvec.z - 1.0);
```
with
```
body.setLinearVelocity(0.0, 0.0, 0.0);
```

run trough walls.

**Comment by luboslenco** [comment]
Hm you should not be able to move at all with that setup, using `body.setLinearVelocity(0.0, 0.0, 0.0)`.

But yeah, I assume it's something like `body.setLinearVelocity(dir.x, dir.y, 0.0)` which will then run through static objects (expected).

**Comment by trsh** [comment]
@luboslenco exactly. I made a mistake. 

body.setLinearVelocity(dir.x, dir.y, 0.0)

**Comment by trsh** [comment]
@luboslenco not sure why you closed this. Because whenever we will use setlinearvelocity to manipulate physics it will add some value X to gravity fall. What u offered are workarounds and bad in long term.

**Comment by luboslenco** [comment]
All of these functions are direct calls to the bullet physics. It's the actual api bullet exposes.

**Comment by trsh** [comment]
If you sure.. then well then it just pitty. If I had a scene with very low gravity and use get \ set linear velocity, the object would just freeze orsmth due this X.

**Comment by trsh** [comment]
I would double check the lines that actually take data from bullet and draw / transform the mesh. Maybe the issue is there, adding something redundant.

**Comment by trsh** [comment]
Seems like my problem > https://blenderartists.org/t/clearing-resetting-physics/465799
