### ISSUE TITLE
Sequence node repeats output(0), ignoring any others

### ISSUE THREAD

**Issue by robw001** [armory3d/armory#1054]
The Sequence node repeats output(0), it does not use the remainder of outputs.

(https://github.com/armory3d/armory/files/2695734/sequencenodetest.blend.zip)
Armory v0.6 ($Id: 0c89a8133cc6c3bf794a8bb34036788194138061 $), OS: mac, Target: krom, GAPI: opengl, Blender: 2.79 (sub 6)

To reproduce:
With the attached blender file, run the armory player. Keys "a" and "b" are each linked to a sequence node. The "a" key is attached to a node network on the cube, the "b" is similarly attached, but then to the scene. Repeatedly pressing either key results in either "a1" or "b1" being printed, respectively.

Checking the node's [source code](https://github.com/armory3d/armory/blob/master/Sources/armory/logicnode/SequenceNode.hx), it seems hardcoded to only run output(0), not a sequence of all outputs.

[sequencenodetest.blend.zip](https://github.com/armory3d/logic_pack/files/2695716/sequencenodetest.blend.zip)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Thanks, it's back! https://github.com/armory3d/armory/commit/d315945b4faf836e91bd8a1e22f0647fa4728e46
