### ISSUE TITLE
Sound delay issue in Krom build

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#1055]
The sound will sometimes delay for (0~0.5) seconds when I tested the "Paddle Strike" game with Krom:
 [https://github.com/MiloHX/Paddle_Strike](url)
The HTML5 build doesn't have this problem. 
I am not sure it is a Kha problem or caused by Armory, so I put the issue here at Armory first.

**Comment by MiloHX** [comment]
OK not only it is delayed, but also the sounds have higher pitch, potentially caused by speeding up.

**Comment by MiloHX** [comment]
Test today with the newest 0.6 build (15Jan2019), there are sounds output when playing with Krom using F5 (still delayed, but they can be played).
But if I use the exporter to publish a project with Krom build, there is no sound. @luboslenco not sure if it is related to Hashlink build since both Krom and Hashlink build have no sound now.

**Comment by musa0113** [comment]
I have the same problem, but after I compiled the game using 'visual studio' it works perfectly.

**Comment by luboslenco** [comment]
Should be resolved now in ArmorySDK1909. Please download & setup the sdk from scratch from itch.io.
