### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#106]
i try armory5  build in version,addon and failed . win10 gpu1060 6gb. screenshot build in version
![1](https://cloud.githubusercontent.com/assets/23359603/21649936/080a11f2-d2ac-11e6-82cb-014780d1ecb6.png)
![2](https://cloud.githubusercontent.com/assets/23359603/21649937/080da326-d2ac-11e6-8baf-ef7e6745d470.png)
![3](https://cloud.githubusercontent.com/assets/23359603/21649938/081770b8-d2ac-11e6-9137-95f2e21081a7.png)

**Comment by luboslenco** [comment]
Hi,

- In your project folder with .blend, can you locate `project/Sources/Main.hx` file?
- Did this start to happen with Build 5? The usual - could you try moving the SDK to 'C:\Dev' or something like that just to see if there are no path issues?

**Comment by Xristoskr** [comment]
i try all this build failed again

**Comment by luboslenco** [comment]
Did you check the Main.hx file?

**Comment by Xristoskr** [comment]
do you mean this ?
![4](https://cloud.githubusercontent.com/assets/23359603/21749265/1e53941a-d5a4-11e6-99f7-95f611cf5418.png)

**Comment by luboslenco** [comment]
Yeah! If you open the `Sources` directory, can you spot `Main.hx` file there? Also, can you paste contents of file `khafile.js` here?

**Comment by Xristoskr** [comment]
![5](https://cloud.githubusercontent.com/assets/23359603/21749313/04f3e550-d5a5-11e6-8188-89d426d94306.png) you can ipaste content of file khafile.js ?

**Comment by luboslenco** [comment]
Simplest way - .zip your project folder and drag and drop the .zip file to this post. That way I can try to reproduce the issue on my machine.
![](https://cloud.githubusercontent.com/assets/23359603/21749265/1e53941a-d5a4-11e6-99f7-95f611cf5418.png)

**Comment by Xristoskr** [comment]
https://drive.google.com/file/d/0B3hadYdOOg8US3JiN2hfQVdSSGs/view?usp=sharing

**Comment by luboslenco** [comment]
Does the issue persist in Build 6?

**Comment by Xristoskr** [comment]
No some problem again

**Comment by Xristoskr** [comment]
Did you find anything to resolve this issue ?

**Comment by luboslenco** [comment]
Hi,

I tried to replicate the issue. In your project you shared it looks for Armory at `C:/Program Files (x86)/Armory` - do you get this warning message when pressing *Play in Viewport*?

![cp](https://cloud.githubusercontent.com/assets/3685704/22176562/bb070c10-e00d-11e6-8b28-222a1639d920.jpg)

There must be some silly path bug in Armory which prevents it to locate *Main.hx* file (which is there as you posted). Anything suspicious in add-on preferences? Is *Bundled SDK* checked?

![b2](https://cloud.githubusercontent.com/assets/3685704/22176597/7133861c-e00e-11e6-8050-a55f1d28d76d.jpg)

**Comment by Xristoskr** [comment]
no i dont get warning message and i have check  Bundled SDK . BUILD FAILED again

**Comment by luboslenco** [comment]
I need more info about your setup 😕. If your SDK is in `C:/Program Files (x86)/Armory` and your Armory version is '17.01' (build 6) then you need to get that warning message. Or is your SDK somewhere else? If so, where is it? Where is your blend file located? It's a path issue, I need all the paths.

Does it work if you setup Armory as add-on in standard Blender?

**Comment by Xristoskr** [comment]
i had armory in download page i move  C:/Program Files (x86)/Armory an i get this error yo show me 
![6](https://cloud.githubusercontent.com/assets/23359603/22177401/56b0c842-e025-11e6-8e11-1bd2e71b0e8f.png)

**Comment by luboslenco** [comment]
Aha, I though it was there already. Alright, bear with me and let's try one more thing:
- Create 'C:\Dev' directory
- Move SDK to 'C:\Dev\Armory'
- Important step: Launch Blender and save new blend file to 'C:\Dev\test\untitled.blend', press *Play in Viewport*

Do not place any characters apart from A-Z in the path. If this still won't work, then it is not a path issue and I will think of what else could cause this.

Thanks for help!

**Comment by Xristoskr** [comment]
ok when you mean move to C:\Dev i cant find Dev in C. can you send me screnshoot with steps ?

**Comment by luboslenco** [comment]
Just create a new directory directly in 'C:' and name it 'Dev'. It's ok you can't find it, make a new one. Let me know if I can make it clearer.

**Comment by Xristoskr** [comment]
i did these steps and blender crash

**Comment by luboslenco** [comment]
No more missing Main.hx file, that is good. Does it work in window now? You can launch in window by pressing Play (shortcut F5) instead of Play in Viewport.

<img width="270" alt="play" src="https://cloud.githubusercontent.com/assets/3685704/22184331/f324a95a-e0cf-11e6-8bd7-874302eb6436.png">

**Comment by Xristoskr** [comment]
we have two things
1) it work with F5
2)IT crash with play viewport

**Comment by luboslenco** [comment]
1. Cool, finally something works!

2. It seems there is a problem with Play in Viewport on new nvidia cards (related issue at https://github.com/armory3d/armory/issues/75). I ordered gtx 1060 to fix this, will report back on Tuesday when the card arrives. :)

As for the previous problem of missing Main.hx file, will fix that too.

**Comment by Xristoskr** [comment]
Did you find what cause this issue ?

**Comment by luboslenco** [comment]
@Xristoskr: I managed to reproduce the crash on my machine using gtx 1060 (hooray). Debugging now - the crash occurs somewhere in nvidia drivers, it's probably unhappy about some opengl calls, will report back.

**Comment by luboslenco** [comment]
I fixed the crash and will package new builds tomorrow or Monday. Keeping the issue open till we test on your machine too, to make sure it's really fixed.

---

For future reference:

Crash
`Unhandled exception at 0x0000000069E8D778 (nvoglv64.dll) in blender.exe: Fatal program exit requested.`

was caused by 

```
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, bufferId);
glBufferData(GL_ELEMENT_ARRAY_BUFFER, myCount * 4, data, GL_STATIC_DRAW);
```

The fix was to unbind the buffer immediately after calling glBufferData.

```
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, bufferId);
glBufferData(GL_ELEMENT_ARRAY_BUFFER, myCount * 4, data, GL_STATIC_DRAW);
glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
```

**Comment by luboslenco** [comment]
@Xristoskr 
Build 7 is out, can you get *Play in Viewport* to work on your machine now?

**Comment by Xristoskr** [comment]
IT WORK
