### ISSUE TITLE
Python API change?

### ISSUE THREAD

**Issue by zaethan** [armory3d/armory#1063]
* It might be that the API for `context.user_preferences` has changed to `context.preferences`.

I built blender from source today and starting the new build reported some errors related to armory on startup. These were about `context` not having an attribute `user_preferences`, so I looked into the installation files and found some occurences of `context.preferences`. Changing all occurences of `context.user_preferences` to `context.preferences` got rid of the errors, so I guess the API changed.

I also found this commit in a blender github mirror:
https://github.com/sobotka/blender/commit/63fcbfc3a7325d79b9e916457d64c302ddfeadfa

**Comment by BlackGoku36** [comment]
Fix at https://github.com/armory3d/armory/pull/1064

**Comment by zaethan** [comment]
Thank you :)
Closing this.
