### ISSUE TITLE
Armory_0.6alpha0 linux ubuntu

### ISSUE THREAD

**Issue by AttSee** [armory3d/armory#1065]
Armory_0.6alpha0 linux ubuntu
When running

Read prefs: /home/attia/.config/blender/2.80/config/userpref.blend
Received X11 Error:
	error code:   179
	request code: 155
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   179
	request code: 155
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   179
	request code: 155
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   179
	request code: 155
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   179
	request code: 155
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   179
	request code: 155
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   8
	request code: 155
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 155
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 155
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 155
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 155
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 155
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
found bundled python: /home/attia/Program/Armory/2.80/python
Armory: Proxy objects synchronized

**Comment by luboslenco** [comment]
Hm, are you able to run Blender 2.8 builds from blender.org without this error?

**Comment by AttSee** [comment]
yab  ...It's bug  from Blender 2.8.
