### ISSUE TITLE
VoxelGI issues

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#1066]
I know 0.6 alpha has lot of error, but here i found one while testing and it crash on start:

```C:\Users\KHIDIR SUTHAR\Downloads\armory_examples-master\armory_examples-master\voxelgi_teapots\build_teapots\debug\temp\Material_voxel.geom.hlsl(27,9-14): error X3004: undeclared identifier 'output'

Compiling shader 20 of 38 (Material_voxel.geom.glsl) failed:
Shader compiler error.
(node:10140) UnhandledPromiseRejectionWarning: Shader compiler error.
(node:10140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
C:\Users\KHIDIR SUTHAR\Downloads\armory_examples-master\armory_examples-master\voxelgi_teapots\build_teapots\debug\temp\Material_voxel.vert.hlsl(25,5-15): error X3004: undeclared identifier 'gl_Position'

Compiling shader 21 of 38 (Material_voxel.vert.glsl) failed:
Shader compiler error.
Finished in 3.096996545791626
Build failed, check console```

It is produced when Voxel GI is selected.

OS: Windows 10 Home
GPU: Radeon Pro 555
CPU: Intel Core i5-74000.

**Comment by BlackGoku36** [comment]
Update:
Browser:
![armvxgib](https://user-images.githubusercontent.com/36535717/51381742-fc82e280-1b3a-11e9-8fcc-02b66debe00e.JPG)
(looks goods, Amazing FPS).
Krom:
![armvgi](https://user-images.githubusercontent.com/36535717/51382124-f7726300-1b3b-11e9-8a22-9913f536da0b.JPG)

**Comment by BlackGoku36** [comment]
https://github.com/armory3d/armory/issues/1146

**Comment by luboslenco** [comment]
Use voxelao instead of voxelgi, gi will be reworked to utilize raytracing instead.

**Comment by mistajuliax** [comment]
Hi @lubos will raytracing use voxel cone tracing like svogi in cryengine or a new implementation like rtx raytracing ?? Did you read this : https://www.cryengine.com/news/how-we-made-neon-noir-ray-traced-reflections-in-cryengine-and-more really interesting interview about neon demo from crytek's raytracing implementation.

**Comment by luboslenco** [comment]
Hey @mistajuliax, thanks for the link! Will be pure raytracing. I started with DXR/D3D12 backend for now but it's not tied to a specific api, will eventually add Vulkan as well. Upcoming amd (+consoles) / intel cards are supposed to have raytracing units so will make decisions based on that to leverage the hardware.

Some related links to under-the-hood implementation:
https://github.com/Kode/Kore/blob/master/Sources/Kore/Graphics5/RayTrace.h
https://github.com/Kode/Kore/blob/master/Backends/Graphics5/Direct3D12/Sources/Kore/RayTraceImpl.cpp
https://github.com/Kode/Kore/blob/master/Backends/Graphics5/Direct3D12/Sources/Kore/RayTraceImpl.h
https://github.com/luboslenco/RayTraceG5-Kore

**Comment by mistajuliax** [comment]
Ok, great i will look at these links, thanks for infos. 
It would be great to have a section in docs on how you implement things and what technique you used, adding reference docs implementation, like gpu gems, gpu pro, or whatever docs, books, articles inspired you to implement things. :)

**Comment by luboslenco** [comment]
Opened a new issue to take care of that https://github.com/armory3d/armory/issues/1268. :)

**Comment by mistajuliax** [comment]
Hi lubos, me again ! Did you see that ? : https://morgan3d.github.io/articles/2019-04-01-ddgi/
https://morgan3d.github.io/articles/2019-04-01-ddgi/intro-to-gi.html
https://morgan3d.github.io/articles/2019-04-01-ddgi/overview.html#citation-archard19
Keep the good develop ! 

Best regards
