### ISSUE TITLE
Comma key (,) and full stop key (.) has no effect

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#1067]
If try to check the comma key (,) and full stop key (.) with keyboard.started() function, they will not have true value returned.

**Comment by nanjizal** [comment]
MiloHX you can implement your own:

kha.input.Keyboard.get().notify( function( keyCode: Int ): Void {
switch( keyCode ){
case '.'.code:
trace('dot down');
case ','.code:
trace('comma down');
_:
trace('keyCode not used ' + keyCode );
}
, null, null );

**Comment by MiloHX** [comment]
@BlackGoku36 I think they are supposed to be supported, they are listed in the keys array in class Keyboard:
https://github.com/armory3d/iron/blob/master/Sources/iron/system/Input.hx

@nanjizal I tested your code, it doesn't work. So maybe kha doesn't support them? then maybe I just avoid to use them for now.

**Comment by MiloHX** [comment]
As discussed with @BlackGoku36 , the reset() method is impacted by the first fix. He have been send another pull request to address this issue!

**Comment by BlackGoku36** [comment]
fix at https://github.com/armory3d/iron/pull/58

**Comment by MiloHX** [comment]
It is OK now!
