### ISSUE TITLE
Adding node traits, to an object does not succeed in building a preview project

### ISSUE THREAD

**Issue by haizhou37** [armory3d/armory#1074]
**Version:**
Armory_06alpha0_linux64

**OS/device including version:**
manjaro gnome x64
Intel® Core™ i3-2350M CPU @ 2.30GHz × 4
Intel® Sandybridge Mobile
OpenGL ES 3.0 Renderer: Mesa DRI Intel(R) Sandybridge Mobile
intel hd 3000

**Issue description:**
![2018-12-30 20-40-22](https://user-images.githubusercontent.com/33272474/50547424-159f1e80-0c74-11e9-8ea1-c7baa16ba6e2.png)
![2018-12-30 20-39-46](https://user-images.githubusercontent.com/33272474/50547426-1afc6900-0c74-11e9-9462-16a451111e64.png)
![2018-12-30 20-40-34](https://user-images.githubusercontent.com/33272474/50547419-0ddf7a00-0c74-11e9-9ad8-39423a069905.png)

**Minimal reproduction project:**
[ArmoryTest.zip](https://github.com/armory3d/armory/files/2717138/ArmoryTest.zip)

#1059

**Comment by montedre** [comment]
this is caused by the fake user attribute.  For some reason Armory is reading the attribution F as part of the name.  Remove the fake user and it will probably work.

**Comment by haizhou37** [comment]
#1059

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armory/issues/1059. Thanks for report!
