### ISSUE TITLE
Weird thing with the sky texture

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armory#1075]
Hi! I have a Problem with the sky texture. When the sky texture node is connected everything works but when i set the daytime or light whatever to night it looks very weird.

**Comment by BlackGoku36** [comment]
Can you post pic of this wierd look?

**Comment by Noahthenoob53** [comment]
Here = 
![1](https://user-images.githubusercontent.com/41879104/50572718-8fdfb800-0dc6-11e9-9caa-d15abe1f111d.PNG)
![2](https://user-images.githubusercontent.com/41879104/50572719-94a46c00-0dc6-11e9-84d9-a17c735a2279.PNG)
![3](https://user-images.githubusercontent.com/41879104/50572720-9706c600-0dc6-11e9-8cbd-7684c52d872d.PNG)

**Comment by luboslenco** [comment]
Patched in https://github.com/armory3d/iron/commit/ea82c61e20e8ee029190479be1e54067c1db68fc, https://github.com/armory3d/armory/commit/3c25095c941092cf8348bb770d2ccbbac08fa7ca. Should be less weird now, thanks!
