### ISSUE TITLE
Cannot build games after the latest update (0.6 alpha)

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#1081]
After the latest update, games are failed to build:
![image](https://user-images.githubusercontent.com/17811339/50719632-3c2ce180-10da-11e9-91b6-638c0fe40c15.png)

**Comment by luboslenco** [comment]
Did some upgrading in new 0.6beta build, let's see if it holds up now.

**Comment by MiloHX** [comment]
Tested OK for me.

**Comment by MiloHX** [comment]
it works now, so I will close this one, feel free to reopen if someone report the same issue.
