### ISSUE TITLE
At some compositions Area lights are completely wrong

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1082]
[untitled.zip](https://github.com/armory3d/armory/files/2729394/untitled.zip)

Aprox expected:

![3](https://user-images.githubusercontent.com/3727523/50723088-93828000-10e1-11e9-9004-4ef1b61f8526.png)

Result:

![2](https://user-images.githubusercontent.com/3727523/50723092-9e3d1500-10e1-11e9-804e-4632098e0864.png)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/624.

**Comment by trsh** [comment]
Thank you

**Comment by trsh** [comment]
As with 0.6b area lights don't work at all.
