### ISSUE TITLE
RigidBodies with Linear/Angular factor 0 influences other dynamic bodies

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1085]
[untiled.zip](https://github.com/armory3d/armory/files/2730505/untiled.zip)

In console one can see 3.0 shifted to 3.000000476837158. 
Small amount, but when the objects locations are dependent int logic, it can go into recursion.

Ubuntu 18.x, Armory 0.5

**Comment by luboslenco** [comment]
Sounds like a bullet 'issue' coupled with floating point precision. To stay safe do not use 'int logic' on floats.

**Comment by trsh** [comment]
I think 'trigger' check solved my issue. Anyways I think this will come back to you sooner or later as it doesn't seem to be what u suspect. Because when the coordinated don't collide, there is no imprecision in float.

**Comment by luboslenco** [comment]
Sorry I am not sure I follow. Do not compare floats directly. Can you post a code snippet that is causing you trouble?

**Comment by trsh** [comment]
NM, i cant get a stable reproduce of issue. So If i do some day, will file new issue. Thank you.
