### ISSUE TITLE
[SOLVED] Tilesheet nodes not working (v 0.5)

### ISSUE THREAD

**Issue by Awesomeplayer** [armory3d/armory#1087]
*(drag & drop zipped .blend file here)*
![image](https://user-images.githubusercontent.com/22584533/50760989-72619100-1293-11e9-9cda-df20cb3517a4.png)
![image](https://user-images.githubusercontent.com/22584533/50761001-7b526280-1293-11e9-998f-4f65a1224d99.png)

Tried everything the examples did incase of node setups, the tilesheet animation doesnt play

**Comment by Awesomeplayer** [comment]
![image](https://user-images.githubusercontent.com/22584533/50761060-a046d580-1293-11e9-8b7e-0ebf792a487c.png)
here take a look

**Comment by luboslenco** [comment]
Maybe the issue is that UVs are not adjusted to single tile, ie.:
![capture](https://user-images.githubusercontent.com/3685704/51072928-aceb7500-1669-11e9-97d6-8c4cf91ea215.PNG)

(from example https://github.com/armory3d/armory_examples/tree/master/tilesheet)

**Comment by Awesomeplayer** [comment]
How do you perfectly align the uv to match a tile?

**Comment by luboslenco** [comment]
What seemed to work for me is to place the cursor in the top-left corner and scale by (1 / number of tiles), with scaling pivot set to 2D cursor. You should also be able to select the vertices and do 'snap selection - pixels'. Hope that helps a little.

![capture](https://user-images.githubusercontent.com/3685704/51136786-a31a6b00-183d-11e9-9e09-bb82110eab81.PNG)

**Comment by Awesomeplayer** [comment]
![image](https://user-images.githubusercontent.com/22584533/51174977-4d989980-18e3-11e9-9847-09aee9be3861.png)

well it just sits there, doing nothing. is it something with the node setup? 
![image](https://user-images.githubusercontent.com/22584533/51175135-a9632280-18e3-11e9-9899-b17ad92360db.png)
![image](https://user-images.githubusercontent.com/22584533/51175157-b253f400-18e3-11e9-95de-67fcdbbf6108.png)

**Comment by luboslenco** [comment]
Sorry I am unable to tell what is wrong from the pictures, please paste the blend file if possible. Did the [tilesheet](https://github.com/armory3d/armory_examples/tree/master/tilesheet) example work for you? Maybe there is a bug?

**Comment by Awesomeplayer** [comment]
yes the tilesheet example (the one with the penguin) works as intended, I even added nodes to test it there myself and works as it should. its just that anything out of the examples dont work, theres also an example (one out of the three animated texture examples) that doesnt work. Its called tilesheet2d (this one ↘)
![image](https://user-images.githubusercontent.com/22584533/51175932-d57fa300-18e5-11e9-910d-64e6a2784e1c.png)

**Comment by Awesomeplayer** [comment]
here's the blend link 
http://pasteall.org/blend/index.php?id=51044

**Comment by Awesomeplayer** [comment]
oops forgot to pack textures wait

**Comment by Awesomeplayer** [comment]
http://pasteall.org/blend/index.php?id=51045
here

**Comment by Awesomeplayer** [comment]
Thanks, well I think I know the issue source, I forgot to turn on Tilesheet in the materials tab, didnt know there was a button like that. 
![image](https://user-images.githubusercontent.com/22584533/51243966-14792b80-19ae-11e9-8874-39f74b8be890.png)

**Comment by Awesomeplayer** [comment]
and voila
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22584533/51244308-f65ffb00-19ae-11e9-95ad-5b071a380de2.gif)

**Comment by luboslenco** [comment]
I have removed the `Material - Tilesheet` option in https://github.com/armory3d/armory/commit/c81d4949ca9e41647bad7a1d8906c01dc40f536b, it will now work out the box, no need to enable anything for the material. Thanks for report!
