### ISSUE TITLE
Crash using a jpg environnement texture in world tab

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#109]
![blenderarmory_bugsky](https://cloud.githubusercontent.com/assets/15276930/21776480/0bcfc2b2-d69b-11e6-81a1-efd73ee06cf2.png)

**Comment by zauberparacelsus** [comment]
Is this using the Armory packaged in Build 5, or are you using Armory from git?  I ask because on Build 5, I was able to use a JPG environment texture without crashing ([but not entirely without issue](https://github.com/armory3d/armory/issues/100)).

**Comment by MagicalPaladin** [comment]
Build 5

**Comment by luboslenco** [comment]
Should now be fixed, please reopen if issue persist.
