### ISSUE TITLE
build from source code using visual studio

### ISSUE THREAD

**Issue by mikrokode** [armory3d/armory#1093]
Hi,

I am new to python, may i know how to build and compile the engine source code using visual studio 2017?

KT Wong

**Comment by luboslenco** [comment]
Hello, all you need is to clone the repositories. Please check out the manual here: https://armory3d.org/manual/#/dev/gitversion.

Additional info: https://armory3d.org/manual/#/essentials/krom

**Comment by mikrokode** [comment]
Hi,

the page only show us how to plugin the SDK into blender, but how can i compile, build, run and debug the full engine source code? I expect to learn your engine from start to end, but just for fun, without commercial purpose. Can you show me the ways?

KT Wong

**Comment by luboslenco** [comment]
You don't 'compile' the engine sources, check the explanation at:
https://armory3d.org/manual/#/essentials/krom

> When you clone Armory from git, there is no need to build anything. The engine is compiled alongside the game into JS instantly as you press the Play button.

You only compile in Visual Studio after exporting the game using the native/C++ backend:
https://armory3d.org/manual/#/platforms/windows?id=native-c

You can freely use Armory for commercial purposes, no restriction there.
