### ISSUE TITLE
Kore fetching error 

### ISSUE THREAD

**Issue by Redfill** [armory3d/armory#1096]
when updating armory using the update button, I get an error when it's trying to fetch Kore

Cloning into '/Armory/armsdk/Kha/Tools/oggenc'...
remote: Enumerating objects: 7, done.        
remote: Counting objects: 100% (7/7), done.        
remote: Compressing objects: 100% (7/7), done.        
remote: Total 7 (delta 0), reused 6 (delta 0), pack-reused 0        
Submodule path 'Backends/Kore/khacpp': checked out 'cc0097dd4822f75c707b6e87e6acfec68bcf38d1'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: Server does not allow request for unadvertised object b950cdaacb9f845d98980fb1398b1f3f70f9e55a
Fetched in submodule path 'Kore', but it did not contain b950cdaacb9f845d98980fb1398b1f3f70f9e55a. Direct fetching of that commit failed.

**Comment by luboslenco** [comment]
Did some upgrading in new 0.6beta build, let's see if it holds up now.

Link to https://github.com/armory3d/armory/issues/1081.
