### ISSUE TITLE
Get Group Node doesn't work - 2.8

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#1097]
I believe due to 2.8 changing how groups work as they are now collections, the get group node no longer 
works.

![image](https://user-images.githubusercontent.com/5720489/51079114-90772900-16b9-11e9-8008-1e86e3e6bfa2.png)

![image](https://user-images.githubusercontent.com/5720489/51079106-6e7da680-16b9-11e9-8057-b724bc75e284.png)

This probably now needs to look for collections. Correct me if I am wrong or missing how this should function now.

Blender 2.8 - 0.6 Latest sdk

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Did some fixing, it should work with collections now.  `Get Group` node is newly labeled as `Get Collection`. Thanks for report!
