### ISSUE TITLE
Rigid body effects another body it should not by settings

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1099]
So part #2

[ex.zip](https://github.com/armory3d/armory/files/2754614/ex.zip)

The trigger thing not so important as `oRB.setLinearFactor(0, 0, 0);`

**Comment by luboslenco** [comment]
Sorry I am not sure what this means, the included `MyTrait` doesn't seem to be attached to anything.

`.setLinearFactor()` is a direct call to bullet engine, maybe it's the way bullet behaves.

**Comment by trsh** [comment]
@luboslenco attach it to "Cube.001" and wait to secs. No idea how it got lost :/

**Comment by trsh** [comment]
This is workaround im using now, but it will not do in all cases:

```
var rb = new RigidBody(1.0, Shape.Box);
					rb.trigger = true;

					object.addTrait(rb);
					var oRB = object.getTrait(RigidBody);
					
					oRB.syncTransform();
					oRB.setLinearFactor(0, 0, 0);
					oRB.setAngularFactor(0, 0, 0);
					oRB.disableGravity();
					oRB.setLinearVelocity(0, 0, 0);
					oRB.activate();

					rb.trigger = false;
```

**Comment by luboslenco** [comment]
Rigid body construction parameters need to be passed into constructor, see here:
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/physics/bullet/RigidBody.hx#L79

**Comment by trsh** [comment]
Heh! Ok
