### ISSUE TITLE
Interior Mapping

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#11]
One rendering feature that the game Watchdogs featured, is that it could render indoor areas behind windows without any actual geometry, instead using a pixel shader to fake the geometry.

This blog post on the Unreal Engine forums highlights the technique: https://forums.unrealengine.com/showthread.php?7444-Watch-Dogs-style-Interior-Mapping-material

**Comment by adriansnetlis** [comment]
If you can do it in UE4 than you can also do it in Armory as they're both using node-based render system with user control over it. In fact, from what I've seen, Armory features even greater control over rendering system:)

**Comment by JeannotLandry** [comment]
That would be awesome :) That could really help when making real time architectural walk-through!

**Comment by luboslenco** [comment]
Started with some [renderpath](https://github.com/armory3d/armory_docs/blob/master/dev/renderpath.md) docs, coupled with material nodes it should be possible to roll this as a stand-alone add-on.
