### ISSUE TITLE
Tessalleted displacement not showing/rendering

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#110]
![bug_armory4](https://cloud.githubusercontent.com/assets/15276930/21782655/71f0596c-d6b4-11e6-9432-e792816979c5.png)

**Comment by luboslenco** [comment]
Is the quad subdivided a little? (otherwise there may be not enough geometry to operate.) Please throw in blend file or zipped project with assets, that way I can fix stuff way faster:) (also for other issues). Thanks!

**Comment by MagicalPaladin** [comment]
[test2.zip](https://github.com/armory3d/armory/files/695611/test2.zip)
here it is

**Comment by luboslenco** [comment]
Found some possible issues:
- Mesh has to be unwrapped if texture is used for displacement (provided blend is missing this but your original is apparently unwrapped)
- Mesh has to be subdivided a little as mentioned before
- HTML5 & Electron do not support tessellation, adding a warning for this to console output

After unwrapping the mesh and switching to Krom I got your test file to work. One caveat is that normal map is still required, as only positions are displaced.

**Comment by MagicalPaladin** [comment]
Alright, i'll try that
