### ISSUE TITLE
code-complete plugin-in made Armory3D restart immediately

### ISSUE THREAD

**Issue by grants** [armory3d/armory#1102]
I am using a code-complete plugin which repo is https://github.com/JacquesLucke/code_autocomplete

When I start this plugin with jedi support, Armory3D will open a new window and repeat this action when I type every single letter.

Is this a bug I should put here? Thx

**Comment by luboslenco** [comment]
Do you mean a new Blender instance opens up? Which Armory version are you on? Same on `0.6 beta`? (Sorry no experience with `code_autocomplete` plugin yet.)

**Comment by grants** [comment]
yes, new Blender instance opened up and show me another blender window. If I keep typing in the text editor (keep the auto-completion plugin opened), another Blender window would show up, repeat and repeat. I'm using Armory_05_linux64_b27 version. I will try 0.6 beta and post the result later.

**Comment by luboslenco** [comment]
Should be ok in 0.6, as it's using a regular Blender build.
