### ISSUE TITLE
[Featuere] Export Blender Custom Properties

### ISSUE THREAD

**Issue by zicklag** [armory3d/armory#1104]
It would be great if Blender Custom properties could be exported as object properties in the Armory game. For example if I add a life property to an object and set it to 100. The "Life" property of that object in blender should be set to 100 when the game starts.

![image](https://user-images.githubusercontent.com/25393315/51345434-96299180-1a60-11e9-91eb-23584d52a677.png)

I'm not sure when exactly I might get the time, but this is probably something that I could manage, I just wanted to create the issue to make sure that it doesn't get forgotten.

**Comment by luboslenco** [comment]
Yeah! In 0.6 there is  `Object - Armory Props - Properties` list, but I would also love to reuse existing panels instead. I am only concerned that `Custom Properties` also contains other 'junk'.:/

**Comment by zicklag** [comment]
Oh, yeah, I forgot about the Armory property panel. I've seen it before, I just hadn't used it, then I forgot about it when I needed it. I just looked at the Blender property panel and it only lets you set float values, and it does have more "junk" in it. Keeping the Armory one is probably nicer.

**Comment by zicklag** [comment]
Going to close this, as I'm pretty sure that Blender properties won't work for anything but floats and we already have a panel that does what we need. You can re-open it if you think it is still worth pursuing.

**Comment by luboslenco** [comment]
Storing this as a future reference if we get back to it -  Whoa, I accidentally found out that you can change the type if you click `Edit` and enter a string/int value into `Property Value`.
![capture](https://user-images.githubusercontent.com/3685704/51410564-526c8000-1b65-11e9-99b1-7448df6fcf04.PNG)

**Comment by zicklag** [comment]
Whoa that's weird. Maybe it could work then.
