### ISSUE TITLE
0.6 beta - GL Error 1282 on Linux

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1106]
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:44: characters 1-8 : Duplicate class field declaration : font_default
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:46: lines 46-54 : Defined in this class
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:44: characters 1-8 : Duplicate class field declaration : font_defaultName
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:46: lines 46-54 : Defined in this class
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:44: characters 1-8 : Duplicate class field declaration : font_defaultDescription
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:46: lines 46-54 : Defined in this class
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:44: characters 1-8 : Duplicate class field declaration : font_defaultLoad
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:46: lines 46-54 : Defined in this class
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:44: characters 1-8 : Duplicate class field declaration : font_defaultUnload
/home/trsh/Downloads/Armory/armsdk/Kha/Sources/kha/Assets.hx:46: lines 46-54 : Defined in this class

**Comment by trsh** [comment]
Project cleaned, SDK updated

**Comment by luboslenco** [comment]
Please paste the project when possible. Does default cube blend work?

Maybe you copied the `armsdk/armory/Assets/font_default.ttf` file into your project, causing a duplicate include? Maybe there is a bug caused by some build flags combination? It's hard to tell without inspecting the project. You could check the generated `khafile.js` to see where those multiple `font_default.ttf` come from.

**Comment by trsh** [comment]
@luboslenco i did not copy, but it was in `bundled`

Now its this

`GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 638`

And lightning broken

**Comment by trsh** [comment]
Examples: light_ies & light_area broken in Linux!

**Comment by luboslenco** [comment]
The examples in the `_` folder are not yet updated to 0.6beta. Other examples should work. And yes I did test on my Manjaro box like I always do. Even the `voxelgi_teapots` example works for me. There is simply too many configurations for me to test on myself.

**Comment by trsh** [comment]
Anyway `animation` example doesn't work on Ubuntu. `GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 638`. Milo is also doing tests. He will report.

**Comment by luboslenco** [comment]
@BlackGoku36 try using a 'safe' path without the `(` and `)` characters.

**Comment by trsh** [comment]
Linux seems to ignore sky radiance PB reflections.

**Comment by luboslenco** [comment]
@BlackGoku36  What do you mean by 'not windows'? What is your OS and GPU there? Is Voxel GI enabled in your .blend file? Are you using the latest [armory_examples](https://github.com/armory3d/armory_examples) for 0.6?

**Comment by BlackGoku36** [comment]
Ah i am sorry a typo, i meant to write `not linux`

**Comment by trsh** [comment]
@luboslenco sure u can see difference between windows KROM and Linux KROM? (The pic above and my screenshot). Playing with lights will not help there :P.  So its an elated issue.

**Comment by luboslenco** [comment]
@trsh I get the same result on both Linux and Windows.
@BlackGoku36 use `New Folder` instead of `New Folder(3)`.

I created a new issue for the `GL Error 1282` at https://github.com/armory3d/armory/issues/1107.
Redirecting this to the forums now as we are cluttering the tracker here and I am a bit lost. We can then open concrete bug reports here.

**Comment by trsh** [comment]
@luboslenco what same results? There are two. I have one more people on Linux reporting it looks like mine.

**Comment by luboslenco** [comment]
I commented on your original pic with `that is how the example looks.` :)

**Comment by trsh** [comment]
Ok, so Goku is wonder child :D
