### ISSUE TITLE
GL Error 1282/1286  on Linux and macOS - 0.6 beta

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#1107]
Investigate `GL Error 1282 ../../Kore/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 638`

**Comment by BlackGoku36** [comment]
not an linux issue only
Its compile on macOS but give this similar error
``GL Error 1286 ../../Krom/Kore/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 284``
BTW why isn't there Metal graphics api option for macOS?

**Comment by luboslenco** [comment]
I think all of the examples will give you that error but voxels in particular will not work on macOS because opengl support is crippled there and now deprecated.

Metal api is present in the exporter only for now. It's wip. Use https://github.com/luboslenco/kha3d_examples if you want to play with that, I think it should already run ok there on Metal.

**Comment by BlackGoku36** [comment]
Actually VoxelGI runs really well on MacOS and gives 60fps in krom and look like windows's VoxelGI but faster and better.
So, metal is WIP for iron too?

**Comment by luboslenco** [comment]
> look like windows's VoxelGI but faster and better

That can't be true because voxelgi is automatically [disabled on macOS](https://github.com/armory3d/armory/blob/master/blender/arm/utils.py#L439) to prevent errors.

All Metal code is contained in Kore, here:
https://github.com/Kode/Kore/tree/master/Backends/Graphics5/Metal/Sources/Kore

But please lets stay on the `GL Error 1282` here.:)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/848.
