### ISSUE TITLE
Scene created in 0.5 broken in 0.6

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1108]
![broke](https://user-images.githubusercontent.com/3727523/51385551-4ca47980-1b28-11e9-89fb-e15e5289aeb4.png)

a) Textures scale out of wreck (ground etc.)
b) Area lights completely gone
c) Identical meshes, 1 ok, 2 broken in triangles

I granted access for `lubos@armory3d.org` in https://gitlab.com/game-new-beginnings-group/test-lab/tree/dev .

[no spoiling/leaking please for now]

**Comment by luboslenco** [comment]
Please export the broken meshes and mail me at `lubos@armory3d.org` if you do not wish to share here. (Sorry I would prefer to not enter confidential repos without some kind of agreement, to prevent the risk.)

**Comment by trsh** [comment]
Sent!
