### ISSUE TITLE
[Q] About lightning in 0.6

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1109]
I know this is not right place to ask questions (at same time only where can get answers like this), but as Area lights are off in 0.6, should we create feature request (get votes) to reanimate them, or its WIP, or bug or something else? Im confused

**Comment by luboslenco** [comment]
> I know this is not right place to ask questions (at same time only where can get answers like this)

I don't get this nagging from you, now coming basically non-stop.. You know we run forums for this, I am answering there whenever I can:
http://forums.armory3d.org/

0.6 is in beta, it's not a final release.

**Comment by trsh** [comment]
Expect stuff like this, if you use https://en.wikipedia.org/wiki/Perpetual_beta 'banana principle'. Normally people refer to Beta as a Software that has full functionality, but with bugs -https://en.wikipedia.org/wiki/Software_release_life_cycle.  

"Beta phase generally begins when the software is feature complete but likely to contain a number of known or unknown bugs".

If you have your own version Logic, you should document it orsmth, but is not good path to go.

**Comment by luboslenco** [comment]
Broken area lamps is a bug that I will fix in the final release.

Stop with your endless wars this is beyond insane now. It is not even fun anymore. I do not know what happend to you but I kindly ask you to stop.

**Comment by trsh** [comment]
> Broken area lamps is a bug that I will fix in the final release.

Aleluja :) . Deal!
