### ISSUE TITLE
Safari Won't Compile Shader

### ISSUE THREAD

**Issue by Mephphisto** [armory3d/armory#1113]
This error occurs with all my projects and even the Demos (https://armory3d.org/download.html).
Safari Error:
[Error] WebGL: ERROR: unsupported shader version
	compileShader
	compileShader (kha.js:34094)
	compile (kha.js:34028)
	initShaders (kha.js:32303)
	kha_graphics4_ImageShaderPainter (kha.js:32290)
	kha_graphics4_Graphics2 (kha.js:33091)
	kha_js_graphics4_Graphics2 (kha.js:37022)
	loadFinished (kha.js:22149:110)
	init2 (kha.js:22041)
	initSecondStep (kha.js:21875)
	init (kha.js:21872)
	start (kha.js:21671)
	start (kha.js:706)
	main (kha.js:719)
	main (kha.js:114)
	(anonyme Funktion) (kha.js:38877)
	Globaler Code (kha.js:38878)
[Error] Error: Could not compile shader:
ERROR: unsupported shader version

	compileShader (kha.js:34096:105)
	compile (kha.js:34028)
	initShaders (kha.js:32303)
	kha_graphics4_ImageShaderPainter (kha.js:32290)
	kha_graphics4_Graphics2 (kha.js:33091)
	kha_js_graphics4_Graphics2 (kha.js:37022)
	loadFinished (kha.js:22149:110)
	init2 (kha.js:22041)
	initSecondStep (kha.js:21875)
	init (kha.js:21872)
	start (kha.js:21671)
	start (kha.js:706)
	main (kha.js:719)
	main (kha.js:114)
	(anonyme Funktion) (kha.js:38877)
	Globaler Code (kha.js:38878)

**Comment by BlackGoku36** [comment]
Well, apparently Apple dropped OpenGL support on their devices, and adopted Metal Api completely.
and Metal support is WIP in armory

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armory/commit/44c8cdb679aa2df8f5d736ee58d2218549ad22a9. `Blender Preferences - Add-ons - Armory - Legacy Shaders` and mobile render path should be enabled to handle browsers which are not WebGL2 capable.

OpenGL being deprecated does not (yet) affect WebGL.

**Comment by Mephphisto** [comment]
First of all Thanks!
However, I still don't seem to be able to get it to run.
Here is what I did:
1st Blender Blender Preferences - Add-ons - Armory - Update SDK
2nd Restart Blender
3rd Save the start scene (cube with light and camera)
4th  Preferences - Add-ons - Armory - Legacy Shaders
5th Armory Render Path Mobile 
6th Armory Player - Runtime Browser -> Play

[Error] WebGL: ERROR: unsupported shader version
	compileShader
	compileShader (kha.js:33609)
	compile (kha.js:33543)
	finishCompile (kha.js:5736)
	(anonyme Funktion) (kha.js:5713)
	(anonyme Funktion) (kha.js:4476)
	onreadystatechange (kha.js:20381)
[Error] Error: Could not compile shader:
ERROR: unsupported shader version

	compileShader (kha.js:33611:105)
	compile (kha.js:33543)
	finishCompile (kha.js:5736)
	(anonyme Funktion) (kha.js:5713)
	(anonyme Funktion) (kha.js:4476)
	onreadystatechange (kha.js:20381)
[Error] WebGL: ERROR: unsupported shader version
	compileShader
	compileShader (kha.js:33609)
	compile (kha.js:33543)
	finishCompile (kha.js:5736)
	(anonyme Funktion) (kha.js:5713)
	(anonyme Funktion) (kha.js:4476)
	onreadystatechange (kha.js:20381)
[Error] Error: Could not compile shader:
ERROR: unsupported shader version

	compileShader (kha.js:33611:105)
	compile (kha.js:33543)
	finishCompile (kha.js:5736)
	(anonyme Funktion) (kha.js:5713)
	(anonyme Funktion) (kha.js:4476)
	onreadystatechange (kha.js:20381)

**Comment by luboslenco** [comment]
Argh, fixed one more [issue](https://github.com/armory3d/iron/commit/ebf2e819d10161d4a5b3267f2861a296454836d0), sorry and thanks for letting me know. Would you mind giving it one more try? (same steps should work now)

**Comment by Mephphisto** [comment]
Wow that did it! thanks so much!
