### ISSUE TITLE
movie texture FFMPEG Path

### ISSUE THREAD

**Issue by tachikaS** [armory3d/armory#1114]
Hello there,
i‘m new with armory, so I’m sorry if this is a stupid question but i hope to get help here after spending some time fixing this problem on my own. I wanted to try a movie texture like shown in this example: https://www.youtube.com/watch?v=tgJogOYtLF0. So I used a simple plane and used a mp4 movie clip as input for the base color. I also installed FFMPEG correctly and tried to specify the path in the preferences. But every time I want to render it in Armory the console shows an issue when exporting the mp4. It says “Video file could not be exported, you have to specify a path to ffmpeg.”
I tried many paths now, for example: “C:\ffmpeg4\ffmpeg” , “C:\ffmpeg4\ffmpeg\bin”, “C:\ffmpeg4\ffmpeg\bin\ffmpeg.exe”, but nothing worked. I tried this on Armory 0.5 and 0.6 beta and got the same issue. I think I do something
 wrong but I don’t know what it is.

**Comment by stanleytf** [comment]
hey did you figure out the answer, i am struggling with this too.
