### ISSUE TITLE
[FR] Make render path extendable

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1116]
So basically if i want my render path a bit different from original, I still have to copy-paste stuff like just in https://github.com/armory3d/driver_celshade/blob/master/Sources/celshade/renderpath/RenderPathCreator.hx. That's kind of non productive, because:

1) Repeating code
2) If I want to align with new stuff in Armory, I have to keep everything up to date (manually)
3) I lose Forward and Deffered path switch?

Instead the long blocks, it could be split into sub function, by thema, so it looks like:

```
commands(){
  thisOnlyForDefferedEmptyInForward()
  drawmesh()
  dothis()
  dothat()
  hereIPutMyThing()
  aa()
  etc
}
```

Also some base class could be created to collect indetical blocks like:

```
#if (rp_supersampling == 4)
			{
				var finalTarget = "";
				path.setTarget(finalTarget);
				path.bindTarget(framebuffer, "tex");
				path.drawShader("shader_datas/supersample_resolve/supersample_resolve");
			}
			#end
```

This way its easier to extend the RP, and keep it up to date with core changes.

**Comment by luboslenco** [comment]
Don't want to fragment the render path code at this time because that would result in dependency hell. This way when Armory render path changes, separate path like driver_celshade can continue to function.
driver_celshade is only 368 lines for the whole path. Right now all of the shader invocations can be viewed at single place which is handy for optimization.

**Comment by trsh** [comment]
> dependency hell

Interesting. Can u explain a but or give example?

> This way when Armory render path changes, separate path like driver_celshade can continue to function. 

But raw implementation like `driver_celshade` will continue to function in any case. Ppl can still write/use such thing after `fragment`. Ppl still have choice to copy paste :)

> Right now all of the shader invocations can be viewed at single place which is handy for optimization

Hmm.. I dont think one big function is much more of an overview, that separate functions (for me it just creates headaches as an big OOP veteran), but that's highly subjective and as you work mostly on it, I  respect that

I just want to add some render stuff right before AA, and Im require then to copy all over, what will make me dependent on constantly manually updating my code (for example when u do some optimizing).

Maybe something even smarter can be done. Like some macro invocations. Duno. I will try to think a bit more on this, maybe we can find a compromise. Thank you.

**Comment by trsh** [comment]
I will adopt what Im up to for my project (change those core classes), and the let you take a look. Maybe u will like it after all, and we are here misunderstanding each other ;)
