### ISSUE TITLE
[FR] Make contextEvents available also for non debug builds

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1118]
Drop `if` here

```
#if arm_debug
		// Callbacks to specific context
		if (contextEvents != null) {
			var ar = contextEvents.get(context);
			if (ar != null) for (i in 0...ar.length) ar[i](g, i, ar.length);
		}
		#end
```

And lover by `notifyOnContext`

Ppl will still have `#if arm_debug` in traits using this, so nothing will be broken. And we can inject some custom rendering similar to debug lines for production use.

**Comment by luboslenco** [comment]
The `#if arm_debug` guard is there on purpose. It's intended only for debug because there will not be any sort of culling when drawing this way.
