### ISSUE TITLE
Black screen on android, Armory 0.6b

### ISSUE THREAD

**Issue by html** [armory3d/armory#1121]
I'm building app using latest Armory3d version from repository.
When I run any app on Android 8.1.0 (phone TA-1047) it shows only black screen.

I've debugged it and Armory3d fails to show materials properly.

I've made app and manually loaded mesh with material into app.
And it worked, mesh did show.

So problem is either in exporting or displaying blender materials.

**Comment by html** [comment]
I'm debugging case and more accurate reason is shaders.
Setting proper shaders for material makes object visible.
Default shaders don't work.

**Comment by zicklag** [comment]
Did you try adding a Mobile render path preset:

http://forums.armory3d.org/t/apk-compiling-for-android-armory06-beta-win64/2506/2?u=zicklag

**Comment by html** [comment]
Thanks that makes things little better, but cube has really bad form and color
![screenshot_20190127-180036](https://user-images.githubusercontent.com/112117/51803488-651a3f80-225e-11e9-9192-4d2c4a9cfe86.png)

**Comment by html** [comment]
Found workaround to render app on android. It renders not in the best way but shows meshes and colors properly.

```
// Imports needed
import iron.RenderPath;
import armory.renderpath.Inc;

// Put this inside some trait to run at initialization
notifyOnInit(function() {
		var path = new RenderPath();
		path.commands = function() {
			path.setTarget("");
			path.clearTarget(0xFF87CEEB, 1.0); // Color to clear
			path.drawMeshes("mesh");
			Inc.bindShadowMap();
		};
		RenderPath.setActive(path);
});

```

This is mobile version
![screenshot_20190128-185549](https://user-images.githubusercontent.com/112117/51853245-8186ac80-2330-11e9-9a50-c17a9d434c03.png)

and this is desktop version without custom render path
![desktop](https://user-images.githubusercontent.com/112117/51853436-f8bc4080-2330-11e9-860a-04480c39a3ae.jpg)

**Comment by html** [comment]
I got proper rendering using mobile preset. It did not apply for the first time for some reason.
