### ISSUE TITLE
Mesh / Set Mesh crashed Krom

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1125]
Hi,

Setting the mesh of an object in On Init will crash Krom (works when running in browser, though).
![mesh_crash](https://user-images.githubusercontent.com/47137964/51894635-a3237a80-23a8-11e9-866f-f506e58f130e.png).

(Updated SDK today)

see attached .blend file [mesh_crash.zip](https://github.com/armory3d/armory/files/2806655/mesh_crash.zip)

Best regards
blackno666

**Comment by luboslenco** [comment]
Also addressed by https://github.com/armory3d/armory/commit/c6a26a0dadf989466bd9fe907617a87647e19630.

(link https://github.com/armory3d/armory/issues/1153)
