### ISSUE TITLE
[FR] Move Tilesheet from object to Material

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#1126]
Hi, first it's a suggestion. 

I think move tilesheet from object panel to material panel would be more effective and convenient. Every time i need to tweak both tilesheet and armory props i need to switch from objet panel to material panel. It's not convenient and me it's time consuming. May be tilesheet could be in Armory props tabs in Material panel or Separate from Armory Props but place in Material panel as it is in obet panel. 

What do you think about it ? 

*(drag & drop zipped .blend file here)*

**Comment by zicklag** [comment]
I think that sounds like a good idea. I'll try to submit a PR for that today.

**Comment by mistajuliax** [comment]
Great ! I'm testing today's build. There are many improvements so far. i'm pointing issues i found and thoughts about UI ...

**Comment by zicklag** [comment]
You think it would be good as a nested panel inside of Armory Props or as its own adjacent to Armory Props. When it is nested it only shows up when you expand Armory Props and it shows up under all of the other Armory Props settings:

![image](https://user-images.githubusercontent.com/25393315/51919136-6e172800-23a8-11e9-8ddf-5ddd7c95499a.png)

**Comment by mistajuliax** [comment]
It seems to be nice when it is nested inside Armory Props but it's only my opinion. You have to think that there is an armory props tabs in object panel too with options relative to tilesheet. In tilesheet tabs, you name your tilesheet texture and your animation and setup frame rate, tiles etc ... and in Armory props tabs in object panel, there is a tilesheet option where you have to pick up the name of your tilesheet and the name of the animation. i hope I'm clear. may be some options have to be gathered. what do you tink about this this @lubos ?

**Comment by mistajuliax** [comment]
Great looks nice, what about billboard option ? it is relative to tilesheet and particle too. I hope it is not a big deal to organize all of this ...

**Comment by mistajuliax** [comment]
I have to go, i will think about this and give feedback as soon as possible

**Comment by luboslenco** [comment]
The items in `Armory Props` panel are attached to the 'context', ie.:
- `Object panel - Armory Props` - properties per object
- `Material panel - Armory Props` - properties per material

`Armory Tilesheet` is currently a 'global' list, so it should be either standalone or the tilesheets should be defined per material (which I am not sure is ideal). Also the blending sub-panel is sweet!:)

**Comment by zicklag** [comment]
@mistajuliax Sounds good. Maybe we can discuss on your [forum topic](http://forums.armory3d.org/t/tilesheet-tabs/2576) and rename it to "UI Organization" or something. It is easier to go back and forth on the forum than it is on GitHub.

We can go over general UI organization and I can just make a single PR for the changes. Its actually really easy to mess with the UI so I have no problem doing it, we just have to figure out what we want to do.

**Comment by mistajuliax** [comment]
you're right let's discuss this on the forum .

**Comment by luboslenco** [comment]
@zicklag do you still have code for this + blending subpanel handy? We can go with this for a start and more ui cleanups also welcome as we go. 🙂

**Comment by zicklag** [comment]
Oh yeah, I should still have that. I forgot about this, I'll create a PR for it. :+1:
