### ISSUE TITLE
VXGI issue when emission is on.

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#1130]
VXGi work with emission at 0 
![vxgi works](https://user-images.githubusercontent.com/7542691/51916567-de8c6c00-23dd-11e9-810c-f58e6230e3db.jpg) 
Build failed when emission is set to something else than 0 
![vxgi failed](https://user-images.githubusercontent.com/7542691/51916655-0c71b080-23de-11e9-92ac-7ede56821779.jpg)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/armory/commit/7f6b640dfe842ebd9e735e83f5840a1178788023, thanks!
