### ISSUE TITLE
[FR] Add a check box or constraint resizable window to keep Homothety 

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#1131]
It's not a priority but it would be great to have the ability to keep homothety when we use resizable window
![non homothetic](https://user-images.githubusercontent.com/7542691/51972839-a1c38200-247c-11e9-9680-1a268120ffc4.jpg)
![non homothetic2](https://user-images.githubusercontent.com/7542691/51972841-a38d4580-247c-11e9-99fe-bc9f6b6ea015.jpg)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Will fix at https://github.com/armory3d/armory/issues/1010.
