### ISSUE TITLE
Mesh size doesn't match collision object size on scaled spawned objects

### ISSUE THREAD

**Issue by Bugsbane** [armory3d/armory#1132]
When an object to be spawned is scaled, it leads to a different mesh size than the collision object size. 

For example, if you have a sphere scaled to 50% and an empty scaled to 200%, and the empty spawns the sphere, the collision object used to calculate the physics will come out at 50%, while the mesh comes out at 100% size, so you end up with the spawned meshes being overly large and partially going through rigid bodies ingame:
![screenshot_20190130_114133](https://user-images.githubusercontent.com/401733/51997069-046c4c00-2484-11e9-89ab-8a39a2effcf1.png)

If the sphere and empty which spawns it aren't scaled though (ie 100% scale), both the collision object and the mesh size match and act as expected:

![screenshot_20190130_113830](https://user-images.githubusercontent.com/401733/51996850-958ef300-2483-11e9-8ca3-181955253e1a.png)

Here's the blend file used to create these examples (push left arrow to spawn the scaled sphere, and right arrow to spawn the unscaled one):

[spawn-test.zip](https://github.com/armory3d/armory/files/2813562/spawn-test.zip)

Bonus points if you know why there's a small black shadow on each ball, or why the right spawn creates 2 spheres instead of one...

**Comment by luboslenco** [comment]
Scaling and black shadows issues should be gone, thanks for the test file!

`SphereSpawnRight` was also attached to plane, so it was running twice. There is a way to inspect scene traits in the outliner now, added info [here](https://github.com/armory3d/armory_docs/blob/master/essentials/traits.md).
