### ISSUE TITLE
Forest example is broken

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#1135]
Is forest example up to date ?? libraries folder is empty. and if copy/paste libraries folder from driver cellshade i get a error, i can't play this example.
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Please use 0.6 beta builds to run that example, git builds can be wonky. To prevent empty libraries folder, clone using:
`git clone --recursive https://github.com/armory3d/driver_celshade_example` (check [readme](https://github.com/armory3d/driver_celshade_example/blob/master/README.md)).
Hope that helps!
