### ISSUE TITLE
Inaccurate shadows produced by point lights

### ISSUE THREAD

**Issue by DiegoBM** [armory3d/armory#1137]
When using point lights armory produces incorrect shadows resembling the presence of another light source on the opposite location of my actual only light source.

This is the shadow produced by blender:
![blender_shadow](https://user-images.githubusercontent.com/1613216/52076235-85b00580-258e-11e9-93c8-b9d6d36b7920.png)

And this is the shadow produced by armory:
![armory_shadow](https://user-images.githubusercontent.com/1613216/52076248-8cd71380-258e-11e9-8e59-f22ed38166d6.png)

Sun lamps don't seem to produce that bleeding. I've tried tweaking the light source bias, changing the world properties, playing with irradiance, SSAO and nothing seems to remove that effect (bias seems to reduce it a bit but not make it dissapear and eventually it will add bizarre artifacts).

I'm including the blend file for debug purposes:
[transform.zip](https://github.com/armory3d/armory/files/2818573/transform.zip)

**Comment by luboslenco** [comment]
Fix pushed, thanks!

**Comment by DiegoBM** [comment]
Superb! Thank you very much!
