### ISSUE TITLE
Cannot reassign traits to existing trait slots - cache issue

### ISSUE THREAD

**Issue by DiegoBM** [armory3d/armory#1139]
Version: Amory 0.6 beta redistributable as downloaded from Armory website.

If you try to reassign an existing haxe script to an existing trait slot, the console will display an error indicating that it could not find such file even though it exists, displaying:

> iron.Scene:621: Error: Trait 'arm.MyTrait' referenced in object 'Cube' not found

Steps to reproduce:
1. Download "Armory_06beta_win64.zip/7z" from Armory website, extract and run.
2. Create a new scene, save and build for the first time.
3. Select the cube and create a new Haxe trait slot for it on the traits list.
4. Create a new Haxe script file by clicking "New Script", assign it a name, and run
5. Create another Haxe script file by clicking "New Script", assign it a name (will be automatically assigned to the trait slot created on step 3), and run
6. Assign the script created on step 4 to the trait slot created on step 3 and run.

The system console will display the error

Cleaning the project solves the issue.
Removing the trait slot from the traits list and creating a new trait slot, also solves the problem

**Comment by BlackGoku36** [comment]
I think that might be cache issue

**Comment by DiegoBM** [comment]
Oh sorry, I couldn't find and existing issue about this by searching. Thank you @BlackGoku36 for the hint. You are correct, if you disable "Cache Build" it won't display the error anymore. Will close this one

**Comment by luboslenco** [comment]
Disabling `Cache Build` will prolong build times, will investigate and hopefully fix the cache issue.:)

**Comment by DiegoBM** [comment]
Thank you @luboslenco, it's true, for final users Cache Build is probably a must.

**Comment by luboslenco** [comment]
Appears to be ok nowadays.
