### ISSUE TITLE
kraffiti crashing

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#114]
As the title says, i've tried the solution below, blender won't crash anymore, but krom crash after build
---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Hi, thanks for report. Can you hand some more info? What 'solution below' do you have in mind? Can you paste blend that crashes? Or does it crash every time with every scene you try?

**Comment by MagicalPaladin** [comment]
It's only crash with this scene, i've renamed the "new" cmft file and deleted the other one to fix blender crash, but now krom's crash. it's crash with scene 4.

**Comment by luboslenco** [comment]
Aha, I see. Is the error  'Could not open envmap_radiance_0.hdr'? If so - try to hit *Clean Project* button (or delete 'build' folder placed alongside .blend file manually).

If that helps then the fix is already in place to prevent this in next build. If it won't help please paste the console output so we can investigate further.

**Comment by MagicalPaladin** [comment]
i've got "kraffiti.exe" crashing clean project does nothing

**Comment by luboslenco** [comment]
Hm, can you send me the zip of your project folder (with build folder included)? I will try to reproduce the issue on my machine. If *kraffiti.exe* crashes then the radiance maps are probably still not generated.

Also, please paste the console log even if there are no errors, will be useful to see how far the build process went till it crashed. :)

**Comment by MagicalPaladin** [comment]
Here is the blend, how can i see the console log ?
[scene4.zip](https://github.com/armory3d/armory/files/709064/scene4.zip)

**Comment by luboslenco** [comment]
Awesome, thanks!

For the console, it is:
*Blender - Window - Toggle System Console*

You should then be able to simply copy-paste the text here.

![blender_tip_console_toggle](https://cloud.githubusercontent.com/assets/3685704/21994032/0890ae4e-dc1e-11e6-882a-a92e6c13a8e0.png)

**Comment by luboslenco** [comment]
@MagicalPaladin 
Any news using Build 7? Does kraffiti.exe still crash?

**Comment by MagicalPaladin** [comment]
just downloaded it, will try it sand tell you then

**Comment by MagicalPaladin** [comment]
well don't have this anymore
