### ISSUE TITLE
Only one area light per scene works

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1140]
[untitled.zip](https://github.com/armory3d/armory/files/2821827/untitled.zip)

Ubuntu, Krom runtime, 0.6, SDK up to date

Only one area light per scene works. The yellow one is on, green off. Delete yellow and green is on.

**Comment by knowledgenude** [comment]
Follow https://github.com/armory3d/armory/issues/1772

**Comment by knowledgenude** [comment]
Follow https://github.com/armory3d/armory/issues/1772#issue-660023398
