### ISSUE TITLE
Static scene performance

### ISSUE THREAD

**Issue by DavidLeoni** [armory3d/armory#1145]
Seems like a static scene with just the default cube and no script eats 5% of cpu, which on my laptop triggers the fan quite early. During most games this is not an issue as scene is expected to move constantly, but for other scenarios like online item configurators or static adventure games this can be annoying (noise, heating, battery drain, etc). 

I have Ubuntu 16.04 and tried HTML5 debug / build mode both in Firefox 65 and Chrome 67 with similar results.

David

**Comment by luboslenco** [comment]
Hello,

Do you experience the same issue when running in Krom? What is your GPU usage? That may be the main reason for spinning fans. (You could verify that by lowering the render path to the mobile preset.)

**Comment by DavidLeoni** [comment]
Disclaimer: I know nothing about GPU profiling :-)  

I gave it a try with Krom Desktop / Mobile, HTML5 Mobile Firefox / Chrome. Setting Mobile actually solves the problem except in the Firefox, where CPU usage seems still too high (15%) with fan spinning, while in Chrome CPU remains silent at ~7% 

I put here the findings.

I have Intel card, and I used tool `intel_gpu_top`

![image](https://user-images.githubusercontent.com/628313/52178534-39540800-27d0-11e9-9836-082843bf0409.png)

## just Blender 
for comparison
cpu: 0
gpu: low
fans spinning: no

![image](https://user-images.githubusercontent.com/628313/52178477-55a37500-27cf-11e9-9d87-1780e937f242.png)

## Krom Desktop published build

cpu: low
gpu: high
fans spinning: yes

![image](https://user-images.githubusercontent.com/628313/52178513-e5492380-27cf-11e9-8ad1-526794c2647f.png)

## Krom Mobile published build

cpu: low
gpu: low
fans spinning: no

![image](https://user-images.githubusercontent.com/628313/52178671-b16efd80-27d1-11e9-9faa-5784fce43db7.png)

## HTML5 Mobile published build Firefox

cpu: 15%
gpu: low
fans spinning: yes

![image](https://user-images.githubusercontent.com/628313/52178739-66a1b580-27d2-11e9-9b9f-39bc3f95de30.png)

## HTML5 Mobile published build Chrome

cpu: 7%
gpu: low
fans spinning: no

![image](https://user-images.githubusercontent.com/628313/52178927-62769780-27d4-11e9-9c3e-91cddb3096b1.png)

**Comment by luboslenco** [comment]
Thanks for the great info there! Will further improve at https://github.com/armory3d/armory/issues/870.
