### ISSUE TITLE
Voxel GI sunlamp settings ignored

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1146]
0.6 beta. Also GI doesn't seem to work at all if there is no sunlamp present in the scene.

**Comment by BlackGoku36** [comment]
Was testing scene provided by someone in discord server, where i tried to use sunlamp with Voxel GI and without any Voxel but didn't work looked darky and blacky , look like Sunlamp bug to me.

**Comment by BlackGoku36** [comment]
Link: https://github.com/armory3d/armory/issues/1066

**Comment by Simonrazer** [comment]
Win 10 Home/Basic/idk the usual thing
GTX 1060 6GB
i5 6500 
16gb DDR4 ram

**Comment by luboslenco** [comment]
Sun settings no longer ignored now.
