### ISSUE TITLE
Mesh display wrong

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1148]
Hi,

Win10, Quadra K2000, Armory 0.6

I created a mesh by first creating a bezier curve, adding a bevel with a bezier circle, converted the curve to a mesh, cut off the top half and inverted the normals (but normal's orientation does not matter). The viewport is very different from Krom/Browser. It seems some vertices are connected in a very wrong way.

![meshbug](https://user-images.githubusercontent.com/47137964/52244459-fed89100-28dd-11e9-879c-16de40ea3638.png)

[MeshBug1.zip](https://github.com/armory3d/armory/files/2830182/MeshBug1.zip)

**Comment by luboslenco** [comment]
Seems to be linked to https://github.com/armory3d/armory/issues/855. `.obj` export also produces corrupted mesh but triangulation fixes that. Will resolve at https://github.com/armory3d/armory/issues/855.
