### ISSUE TITLE
Problems with armory material node param with multiple materials assigned

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1149]
[test.zip](https://github.com/armory3d/armory/files/2831407/test.zip)

1) Cube becomes black, lights vanish, etc (happening also without trait).
2) Wrong material obj is returned from Uniforms.externalVec3Links per link (see console output).

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/e6f02ef5f8a728f9ffbaf4df18001cf21659be3a.

**Comment by trsh** [comment]
Thank you
