### ISSUE TITLE
Adding logic pack nodes cause project to crash - Uncaught exception

### ISSUE THREAD

**Issue by greyheron** [armory3d/armory#1150]
When adding logic pack nodes to existing project, execution breaks with following error:

```
Uncaught exception:
                while(_g2 < _g3.length) {
                      ^
TypeError
   at run (krom.js:1121:9)
   at armory_logicnode_LogicNode.prototype.runOutput (krom.js:1026:6)
   at update (krom.js:1465:4)
   at iron_App.update (krom.js:6087:3)
   at Anonymous function (krom.js:25259:3)
   at kha_Scheduler.executeTimeTasks (krom.js:25143:4)
   at kha_Scheduler.executeFrame (krom.js:25095:3)
   at kha_SystemImpl.renderCallback (krom.js:25891:2)
```
Note that I create the issue in armory and not in [logic pack](https://github.com/armory3d/logic_pack/) because this happens only by adding the folder to Libraries folder in the project without using any node provided by that repository. Also, I am not using any custom node in this project.

The test I run was:

- Execute project without logic pack: works perfectly fine
- Clone logic pack in Libraries folder
- Execute project without any changes after restarting blender: it crashes with error mentioned above
- Remove logic pack from Libraries folder
- Execute project without any changes after restarting blender: works perfectly fine

 Let me know if I should create the issue in the other repository instead.

**Comment by luboslenco** [comment]
Hm, do you get this behavior in every project? It looks ok here but I think I am just not triggering the bug.

**Comment by greyheron** [comment]
I cannot replicate the issue anymore. I tried in new projects and the project that I had the issue initially and is not happening anymore.
