### ISSUE TITLE
Switching to "Camera: Viewport" in player settings just causes camera to spin

### ISSUE THREAD

**Issue by Bugsbane** [armory3d/armory#1151]
This works in literally every blend file I have tried, including the animations example file here and the default cube Blendfile among others. It's very simple to test.

Anyway, whenever the Armory Player setting "Camera" is switched from "Scene" to "Viewport",then as soon as the Armory Player is started, the camera immediately starts spinning around the Z axis. It seems that it's similar to the closed issue #486 however now the camera rotates instead of moving on an axis.

I've tried and found this in version 0.5, 0.6 *and* the current Git version where I just updated the SDK and restarted (not sure how to get the exact checkout of this version?)

**Comment by luboslenco** [comment]
Uh oh, do you mean this animation example?
https://github.com/armory3d/armory_examples/tree/master/animation

It seems ok here for some reason. What OS are you on? Do you see the same behavior in krom and browser?

> (not sure how to get the exact checkout of this version?)

It should be displayed in the system console on each build (the line is `Armory v0.6 ($Id:  $)`)

**Comment by Bugsbane** [comment]
No, sorry, I meant this one:
https://github.com/armory3d/armory_examples/tree/master/animation_actions

I'm on Kubuntu 18.10. I get the behaviour with Krom, however it doesn't seem to happen when using the browser target.

**Comment by Bugsbane** [comment]
@BlackGoku36 suggested that this might be just a different consequence of issue #512

**Comment by BlackGoku36** [comment]
Yeah, I think so, @luboslenco can you show me where is viewport's camera's trait is? I can't seem to find it

**Comment by luboslenco** [comment]
Yup, the trait is [WalkNavigation](https://github.com/armory3d/armory/blob/master/Sources/armory/trait/WalkNavigation.hx) (it's named after `3D Viewport - View - Navigation - Walk Navigation` thingy in Blender).

Whenever needed you can also inspect traits in the debug console. 🙂 
![c](https://user-images.githubusercontent.com/3685704/53516506-c6873580-3acc-11e9-89ce-f67bb565d14d.PNG)

**Comment by knowledgenude** [comment]
Can't reproduce the issue using Linux. Please reopen if this problem was not solved :+1:
