### ISSUE TITLE
Set Scene crashes Krom

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1153]
Hi,

Armory 0.6, win10: when using the following node, Krom crashes (works in browser, though).
Not sure if this is a bug of armory of kha or whatever (I don't have a understanding of the underlying structures but I thought I'd post it here anyway).

![setscenebug](https://user-images.githubusercontent.com/47137964/52372356-471bbe80-2a58-11e9-9b3a-3dc091e7c47d.png)

Attached is the blend file. [xscene.zip](https://github.com/armory3d/armory/files/2838159/xscene.zip)
Best regards
blackno666

**Comment by DiegoBM** [comment]
I reckon the problem comes from the "Scene" node instead. Apparently it's transferring a name with white spaces to the "Set Scene" node. If you use a "String" node instead of a "Scene" node, it will work. In any case worth taking a look at.

**Comment by luboslenco** [comment]
Hello,

Thanks for opening a bug report! Testing patch at https://github.com/armory3d/armory/commit/c6a26a0dadf989466bd9fe907617a87647e19630, should be good now.
