### ISSUE TITLE
Krom + Voxel GI + emission material == build failure "'emission' : undeclared identifier"

### ISSUE THREAD

**Issue by Bugsbane** [armory3d/armory#1154]
When I use an emission material with Krom and GI Voxels, the build fails giving the errors:

```
ERROR: /tmp/build_untitled4/compiled/Shaders/glow_voxel.frag.glsl:25: 'emission' : undeclared identifier 
ERROR: /tmp/build_untitled4/compiled/Shaders/glow_voxel.frag.glsl:25: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link

Compiling shader 9 of 24 (glow_voxel.frag.glsl) failed:
Shader compiler error.
(node:1126) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Shader compiler error.
(node:1126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERROR: /tmp/build_untitled4/compiled/Shaders/glow_voxel.geom.glsl:14: 'lightPositionGeom' : undeclared identifier 
ERROR: /tmp/build_untitled4/compiled/Shaders/glow_voxel.geom.glsl:14: 'lightPositionGeom' :  left of '[' is not of type array, matrix, or vector  
ERROR: /tmp/build_untitled4/compiled/Shaders/glow_voxel.geom.glsl:14: 'assign' :  cannot convert from ' const float' to 'layout( stream=0) out 4-component vector of float'
ERROR: /tmp/build_untitled4/compiled/Shaders/glow_voxel.geom.glsl:14: '' : compilation terminated 
ERROR: 4 compilation errors.  No code generated.


SPIR-V is not generated for failed compile or link

Compiling shader 10 of 24 (glow_voxel.geom.glsl) failed:
Shader compiler error.
```
If I use the browser target, the build doesn't crash, but neither do I get the emission material casting light. It's the same if I use Voxel AO or turn all global illumination off.

While this is related to #1143 , I would say that it's not the same as this isn't just a feature request, it's a bug causing the build to fail when trying to run the ArmoryPlayer.

Specs:
Armory v0.6 ($Id: a24ce47235b5e4359e76d21b38374d17560e0e7d $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.80 (sub 40)
Kubuntu 18.10
Intel graphics card with i915 driver

Demo file:
[VoxelGIKromCrash.zip](https://github.com/armory3d/armory/files/2839823/VoxelGIKromCrash.zip)

**Comment by luboslenco** [comment]
Thanks, fixed build error at https://github.com/armory3d/armory/commit/7f6b640dfe842ebd9e735e83f5840a1178788023. The emission only affects object itself and bloom as of now.
