### ISSUE TITLE
Get Property returning the property name too

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#1155]
Just a remark that could reduce number of nodes and help during debuging for example,
that is to add to the Get Property node 
![image](https://user-images.githubusercontent.com/20455592/52478708-848e6200-2ba6-11e9-88a8-88b88ebcd1e0.png)
 an output of the Property name too. 

(this can be done actually by adding a node String with the property name inside, but could reduce number of nodes)
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armory/pull/1300.
