### ISSUE TITLE
"end before you begin" exception, game crash

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1160]
With the SDK of today, the game will always output a "end before you begin" exception. Also, when running the game and pressing space: as soon as the circle hits the other object, the game will crash.

Everything worked with the version from like 5 days ago.

[GooCursor1.zip](https://github.com/armory3d/armory/files/2858127/GooCursor1.zip)

Best regards
blackno666

**Comment by luboslenco** [comment]
Fixed now at https://github.com/armory3d/armory/commit/78dba00f17235497bbebfcee40213128e84eba4b.
