### ISSUE TITLE
404 error in browser when live patch is opened

### ISSUE THREAD

**Issue by XQDD** [armory3d/armory#1162]
(Newest Git)
Work in krom

![image](https://user-images.githubusercontent.com/20871761/52694444-b50a3d80-2fa4-11e9-9553-b50d152bcc39.png)

![image](https://user-images.githubusercontent.com/20871761/52694395-8ab88000-2fa4-11e9-8b4a-116556fcdbb7.png)

**Comment by luboslenco** [comment]
Thanks, fixed now at 49c58d2c056363b7cc6479e00884114d40a0404f.
