### ISSUE TITLE
Kode Studio Debug not work in 0.6b

### ISSUE THREAD

**Issue by XQDD** [armory3d/armory#1165]
Krom application haven't run

OS: Windows10 64 v1809
Armory Version: 0.6beta
Armory SDK Version: newest git

![image](https://user-images.githubusercontent.com/20871761/52708808-11318980-2fc6-11e9-8bd0-5eae81b07cb3.png)

**Comment by luboslenco** [comment]
Fixed now in newest build from itch.io.:)

**Comment by BlenderViza** [comment]
Same problem to me 17 days after fixing. 
Armory SDK updated 2 days ago. 
No problems and no errors but application doesn't show and the little blue marker is idle until clicking the stop button.
