### ISSUE TITLE
[FR] EEVEE bloom parameters match armory bloom ?

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#1166]
Here you can see settings are different and doesn't match each other. It would be great to have same settings and result share by armory and eevee to preview render result expected in armory.
I don't know if it possible and wich techniques uses armory and eevee but as they both uses post process may be it is something doable ... 
![bloom 01](https://user-images.githubusercontent.com/7542691/52712003-9fd8e300-2f93-11e9-83c6-f812b9ac3289.jpg)
Another issue is the view distance ... here you can sse nothing with armory default bloom parameters unlesss you are very near from object.
![bloom 02](https://user-images.githubusercontent.com/7542691/52712185-1f66b200-2f94-11e9-826f-65a6e0a1dc58.jpg)
![bloom 03](https://user-images.githubusercontent.com/7542691/52712234-43c28e80-2f94-11e9-966c-1b4ae0973240.jpg)
[laser_beam_test.01.zip](https://github.com/armory3d/armory/files/2860358/laser_beam_test.01.zip)

*(drag & drop zipped .blend file here)*

**Comment by kenthinson** [comment]
This would be great to have them match. Also it would be nice to simply remove the armory bloom settings and just read the eevee settings during compile time. That way we wouldn't have to change them in two different places.
