### ISSUE TITLE
Cloth and softbody self collision

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#117]
Important future armory must have

**Comment by zauberparacelsus** [comment]
In order to be doable in real-time, you would probably need to use a lower-resolution mesh for the simulation, and then either (A) apply the transformation to a higher-resolution mesh, or (B) use tessellation on the lower-resolution mesh to make it into a higher resolution one.

**Comment by luboslenco** [comment]
Definitely. I want to make physics module fully isolated before going deeper, so both bullet and physx could be supported.

Merging issue with https://github.com/armory3d/armory/issues/8.
