### ISSUE TITLE
Annoying warning on Linux

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1170]
`WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1419 pyrna_enum_to_py: current value '0' matches no enum in 'Area', '(null)', 'type'`

Happens on every blend open.
Ubuntu 18.x, armory 0.6, SDK up to date

**Comment by XQDD** [comment]
Windows+1
![image](https://user-images.githubusercontent.com/20871761/52857594-9a7dc300-3162-11e9-8fa2-9373097acd79.png)

**Comment by luboslenco** [comment]
Fixed now at https://github.com/armory3d/armory/commit/a8b830303ad72dbed7c7ad56f39243447c528ac6.
