### ISSUE TITLE
Transform.dim is not calculated correctly when the origin is not at the bounding box center

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#1172]
I encountered an issue that when I used the `object.transform.dim` of an object with none centered origin, the values were not correct _(bigger than the actual dimension in blender)_

I checked the code , the dim values came from `dimensions` which came from `aabb`, and it was calculated using the bounding box information:

```
    def calc_aabb(self, bobject):
        aabb_center = 0.125 * sum((Vector(b) for b in bobject.bound_box), Vector())
        bobject.data.arm_aabb = [ \
            abs((bobject.bound_box[6][0] - bobject.bound_box[0][0]) / 2 + abs(aabb_center[0])) * 2, \
            abs((bobject.bound_box[6][1] - bobject.bound_box[0][1]) / 2 + abs(aabb_center[1])) * 2, \
            abs((bobject.bound_box[6][2] - bobject.bound_box[0][2]) / 2 + abs(aabb_center[2])) * 2  \
        ] 
```

I think the `aabb_center` related codes need to be removed since it is basically just a local offset of the origin which shouldn't be added to the dimensions. So I think the function should change to:

```
    def calc_aabb(self, bobject):
        bobject.data.arm_aabb = [ \
            abs(bobject.bound_box[6][0] - bobject.bound_box[0][0]), \
            abs(bobject.bound_box[6][1] - bobject.bound_box[0][1]), \
            abs(bobject.bound_box[6][2] - bobject.bound_box[0][2])  \
        ]
```
I am not sure if there is other intention to adding the `aabb_center` to the dimension values, so please let me know if you agree with this change. Thanks!

/Milo

**Comment by luboslenco** [comment]
There was an intention to this due to packing vertex data into 16bits IIRC. But we should expose the proper value in `object.transform.dim` like you suggested. Will investigate at https://github.com/armory3d/armory/issues/1259.
