### ISSUE TITLE
Cannot play the Project

### ISSUE THREAD

**Issue by Snewkis** [armory3d/armory#1173]
I create a new empty project : just a simple cube

But when I open the armory player menu, there is nothing.

![image](https://user-images.githubusercontent.com/46242196/52876071-5be20b80-3156-11e9-8f3f-9e06d8b96cff.png)

**Comment by BlackGoku36** [comment]
Are there any errors in `Debug console`?
Are you using armory from itch.io?

**Comment by Snewkis** [comment]
There is no error in `Debug console`, and yes, I'm using armory from itch.io

**Comment by luboslenco** [comment]
Hello, which OS are you on? Nothing from the [troubleshooting](https://armory3d.org/manual/#/getting_started/setup?id=troubleshooting) guide helps?

I am not sure I follow the `Debug console` thing. On Windows the errors should be displayed after clicking  `Blender - Window - Toggle System Console` or when starting Blender from terminal (Linux / macOS).

**Comment by Snewkis** [comment]
There is no errors... ¯\_(ツ)_/¯

**Comment by Snewkis** [comment]
I re-install armory, 
now it's working !
