### ISSUE TITLE
init_properties_on_load error

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1176]
This started poping out when migrated project from 0.5 to 0.6. The error is kind of un-informative and I have no clue what todo with it

```
Read blend: /home/trsh/forks/nb_files/test_lab/test_lab.blend
Traceback (most recent call last):
  File "/media/trsh/AREJAIS/Armory/Armory/armsdk//armory/blender/arm/handlers.py", line 86, in on_load_post
    props.init_properties_on_load()
  File "/media/trsh/AREJAIS/Armory/Armory/armsdk//armory/blender/arm/props.py", line 345, in init_properties_on_load
    inp.default_value_get = bpy.data.objects[inp.default_value]
KeyError: 'bpy_prop_collection[key]: key "button_1" not found'
```

**Comment by trsh** [comment]
Python doesn't handle missing keys good, so have to add some check here probably. But again, I dont know the plan- like what happens if check for key fails.

**Comment by luboslenco** [comment]
Removed the b2.79 migration code which could cause this issue. https://github.com/armory3d/armory/commit/c0ce39521da91107643e33d7b74ec6124c8931d1
