### ISSUE TITLE
Python error on opening 0.5 project in 0.6 arm

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1177]
```
Read prefs: /home/trsh/.config/blender/2.80/config/userpref.blend
found bundled python: /media/trsh/AREJAIS/Armory/Armory/2.80/python
Armory: Proxy objects synchronized
Read blend: /home/trsh/forks/nb_files/test_lab/test_lab.blend
Traceback (most recent call last):
  File "/media/trsh/AREJAIS/Armory/Armory/armsdk//armory/blender/arm/handlers.py", line 86, in on_load_post
    props.init_properties_on_load()
  File "/media/trsh/AREJAIS/Armory/Armory/armsdk//armory/blender/arm/props.py", line 342, in init_properties_on_load
    node.property0 = ''
TypeError: bpy_struct: item.attr = val: LNMaterialNode.property0 expected a Material type, not str
```

**Comment by trsh** [comment]
I think its from other nodes in my proj. I will try to reproduce in blend

**Comment by UglinessInTheUI** [comment]
Maybe it's the connection that's causing it. I can clone the string node just fine but it was not connected to anything.

![2019 02 23-04 40](https://user-images.githubusercontent.com/12206146/53286001-3a1ff000-3725-11e9-9d18-6a45361828a2.png)

**Comment by trsh** [comment]
@UglinessInTheUI 

Well one can see the issue in stack trace I pasted. Im not 100% sure what's causing it. I also got this on opening the project.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/1176.
