### ISSUE TITLE
Newest build 0.6 from itch dead on Linux

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1179]
```
Standard library not found
Build failed, check console
```

Ubuntu 18.x, 0.6 SDK updated

**Comment by zicklag** [comment]
Works for me with the latest SDK from git. I'm not sure if the Armory updater will pull **all** of the changes or not.

Do you have Haxe installed on your system separate from Armory? It sounds like for some reason it can't find the Haxe standard library. Haxe is bundled with Kha, so you don't have to install it manually, but for some reason it is not finding it. Maybe try unsetting `HAXE_STD_PATH` in a shell and try running it again from that shell.

**Comment by trsh** [comment]
@zicklag i just updated SDK, and the issue is gone. 

¯\_(ツ)_/¯
