### ISSUE TITLE
Viewport navigation

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#118]
Following http://forums.armory3d.org/t/feature-request/196.

- Remapping viewport navigation keys
- More navigation modes

**Comment by mistajuliax** [comment]
Hi lubos ! longtime no play with armory cause i'm a father now :) . I have just downloaded the lastest release ( build 14 ) and i see a feature i'e requested double sided material, thanks a lot !! Did you have some advancements about navigation in azerty ? or an option to switch qwerty to azerty navigation in armory viewport ?

**Comment by luboslenco** [comment]
Hello @mistajuliax,

Wow so cool to hear that - I wish your family all the best! I have now also added option to switch viewport controls, it will be out in upcoming build. (or get the latest [git version](http://armory3d.org/manual/dev/gitversion.html) and [armory addon](https://github.com/armory3d/armory/blob/master/blender/addon/armory.py)). :)

<img width="779" alt="azerty" src="https://user-images.githubusercontent.com/3685704/33182391-1839e432-d074-11e7-9169-1c0298757d5a.png">

**Comment by mistajuliax** [comment]
Hi Lubos, Thanks a lot. Everyone is fine here :) . Nice to see we users are heard by developers ! Thanks for navigation Controls ! it will be easier for azerty users. Keep going on the good job, Armory is great and promising !!
