### ISSUE TITLE
HDR lighting issue

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#1182]
HDR lighting passes through objects as seen in the below picture:
(Red circle is where the light source is in HDR map, but get lighting effect (black circle) as if there was no wall in between even though there is).
<img width="523" alt="hdrerror" src="https://user-images.githubusercontent.com/36535717/53044593-78ad7480-34b1-11e9-9940-9a992a307533.png">
Happens on both HTML5 and Krom
Armory Version: 0.6 (https://github.com/armory3d/armory/commit/6a6c0704e7ba484ea21bf410d32ee8983f380e81)

**Comment by trsh** [comment]
Same here.

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armory/issues/1110, will fix at https://github.com/armory3d/armory/issues/649.
