### ISSUE TITLE
Timer node doesn't reset after use

### ISSUE THREAD

**Issue by Bugsbane** [armory3d/armory#1183]
Following this forum post:
http://forums.armory3d.org/t/problem-with-timer-node/2728

the user has a problem with the timer node only working the first time. Now I'm no coder (warning! "artist code" ahead! =:-O ), but looking at the node source, there doesn't seem to be any test for if repetitions has met/exceeded the number set in "repeat" to stop the node.

Shouldn't there be something before line 23 in the timer node like:

```
if (repetitions >= repeat) {
			removeUpdate();
			time = 0;
			repetitions = 0;
			}
```
???

**Comment by luboslenco** [comment]
Thanks, fixed now at https://github.com/armory3d/armory/issues/1252!
