### ISSUE TITLE
[FR] sound volume control

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1184]
Feature Request: I'd wish for a way to control the volume of sounds/speakers (percentage of volume or something the like). Currently the only possibility to do so (or at last I know of) is to move the speaker away from the camera. 

Even though this works, the user must take care to sounding object along the optical axis of the camera, otherwise the sound will not fade for the left and right channel equally. Besides there's no real way of controlling how loud the sound will be, except for trial and error.

**Comment by luboslenco** [comment]
Should be doable with `speaker.data.volume = 0.5;` now.
