### ISSUE TITLE
Annoying issue when pressing Play...

### ISSUE THREAD

**Issue by ghost** [armory3d/armory#119]
Hello,

I often have the error shown below when I press on Play and I don't know why. It is a bit annoying because it is not systematic. Has someone had this issue and how did you fix it?

![error](https://cloud.githubusercontent.com/assets/16611911/22377189/3215bad4-e4b1-11e6-8166-1260f7b4d4cb.png)

---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Heyo,

That indeed looks annoying. Is your .blend file located on different disk drive than your armory sdk(C:) when this happens?

(if so then I will need to get rid of using relative paths pointing to armory sdk internally to fix this.)

**Comment by E25543** [comment]
(sorry for the delay)

When I first wrote the message, Blender+Armory+File were on the F drive (I'm running short of space of C:). However, Blender stored some data on the C:/.../AppData/Roaming folder. So, I migrated everything to the C: to make sure I fixe the issue: everything is on C:. It didn't and I got the error message:

![error02](https://cloud.githubusercontent.com/assets/16611911/22403275/a8cdd8de-e612-11e6-8030-5f53222ee52a.jpg)

I am also giving the file that costed the problem. Maybe you can make go use of it and tell me what I did wrong.

[ArmoryTest.zip](https://github.com/armory3d/armory/files/737424/ArmoryTest.zip)

Let me know if I can do something more.

**Comment by sh-dave** [comment]
I think this is a different issue now (read the Runtime Error line). Try to move the project to somewhere programs have write access on C like the 'Own documents' folder: ```C:\Users\<your name>\Documents```.
Depending on your settings, the root c:\ might be protected by windows.

**Comment by E25543** [comment]
Hey,

I moved everthing to my user's documents and I have the previous issue:

![armoryerror03](https://cloud.githubusercontent.com/assets/16611911/22404931/0f391480-e63b-11e6-8a02-e63952f38b6b.jpg)

I think there's something about how my scene is built. Before doing the scene you can download, I tested if Armory worked correctly by adding a sky texture, camera, cube, viewport Camera: walk. It was ok.

Then I added an architectural model (just 48k polygons) and I got this message. The scene has 440 objects: is there is limit?

**Comment by luboslenco** [comment]
@E25543 
Can you test with Build 7?
- I got rid of relative paths, should work from any drive now so feel free to move it around.
- *'NoneType' object has no attribute 'nodes'* could happen before when 'empty' material was assigned to object. This should also be resolved now.

**Comment by E25543** [comment]
Hey!

Works fine. No problem loading. Wow! Armory is able to load all that easily!

I have one question though... I don't know if I should open another issue... anywhere here it goes:

I sometimes have shadows problems as shown in the following image:
![shadowquestion](https://cloud.githubusercontent.com/assets/16611911/22454071/a6504462-e783-11e6-97f7-fa4900998ab7.jpg)

Sometimes shadows are projects in a strange way. It's possible that there is a setting but that it is just me doing things wrong. How would you fix that?

**Comment by luboslenco** [comment]
Shadows projected in a strange way should now be fixed. For point/spot lamps, setting _Properties - Lamp - Armory Props - Clip End_ tells the distance from lamp where shadows are cast.
