### ISSUE TITLE
Non assigned overlay material breaks object

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1191]
[untitled.zip](https://github.com/armory3d/armory/files/2896620/untitled.zip)

Green material isn't really assigned (not main material and not added to any faces), but it brakes blue emission added to face.

**Comment by Bugsbane** [comment]
Not sure which material you mean by "Green material", but I'm guessing Material.002? (Material seems to be the grey one, and Material.003 seems to be the blue emission material).

Something I noticed in the console output:
```
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.frag.glsl).
Done.
Finished in 5.560987234115601
Uniform N not found.
```

The "uniform N" message goes away if I remove the material slot for Material.002. If I delete the data block for material.002 from the shader nodes editor, I also get the following error message:
```

Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 5.643336772918701
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1419 pyrna_enum_to_py: current value '0' matches no enum in 'Area', '(null)', 'type'
WARN (bpy.rna): /home/sources/buildbot-x86_64-slave/linux_glibc224_x86_64_cmake/blender.git/source/blender/python/intern/bpy_rna.c:1419 pyrna_enum_to_py: current value '0' matches no enum in 'Area', '(null)', 'type'
Uniform N not found.
```

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/6a90241147b438ffdc5f22c89d6c40d9f0d3bf5f.
