### ISSUE TITLE
Cloned Objects With ALT+D Lose Functionality

### ISSUE THREAD

**Issue by UglinessInTheUI** [armory3d/armory#1192]
After ALT+D cloning , the logic nodes seem to be there but the functionality is lost. Does anybody know how to set the game in full screen mode because i can't find it anywhere ? Also , where are the AA options ? Thank you.

[ClonedRotate.zip](https://github.com/armory3d/armory/files/2896745/ClonedRotate.zip)

**Comment by luboslenco** [comment]
Hey,

For the fullscreen option, check `Armory Project - Window - Mode`:
![capture](https://user-images.githubusercontent.com/3685704/53288573-032ff580-378a-11e9-9a3a-538212c4caab.PNG)

And for current AA options, `Armory Render Path` panel:
![capture1](https://user-images.githubusercontent.com/3685704/53288587-29ee2c00-378a-11e9-965c-5776525516f9.PNG)

**Comment by UglinessInTheUI** [comment]
Thank you very much for that info. Any ideas why the rotation is not working on the cloned cubes ? The logic seems to be there but the clones are not rotating.

**Comment by BlackGoku36** [comment]
You will need to assign trait to all cloned cube to work, traits would not work if object is just clone, trait needed to be assigned :)

**Comment by UglinessInTheUI** [comment]
Each cube needs to have a different new trait ? I can not reuse the existing trait for all the cubes ? The cubes already have the same trait assigned to them but they are not working.

**Comment by UglinessInTheUI** [comment]
I want to assign one trait to multiple objects. So far it's not working.

**Comment by BlackGoku36** [comment]
you can assign one trait to multiple objects and it should works, can you send your trait so that i can check?

**Comment by UglinessInTheUI** [comment]
The file is right there at the top of the page. It's a simple rotate node assigned to all cubes but only one is rotating. I will have to try a script instead because it's not working. Even if i select the object name for each node is still not working.

**Comment by luboslenco** [comment]
It looks like you are directly referencing the `Cube` object in your logic node tree:
![2](https://user-images.githubusercontent.com/3685704/53301422-f4f9dc00-3852-11e9-8a04-232f2f2ec0cd.PNG)

If you want to rotate the object which owns the trait instance, you can leave the `Object` field blank or use the `Self` node:
![1](https://user-images.githubusercontent.com/3685704/53301429-21155d00-3853-11e9-86bb-6db3c668bff4.PNG)

Also, to assign traits per object, go into the `Object` tab. (Scenes can posses traits too.)
![3](https://user-images.githubusercontent.com/3685704/53301489-bc0e3700-3853-11e9-8af5-756871d680ca.PNG)

Hope that helps!

**Comment by UglinessInTheUI** [comment]
That sounds like a good solution. Thank you very much.

**Comment by UglinessInTheUI** [comment]
I tried it and it doesn't work. I have no idea why it's not working. With the self node it should work but it still doesn't work. Could be a bug.

**Comment by UglinessInTheUI** [comment]
I had to delete all the cubes and it started to do something again. But it's doing some kind of pivoting now.

**Comment by luboslenco** [comment]
Did you assign the trait to the object in the `Properties - Object` panel like pictured above? (In your original file you were creating a Scene trait.)

**Comment by UglinessInTheUI** [comment]
I guess the trait is assigned to the scene by mistake. Sorry about that.

[ClonedRotate2.zip](https://github.com/armory3d/armory/files/2898354/ClonedRotate2.zip)

**Comment by UglinessInTheUI** [comment]
Definitely some kind of bug because the self rotation is not working. The properties are not updating.

**Comment by luboslenco** [comment]
You need to assign the trait in the `Object` tab instead of `Scene` tab. Check the active tab below:
![image](https://user-images.githubusercontent.com/3685704/53549707-2dd8d000-3b35-11e9-8c62-b60219096b21.png)

**Comment by UglinessInTheUI** [comment]
OK , i will try that. Thank you.

**Comment by UglinessInTheUI** [comment]
It's working. Finally. Thank you.
