### ISSUE TITLE
[Feature Request] - Add function or state to know if an audio object is playing or not

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#1196]
Through discussion on Discord, I believe it is not possible at the moment to know whether or not a sound is playing. 

It would be useful to have a boolean flag on a audio object that is set once audio is played.

In addition to this, it would be good to have events for:

- Audio Started
- Audio Finished
- Audio Paused

If there are functions for this then correct me, but looking through the API it doesn't seem like there currently is.

Thanks
*(drag & drop zipped .blend file here)*

**Comment by nanjizal** [comment]
Defaultsound,

When the sound is played it returns an AudioChannel:
``` haxe
var audioChannel: kha.audio1.AudioChannel =  iron.system.Audio.play(sound);
```
so I am guessing you can do something like
``` haxe
package arm;
import kha.audio1.AudioChannel;
class PlaySound extends iron.Trait {
        public var audioChannel: AudioChannel1;
        public var playing = false;
	public function new() {
		super();

		notifyOnUpdate(function() {

			var mouse = iron.system.Input.getMouse();

			// Mouse clicked
			if (mouse.started()) {
                                playing = true;
				iron.data.Data.getSound('beep.wav', function(sound:kha.Sound) {
					audioChannel = iron.system.Audio.play(sound);
                                        playing = true;
				});
			}
                        if( audioChannel != null ) if( audioChannel.finished ) playing = false;
 
		});
	}
}
```

note that AudioChannel has other properties such as length and position so you can actually work out how far you are through the sound.
``` haxe
if( audioChannel.finished == false ) percentPlayed = 100*audioChannel.position/audioChannel.length;
```

**Comment by AlexDBurrows** [comment]
Ah I see, I thought I might have missed a class. Thanks!

**Comment by Defaultsound** [comment]
Ah I see I thought I must have missed something, Thanks!

**Comment by luboslenco** [comment]
Reminder to add more info on this to the manual. 🙂

**Comment by luboslenco** [comment]
Updated manual at https://github.com/armory3d/armory/wiki/sound.
