### ISSUE TITLE
Armory didn't make a compile.inc when making the builds 0.6

### ISSUE THREAD

**Issue by DA64** [armory3d/armory#1197]
For an unknown reason when I start a new blender file, save it, then run it on armory, the program can't seem to find a file in the builds. I went to look and I noticed that the program forgot to make a compiled.inc file for the build, and it still does that every time I try to make a new blend file. Is there anyway on how I can fix this?

**Comment by luboslenco** [comment]
Hey @DA64, which OS are you on? Sometimes those are caused by permission issues. Can you see anything suspicious in the system console/terminal after building the project?

**Comment by DA64** [comment]
> Hey @DA64, which OS are you on? Sometimes those are caused by permission issues. Can you see anything suspicious in the system console/terminal after building the project? (before the missing file error comes up)

I have windows 10. I will go ahead and look in the console just to see what its doing.

**Comment by DA64** [comment]
Here's what I got 
Read prefs: C:\Users\froms\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Users\froms\Downloads\Armory\2.80\python
Armory: Proxy objects synchronized
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.generic.select_box.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\none.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.generic.cursor.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.transform.transform.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.transform.translate.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.transform.rotate.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.transform.resize.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.gpencil.draw.dat Unable to load from file
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.view3d.ruler.dat Unable to load from file
Read blend: F:\floatingCube.blend
Missing icons: C:\Users\froms\Downloads\Armory\2.80\datafiles\icons\ops.generic.select.dat Unable to load from file

Armory v0.6 ($Id: 988482e02afefe458b00e4dea75db2d01b76e49d $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 44)
Exporting Scene
Scene exported in 0.007979154586791992
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Traceback (most recent call last):
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\props_ui.py", line 501, in execute
    make.play()
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\make.py", line 468, in play
    build(target=runtime_to_target(), is_play=True)
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\make.py", line 352, in build
    export_data(fp, sdk_path)
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\make.py", line 157, in export_data
    write_data.write_compiledglsl(defs + cdefs, make_variants=has_config)
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\write_data.py", line 450, in write_compiledglsl
    with open(arm.utils.build_dir() + '/compiled/Shaders/compiled.inc', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build_floatingCube/compiled/Shaders/compiled.inc'

location: <unknown location>:-1

location: <unknown location>:-1

Armory v0.6 ($Id: 988482e02afefe458b00e4dea75db2d01b76e49d $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 44)
Exporting Scene
Scene exported in 0.007978677749633789
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Traceback (most recent call last):
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\props_ui.py", line 501, in execute
    make.play()
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\make.py", line 468, in play
    build(target=runtime_to_target(), is_play=True)
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\make.py", line 352, in build
    export_data(fp, sdk_path)
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\make.py", line 157, in export_data
    write_data.write_compiledglsl(defs + cdefs, make_variants=has_config)
  File "C:/Users/froms/Downloads/Armory/armsdk//armory/blender\arm\write_data.py", line 450, in write_compiledglsl
    with open(arm.utils.build_dir() + '/compiled/Shaders/compiled.inc', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build_floatingCube/compiled/Shaders/compiled.inc'

location: <unknown location>:-1

location: <unknown location>:-1
