### ISSUE TITLE
SetMaterialRgbParamNode doesn't really take material into account

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1198]
https://github.com/armory3d/armory/blob/master/Sources/armory/logicnode/SetMaterialRgbParamNode.hx

mat is an input that is never really used, except returning null if it's not set?

**Comment by Sandy10000** [comment]
Here is an example of using the Set Material RGB Param node.
https://github.com/armory3d/armory_examples/tree/master/material_params
It seems that the material input is used correctly.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/574f6ab96dd7c6d917ab9121b1b654c008d44035.

**Comment by trsh** [comment]
Thank you!
