### ISSUE TITLE
[FR] Enhance LoadingScreen

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1204]
I like how
https://github.com/armory3d/armory_examples/blob/master/load_screen/Sources/arm/LoadingScreen.hx

works, but is doesn't allow me to inject own preloading logic (like save game, cache some fonts or additional images, etc.).

```
override function ready(ready){
  // add my own preload logic
  if(isSomething) ready(); // assume all is done
}
```

Something like that?

**Comment by luboslenco** [comment]
Use scene trait to initialize additional stuff for now.

**Comment by trsh** [comment]
@luboslenco it's a bit strange to have 2 loading screens
