### ISSUE TITLE
Armor paint won't work

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armory#1208]
Hello! Today i tried armor paint out and it didn't start. I followed every step but it still not working.
Error:

D:\Armory engine\Armory\armsdk\Kha\Tools\haxe\std/haxe/io/Input.hx:189: characters 37-42 : Uncaught exception Eof
C:\Users\Noah\Documents\armorpaint-master\Sources/arm/Macro.hx:13: characters 27-49 : Called from here
For function argument 'text'

C:\Users\Noah\Documents\armorpaint-master\Sources/arm/UITrait.hx:19: lines 19-2098 : Defined in this class

Haxe compiler error.
Finished in 10.172865390777588
Build failed, check console

It would be very nice if this problem get solved.
Have a good day!!

**Comment by luboslenco** [comment]
Hello,

To fix your problem, you need to follow the steps as described: use `git clone https://github.com/armory3d/armorpaint` to download. Hope that helps! 🙂 

(Please open ArmorPaint issues at https://github.com/armory3d/armorpaint/issues.)
