### ISSUE TITLE
Customize khafile.js

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#121]
Is there any way to customize the generated khafile.js (like adding libraries/assets) yet?
I tried to write stuff in the Textfield in the Render Properties Panel under 'Armory Project => Khafile' in Blender, but that just seems to disappear. If there isn't, i'd also take a link to the sources where the file gets generated, so i can hack my own stuff into it for now.

Edit: just figured out it's blender/write_data.py

**Comment by luboslenco** [comment]
Yup, write_data.py it is. It should also work the non-hacky way, but you need to create new text data block in text editor and reference that in 'Armory Project => Khafile'. The contents of that will be appended to khafile.js. Hopefully the picture shows it clearer.

![khafile](https://cloud.githubusercontent.com/assets/3685704/22403785/5fcbee22-e622-11e6-8f27-1034a251c34c.jpg)

**Comment by sh-dave** [comment]
Works like a charm :+1:
