### ISSUE TITLE
Armory3d buggy wind shader!!

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armory#1210]
Hello! I have a problem. I use the shader from the celshade forest example for my grass model. When I apply it to my model,  it will be green and i don't want it, I have a texture on it. By the way can I use the shader for public? If no then can somebody recommend me a good website to learn glsl coding. It would be very nice if somebody can help me. I hope you have a good day!!!
![1](https://user-images.githubusercontent.com/41879104/53902985-c514ba80-4042-11e9-9311-184b031b45a8.png)
![2](https://user-images.githubusercontent.com/41879104/53902989-c645e780-4042-11e9-95c6-e5755bd65c35.jpeg)

**Comment by XQDD** [comment]
What's the two picutres represent? What effect do you want? And can you show the blender file?

**Comment by luboslenco** [comment]
Sorry that [shader](https://github.com/armory3d/driver_celshade_example/blob/master/Shaders/GrassMaterial.vert.glsl) does not handle textures, only color. Yes it's usable for public, I have added a [license](https://github.com/armory3d/driver_celshade_example/commit/c40882f77cfe315c20d06ba65c8277e1e5cfa4cb) file. Some basic 3d tutorials available [here](https://github.com/luboslenco/kha3d_examples)!

**Comment by Megalomaniak** [comment]
@luboslenco just needs an (optional - for those that want it) fragment shader to handle textures, no?

**Comment by luboslenco** [comment]
@Megalomaniak yes! It shouldn't be difficult to implement a variant of that shader which handles textures,
