### ISSUE TITLE
Looks like it might just be bug with the path handling : Error occurs when press [F5] key

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1213]
I no speak Americano.
I’m using Armory 0.6 for Win.
--------------------------------------
Save
Drive:\Filename …No good(Error occurred)
Drive:\Folder\Filename …Good(No problem)
--------------------------------------

1.Save [p:\untitled.blend]
2.Press [F5] key
3.Error occurs

Traceback (most recent call last):
File “P:Armory_06_win64/Armory/armsdk//armory/blender\arm\props_ui.py”,
line 501, in execute make.play()
File “P:Armory_06_win64/Armory/armsdk//armory/blender\arm\make.py”,
line 468, in play build(target=runtime_to_target(), is_play=True)
File “P:Armory_06_win64/Armory/armsdk//armory/blender\arm\make.py”,
line 352, in build export data(fp, sdk_path)
File “P:Armory_06_win64/Armory/armsdk//armory/blender\arm\make.py”,
line 157, in export_data write_data.write_compiledglsl(defs + cdefs,
make_variants=has_config)
File “P:Armory_06_win64/Armory/armsdk//armory/blender\arm\write_data.py”,
line 450, in write_compiledglsl with open(arm.utils.build_dir() + ‘/compiled/Shaders/compiled.inc’, ‘w’) as f:
FileNotFoundError: [Errno 2] No Such file or directory: ‘build_untitled/compiled/Shaders/compiled.inc’

location: :-1

location: :-1

Save [P:\New Folder\untitled.blend] no problem.
Error saving when saving directly under drive.
No problem when creating and saving folders.

**Comment by luboslenco** [comment]
Hello!

When saving directly under the drive letter Windows may prevent writing the files. Noted to prefer a safe path at [setup](https://armory3d.org/manual/#/getting_started/setup).
