### ISSUE TITLE
Faces Not Triangulated on Export

### ISSUE THREAD

**Issue by taholmes160** [armory3d/armory#1215]
*(drag & drop zipped .blend file here)*
I am working on an arch viz project, and when I cut a hole in the roof of the structure, it does not show in the armory player.  The hole was cut with a boolean --- the cutter is hovering above the model in the .blend file
[Roof After Boolean.zip](https://github.com/armory3d/armory/files/2949797/Roof.After.Boolean.zip)

This is the workspace view 
![image](https://user-images.githubusercontent.com/24684691/54088727-5b90f680-4337-11e9-8a7f-9368dada5fd1.png)

This is a quick EEVEE render of it
![image](https://user-images.githubusercontent.com/24684691/54088741-6ea3c680-4337-11e9-9b01-5a3ab36bad74.png)

Finally is a screenshot of the Armory Player

![image](https://user-images.githubusercontent.com/24684691/54088754-88dda480-4337-11e9-9855-e00961965b41.png)

The exact same thing happens when the hole is cut with a set of loops. 

I'd be glad to submit anything else that is needed as well -- please let me know

Tim

**Comment by Bugsbane** [comment]
As mentioned on [this forum post](http://forums.armory3d.org/t/problem-with-holes-cut-in-slanted-roofs/2835/3) this was just an issue with Armory not liking Ngons being used. When the mesh was triangulated, it works fine.

That said, if Blender can handle ngons and Armory can't, then we should really automatically apply a triangulate modifier to all ngons in a scene before compiling to fix these kinds of bugs.

**Comment by zicklag** [comment]
I'm pretty sure that Armory *is* supposed to triangulate the faces automatically on export, so I think this still counts as a bug, but we should rename the issue something like "Faces not triangulated on export".

**Comment by taholmes160** [comment]
Is that something the system will handle, or do I need to rename it?

Tim

**Comment by zicklag** [comment]
@taholmes160 You'll need to rename it.

**Comment by taholmes160** [comment]
Done

**Comment by BlackGoku36** [comment]
@luboslenco  Where is this automatic triangulate on export code?

**Comment by luboslenco** [comment]
@BlackGoku36 sounds good, the export code is located at:
https://github.com/armory3d/armory/blob/master/blender/arm/exporter.py#L1108
https://github.com/armory3d/armory/blob/master/blender/arm/exporter.py#L1239

Maybe helpful related issues:
https://github.com/armory3d/armory/issues/1148 https://github.com/armory3d/armory/issues/855

**Comment by XQDD** [comment]
Well

![image](https://user-images.githubusercontent.com/20871761/54369627-37c00e80-46b1-11e9-9989-2554fcbc80ce.png)

same after triangulate 

![image](https://user-images.githubusercontent.com/20871761/54369693-52928300-46b1-11e9-9d48-46f4b229e2f2.png)

[main.zip](https://github.com/armory3d/armory/files/2967191/main.zip)

**Comment by XQDD** [comment]
I think there should be a FAQ to explain some common mistakes...

**Comment by zicklag** [comment]
@XQDD Maybe you should start the doc. :smiley: I think that it isn't a bad idea. This is definitely something I would have liked to known about. Either an FAQ or a Tips & Tricks type document.

The docs repo is [here](https://github.com/armory3d/armory_docs) if you are interested.

**Comment by XQDD** [comment]
No problem, and when I'm free I will do this

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armory/pull/1401.
