### ISSUE TITLE
Emission map/tex makes models dark

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1217]
[test.zip](https://github.com/armory3d/armory/files/2951468/test.zip)

1) Models are dark
2) Remove emm. from node connection
3) Still lightning seems weird
4) Box in front seems weird rendered

Ubuntu bionic, arm 0.6 from itch

**Comment by Bugsbane** [comment]
I can confirm this behaviour in:
Armory v0.7 ($Id: f618d47c6cfb765b981cc21677d775fc25786df8 $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.80 (sub 44) (Itch download, upated to latest GIT)
Nvidia 390 driver

Rendering shows up dark:
![Screenshot_20190324_205032](https://user-images.githubusercontent.com/401733/54888775-8b331900-4e76-11e9-8777-918a4956d5e5.png)

Removing emission map removes the issue:
![Screenshot_20190324_205533](https://user-images.githubusercontent.com/401733/54888831-304df180-4e77-11e9-90cd-f7942c895c10.png)

Emission map itself seems to be properly created:
![_SciFi_Containers_emissive](https://user-images.githubusercontent.com/401733/54888828-144a5000-4e77-11e9-9460-9abb2f29d844.png)

Not sure about the cube. At first I thought it was probably inverted normals, however recalculating the normals with face outwards doesn't fix the issue. Neither does using a different material. Creating a new cube that uses the same material is rendered fine.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/46a7e81f40d1939fdc8a331468726893b236f4b7. Cube issue is related to https://github.com/armory3d/armory/issues/415.
