### ISSUE TITLE
Play Sound - wrong file name filtering

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#1218]
After adding a new sound via the sequencer, then selecting it in the Play Sound list, I get an Error : Could not open file ...  normal, as the caracters+space set by blender in front of the file name to see number of users, must be deleted from the input inside the Play Sound.
(Armory 0.6 /W10)

**Comment by luboslenco** [comment]
(Note to also investigate issue [here](http://forums.armory3d.org/t/play-sound-pb-filtering-the-sound-file-name-from-blender-2-8/2841/2).)

**Comment by luboslenco** [comment]
Hm, this is already supposed to be fixed in 0.6 via https://github.com/armory3d/armory/commit/f9f5bea10835d09bc4aceed11e0d22ce22c17fe9.

**Comment by Didiercode** [comment]
It was tested with the modif  type=bpy.types.Sound too ...

**Comment by luboslenco** [comment]
Sorry I do not follow, is this still throwing an error? If possible please link me with a blend file and I will investigate.

**Comment by Didiercode** [comment]
Hello Lubos
Thereafter a simple example 
[soundtest.zip](https://github.com/armory3d/armory/files/3029382/soundtest.zip)

**Comment by luboslenco** [comment]
Hm maybe you need to re-enter the `bow_shoot.wav` value? It appears to be ok here.:/
![1](https://user-images.githubusercontent.com/3685704/55829555-30a0ea80-5b0f-11e9-85a2-d1877403f364.PNG)

**Comment by luboslenco** [comment]
Hoping the value re-enter helped!
