### ISSUE TITLE
__default_data.arm

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#122]
I tried to publish a project via github pages (usual gh-pages every project can have), but it fails to load the __default_data.arm. Not sure exactly why, maybe something with the filename?

As a simple fix, i tried to rename everything with __default to aadefault (generated Scene.arm (with hex editor), __default_data.arm (with hex editor) and kha.js) and it actually works now!

You might just choose a different name for that particular file so this issue disappears?

**Comment by luboslenco** [comment]
Dammit, those naming issues. Thanks for report - should be fixed in https://github.com/armory3d/armory/commit/27a8736ce47f008033828c7697cc6672d2cb7a38.
