### ISSUE TITLE
Add-on install failure

### ISSUE THREAD

**Issue by GrahamWilkins** [armory3d/armory#1220]
I tried to install Armory as an add-on to Blender 2.7 onto my MacBook Pro. I carry out the instruction in the ’setup docs’ 
Download and unpack appropriate SDK for your platform.
In Blender, Select Edit - Preferences... and navigate to the Add-ons tab.
Click Install....
Select armory.py located in my_unpacked_sdk/Armory/armsdk/armory/blender/addon (on MacOS the location is my_unpacked_sdk/Armory/Blender.app/armsdk/armory/blender/addon).
Enable Armory add-on.
Set SDK Path property to my_unpacked_sdk/Armory/armsdk.
Before I carry out the next step I looked at the ‘Updater’ option and downloaded from https://git-scm.com/ 2.21.0. This worked fine but I could not locate the file </my_unpacked_sdk/Armory/armsdk/> via the ‘Update SDK’ link the error message said: there is no such file or directory <my_unpacked_sdk/Armory/armsdk>.

![Armory image](https://user-images.githubusercontent.com/40180953/54436462-7ba32a00-472a-11e9-835b-7edb97678e67.jpg)

I hit 'Save Preferences' and restarted Blender as instructed. Blender opens fine but there are no tools for Armory as described in the tutorial video.

I also tried to install the full Blender app via ‘Terminal’ I followed the instructions and renamed the file to prevent an overwrite of my working version. When I try to launch the verification process begins but I receive an error message 'Application is damaged’ and I will not open.

**Comment by Bugsbane** [comment]
The latest Armory (0.6) is only compatible with Blender 2.8+. Version 0.5 is compatible with Blender 2.7x however it's also deprecated and significantly behind v0.6 (and 0.7 in development).

**Comment by GrahamWilkins** [comment]
Thank you very much. As you might guess I'm very new to Armory. I now have both versions running and just beginning to get to grips with it. Are there any 0.6 tutorials available?

**Comment by Bugsbane** [comment]
No problem! I was new not that long ago, too! :P There are a bunch of resources, including places to watch tutorials, and general tips for new users at this forum thread, here:
http://forums.armory3d.org/t/faq-the-top-things-i-wish-i-knew-when-starting-with-armory/2871?u=armored_blob

**Comment by Amir-Arsalan** [comment]
I think this issue is relevant to [this](https://github.com/armory3d/armory/issues/1228)

**Comment by Bugsbane** [comment]
@Amir-Arsalan - They were trying to install git Armory (0.7) on Blender 2.7. Armory hasn't been compatible with Blender 2.7 since v0.5. Your issue is to do with the very recent Blender versions changing their API requirements for addons (even the most recent Armory).

**Comment by luboslenco** [comment]
Hopefully all good now. 🙂
