### ISSUE TITLE
All lamp strenght settings ignored

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1222]
Looks like it always uses a value of a little more than 1. 
occurs with 0.6 updated and from itch.io. Reinstalled Armory and still broken.
Win 10 GTX 1060 

_how has nobody noticed this yet 0.6 is already out for a month or is PC borked idk_

**Comment by philipmduarte** [comment]
Are you perhaps using the cycles engine? I had this same issue a while back, and it was because I was setting the light with the cycles engine on. Once I switched to eevee, the light was fine.

**Comment by Simonrazer** [comment]
Not working with eevee as well, "retail" and updated tested.

**Comment by Simonrazer** [comment]
Well ok, I have now discovered the way it works, but this way is not good. You NEED to use Eevee's Energy setting, not the Strength value of the node editor. Not intuitive for long-time Blender users. Pls make both things work.

**Comment by luboslenco** [comment]
I am not sure how to take both settings into account without bringing in more confusion. Eevee has its own light energy setting and Armory takes Eevee values since that gives a better viewport workflow.

**Comment by philipmduarte** [comment]
Sticking to eevee is fine by me. Other than that, maybe pick the values from the current rendering engine, but that would probably mean rewriting the scene parser in too many places so might not be worth it.

**Comment by luboslenco** [comment]
Let's stick with eevee then to keep things simpler..
