### ISSUE TITLE
Add-on is enabled in Blender 2.79b but there are no tools in the property settings.

### ISSUE THREAD

**Issue by GrahamWilkins** [armory3d/armory#1224]
[construction_blend.zip](https://github.com/armory3d/armory/files/2975551/construction_blend.zip)

*(drag & drop zipped .blend file here)*

**Comment by BlackGoku36** [comment]
Which Armory Version are you using?
0.6 from itch/latest git? then, sorry these armory version doesn't support blender 2.79b anymore and it will only support Blender 2.8 from now on.

0.5? did you try saving preference and restarting blender?

If you aren't sure about versioning, Then in blender, `Windows-Toggle system console`(Command prompt/Terminal should pop-up), paste here what you see

**Comment by GrahamWilkins** [comment]
Thank you for your response I appreciate that very much.

I had tried repeatedly to resolve the problem using so many options, however, this morning as soon as I saw your email, I tried again. It worked perfectly. I have no idea why. Problem resolved, thank you.

Regards Graham

**Comment by BlackGoku36** [comment]
Can you close this issue if it works 😃
