### ISSUE TITLE
Unable to assign a node tree to a scene 

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#1229]
I meet for the first time a problem when trying to assign a Node Tree to a scene.

I don't see the selected Tree name appearing in the list Armory Traits, even if the node tree is well activated during the Play. Seem a kind of refresh not done.

What could be the problem ?

![image](https://user-images.githubusercontent.com/20455592/55032200-a2a60980-5010-11e9-9de4-4f2d9f9dddb8.png)

**Comment by luboslenco** [comment]
Not sure I can reproduce this. Please paste a blend file if issue persists, will take a look.
