### ISSUE TITLE
Crash on player stop

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#123]
Like the title says, 
![error](https://cloud.githubusercontent.com/assets/15276930/22460514/72eb6a94-e7a5-11e6-9019-ccb5cd4007b5.png)

---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Blend file please. It looks like you have 2 viewports, notice another Play in Viewport button there.

**Comment by MagicalPaladin** [comment]
[test.zip](https://github.com/armory3d/armory/files/741648/test.zip)

**Comment by luboslenco** [comment]
Hm, you have two 3D viewports and trying to play in the one that is not visible. Can you try to merge those two into one 3D viewport and then hit play?

![test](https://cloud.githubusercontent.com/assets/3685704/22461353/318a110a-e7a9-11e6-9cc6-20975ab00ba7.jpg)

**Comment by MagicalPaladin** [comment]
works but crash when i hit stop

**Comment by luboslenco** [comment]
I think the blend file got corrupted, unable to even open it in standard Blender. Please create a new blend file and re-import data if needed.

**Comment by MagicalPaladin** [comment]
not working either
[test2.zip](https://github.com/armory3d/armory/files/741734/test2.zip)

**Comment by luboslenco** [comment]
This one works fine for me. Can you hit Window - Toggle System Console in Blender and see anything suspicious?

**Comment by MagicalPaladin** [comment]
Weird, everyting looks ok, but i've seen that line : wmSubWindowScissorSet 0: doesn't exist

**Comment by luboslenco** [comment]
So for every scene you hit Play in Viewport and then hit Stop, Blender crashes? If you test more examples - do they all crash on Stop?

**Comment by MagicalPaladin** [comment]
Work nicely on scene 3

**Comment by Nopotato** [comment]
Hello, I get a similar (same?) crash on user stop, but ONLY when I duplicate the viewer after pressing play. if I then stop it in the new viewer (they both run fine together) then It crashes every time.

**Comment by luboslenco** [comment]
No longer crashes, although only 1 viewport player instance works at a time for now.
