### ISSUE TITLE
No logs in Wasm API and I cannot use web_sys console in rust assembly

### ISSUE THREAD

**Issue by dancespiele** [armory3d/armory#1230]
The wasm API doesn't provide any log, I tried another way to get the console.log using wasm-pack (https://rustwasm.github.io/docs/book/reference/debugging.html) but I get the error in the browser that the module is not a object.

**Comment by dancespiele** [comment]
ok I think trace is for logs. I don't have experience with Haxe :)

**Comment by nanjizal** [comment]
Maybe worth looking at jsprime and NME in relation to c++ haxe in the browser, looking through code you may get some clues.
http://gamehaxe.com/demos/1000ogres/index.html
http://hughsando.com/2017/09/11/10-year-anniversary/
You can setup jsprime quite easily there is an example use of NME.
https://github.com/nanjizal/PolyominoTriangles/blob/master/compile/polyominoTrianglesNME.hxml#L4
there is also a Kha setup example so you can compare the approaches.
You will find more about jsprime via NME related pages.
http://nmehost.com/
Sorry I know it's different haxe toolkit but I think it may contain some useful stuff if you don't mind crawling through code.
