### ISSUE TITLE
Add a "Good First Contribution" Tag To Issues

### ISSUE THREAD

**Issue by zicklag** [armory3d/armory#1233]
Hey @luboslenco, could you add a Good First Contribution tag, or whatever GitHub calls it, to #1231 and #1232?

I put it in the title, but it would be better as a tag. I think it would be good to keep an eye out for those those kinds of issues and tag them for people who are wanting to get started in Armory development.

**Edit:** #1215 might be another good candidate.

**Comment by luboslenco** [comment]
It's [live](https://github.com/armory3d/armory/labels/good%20first%20contribution)! 😃

**Comment by zicklag** [comment]
Awesome, thanks!
