### ISSUE TITLE
Cannot open audio device default when running

### ISSUE THREAD

**Issue by DrLuke** [armory3d/armory#1235]
When I try to run the default startup scene with the Krom runtime, I get the following error in the console:

````
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
cannot open audio device default (Device or resource busy)
````

I am running on Arch Linux with pulseaudio. Please let me know if you need any more information.

Also, is there any way to disable the sound system so I can continue working?

**Comment by DrLuke** [comment]
Sound can be disabled in `Armory Project -> Modules`, but it still tries to open an audio device. Shouldn't it not do that when audio is disabled?

**Comment by sh-dave** [comment]
Are you a member of the `audio` group? I think we had that (or something quite similar) and it turned out one of the problems was a permission issue with the user.

**Comment by DrLuke** [comment]
I've added myself to the audio group but still get the same error. Good idea though!

**Comment by sh-dave** [comment]
Just to make sure, you rebooted / relogged as well?

Can you play sounds in the commandline with aplay?
- e.g. `aplay /usr/share/sounds/alsa/Rear_Right.wav`

**Comment by DrLuke** [comment]
Aha! Installing alsaplayer gives me the following error(s):

````
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
snd_pcm_open: Device or resource busy (default)
Failed to initialize plugin!
/usr/lib/alsaplayer/output/libalsa_out.so failed to load
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
jack: server not running?
/usr/lib/alsaplayer/output/libjack_out.so failed to load
error opening /dev/dsp
Failed to initialize plugin!
/usr/lib/alsaplayer/output/liboss_out.so failed to load
NOTE: THIS IS THE NULL PLUGIN.      YOU WILL NOT HEAR SOUND!!
libmikmod.so.3: cannot open shared object file: No such file or directory
libaudiofile.so.1: cannot open shared object file: No such file or directory
````

**Comment by DrLuke** [comment]
Reinstalling the package `pulseaudio-alsa` fixed the issue, some auto-generated configuration probably was wrong for whatever reason. Thank you!
