### ISSUE TITLE
VGI build failed

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#124]
i download example and try first person. when i unable vgi build failed
https://drive.google.com/open?id=0B3hadYdOOg8UcTJnYzdXQml1aEE

---
optional - drag & drop .blend file here

**Comment by Xristoskr** [comment]
same problem again
![14](https://cloud.githubusercontent.com/assets/23359603/23620790/dc7a061c-02a0-11e7-8ef0-63a7e51398b2.png)
![15](https://cloud.githubusercontent.com/assets/23359603/23620792/dc7fc840-02a0-11e7-8f3b-74dd19b07c9d.png)
i use you example cornell

**Comment by luboslenco** [comment]
You need to select C++ runtime and hit play, it will not work in viewport/krom yet. Do you have Visual Studio installed? (Visual Studio Community is enough)

**Comment by Xristoskr** [comment]
i dont have visual studio
