### ISSUE TITLE
Objects with material set to billboard won't scale

### ISSUE THREAD

**Issue by greyheron** [armory3d/armory#1245]
When using billboard material on an object, the only thing that can be changed during runtime is its location, changes to its scale won't do anything. Same if trying to assign a different material.

**Comment by greyheron** [comment]
Assign a different material so that's not a bug I had the wrong setup.

Scale is an issue, I have attached an example with two planes one set to billboard and the other one not, both have same trait attached to it: on click change its scale, only no billboard plane changes.

[billboard-scale-bug.zip](https://github.com/armory3d/armory/files/3040641/billboard-scale-bug.zip)

**Comment by BlackGoku36** [comment]
@luboslenco where is billboard script kept at?

**Comment by luboslenco** [comment]
@BlackGoku36 searching for `billboard` in armory and iron folders should display all the references to it (python UI, shader gen and passing uniforms).

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/iron/commit/4b03e47e77aa9dfeb271822da7d6cd0991bfa5a7, thanks for report!
