### ISSUE TITLE
Tessellated fur ?

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#125]
i would like to know how i can do that 
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
This is by no means an efficient approach to do fur, but one way I did the pic below was to just subdivide the sphere, throw a fur texture on it and a noisy displacement map for pointy look. Some value tweaking will also be necessary (for example for displacement strength).

For a proper fur/hair system additional work in Armory will be needed.

![fur](https://cloud.githubusercontent.com/assets/3685704/22605199/1439e14a-ea4f-11e6-8fd1-8c45cc5b51ab.jpg)
