### ISSUE TITLE
Snap package support [Feature Request]

### ISSUE THREAD

**Issue by mikeroyal** [armory3d/armory#1251]
I was wondering if you might have an interest in making [snap package](https://snapcraft.io/) version. Also, your app would be promoted on the [snap store page](https://snapcraft.io/store).

[Crafting your first snap](https://tutorials.ubuntu.com/tutorial/create-your-first-snap#0)

[Build and test snap](https://snapcraft.io/build)

[Getting Started snap template](https://github.com/snapcrafters/fork-and-rename-me)

**Comment by luboslenco** [comment]
In the future Armory may get primarily distributed as normal Blender add-on, without including the Blender copy itself. So it's probably best to keep things as is for now, thanks!
