### ISSUE TITLE
Timer node does not work

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1252]
This is the same as #1183 but with demo files.

The timer node does not work as expected. In the following setup it creates a cube once, and deletes it after a second. If the timer is invoked a second time, the cube is delete immediately.
Here's a zipped .blend file: [ontimer.zip](https://github.com/armory3d/armory/files/3070631/ontimer.zip)

![OnTimer](https://user-images.githubusercontent.com/47137964/55993455-6f6da680-5caf-11e9-91e0-864150fdf239.png)

![2019-04-11 23-09-18](https://user-images.githubusercontent.com/47137964/55993461-74325a80-5caf-11e9-82fd-46aa079c5c6c.gif)
The first time, space bar is pressed, the cube stays for one second, the other times it's deleted immediately.

**Comment by luboslenco** [comment]
Thanks for the blend file! Fix pushed at https://github.com/armory3d/armory/commit/4066143af8be0e93a2c7e2554b9621b913715033.
