### ISSUE TITLE
Allow drawing 3D lines/curves

### ISSUE THREAD

**Issue by tree786** [armory3d/armory#1253]
Feature request.

It would be handy if a 'draw line' function is implemented, which allows drawing lines (or curves using multiple line segments) by passing in two Vector3 arguments, which correspond to the starting and end points of the line. E.g. something along the lines of : `render_line(vec3 start_point, vec3 end_point)`

**Comment by luboslenco** [comment]
Some (primitive) line drawing is exposed in debug mode, small example here:
https://github.com/armory3d/armory_examples/tree/master/debug_draw

For non-debug purposes, adapting DebugDraw trait to the project needs could be a starting point:
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/internal/DebugDraw.hx

Enhancements to the DebugDraw welcome!
