### ISSUE TITLE
cannot make gi or ao work on armory-_-!

### ISSUE THREAD

**Issue by morningsashimi** [armory3d/armory#1255]
cannot make gi or ao work on armory-_-!
*(drag & drop zipped .blend file here)*
![question](https://user-images.githubusercontent.com/49634418/56176773-08066e00-5fb1-11e9-9a5b-bd2cf7473984.png)

**Comment by philipmduarte** [comment]
Armory is pretty demanding hardware-wise. Are you sure your machine can run voxel ao? My 2015 macbook pro can't, for instance. Notice there's a difference between voxel ao and screen-space ao.
Can you run the examples properly?

**Comment by morningsashimi** [comment]
Intel I5-3470
8 GB Memory
Geforce GTX 650 TI
OpenGL  version 4.6
![opengl](https://user-images.githubusercontent.com/49634418/56249597-32afff80-6061-11e9-8196-09dcda01f222.png)

**Comment by Bugsbane** [comment]
You're using an older version of Armory there (0.5 or earlier). Please try with the current version (0.6 or 0.7-Git via the "Update SDK" option in the addon options).

Please let us know if the example files work with a more recent version of Armory, thanks.

**Comment by morningsashimi** [comment]
error occur when Updating SDK
![question2](https://user-images.githubusercontent.com/49634418/56263605-6fe3b400-6098-11e9-8775-fb51631be712.png)
![question3](https://user-images.githubusercontent.com/49634418/56263612-74a86800-6098-11e9-89a3-fa1167593b4f.png)

**Comment by Bugsbane** [comment]
Not sure if this is the issue, but do you have Git installed?

**Comment by SumGaea** [comment]
Should probably use the Blender 2.8 (not 2.7) version of Armory from now if updating the SDK (=> itch.io 0.6).

**Comment by luboslenco** [comment]
Sorry only Blender 2.8 is supported now like mentioned. Armory 0.6 defaults to Direct3D11 on Windows, should make the voxel ao work on your machine.
