### ISSUE TITLE
has contact(Array)

### ISSUE THREAD

**Issue by than10AM** [armory3d/armory#1256]
We have a "on contact(Array) node".
![image](https://user-images.githubusercontent.com/31183489/56318684-f8795780-615f-11e9-9efb-ad4a44bf734b.png)
But there is no "has contact(Array)" node.
Coud this be fixed?

Sincerely Arthur.

**Comment by SumGaea** [comment]
Use two On Contact (Array) nodes. One set to Begin, the other to End. Route each into a Gate node Value, set it to AND. Also use Merge node (from the Arrays), route that into the Gate node In.

On Begin and While Gate is false you have a Has Contact (Array). If someone wants to test or make a picture feel free.

**Comment by MoritzBrueckner** [comment]
Was implemented in #1652, closing this issue now
