### ISSUE TITLE
Two scenes that mention Rigidbody in the same run, second crashes on RayCast?

### ISSUE THREAD

**Issue by blue24** [armory3d/armory#1258]
Hello.

My armory version was downloaded as Armory_06_win64.zip from https://armory3d.org/download.html

I've noticed, seemingly at random (initially), physics.rayCast causes a crash (or freeze: any Rigidbodies in-scene no longer fall, input is not responsive, etc.):

```
Uncaught exception:
                rayFrom.setValue(from.x,from.y,from.z);
                ^
TypeError: Unable to get property 'setValue' of undefined or null reference
   at rayCast (krom.js:5194:3)
   at update (krom.js:430:3)
   at iron_App.update (krom.js:1401:3)
   at Anonymous function (krom.js:25425:3)
   at kha_Scheduler.executeTimeTasks (krom.js:25309:4)
   at kha_Scheduler.executeFrame (krom.js:25261:3)
   at kha_SystemImpl.renderCallback (krom.js:25926:2)
```
...from the System Console window.

Crash occurs at 
<armoryFolder>\armsdk\armory\Sources\armory\trait\physics\bullet\PhysicsWorld.hx, line 305.

It is possible loading a  scene after one that has Rigidbodies causes "armory.trait.physics.PhysicsWorld.active.vec1" and vec2 (present in the file above) to become null for the rest of the game (through scene changes).

To test, I made a new project (attached below), cloned a scene with two cubes and a plane four times, and changed as follows:
scene1: nothing, no physics. cubes just float.
scene2: cubes and plane get Rigidbody. Cubes fall and hit the plane.
scene3: same as 2, plus cubes get a trait to do rayCasts checks and float above the ground if detected. It will continually fall a little and float.
scene4: copy of 3, no difference.

Each scene has a trait to change to another scene of that number if the 1, 2, 3, or 4 keyboard keys are pressed to see what scene change(s) cause a crash.

There is a file inside the attached project folder, Test.xlsx (Excel) with a table that summarizes that and another table (Scene Trials) that shows the outcomes of starting at different scenes and switching to different ones and indicates a crash (red text). Consistently, picking scenes 3 or 4 after picking 2 or picking 3 or 4 successfully once but picking either again causes the crash.

Possible fix: PhysicsWorld.hx, in line 60, change this line
    if (nullvec) {
to
    if(nullvec || vec1 == null || vec2 == null){
...this allows vec1 or vec2 being null to also indicate that vec1 and vec2 should be re-created.

If there are side-effects to this change (I don't understand why vec1 or vec2 would go null to begin with) or my use of "iron.Scene.setActive" in Sources/arm/ChangeSceneLogic.hx to change scenes is wrong or incomplete, I would like to know. I tried the fix myself and it seems to stop all crashes from the Scene Trials table in Test.xlsx.

Blender project: Blender project: [ray_scenechange_test.zip](https://github.com/armory3d/armory/files/3101067/ray_scenechange_test.zip)

My armory install is at C:\Armory_06_win64 on my machine, and it has to be at this exact same place on other machines for .hx files to be able to be opened in Kode Studio by the Edit Script button. This also seemed a little odd to me.

Thanks. I've never used the issues feature of github, so apologies if I did something wrong.

**Comment by luboslenco** [comment]
Super cool issue report, thanks! Pushed a fix at  https://github.com/armory3d/armory/commit/f036a63b9f9e5755a9176e97b0d889191c906649.

**Comment by blue24** [comment]
I see, making the two vars static also makes sense - they don't get reset to NULL just because a new PhysicsWorld is made between Scenes.

Thankyou, too.
