### ISSUE TITLE
Build 7 packed assets problem

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#126]
I downloaded build 7 to test the maze game sample and I can't run the game.

It seems there is a problem finding or extracting topanda.hdr. May be a path problem under Mac? ("Application Support" has a space). Ok, enough guesses :-) let me paste the log:

<pre>
Armory v17.01.1
/bin/sh: /Users/artur/Library/Application: No such file or directory
Traceback (most recent call last):
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/props_ui.py", line 491, in execute
    make.play_project(True)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make.py", line 348, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make.py", line 268, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make.py", line 80, in export_data
    world_outputs = make_world.build_node_trees(active_worlds)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make_world.py", line 25, in build_node_trees
    output = build_node_tree(world)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make_world.py", line 45, in build_node_tree
    parse_world_output(world, output_node, context)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make_world.py", line 120, in parse_world_output
    parse_surface(world, surface_node, context)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make_world.py", line 141, in parse_surface
    parse_color(world, color_node, context, envmap_strength_const)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/make_world.py", line 220, in parse_color
    mip_count = write_probes.write_probes(filepath, disable_hdr, mip_count, generate_radiance=wrd.generate_radiance)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//armory/blender/write_probes.py", line 79, in write_probes
    ' height=' + str(target_h)], shell=True)
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/Contents/Resources/2.78/python/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/Contents/Resources/2.78/python/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//"Kode Studio.app"/Contents/Kha/Kore/Tools/kraffiti/kraffiti-osx from="/Users/artur/Documents/Graphics/Projects/ArmoryExamples/games/mazeball/build/compiled/Assets/unpacked/topanda.hdr" to="build/compiled/Assets/envmaps/topanda_radiance.hdr" format=hdr width=1024 height=512']' returned non-zero exit status 127

location: <unknown location>:-1

location: <unknown location>:-1
</pre>

I'm having exactly the same problem with Scene 4 but with a different envmap file:

<pre>
subprocess.CalledProcessError: Command '['/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/.//armsdk//"Kode Studio.app"/Contents/Kha/Kore/Tools/kraffiti/kraffiti-osx from="/Users/artur/Documents/Graphics/Projects/ArmoryExamples/scene4/build/compiled/Assets/unpacked/envmap.hdr" to="build/compiled/Assets/envmaps/envmap_radiance.hdr" format=hdr width=1024 height=512']' returned non-zero exit status 127
</pre>

Scenes without environment maps are working perfect (Scene 1, Scene 2, Scene 3; for example).

I haven't tried these examples with build 6 to see if the path problem was already there. If you need more info and want me to test it, please, let me know.

System:
Mac OSX 10.12.3
Intel HD Graphics 6000
Armory Bundled Blender

**Comment by AndreaMonzini** [comment]
Hello,
the Mazeball game example works (slowly) here ( OS X® 10.11.6 ).
But with default Blender layout the Properties->Render options sometimes disappear after loading.

**Comment by luboslenco** [comment]
@arturjpv Oh my, it was indeed the space in the path - thanks for report!

As a quick fix you could apply this patch (https://github.com/armory3d/armory/commit/74808c224a4e3c5dce86ef22e586c2a108a1e5b2), or manually replace the lines in `/Users/artur/Library/Application Support/itch/apps/Armory3D/Armory/blender.app/armsdk/blender/write_probes.py`.

(Or use a path with no spaces, but that is probably not viable since you seem to be running through itch). Fix will be included in the next build out of the box.

@AndreaMonzini 
By options disappearing, do you mean Armory buttons? Any Python errors in console when that happens? Would like to tackle that.

If it is slow as in low framerate, try changing to Forward Path preset in Camera data options. Might help if your video card is tight on memory, since deferred renderer is hungry in this regard. (running in a smaller window should also help).

**Comment by arturjpv** [comment]
@luboslenco Perfect, patch applied and everything is working.

My preferred method of using armory would be to configure it as an add-on on a regular blender. Until that is possible, with play in viewport, I'm using armory from itch. In this way I'm keeping two separated versions of blender.

@AndreaMonzini With slow, do you mean the ball? I'm having a good render frame rate for my machine. If you mean the ball, try changing the friction of the ball in the physics data block.

**Comment by AndreaMonzini** [comment]
@luboslenco everything seems to disappear in the panel but then i discovered  that all was hidden and recoverable with scrollbar ( i t happen the first time i open the example).
image:
![armoryb7_1](https://cloud.githubusercontent.com/assets/12413409/22528337/24e4184e-e8d3-11e6-83dc-ad3acd6455d6.png)
and console:
`/Users/imac21/Desktop/Armory3D_Test/Armory/blender.app/Contents/MacOS/blender 
Read new prefs: /Users/imac21/Library/Application Support/Blender/2.78/config/userpref.blend
found bundled python: /Users/imac21/Desktop/Armory3D_Test/Armory/blender.app/Contents/MacOS/../Resources/2.78/python
read blend: /Users/imac21/Desktop/Armory3D_Test/armory_examples-master/games/mazeball/mazeball.blend`

Deferred low is faster but i still have some problem with friction in some directions.
Anyway when i play in viewport i see some errors in the console:

`Armory v17.01.1
CMFT info: Converting latlong image to cubemap.
CMFT info: Saving spherical harmonics coefficients to build/compiled/Assets/envmaps/topanda_irradiance.c
CMFT info: Done.
CMFT info: Converting latlong image to cubemap.
CMFT info: Resizing source image from 512x512 to 128x128.
Failed to translate text file to binary file.
Errors:
Error: IL Text Translator(line=370) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=374) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=441) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=444) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=488) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=491) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1081) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1084) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1120) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1123) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1160) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1163) near r1:  
	syntax error                                                              
Error: IL Text Translator(line=1200) near r2:  
	syntax error                                                              
Error: IL Text Translator(line=1203) near r2:  
	syntax error                                                              
Error: IL Text Translator(line=1240) near r2:  
	syntax error                                                              
Error: IL Text Translator(line=1243) near r2:  
	syntax error                                                              
Error: IL Text Translator(line=1280) near r2:  
	syntax error                                                              
Error: IL Text Translator(line=1283) near r2:  
	syntax error                                                              
Error: IL Text Translator(line=2159) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2163) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2230) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=2233) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=2277) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2280) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2345) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2348) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2409) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=2412) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=2456) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2459) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2525) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2528) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2589) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=2592) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=2636) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2639) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2705) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2708) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2769) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=2772) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=2816) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2819) near r3:  
	syntax error                                                              
Error: IL Text Translator(line=2885) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2888) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=2949) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=2952) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=2996) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=2999) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=3065) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=3068) near r6:  
	syntax error                                                              
Error: IL Text Translator(line=3129) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=3132) near r5:  
	syntax error                                                              
Error: IL Text Translator(line=3176) near r4:  
	syntax error                                                              
Error: IL Text Translator(line=3179) near r4:  
	syntax error                                                              

CMFT WARNING: CL Compilation failed:
<program source>:368:9: warning: double precision constant requires cl_khr_fp64, casting to single precision
    if (0.0 != color.w)
        ^
<program source>:461:9: warning: double precision constant requires cl_khr_fp64, casting to single precision
    if (0.0 != colorWeight.w)
        ^

CMFT info: Running radiance filter for:
	[srcFaceSize=128]
	[lightingModel=blinnbrdf]
	[excludeBase=false]
	[mipCount=8]
	[glossScale=7]
	[glossBias=3]
	[dstFaceSize=128]
CMFT WARNING: OpenCL failed!
CMFT info: Radiance -> Starting filter...
CMFT info: Radiance -> Utilizing 4 CPU processing threads.
CMFT info: Radiance -> ------------------------------------
CMFT info: Radiance ->  Device / Face /     Time /    Total
CMFT info: Radiance -> ------------------------------------
CMFT info: Radiance -> [CPU0]  |    1 |   0.002s |   0.002s
CMFT info: Radiance -> [CPU0]  |    1 |   0.002s |   0.004s
CMFT info: Radiance -> [CPU1]  |    1 |   0.002s |   0.004s
CMFT info: Radiance -> [CPU0]  |    1 |   0.002s |   0.006s
CMFT info: Radiance -> [CPU1]  |    1 |   0.002s |   0.006s
CMFT info: Radiance -> [CPU0]  |    1 |   0.002s |   0.008s
CMFT info: Radiance -> [CPU1]  |    2 |   0.005s |   0.011s
CMFT info: Radiance -> [CPU0]  |    2 |   0.005s |   0.013s
CMFT info: Radiance -> [CPU1]  |    2 |   0.005s |   0.017s
CMFT info: Radiance -> [CPU0]  |    2 |   0.005s |   0.018s
CMFT info: Radiance -> [CPU1]  |    2 |   0.005s |   0.022s
CMFT info: Radiance -> [CPU0]  |    2 |   0.005s |   0.023s
CMFT info: Radiance -> [CPU1]  |    4 |   0.015s |   0.037s
CMFT info: Radiance -> [CPU0]  |    4 |   0.015s |   0.038s
CMFT info: Radiance -> [CPU1]  |    4 |   0.015s |   0.052s
CMFT info: Radiance -> [CPU0]  |    4 |   0.015s |   0.053s
CMFT info: Radiance -> [CPU1]  |    4 |   0.015s |   0.067s
CMFT info: Radiance -> [CPU0]  |    4 |   0.015s |   0.069s
CMFT info: Radiance -> [CPU2]  |    8 |   0.042s |   0.110s
CMFT info: Radiance -> [CPU3]  |    8 |   0.039s |   0.116s
CMFT info: Radiance -> [CPU2]  |    8 |   0.058s |   0.181s
CMFT info: Radiance -> [CPU1]  |    8 |   0.115s |   0.182s
CMFT info: Radiance -> [CPU3]  |    8 |   0.068s |   0.195s
CMFT info: Radiance -> [CPU0]  |    8 |   0.080s |   0.197s
CMFT info: Radiance -> [CPU1]  |   16 |   0.181s |   0.363s
CMFT info: Radiance -> [CPU0]  |   16 |   0.168s |   0.365s
CMFT info: Radiance -> [CPU3]  |   16 |   0.178s |   0.373s
CMFT info: Radiance -> [CPU2]  |   16 |   0.205s |   0.386s
CMFT info: Radiance -> [CPU1]  |   16 |   0.183s |   0.547s
CMFT info: Radiance -> [CPU0]  |   16 |   0.197s |   0.562s
CMFT info: Radiance -> [CPU3]  |   32 |   0.408s |   0.780s
CMFT info: Radiance -> [CPU2]  |   32 |   0.396s |   0.782s
CMFT info: Radiance -> [CPU1]  |   32 |   0.390s |   0.947s
CMFT info: Radiance -> [CPU0]  |   32 |   0.411s |   0.973s
CMFT info: Radiance -> [CPU2]  |   32 |   0.462s |   1.244s
CMFT info: Radiance -> [CPU3]  |   32 |   0.477s |   1.258s
CMFT info: Radiance -> [CPU0]  |   64 |   0.967s |   1.940s
CMFT info: Radiance -> [CPU1]  |   64 |   1.008s |   1.955s
CMFT info: Radiance -> [CPU2]  |   64 |   0.934s |   2.178s
CMFT info: Radiance -> [CPU3]  |   64 |   0.931s |   2.189s
CMFT info: Radiance -> [CPU1]  |   64 |   0.872s |   2.828s
CMFT info: Radiance -> [CPU0]  |   64 |   0.935s |   2.875s
CMFT info: Radiance -> [CPU2]  |  128 |   1.812s |   3.991s
CMFT info: Radiance -> [CPU3]  |  128 |   1.835s |   4.023s
CMFT info: Radiance -> [CPU1]  |  128 |   1.806s |   4.633s
CMFT info: Radiance -> [CPU0]  |  128 |   1.837s |   4.712s
CMFT info: Radiance -> [CPU2]  |  128 |   1.269s |   5.260s
CMFT info: Radiance -> [CPU3]  |  128 |   1.239s |   5.263s
CMFT info: Radiance -> ------------------------------------
CMFT info: Radiance -> Total faces processed on [CPU]: 48
CMFT info: Radiance -> Total faces processed on <GPU>: 0
CMFT info: Radiance -> Total time: 5.263 seconds.
CMFT info: Saving build/compiled/Assets/envmaps/topanda_radiance.hdr [HDR 512x256 RGBE LatLong 1-faces 8-mips].
CMFT info: Done.
#2x1
#1x1
Exporting mesh Cube.001
Exporting mesh Cube.002
Exporting mesh Sphere
Scene built in 1.5071442127227783
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvTex_Rad_SSAO.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvTex_Rad_SSAO_CompoTonemap.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvTex_Rad_SSAO.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvTex_Rad_SSAO.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvTex_Rad_SSAO.arm).
Exporting asset 1 of 1 (world_Irr_EnvTex_Rad_SSAO.arm).
Exporting asset 1 of 1 (BallMat_data.arm).
Exporting asset 1 of 1 (MazeMat_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (scuffed-plastic-ao.jpg).
Exporting asset 1 of 1 (scuffed-plastic-normal.jpg).
Exporting asset 1 of 1 (scuffed-plastic-rough.jpg).
Exporting asset 1 of 1 (scuffed-plastic2-alb.jpg).
Exporting asset 1 of 1 (topanda.hdr).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (topanda_irradiance.arm).
Exporting asset 1 of 1 (topanda_radiance.hdr).
Exporting asset 1 of 1 (topanda_radiance_0.hdr).
Exporting asset 1 of 1 (topanda_radiance_1.hdr).
Exporting asset 1 of 1 (topanda_radiance_2.hdr).
Exporting asset 1 of 1 (topanda_radiance_3.hdr).
Exporting asset 1 of 1 (topanda_radiance_4.hdr).
Exporting asset 1 of 1 (topanda_radiance_5.hdr).
Exporting asset 1 of 1 (topanda_radiance_6.hdr).
Exporting asset 1 of 1 (topanda_radiance_7.hdr).
Exporting asset 1 of 1 (topanda_radiance_8.hdr).
Exporting asset 1 of 1 (topanda_radiance_9.hdr).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.001.arm).
Exporting asset 1 of 1 (mesh_Cube.002.arm).
Exporting asset 1 of 1 (mesh_Sphere.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (BallMat_mesh.frag.glsl).
Compiling shader 1 of 1 (BallMat_mesh.vert.glsl).
Compiling shader 1 of 1 (BallMat_shadowmap.frag.glsl).
Compiling shader 1 of 1 (BallMat_shadowmap.vert.glsl).
Compiling shader 1 of 1 (MazeMat_mesh.frag.glsl).
Compiling shader 1 of 1 (MazeMat_mesh.vert.glsl).
Compiling shader 1 of 1 (MazeMat_shadowmap.frag.glsl).
Compiling shader 1 of 1 (MazeMat_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvTex_Rad_SSAO.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvTex_Rad_SSAO.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvTex_Rad_SSAO_CompoTonemap.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvTex_Rad_SSAO_CompoTonemap.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvTex_Rad_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvTex_Rad_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvTex_Rad_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvTex_Rad_SSAO.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvTex_Rad_SSAO.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvTex_Rad_SSAO.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvTex_Rad_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvTex_Rad_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Image topanda_radiance.hdr
Image topanda_radiance_0.hdr
Image topanda_radiance_1.hdr
Image topanda_radiance_2.hdr
Image topanda_radiance_3.hdr
Image topanda_radiance_4.hdr
Image topanda_radiance_5.hdr
Image topanda_radiance_6.hdr
Image topanda_radiance_7.hdr
Image topanda_radiance_8.hdr
Image topanda_radiance_9.hdr
Image brdf.png
Image noise8.png
Image scuffed-plastic2-alb.jpg
Image scuffed-plastic-ao.jpg
Image scuffed-plastic-rough.jpg
Image scuffed-plastic-normal.jpg
Image topanda.hdr
`

**Comment by AndreaMonzini** [comment]
@arturjpv i changed the friction value and indeed works better ( thanks) but i still have some problems with the ball movement in some position and direction, for example very slow from top to bottom in the  example pic:
![mazeball](https://cloud.githubusercontent.com/assets/12413409/22528872/666a6a5a-e8d5-11e6-82ce-fbffe526708a.png)

**Comment by luboslenco** [comment]
I should probably adjust the friction value out of the box.

@AndreaMonzini It looks like [cmft](https://github.com/dariomanesku/cmft) binary used for processing environment maps under the hood is having troubles using GPU for that on your machine. It should still go fine using CPU only but takes longer time to complete. 

To (likely) get rid of the errors you can also force CPU use only, by unchecking *Armory Player - Advanced - GPU Processing*.

**Comment by AndreaMonzini** [comment]
@luboslenco no errors after i have disabled  Armory Player - Advanced - GPU Processing.
