### ISSUE TITLE
Armature/Bone transformation

### ISSUE THREAD

**Issue by ihmc3jn09hk** [armory3d/armory#1260]
Thanks so much on Armory3D development. Here I am having troubles on editing the bone's transformation of an armatured mesh. Following from the [issue](https://github.com/armory3d/armory/issues/397), I used the example_movebone from the [armory_example repository](https://github.com/armory3d/armory_examples) as a tutorial and test case. However, I cannot find a way to perform a transformation to scale a bone like the way in Blender->Pose mode does. The following images illustrate the problem. Can anyone help?

1. How to apply a transformation( Translate, rotate, scale ) to a bone like in Blender->Pose mode? _**Furthermore, I cannot find a member function rotate() for Mat4 class._
2. I simply modified the transformation to identity in the logic node "LogicBoneFK" but the Arm of the avatar is transformed incorrectly. _(The arm raised like in the 2nd image but without scaling)_
3. Is it a must to have an animation attached to the Object to perform armature modification?
4. Since the documentation does not mention any details, could someone explain those members/properties/variables meanings, e.g. skeletonMatsBlend?

Remarks: _The script of the example maybe outdated, e.g. MoveBoneFK.hx will compile with errors.
rename "multmat2" to "multmat" resolve it. And I think the logic is incorrect for the example. Point it out if I am wrong._
`m.setFrom(w);`
`m.translate(30, 0, Math.sin(iron.system.Time.time()) * 50);`
`iw.getInverse(w);`
`m.multmat(iw);`
To
`iw.getInverse(w);`
`m.multmat(iw);`
`m.translate(30, 0, Math.sin(iron.system.Time.time()) * 50);`
`m.multmat(w);`

**Expected transformation**
![image](https://user-images.githubusercontent.com/13495525/56732585-73f68c80-6790-11e9-849d-46060c7d4f33.png)

**Edited the scale=(1.5,1.5,1.5) at the '("LogicBoneFK")LogicNode->Transformation' node and run the player**
![image](https://user-images.githubusercontent.com/13495525/56732425-dc913980-678f-11e9-888b-6b3d34f27c67.png)
[animation_movebone.zip](https://github.com/armory3d/armory/files/3116655/animation_movebone.zip)

**Comment by knowledgenude** [comment]
Link to https://github.com/armory3d/armory/issues/1583
