### ISSUE TITLE
GI doesn't work

### ISSUE THREAD

**Issue by PtrMan** [armory3d/armory#1265]
### SHORT DESCRIPTION:
GI is broken on the official Win64 build (of armory 0.6).

### EXPECTED RESULT:
GI like in the video https://www.youtube.com/watch?time_continue=1&v=8KavBpfLLtY

### ACTUAL RESULT:
![image](https://user-images.githubusercontent.com/1067920/57185295-e9690800-6ec8-11e9-977b-8620d8d9b5b7.png)

### STEPS TO REPRODUCE:
* load file in example repo, press F5

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender: 2.80?
Armory: 0.6
Operating system: Win64 Windows 10
Graphics card & driver: Radeon™ RX 460, newest stable driver

**Comment by BlackGoku36** [comment]
https://github.com/armory3d/armory/issues/1066#issuecomment-481837222

**Comment by PtrMan** [comment]
I actually tried the GI path because I intended to play around with realtime GI - not AO

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/1325.
