### ISSUE TITLE
Android publish issues

### ISSUE THREAD

**Issue by OlafausBerlin** [armory3d/armory#1267]
Thanks for helping to contribute to Armory3D!
To help us fix your issue or implement your feature as quickly as possible, please fill out the following information as best you can:
Hi,
since this is my first post
thanks to the developers of Armory for their strength to do such a big project.  
I started to try Armory almost a week ago.
I downloaded an example file from Armory (pick.blend) to see if i can bring this to an Android device.
I had some problems (red errors and nodes were not updated when i changed something), it seems that this project was buid with an older version of armory.
So i decided to redo this project with Armory 0.6.
This project is just a cube on a plane.
The cube and the plane have rigidbodys. The cube has a box collider.
When you click with the mouse on the cube, the cube jumps one Unit on the z axis.
When i hit play in Armory, everything is fine.
![Klickcube](https://user-images.githubusercontent.com/50340215/57250982-00ceff00-7049-11e9-8e6e-c22053623843.gif)
When i export it to Windows, the cube jumps when i click on the cube.
When i build an apk in Android Studio, i can start the app, but when i click the cube, it does not jump.
The cube has a "mcube" trait with all the logic nodes that are necessary.
Please see the pictures with my settings.
![Logic-Nodes](https://user-images.githubusercontent.com/50340215/57250979-00366880-7049-11e9-9a00-0a83fdc0744e.jpg)
![Project Settings](https://user-images.githubusercontent.com/50340215/57250980-00ceff00-7049-11e9-97a8-37cebbb8d100.jpg)
![Publish Settings](https://user-images.githubusercontent.com/50340215/57250981-00ceff00-7049-11e9-83d5-be1021f713d7.jpg)
The console shows only one Error after i start ArmoryBlender (Error, region type 12 missing in - name:"View3d" , id:1).
I don´t have any publish errors in Armory.
I found out that Armory prepares the gradle output with all possible build variants for Android studio.
The default build variant seems to be set to "debug-x86".
My tests are done with the Nox Android emulator (Android 4.2.2, Android 5.1.1 and Android 7.1.2) and with my smartphone (Android 6.0.1).
I have some experience with "Unity" and a visual scripting asset.
When i use "mouse click" and "mouse pick" inside of Unity it also works as an arm full signed release apk inside of Nox (with a mouse)
and on my smartphone with touch.

Back to Armory:
My arm apk´s are build with "exclude "lib/x86_64/**" and "exclude "lib/x86/**" in build.gradle.
![build gradle](https://user-images.githubusercontent.com/50340215/57250977-00366880-7049-11e9-9c23-a9fb92045c6f.jpg)
Android Studio gives the following hint when i syncronize for x86_64 and x86
"Syncing only active variant You can disable this experimental feature from
File - Settings - Experimental - Gradle - Only sync the active variant"
I don´t have any errors in Android Studio when i build the apk´s.

Tests:
Nox (Android 4.2.2; Android 5.1.1; Android 7.1.2):
release-x86_64-unsigned.apk (Installation not possible)
release-x86-unsigned.apk (Installation not possible)
debug-x86_64.apk (App can be installed and runs)
debug-x86.apk (App can be installed and runs)
release-armeabi-v7a-unsigned.apk (Installation not possible)
release-arm64-v8a-unsigned.apk (Installation not possible)
debug-armeabi-v7a.apk (App can be installed and runs)
debug-arm64-v8a.apk (App can be installed and runs)
[debug-arm64-v8a.zip](https://github.com/armory3d/armory/files/3149647/debug-arm64-v8a.zip)
[debug-armeabi-v7a.zip](https://github.com/armory3d/armory/files/3149648/debug-armeabi-v7a.zip)
[release-arm64-v8a-unsigned.zip](https://github.com/armory3d/armory/files/3149649/release-arm64-v8a-unsigned.zip)
[release-armeabi-v7a-unsigned.zip](https://github.com/armory3d/armory/files/3149650/release-armeabi-v7a-unsigned.zip)
[debug-x86.zip](https://github.com/armory3d/armory/files/3149651/debug-x86.zip)
[debug-x86_64.zip](https://github.com/armory3d/armory/files/3149652/debug-x86_64.zip)
[release-x86-unsigned.zip](https://github.com/armory3d/armory/files/3149653/release-x86-unsigned.zip)
[release-x86_64-unsigned.zip](https://github.com/armory3d/armory/files/3149654/release-x86_64-unsigned.zip)
The cube never jumps and this makes him sad.

I did another project with a cube that only rotates (no mouse action)
and the cube rotates even in Nox.

What am i doing wrong ?
Is it already possible to build a full signed release apk in Armory that runs?
   

(Sorry if my english has bugs, i am not native english)

[KlickCube.zip](https://github.com/armory3d/armory/files/3149623/KlickCube.zip) (Blendfile)

**Comment by knowledgenude** [comment]
Already was fixed
