### ISSUE TITLE
[Bug] 'COLOR' enum for `color_space` no longer valid

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#1272]
Downloaded blender 2.8 build : `2019-05-13 19:09` hash : `27d097e92d54` and I can't build my project unless I change line `471` in `cycles.py`.

The drop down for color spaces on the texture image no longer have the `Color` option. The line is used again on `479`.

I thin kit should be `Raw` now? But im not sure.

**Comment by luboslenco** [comment]
Patched now at https://github.com/armory3d/armory/commit/f9b268310d7940aa99ba17e8b57f8472a05ec035, thanks for notice!
