### ISSUE TITLE
How to import an object correctly?

### ISSUE THREAD

**Issue by Gravicapot** [armory3d/armory#1274]
How to import an object into the editor to start the engine? Object scaling does not work for me. (Transformation) I set my values. After starting F5, all values of the object are reset.

Thank. And I apologize for my English)

**Comment by BlackGoku36** [comment]
Try clean building by pressing `Clean` button next to `Run` in `Armory Player`

**Comment by Gravicapot** [comment]
I made a [video](https://youtu.be/GVFE5FyFGJ0) to understand my problem.  The imported object constantly resets the settings.

**Comment by Gravicapot** [comment]
Maybe I import wrong?

**Comment by luboslenco** [comment]
@Gravicapot it looks like your imported object contains animation data, which then overrides your transformation changes.

Try expanding the `Box02_LOD_HIGH` object in outliner, right-click on its animation entry - `Clear Animation Data` to make it work. Unchecking `Import Animation` during fbx import may also work.

![1a](https://user-images.githubusercontent.com/3685704/58022226-4e4d7080-7b0d-11e9-83ed-c64be91c43e6.PNG)

**Comment by Gravicapot** [comment]
It works! Hell, I'm never so happy. Thanks friend, more thanks !!!

**Comment by luboslenco** [comment]
Yay! Happy to hear!
