### ISSUE TITLE
App icon for launchers

### ISSUE THREAD

**Issue by 1l0** [armory3d/armory#1276]
For now, Armory uses Blender icon instead of original one that confuse me a bit when I launch the app from app launchers.

![Screenshot from 2019-05-19 09-32-01](https://user-images.githubusercontent.com/3931445/57976581-980b5d80-7a1e-11e9-9a91-b0bde9722ead.png)

So I created an icon for that by copying your work.

![Screenshot from 2019-05-19 10-09-26](https://user-images.githubusercontent.com/3931445/57976582-9a6db780-7a1e-11e9-9b44-171a6a0eec2d.png)

Can I upload this to GitHub?

**Comment by luboslenco** [comment]
Totally, please do! 🙂
