### ISSUE TITLE
Logic nobes for multiplayer (feature request )

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#1280]
example https://docs.unrealengine.com/en-us/Resources/Showcases/BlueprintMultiplayer

**Comment by RomStef** [comment]
i'm intrested too in this feutures , i have found this library for haxe for managing the socket communication. Maybe it can be implemented in the nodes system

https://lib.haxe.org/p/udprotean/

**Comment by MoritzBrueckner** [comment]
Implemented in https://github.com/armory3d/armory/pull/2658.
