### ISSUE TITLE
every custom glsl shader doesn't work in armory3d!!pls help

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armory#1285]
Hey there! Every time when I am writing a custom glsl shader in armory an try to play it, I always get this error after writing it correctly:

ERROR: 2 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link

Compiling shader 1 of 2 (MyMaterial.frag.glsl) failed:
Shader compiler error.
(node:8532) UnhandledPromiseRejectionWarning: Shader compiler error.
(node:8532) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8532) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERROR: C:\Users\Noah\Documents\Haxe\build_Haxe\compiled\Shaders\Project\MyMaterial.vert.glsl:6: 'gl_ModelViewProjectionMatrix' : undeclared identifier
ERROR: C:\Users\Noah\Documents\Haxe\build_Haxe\compiled\Shaders\Project\MyMaterial.vert.glsl:6: 'assign' :  cannot convert from ' temp float' to ' gl_Position 4-component vector of float Position'
ERROR: C:\Users\Noah\Documents\Haxe\build_Haxe\compiled\Shaders\Project\MyMaterial.vert.glsl:6: '' : compilation terminated
ERROR: 3 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link

Compiling shader 2 of 2 (MyMaterial.vert.glsl) failed:
Shader compiler error.
Finished in 0.8326117992401123
Build failed, check console

I would be so happy if there is a solution for this.

**Comment by luboslenco** [comment]
Hi! Are you able to paste your project / shaders? It looks like there are some compilation errors:
`MyMaterial.vert.glsl:6: 'gl_ModelViewProjectionMatrix' : undeclared identifier`

**Comment by Noahthenoob53** [comment]
Hey Lubos!! Here is my project.
[SHADER.zip](https://github.com/armory3d/armory/files/3241098/SHADER.zip)

**Comment by luboslenco** [comment]
Thanks for sharing your project!

`gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;`

That is an ancient glsl now. 🙂 For `#version 450` which armory uses, try checking Kha tutorials [here](https://github.com/luboslenco/kha3d_examples/wiki) or armory example [here](https://github.com/armory3d/armory_examples/tree/master/material_shaders/Shaders).
