### ISSUE TITLE
Shading error

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1286]
The following geometry will not render corretly in Krom:

![Shading](https://user-images.githubusercontent.com/47137964/58664384-d104d580-832e-11e9-8119-c9aee10212f4.png)

It is one object with two colors assign, the left heart is no watertight model (it has a hole on the bottom), the second is watertight, but doesn't render correctly, either.

Herer's the .blend:
[Shading.zip](https://github.com/armory3d/armory/files/3238733/Shading.zip)

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/1215.

**Comment by blackno666** [comment]
When triangulating first, I obtain only white hearts.... is this how it should be?

**Comment by luboslenco** [comment]
Yes, see https://github.com/armory3d/armory/issues/1215#issuecomment-472935541. You should get the same result in Blender with `Viewport Shading - Backface Culling` enabled. You can use `Recalculate Normals` to fix that.
![1aa](https://user-images.githubusercontent.com/3685704/58704324-e1a76100-83ab-11e9-95e6-60cea24b278d.PNG)
