### ISSUE TITLE
animation problem

### ISSUE THREAD

**Issue by PixelSonic101** [armory3d/armory#1287]
Thanks for helping to contribute to Armory3D!
To help us fix your issue or implement your feature as quickly as possible, please fill out the following information as best you can:

### SHORT DESCRIPTION:
OK so I imported a animation and it's always crashing.

### EXPECTED RESULT:
_What did you expect to happen? For a feature request, what would you like to happen?_

### ACTUAL RESULT:
_What happens right now that's different from how you expect or want it to work?_

### STEPS TO REPRODUCE:
_Please list clear, step by step instructions to replicate the result you got. For a feature request list the steps to use the feature._
Steps:
1.
2.
3.
etc.

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender: 2.80
Armory: 06
Operating system: windows 10
[untitled.zip](https://github.com/armory3d/armory/files/3244749/untitled.zip)

Graphics card & driver:

### TEST FILE TO REPRODUCE:
_Please create the simplest file possible that demonstrates the issue:_
*(drag & drop the zipped .blend file here)*

**Comment by knowledgenude** [comment]
No crash running the .blend, so i can't confirm the issue.
