### ISSUE TITLE
Scripts codes not working in armory3d please help

### ISSUE THREAD

**Issue by blusmtusm** [armory3d/armory#1291]
hi i using armory3d and when i launch the armory player game working but scripts not working i watch tutorial try download examples but in all this things scripts codes not working

i mean the object is not moving i try made cube move left or right but codes not working please help me

even on examples wich made other people project script not working but player is launch

i use windows 7

**Comment by luboslenco** [comment]
Hey @blusmtusm, are you able to zip your project and paste it here? Which examples did you try?

**Comment by blusmtusm** [comment]
i try this one from tutorial is attached

also i try made the same as on video but coding not working
https://youtu.be/wR3gnGQ-GCQ

пт, 7 июн. 2019 г. в 08:46, Lubos Lenco <notifications@github.com>:

**Comment by luboslenco** [comment]
In your project the `CubaTrait.hx` file appears to be empty:

```hx
package arm;

class CubaTrait extends iron.Trait {
	public function new() {
		super();

		// notifyOnInit(function() {
		// });

		// notifyOnUpdate(function() {
		// });

		// notifyOnRemove(function() {
		// });
	}
}
```

**Comment by blusmtusm** [comment]
but why i type script maybe need aplly it but how to apply after i mean i
type edit script type code close thins not enough maybe need apply script
how to do this?

maybe problem of this

пт, 7 июн. 2019 г. в 09:10, Lubos Lenco <notifications@github.com>:

**Comment by luboslenco** [comment]
Try opening the `CubaTrait.hx` file in your favorite text editor, type the code and make sure to save the file. Armory should then pick it up.

**Comment by blusmtusm** [comment]
but i type the code in armory code editor so i ask how to apply to and save
it when i close the project and open i can see the code

but you tald me it emprty so code was like this :

package arm;

import iron.math.Vec4;

class CubaTrait extends iron.Trait {
    public function new() {
        super();

        // notifyOnInit(function() {
        // });

        notifyOnUpdate(function() {

         var mouse = iron.system.Input.getMouse();

            object.transform.rotate(Vec4.zAxis(), mouse.movementX * 0.003);

        });

        // notifyOnRemove(function() {
        // });
    }
}


пт, 7 июн. 2019 г. в 09:27, Lubos Lenco <notifications@github.com>:

**Comment by blusmtusm** [comment]
> 
> 
> Try opening the `CubaTrait.hx` file in your favorite text editor, type the code and make sure to save the file. Armory should then pick it up.

bro thank i try svae the code and its working i love you thanks for help this topic is solved

**Comment by luboslenco** [comment]
Yay, happy you got it to work!
