### ISSUE TITLE
Bug With Audio Sounds in Armory3d on windows

### ISSUE THREAD

**Issue by blusmtusm** [armory3d/armory#1294]
hi i has windows 7 i know the code i did is right i setup sound to object fireSound when it shoot

but when i launch the game game is working sounds isn't working correctly it start play without pushing button i set to it sound

and it plays endless with delay and non stop

why this when this bug be solved is big lose game without sounds

**Comment by luboslenco** [comment]
Hello @blusmtusm, please attach the project if possible, I can then investigate further.

**Comment by blusmtusm** [comment]
thanks this post was two weeks ago some one try help only now but i already solve this bymyself

now sound is working correct i try different script from different tutorial and it was work

so for now this topic solved and closed thanks
