### ISSUE TITLE
playing a animation closes armory?

### ISSUE THREAD

**Issue by PixelSonic101** [armory3d/armory#1296]
ok so I wanted to test this animation in armory so I click play but always closes
so what am I doing wrong
https://www.youtube.com/watch?v=MkUJq3VVaxY&t=6s

here is the console
![image](https://user-images.githubusercontent.com/44338582/59562918-64037680-9076-11e9-891a-ce5401ed79cf.png)

**Comment by luboslenco** [comment]
Probably a bug in armory animation exporter, but it's hard to tell exactly. If possible pasting any reproducible samples is welcome.

**Comment by PixelSonic101** [comment]
I can send you my project if that helps
https://drive.google.com/file/d/1tkNihrvqf2NRHDisLtXBUtdXO05wH3-k/view?usp=sharing

**Comment by luboslenco** [comment]
Thanks for sharing the file - it should run fine now using the latest `ArmorySDK-2019-08`, but please disable `Dynamic Resolution` in `Render Path` properties for now. (or apply https://github.com/armory3d/armory/commit/ff5cf50e4edc8a692c1ddb8330a0cd97a4a35bb0 / update to the latest git after downloading `ArmorySDK-2019-08` 🙂).
