### ISSUE TITLE
noob error with new scene, no compile.inc found

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#1302]
### SHORT DESCRIPTION:
New blend, add a cube and hit play -> error

### EXPECTED RESULT:
see a cube in krom

### ACTUAL RESULT:
Armory v0.6 ($Id: 988482e02afefe458b00e4dea75db2d01b76e49d $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 44)
Exporting Scene
Scene exported in 0.0047070980072021484
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Traceback (most recent call last):
  File "E:/armory/armsdk//armory/blender\arm\props_ui.py", line 501, in execute
    make.play()
  File "E:/armory/armsdk//armory/blender\arm\make.py", line 468, in play
    build(target=runtime_to_target(), is_play=True)
  File "E:/armory/armsdk//armory/blender\arm\make.py", line 352, in build
    export_data(fp, sdk_path)
  File "E:/armory/armsdk//armory/blender\arm\make.py", line 157, in export_data
    write_data.write_compiledglsl(defs + cdefs, make_variants=has_config)
  File "E:/armory/armsdk//armory/blender\arm\write_data.py", line 450, in write_compiledglsl
    with open(arm.utils.build_dir() + '/compiled/Shaders/compiled.inc', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build_armorytest/compiled/Shaders/compiled.inc'

I diff with the tutorial blend file:
![image](https://user-images.githubusercontent.com/65325/59964386-21232200-9500-11e9-98c1-63790076ff52.png)

### STEPS TO REPRODUCE:
1. new blend file
2. add a cube
3. Armory Player > hit play

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender: 2.80 (coming with Armory 06
Armory: 06
Operating system: Win10Pro
Graphics card & driver: GTX970

**Comment by luboslenco** [comment]
Hey, so the tutorial file works but the default cube does not? Any chance you are storing your .blend file directly under the drive root? If so moving `E:\armorytest.blend` to something like `E:\projects\armorytest.blend` might help, otherwise Windows prevents writing the files.

**Comment by j2l** [comment]
Hahaha, I never thought of this one!!
Thank you!
Fixed for me.
