### ISSUE TITLE
@prop does not work in hx files residing in subfolder

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1306]
Armory v2019.6 ($Id: a1f62c5c53fd416d5483932a490fe041c6af29f3 $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 74)

Using the @prop keyword in a .hx file will expose the property to the UI. This does not work for .hx files residing in subfolders (created by nameing the Trait [subfoldername].[Traitname])

The following screenshot shows to scripts with basically the same content, but one is in the subfolder "sub". The property "myvalue" will not show (left side of the screen). The script not in a sub folder shows the property correctly (right side of the screen).

![prop](https://user-images.githubusercontent.com/47137964/60127501-a1f84d00-9790-11e9-8071-704fc0fd6540.png)

**Comment by luboslenco** [comment]
Closed via https://github.com/armory3d/armory/pull/1314.
