### ISSUE TITLE
batch meshes broken

### ISSUE THREAD

**Issue by Redfill** [armory3d/armory#1312]
when activating batch Meshes and instanced children is activated (any of the option) the mesh gets destroyed or simply doesn't render
![image](https://user-images.githubusercontent.com/18517879/60694360-e0d28500-9eab-11e9-934a-ee06a4de2413.png)

### STEPS TO REPRODUCE:

1. have batch meshes and instance children on
2. spawn object

### TECHNICAL SPECIFICATIONS:
Blender: 2.8
Armory: latest from git 
Operating system: Ubuntu 18.04
Graphics card & driver: gtx 950 & 430.26 driver

[instance.zip](https://github.com/armory3d/armory/files/3360913/instance.zip)
(press w to spawn new one)

**Comment by luboslenco** [comment]
Appears to work now without mesh getting destroyed.
