### ISSUE TITLE
Incompatibilities with jack audio

### ISSUE THREAD

**Issue by parsashahzeidi** [armory3d/armory#1313]
Even tho I don’t use any audio in my blend file, Armory seems to fail to run since I’m using Jack instead of PulseAudio. The app seems to build correctly but only manages to stay open for 1 frame and crashes immediately.  Here's the error:
https://pastebin.com/ZFWgAWBs

It does seem to work with PulseAudio, but I didn't try it on the newer versions.
Using Blender 2.8, 
Git Armory
Kubuntu 19.04
Intel Integrated 5000, Jack audio bridged with Alsa, Cadence

**Comment by luboslenco** [comment]
Any luck using ArmorySDK1909?
