### ISSUE TITLE
target c++ in  Armory 0.6

### ISSUE THREAD

**Issue by creutzerb** [armory3d/armory#1315]
DESCRIPTION:
I tried targeting C++ because I want to use a haxe library with limited build targets.
I created a new custom preset in the Armory Exporter and left Khamake empty.
Project generates fine.
Project builds fine.

RESULT:
I get an error shortly after the "Starting Application" message.
(Error Begin before you end)
( I get the same "Microsoft C++ exception: Dynamic at memory location..." on a clean project with only the default blender scene )

QUESTION:
Is the C++ target currently supposed to be supported by armory3D ?

TECHNICAL SPECIFICATIONS:
Windows 10 - VS2017
Blender: version: 2.80 (sub 74)
Armory: 0.6.0 (updated sdk in preferences/addon)

**Comment by luboslenco** [comment]
C++ target is still supposed to work, any change if you switch graphics api to Direct3D11 (for custom it defaults to opengl)? That way it appears to run ok for me, testing the default cube.

**Comment by creutzerb** [comment]
Pretty much the same result. 
I don't think I had `Error 20 (this feature has not been implemented yet) in function AVolute::GetProductInfoT::<lambda_3f1b9fa7ebe823e68fd50ffbde777b68>::operator ()` before, but I could be wrong. 
I still get `Error Begin before you end` depending on the config.
I have tried debug/release x64/x86.
Anything I should know about Visual studio config ? I don't use it much.
(SDK version : 10.0.17763.0, Platform toolset : Visual Studio 2017 (v141)
Thanks.

**Comment by luboslenco** [comment]
I tested with the latest `ArmorySDK-2019-08` + VS 2019 + D3D11 now and it still works out of the box for me.:( Kha defaults to VS 2019 nowadays, so that is why you have to retarget the project.

Publish will export everything from scratch and remove old build files to produce a clean build.

**Comment by creutzerb** [comment]
Thanks for your reply.
My project is on standby for now. If I get back to it I'll probably cleanup all the visual studio mess I have right now hopefully it works right away. Installing VS 2017 did not go smoothly with the other versions installed, but I don't want to break other projects that currently work...
