### ISSUE TITLE
Player not starting on OSX when run Blender from command line

### ISSUE THREAD

**Issue by zevarito** [armory3d/armory#1316]
### SHORT DESCRIPTION:
When Blender has been launched from terminal (to have log access), Armory Player doesn't work.

### EXPECTED RESULT:
I'd expect player open as it does when Blender has been launched from OSX Finder.

### ACTUAL RESULT:
After compile shaders fails with:
```
...
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
File "_build/src/context/common.ml", line 458, characters 21-27: Assertion failed
Build failed, check console
```

### STEPS TO REPRODUCE:
1. Open terminal
2. Launch `blender` binary from MacOS folder inside /Applications/Blender2.8
3. Open Armory3D Scene and hit F5

### TECHNICAL SPECIFICATIONS:
Blender: 2.8 Alpha
Armory: Latest source from armsdk
Operating system: MacOS Mojave 10.14.4
Graphics card & driver: ATI

**Comment by zevarito** [comment]
I was able to move one step by removing homebrew `haxe` and properly setup `HAXE_STD_PATH`, but still cannot make the Player run when Blender has been launched from a shell.

Now the problem comes after (logs bellow) when a osx popup `Krom quit unexpectedly... Ignore, report, reopen` appears.

I would like to know if these logs are from Krom, and if so, how I can visualize them when run the project from Kode where I don't see anything like that.
My goal is to have one environment compiling and running with full logs, doesn't matter if it will be blender or Kode.

```
Finished in 0.7164809703826904
deviceBufferSize = 4096
mSampleRate = 44100
mFormatFlags = 00000009
mBytesPerPacket = 8
mFramesPerPacket = 1
mChannelsPerFrame = 2
mBytesPerFrame = 8
mBitsPerChannel = 32
```

**Comment by zevarito** [comment]
I was able to get a few more log lines, looks weird.

```
GL Error 1286 /Users/lubos/Downloads/Krom/Kore/Backends/Graphics4/OpenGL/Sources/Kore/OpenGL.cpp 284
```

**Comment by luboslenco** [comment]
Hey, any luck using the `ArmorySDK-2019-08` build if you get to try it?
