### ISSUE TITLE
Voxel AO issues on Intel graphics

### ISSUE THREAD

**Issue by VicentGJ** [armory3d/armory#1318]
#SHORT DESCRIPTION:
Voxel AO in Linux produces artifacts when using Intel GPUs in Linux.

### EXPECTED RESULT:
![voxels work good](https://user-images.githubusercontent.com/52976500/61326093-10ef2180-a7e4-11e9-9249-5e19ddd06148.png)

### ACTUAL RESULT:
![voxels issues intel](https://user-images.githubusercontent.com/52976500/61326112-1a788980-a7e4-11e9-8b56-49d037d00c57.png)

### STEPS TO REPRODUCE:
Steps:
1. Add a Cube and a light to a blank scene.
2. Turn on Voxel AO under the Voxels tab in Render Path.
3. Play the project.

### TECHNICAL SPECIFICATIONS:
Armory: 0.6
Operating system: Manjaro Linux
Graphics card & driver: Intel UHD 620 with Mesa 19 driver

### TEST FILE TO REPRODUCE:
[VX AO.zip](https://github.com/armory3d/armory/files/3398943/VX.AO.zip)

**Comment by VicentGJ** [comment]
I dont know yet if is a Linux only issue. It is maybe because of Mesa drivers for Intel not supports opengl 4.5 if voxel AO depends of it.

**Comment by luboslenco** [comment]
Yeah, 4.4 is the minimum - need to implement https://github.com/armory3d/armory/issues/1031 to make it obvious.
