### ISSUE TITLE
Armory Krom build crashes every time a sound is played

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#1319]
### SHORT DESCRIPTION:
Add a "play sound" or "play speaker" node. Crashes. Latest Git build.

### EXPECTED RESULT:
Play a sound.

### ACTUAL RESULT:
Crashes.

### STEPS TO REPRODUCE:
Steps:
1. Add node for sound
2. Test in Krom or export to Krom
3.Play sound
4.Crash

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender: 2.8 (2019-07-14)
Operating system: Linux 64-bit
Graphics card & driver: Intel Integrated

**Comment by luboslenco** [comment]
Should be resolved now in ArmorySDK1909. Please download & setup the sdk from scratch from itch.io.
