### ISSUE TITLE
Splitscreen example doesn't work

### ISSUE THREAD

**Issue by ArmoryBlender** [armory3d/armory#1320]
Hey there!! I want the splitscreen example in my game but unfortunately it doesn't work. If I try to play the splitscreen example it only gives me a black screen. I don't know what I can do.

**Comment by luboslenco** [comment]
Hi @ArmoryBlender! Any luck using the latest armory and armory_examples versions? Pushed some fixes at https://github.com/armory3d/armory/commit/f5f7926d1f2019eb5ecd580eb22c4db233b91e15 and https://github.com/armory3d/armory_examples/commit/bff90ee6f9cdca95b876f5161f85507f9354cc32.

**Comment by ArmoryBlender** [comment]
Hey @luboslenco !! Unfortunately I can‘t try this out because I‘m on vacation but soon as I get home I will try this out. Thanks for you respond!! Have a nice day!

**Comment by luboslenco** [comment]
No prob at all, should work fine now - thanks for report. 🙂 Enjoy your vacation!

**Comment by ArmoryBlender** [comment]
Thank you so much man!!
