### ISSUE TITLE
Unexpected mesh deformation animation

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armory#1321]
### Version:
Armory v2019.7 ($Id: 817bd37d712a58bf387b7808cccc5ae19cf6f534 $)
Blender: 2.80 RC1
### Issue:
I was trying to figure out a workflow to get animations in custom characters in Mixamo working, and got jarring results:
![giphy](https://user-images.githubusercontent.com/42382648/61499394-64589f80-a99d-11e9-9a94-a7c71399e6c8.gif)
As you can see for a second, the animation plays fine in Blender but in Krom the mesh deformation is all distorted.

### Steps:
1) Export character to FBX with default settings.
2) Load character to Mixamo, setup the autorig, etc.
3) Pick a random animation
4) Download animated char as .FBX
5) Import in Blender in a new file, default setings or also default armature with in Armature: Ignore Leaf Bones + Automatic Bone Orientation.
6) Run

### Test file to reproduce:
[test5.zip](https://github.com/armory3d/armory/files/3408823/test5.zip)

**Comment by N8n5h** [comment]
@luboslenco I noticed the animations in some of the templates are from Mixamo, how did you get those working?

**Comment by greyheron** [comment]
I had similar issues in the past with armatures and meshes. What I did was remove the armature as parent of the mesh. Put them both at location 0, 0, 0 and then parent the mesh with the armature again. That worked for me. As soon as I move the armature from 0, 0, 0 weird things happened. So my work around is that I am putting all my animated characters at that location and then I have a Trait attached to the scene that will put them in their places.

**Comment by N8n5h** [comment]
I tried that and a combination of different things including: removing materials, removing "mixamo:" from bones/vertex groups, unparenting and trying different scales for the mesh, different scales for the rig (when importing), but unluckily none of them worked for me. 

I noticed that characters that you can pick from mixamo directly work straight away, so I was trying to find what is the difference that produces that problem.
![giphy](https://media.giphy.com/media/L4ULK5210GUy3LbBFJ/giphy.gif)

**Comment by N8n5h** [comment]
Ok, I found a solution: when exporting the character to mixamo I used .FBX and `Apply scaling` -> `FBX Units Scale`, last time I checked that did the trick.
