### ISSUE TITLE
No realtime Global Illumination currently working.

### ISSUE THREAD

**Issue by VicentGJ** [armory3d/armory#1325]
### SHORT DESCRIPTION:
There is no any algorithm for realtime GI currently in place. The only option for now is Lightmapping but that only provide static lighting. Is very important to get this kind of feature up and running before next stable release. Raytracing is not a good option in short term because is restricted to high range Nvidia GPU. Merging to code base something like this add-on http://forums.armory3d.org/t/hdr-lightmaps-addon or maybe a rework on Voxel GI using a mixed CPU and GPU approach like Godot engine does?

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armory/issues/649 and https://github.com/armory3d/armory/issues/1268, Voxel AO also stays alive.
