### ISSUE TITLE
Archive older versions

### ISSUE THREAD

**Issue by larbacsilva** [armory3d/armory#1328]
Hi,

Actually, I won't report any kind bug, just request something. I've started a [thread ](http://forums.armory3d.org/t/can-i-use-latest-version-with-blender-2-79/3393) on the forum asking about old version (compiled) from the Armory 3D and I would like to ask (if possible) to archive older versions of the engine. Also, I would love to download the version with support to Blender 2.79. 

Thank you.

**Comment by luboslenco** [comment]
Hi,

0.5 (last b2.79 compatible release) is now available again on itch.io, will also make sure to keep 0.6 there. To re-clone older version manually, releases are tagged at [armsdk](https://github.com/armory3d/armsdk/releases) repo.
