### ISSUE TITLE
Build 7: bundled scripts not always visible

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#133]
Bundled scripts classes are not visible in Armory Traits until you build the project. 
System : OS X® 10.11.6

How to reproduce:
Open new project, save it and go in Armory Traits, when you select Bundled Script the list is empty.
Only after you build the project the Bundled script list is visible.

PS: It would be useful to edit Bundled scripts from Armory Traits panel or  add an option to  "load scripts". Simple workaround for now is just create new Haxe script, edit it and load scripts in Kode Studio.

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/armory/commit/09183e345928c0e0c3882b609dcab4591efcb02c - thanks!

Keeping open till "load script" functionality is added.

**Comment by luboslenco** [comment]
Editing bundled scripts is now also possible (https://github.com/armory3d/armory/commit/39da6198ecba1f34bf8072ded509c1eef6cfc9cc) - with bundled script selected, the usual 'Edit Script' button will show up - this will copy source to project and open local copy in Kode Studio.

<img width="318" alt="edit_bundled" src="https://cloud.githubusercontent.com/assets/3685704/23319922/df54449e-fad8-11e6-88b5-d6a8d111845f.png">

**Comment by AndreaMonzini** [comment]
Great! thank you!
