### ISSUE TITLE
Armory3d 0.6 version on itch.io doesn't work

### ISSUE THREAD

**Issue by ArmoryBlender** [armory3d/armory#1330]
Hey! I recently set my pc back and I had to download armory3d from the official website again. Unfortunately there is something wrong with the blender version. I can't click anything. I hope @luboslenco you can fix this soon, not because of me rather for the new ones who joined the armory3d community.

**Comment by VicentGJ** [comment]
I also​ have this issue in Linux which is really annoying, but I think if @luboslenco update the blender version to a stable one should be enough to fix it.

**Comment by arigbs** [comment]
I experienced the same thing.

**Comment by ArmoryBlender** [comment]
Hey Guys!! I found out to use the broken version!!! You have to load the factory settings! 

![InkedBlender Screenshot 2019 08 03 - 20 17 10 97_LI](https://user-images.githubusercontent.com/48133099/62415558-06c68300-b62c-11e9-8c7e-bc93b01e97c8.jpg)

**Comment by VicentGJ** [comment]
Sweet but I still think @luboslenco should fix this or will be annoying for newcomers

**Comment by arigbs** [comment]
> Hey Guys!! I found out to use the broken version!!! You have to load the factory settings!
> 
> ![InkedBlender Screenshot 2019 08 03 - 20 17 10 97_LI](https://user-images.githubusercontent.com/48133099/62415558-06c68300-b62c-11e9-8c7e-bc93b01e97c8.jpg)

Good to know. Tried it and it works. Thanks.

**Comment by luboslenco** [comment]
Updated itch.io with the new `ArmorySDK-2019-08` build, it is now preferred to setup Armory in your existing Blender copy to prevent issue like this. (I guess running newer Blender version did something to preferences which older Blender build included in Armory could not handle?)

Also updated setup guide:
https://github.com/armory3d/armory/wiki/setup

Thanks for report!
