### ISSUE TITLE
Build fails with Render Path related errors.

### ISSUE THREAD

**Issue by arigbs** [armory3d/armory#1331]
![arm2](https://user-images.githubusercontent.com/13068652/62418653-748fa080-b666-11e9-962e-9deff30a812f.JPG)

Using Blender 2.8 with Armory version 2019.07
This error referring to render target persists no matter whether I update from preferences, or I clone from the repo. The build just fails. I  do not know what to make of it and searching online has failed to yield any leads.

**Comment by luboslenco** [comment]
Hi,

Any luck if you try with the latest 2019.08 release?

**Comment by arigbs** [comment]
> Hi,
> 
> Any luck if you try with the latest 2019.08 release?

Hi, I've tried it, the errors still persist...

**Comment by luboslenco** [comment]
Can you share .blend file to reproduce the errors? I am assuming default cube works?

**Comment by arigbs** [comment]
> Can you share .blend file to reproduce the errors? I am assuming default cube works?

Yes other scenes work. I followed a suggestion from [this forum thread](http://forums.armory3d.org/t/build-errors-first-shader-related-then-render-path-related/3370/2), that the issue might be with Armory not supporting Light Probes and to try appending the project bit by bit to a new scene. I tried this and left out the irradiance maps and light probes I had used to set up the scene in blender. So far so good, it seems to have resolved that issue as the scene now builds, though it's all dark, I now have to figure out how to handle lighting in Armory, I thought the lighting set up in Blender would translate directly, but it seems this is not the case. 

P.s. I think I can confirm that the lightprobes are the issue. The file attached has a sample scene with just the default cube and to which I appended the irradiance volumes and reflection cube maps from the offending project. This file throws the error, thus suggesting that the light probes are indeed the problem.
[lightProbeError.zip](https://github.com/armory3d/armory/files/3483170/lightProbeError.zip)

**Comment by luboslenco** [comment]
Build errors should be gone now using [git version](https://github.com/armory3d/armory/wiki/gitversion) (patched at https://github.com/armory3d/iron/commit/cb180146a229a1b3151acc2f73ccd9a5af8530fa). Irradiance volumes are not yet implemented though, hopefully soon at https://github.com/armory3d/armory/issues/649.
