### ISSUE TITLE
Create Repos for builds of kode for every OS

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armory#1332]
I'm playing with the possibility of making armory sdk installable directly from the addon page inside Blender Preferences, and AFAIK there is no repos that hosts the builds of kode for each OS: "linux64","win32" and "KodeStudio.app" so maybe repos for those could be created to facilitate the process. 

Also, there is another thing I'm missing that is platform specific or it's just those folders?

Update: I didn't notice that those folders are for kode for each OS.

**Comment by zicklag** [comment]
The [Armory SDK][sdk] contains all of the binaries needed by Armory for Windows, Mac, and Linux. If you just bundled the Armory SDK with the plugin and hardcoded the SDK path so that you don't have to set it as an addon preference, you should be able to install the plugin just like any other Blender plugin. Granted, if you did it like that, the plugin download would be larger than necessary for any one platform, because it includes the binaries for all of them.

[sdk]: https://github.com/armory3d/armsdk

**Comment by N8n5h** [comment]
@zicklag Oh, what I meant by "installable with the addon" was to expand the functionality of the "update" button to allow "installing" (cloning) the sdk rather than just "updating". 
The only thing missing is the builds for kode studio I think and nodejs

**Comment by zicklag** [comment]
Ah, that makes sense. That is a good idea. In that case, maybe it could just download it from here: https://github.com/Kode/KodeStudio/releases.

**Comment by N8n5h** [comment]
Yeah, it would be cool if the builds were ready to clone from repos to make the process easier

**Comment by N8n5h** [comment]
[my progress so far](https://github.com/N8n5h/armsdk/blob/patch2/armory.py) is an updated version of [this initial version](https://github.com/N8n5h/armsdk/blob/patch-1/armory.py) that didn't require the extra repos for Kode builds and is working fine in win 7/win 10 and linux, so the only thing missing are the repos to make the newest work and test in macOS if possible. 

I also added some error catching to catch common issues when updating the sdk (missing folder(s), git not installed, not enough space, ...)

I'm still learning python and blender API, so if you see any ugly code please point it out.

**Comment by luboslenco** [comment]
@N8n5h I am trying to simplify Armory setup, so it gets installed into existing Blender copy as a regular add-on. The [setup guide](https://github.com/armory3d/armory/wiki/setup) now lists code editor as a separate download. I think your initial version should be good to go this way?

**Comment by N8n5h** [comment]
Yes, should be.

I changed a few bits in the second version that might be confusing in the first one, like the label of the button "Install SDK" to "Download and Set up SDK" and when a folder doesn't exist a label appears instead of always saying "the folder will be created if doesn't exist".

**Comment by N8n5h** [comment]
> @N8n5h I am trying to simplify Armory setup, so it gets installed into existing Blender copy as a regular add-on. The [setup guide](https://github.com/armory3d/armory/wiki/setup) now lists code editor as a separate download. I think your initial version should be good to go this way?

The changes I made allow "installing" the sdk to an empty folder, so I guess the setup guide could be updated to mention the 2 possibilities of manually downloading and downloading in the addon page.

**Comment by luboslenco** [comment]
It's in https://github.com/armory3d/armsdk/pull/3, thanks! Perhaps best to mention it at https://github.com/armory3d/armory/wiki/gitversion since this will fetch the latest git version?
