### ISSUE TITLE
Kha Permission Error Report on Linux

### ISSUE THREAD

**Issue by rogper** [armory3d/armory#1333]
### SHORT DESCRIPTION:
I'm getting a permission error report when pressing play.

### EXPECTED RESULT:
I would expect it to play.

### ACTUAL RESULT:
It returns this error message:
Armory v2019.8 ($Id: 63553e8d8723f625a57df134fdb8b9db6cd861aa $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.80 (sub 75)
Exporting Scene
Scene exported in 0.004796028137207031
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Traceback (most recent call last):
  File "/home/rogper/ArmorySDK//armory/blender/arm/props_ui.py", line 523, in execute
    make.play()
  File "/home/rogper/ArmorySDK//armory/blender/arm/make.py", line 493, in play
    compile(assets_only=(not wrd.arm_recompile))
  File "/home/rogper/ArmorySDK//armory/blender/arm/make.py", line 274, in compile
    arm.lib.server.run_haxe(arm.utils.get_haxe_path())
  File "/home/rogper/ArmorySDK//armory/blender/arm/lib/server.py", line 19, in run_haxe
    haxe_server = subprocess.Popen([haxe_path, '--wait', str(port)])
  File "/home/rogper/blender-2.80/2.80/python/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/rogper/blender-2.80/2.80/python/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/rogper/ArmorySDK//Kha/Tools/haxe/haxe-linux64'

### STEPS TO REPRODUCE:
Steps:
1. On the default blender start up scene (cube, lamp and camera) set up Armory Player, Armory Exporter and Armory Render Path;
2. Save file
3. Press Play

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender: 2.8 official
Armory: v2018.8
Operating system: Linux Mint 19.1
Graphics card & driver: Nvidia 390.116

### TEST FILE TO REPRODUCE:
_Please create the simplest file possible that demonstrates the issue:_
*(drag & drop the zipped .blend file here)*

**Comment by zicklag** [comment]
I think you should be able to run `chmod +x /home/rogper/ArmorySDK//Kha/Tools/haxe/haxe-linux64` to fix that. If Armory comes with that file with it non-executable, then that would be a bug.

**Comment by rogper** [comment]
Hey zicklag, thanks for the help! :)
I did as you mentioned, but then I got a brand new permission error:

Armory v2019.8 ($Id: 63553e8d8723f625a57df134fdb8b9db6cd861aa $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.80 (sub 75)
Exporting Scene
Scene exported in 0.004872322082519531
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/rogper/ArmorySDK//nodejs/node-linux64', '/home/rogper/ArmorySDK//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_Test/debug', '--nohaxe', '--noproject']
Using project from /home/rogper/Desktop
Traceback (most recent call last):
  File "/home/rogper/ArmorySDK//armory/blender/arm/props_ui.py", line 523, in execute
    make.play()
  File "/home/rogper/ArmorySDK//armory/blender/arm/make.py", line 493, in play
    compile(assets_only=(not wrd.arm_recompile))
  File "/home/rogper/ArmorySDK//armory/blender/arm/make.py", line 284, in compile
    state.proc_build = run_proc(cmd, assets_done if compilation_server else build_done)
  File "/home/rogper/ArmorySDK//armory/blender/arm/make.py", line 33, in run_proc
    p = subprocess.Popen(cmd)
  File "/home/rogper/blender-2.80/2.80/python/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/rogper/blender-2.80/2.80/python/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/rogper/ArmorySDK//nodejs/node-linux64'

I guess I can do the same thing for the nodejs folder and all the others that may show up next, but I don't think I have any kind of strange permissions on my system....

**Comment by rogper** [comment]
I made the same as before and then I've got this error:

Armory v2019.8 ($Id: 63553e8d8723f625a57df134fdb8b9db6cd861aa $)
OS: linux, Target: krom, GAPI: opengl, Blender: 2.80 (sub 75)
Exporting Scene
Scene exported in 0.0035212039947509766
Exported modules: ['audio']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_ShadowMap', '_CSM', '_SinglePoint', '_SMAA', '_SSAO']
Running:  ['/home/rogper/ArmorySDK//nodejs/node-linux64', '/home/rogper/ArmorySDK//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--parallelAssetConversion', '4', '--to', 'build_Test/debug', '--nohaxe', '--noproject']
Using project from /home/rogper/Desktop
Using Kha from /home/rogper/ArmorySDK/Kha
Creating Kha project.
Exporting asset 1 of 3 (Scene.arm).
Exporting asset 2 of 3 (mesh_Cube.arm).
Exporting asset 3 of 3 (World_irradiance.arm).
Exporting asset 1 of 2 (Material_data.arm).
Exporting asset 2 of 2 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
(node:29405) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: spawn EACCES
(node:29405) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Error: Could not process argument project-krom.hxml (file not found)
invalid character: -
Build failed, check console

**Comment by zicklag** [comment]
That would be yet another executable permission error ( the `EACCESS` ), but it doesn't say which file it is failing to execute in the Error message.

Hmm :confused:. I once ran into this "all executables lose the executable permission" problem when I tried to rsync the Armory SDK and forgot the flag that tells it to preserve executability. I guess you could do a recursive `chmod` that marks *all* of the files in the SDK as executable. Generally you don't make files that aren't programs executable, but I don't *think* it would hurt anything.

```
chmod +x -R /path/to/armsdk/
```

Otherwise you could re-download the SDK and everything should work fine. I'm not sure what caused the files to lose their executability, but it should be fine if you re-download them.

**Comment by rogper** [comment]
Ok, that worked :) after marking all files as executable it played. 

I've download the version from itch.io, and I had this issue with 2018.7 and now with 2018.8. I have tried to re-install it many times, I've even cleared all blender configuration files too. I may attempt to clone it from git... I didn't remembered of doing that, thanks for mentioning it! 

Wait! I've unziped the SDK :) Does it install without unzipping? I'll report on this.

**Comment by zicklag** [comment]
Oh, that reminds me, I've had a problem before with Blender when I tried to install a Blender plugin from a Zip that had executables in it and it didn't keep the executability flag when it unziped it.

If the zip was made on a Windows machine or if the unzip program you are using doesn't respect the executable flags that might be the problem.

**Comment by rogper** [comment]
Hello, I confirm that this was an unzipping issue. 
If I unzip the file with the right click and then "unzip to here" it messes up all the permissions, but if I open the actual software and only then save to a specific location everything works great.

I guess that perhaps compressing a Linux version with .tar.gz instead of Zip would solve this forever.
Thanks again for all the help! :)

**Comment by luboslenco** [comment]
@rogper it should unpack properly as usual on Linux now, I have updated the `.zip` on itch.io. Thanks for the heads up!
