### ISSUE TITLE
Is Kravix.exe malware?  

### ISSUE THREAD

**Issue by JamesXyXz** [armory3d/armory#1335]
Thanks for helping to contribute to Armory3D!
To help us fix your issue or implement your feature as quickly as possible, please fill out the following information as best you can:

### SHORT DESCRIPTION:
_Keep it 1-3 sentences and to the point._

### EXPECTED RESULT:
_What did you expect to happen? For a feature request, what would you like to happen?_

### ACTUAL RESULT:
_What happens right now that's different from how you expect or want it to work?_

### STEPS TO REPRODUCE:
_Please list clear, step by step instructions to replicate the result you got. For a feature request list the steps to use the feature._
Steps:
1.
2.
3.
etc.

### TECHNICAL SPECIFICATIONS:
_What version(s) of the following did you try:_
Blender:
Armory:
Operating system:
Graphics card & driver:

### TEST FILE TO REPRODUCE:
_Please create the simplest file possible that demonstrates the issue:_
*(drag & drop the zipped .blend file here)*

**Comment by sh-dave** [comment]
There is no such thing. If you mean `krafix.exe` it's a binary of the shader-cross compiler of [this](https://github.com/kode/krafix) repository. If you mean `kravur.exe` that's also not malware, it's a build of [this one](https://github.com/kode/kravur)

**Comment by luboslenco** [comment]
Hope that helped! It's also possible to compile those [by hand](https://github.com/Kode/Kinc/wiki/Getting-Started).
