### ISSUE TITLE
Armory and emacs battle-haxe

### ISSUE THREAD

**Issue by mbmattos1113** [armory3d/armory#1339]
I was trying to use armory autocompletion on emacs using the battle-haxe package.
I was told that i'd need a .hxml file to give instructions to haxe in order to have the autocompletion. Where can i get the .hxml on armory?
https://github.com/AlonTzarafi/battle-haxe/issues/1

**Comment by zicklag** [comment]
Its in `build_blendname/debug/project-krom.hxml` for Krom projects.

**Comment by mbmattos1113** [comment]
Many thanks for the quick response :)
