### ISSUE TITLE
Offscreen For WebGL error

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#134]
This error occurs when you take a scene that renders and run it in Armory Player (don't build just quick run). Have the runtime set to Electron. Navigation is set to none and the POV is the viewport camera. Debug Console, Live Patching are both on (live patching not used). Click the run button. After the scene is loaded and runs, click on the close icon to close the window. This shows up: [.Offscreen-For-WebGL-092E7FF8 ]RENDER WARNING: there is no texture bound to the unit 3. Console error screen captured: 
![capture](https://cloud.githubusercontent.com/assets/15915424/22958286/6163b1b6-f2fc-11e6-8afd-44724e11cd29.JPG) . Enjoy.

---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Thanks for report - added check in https://github.com/armory3d/armory/commit/e88322715521e714a2e71c86a6c3ecdc74f4375b.
