### ISSUE TITLE
Sound Broken on Krom Windows 10 when updating the SDK ArmorySDK1908 to the latest SDK in Blender

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1340]
**SHORT DESCRIPTION:**
sound stop working when using Krom in Blender2.8
after updating the SDK ArmorySDK1908 in Blender.

**FULL DESCRIPTION**
a project with a sound (Audio.play(); ) will not emit any sound in Blender 2.80 when using the Krom renderer (using F5).
Please note the sound works fine when exporting in Html5 instead of using Krom.

It worked fine before with only the SDK1908 : ArmorySDK1908.zip.
it seems like it is when updating to the latest/lastest SDK that Krom is loosing its sound features.

**EXPECTED RESULT:**
Play a sound.

**ACTUAL RESULT:**
No sound at all

**STEPS TO REPRODUCE:**
Steps:
    Install official Blender 2.80 for windows64 bits
    Install Armory as a plugin for Blender using ArmorySDK1908.zip
    Update Armory SDK in Blender
    Test in Krom or export to Krom
    3.Play sound
    4.No sound

**TECHNICAL SPECIFICATIONS:**
Blender 2.80 (sub 75), branch: official master, commit date: 2019-07-29 14:47
renderer:	'Intel(R) HD Graphics 620'
windows 10 pro version 1903

**Comment by VicentGJ** [comment]
I got the same issue in Manjaro Linux. It needs an urgent fix.

**Comment by luboslenco** [comment]
Should be resolved now in ArmorySDK1909. Please download & setup the sdk from scratch from itch.io.
