### ISSUE TITLE
in firefox , mouse wheel fails after random interval

### ISSUE THREAD

**Issue by plankatron** [armory3d/armory#1341]
### EXPECTED RESULT:
mouse wheel works forever in html

### ACTUAL RESULT:
randomly freezes , cannot figure out what the exact cause is 

### STEPS TO REPRODUCE:
Open up blend file, export to html 5 , use mouse wheel for a bit, should hang in under a minute

### TECHNICAL SPECIFICATIONS:
Blender: Blender 2.8 rc1
Armory: Latest Update
Operating system: Linux Mint 19.2
Graphics card & driver: Nvidia RTX 2070 , 430 driver

### TEST FILE
so blend files are not supported at github .. 

[test blend](http://7rnx.net/tmp-sync/eyeboot-armory.blend)

**Comment by MoritzBrueckner** [comment]
Hi, unfortunately the example file no longer exists, and because Kha was updated a lot since the issue was opened and there doesn't seem to be similar reports I will close this issue now. If the issue should come up again we can reopen it.
