### ISSUE TITLE
Armory Canvas Button cant change Alpha or color

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armory#1344]
Changing the alpha or color of a Canvas button in the editor does not have any effect. I would like to be able to have invisible buttons that can still be clicked. Using Visible property disables the functionality. 

Maybe visible should be renamed to deactivated? and alpha should be implemented. Thanks!

**Comment by BlackGoku36** [comment]
@kenthinson  Setting alpha and and fancy color for all elements should work now.
