### ISSUE TITLE
Issues with viewport camera on Krom

### ISSUE THREAD

**Issue by VicentGJ** [armory3d/armory#1346]
Pressing "Q" key while using viewport camera on Krom player causes the camera to fall down even after releasing the key.
**System**
Blender: 2.8 rc2
Armory: 2019.8
OS: Linux
Graphics card: Nvidia MX 150

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by luboslenco** [comment]
Same in ArmorySDK1909? Basically "Q" key gets stuck? Does the same happen with "E" key?

**Comment by VicentGJ** [comment]
I have not try with  Armory 19.09, I will try soon, "E" key does not do the same.

**Comment by Sandy10000** [comment]
There is a problem that Krom (Linux) cannot detect the release of the "q" key. (https://github.com/armory3d/armory/issues/1387)
If #1387 is solved, #1346 will be solved.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/1387.
