### ISSUE TITLE
Clouds not working

### ISSUE THREAD

**Issue by VicentGJ** [armory3d/armory#1347]
**Description**
The clouds settings in the world tab are being completely ignores and cloud do not render. Tested in Third_Person_Terrain template.

**System**
Blender: 2.8 rc2
Armory: 2019.8
OS: Manjaro Linux
Graphics card: Nvidia MX 150

**Comment by VicentGJ** [comment]
Okay so this was a real mistake on my side. After more testing I realized it was a problem of my setup.

**Comment by AFWSI** [comment]
> Okay so this was a real mistake on my side. After more testing I realized it was a problem of my setup.

What did you do to get it to work? I can’t get it working in the example or my projects. It worked in the past.
