### ISSUE TITLE
Ocean not working in Forward render

### ISSUE THREAD

**Issue by VicentGJ** [armory3d/armory#1348]
**Description**
Ocean works correctly in Deferred but is not rendered at all when using Forward. Tested in ThirdPerson_Terrain template.

**System**
Blender: 2.8 rc2
Armory: 2019.8
OS: Manjaro Linux
Graphics card: Nvidia MX 150

**Comment by luboslenco** [comment]
Fixed at https://github.com/armory3d/armory/commit/be4853cb6a7987a5ffce2827c55f9aa225018a6d, thanks for report!
