### ISSUE TITLE
Unable to play/build project under Linux

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#135]
Finally had the time to test armory under Linux also.

I'm not able to run a simple scene. It's seems something related with Kha instead of directly related with armory.

Find the log here:
<pre>
Armory v17.01
Scene built in 0.006128072738647461
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CompoTonemap.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (mesh_Suzanne.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CompoTonemap.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CompoTonemap.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:87: characters 34-60 : Class<kha.Shaders> has no field painter_image_frag
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:88: characters 32-58 : Class<kha.Shaders> has no field painter_image_vert
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:322: characters 34-62 : Class<kha.Shaders> has no field painter_colored_frag
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:323: characters 32-60 : Class<kha.Shaders> has no field painter_colored_vert
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:586: characters 34-59 : Class<kha.Shaders> has no field painter_text_frag
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:587: characters 32-57 : Class<kha.Shaders> has no field painter_text_vert
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:816: characters 34-60 : Class<kha.Shaders> has no field painter_video_frag
/home/artur/.config/itch/apps/Armory3D/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:817: characters 32-58 : Class<kha.Shaders> has no field painter_video_vert

Haxe compiler error.
Build failed, check console
</pre>

Linux System: Solus 2017.01.01.0 64-bit
Linux Kernel: 4.9.7
Graphic Card: GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by arturjpv** [comment]
Ok, found the relation with issue #96 

It seems the dot charater in ".config" is breaking the path. Moving Armory out of that dir works. The weird thing is that this is Itch.io default path for downloaded content. :-(

**Comment by luboslenco** [comment]
Should work now - any luck?

**Comment by arturjpv** [comment]
Hi @luboslenco,

I still need to move Armory outside Itch directory in order to make it work. However, the problem has changed. Shaders finish compiling, so the Kha issue seems solved.

Log for scene1:
<pre>
Color management: using fallback mode for management
Read new prefs: /home/artur/.config/blender/2.78/config/userpref.blend
found bundled python: /home/artur/.config/itch/apps/Armory3D/Armory/2.78/python
which: no nvcc in (/home/artur/.sdkman/candidates/gradle/current/bin:/usr/local/bin:/usr/bin:/bin)
read blend: /home/artur/Documents/Armory Projects/Armory Examples/scene1/scene1.blend
Project updated to sdk v17.03.1
Project cleaned

Armory v17.03.1
OS: linux, Target: krom
[bpy.data...nodes["Set Transform"]]
Exporting mesh Plane
Exporting mesh Suzanne
Scene built in 0.2395477294921875
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CToneFilmic.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (mesh_Suzanne.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CToneFilmic.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CToneFilmic.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
hosek_radiance.hdr
Could not open file /home/artur/Documents/Armory Projects/Armory Examples/scene1/build/krom/hosek_radiance.hdr.
Writing: /tmp/scene1.crash.txt
Segmentation fault (core dumped)
</pre>

At first I though this was the "spaces" problem again ("Armory Projects" and "Armory Examples"), but moving armory outside Itch directory makes this work. So it seems there is no problem with spaces in the project path.

/home/artur/Documents/Armory Projects/Armory Examples/scene1/build/krom/ is full of content and a lot of files are generated. However, hosek_radiance.hdr is not there.

If I try to play physics_softbody, which has no radiance file, the same problem appears with "ammo.js":
Could not open file /home/artur/Documents/Armory Projects/Armory Examples/physics_softbody/build/krom/ammo.js.

I see both files are provided inside armsdk, so maybe the "." in ".config" is now disturbing finding resources in the "armsdk" path.

**Comment by razvanc-r** [comment]
For me works under `.config` for some reason. Maybe it's the combination of `.` and `space` in your case... Don't know

**Comment by arturjpv** [comment]
Hi @razvanc-r,

I removed the spaces in the project path before moving armory outside the Itch directory. As it also failed, I decided to move armory again.

I will try to test this again repeating all the steps just to avoid mixing things now just remembering.

Are you using the provided bundled blender in armory? Or are you using another blender version installing the add-on?

**Comment by razvanc-r** [comment]
I'm using Itch version, so bundled blender

**Comment by arturjpv** [comment]
ok, same here... I will test it again to see If I can find the reason of why it's working for you.

**Comment by luboslenco** [comment]
@arturjpv I think there still could be some wrong path mangling, will try to investigate tomorrow and post a patch. This is only a quick temporary fix which actually copies some assets to local project folder, to prevent that '.config' in path..

**Comment by arturjpv** [comment]
This seems fixed in Build 10.

I'm not experimenting any problems related with paths in builds. I will wait until more examples are adapted for Build 10 features to better test the issue. If you want, we can close it for now. We will open a new issue if other path problems appear on other parts.

**Comment by luboslenco** [comment]
Hooray! Feel free to keep it open.

**Comment by arturjpv** [comment]
Closing Issue!
