### ISSUE TITLE
Cannot use CJK characters in the UI editor

### ISSUE THREAD

**Issue by HenryAWE** [armory3d/armory#1350]
**Description**
The UI editor cannot accept the input from the IME.   

![input](https://user-images.githubusercontent.com/25245891/63223095-183e8c00-c1e3-11e9-96b3-79bc41d8de98.png)
Even copy-paste the text from the other application does't work.  

**Expected behavior**
UI Editor can accept the non-English input.

**Comment by jhch3** [comment]
that's kha. defining Graphics.fontGlyphs fist. and setting font with CJK  fonts(eg. ttf-wqy).
