### ISSUE TITLE
Transparency problem

### ISSUE THREAD

**Issue by RomStef** [armory3d/armory#1351]
Hi guys , i'm new here.
I'm trying to convert a shader of mine from upBGE to Armory3D but the transparency doesn't work as expected. the shader must be applied on a skydome and emulate dynamic clouds

this is the nodes setup in armory

![node](https://user-images.githubusercontent.com/20901566/63363723-6931ba00-c374-11e9-8935-4796697b0c50.png)

and this is the result

![test](https://user-images.githubusercontent.com/20901566/63363782-85355b80-c374-11e9-8cad-3aac1d62b656.png)

this is the result on upbge

![test_2](https://user-images.githubusercontent.com/20901566/63363765-7f3f7a80-c374-11e9-9bae-74ad9f3b24c4.png)

and this is a demo in upbge

https://www.youtube.com/watch?v=Q37I0zyH624&t=6s

**System**
Blender: 2.8
Armory: SDK 2019 08
OS: Windows 10
Graphics card: nVidia GTX 1050TI

this is the file i'm workin on
[armory_dynamic_sky.zip](https://github.com/armory3d/armory/files/3521531/armory_dynamic_sky.zip)

Thanks in advance

**Comment by onelsonic** [comment]
I have the same behavior the transparency is not working properly.
it seems that it needs more levels of grey alpha transparency than how it is handled now.
This is really problematic.

Should this be flagged as a bug?

**Comment by Sandy10000** [comment]
The issue was resolved by unchecking Armory Props-Alpha Test in the Materials tab.
![1](https://user-images.githubusercontent.com/48373918/66750270-03226880-eec7-11e9-9b82-5697c6d670c7.jpg)
![2](https://user-images.githubusercontent.com/48373918/66750289-0fa6c100-eec7-11e9-8bdf-7eb312639102.jpg)
