### ISSUE TITLE
'emission' : undeclared identifier with Armory PBR materials if emission is set to a value higher than 0

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1352]
**Description**
compilation of project return the following : 
'emission' : undeclared identifier 

**To Reproduce**
when using a Armory PBR material and setting the emission to a value higher than 0.
I am using the current stable build : ArmorySDK1908

**Comment by luboslenco** [comment]
Appears to be ok in ArmorySDK1909. If issue still persists please reopen with .blend file.
