### ISSUE TITLE
Set Scene not working with Krom.

### ISSUE THREAD

**Issue by Iamawesome12345** [armory3d/armory#1353]
Hello, I've encountered some issues when using the "Set Scene" node.

![Set Scene](https://user-images.githubusercontent.com/54377522/63467780-3222dd80-c434-11e9-89f9-07e1bb7c2136.JPG)
First off when I use the "Virtual Button" node (I'm new to armory) its the only thing I could find that would at all possibly relate to a button on my Canvas UI, so I used that to try to make the function for my button on my UI. The way I have it setup currently (as above) it does not work, when i click the button when running the game, nothing happens. I have this node tree set as a trait of the scene and not one of the objects. So then I tried removing the "Virtual Button" node, and replacing it with a "Keyboard" node assigning the key as "R". That instead of doing nothing, froze the Krom player. But it works in browser mode (the scene loads), with the exception of the HDR that I have set (which doesn't load I'm pretty sure unless it was very dark) for my scene that I wanted to load, I can't tell if that's an issue with the loading of the scene or an issue with browser mode. I've also seen a post on the Set Scene not working before and tried the supposed solution to that and it didn't work.

Thanks in advance!

**Comment by luboslenco** [comment]
Hi, do you still have a .blend file handy? There is a simple example using `Set Scene` node [here](https://github.com/armory3d/armory_examples/blob/master/logic_examples/scenes.blend) but that one appears to be ok.
