### ISSUE TITLE
terrain example not working under blender 2.80 with current SDK 

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1354]
I've been playing with the Armory terrain module.
It is not behaving correctly under blender 2.80
When trying to generate a terrain I have the following error :
Am I doing something wrong??
Same issue with the terrain example (https://github.com/armory3d/armory_examples/blob/master/terrain/terrain.blend)
---------------

Traceback (most recent call last):
  File "C:\armory//armory/blender\arm\props_ui.py", line 1207, in execute
    node.color_space = 'NONE'
AttributeError: 'ShaderNodeTexImage' object has no attribute 'color_space'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armory/commit/4d5309a07a38770fb833d05d509ca0c4149e3ad9, blender python api changed slightly which resulted in the `AttributeError: 'ShaderNodeTexImage' object has no attribute 'color_space'` error. Thanks for report!

**Comment by onelsonic** [comment]
great thank you for the fix
