### ISSUE TITLE
Armory Bake - Apply broken

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#1358]
**Description**
Pressing `Properties - Render - Armory Bake - Apply` throws:

```
File "/armory/blender/arm/props_bake.py", line 253, in execute
    bpy.data.images[img_name].pack(as_png=True)
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)
```

**To Reproduce**
Example at https://github.com/armory3d/armory_examples/blob/master/material_examples/baked.blend

**System**
Blender: 2.8
Armory: 2019.8
OS: Windows 10

**Comment by arigbs** [comment]
Experienced this too. Good to see its been picked up as a bug.

**Comment by VicentGJ** [comment]
Okay, funny thing. I make my first try to fixing this issue, and what I found it is not extremely necessary to save the image as png (although the Blender API is very lacking in the bpy.data module) so I just leave the parenthesis empty like this:
`bpy.data.images[img_name].pack()`
It not longer complain about the typing instead it gives the following error:


> Traceback (most recent call last):
  File "C:\Users\Vicente\Documents\Armory\ArmorySDK//armory/blender\arm\props_bake.py", line 253, in execute
    bpy.data.images[img_name].pack()
RuntimeError: Error: Unable to pack file, source path C:\Users\lubos\Documents\Armory\armory_examples\material_baked\build_baked\compiled\Assets\unpacked\Cube_baked.jpg' not found`> 

I'm very confused right now becouse my user name is not "lubos" :)
@luboslenco any idea of what can be causing this???

**Comment by luboslenco** [comment]
Did you hit `Bake` before clicking `Apply`? Looks like the baking was not done and it's pointing to the old path.

**Comment by VicentGJ** [comment]
Thanks @luboslenco it was a dumb mistake, it works now with the simple fix I mention before, here is the result:
![Bake_Result](https://user-images.githubusercontent.com/52976500/64456397-64992f80-d0f0-11e9-94c3-5ec57c40f0e6.jpg)

**Comment by VicentGJ** [comment]
Oh man, that really needs a denoiser!!! Now I just have to find out how to implement one 🤔

**Comment by VicentGJ** [comment]
Sometimes when I hit play immediately after applying a new baked lightmap, Blender crashes and close leaving this output:

> Armory v2019.9 ($Id: 2c6dcd0b50371c010c1287c332b6c1b791aeb1c1 $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 75)
Exporting Scene
Armory Info: Converting to C:\Users\Vicente\Documents\Armory\Projects\Archviz\Basic/build_untitled/compiled/Assets/unpacked/Cube.001_baked.jpg
Error   : EXCEPTION_ACCESS_VIOLATION
Address : 0x00007FF7D25718EE
Module  : C:\Program Files\Blender Foundation\Blender\blender.exe
>
Any idea @luboslenco???

**Comment by mehr110** [comment]
> **Description**
> Pressing `Properties - Render - Armory Bake - Apply` throws:
> 
> ```
> File "/armory/blender/arm/props_bake.py", line 253, in execute
>     bpy.data.images[img_name].pack(as_png=True)
> TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)
> ```
> 
i have same problrm. how you solved it?

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armory/commit/32da177143b88e7c69a5d7d7d86ae7d75b5d13ee.

Not sure about the Blender crash though, maybe something to do with dependency graph. Python should not crash Blender. Is it the same in b2.81?

**Comment by VicentGJ** [comment]
Okay interesting 🤔. I most check that. It will be good to keep this thread open until we make sure there is no more issues

**Comment by luboslenco** [comment]
Please reopen if issue persists in recent Blender builds.
