### ISSUE TITLE
Type not found : kha.arrays.Int16Array / haxe_bin.git? 

### ISSUE THREAD

**Issue by DinTurbo** [armory3d/armory#1359]
Having problems with Armory3d SDK install / Kode Studio. Have tried multiple days and it always fails. Exact same fatal errors. I think it is something wrong with the haxe_bin.git? Or have I managed to screw something up? twice now? (reinstalled like a good newbie do)

When updating in Armory3d with administration privileges console says:
-Lots of stuff-
Receving objects:100% <794/794>, 4.14MiB : 10.00 KiB/s, done. (Yes my speed is terrible)

Resolving deltas: 100% <362/362>, done.
error: fatal: The remote end hung up unexpectedly
RPC failed: curl 18 transfer closed with outstanding read data remaining
fatal: early EOF
fatal: unpack-objects failed
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: PRC failed; curl 18 transfer closed with outstanding read data remaining
fatal: clone of "https://github.com/armory3d/haxe_bin.git" into submodule path ´C:/Program Files/Armory3d/ArmorySDK1908/Kha/Tools/haxe´ failed
Failed to clone ´Tools/haxe´. Retry scheduled
-Lots of stuff-
Armory SDK updated, please restart Blender

And in Kode studio I do not get the completion help working. (new to programming and like to have it ;c)

Kode Studio, 
Sorce: Haxe (Extension)

Building Cache...
Failed - try fixing the error(s) and restarting the language server:

C:\Program Files\Armory3d\ArmorySDK1908\iron\Sources/iron/data/MeshData.hx:4: characters 8-29 : Type not found : kha.arrays.Int16Array
C:\Program Files\Armory3d\ArmorySDK1908\iron\Sources/iron/data/MeshData.hx:4: characters 8-29 : Type not found : kha.arrays.Int16Array
C:\Program Files\Armory3d\ArmorySDK1908\iron\Sources/iron/data/MeshData.hx:4: characters 8-29 : Type not found : kha.arrays.Int16Array

And when doing anything in Kode Studio it keeps giving me the error
[Error - 7:57:06 PM] Request textDocument/hover failed.
  Message: C:\Program Files\Armory3d\ArmorySDK1908\iron\Sources/iron/data/SceneFormat.hx:6: characters 8-29 : Type not found : kha.arrays.Int16Array
  Code: -32603 

**System**
Blender: 2.8
Armory: ArmorySDK-2019-08
OS: Win7
Graphics card: Nividia 1060 3gb

No ide really what to do but report it?? Looks like I just do not get the files needed right?

**Comment by hanseltime** [comment]
As a potential fix for the Kode Studio problem, did you make sure to explicitly set your Kode Studio kha path to the kha provided with the Armory3d sdk?

https://github.com/Kode/Kha/wiki/Getting-Started

Summarizing from there:  File -> Preferences -> Settings -> Kha Configuration -> <Path to the Kha folder in the armory3d sdk>.  This worked for me.

**Comment by DinTurbo** [comment]
Well ArmorySDK1908 did not provide any Kode Studio in the download itself. So I downloaded it and put it it's own directory and in my preferences in Blender I pointed to that directory. (VS Code Path:) It supports Kode Studio too (it says so hovering over it) so I got it working but with the problem stated above. 

Now when I read you talking about Kode Studio being provided (it's not) I remember a few months back when I had a copy of Armory3D that had no problem with Kode Studio. It was provided with the download and placed inside of Armory3D's directory. So I just tried to move my Kode Studio into "ArmorySDK1908" and ofc I pointed to it in my preference and the error is gone!  "It just works" Now Kode Studio works like I expected it to ;) 

But the error I get when updating the SDK is still there. And have to paste the helpful .backups to make Armory work again. As the update fails the folders are not being put back but instead folders are missing in the install. I think Krom and some other folder is just gone after I run the update? Kha I think? Just playing around with Armory as I'm to new to do anything with it or Unreal 4. 

But why is it happening? Is it just my system and the user's fault. Or is it something wrong with Armory. Meeeh ?

**Comment by DinTurbo** [comment]
Yea that made Kode Studio work! Reinstalled Blend, Armory and Kode for the 4th time now. But hey it at least works now! Have to pray that SDK update now just works. 

In Kode Studio I did like hanseltime said and yea that was just a blank path before I changed it. At first I belied you was saying to change preferences in "Blender". But yea telling Kode Studio where to look makes sense. Just not very well explained in the install of Armory. (if at all)

**Comment by luboslenco** [comment]
From the original post:
```
error: fatal: The remote end hung up unexpectedly
RPC failed: curl 18 transfer closed with outstanding read data remaining
fatal: early EOF
fatal: unpack-objects failed
fatal: early EOF
fatal: The remote end hung up unexpectedly
fatal: index-pack failed
error: PRC failed; curl 18 transfer closed with outstanding read data remaining
fatal: clone of "https://github.com/armory3d/haxe_bin.git" into submodule path ´C:/Program Files/Armory3d/ArmorySDK1908/Kha/Tools/haxe´ failed
```
indicates cloning from github failed for some reason (connectivity issues?). When that happens the sdk will get damaged / missing files and needs to be restored.
