### ISSUE TITLE
make_material - 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#136]
How are we going to fix this?

![image](https://cloud.githubusercontent.com/assets/15915424/23090136/4420bc4c-f564-11e6-9b92-6d7b48e37dc8.png)

---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Please do
`optional - drag & drop .blend file here`

**Comment by George-the-1st** [comment]
Unfortunately, this error happened with a production file. I can't just share it. It sucks but I need to keep those close to heart until I release the game entirely.

**Comment by luboslenco** [comment]
Sorry, will have to get back to this when more data is gathered.

**Comment by George-the-1st** [comment]
That's fine. I'll make sure to give you my affected source files when all is said and done at the end of the day. It'll be a while, though. Don't hold your breath for early release.
