### ISSUE TITLE
complicated node setup causing compile errors in armory

### ISSUE THREAD

**Issue by plankatron** [armory3d/armory#1362]
i am getting compilation errors when using a specific node setup in a specific blend file, the node setup in question was a setup martinsh made for an exponential height fog for eevee, i looked at it and thought it could possibly work in armory, 

**To Reproduce**
run the blend file 

**Expected behavior**
expect armory to compile correctly

**System**
Blender: 280
Armory: 0.6
OS: linux
Graphics card: rtx 2070

**Test File**
[exp_height_fog_eevee_free.blend.tar.gz](https://github.com/armory3d/armory/files/3559701/exp_height_fog_eevee_free.blend.tar.gz)

**Comment by Sandy10000** [comment]
There is a list of available nodes on this page.
https://github.com/armory3d/armory/wiki/supported_nodes

**Comment by MoritzBrueckner** [comment]
Hi, this file no longer causes compile errors so I will close this issue. Be aware though that not all shader nodes nodes are supported (for example the "Shader to RGB" node which is used in the file), like Sandy10000 wrote.
