### ISSUE TITLE
Clouds not working with ArmorySDK1908

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armory#1363]
**Description**
Clouds doesn't work with ArmorySDK1908 and Blender ```commit 82ef1edce4a2152c59a093705be2fcccc3256ab2```. I downloaded and tested Armory_06_win64 and clouds work fine. Guess it's the ArmorySDK1908 or latest Blender.

**System**
Blender: ```commit 82ef1edce4a2152c59a093705be2fcccc3256ab2```.
Armory: ArmorySDK1908
OS: Windows 10 64bit
Graphics card: GTX 950M

**Comment by onelsonic** [comment]
same here. I never succeed to use it on ArmorySDK1908

**Comment by luboslenco** [comment]
Should be resolved now in ArmorySDK1909. Please download & setup the sdk from scratch from itch.io.
