### ISSUE TITLE
Zui not resizing along with window at all

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1366]
Description
I am doing tests with the Zui system, but the UI is not resizing itself along with the window.
Either with Krom or in html5.
You normally expect that the UI will scale up and down along with your application or canvas windows but it is not.

To Reproduce
Create a new UI, then resize your html5 canvas or make your Krom application resizable, 
in either case the UI will keep it initial ratio and size and will not scale up or down according your your window.

Expected behavior
a proper scaling of the UI along with the application window.

System
Blender : 2.80 (sub 75), branch: official master, commit date: 2019-07-29 14:47
Armory : ArmorySDK1909 and ArmorySDK1908
OS : Windows 10 pro version 1903
Graphics card: Intel HD Graphics 620

Test File
http://forums.armory3d.org/uploads/default/original/2X/d/d0d30ee7efdaf9f30034bc7b9f2e78b17ff0a896.blend

**Comment by onelsonic** [comment]
is there a way to pinned them down so they stick in one place of the screen.
I know in Unity you can specify any coordinates of the screen.

See my updated example here : 
File : http://bit.ly/UICanvasanchor

Exporting it to Krom with a resizable window :
<img width="188" alt="windows_resizable_maximizable" src="https://user-images.githubusercontent.com/53947594/65393454-0ec7b700-dd81-11e9-9f94-bcd818c56230.png">

will make my object (here the Armory Logo) be in the right place in the normal window size:
<img width="481" alt="2019-09-22 21_15_33-basic2d" src="https://user-images.githubusercontent.com/53947594/65393475-4afb1780-dd81-11e9-9402-7d602ba398d1.png">

to something that does work at all when resizing the window:
<img width="1075" alt="2019-09-22 21_15_42-basic2d" src="https://user-images.githubusercontent.com/53947594/65393480-56e6d980-dd81-11e9-951a-52d41e7afd8d.png">

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/zui/commit/7a7ef72a68627eab781952e3106fc573f1ea992c. With anchor set to bottom-right, the element will stay pinned to that corner even after window resize.

**Comment by j2l** [comment]
In addition, Firefox is totally messing with ZUI:
- windows width change doesn't change anything in Firefox
- height change moves up/down a text box anchored at top-left but not a menu anchored at top-right
