### ISSUE TITLE
"Update SDK" button is ... downdating

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#1367]
**Description**
I updated the SDK this morning using the button in the prefs and I noticed some errors.
Since I have an error that you already [patched](https://github.com/armory3d/armory/commit/4d5309a07a38770fb833d05d509ca0c4149e3ad9), I compared props_ui.py of /armory and armory_backup and noticed that the update removed the fix.

I had to Restore the SDK (thanks for this button!) to get back to 19.09 tag but add-on version still states 2019.8.0
Weird.

**System**
Blender: 2.80.75
Armory: 2019.8 (19.09)

**Comment by j2l** [comment]
Aaarg, still getting "AttributeError: 'ShaderNodeTexImage' object has no attribute 'color_space'" for Armory Terrain.
I double checked I have `node.color_space = 'NONE'` at line 1207 of props_ui.py

**Comment by j2l** [comment]
Restarting Blender fixed it.

**Comment by luboslenco** [comment]
Should be fine in `ArmorySDK-2019-10`, please make to sure to also install the latest `armory.py` included in `ArmorySDK-2019-10.zip`.
