### ISSUE TITLE
I can't found All Armory3D's function(ex:"Player","Traits","LogicNodeEditor") Armory3D1909

### ISSUE THREAD

**Issue by NanakiChi** [armory3d/armory#1368]
HELLO
I have a question about "ArmorySDK1909".
Today,after updating Armory,I noticed the "Play"button, "Armory Traits" and "LogicNodeEditor" disapperd.

,
I deleted ArmorySDK1908 from add-on. And installed armory.py from ArmorySDK1909 when I updated

By the way ,
My friend face same ploblem.
He reinstall blender and install armory.py from ArmorySDK1909.
But he can't found them.

☆Please let me know if the location of the functions are moving.
 if this ploblem is bug, I wish to repaired quickly.

(Sorry for the poor English,because I'm Japanese.)

Blender:ver.2.8
Armory:ArmorySDK1909
OS:Windows10

**Comment by Sandy10000** [comment]
HELLO.

“SDK Path” may not be set.
![1](https://user-images.githubusercontent.com/48373918/64436026-7bdf1980-d0fe-11e9-839d-c02a790e31ef.jpg)
Specify "SDK path" in the white area of ​​the image."SDK path" refers to the "ArmorySDK" folder.

---Japanese---
こんにちは。

”SDK Path”が設定されていない可能性があります。
画像の白く囲んだ部分に"SDK path"を指定してください。"SDK path"は"ArmorySDK"フォルダのことを指します。

**Comment by NanakiChi** [comment]
https://github.com/armory3d/armory/issues/1368#issuecomment-528885231
Thank you for this comment.
I have just tried it, but I can't solve problem (T_T)

**Comment by Sandy10000** [comment]
Is there an "armory" folder in the "ArmorySDK" folder?
If there is no “armory” folder and there is an “armory_backup” folder, the following folders must be renamed.

| before | after |
--- | ---
| armory_backup | armory |
| iron_backup | iron |
| Kha_backup | Kha |
| Krom_backup | Krom |
| lib\armory_tools_backup | lib\armory_tools |
| lib\haxebullet_backup | lib\haxebullet |
| lib\haxerecast_backup | lib\haxerecast |
| lib\zui_backup | lib\zui |
| nodejs_backup | nodejs |

If you are worried about renaming, re-decompressing and replacing the zip compressed file has the same effect.
This phenomenon occurs when an error occurs after pressing the “Update SDK” button.

---Japanese---
"ArmorySDK"フォルダの中に"armory"フォルダはありますか?
”armory”フォルダが無く”armory_backup”フォルダがある場合フォルダのリネームが必要です。(フォルダは英文を参照してください)
リネーム作業が心配な場合はzip圧縮ファイルを再度展開し直して置き換えても同じ効果があります。
”Update SDK”ボタンを押した後エラーが発生した場合などにこの現象が発生します。

**Comment by NanakiChi** [comment]
https://github.com/armory3d/armory/issues/1368#issuecomment-529108372
Oh! Thank you so much!!
I have just solved this ploblem!
