### ISSUE TITLE
Massive lag on MacOS even though fps is around 40

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#1369]
Thank you for contributing to Armory!

**Description**
There is massive lag on macOS, feel like 15fps even though it show 40 fps in debug console. This happens in [FPS template](https://github.com/armory3d/armory_templates/tree/master/first_person). It looks like it only happen with game made before blender 2.8 because I can't reproduce it in new file

**To Reproduce**
Play [FPS template](https://github.com/armory3d/armory_templates/tree/master/first_person) on MacOS Mojave

**Expected behavior**
Real fps should be around like said in debug console, or debug console a liar.

**System**
Blender: Blender 2.8
Armory: Latest Git, last updated 1-2 days ago
OS: MacOS Mojave
Graphics card: Intel Iris Pro 1536 MB
CPU: 2.2 GHz Intel Core i7

**Test File**
[FPS template](https://github.com/armory3d/armory_templates/tree/master/first_person)

**Comment by luboslenco** [comment]
Should get resolved with eventual switch to metal but right now opengl is a mess on macos, sorry.
