### ISSUE TITLE
function missing not added from SDK - voxel example

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1371]
Not sure if it is related to the build process or only the voxel example, 
but when trying to compile it seems the function "packFloatInt16" is missing when it can effectively be found in the SDK : armory\Shaders\std\gbuffer.glsl

So not sure if this is broader issue.
Below is the error : 

	ERROR: C:\voxel\build_voxels\compiled\Shaders\Project\vox.frag.glsl:30: 'packFloatInt16' : no matching overloaded function found
	ERROR: C:\voxel\build_voxels\compiled\Shaders\Project\vox.frag.glsl:30: '' : missing #endif
	ERROR: C:\voxel\build_voxels\compiled\Shaders\Project\vox.frag.glsl:30: '' : compilation terminated
	ERROR: 3 compilation errors.  No code generated.

	SPIR-V is not generated for failed compile or link

	Compiling shader 3 of 4 (vox.frag.glsl) failed:
	Shader compiler error.
	(node:14472) UnhandledPromiseRejectionWarning: Shader compiler error.
	(node:14472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
	(node:14472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
	Build failed, check console

Any SDK
intel graphics
Win10Pro
Blender 2.80 offcial

**Comment by luboslenco** [comment]
Will fix at https://github.com/armory3d/voxel_world/issues/8, thanks for report!
