### ISSUE TITLE
Text autocomplete does not work in VScode

### ISSUE THREAD

**Issue by kone9** [armory3d/armory#1372]
Thank you for contributing to Armory!

**Description**
![Screenshot_4](https://user-images.githubusercontent.com/12847027/64374686-bc556f00-cffa-11e9-99ed-766871ee4f55.jpg)

Hello, I am installing the latest version of Armory Engine as an addon in Blender 2.8, the issue is that VScode does not work and install Kha Extension pack and look for the folder in the path but it still does not work.
Another issue aside if I put the path to KODE_studio does not work or does not appear as an editor when opening a file.
I would greatly appreciate a 2 minute video showing the procedure

**To Reproduce**
install armory engine as addond
After doing the whole procedure, look for the folder where you have visual studio and place it
![Screenshot_1](https://user-images.githubusercontent.com/12847027/64374475-55d05100-cffa-11e9-9721-84e00f5fd43f.jpg)

**Expected behavior**
I want autocomplete to work using vscode

**System**
Blender:
![Screenshot_2](https://user-images.githubusercontent.com/12847027/64374641-a8aa0880-cffa-11e9-86bc-d1acb6de2383.jpg)

Armory:
![Screenshot_3](https://user-images.githubusercontent.com/12847027/64374621-9d56dd00-cffa-11e9-8d1d-ddea62bc6cb4.jpg)

OS:windows 7 64 bits
Graphics card:gforce 9800 gt

**Test File**
*(drag & drop the zipped .blend file here)*
[prueba_armory.zip](https://github.com/armory3d/armory/files/3580943/prueba_armory.zip)

**Comment by BlackGoku36** [comment]
Try: Press`F1` and type `Haxe: Restart language server`

**Comment by luboslenco** [comment]
Hoping the `Restart language server` did the trick.
