### ISSUE TITLE
Armory becomes unusable after an error occurs when the "Update SDK" button is pressed.

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1375]
**Description**
An error occurs when press the "Update SDK" button on a computer that does not have "git" installed. At that time armory cannot be used because the renamed folder name is not restored. (There is no "armory" folder etc. but "armory_backup" folder etc.)

**To Reproduce**
Press the "Update SDK" button on a computer that does not have "git" installed.

**Expected behavior**
If an error occurs, there should be a process to restore the renamed folder name.

**System**
Blender:2.8
Armory:2019.9
OS:Windows10

**Comment by N8n5h** [comment]
So basically the restore sdk button is not working?

**Comment by Sandy10000** [comment]
I didn't notice the "Restore SDK" button next to the "Update SDK" button. If you click "Restore SDK" button, the folder name will be corrected without any problem. I was ridiculous. Thank you for teaching me.

**Comment by Sandy10000** [comment]
"Nodejs_backup" was not restored even when "Restore SDK" button was pressed. Other folders were restored.

**Comment by N8n5h** [comment]
small oversight when I updated the armory.py add-on file :sweat_smile: , should be fixed with https://github.com/armory3d/armsdk/pull/4

**Comment by Sandy10000** [comment]
Thank you for the response.
