### ISSUE TITLE
Textures in materials are not visible in rendering with Armory "IS MISSING UV MAP"

### ISSUE THREAD

**Issue by kone9** [armory3d/armory#1378]
Thank you for contributing to Armory!

**Description**
Hi, I have a scene with several materials.The materials are 1 texture and the main shader connected.The theme is that the textures are not seen, it is rare because it is a simple material.
<img width="798" alt="Screenshot_3" src="https://user-images.githubusercontent.com/12847027/64580452-c067f080-d35c-11e9-957f-78343fb8d04d.png">
In armory render path it is configured as MOVILE and as a rendering engine this CYCLES, although it would not have to influence the selected render engine, since armory uses a separate engine.
<img width="800" alt="Screenshot_4" src="https://user-images.githubusercontent.com/12847027/64580611-4be18180-d35d-11e9-8b0b-ac226885ed0b.png">

**To Reproduce**
Create one as if it were a house, add materials to the objects using the main BSD and a texture as color ... Then render and you will notice that the textures are not visible ... There are also rare transparencies that should not be.

**Expected behavior**
When rendering with armory engine, simple materials with textures would have to work correctly ... In any Game engine where I export this scene in GLTF format the materials work well, including godot engine or Unity.

**System**
Blender:
<img width="268" alt="Screenshot_5" src="https://user-images.githubusercontent.com/12847027/64580755-e641c500-d35d-11e9-9031-c03d90497a8c.png">

Armory:
<img width="702" alt="Screenshot_6" src="https://user-images.githubusercontent.com/12847027/64580782-f8bbfe80-d35d-11e9-90b0-eb8ed0c1ac65.png">

OS:
<img width="626" alt="Screenshot_7" src="https://user-images.githubusercontent.com/12847027/64580794-0b363800-d35e-11e9-8841-4c2317eb392d.png">

Graphics card:
<img width="309" alt="Screenshot_8" src="https://user-images.githubusercontent.com/12847027/64580826-2739d980-d35e-11e9-8d27-6e76140d7ff1.png">

**Test File**
*(drag & drop the zipped .blend file here)*
[terremoto_juego.zip](https://github.com/armory3d/armory/files/3593485/terremoto_juego.zip)

**Comment by N8n5h** [comment]
Can you toggle the system console by Window > Toggle System Console and check if there is any missing texture/image error message when you press Play? 

In the zip file you provided there is no external assets included like images, so I assume you link them from an external folder, right?

**Comment by kone9** [comment]
> Can you toggle the system console by Window > Toggle System Console and check if there is any missing texture/image error message when you press Play?
> 
> In the zip file you provided there is no external assets included like images, so I assume you link them from an external folder, right?
console message
<img width="794" alt="Screenshot_4" src="https://user-images.githubusercontent.com/12847027/64655582-18593280-d403-11e9-9032-35cb5820df90.png">
<img width="642" alt="Screenshot_5" src="https://user-images.githubusercontent.com/12847027/64655583-18593280-d403-11e9-8815-10383af87d3b.png">

Textures are packaged in the .blend
<img width="602" alt="Screenshot_3" src="https://user-images.githubusercontent.com/12847027/64655637-36bf2e00-d403-11e9-85c1-1b592955d9e7.png">

I send you the file again just in case but uploaded to google drive
In the project the textures are linked and are not in the same folder where the project is stored .... Is that the problem?
https://drive.google.com/open?id=1OLfZ8qzvyLVu7pN4_Do7B7GdT6oOlWdW

It seems that the problem is with UVMAP, but MAP uv are fine.
<img width="769" alt="Screenshot_6" src="https://user-images.githubusercontent.com/12847027/64655778-ac2afe80-d403-11e9-8f8e-72da5db51be7.png">

**Comment by kone9** [comment]
> Can you toggle the system console by Window > Toggle System Console and check if there is any missing texture/image error message when you press Play?
> 
> In the zip file you provided there is no external assets included like images, so I assume you link them from an external folder, right?

Also update the SDK with this button just in case, but it doesn't change, the result is the same.
<img width="496" alt="Screenshot_3" src="https://user-images.githubusercontent.com/12847027/64656411-b817c000-d405-11e9-975c-219fe31b3c26.png">

**Comment by kone9** [comment]
> Can you toggle the system console by Window > Toggle System Console and check if there is any missing texture/image error message when you press Play?
> 
> In the zip file you provided there is no external assets included like images, so I assume you link them from an external folder, right?

Similarly something strange happens, see what it looks like when I render using cycles ..
<img width="799" alt="Screenshot_8" src="https://user-images.githubusercontent.com/12847027/64656829-1c874f00-d407-11e9-8596-a2d8711412c4.png">


However with Eevee it looks good
<img width="800" alt="Screenshot_7" src="https://user-images.githubusercontent.com/12847027/64656798-02e60780-d407-11e9-90ca-9ce8dedfefd8.png">

Workbench also works well
<img width="798" alt="Screenshot_9" src="https://user-images.githubusercontent.com/12847027/64656853-3c1e7780-d407-11e9-9b9c-78f41c97da71.png">

**Comment by N8n5h** [comment]
https://youtu.be/kFXqIprtF2Y?t=388 please try the possible fixes shown in this video tutorial, the tutorial subject is unrelated but the video shows how to workaround or solve the issue with "missing uv map", 
basically:
connect a uv map node to the texture map node,
disconnect and reconnect a texture map node to the main shader node (principled BSDF/armory PBR/etc),
have the uv editor open and press tab a few times.

**Comment by kone9** [comment]
> as a workaround https://youtu.be/kFXqIprtF2Y?t=388 try the possible fixes shown in this video tutorial, the tutorial subject is unrelated but the video shows how to workaround or solve the issue with "missing uv map",
> basically:
> connect a uv map node to the texture map node,
> disconnect and reconnect a texture map node to the main shader node (principled BSDF/armory PBR/etc),
> have the uv editor open and press tab a few times.

OK I'M GOING TO TRY IT AND TOMORROW I SEND YOU SOME PICTURES TO SEE IF I COULD BE SOLVED .... IF I SOLVED THE PROBLEM I WILL DO A TUTORIAL IN SPANISH ... SALUDOS

**Comment by kone9** [comment]
TUTORIAL PROBLEM SOLUTION WHILE BOTH
https://www.youtube.com/watch?v=myE4UkkhoaA&t=33s

**Comment by kone9** [comment]
>  bpy.types.Material.export_uvs = BoolProperty(name="Export UVs", default=False)

<img width="799" alt="Screenshot_1" src="https://user-images.githubusercontent.com/12847027/64863962-61c89e00-d60c-11e9-9682-a196041a3602.png">

**Comment by luboslenco** [comment]
@N8n5h `export_uvs` property is supposed to tell whether the material uses UV map data or not. It's then used during geometry export in `export_mesh_data`. Need to investigate why it fails there, plus also seeing the weird cycles output.

**Comment by Naxela** [comment]
I've stumpled upon this problem too with various material-related addon projects, and I'm not entirely sure of the cause, but I suspect it might have something to do with somekind of caching or leftover datas somehow (maybe related to the new Blender EEVEE/PBR viewport) - In any case, I find that refreshing (tag for update) the materials and cleaning the Armory project afterwards helps on this by running:

```python
import bpy, arm

for mat in bpy.data.materials:
        mat.update_tag()

arm.make.clean()
```

![MatUV](https://user-images.githubusercontent.com/5429817/64884853-fa8a0880-d662-11e9-9fb4-e6a751925884.jpg)

**Comment by N8n5h** [comment]
Doing more tests, the problem seems to be with the dependy graph:

- Creating a new cube, applying a new material to the cube, and attaching a texture node to the material.

Then in the console:

```
>>>> bpy.data.objects['Cube'].to_mesh().materials[0].export_uvs
> False
```
```
>>>> bpy.data.objects['Cube'].evaluated_get(bpy.context.evaluated_depsgraph_get()).to_mesh().materials[0].export_uvs
> False
```

After calling import_materials()

```
>>>> bpy.data.objects['Cube'].to_mesh().materials[0].export_uvs
> True
```

```
>>>> bpy.data.objects['Cube'].evaluated_get(bpy.context.evaluated_depsgraph_get()).to_mesh().materials[0].export_uvs
> False
```

https://github.com/armory3d/armory/blob/baac952ba24d400065e4ee66b396086898b3026b/blender/arm/exporter.py#L1269

**Comment by luboslenco** [comment]
Thanks for the fix!
