### ISSUE TITLE
Unable to install, no errors

### ISSUE THREAD

**Issue by sortai** [armory3d/armory#1379]
**Description**
After installing armory.py and pointing the SDK path to the extracted folder, I see no change in under any menu

**System**
Blender: 2.80
Armory: 2019.9
OS: Windows 10
Graphics card: NVIDIA GeForce GTX 1050 Ti

**Comment by N8n5h** [comment]
Can you toggle the system console by Window > Toggle System Console and check if there is any error message when you launch Blender?

**Comment by VicentGJ** [comment]
I had experienced the same issue but it was with 2019.8. The newest version resolves it for me

**Comment by sortai** [comment]
> 
> 
> Can you toggle the system console by Window > Toggle System Console and check if there is any error message when you launch Blender?

there are no errors on launch, but I tried re-installing the add-on with the system console visible and I saw a long chain of errors, ending with
```
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray' from 'numpy.core' (C:\Users\barti\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py)
```

**Comment by N8n5h** [comment]
Where did you get the armory.py and the armory SDK? and what is the version of the SDK you used?

Also can you post a picture of the Armory add-on page inside Blender settings?

**Comment by sortai** [comment]
I fixed the problem; apparently it was the python installation that I use that was used instead of the one packaged with blender, after updating numpy everything started to work.
