### ISSUE TITLE
Changing Note Tree Type name doesn't change Tree in Armory Traits

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#138]
Changing the name of the tree type in Logic Node editor doesn't change the name in the Tree type under Armory traits in Object panel. It just makes the name turn red and says it is invalid. This should be done as part of the next build.
---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Merging with your newer report https://github.com/armory3d/armory/issues/158.
