### ISSUE TITLE
Cannot detect "escape", "comma", or "period" input on "keyboard" logic node or Linux (Krom).

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1387]
**Description**
The "escape" key is detected as the "enter" key.If you press "escape"-"enter"-"enter" in this order, the result will be "enter" - no response - "enter". "period" and "comma" have no reaction.

There is no problem with Windows (Krom) and browser targets.

"period" and "comma" have been fixed since there was a problem when we checked with Windows before. I don't think there is a problem with the fix, but it may be affected.
https://github.com/armory3d/armory/pull/1307

**To Reproduce**
Created an example that can easily check the key registered in the "keyboard" logic node.   
_/armory_examples/logic_examples/keyboard.blend_
Open keyboard.blend on a PC with Linux installed, set the target to Krom and press the start button. Then press “escape”, “period”, “comma” key.

**Expected behavior**
"escape", "period", and "comma" keys are detected normally.

**System**
Blender:2.8
Armory:2019.9
OS:Linux Mint 19.2 Tina

**Comment by zeeshan595** [comment]
Can confirm on linux (manjaro) the keyboard keys escape, period and comma are not working but this seems like a kha issue because I tried getting the input from kha and had the same issue

```hx
package arm;

import kha.input.KeyCode;
import iron.math.Vec4;
import armory.trait.physics.RigidBody;
import kha.input.Keyboard;

class TestScript extends iron.Trait {
	var keyboard:Keyboard;
	var body:RigidBody;

	public function new() {
		super();

		notifyOnInit(init);
		notifyOnRemove(exit);
	}

	private function keyDown(key:KeyCode) {
		if (key == KeyCode.Escape) {
			body.applyForce(new Vec4(0, 0, 1000));
		} else if (key == KeyCode.D) {
			body.applyForce(new Vec4(0, 0, 1000));
		}
	}

	private function keyUp(key:KeyCode) {}

	private function init() {
		body = object.getTrait(RigidBody);

		keyboard = Keyboard.get();
		keyboard.notify(keyDown, keyUp);
	}

	private function exit() {
		keyboard.remove(keyDown, keyUp, null);
	}
}
```

**Comment by Sandy10000** [comment]
Thank you for the information. I reported it to Kha.
https://github.com/Kode/Kha/issues/1129

**Comment by Sandy10000** [comment]
Added information to kha in response to information from the armory forum.
http://forums.armory3d.org/t/issues-with-keyboard-q-not-releasing/3601

**Comment by Sandy10000** [comment]
The fixes were merged on the Kha (Kinc) side. If  synchronize on the armory side, the problem will be solved.

**Comment by luboslenco** [comment]
Update included in ArmorySDK1911. Thanks!
