### ISSUE TITLE
How to add a cutscene?

### ISSUE THREAD

**Issue by swimming92404** [armory3d/armory#1389]
When I tried to realize it, I found that timeline animation was always loop, and I want to trigger the cutscene according to entering the empty volume object, but to do this, I must have a reference to the cutscene animation which I want to play.NLA and Actions Editors seem to only alow to add character animatons?
Sorry for my poor english.

**Comment by swimming92404** [comment]
I just added the Timeline animation to the NLA, It could be be played with haxe just once, but I still confused how to combine multiple object animations to NLA and get the reference to play?

**Comment by trsh** [comment]
I managed to make cut-scene with a custom node that a) blocks input b) Moves camera to right place c) makes those 2 black lines up an down

**Comment by knowledgenude** [comment]
I don't have used animations in Armory until now. But i think Timeline will follow the frames (like happens in Blender if you start the animation, it will be played in loop always until you stop it). So, you can use Timeline to animate objects of the scenery like plataforms, etc. that will always play the animation according to the game time. For "controlled" animations like idle, walk cycles, etc. or even a simple object movement, i think you should use the Action Editor.
