### ISSUE TITLE
Sound not working in Krom Linux

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armory#1396]
**Description**
Sound is not working in Krom Linux when hitting Play, tested with the Platformer template, works fine in Web Browser. 

**System**
Blender:b2.80
Armory: 1cdf519
OS: Ubuntu 18.04.2

**Comment by VicentGJ** [comment]
Same issue here

**Comment by N8n5h** [comment]
What can we do to help with this one @luboslenco? Is it an Armory issue or a Krom issue? if the later, how can we test to report it to the kha developers?

**Comment by luboslenco** [comment]
I tested on Ubuntu 18.04 and somehow the sound works for me, do you still experience this with `ArmorySDK-2019-10`?

**Comment by N8n5h** [comment]
Tested again with the latest armory.py, and SDK from latest commit: Armory v2019.10 ($Id: 23569febd4ea47500278608b0b3428a4d2162bcc $)

and sound is working again! :smile:

**Comment by luboslenco** [comment]
Wohooo! 🔉🎵
