### ISSUE TITLE
Canvas interface issues - unable to use in SDK 1909

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1397]
a picture say it all : 
The edit canvas interface is broken in the last SDK1909 making it unusable, sometimes when I switch windows on windows 10 the interface font just disappears : 
 
<img width="801" alt="2019-09-22 20_46_08-Clipboard" src="https://user-images.githubusercontent.com/53947594/65392943-02d8f680-dd7b-11e9-89db-8803d54d775f.png">

**Comment by onelsonic** [comment]
nevermind - had to clear my cache, it works now

**Comment by BlackGoku36** [comment]
That is Zui font issue, rescaling UI from armory2d's preference should be temporary solution

**Comment by onelsonic** [comment]
thank you I will work with the current dev build from now on.
The sound is not working on Krom, hope it is fixed in the next version.
