### ISSUE TITLE
Payment gateway that is not PayPal

### ISSUE THREAD

**Issue by Xananax** [armory3d/armory#14]
I'm hugely interested by Armory. Blender + Kha in a unified interface, it's like a dream come true. I'm ready to buy it right now. I don't care what's unfinished, I want to support the project.

However, I live in Lebanon, and Paypal blacklist Lebanon, without any disclosed reason. Years of petitions and messages on forums by thousands, asking why, have gone utterly unacknowledged (left with absolutely no answer, in a baffling display of rudeness on the part of PayPal), so there's no reason to believe this situation will change anytime soon.

I implore you to implement another payment gateway besides, or parallel to Paypal. I must emphasize that _absolutely any other gateway works_. PayPal is the only one that does this. I also should point out that Lebanon is not the only country that is blacklisted, though an exact list is unavailable (since PayPal is completely silent on the matter).

I hope this is possible!

**Comment by HeadClot** [comment]
Maybe Itch.io would work?

Here is a link to it. https://itch.io/

It would also give Armory 3D allot more exposure to the overall indie scene :)

**Comment by mikebelanger** [comment]
Has the author considered doing a kickstarter/indiegogo?  I know that's a much more complex thing, but I'm guessing crowdfunding sites accept payment methods besides paypal in Lebanon.

**Comment by Xananax** [comment]
@HeadClot I don't think the store has much to do with it; Itch proposes both Paypal and Stripe payments, but the actual gateway details are up to the author. There's a "deferred payment" system where Itch takes care of everything for you, but it's deferred.

@mikebelanger, depends. I know I can use kickstarter; I think IndieGogo is PayPal. But anyway, in my opinion, that's another business model entirely. Not that it is not worth discussing, but I don't think it's related to my request.

**Comment by luboslenco** [comment]
Hey,

I am really stunned to see such a passionate interest.

I knew there will be problems with PayPal, it was the first quick choice. Maybe adding itch as an alternative would work for now. Also, if there will be no way for someone to obtain the project, I will not mind making it available to him. Paid model is mainly introduced to increase the odds of keeping the project going at full pace, but in the end anyone using the project for his work will be super helpful.

Regarding the Kickstarter, I am leaning towards not going that way. As mentioned it is a complex thing and at this point I would rather spend all efforts on improving the project itself. I don't mind taking a slower start as there will be lots of stuff to fix anyway. Plus Kickstarter would likely lead to another rush for more features, which I would like to avoid till the end of year and spend power on making foundations more solid. :)

**Comment by Xananax** [comment]
Definitely agree on the Kickstarter thing. Imho, Kickstarter only works under very specific circumstances, which are not the circumstances of this project as of now. I could expand, but it isn't really the subject at hand.

Putting the project on itch, if you allow for stripe, would solve all of my problems :)

**Comment by HeadClot** [comment]
Just a bit of an heads up for you @luboslenco - if you put the preview on Itch.io use Itch.io refinery.

https://itch.io/refinery it will allow you to collect allot of good feedback about Armory 3D. I would encourage you to look into it. :)

**Comment by songproducer** [comment]
Bitcoin would be perfect for making contributions from PayPal restricted countries. I'm happy to help /advise on setting up if the developers are interested.

**Comment by luboslenco** [comment]
Resolving through a to-be-launched-soon Armory [patreon](https://www.patreon.com/armory) account. 🏗
