### ISSUE TITLE
Uncaught TypeError: Cannot read property \'speed\' of undefined

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#140]
![capture](https://cloud.githubusercontent.com/assets/15915424/23151046/0134d2ec-f7c6-11e6-9c07-0d3ff13c39d0.JPG)

---
optional - drag & drop .blend file here

**Comment by George-the-1st** [comment]
The animation action wasn't active but it was calling for the speed that the camera should be animated to move. This was done on purpose but it seems that the engine couldn't handle it.

**Comment by luboslenco** [comment]
Same here, otherwise it is very hard to figure out what you are attempting to do.
`optional - drag & drop .blend file here`

**Comment by George-the-1st** [comment]
Unfortunately, this error happened with a production file. I can't just share it. It sucks but I need to keep those close to heart until I release the game entirely.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/e03124367779e2dfbcd2c8474d5ac7d43bdc7fc0.
