### ISSUE TITLE
Read JSON and Read File node buggy

### ISSUE THREAD

**Issue by KeksMeister** [armory3d/armory#1402]
I have a file /Bundled/config.json as well as /Bundled/canvas/config.json. Whenever I try to read "config.json" with a Read File or Read JSON node I get data from the config file in the canvas directory. If the file in canvas does not exist or is renamed the data are read from the config in Bundled.
If there is a config.json file in Bundled and in a subdirectory besides canvas (eg /Bundled/test/config.json) the data are read from the file in Bundled.
While testing with this issue I also noticed that I am not able to read a file using a path in the Read JSON / File nodes. When I try to use "test/config.json" in the node the programm crashes, regardless if the file does exist or not.

**Comment by KeksMeister** [comment]
See also https://github.com/armory3d/armory/issues/1394 for the second part

**Comment by luboslenco** [comment]
Linking with https://github.com/armory3d/armory/issues/1394.
