### ISSUE TITLE
ColorRamp Combination

### ISSUE THREAD

**Issue by DoMal27** [armory3d/armory#1404]
**Description**
Combining node 'ColorRamp' results cutouts. Both mixing sequences of colorramps by connect them by them self or by mixing with MixRGB node.
Similar problem:  #905 

**To Reproduce**
My setups:
Set 1:
or gradient texture or some socket from 'Texture Coordinate' in ColorRamp in another ColorRamp

Set 2:
a gradient texture in ColorRamp, another ColorRamp receiving same grandient texture, both ColorRamp mixing in a MixRGB node by a factor of a third ColorRamp

**Expected behavior**
No cutouts or missing portions of the mix or combination

**System**
Blender: 2.80- (sub75) 2019 07 29
Armory: 2019.9.0
OS: Windows 10.0.17763
Graphics card: Intel UHD Graphics 630 & Radeon RX580

**Pictures**
Left-Blender Result; Center-Node Setup example; Right-Armory Result

![Bug_MixColorRamp](https://user-images.githubusercontent.com/20363585/65560224-2a16fb80-df14-11e9-9f15-dfeb7312f3d7.png)

![Bug_DoubleColorRamp](https://user-images.githubusercontent.com/20363585/65559866-cb04b700-df12-11e9-9580-1e9925f62237.png)

**Comment by j2l** [comment]
In 2019.11 B2.80
I also noticed a weird behavior with color ramps:
The range is re-interpreted, 
- below 0.5 has less "weight" than in Blender
- above 0.8 has more weight

See, top is Krom, bottom is Blender, same object (at 0,0,0), shader and color ramp:
![image](https://user-images.githubusercontent.com/65325/68992155-162eac80-0868-11ea-90dd-5bd29900b657.png)
