### ISSUE TITLE
Multiple Input Node - Join Controller Input

### ISSUE THREAD

**Issue by DoMal27** [armory3d/armory#1405]
The "Merge" node joins several lines in one. If I use it for multiple control inputs and (in this case) press simultaneously "S" and "Down", both will fire the "Merge" node causing twice effect if I want to move a character. 

![image](https://user-images.githubusercontent.com/20363585/65635191-3ce20c80-dfb6-11e9-989a-cd414b4c4804.png)

Would be nice if there was something to merge several entries without this double effect.

**Comment by zeeshan595** [comment]
This should give you the same result. Basically triggers a jump event and then you can use that event instead of a direct input event 

![image](https://user-images.githubusercontent.com/6005448/65640474-59943980-dfe2-11e9-8366-85652df8e29f.png)

**Comment by DoMal27** [comment]
Yes, the behavior is the same, but the player will be able to cheat.

I think I was misunderstood. If in your example the player press both in same time (space+cross/a) the character will receive 2x the event Jump instead of only one, causing a double jump.

The question here is:
How can I set up multiple inputs for the same action or a single event, without being triggered multiple times?
If there is a node or a sub-menu in Render/ArmoryProject to create special events, it will be easier.

**Comment by zeeshan595** [comment]
I see what you mean.
I think most games restrict input from one device at a time.
For example: 
In divinity if you press enter on the start key you will not be allowed to use a gamepad. They game will ask you to go back to the title screen and press `A` on the game pad.
Some games also implement it in the options menu. 

I am not too sure if there is a node that exists which can do this but here is a quick haxe script you can write to do the following and it will fire an event once so you can use nodes to catch it

```
package arm;

import armory.system.Event;
import kha.input.KeyCode;
import kha.input.Keyboard;

class TestScript extends iron.Trait {
	var keyboard:Keyboard;
	var isSpacePressed = false;
	var isWPressed = false;

	public function new() {
		super();

		notifyOnInit(init);
		notifyOnRemove(exit);
	}

	private function keyDown(key:KeyCode) {
		if (key == KeyCode.Space) {
			isSpacePressed = true;
		}
		if (key == KeyCode.W) {
			isWPressed = true;
		}

		if (isSpacePressed && isWPressed) {
			Event.send('Jump Forward');
		}
	}

	private function keyUp(key:KeyCode) {
		if (key == KeyCode.Space) {
			isSpacePressed = false;
		}
		if (key == KeyCode.W) {
			isWPressed = false;
		}
	}

	private function init() {
		keyboard = Keyboard.get();
		keyboard.notify(keyDown, keyUp);
	}

	private function exit() {
		keyboard.remove(keyDown, keyUp, null);
	}
}
```
![image](https://user-images.githubusercontent.com/6005448/65645018-d5e04a00-dfed-11e9-843a-4820e6357792.png)

**Comment by DoMal27** [comment]
It's much easier control the events by Haxe.
I'm not totally familiar with Haxe and Blender together yet but I'll get there.
I appreciate your time, it was very enlightening.

...
Just a complement to future readers, need to update `keyUp` section
```haxe
private function keyUp(key:KeyCode) {
		var currentKey = iron.system.Input.Keyboard.keyCode(key).toLowerCase();
		if (currentKey == key1) {//KeyCode.Space) {
			isKey1Pressed = false;
		}
		if (currentKey ==  key2) {//KeyCode.W) {
			isKey2Pressed = false;
		}
```
