### ISSUE TITLE
key "Principled BSDF" not found'

### ISSUE THREAD

**Issue by zqc972** [armory3d/armory#1407]
I use blender 2.80 with ArmorySDK-2019-08 to open these templates in armory_templates-2019.08.zip, when i click "Play", it always prompts:key "Principled BSDF" not found',  error info like this(racetrack.blend):

Traceback (most recent call last):
  File "D:\ArmorySDK1908//armory/blender\arm\props_ui.py", line 523, in execute
    make.play()
  File "D:\ArmorySDK1908//armory/blender\arm\make.py", line 462, in play
    build(target=runtime_to_target(), is_play=True)
  File "D:\ArmorySDK1908//armory/blender\arm\make.py", line 346, in build
    export_data(fp, sdk_path)
  File "D:\ArmorySDK1908//armory/blender\arm\make.py", line 110, in export_data
    exporter.execute(bpy.context, asset_path, scene=scene)
  File "D:\ArmorySDK1908//armory/blender\arm\exporter.py", line 1970, in execute
    self.make_default_mat('armdefault', self.defaultMaterialObjects)
  File "D:\ArmorySDK1908//armory/blender\arm\exporter.py", line 1495, in make_default_mat
    mat.node_tree.nodes['Principled BSDF'].inputs[7].default_value = 0.25
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

location: <unknown location>:-1

is this problem a bug? please help me,thanks!

**Comment by zqc972** [comment]
yes,I tried it with ArmorySDK-2019-09,the same problem is still there....Uh,I also tried to open the projects of armory_tutorials-19.08,and these projects can run perfectly,it seems that it will only report errors to armory_templates-2019.08

**Comment by luboslenco** [comment]
Sounds weird. Are all of the templates affected or just the racetrack? I am afraid the only way to pinpoint the issue is to progressively remove stuff from the template file until the error goes away, as I am unable to reproduce it so far.

**Comment by zqc972** [comment]
Hi,this problem affects most of projects in armory_templates-2019.08,but in these days,I found a way to run them correctly,I guess it's probably because some objects of these projects don't have material,the program does not set the default material for them correctly so report this error.

In armory_templates-2019.08,these objects don't have material:
archery/archery.blend:
     JFootL, JFootR, JForeArmL, JForeArmR, JHandL, JHandR, JHead, JHips, JLegL, JLegR, JShoulderL, JShoulderR, JSpine, JUpLegL, JUpLegR, Player
first_person/first_person.blend:
     Player
platformer/platformer.blend:
    Player
racetrack/racetrack.blend:
     Plane, Plane.001, Plane.002, Plane.003, Trigger0, Trigger1, Trigger2, Trigger3
third_person/third_person.blend:
     Player
third_person_terrain/third_person.blend:
     Player,tree-treeCollision, tree.001-treeCollision.001, tree.002-treeCollision.002, tree.003-treeCollision.003
top_down/top_down.blend:
     Player
twinstick/twinstick.blend:
     Player

After giving these objects a material, the error disappears.
![QQ截图20191005155034](https://user-images.githubusercontent.com/20378865/66251911-39a20a00-e788-11e9-90b2-b35c0c88a00a.png)
![QQ截图20191005155234](https://user-images.githubusercontent.com/20378865/66251914-3a3aa080-e788-11e9-8dd5-5597fb2e7e9b.png)

**Comment by luboslenco** [comment]
Thanks for the pictures! Possibly fixed now at https://github.com/armory3d/armory/commit/ced8cd845fa98893cb870ae628b7e328b25dcb2e.

**Comment by zqc972** [comment]
Yes! It 's fixed,thanks!
