### ISSUE TITLE
SDK SDK1909 - android compilation fail

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1408]
Hi there, 
when trying to compile a basic cube project to android (target Android (C))
I have the following compilation error with the SDK1909 :

	Compiling shader 1 of 19 (armdefault_mesh.frag.glsl).
	Compiling shader 2 of 19 (armdefault_mesh.vert.glsl).
	Compiling shader 3 of 19 (armdefault_shadowmap.frag.glsl).
	Compiling shader 4 of 19 (armdefault_shadowmap.vert.glsl).
	Unknown profile android-native

	Unknown profile android-native

	Unknown profile android-native

	Compiling shader 2 of 19 (armdefault_mesh.vert.glsl) failed:
	Shader compiler error.
	(node:14540) UnhandledPromiseRejectionWarning: Shader compiler error.
	(node:14540) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
	(node:14540) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
	Compiling shader 3 of 19 (armdefault_shadowmap.frag.glsl) failed:
	Shader compiler error.
	Unknown profile android-native

	Compiling shader 1 of 19 (armdefault_mesh.frag.glsl) failed:
	Shader compiler error.
	Compiling shader 4 of 19 (armdefault_shadowmap.vert.glsl) failed:
	Shader compiler error.
	Finished in 1.5225307941436768
	Build failed, check console

**Comment by Sandy10000** [comment]
Hi.

How to deal is written on this page.
http://forums.armory3d.org/t/armory-android-publish-error/3549

**Comment by onelsonic** [comment]
thanks I can publish with the current build but I lost the sound in Krom.
Let's see when Krom is re-written.
