### ISSUE TITLE
Error with Build 8

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#142]
Got this error : 
D:\Documents Thoom\Documents\Downloads\Sources/arm/node/NodeTree.hx:5: characters 30-64 : Type not found : armory.trait.internal.NodeExecutor
D:\Documents Thoom\Documents\Downloads\Sources/Main.hx:3: lines 3-42 : Defined in this class

Haxe compiler error.
Build failed, check console
---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Heyo,

Does cleaning the project help? It looks like some old logic node stuff is stuck there.

**Comment by MagicalPaladin** [comment]
Well, now blender crash 3 secs after playing here you are : Uniform W not found.
Uniform eye not found.
Uniform W not found.
Uniform eye not found.
Uniform W not found.
Uniform eye not found.
Uniform W not found.
Uniform eye not found.

**Comment by luboslenco** [comment]
What project is this? Can you paste the blend?

**Comment by MagicalPaladin** [comment]
Scene 3

**Comment by AndreaMonzini** [comment]
Scene works here with Builds 8 in OS X® 10.11.6

**Comment by luboslenco** [comment]
Any luck with the new patched builds(08b)? Should be fixed.
https://armory.itch.io/armory3d

**Comment by MagicalPaladin** [comment]
Works

**Comment by luboslenco** [comment]
Great!
