### ISSUE TITLE
Skinning is broken on android.

### ISSUE THREAD

**Issue by DarthVernus** [armory3d/armory#1422]
**Description**
Skinning is broken on android.
![device-2019-10-04-062130](https://user-images.githubusercontent.com/11670568/66185853-602d4b80-e689-11e9-84cc-0c7e4dc48deb.png)

**To Reproduce**
Generate android project (HashLink(C)), open it in Android Studio, connect your device and press 'Run'.

**Expected behavior**
krom, html5 works correctly.

**System**
Blender: 2.80
Armory: 1910
OS: win 7
Graphics card: nvidia 750 ti
Device: huawei mediapad t3 10 (android version: 7.0)

**Test File**
armory_examples/animation/animation.blend.

**Comment by onelsonic** [comment]
Cannot reproduce your issues, but I had similar problem before.
It happened when I did move the armature separately from the model or moved the model separately from the armature. It also occurred when I somehow change the model origin incorrectly in blender. Best is to use an empty and put everything inside to move it.

What I get with the last built - with the Android Studio 3.5 (I tested 3.5.1 but it did not worked)
and I don't update the Gradle plugin, I leave it as it is.
On a samsung galaxy it works fine:
![Screenshot_20191005-121736_animation](https://user-images.githubusercontent.com/53947594/66253570-ec636f80-e76a-11e9-95a8-05df08882cb7.jpg)

**Comment by N8n5h** [comment]
Unable to reproduce on the animation example with:

Device: Samsung Galaxy Grand Prime Android 5.1.1
Armory SDK: Latest version, from commit cb2592ad54326067752640181069208ce15dc2a8
armory.py, Latest version from commit [953ffd5](https://github.com/armory3d/armsdk/commit/953ffd51ae568673fa80851a42e4bb7924975088)
Android Studio 3.5

Steps I did:
1) add android-hl export settings
2) add mobile render path
3) config the export render path to be mobile
4) Export
5) Open animation project file in Android Studio
6) Run app

**Comment by DarthVernus** [comment]
I did all steps but animation example still don't work.

**Comment by onelsonic** [comment]
I'm on Win10 and using Android Oreo 8.0
maybe something behaving differently with a different version of android? We can check what is differing, step by step.

**Comment by N8n5h** [comment]
> I did all steps but animation example still don't work.

In that case what I would try is testing the same setup with a different device with a different android version, to pinpoint if the issue is the first device or your setup.

**Comment by knowledgenude** [comment]
I think Apply Scale on mesh should solve this
