### ISSUE TITLE
Error when running project

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1424]
Armory v2019.10 ($Id: 23569febd4ea47500278608b0b3428a4d2162bcc $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 44)

Traceback (most recent call last):
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\props_ui.py", line 457, in execute
    make.play()
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make.py", line 462, in play
    build(target=runtime_to_target(), is_play=True)
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make.py", line 346, in build
    export_data(fp, sdk_path)
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make.py", line 95, in export_data
    make_renderpath.build()
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 170, in build
    if len(bpy.data.cameras) > 0 and bpy.data.cameras[0].dof.use_dof:
AttributeError: 'Camera' object has no attribute 'dof'

**Comment by michelson** [comment]
same here

**Comment by N8n5h** [comment]
First, can you post a minimal project (blend file) to reproduce the issue?

Second, what where you doing before the issue show up? Did it work before?

**Comment by trsh** [comment]
@michelson can you? My project is pretty huge. The error showed up after updating SDK in settings.

**Comment by michelson** [comment]
@trsh , I'm trying but now I can't reproduce the issue. It's working! but I get a new one #1428

**Comment by N8n5h** [comment]
> @michelson can you? My project is pretty huge. The error showed up after updating SDK in settings.

You could maybe make a copy of your project and trim the copy project of any bloat that is not related to the issue and you don't want to share (materials / textures / meshes / objects / scripts / logic nodes / etc ) where the issue can still be reproduced.

Or otherwise maybe a set of steps that leads to the issue helps too.

**Comment by luboslenco** [comment]
Please reopen with .blend file if problem persists.
