### ISSUE TITLE
grease pencil support?

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1427]
the grease pencil support has been removed because of the recent changes with blender 2.80,
or due to performances related issues with the engine?

It seems like this would made some pretty good 2.5D animation capability into Armory.

What are your thoughts?
Where can I found the old code that supported it to have a look?

Here is an example of the new Grease Pencil for 2.80 :
http://bit.ly/sample_greasepencil

<img width="150" alt="2019-10-07 14_24_49-Blender  C__Users_devWin10_Downloads_Still_by_Jason_Lee blend" src="https://user-images.githubusercontent.com/53947594/66311288-65e79300-e90e-11e9-8158-ed585072faa9.png">

**Comment by BlackGoku36** [comment]
linked to: https://github.com/armory3d/armory/issues/810

**Comment by nanjizal** [comment]
My experimental drawing code Trilateral ( 2D ) can be used in Iron I don't know if that's helpful.  I was hoping for some changes in Iron to allow per triangle transparency ( and perhaps texture I forget ) and so have not worked on Iron / Armory integration recently, but have moved to using Trilateral with my geom math library ( now with dual Quaternion support ).

This is a pure Haxe WebGL test that shows texture spinning, I have some with Iron around also.
https://nanjizal.github.io/trilateralTextureTest/bin/

The drawing api is fairly easy to use but far from perfect.

**Comment by N8n5h** [comment]
> it was removed due to b2.8 changes
What changes that produced the removal? Changes to the API?
Can this code be reintroduced if updated, or is it obsolete or not optimal?

**Comment by luboslenco** [comment]
Yes, api changes. I have pushed parts of the old (non-functional) grease pencil code to https://github.com/armory3d/armory/tree/grease. Not yet sure what needs to be reworked but maybe it gets useful.
