### ISSUE TITLE
Build 8 Linux version not working

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#143]
Some dynamic dependencies are not being satisfied.

Blender is not starting because linpng16 is not found in my system:
/home/artur/.config/itch/apps/Armory3D/Armory/blender: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory

If I run "ldd ./blender" inside the armory provided blender version the required dynamic libraries is bigger than the official blender build and not all the libraries are provided. This also shows that other dynamic dependencies are not satisfied also. Armory build 7 had fewer dependencies than 8 and it seems all were provided. This seems like differences in the compilation options or some new libs not beeing provided in the custom build.

ldd for Armory build 8
<pre>
linux-vdso.so.1 (0x00007ffdfe2f9000)
libpng16.so.16 => not found
libz.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libz.so.1 (0x00007ff90a326000)
libfreetype.so.6 => /home/artur/.config/itch/apps/Armory3D/Armory/libfreetype.so.6 (0x00007ff90a079000)
libpython3.5m.so.1.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libpython3.5m.so.1.0 (0x00007ff9099e8000)
libGLEW.so.1.13 => /home/artur/.config/itch/apps/Armory3D/Armory/libGLEW.so.1.13 (0x00007ff909750000)
libopenal.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libopenal.so.1 (0x00007ff9094de000)
libtiff.so.5 => /home/artur/.config/itch/apps/Armory3D/Armory/libtiff.so.5 (0x00007ff909269000)
libOpenImageIO.so.1.6 => /home/artur/.config/itch/apps/Armory3D/Armory/libOpenImageIO.so.1.6 (0x00007ff90895a000)
libjpeg.so.8 => /home/artur/.config/itch/apps/Armory3D/Armory/libjpeg.so.8 (0x00007ff908700000)
libboost_locale.so.1.61.0 => not found
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff9084e2000)
libHalf.so.12 => /usr/lib/libHalf.so.12 (0x00007ff90829f000)
libIex-2_2.so.12 => /usr/lib/libIex-2_2.so.12 (0x00007ff90807f000)
libIlmImf-2_2.so.22 => /usr/lib/libIlmImf-2_2.so.22 (0x00007ff907ba3000)
libjemalloc.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libjemalloc.so.1 (0x00007ff90796b000)
libGLU.so.1 => /usr/lib/libGLU.so.1 (0x00007ff9076ea000)
libGL.so.1 => /usr/lib/libGL.so.1 (0x00007ff9073ab000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007ff907049000)
libXi.so.6 => /usr/lib/libXi.so.6 (0x00007ff906e36000)
libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007ff906c30000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007ff906a26000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007ff906822000)
libv8.so => /home/artur/.config/itch/apps/Armory3D/Armory/libv8.so (0x00007ff905c52000)
libv8_libplatform.so => /home/artur/.config/itch/apps/Armory3D/Armory/libv8_libplatform.so (0x00007ff90a72c000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007ff90588c000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff90a541000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007ff905583000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007ff9051e8000)
libgomp.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libgomp.so.1 (0x00007ff904fc4000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ff904dac000)
libpng12.so.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libpng12.so.0 (0x00007ff904b85000)
libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007ff90495a000)
libutil.so.1 => /usr/lib/libutil.so.1 (0x00007ff904756000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007ff90454e000)
liblzma.so.5 => /home/artur/.config/itch/apps/Armory3D/Armory/liblzma.so.5 (0x00007ff90432b000)
libjbig.so.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libjbig.so.0 (0x00007ff90411c000)
libboost_filesystem.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_filesystem.so.1.58.0 (0x00007ff903f00000)
libboost_regex.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_regex.so.1.58.0 (0x00007ff903bcb000)
libboost_system.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_system.so.1.58.0 (0x00007ff9039c6000)
libboost_thread.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_thread.so.1.58.0 (0x00007ff903797000)
libopenjpeg.so.5 => /home/artur/.config/itch/apps/Armory3D/Armory/libopenjpeg.so.5 (0x00007ff903573000)
libIlmThread-2_2.so.12 => /usr/lib/libIlmThread-2_2.so.12 (0x00007ff90336c000)
libnvidia-tls.so.375.39 => /usr/lib/libnvidia-tls.so.375.39 (0x00007ff903168000)
libnvidia-glcore.so.375.39 => /usr/lib/libnvidia-glcore.so.375.39 (0x00007ff901395000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007ff90117f000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007ff900f55000)
libv8_libbase.so => /home/artur/.config/itch/apps/Armory3D/Armory/libv8_libbase.so (0x00007ff90a70b000)
libicui18n.so => /home/artur/.config/itch/apps/Armory3D/Armory/libicui18n.so (0x00007ff900cdb000)
libicuuc.so => /home/artur/.config/itch/apps/Armory3D/Armory/libicuuc.so (0x00007ff90a575000)
libicui18n.so.55 => /home/artur/.config/itch/apps/Armory3D/Armory/libicui18n.so.55 (0x00007ff90081f000)
libicuuc.so.55 => /home/artur/.config/itch/apps/Armory3D/Armory/libicuuc.so.55 (0x00007ff90046c000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007ff900268000)
libicudata.so.55 => /home/artur/.config/itch/apps/Armory3D/Armory/libicudata.so.55 (0x00007ff8fe7b0000)
</pre>

ldd for Armory build 7
<pre>
linux-vdso.so.1 (0x00007ffcb031d000)
libpng12.so.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libpng12.so.0 (0x00007f17807a8000)
libz.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libz.so.1 (0x00007f178058d000)
libfreetype.so.6 => /home/artur/.config/itch/apps/Armory3D/Armory/libfreetype.so.6 (0x00007f17802e0000)
libpython3.5m.so.1.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libpython3.5m.so.1.0 (0x00007f177fc4f000)
libGLEW.so.1.13 => /home/artur/.config/itch/apps/Armory3D/Armory/libGLEW.so.1.13 (0x00007f177f9b7000)
libopenal.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libopenal.so.1 (0x00007f177f745000)
libtiff.so.5 => /home/artur/.config/itch/apps/Armory3D/Armory/libtiff.so.5 (0x00007f177f4d0000)
libOpenImageIO.so.1.6 => /home/artur/.config/itch/apps/Armory3D/Armory/libOpenImageIO.so.1.6 (0x00007f177ebc1000)
libjpeg.so.8 => /home/artur/.config/itch/apps/Armory3D/Armory/libjpeg.so.8 (0x00007f177e967000)
libboost_locale.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_locale.so.1.58.0 (0x00007f177e65a000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f177e43c000)
libHalf.so.12 => /usr/lib/libHalf.so.12 (0x00007f177e1f9000)
libIex-2_2.so.12 => /usr/lib/libIex-2_2.so.12 (0x00007f177dfd9000)
libIlmImf-2_2.so.22 => /usr/lib/libIlmImf-2_2.so.22 (0x00007f177dafd000)
libjemalloc.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libjemalloc.so.1 (0x00007f177d8c5000)
libGLU.so.1 => /usr/lib/libGLU.so.1 (0x00007f177d644000)
libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f177d305000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f177cfa3000)
libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f177cd90000)
libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f177cb8a000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f177c980000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f177c77c000)
libv8.so => /home/artur/.config/itch/apps/Armory3D/Armory/libv8.so (0x00007f177bbac000)
libv8_libplatform.so => /home/artur/.config/itch/apps/Armory3D/Armory/libv8_libplatform.so (0x00007f1780bba000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f177b7e6000)
/lib64/ld-linux-x86-64.so.2 (0x00007f17809cf000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f177b4dd000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f177b142000)
libgomp.so.1 => /home/artur/.config/itch/apps/Armory3D/Armory/libgomp.so.1 (0x00007f177af1e000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f177ad06000)
libexpat.so.1 => /usr/lib/libexpat.so.1 (0x00007f177aadb000)
libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f177a8d7000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f177a6cf000)
liblzma.so.5 => /home/artur/.config/itch/apps/Armory3D/Armory/liblzma.so.5 (0x00007f177a4ac000)
libjbig.so.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libjbig.so.0 (0x00007f177a29d000)
libboost_filesystem.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_filesystem.so.1.58.0 (0x00007f177a081000)
libboost_regex.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_regex.so.1.58.0 (0x00007f1779d4c000)
libboost_system.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_system.so.1.58.0 (0x00007f1779b47000)
libboost_thread.so.1.58.0 => /home/artur/.config/itch/apps/Armory3D/Armory/libboost_thread.so.1.58.0 (0x00007f1779918000)
libopenjpeg.so.5 => /home/artur/.config/itch/apps/Armory3D/Armory/libopenjpeg.so.5 (0x00007f17796f4000)
libicui18n.so.55 => /home/artur/.config/itch/apps/Armory3D/Armory/libicui18n.so.55 (0x00007f1779238000)
libicuuc.so.55 => /home/artur/.config/itch/apps/Armory3D/Armory/libicuuc.so.55 (0x00007f1778e85000)
libIlmThread-2_2.so.12 => /usr/lib/libIlmThread-2_2.so.12 (0x00007f1778c7e000)
libnvidia-tls.so.375.39 => /usr/lib/libnvidia-tls.so.375.39 (0x00007f1778a7a000)
libnvidia-glcore.so.375.39 => /usr/lib/libnvidia-glcore.so.375.39 (0x00007f1776ca7000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f1776a91000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f1776867000)
libv8_libbase.so => /home/artur/.config/itch/apps/Armory3D/Armory/libv8_libbase.so (0x00007f1780b97000)
libicui18n.so => /home/artur/.config/itch/apps/Armory3D/Armory/libicui18n.so (0x00007f17765ed000)
libicuuc.so => /home/artur/.config/itch/apps/Armory3D/Armory/libicuuc.so (0x00007f1780a03000)
libicudata.so.55 => /home/artur/.config/itch/apps/Armory3D/Armory/libicudata.so.55 (0x00007f1774b35000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f1774931000)
</pre>

While ldd for an official blender 2.78c is:
<pre>
linux-vdso.so.1 (0x00007ffda73ea000)
librt.so.1 => /usr/lib/librt.so.1 (0x00007f29cd8a9000)
libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f29cd5d0000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f29cd3b2000)
libGLU.so.1 => /usr/lib/libGLU.so.1 (0x00007f29cd131000)
libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f29ccdf2000)
libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f29cca90000)
libXi.so.6 => /usr/lib/libXi.so.6 (0x00007f29cc87d000)
libXxf86vm.so.1 => /usr/lib/libXxf86vm.so.1 (0x00007f29cc677000)
libXrender.so.1 => /usr/lib/libXrender.so.1 (0x00007f29cc46d000)
libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f29cc269000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f29cc065000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f29cbc9f000)
/lib64/ld-linux-x86-64.so.2 (0x00007f29cdab1000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f29cb996000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f29cb77e000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007f29cb560000)
libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f29cb34a000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f29cafaf000)
libnvidia-tls.so.375.39 => /usr/lib/libnvidia-tls.so.375.39 (0x00007f29cadab000)
libnvidia-glcore.so.375.39 => /usr/lib/libnvidia-glcore.so.375.39 (0x00007f29c8fd8000)
libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f29c8dc2000)
libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f29c8b98000)
libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f29c8994000)
</pre>

Edited: Should I worry about armory differing too much from an official blender and having problems running it as an add-on in the future? Or these differences are just for the current support of "Play in viewport"?

**Comment by luboslenco** [comment]
Armory will never divert from official Blender, the changes are only to "inject" play in vieport functionality. Fixing the lib issues tonight, thanks for report!

**Comment by arturjpv** [comment]
Nice to hear that!

Keep up the good work!

**Comment by luboslenco** [comment]
New patched build is up (08b) - any progress on this?
(https://armory.itch.io/armory3d)

The reason for long ldd list - Blender compiles statically on Linux, but I had troubles with that for Armory. As an alternative solution the libs are 'hoarded' alongside the binary.

**Comment by arturjpv** [comment]
The provided blender version is working now.

I still have to move it outside the Itch.io folder. So issues like #135 and #96 seems to be still present. Although this seems related with Kha instead of armory.

After moving armory from Itch.io, I'm able to play armory scenes.

I opened a random example, don't remember which now, and saw some graphical problems. Instead of providing wrong information here I will do a better analysis. I will ensure my projects are clean from past builds, to see if the problem is real, and will go one by one, from simple to complex, to locate the problem better (still need to find the time for this).

We can close this issue! :-)

**Comment by luboslenco** [comment]
Great! Sorry for 'wasting' your bandwidth.

Not being able to play from itch is a big issue. I have one more idea to try there, hopefully it will work. Will report at https://github.com/armory3d/armory/issues/135.
