### ISSUE TITLE
physicly based procedural ik animation?

### ISSUE THREAD

**Issue by jaredgreen2** [armory3d/armory#1430]
if there isn't a system for this, there should be.

**Comment by luboslenco** [comment]
Hoping to implement eventually but let's focus on existing issues first. 🙂

**Comment by jaredgreen2** [comment]
any clue as to when?

    On Tuesday, October 8, 2019, 7:45:12 AM MST, Lubos Lenco <notifications@github.com> wrote:  
 
 
Closed #1430.
