### ISSUE TITLE
 Uniform not found warnings

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1432]
I keep getting the following errors in my projects no matter the Renderer I use.
Things seems to work fine but these errors are still popping at the start :

	W/Kinc: Uniform N not found.
	W/Kinc: Uniform sunDir not found.
	W/Kinc: Uniform sunCol not found.
	W/Kinc: Uniform envmapStrength not found.
	W/Kinc: Uniform LWVP not found.
	W/Kinc: Uniform shadowsBias not found.

**Comment by DoMal27** [comment]
Some combinations I noticed:

Where there is no light in the scene:
```
Uniform invVP not found.
Uniform eye not found.
Uniform cameraProj not found.
Uniform eyeLook not found.
Uniform receiveShadow not found.
Uniform W not found.

```

Deferred render + Area Lamp:
```
Uniform lightProj not found.
```

Forward render + Area Lamp:
```
Uniform receiveShadow not found.
Uniform lightProj not found.
```

I think it started with version 201910.
