### ISSUE TITLE
Tilesheet Framerate

### ISSUE THREAD

**Issue by ControllerArts** [armory3d/armory#1437]
**Description**
Tilesheet's framerate changes depending on whether or not there is a light in the scene and/or shadow option on/off.

[Q] Does this delay happen only with tilesheet or is it a "no light / shadow" scene problem?

My scene setup:
1: 4x4 Tilesheet with Framerate 16.7, loop mode.
1A: With any light in the scene and shadow option On
1B: No lights Or no shadow enabled in options

What happens:
1: The game's framerate is constant at 16.7 ms.
1A: Tilesheet takes 367 ms to complete one cycle.
1B: Tilesheet takes 500 ms to complete one cycle.

**To Reproduce**
- New blender file, clear the default scene
- Add a plane and setup any tilesheet in loop
- New nodetree with Init + Play Tilesheet
- Run the game and check the framerate of the animation
- Close the game add a sun, turn Off shadow in Light option and/or in armory render options
- Run the game (the animation frame rate should be the same)
- Close the game, turn On shadow both in Light option and in armory render options
- Run the game (the animation plays faster)

**Expected behavior**
- Same frame rate for tilesheet, with or without light.

**System**
Blender: 2.80.75
Armory: 2019.10
OS: Windows 10.0.17763 & Arch linux - 5.2.20-1-Manjaro
Graphics card: Intel UHD Graphics 630 & Radeon RX580

**Comment by MoritzBrueckner** [comment]
Hi, this will be fixed by https://github.com/armory3d/iron/pull/163. Thanks for the report!

> [Q] Does this delay happen only with tilesheet or is it a "no light / shadow" scene problem?

It was a tilesheet-only problem, I explained it in the PR linked above :)
