### ISSUE TITLE
GUI for debug console is a mess

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#144]
Reading information off of this thing is hard. It should have a very simple layout that is visible and then a drop down that gives you the nitty gritty or another checkbox next to the debug console checkbox that unlocks the advanced debug console. The streamlined debug console should tell me the current framerate as well as the lowest hit framerate and the highest hit framerate and the average framerate at the very least. You can do a lot with this information alone and having it very clearly stated front and center would help. Either that or a better wiki page for it.
---
optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
Please keep it in a single issues: https://github.com/armory3d/armory/issues/85

The first line in the console tells current **frame time**, then minimum and maximum.

Conversion example: 1000 / 16.7(rounded) = 60 fps

<img width="253" alt="console" src="https://cloud.githubusercontent.com/assets/3685704/23649516/13049de0-031f-11e7-8886-915413d0fe23.png">
