### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by karlxuthus** [armory3d/armory#1440]
Thank you for contributing to Armory!

**Description**
I install the add-on and test the cube. When I click the player, the tip shows 'build failed'

**To Reproduce**
![1](https://user-images.githubusercontent.com/24907980/67073252-44619380-f1b9-11e9-8cde-27b4eb0b0cd6.png)

**Expected behavior**
![02](https://user-images.githubusercontent.com/24907980/67073493-cfdb2480-f1b9-11e9-9957-2932fdcf0a8a.png)

**System**
Blender:2.8
Armory:1910
OS: Win 10
Graphics card: GeForce GT75M

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by luboslenco** [comment]
Hi, can you check the [system console](https://github.com/armory3d/armory/wiki/setup#windows) and paste the error log?

> To see error messages, press Menu bar - Window - Toggle System Console in Blender.

**Comment by kh000** [comment]
Maybe its not the same issue, however for me every new project fails on:
```
Compiling shader 6 of 8 (painter-video.frag.glsl).
Compiling shader 7 of 8 (painter-text.vert.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "E:\14_grafika\blender\blender-2.80-windows64\2.80\python\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "E:\14_grafika\blender\blender-2.80-windows64\2.80\python\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "F:\gameDev\armory\ArmorySDK//armory/blender\arm\make.py", line 32, in fn
    done()
  File "F:\gameDev\armory\ArmorySDK//armory/blender\arm\make.py", line 384, in compilation_server_done
    os.rename('krom/krom.js.temp', 'krom/krom.js')
FileNotFoundError: [WinError 2] File cannot be found: 'krom/krom.js.temp' -> 'krom/krom.js'
```
it might be related to this change: https://github.com/armory3d/armory/issues/1438

**Comment by karlxuthus** [comment]
![error](https://user-images.githubusercontent.com/24907980/67159654-019ae980-f37a-11e9-8bbb-ed074507ee51.png)

**Comment by BlackGoku36** [comment]
@kh000 Where is your blend file kept, I had similar issue when keeping blend file exposed directly to drive folder.

**Comment by kh000** [comment]
@BlackGoku36 i keep all my project in `F:\gameDev\armory\projects\`, and I have created new one to test in `F:\gameDev\armory\projects\`new_project\`.
I have cleaned up, armory sdk and checked out again. Now its working. Sorry if I took your time to investigate the problem.

**Comment by BlackGoku36** [comment]
@kh000  No problem!
@karlxuthus  Some sockets and nodes aren't supported, see [supported nodes](https://github.com/armory3d/armory/wiki/supported_nodes)

**Comment by luboslenco** [comment]
Please reopen if problem persists with ArmorySDK1911.
