### ISSUE TITLE
iOS (C) HashLink - Xcode errors project won't compile - ArmorySDK1910

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1443]
iOS (C) HashLink projects generation is not working correctly at the moment: 

Opening the generated project on Xcode (current build v11.1),
will tell you there is a Semantic Issue in the actual Kha of Armory in :

ArmorySDK/Kha/Backends/KoreHL/hl/src/hl.h

line 245 : Unknown type name 'char16_t'

looking at this error it seem there is some error in the code somewhere, like some text that should have been commented and that is not. Xcode does not provide much on this error...

It looks like some change need to be done in Kha in order to correctly generate iOS (C) HashLink files.

To reproduce open a simple iOS (C) HashLink generated project with Xcode on a mac :
File provided : https://git.io/Je0rN

**Comment by onelsonic** [comment]
the problem is probably with the following changes not correctly working with Xcode 11.1 for iOS : 
https://github.com/HaxeFoundation/hashlink/pull/218/commits/76f4df7d0ddec3d92b36d42e3a845ab50efcbbd3

the section currently flagged in Xcode is this in Kha : 
see below the Xcode errors :
https://github.com/armory3d/Kha/blob/master/Backends/KoreHL/hl/src/hl.h
line.236 to line.248

```

236. #	include <stdarg.h>
237. #if defined(HL_IOS) || defined(HL_TVOS) || defined(HL_MAC)
238. #include <stddef.h>
239. #include <stdint.h>
240. uint16_t char16_t;             //Cannot combine with previous 'type-name' declaration specifier
241. uint32_t char32_t;             //Cannot combine with previous 'type-name' declaration specifier
242. #else
243. #	include <uchar.h>
244. #endif
245. typedef char16_t uchar;        //Unknown type name 'char16_t'
246. #	undef USTR
247. #	define USTR(str)	u##str
248. #endif

```

**Comment by onelsonic** [comment]
the section currently flagged in Xcode is this in Kha : 
see below the Xcode errors :
https://github.com/armory3d/Kha/blob/master/Backends/KoreHL/hl/src/hl.h
line.236 to line.248

```

236. #	include <stdarg.h>
237. #if defined(HL_IOS) || defined(HL_TVOS) || defined(HL_MAC)
238. #include <stddef.h>
239. #include <stdint.h>
240. uint16_t char16_t;             //Cannot combine with previous 'type-name' declaration specifier
241. uint32_t char32_t;             //Cannot combine with previous 'type-name' declaration specifier
242. #else
243. #	include <uchar.h>
244. #endif
245. typedef char16_t uchar;        //Unknown type name 'char16_t'
246. #	undef USTR
247. #	define USTR(str)	u##str
248. #endif

```

**Comment by onelsonic** [comment]
This should Fix it : 
need to be applied to the Kha version of Armory.
https://github.com/armory3d/Kha/pull/1

**Comment by onelsonic** [comment]
using the fix above the simple-cube scene will compile and run on iOS but a more complex scene will just have a black screen without the 3D layer.
https://github.com/armory3d/Kha/blob/master/Backends/KoreHL/hl/src/hl.h
this file needs to be fully reviewed to work with Xcode 11.1

**Comment by luboslenco** [comment]
Fix pushed at https://github.com/Kode/Kha/pull/1149.
