### ISSUE TITLE
macOS (C) HashLink - compiling ok without Physics - haxebullet 2.87 outdated on mac

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1444]
I tried to compile a project to target macOS using the macOS (C) HashLink.
While a simple project is compiling fine (simple-cube), if you use some physics "Bullet" the project will not compile on macOS.

you will get the following error :

    Argument value ####### is outside the valid range [0, 255]

I appears to be a [bullet issue with the apple clang ](https://github.com/bulletphysics/bullet3/issues/2114)

There is two way to fix it, either move to the updated version 3 of bullet or apply this quick fix :
replace :

    #define BT_SHUFFLE(x,y,z,w) ((w)<<6 | (z)<<4 | (y)<<2 | (x))

with 

    #define BT_SHUFFLE(x, y, z, w) (((w) << 6 | (z) << 4 | (y) << 2 | (x)) & 0xff)

in the haxebullet/bullet/LinearMath/btVector3.h

**Comment by luboslenco** [comment]
It's in, thanks again for the patch!
