### ISSUE TITLE
Import error on start

### ISSUE THREAD

**Issue by IBurntMyToast** [armory3d/armory#1448]
**Description**
When I install Armory it does not show the Armory player and when I looked in the console, it shows this:
![Annotation 2019-10-26 232251](https://user-images.githubusercontent.com/6313678/67629688-a8362d00-f847-11e9-849f-88025e3177b7.png)
![Annotation 2019-10-26 232252](https://user-images.githubusercontent.com/6313678/67629689-aa988700-f847-11e9-895f-36a300950f7a.png)

**To Reproduce**
1) Install Armory
2) Point addon to SDK folder
3) Restart Blender
4) Issue

**Expected behavior**
Console Errors

**System**
Blender: 2.80.75
Armory: 2019.9.0
OS: Windows 10 64bit
Graphics card: Nvidia GeForce GTX 1060 and Intel(R) UHD Graphics 630

**Comment by BlackGoku36** [comment]
I first guess is that you have 32bit blender when you should have 64bit blender

**Comment by IBurntMyToast** [comment]
I have the 64bit version and to make sure I have it, I reinstalled Blender using the 64bit installer

**Comment by BlackGoku36** [comment]
Same errors? than I have no idea

**Comment by luboslenco** [comment]
Hm, maybe a custom python installation or something like that causing trouble?:/

**Comment by IBurntMyToast** [comment]
I have Python 3.7.3. Does Armory need the newest Python version, which is 3.8.0?

**Comment by luboslenco** [comment]
Python 3.7 is ok, installing/getting numpy to work should resolve the issue. Armory is only tested with the bundled Blender python, sorry.
