### ISSUE TITLE
Armory error with any blend

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#145]
i've got this when i use both viewport player and external : D:\Documents Thoom\Project\VisuellementCritique\HS8\Sources/arm/node/NodeTree.hx:11: characters 2-30 : Not enough arguments, expected node:armory.logicnode.Node
---
[PaladinV5rigged_Armory.zip](https://github.com/armory3d/armory/files/824856/PaladinV5rigged_Armory.zip)

**Comment by luboslenco** [comment]
Heyo, the problem is there are old logic nodes in your project. Delete all nodes pictures below and it should work. I will try to handle this automatically in next builds.

![oldnodes](https://cloud.githubusercontent.com/assets/3685704/24086020/89601144-0d07-11e7-95ed-9cb6f2b70f79.jpg)
