### ISSUE TITLE
more flags than bugs

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1453]
Hi there, 
this is a suggestion so we can have a better visibility on current issues in Armory3D.
a proposal will be to use a series of tags when raising issues, other than bugs and feature request. Then it will be good to have a prioritization system maybe with votes.

I looked at other engine, here is what unreal is doing : 
https://issues.unrealengine.com/issue/search?q=&resolution=&component=&sort=

and here is my suggested list for armory, what do you think of it? 

```
2d
3d
animation
armory_bake
assest
audio
bundled
camera
compositor
documentation
examples
exporter
general
haxe
html5
input
iron
kha
krom
lib
lod
modules
networking
nodejs
nodes
physics
physics_bullet
physics_oimo
platform
platform_android_c
platform_console
platform_custom
platform_html5_js
platform_ios_c
platform_linux_c
platform_linux_krom
platform_macos_C
platform_macos_krom
platform_node_js
platform_windows_c
platform_windows_krom
player
player_movement
post_process
project
props
proxy
render_path
render_path_2d-baked
render_path_desktop
render_path_max
render_path_mobile
renderer
renderer_deferred_clustered
renderer_forward_clustered
shadows
traits
ui
Video
voxel_ao
vr
wasm
window
world
```

**Comment by Sandy10000** [comment]
Hi @onelsonic.

Certainly I feel that searchability is not so good. Some of the labels you have proposed already exist.(https://github.com/armory3d/armory/labels) It might be a good idea to start by making effective use of it.

For example, if many of the issues written about physics do not have a physics label, no one will try to search using that label. I think it is important to be able to put labels thoroughly and accurately.

**Comment by luboslenco** [comment]
Will try to put up more labels in the future. For voting please use the 👍 reaction:
https://github.com/armory3d/armory/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

(link: https://github.com/armory3d/armory/projects/4)
