### ISSUE TITLE
azerty left move bug

### ISSUE THREAD

**Issue by Shai-studio** [armory3d/armory#1454]
**Description**
When using an azerty keyboard and wasd type controls, the left button(q) stays active, once pressed one time and released, preventing the character to stop.

**To Reproduce**
Problem visible in all templates and examples needing wasd controls.

**System**
Blender: 2.80 non beta
Armory: 2019.0.10
OS: Ubuntu 18.04
Graphics card: Radeon RX560

**Comment by Sandy10000** [comment]
A problem with Linux (Krom) not being able to detect the Q key release has been reported in #1387.

**Comment by luboslenco** [comment]
Should be resolved in ArmorySDK1911.
