### ISSUE TITLE
OpenSteetMap add-on disables Armory

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#146]
Somehow [blender-osm](https://github.com/vvoovv/blender-osm) is not playing nice with Armory - investigating.

**Comment by HeadClot** [comment]
If you need an extra pair of eyes on this let me know :)

**Comment by luboslenco** [comment]
@HeadClot If you are around then your pair of eyes would come handy. :) Armory should no longer break at startup when blender-osm is installed.

**Comment by razvanc-r** [comment]
I can confirm that blender-osm works fine with Armoury now
