### ISSUE TITLE
unable to install ArmorySDK-2019-11 on Windows - ModuleNotFoundError: No module named 'start'

### ISSUE THREAD

**Issue by chuckgordon** [armory3d/armory#1462]
Thank you for contributing to Armory!

**Description**
Would love to test armory. But installation doesn't work - I don't get a render > Play button.
I discovered that already the installation fails with the following message in the system console:
Read prefs: C:\Users\MYUSERNAME\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: D:\prog\blender280_4Armory\2.80\python
addon_utils.disable: armory not disabled
Modules Installed (armory) from 'd:\\prog\\ArmorySDK\\armory.py' into 'C:\\Users\\MYUSERNAME\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Users\MYUSERNAME\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\armory.py", line 246, in execute
    import start
ModuleNotFoundError: No module named 'start'

location: D:\prog\blender280_4Armory\2.80\scripts\modules\bpy\ops.py:201

. . .

What I noticed - it sounds a bit like: https://github.com/armory3d/armory/issues/151 .
I also had the OSM Plugin (premium version) active.
But I completely removed (not just disabled) it and restarted blender some times and made a copy of my blender directory (which might be useless as it points to the same config files).

**To Reproduce**
Open Blender, go to Edit > Preferences
Install from file
Chose armory SDK directory and pick armory.py .
Then the error message appears in the system console.

**Expected behavior**
Armory should be installed and I should be able to save a .blend file and press F5 to run it.

**System**
Blender: 2.80
Armory: ArmorySDK-2019-11
OS: Windows 10
Graphics card: NVIDIA GTX 1070

**Test File**
*(drag & drop the zipped .blend file here)*
didn't come that far.
Hope you can help.
Thanks!

**Comment by luboslenco** [comment]
Hi, can you give it a shot using the older ArmorySDK-2019-10? Do you get the same error?

(Note: using the older SDK you will have to manually fill in the `SDK Path` property in Armory add-on preferences once `armory.py` gets installed)

**Comment by Remiel-Fallen** [comment]
![Visual Studio](https://user-images.githubusercontent.com/57365021/68179236-1d4ae600-ff5d-11e9-8bb0-61fc5be23b0e.jpg)
Had the same problem Windows defender was stopping it Haxe and Krafix from writing to my program files so I copy Armory to my C drive and also didn't have all the build tools install in Visual Studio. I had no problem installing after I changed both.

**Comment by chuckgordon** [comment]
> Hi, can you give it a shot using the older ArmorySDK-2019-10? Do you get the same error?
> 
> (Note: using the older SDK you will have to manually fill in the `SDK Path` property in Armory add-on preferences once `armory.py` gets installed)

Thanks, I will check later today with ArmorySDK-2019-10.

**Comment by Remiel-Fallen** [comment]
![Blender-Preference](https://user-images.githubusercontent.com/57365021/68231496-2d98aa80-ffc9-11e9-99f4-3be9f395397b.png)
You have to fill in the SDK pack with newer version and click on the advance box and fill in editor paths. Easier to show you!

**Comment by chuckgordon** [comment]
>Hi, can you give it a shot using the older ArmorySDK-2019-10? Do you get the same error?
I tried with the 2019.10 version and filled in the SDK path. Result: It works fine. No errors with 2019-10.
When I switch to 2019-11 version I get the mentioned error: "import start
ModuleNotFoundError: No module named 'start'".

**Comment by Remiel-Fallen** [comment]
What editor are using, can you send a print screen picture of your Armory settings?

**Comment by Remiel-Fallen** [comment]
The best is Visual Studio Code with Haxe and Git extensions from https://marketplace.visualstudio.com/VSCode .  You can also download full packages Git from https://git-scm.com/ and Haxe from https://haxe.org/download/

**Comment by chuckgordon** [comment]
Now, Screenshot attached. 
I tried moving the SDK from D:\... to C:\... even in the identical directory on your screenshot with case sensitivity. It doesn't do the trick. Step 1 is fine - installing from the python script. The moment I tick the checkbox in front of "Render: Armory" to enable it the error occurs in the console. Before I even give any information about any editor. I use VSCode as you can see. With Armory 19.10 everything works fine.
![2019-11-05 21_35_19-Armory_NoModuleNamedStart](https://user-images.githubusercontent.com/57293989/68244162-86416500-0014-11ea-90d8-fa48ce00af71.jpg)

Any idea?

**Comment by Remiel-Fallen** [comment]
I'm wondering why in your Armory SDK Manager it reads "Download and setup SDK" click on it and find out and make sure you click on the box in the lower left and save the new paths. The only other thing I did just incase there was a bug in windows defender was open defender click on virus and threats the ransomeware protection enable it and allow Blender, Haxe and Krafix to have access.

**Comment by Remiel-Fallen** [comment]
![WD1](https://user-images.githubusercontent.com/57365021/68246358-a22e1200-ffe6-11e9-9692-5ab6e73e5c0b.png)
![WD2](https://user-images.githubusercontent.com/57365021/68246366-a5290280-ffe6-11e9-939d-cd0a9da2080e.png)
![WD3](https://user-images.githubusercontent.com/57365021/68246373-a823f300-ffe6-11e9-8f86-cd877345b95e.png)

**Comment by Remiel-Fallen** [comment]
![WD4](https://user-images.githubusercontent.com/57365021/68246525-ed482500-ffe6-11e9-896f-28fe91a627bc.png)
 I was getting errors even though I didn't have it enable it was blocking Blender and Armory from working.

**Comment by Remiel-Fallen** [comment]
Another make sure you check the box "Save on Build" and you can get FFmpeg for your sound here. https://ffmpeg.org/download.html#build-windows

**Comment by Remiel-Fallen** [comment]
![Console1](https://user-images.githubusercontent.com/57365021/68247458-e3bfbc80-ffe8-11e9-8eb2-19d42e4a56ed.png)
![Console2](https://user-images.githubusercontent.com/57365021/68247500-f9cd7d00-ffe8-11e9-82e8-1c10612bd339.png)
![Console3](https://user-images.githubusercontent.com/57365021/68247506-fd610400-ffe8-11e9-9131-528d89b9440b.png)
This is my console output after updating.

**Comment by Remiel-Fallen** [comment]
If I was you I would start from scratch. Don't check the box on the armory plugin just the down arrow and click the remove button. Download the plugin unzip it and copy it to the OS main tree if that's on D: or C: this the drive where windows and everything else is installed. Download full builds of Git and Haxe and install them. If that doesn't work it your windows defender stopping you change your settings like above. Make sure you save preferences in the bottom left and restart after you save.

**Comment by Remiel-Fallen** [comment]
![Cycles-Armory](https://user-images.githubusercontent.com/57365021/68255050-276ef200-fffa-11e9-892e-27ec22242abd.png)
This what you should have when it's install right.

**Comment by indigozero** [comment]
I just had a similar if not same issue. It was because I pressed the 'Update SDK' button and it failed because of my git install. I noticed that if the 'Update SDK' button is pressed it will rename all the folders in the 'SDK path' by appending a '_backup' to each of them. The 'Restore SDK' button will undo it. I ended up needing to first install git through the installer on https://git-scm.com/ (regardless of visual studio's git install), and then restarting blender. I then pressed the 'Update SDK' button while the console was open and it worked on updating which fixed my ability to run Armory.

I installed ArmorySDK-2019-11 originally. I'm currently running what ever version it was updated to.

**Comment by karlxuthus** [comment]
I download ArmorySDK-2019-11 and meet the same problem. I try to fix it. Now my test can work well.

![image](https://user-images.githubusercontent.com/24907980/68460420-d43bb000-0242-11ea-8836-0a288e67b623.png)
This is my fixed Armory3d[https://drive.google.com/file/d/1Inlo-N7pLFtij0eHgK1QLfy42oLXtkGO/view?usp=sharing](url)

**Comment by Remiel-Fallen** [comment]
![Armory-config](https://user-images.githubusercontent.com/57365021/68523574-299ab000-0289-11ea-8cc2-7a24ea43a467.png)
I uninstalled everything and reinstalled Visual Studio Code with no extra extensions and extracted the Armory3D into the same directory that VS Code was installed in C:\Users\remie\AppData\Local\Programs and installed git from https://git-scm.com/ put my directory paths in the Armory addon restarted Blender and everything works.

**Comment by luboslenco** [comment]
Hoping the ideas above worked. If not please feel welcome to reopen.
