### ISSUE TITLE
Runtime errors when applying Generic or Fixed constraint

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1463]
**Description**
When applying rigid body constraint Fixed or Generic in Blender, build fails and displays the following message :
![Capture1](https://user-images.githubusercontent.com/55564981/68091201-0765f400-fe7d-11e9-96ae-22308cd7d131.PNG)

However, no errors when applying all other constraints.

**To Reproduce**
1. Create a new Blend file
2. Add 2 cubes as rigid bodies
3. connect two rigid bodies with an empty as a rigid body constraint and type as fixed
4. Run Armory

**Expected behavior**
During runtime:
![Capture1](https://user-images.githubusercontent.com/55564981/68091209-1d73b480-fe7d-11e9-9427-32b11e2df041.PNG)

**System**
Blender: 2.80
Armory: 2019.11.0
OS: Windows 8.1
Graphics card: Intel HD4000

**Test File**
*(drag & drop the zipped .blend file here)*
[ConstraintError.zip](https://github.com/armory3d/armory/files/3802073/ConstraintError.zip)

**Comment by cmd410** [comment]
I reproduced the bug.

Blender: 2.80
Armory: 2019.11.0
OS: Windows 7
Graphics: AMD R7 240

Noticed that this error doesn't happen in Armory 2019.10.0 and constraint works as expected.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/haxebullet/pull/31.
