### ISSUE TITLE
The wiki page describing the deprecated voxel GI needs to be modified

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1465]
Voxel GI seems to be abolished.(https://github.com/armory3d/armory/commit/52402499823ccdc30df7aff562a568bef9f9580c)

It is written that it is necessary to set the voxel GI to use the material node "Emission"(https://github.com/armory3d/armory/wiki/supported_nodes)

How to set the voxel GI has been written on this page(https://github.com/armory3d/armory/wiki/global_illumination)

These pages need to be modified.

**Comment by Sandy10000** [comment]
http://forums.armory3d.org/t/emission-shader-not-shadeless/3674

**Comment by luboslenco** [comment]
Updated the wiki pages.
