### ISSUE TITLE
Rendering problems under Linux in Build 8

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#147]
Scene 4 is not rendering the background properly. On the first and second builds the scene always got the background wrongly aligned and with problems in the image data. The graphical artifacts were different on each execution.

After closing and cleaning the build several times, finally the background appeared correctly. Besides this, even loading the background correctly, the shading of the spheres was not taking into account the environment (no reflections).

This problem is also present in scenes like the maze ball game. Although the background always seemed right in this scene, the ball never reflected the environment.

I tried to replicate these problems under macOS and everything seems ok. So these rendering problems seems related with the linux version only (or a problem in my system).

I attach screenshots of the different tests. Note: Some of the images have a window with alpha from the tool I used to take the screenshots. It seems the screenshot was taken before completely vanishing the window. As soon as I noticed this I gave some time to take the screenshot... so not all the images are compromised. Don't pay attention to the rectangular dialog with alpha... sorry :-)

Background problems (two different executions, I rotated the view to point the problems better)
![scene4_1](https://cloud.githubusercontent.com/assets/1221735/23717824/a8d54e52-0435-11e7-888f-602a687f6c9e.png)
![scene4_2](https://cloud.githubusercontent.com/assets/1221735/23717853/bded0456-0435-11e7-9aa8-6d8242c27b4d.png)

Background is right this time, but the shading on the spheres is still wrong
![scene4_3](https://cloud.githubusercontent.com/assets/1221735/23717898/e76cb376-0435-11e7-8e42-3000ba83fc70.png)

Shading problem also appearing on the maze ball
![mazeball](https://cloud.githubusercontent.com/assets/1221735/23718234/fa67eb0c-0436-11e7-9001-60c67fcccd17.png)

Rendering results in Armory Build 7 for linux. Background and shading ok, but with different color saturation that Armory Build 8 under macOS (Maybe this is right and it's a real difference between Build 7 and 8)
Scene 4 build 7 under Linux
![scene4_build7](https://cloud.githubusercontent.com/assets/1221735/23717987/3fb7b6ca-0436-11e7-9b3c-aab5539b8a53.png)
Scene 4 build 8 under macOS
![armoryscene4_mac](https://cloud.githubusercontent.com/assets/1221735/23718013/53b9e1e8-0436-11e7-846d-1ea26e03ee31.png)

System: Linux
Solus 2017.01.01.0 64-bit
GeForce GTX 1060 6GB/PCIe/SSE2

**Comment by luboslenco** [comment]
This is gold, thanks! Hm, maybe I screwed up some Linux binaries, either [kraffiti](https://github.com/Kode/kraffiti) for image manipulation or [cmft](https://github.com/dariomanesku/cmft) for environment map processing. Will dig further and report back.

**Comment by luboslenco** [comment]
Fixed some renderer errors and spheres should now reflect the environment map properly. Please let me know if you get to test it again.

**Comment by arturjpv** [comment]
Working in Build 9!

**Comment by arturjpv** [comment]
Close Issue
