### ISSUE TITLE
armorySDK1910 status

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1472]
armorySDK1910 status

| Targets       | 3D            | Physics       | Gamepad       | mouse/touch   | sound         | Network       | Comments                                  |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | -------------                             |
| android-hl    | operational   | issues        | issues        | operational   | 44100khz      | ?             | android-hl: Physics and Gamepad issues    |
| ios-hl        | issues		| -		        | -             | -             | ?             | -             | ios-hl: no 3D render Metal API issues     |
| windows-hl	| operational   | operational   | operational  	| operational   | 48000khz      | ?             | windows-hl: 48000khz audio needed         |
| macos-hl  	| issues        | -             | ?             | issues        | 48000khz      | ?             | macos-hl: no 3D render Metal API issues   |
| linux-hl  	| -             | -             | -             | ?             | -             | -             | linux-hl: not compiling (on ubuntu)       |
| krom-windows  | operational   | ?             | ?             | operational   | 48000khz      | ?             | krom-windows: 48000khz audio needed       |
| krom-macos    | operational   | ?             | ?             | ?             | 48000khz      | ?             | krom-macos: 48000khz audio needed         |
| krom-linux-hl | operational   | operational   | operational   | operational   | ?             | ?             |                                           |
| html5		    | operational   | operational   | operational   | operational   | operational   | ?             |                                           |
| node (js)     | ?             | ?             | ?             | ?             | ?             | ?             |                                           |

**Comment by softyoda** [comment]
This issue is closed, do you know if this was implemented, if yes, where ?

I'm trying to found what work and what don't work, and sound don't seem's to work with Krom.
