### ISSUE TITLE
armory3D status tracker SDK1910

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1473]
<img width="299" alt="2019-11-18 15_26_52-armory-status xlsx - Excel" src="https://user-images.githubusercontent.com/53947594/69060853-6482ad80-0a18-11ea-82a9-91c036f7d9bc.png">

https://github.com/onelsonic/armory_tests/raw/master/armory-status.xlsx

Targets |  Build Status
-- | --
android-hl | ![passing](https://user-images.githubusercontent.com/53947594/68614838-09a20100-04c2-11ea-8db4-26e0bb77cb98.png)
ios-hl |  ![failing](https://user-images.githubusercontent.com/53947594/68614954-584f9b00-04c2-11ea-8841-d8fa05345a56.png)
windows-hl | ![passing](https://user-images.githubusercontent.com/53947594/68614838-09a20100-04c2-11ea-8db4-26e0bb77cb98.png)
macos-hl |  ![failing](https://user-images.githubusercontent.com/53947594/68614954-584f9b00-04c2-11ea-8841-d8fa05345a56.png)
linux-hl | ![failing](https://user-images.githubusercontent.com/53947594/68614954-584f9b00-04c2-11ea-8841-d8fa05345a56.png)
html5 | ![passing](https://user-images.githubusercontent.com/53947594/68614838-09a20100-04c2-11ea-8db4-26e0bb77cb98.png)
node (js) | ?
krom-windows | ![passing](https://user-images.githubusercontent.com/53947594/68614838-09a20100-04c2-11ea-8db4-26e0bb77cb98.png)
krom-macos | ![passing](https://user-images.githubusercontent.com/53947594/68614838-09a20100-04c2-11ea-8db4-26e0bb77cb98.png)
krom-linux-hl | ![passing](https://user-images.githubusercontent.com/53947594/68614838-09a20100-04c2-11ea-8db4-26e0bb77cb98.png)

**Comment by luboslenco** [comment]
Please move to a new wiki page if possible, as it will get buried on the tracker. 🙁
