### ISSUE TITLE
Android : bullet / Haxebullet Physics incorrect collisions

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1477]
Hi there, 
the physics engine bullet on Android is returning some strange behavior.
A rigid body will pass through another rigid body or through a passive body,
and the collisions and sometime working, sometime not.

It seems that the shells used to calculate the collisions are not correctly aligned with the meshes or have not the same transformations applied to them.

So I am wondering if the bullet source can be directly compiled for android and then used in armory since the current version if not working correctly?

I saw some projects that build it for Android : 
https://github.com/jrgleason/bullet4droid
https://stackoverflow.com/questions/50060426/building-bullet-physics-library-with-android-ndk
https://software.intel.com/en-us/android/articles/porting-the-android-bullet-physics-engine-to-intel-architecture

but then I am not sure if we can use the compiled library into Armory and control it with Haxe.

**Comment by Sanva** [comment]
I think this could be the same as #1756 .

**Comment by onelsonic** [comment]
Issue comes from the Kha C backend : 
Fix has been found by @Sanva 
This should be changed in Kha :
https://github.com/Kode/Kha/commit/39e022b2bf921aedfb651954af6ead4a38d09ce4

**Comment by Sanva** [comment]
@luboslenco I think this can be closed.
