### ISSUE TITLE
Debug Console not working

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1479]
Armory v2019.11 ($Id: 7a844e70beff1825dbedb3e34dcb14326c165c90 $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.81 (sub 15)

Trying to use "Debug Console" will result in the following error message:
[...]ArmorySDK\armory\Sources/armory/trait/internal/DebugConsole.hx:158: characters 54-55 : Int should be Bool

Sample file attached.
[DebugConsole.zip](https://github.com/armory3d/armory/files/3838243/DebugConsole.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/405da0e10e9d1aeba303fd432e95b963fc9ba42b, thanks.
