### ISSUE TITLE
Web Assembly (WASM)

### ISSUE THREAD

**Issue by HeadClot** [armory3d/armory#148]
It would be great to get support for Web Assembly (WASM).

Details [here](http://webassembly.org/) and [here](https://medium.com/mozilla-tech/why-webassembly-is-a-game-changer-for-the-web-and-a-source-of-pride-for-mozilla-and-firefox-dda80e4c43cb#.sgpamhex4)

---
optional - drag & drop .blend file here

**Comment by zauberparacelsus** [comment]
Since Armory depends on Haxe to target multiple platforms, Haxe will need to add a WASM target first.

**Comment by HeadClot** [comment]
@zauberparacelsus Ah good point.

**Comment by luboslenco** [comment]
There is a way to support it through [Kore](https://github.com/Kode/Kore). Would need some work but It already has an [emscripten backend](https://github.com/Kode/Kore/tree/master/Backends/HTML5/Sources/Kore).

**Comment by luboslenco** [comment]
Krom / Armory player is now capable of running WASM, will take further advantage of that as the time goes. :)
https://github.com/luboslenco/krom_wasmtest
