### ISSUE TITLE
Volumetric light shader issue when multiple lights are present

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1480]
**Description**
If a volumetric light is set in an environment with multiple lights, an error occurs and compilation fails. The error contents change depending on the combination of lights.

Report to Armory Forum by Daniel Sobrinho(http://forums.armory3d.org/t/problems-with-volumetric-lights-using-lamps-was-not-sun/3689)

1.  A combination of one "Sun" and one "Spot"(#define _Sun,_Spot._SinglePoint)
ERROR: volumetric_light.frag.glsl:104: 'lPos' : redefinition
1.  Combination of "Sun" and "Point" or "Area"(#define _Sun,_SinglePoint)
ERROR: volumetric_light.frag.glsl:112: 'visibility' : redefinition
1.  Combination of two "Spot" or two "Point"(#define _Clusters)
ERROR:volumetric_light.frag.glsl:119: 'visibility' : undeclared identifier

| combination | #define | line | message |  
---- | ---- | ---- | ----   
| One "Sun" and one "Spot" | _Sun,_Spot._SinglePoint | 104 | 'lPos' : redefinition |  
| "Sun" and "Point" or "Area" | _Sun,_SinglePoint | 112 | 'visibility' : redefinition |
| Two "Spot" or two "Point" | _Clusters| 119 | 'visibility' : undeclared identifier |

**System**
Blender:2.8
Armory:git

**Test File**
http://forums.armory3d.org/uploads/short-url/11Uvk4PBtITImTFV6uFAWl1e8dY.blend

**Comment by MoritzBrueckner** [comment]
This has been fixed by https://github.com/armory3d/armory/pull/2445 and https://github.com/armory3d/armory/pull/1945.
