### ISSUE TITLE
NodeJS : not compiling and returns errors related to kha.SystemImpl.gl2

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1482]
Hi there, 
compiling to NodeJS is not working and returns the following errors :

> _armorySDK\armory\Sources/armory/system/Starter.hx:68: characters 10-28 : Class<kha.SystemImpl> has no field gl2_

this is the section of the file Starter.hx:68 calling gl2 :
should this section below be simply deleted only for NodeJS ?

```
#if (kha_webgl && (!arm_legacy))
}
catch (e:Dynamic) {
	if (!kha.SystemImpl.gl2) {
		trace("This project was not compiled with legacy shaders flag - please use WebGL 2 capable browser.");
	}
}
#end
```

**Comment by luboslenco** [comment]
> should this section below be simply deleted only for NodeJS ? 

Yes, pushed a fix at https://github.com/armory3d/armory/commit/51ab281a21b642e416100ffd5707bcc4d9b1809b. However the [node backend](https://github.com/Kode/Kha/tree/master/Backends/Node/kha) appears to be out-dated in Kha, so there are additional errors.
