### ISSUE TITLE
SSS metalic Bug

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armory#1486]
Thank you for contributing to Armory!

**Description**
When I use sss and enable it in the render path the material becomes metallic.
Issue description.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Please Restore the SSS in 19.7
What you expected to happen.

**System**
Blender: 2.81
Armory: 19.11
OS: MS Win 10
Graphics card: !ntel HD 4400

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by melMass** [comment]
You know the template text is supposed to be removed ?

**Comment by knowledgenude** [comment]
Decrease the Metallic or Roughness in material settings
