### ISSUE TITLE
Extra Editors for Armory as plugins

### ISSUE THREAD

**Issue by HeadClot** [armory3d/armory#149]
Ok, so I kinda covered this in issue #108 but I think it is worth making this a standalone request.

Why not spin feature requests such as #9 and #108 for example off as a separate plugins that can interact with Armory? Thus leaving the Armory Engine Core to be fast and nimble. I know that Unreal Engine 4 is doing the same thing with allot of its modules stuff like PhysX, Paper2D, etc.

**Comment by luboslenco** [comment]
Will continue to place highest priority on this!
