### ISSUE TITLE
SDK auto-detect fails in Blender 2.81

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#1490]
**Description**
SDK auto-detect fails in Blender 2.81, looks like the `bpy.ops.ui.reports_to_textblock` operator got removed.
`AttributeError: Calling operator "bpy.ops.ui.reports_to_textblock" error, could not be found`

**To Reproduce**
Install and enable armory.py in Blender 2.81.

**System**
Blender: 2.81
Armory: 2019.11
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
Oh, that's very unfortunate :(

At first I thought they might only have renamed the operator, but it seems it was replaced by another operator who doesn't really help here.

Sources:
- https://developer.blender.org/D5510
- https://github.com/sobotka/blender/commit/04f9c795aae6a70693fbf5eac880cffe26036cf3#diff-23d6cd2b2159b9a908c99a86e21b44b2

"Replacement": https://docs.blender.org/api/2.81/bpy.ops.screen.html#bpy.ops.screen.info_log_show

Maybe there is a way to contact the Blender devs and ask them if they can bring it back in 2.82, but I don't now if there is any change of success.

**Comment by luboslenco** [comment]
Pushed a fix attempt at https://github.com/armory3d/armsdk/commit/e09ef70aa2d021e9575af792b0b5380fab44f277. Only tested on Windows so far.

For other changes - let's bump the required Blender version to 2.81 for Armory 2019.12, to keep maintenance easier.. https://github.com/armory3d/armsdk/commit/9788758bce1384ed8afbeec6891f2aaa5818c8a3

**Comment by N8n5h** [comment]
The auto-detect works in Linux too.

**Comment by daniel-heywood** [comment]
Using version 12, on MacOS, 10.14.6. Auto-detect not working. 

– My first Armory install, looking forward to playing with it!

**Comment by N8n5h** [comment]
@daniel-heywood 
>Does the SDK need to be in a specific location to be auto-detected?

The "auto-detect SDK" picks the directory where the armory.py was installed from, to follow the structure of the downloadable SDK package (armory.py + SDK folders alongside).

**Comment by daniel-heywood** [comment]
> @daniel-heywood
> 
> > Does the SDK need to be in a specific location to be auto-detected?
> 
> The "auto-detect SDK" picks the directory where the armory.py was installed from, to follow the structure of the downloadable SDK package (armory.py + SDK folders alongside).

That was it. Thanks! I had moved the SDK after installing it. After reinstalling, auto-detect worked correctly on macOS. 

To help ignorants like me, adding that detail to the setup instructions may help: https://github.com/armory3d/armory/wiki/setup

**Comment by N8n5h** [comment]
@daniel-heywood I updated the wiki page to include what to do in case the auto detect SDK didn't work based on what you wrote in https://github.com/armory3d/armory/issues/1502 :+1:

**Comment by luboslenco** [comment]
Thanks for the wiki update! Hopefully the auto-detect feature survives the upcoming b2.82 as well. 😈
