### ISSUE TITLE
Doc bug: How do you parent Shape to Combo, Radio, Slider in UI_Canvas?

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#1493]
I tried all mouse buttons, with CTRL, SHIFT, ALT but I don't get any parenting like you have in the example:
![image](https://user-images.githubusercontent.com/65325/69725727-20319480-111f-11ea-8d33-0b94613431b9.png)
I see in https://github.com/armory3d/armory_examples/blob/master/ui_canvas/Bundled/canvas/MyCanvas.json
```
"text": "My Shape",
			"asset": "",
			"color": 16777215,
			"anchor": 0,
			"parent": null,
			"children": [7, 8, 10],
```
How did you achieve it in the UI?
Thanks!

**Comment by Sandy10000** [comment]
I had the same question before in the Armory forum.(http://forums.armory3d.org/t/how-do-i-create-a-hierarchical-structure-with-the-canvas-editor-outliner/3505)

**Comment by j2l** [comment]
Oh, thank you Sandy! 
I forgot about the forum, I'll clear this ticket
