### ISSUE TITLE
Vertex Animation

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armory#1495]
Pls it seems Armory3d does not support vertex animation.
Pls try and implement it.

**Comment by MoritzBrueckner** [comment]
Possible duplicate of https://github.com/armory3d/armory/issues/225. @divineniiquaye what exactly do you mean with vertex animation? Something like shape keys in Blender?

**Comment by MoritzBrueckner** [comment]
Closing this as shape keys are now implemented in https://github.com/armory3d/armory/pull/2375.
