### ISSUE TITLE
HTML5 : WEBGPU support for Apple devices via Babylon.JS ? 

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1499]
Hi there,
webGPU is now on testing phase with Babylon.js, it will be great to have Armory support webGPU for its HTML5 target.

Best is to target Babylon.js so Babylon.js will make it compatible with WEBGPU in the long term.

Here is the current status of WebPGU with Babylon.js :
https://doc.babylonjs.com/extensions/webgpu

![webgpu](https://user-images.githubusercontent.com/53947594/69982842-aaba2f80-1535-11ea-91fb-440eea0c9375.png)

and here is the Webkit status : 
https://webkit.org/blog/9528/webgpu-and-wsl-in-safari/

**Comment by luboslenco** [comment]
We will add a webgpu backend to Kha, but waiting for broader support at https://github.com/gpuweb/gpuweb/wiki/Implementation-Status. 🙂 Hopefully more webgpu in browsers soon.
