### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by Xananax** [armory3d/armory#15]
Though I wouldn't have the time (and probably not the knowledge) necessary contribute in code, I'd be willing to lend a hand in other ways; I have have several Linode VPSes that I can use to host whatever you want, and I do web (server and front end both, node/PHP/Python/etc). I also do 3D modeling and 2D animation/illustration. If I can help any manner, please tell me so.

I was thinking I could maybe set up forums or some sort of feedback mechanism, since it doesn't seem you have any, yet. It's not a huge contribution, but I don't really see what else I could do. Open to ideas though!

**Comment by mateosss** [comment]
Discourse would be a nice option. It's used in many sites, plus blender artists, is [migrating to it](https://blenderartists.org/forum/showthread.php?385070-Blender-Artists-is-moving-to-Discourse).
https://www.discourse.org/

**Comment by luboslenco** [comment]
Just wow! I wouldn't mind help with the forums/answers site at all. Discourse seems to be the standard these days - would that thing be difficult to set up?

**Comment by Xananax** [comment]
Not at all. Any specific requirements/skin preferences/etc?

**Comment by Xananax** [comment]
Also, maybe deciding on a url so I can set my nginx and pass you the ip (I propose talk.armory3d.com, or something similar)

**Comment by HeadClot** [comment]
Let us know when the forums go up :)

**Comment by luboslenco** [comment]
Closing, forums work perfectly thanks to @Xananax.
http://forums.armory3d.org
