### ISSUE TITLE
armory missing

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#150]
---for some reason i cant find armory when i open blender only the name can be found
![16](https://cloud.githubusercontent.com/assets/23359603/23825063/7a394ab4-068b-11e7-8ff1-1c1f2d3c798f.png)
![17](https://cloud.githubusercontent.com/assets/23359603/23825064/7b96b07c-068b-11e7-8fbf-756879792189.png)

optional - drag & drop .blend file here

**Comment by luboslenco** [comment]
It seems to be conflicting with 'props' add-on. Fixed in upcoming build - I moved armory python classes into separate package to prevent this.

**Comment by luboslenco** [comment]
Aaand fixed.
