### ISSUE TITLE
The output of logic node "Look At" has the x axis rotated 90 degrees

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1500]
**Description**
![1](https://user-images.githubusercontent.com/48373918/70061053-f8fb2b80-1626-11ea-880a-9292217e9f6e.jpg)  

Red Suzanne's node:
![red](https://user-images.githubusercontent.com/48373918/70061430-98202300-1627-11ea-89e3-77dbf67298bd.jpg)

Blue Suzanne's node:
![blue](https://user-images.githubusercontent.com/48373918/70061556-d1f12980-1627-11ea-8941-1678cab9279c.jpg)

**System**
Blender:2.81
Armory:2019.12

**Test File**
[LookAt.blend.zip](https://github.com/armory3d/armory/files/3917234/LookAt.blend.zip)

**Comment by BTCallahan** [comment]
I think it's more of a missing feature then a bug. The lookAT node works - but in a very limited way, as it is only able to make the +Z axis look at the object.

**Comment by Sandy10000** [comment]
I fully agree with your opinion. I realized that I could add this feature myself. Thank you.

I don't know how to change the label, so please change the label if necessary.
