### ISSUE TITLE
Black screen when atempting to play .blend file

### ISSUE THREAD

**Issue by BTCallahan** [armory3d/armory#1501]
When I click the play button under the Armory Player tab, I get a black screen (except for the title bar). I can still switch applications without any trouble, so it's just a simple matter to click the stop button, but the file is unplayable. It was working previously, but I'm not sure why it stopped.

Here's the error message from the console:

Trace: Error: Cannot cast {
	bezierFrameIndex : -1, 
	s0 : 0, 
	object : {
		force_context : null, 
		skip_context : null, 
		tilesheet : null, 
		frustumCulling : true, 
		screenSize : 0, 
		particleIndex : -1, 
		particleOwner : null, 
		particleChildren : null, 
		particleSystems : null, 
		materialIndex : 0, 
		data : {
			scaleTex : 1, 
			scalePos : 6.235245704650879, 
			refcount : 1, 
			count : -1, 
			start : 0, 
			raw : {
				name : Cylinder, 
				scale_pos : 6.235245704650879, 
				index_arrays : [<...>], 
				vertex_arrays : [<...>,<...>], 
				skin : {
					transform : <...>, 
					bone_ref_array : <...>, 
					bone_len_array : <...>, 
					transformsI : <...>, 
					bone_count_array : <...>, 
					bone_index_array : <...>, 
					bone_weight_array : <...>
				}
			}, 
			name : Cylinder, 
			isSkinned : true, 
			geom : {
				mats : {
					h : <...>
				}, 
				actions : {
					h : <...>
				}, 
				skeletonBoneLens : 1,1, 
				skeletonBoneRefs : [<...>,<...>], 
				skeletonTransformsI : [<...>,<...>], 
				skinBoneWeights : 269,32497,32767,32767,298,32468,298,32468,32767,32767,280,32486,280,32486,32767,32767,298,32468,298,32468,32767,32767,269,32497,269,32497,32767,32767,298,32468,298,32468,32767,32767,280,32486,32767,32767,32767,32767,32767,32767,32767,32767,280,32486,32767,32767,298,32468,298,32468,32767,32767,269,32497,32767,32767,32767,32767,32767,32767,32767,32767,32767,32486,280,32468,298,32767,32486,280,30361,2405,30359,2407,32468,298,30361,2405,26505,6261,26505,6261,30359,2407,26505,6261,16383,16383,16383,16383,26505,6261,16383,16383,6261,26505,6260,26506,16383,16383,6261,26505,2407,30359,2404,30362,6260,26506,2407,30359,298,32468,269,32497,2404,30362,32767,32468,298,32486,280,32767,32468,298,30359,2407,30361,2405,32486,280,30359,2407,26505,6261,26505,6261,30361,2405,26505,6261,16383,16383,16383,16383,26505,6261,16383,16383,6261,26505,6261,26505,16383,16383,6261,26505,2405,30361,2407,30359,6261,26505,2405,30361,280,32486,298,32468,2407,30359,32767,32497,269,32468,298,32767,32497,269,30362,2404,30359,2407,32468,298,30362,2404,26506,6260,26505,6261,30359,2407,26506,6260,16383,16383,16383,16383,26505,6261,16383,16383,6261,26505,6261,26505,16383,16383,6261,26505,2407,30359,2405,30361,6261,26505,2407,30359,298,32468,280,32486,2405,30361,32767,32468,298,32497,269,32767,32468,298,30359,2407,30362,2404,32497,269,30359,2407,26505,6261,26506,6260,30362,2404,26505,6261,16383,16383,16383,16383,26506,6260,16383,16383,6260,26506,6261,26505,16383,16383,6260,26506,2404,30362,2407,30359,6261,26505,2404,30362,269,32497,298,32468,2407,30359,32767,32486,280,32468,298,32767,32486,280,30361,2405,30359,2407,32468,298,30361,2405,26505,6261,26505,6261,30359,2407,26505,6261,16383,16383,16383,16383,26505,6261,16383,16383,6261,26505,6260,26506,16383,16383,6261,26505,2407,30359,2404,30362,6260,26506,2407,30359,298,32468,269,32497,2404,30362,32767,32468,298,32486,280,32767,32468,298,30359,2407,30361,2405,32486,280,30359,2407,26505,6261,26505,6261,30361,2405,26505,6261,16383,16383,16383,16383,26505,6261,16383,16383,6261,26505,6261,26505,16383,16383,6261,26505,2405,30361,2407,30359,6261,26505,2405,30361,280,32486,298,32468,2407,30359,32767,32497,269,32468,298,32767,32497,269,30362,2404,30359,2407,32468,298,30362,2404,26506,6260,26505,6261,30359,2407,26506,6260,16383,16383,16383,16383,26505,6261,16383,16383,6261,26505,6261,26505,16383,16383,6261,26505,2407,30359,2405,30361,6261,26505,2407,30359,298,32468,280,32486,2405,30361,32767,32468,298,32497,269,32767,32468,298,30359,2407,30362,2404,32497,269,30359,2407,26505,6261,26506,6260,30362,2404,26505,6261,16383,16383,16383,16383,26506,6260,16383,16383,6260,26506,6261,26505,16383,16383,6260,26506,2404,30362,2407,30359,6261,26505,2404,30362,269,32497,298,32468,2407,30359, 
				skinBoneIndices : 0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,1,0,1,1,1,0,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0

**To Reproduce**
Open the file and click the run button

**Expected behavior**
That the file would be run.

**System**
Blender: 2.80
Armory: 2019.11.0
OS: Fedora 30
Graphics card: GeForce GTX 1650/PCIe/SSE2

**Test File**
[test.zip](https://github.com/armory3d/armory/files/3923242/test.zip)

**Comment by N8n5h** [comment]
I tried your test file but I'm not sure what is going on in the scene... What are you trying to do exactly?

**Comment by BTCallahan** [comment]
When the scene is first initialised the Armature object is supposed to start playing the animation named ArmatureWave. Then during play, when the W key is pressed down, the armature is supposed to begin playing the ArmatureWobble animation. Releasing the W key tells it to play the ArmatureWave again.

The W, S keys affect forwards and backwards movement, and the A and S keys changes the rotation. Prior to the black screen glitch, the movement keys were working normally, it was the animation that I was having trouble with.

**Comment by BTCallahan** [comment]
> I tried your test file but I'm not sure what is going on in the scene... What are you trying to do exactly?

When the scene is first initialised the Armature object is supposed to start playing the animation named ArmatureWave. Then during play, when the W key is pressed down, the armature is supposed to begin playing the ArmatureWobble animation. Releasing the W key tells it to play the ArmatureWave again.

The W, S keys affect forwards and backwards movement, and the A and S keys changes the rotation. Prior to the black screen glitch, the movement keys were working normally, it was the animation that I was having trouble with.

**Comment by N8n5h** [comment]
Maybe you can check the animation examples in https://github.com/armory3d/armory_examples to have an idea how it should be done. Also maybe you can post the steps to reproduce the issue, so it's easier to detect what is the problem in the workflow.

**Comment by BTCallahan** [comment]
> Maybe you can check the animation examples in https://github.com/armory3d/armory_examples to have an idea how it should work. Also posting steps to reproduce the issue would make it's easier to detect what is the problem in the workflow.

I've already looked over them, and I couldn't find anything. It's a moot case, as the problem turned out to be located in the NLA editor. Apparently, there was a zero length animation that wasn't showing up in the Actions editor. Even though I had removed all actions from all objects in the Dope Sheet editor, this one remained. Oh, well, case closed.
