### ISSUE TITLE
Error when running the project

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1506]
No idea why https://github.com/armory3d/armory/issues/1424 is closed as the problem still persists.

On windows 10 64x download armory 06, update SDK from settings, restart blender, save project (change nothing) and press Play with Krom. It gives the fallowing errors. (manual SDK update - same problem)

```
Armory v2019.12 ($Id: 94dc8b99633e01e2432e7b7818ba7c0fe7a461a9 $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.80 (sub 44)
Traceback (most recent call last):
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\props_ui.py", line 457, in execute
    make.play()
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make.py", line 472, in play
    build(target=runtime_to_target(), is_play=True)
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make.py", line 356, in build
    export_data(fp, sdk_path)
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make.py", line 95, in export_data
    make_renderpath.build()
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\make_renderpath.py", line 170, in build
    if len(bpy.data.cameras) > 0 and bpy.data.cameras[0].dof.use_dof:
AttributeError: 'Camera' object has no attribute 'dof'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\handlers.py", line 18, in on_depsgraph_update_post
    depsgraph = bpy.context.evaluated_depsgraph_get()
AttributeError: 'Context' object has no attribute 'evaluated_depsgraph_get'
```

Reopening, restarting etc doesn't help

**Edit:**

**Without an SDK update** (plain download and extract), when running Krom, it just opens white screen and immediately closes. In browser it works. No errors in console.

**Edit 2:**

I took latest Blender 2.81, downloaded latest ArmorySDK1912.zip. Installed it as addon. Restarted blender. The errors are gone, but still Krom window opens and closes right away. I don't see something suspicious in console > https://pastebin.com/7iweyaSr.

**Edit 3**

I took latest Krom binaries and replaced with ones Bundled in SDK and it's working. So this might be a solution.

**Comment by trsh** [comment]
Log when opening Armory

```
Read prefs: C:\Users\trsh\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
AL lib: (EE) ALCmmdevPlayback_open: Device init failed: 0x80070490
found bundled python: C:\Projects\Software\Armory\2.80\python
Traceback (most recent call last):
  File "C:\Projects\Software\Armory\2.80\scripts\modules\addon_utils.py", line 377, in enable
    raise Exception(f"Add-on '{module_name:s}' has not been upgraded to 2.8, ignoring")
Exception: Add-on 'io_export_multiple_objs' has not been upgraded to 2.8, ignoring
Traceback (most recent call last):
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\handlers.py", line 18, in on_depsgraph_update_post
    depsgraph = bpy.context.evaluated_depsgraph_get()
AttributeError: 'Context' object has no attribute 'evaluated_depsgraph_get'
Armory: Proxy objects synchronized
Traceback (most recent call last):
  File "C:/Projects/Software/Armory/armsdk//armory/blender\arm\handlers.py", line 18, in on_depsgraph_update_post
    depsgraph = bpy.context.evaluated_depsgraph_get()
AttributeError: 'Context' object has no attribute 'evaluated_depsgraph_get'
Read blend: C:\Projects\Armory Projects\fp_test\test.blend
```

**Comment by N8n5h** [comment]
Try updating the SDK from Blender 2.81 this time around to see if having the latest version of the SDK solves the issue.

**Comment by trsh** [comment]
@N8n5h I have the latest SDK. Doesn't help

**Comment by N8n5h** [comment]
I noticed Armory and your project are in the drive C, assuming that C is your system drive (where Windows is installed), can you try moving the project file to another drive and then trying to run the project again? and then moving Armory SDK too and try again?

Reason is, it seems that saving stuff in the main drive may cause issues with armory, according to this doc: https://github.com/armory3d/armory/wiki/setup#windows

**Comment by trsh** [comment]
@N8n5h read original under **Edit 3**

**Comment by trsh** [comment]
I think with latest Krom binaries, we can forget this, tho Armory manual should recommend Blender 2.81 with latest SDK, as with 2.80 ain't working. I hope somebody else has not to walk this long path as I did, to get that.
