### ISSUE TITLE
Script "crashes" when calling a method to play an animation

### ISSUE THREAD

**Issue by BTCallahan** [armory3d/armory#1509]
**Description**
I have an object with a rigid body component with two scripts, one that handles controls, and another that handles movement. The object that has the rigid body has a child armature object that has a script to handle animations. The way it works is that the the control script takes input from the keyboard and will call the appropriate methods in the movement and animation scripts. After disabling first the motion script, then both the animation and motion scripts, I was able to isolate the problem in the animation script.

The problem itself is that when I press a key that call a method to play an animation, all scripts stop responding to input. The player no longer is able to move. 

I have updated the SDK and restarted blender, to no avail. 

Here is the output from the console:

`Using project from /home/username/Documents/Blender/armory testing
Using Kha (204c3023) from /home/username/ArmorySDK/Kha
Creating Kha project.
Exporting asset 1 of 1 (ammo.wasm.js).
Exporting asset 1 of 1 (ammo.wasm.wasm).
Exporting asset 1 of 11 (Scene.arm).
Exporting asset 2 of 11 (World_irradiance.arm).
Exporting asset 3 of 11 (action_Armature_Idle.arm).
Exporting asset 4 of 11 (mesh_Cube.001.arm).
Exporting asset 5 of 11 (mesh_Cube.002.arm).
Exporting asset 6 of 11 (mesh_Cube.003.arm).
Exporting asset 7 of 11 (mesh_Cube.004.arm).
Exporting asset 8 of 11 (mesh_Cube.005.arm).
Exporting asset 9 of 11 (mesh_Cube.arm).
Exporting asset 10 of 11 (mesh_Cylinder.arm).
Exporting asset 11 of 11 (mesh_Plane.arm).
Exporting asset 1 of 4 (Material_data.arm).
Exporting asset 2 of 4 (armdefault_data.arm).
Exporting asset 3 of 4 (armdefaultskin_data.arm).
Exporting asset 4 of 4 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Compiling shader 1 of 23 (Material_mesh.frag.glsl).
Compiling shader 2 of 23 (armdefault_mesh.frag.glsl).
Compiling shader 3 of 23 (armdefault_mesh.vert.glsl).
Compiling shader 4 of 23 (armdefault_shadowmap.frag.glsl).
Compiling shader 5 of 23 (armdefault_shadowmap.vert.glsl).
Compiling shader 6 of 23 (armdefaultskin_mesh.frag.glsl).
Compiling shader 7 of 23 (armdefaultskin_mesh.vert.glsl).
Compiling shader 8 of 23 (armdefaultskin_shadowmap.vert.glsl).
Compiling shader 9 of 23 (blur_edge_pass.frag.glsl).
Compiling shader 10 of 23 (compositor_pass.frag.glsl).
Compiling shader 11 of 23 (compositor_pass.vert.glsl).
Compiling shader 12 of 23 (deferred_light.frag.glsl).
Compiling shader 13 of 23 (pass.vert.glsl).
Compiling shader 14 of 23 (pass_viewray.vert.glsl).
Compiling shader 15 of 23 (smaa_blend_weight.frag.glsl).
Compiling shader 16 of 23 (smaa_blend_weight.vert.glsl).
Compiling shader 17 of 23 (smaa_edge_detect.frag.glsl).
Compiling shader 18 of 23 (smaa_edge_detect.vert.glsl).
Compiling shader 19 of 23 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 20 of 23 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 21 of 23 (ssao_pass.frag.glsl).
Compiling shader 22 of 23 (world_pass.frag.glsl).
Compiling shader 23 of 23 (world_pass.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 2.2899885177612305
arm.AnimationObj:24: {
	onUpdates : null, 
	constraintMats : null, 
	constraintTargetsI : null, 
	constraintTargets : null, 
	boneChildren : null, 
	matsFastBlendSort : [], 
	matsFastBlend : [], 
	matsFastSort : [0,1], 
	matsFast : [[[1, 0, 0, 0], [0, 0, -1, 0], [0, 1, 0, 0], [0, 0, 0, 1]],[[0.7100121904087335, -0.7041818153996531, 0.003270768821452005, 0], [-0.003270959293846674, -0.007942649389283879, -0.9999631162256629, 0], [0.7041818102602434, 0.7099753015919312, -0.007942727719273094, 1], [0, 0, 0, 1
Trace: TypeError: Cannot read property 'length' of undefined
    at iron_object_BoneAnimation.setMats (<anonymous>:11010:51)
    at iron_object_BoneAnimation.setActionBlend (<anonymous>:11073:8)
    at iron_object_BoneAnimation.play (<anonymous>:11091:10)
    at arm_AnimationObj.playMove (<anonymous>:402:25)
    at Array.<anonymous> (<anonymous>:434:20)
    at iron_App.update (<anonymous>:4916:27)
    at kha_TimeTask.task (<anonymous>:23009:3)
    at Function.kha_Scheduler.executeTimeTasks (<anonymous>:22893:75)
    at Function.kha_Scheduler.executeFrame (<anonymous>:22845:17)
    at kha_SystemImpl.renderCallback (<anonymous>:23633:16)`

**To Reproduce**
Create a mesh object and an armature and parent the armature to the mesh. Give the armature two animations, then attach a script to it that contains methods to play those animations. Next, attach a script to the mesh object that takes keyboard input and depending on the keys pressed, will call the methods in the script attached to the armiture to play the animations, e.g. plays the first animation when the key "1" is pressed and plays the second when the key "2" is pressed.

**Expected behavior**
The animation would be played normaly.

**System**
Blender: 2.81a
Armory: 2019.11.0
OS: Fedora 30
Graphics card: GeForce GTX 1650/PCIe/SSE2

**Test File**
[script problem.zip](https://github.com/armory3d/armory/files/3940825/script.problem.zip)

**Comment by Sandy10000** [comment]
Creating a strip with the action "Move" in the Nonlinar Animation (NLA) editor works fine.

**Comment by BTCallahan** [comment]
> Creating a strip with the action "Move" in the Nonlinar Animation (NLA) editor works fine.

Thank you, that ended up working. I'm used to working with the BGE, which doesn't have this issue.
