### ISSUE TITLE
Custom Shader for material destroys UV map

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1510]
Whenever I use custom Shader for an Material, the UVs ar missing

"iron.data.Geometry:271: Armory Warning: Geometry Suzanne is missing UV map"

[material_shaders.zip](https://github.com/armory3d/armory/files/3951634/material_shaders.zip)

Press play and check Right monkey

**Comment by kennylerma** [comment]
Bumping this., UVs are need for custom shaders with textures.
