### ISSUE TITLE
iron.system.Audio.play() does not work on Krom

### ISSUE THREAD

**Issue by greyheron** [armory3d/armory#1511]
iron.system.Audio.play() does not seem to work on Krom target, where same code work on other targets.

(Not sure if this bug is already known but I didn't find any open issue about it.)

**Comment by greyheron** [comment]
Following up on this, it looks like Krom by default has disabled the sound. In order to have it enabled a flag --sound should be passed to Krom. 

A suggestion would be to update `/blender/arm/make.py` like this commit https://github.com/greyheron/armory/pull/2/commits/c2d41bd416e41cdc1042f949ffaf0e6708955bfc

If that's good approach I can send a PR to armory3d/armory.

**Comment by luboslenco** [comment]
Hi, the sound should work out of the box - which OS and Armory version are you on? Is this using the 'stock' ArmorySDK from itch.io?

**Comment by greyheron** [comment]
I am on Windows 10, and I am using latest development version of Armory not 'stock' Armory SDK.

**Comment by luboslenco** [comment]
Latest dev version as in using the built-in sdk updater? Or cloning [armsdk](https://github.com/armory3d/armsdk)? Basically need to know your setup to reproduce the issue. 🙂 Does 'stock' ArmorySDK1912 give you the same result?

**Comment by greyheron** [comment]
Apologies, I did a fresh install of armory using the latest ArmorySDK1912 from itch.io and it is working in Krom. I possibly at some stage I built Krom from Kode/Krom and forgot about it. 

In Kode/Krom master sound was inverted and `--nosound` flag should be `--sound` as sound is disabled by default.
