### ISSUE TITLE
canvas nodes only work with scene canvas but not object canvas

### ISSUE THREAD

**Issue by betteravoid** [armory3d/armory#1516]
**Description**
canvas nodes only work with scene canvas but not object canvas.

On object canvas:
"Get" nodes throws: null
"Set" nodes throws: error (cannot read property "get ready" of null ) and freezes the game.

there should be text field for user to input canvas name

On scene canvas everything works perfectly fine
![progress bar](https://user-images.githubusercontent.com/50422301/70939212-13ca9880-2048-11ea-8668-828fa7cc6a23.png)
![canvas error](https://user-images.githubusercontent.com/50422301/70939249-2218b480-2048-11ea-96de-198503319b67.png)

@BlackGoku36

**Comment by knowledgenude** [comment]
You need an Element nammed "ttt"
