### ISSUE TITLE
Uncaught TypeError: Cannot read property 'viewport' of null when VR enabled

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1517]
**Description**

When using the default scene in Blender with VR property enabled, the following error shows up on both Browser and Krom with only the left side part of the viewport displaying.
![Capture](https://user-images.githubusercontent.com/55564981/70958528-d2eb7780-2079-11ea-9cab-9eeda201a0f1.PNG)

`Uncaught TypeError: Cannot read property 'viewport' of null`

    at iron_RenderPath.drawStereo (kha.js:2349)
    at iron_RenderPath.armory_renderpath_RenderPathForward.commands (kha.js:450)
    at iron_RenderPath.renderFrame (kha.js:2014)
    at iron_object_CameraObject.renderFrame (kha.js:11824)
    at iron_Scene.renderFrame (kha.js:3189)
    at iron_App.render (kha.js:1797)
    at Function.kha_System.render (kha.js:21466)
    at animate (kha.js:21943)

I have an Oculus Quest, and similar to the browser only left part of the display shows up. The other side is simply blank. 

Furthermore, I have tested the head tracking and works as expected. I suspect only the implementation of the following lines of code at https://github.com/armory3d/iron/blob/cbf480827b5e8ee4a42ea428c9f144ad05e79159/Sources/iron/RenderPath.hx#L412

**To Reproduce**

- Create a new blend file

- Enable VR in armory render properties and run.

**Expected behavior**
Both sides of the viewport should be displayed without errors

**System**
Blender:2.81
Armory:2019.11.0
OS: Windows 8.1
Graphics card: Intel HD4500

**Comment by luboslenco** [comment]
Thanks for report. I have fixed this particular error at https://github.com/armory3d/iron/commit/a9247efab0225325d1448446ce7afd5a35af7a9c, so both viewports should at least show up. VR support needs more work though - further issues linked at https://github.com/armory3d/armory/issues/1034.
