### ISSUE TITLE
Updating SDK with "Update SDK" button method failing

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armory#1518]
Thank you for contributing to Armory!

**Description**
Cloning SDK through the "Update SDK" button method fails to complete due to an error with git submodule:
```Submodule path 'Tools/haxe': checked out 'de31b2cc440bcd91942d7fae966507ea44176c8e'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
error: Server does not allow request for unadvertised object 83b065d279dad27e7ed4a3be956771818b5e1f96
Fetched in submodule path 'Tools/khamake', but it did not contain 83b065d279dad27e7ed4a3be956771818b5e1f96. Direct fetching of that commit failed.
```

**To Reproduce**
Update SDK From the Armory addon settings

**Comment by luboslenco** [comment]
It's back! Thanks for notice. (https://github.com/armory3d/Kha/commit/cdc54cb3938e26c65cbe2681b51cdcd733d1f1b2)
