### ISSUE TITLE
FileNotFoundError after relative path option then back

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#1519]
**Description**
Saved file is on E drive (not C).
If you click "Generate Relative path" in Armory settings, blend file is somehow changed permanently. Even after removing "Relative path" and removing + re-installing Armory plugin your file is corrupt and cannot be played anymore. It sticks to relative path of generated build files.
Note that some files are generated correctly, it stops at `compiled.inc`

**To Reproduce**
Click "relative path", save blend file.
You'll get something like:
```

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\nobody\Documents\ArmorySDK//armory/blender\arm\props_ui.py", line 457, in execute
    make.play()
  File "C:\Users\nobody\Documents\ArmorySDK//armory/blender\arm\make.py", line 462, in play
    build(target=runtime_to_target(), is_play=True)
  File "C:\Users\nobody\Documents\ArmorySDK//armory/blender\arm\make.py", line 346, in build
    export_data(fp, sdk_path)
  File "C:\Users\nobody\Documents\ArmorySDK//armory/blender\arm\make.py", line 155, in export_data
    write_data.write_compiledglsl(defs + cdefs, make_variants=has_config)
  File "C:\Users\nobody\Documents\ArmorySDK//armory/blender\arm\write_data.py", line 440, in write_compiledglsl
    with open(arm.utils.build_dir() + '/compiled/Shaders/compiled.inc', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build_0untitled/compiled/Shaders/compiled.inc'

location: <unknown location>:-1
```

**Expected behavior**
Back to previous behavior, fulll path

**System**
Blender: 2.82, 2.81, 2.80
Armory: 2019.11.0
OS: Win10

**Test File**
[0untitled.zip](https://github.com/armory3d/armory/files/3975177/0untitled.zip)

**Comment by j2l** [comment]
It is critical to anyone who manage data on a secondary drive and SDK + add-ons on the main drive like me. 
I broke several important files before nailing down to this setting. I dumped and reinstalled Blender, settings, add-ons and restarted from scratch to understand.

**Comment by MoritzBrueckner** [comment]
Hi,

I can't reproduce this error, could you please test if the issue still occurs?

However, I added some safeguards to the khafile generation so that absolute paths are used for those paths that point to a different drive than the project is on.

Thanks for reporting!

**Comment by MoritzBrueckner** [comment]
Doesn't look like it's still an issue, please reopen if the error still occurs.
