### ISSUE TITLE
Need Some AI logic nodes.

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armory#1528]

**Comment by knowledgenude** [comment]
Hi, @divineniiquaye! What kind of nodes you want by AI Nodes? I think is better you made a more especific feature request. I coundn't figure out a AI logic that can't be done already. For example, navigation is a kind of AI. By AI, i understand things like making a bot for example. A bot will make use Navigation and can have an Aim, that you can do using look at node, and can tweak the precision of its aim. Like when it is moving, you can down the bot precision, etc. A AI node don't brings any insight of what you want.
