### ISSUE TITLE
Logic node "Trait" does not work depending on conditions

### ISSUE THREAD

**Issue by Sandy10000** [armory3d/armory#1529]
**Description**
Click here for related forum page.(https://forums.armory3d.org/t/remove-object-if-it-has-contact-with-object-from-collection/3788)

If try to apply a trait that has not been applied to any other object using "Add Trait", the "Trait" node will not get the Trait. Specifically, "cname" is Null both times.

In the test file, press the space bar to fire a bullet. By setting traits in advance for Suzanne (unnecessary objects), can acquire traits and the first bullet firing works without any problem. However, after the second bullet, there is no error but no trait has been applied. (The bullet does not disappear)

By commenting out the following line, the trait is applied to the second and subsequent bullets.
```
if (value != null) return value;
```

**To Reproduce**
Run the test file.

**Expected behavior**
Allows to get traits that have not been applied to any objects.

**System**
Blender:2.81
Armory:2019.12

**Test File**
[Trait.blend.zip](https://github.com/armory3d/armory/files/4002587/Trait.blend.zip)

**Comment by MoritzBrueckner** [comment]
The issue is that Traits were not exported when unused. Now there is a "Fake User" option added to address this in https://github.com/armory3d/armory/pull/1646.
