### ISSUE TITLE
Parenting doesn't work with animation when interpolation is linear

### ISSUE THREAD

**Issue by razcore-art** [armory3d/armory#153]
Possibly other interpolations as well, I haven't checked yet. Problem is even if you modify the curve in the graph editor it still behaves as the default bezier interpolation. So... animations don't take in account the graph editor?

I uploaded the blend file as `.png` so rename file to `*.blend` because github doesn't allow uploading `.blend` files it seems.
![test](https://cloud.githubusercontent.com/assets/1177508/24097965/8aedd45e-0d68-11e7-9910-43aed159d4a4.png)

**Comment by razvanc-r** [comment]
I checked the code (`iron/Sources/iron/object/Animation.hx`) and it seems that is should support linear interpolation unless `track.curve` returns always `bezier` for some reason. I found curve in `TTrack` in `iron/Sources/iron/data/SceneFormat.hx` but I have no idea how it gets the value from blender :D. I'm still figuring out how haxe is tied with blender.

**Comment by razvanc-r** [comment]
Oh! I found out that you have to set keyframe interpolation to **both/all** points in the curve editor, then the animation works as expected. A bit different from blender, should probably fix :P.

I mean in Armory's case it looks like you're not using the data from the F-Curve editor, you're just using a "default" bezier curve interpolation. I suppose once this is implemented correctly then it would behave like in Blender.

**Comment by luboslenco** [comment]
Thanks for report! It should work like Blender, so likely incomplete or missing implementation in Armory. There is a ton of features packed in Blender which makes this happen more often than one would like. Will get that sorted.

PS: Sorry I am running late with things, in full swing to prepare new packages so the next build can take place. :)

PS2: Changing the issue template to say 'drag & drop zipped .blend file' which seems to work, .png will also do hehe.

**Comment by luboslenco** [comment]
Appears to work now.
