### ISSUE TITLE
 font size in canvas?

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#1531]
Happy new year!

Maybe there's a good reason it's missing and I don't get it?
It's present in https://github.com/armory3d/armory2d/blob/f7ded835ea70d7baea3b5deda05c426c29da5efa/Sources/arm2d/Editor.hx, 
https://github.com/armory3d/zui/blob/c8fe916ab6214a04812403704e1709278952cd8c/Sources/zui/Canvas.hx, 
https://github.com/armory3d/armorpaint/blob/45e7d3e589c924bb7cc5c888c6fc5088c0be1ee2/Sources/arm/ui/UINodes.hx
Why isn't it in Canvas?

Or is there an alternative to Canvas with more settings?

Don't want to be rude here, just need to understand if I missed something.

**Comment by BlackGoku36** [comment]
You can do it by:
```hx
var canvas = Scene.active.getTrait(CanvasScript);
canvas.setCanvasFontSize(15); // or whatever font size you want
```

**Comment by j2l** [comment]
Oh wow, than you @BlackGoku36 !

**Comment by j2l** [comment]
@BlackGoku36, is it possible to have another type of canvas? Something 3D?

**Comment by j2l** [comment]
Forget my previous questions, I forgot about the example 🙄
