### ISSUE TITLE
Lightning just doesn't work

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#1538]
One sun or one point/area light works OK. When you add more it starts to break. Some lamps are ignored, some produce unnatural shadows, and if you add more then 4-5, none work. I took a look at the related code, it looks kind of experimental and unfinished - it's very hard to contribute and get some patches done. 

Please we need the most important thing for a game, the lightning, to work properly.

**Comment by luboslenco** [comment]
Aware of the problem but please no duplicate issues.

**Comment by trsh** [comment]
Didn't know this was reported. Sorry!

**Comment by trsh** [comment]
@luboslenco plz plz take brake from Painter to fix this. We have 2 demos waiting for proper lightning
