### ISSUE TITLE
Show traits in Outliner

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#154]
As I was playing with the animation options in `Armory` I noticed a couple of things. There are two ways as I can see to work with animations, `Edit Clips` & `Edit Actions`, under `Properties > Object` tab, but `Edit Actions` is available only on bones. I suggest that Armory should work only with `Action`s and ditch the `Edit Clips` & `Edit Actions` altogether. Arguments:

1. you don't have to "make" animations in `Armory` (under `Edit Clips`) and then select the starting animation from this list, instead just list all available `Action`s from `bpy.data.actions`
2. you don't have to define the range, `Action` object has `frame_range` property which can be used in `Armory`
3. `Action`s can be used on all objects, not just bones and it makes for a more logical workflow, when first doing an animation in `Dope Sheet` it silently creates an `Action` anyway
4. it removes duplicate work

Some other suggestions related to UI. I've noticed that some of the options are hidden away under more `Advanced` settings, one example is the `Advanced` toggle under `Property > Object > Armory Props`. Problem with this is that it hides options that influence the workflow **even** if `Advanced` is turned off. So say I untick `Object Animation` and then untick `Advanced`, then `Armory` uses the unticked `Object Animation` option even though it's not present in the UI any longer. I think this is wrong. I think that unticking `Advanced` should in turn use all options under it with their default values. This makes more sense to me. If you turn something on/off under `Advanced` on multiple objects, then untick `Advanced` you might not remember what you switched on/off. I think you can see how this can be a problem.

About `Traits`. If you could hack the `Outliner` to show the `Traits` under the object mesh data, I think it would improve considerably the ease of keeping track of these `Traits`. So I guess somehow link `Traits` to blender's scene data.

That's it for now :)

**Comment by luboslenco** [comment]
`Advanced` toggle is gone and animations are now using `Action`s. Showing traits in the outliner to go. :)

**Comment by razvanc-r** [comment]
Woho, nice, I'll wait for the next release to play with it :P

**Comment by luboslenco** [comment]
There is an experimental way to inspect traits in the outliner now through a Groups view.
![traits](https://user-images.githubusercontent.com/3685704/33811553-38ebe898-de15-11e7-85af-1644027d5947.PNG)

(Related: http://forums.armory3d.org/t/how-to-list-objects-a-script-or-logic-node-attached/560/5)
