### ISSUE TITLE
Move from Eevee to its own render engine

### ISSUE THREAD

**Issue by SeaPeaMe** [armory3d/armory#1542]
It kinda annoys me that I can't render a snapshot in Eevee and use Armory in its own render engine tab. It would make it so much easier to navigate, as the other options for the eevee engine that don't work in armory don't have to be there.
![Tabs](https://user-images.githubusercontent.com/39147581/72211874-ec6fca00-3526-11ea-981b-5f71228d2998.JPG)

**Comment by N8n5h** [comment]
Armory is not exactly a render engine for Blender so that option would be akwardly placed there. Maybe panels that allow containing subpanels, so it would be less cluttered probably.. but I'm not sure if that is possible currently in Blender.

**Comment by divineniiquaye** [comment]
I have used armory rendered in 2.8 version 0.5 i just dont no Y armory cant do it again

**Comment by BlackGoku36** [comment]
Because the blender's API changed a lot during that time and also did armory. So, it is not easy to re-implement it.
