### ISSUE TITLE
Support for Logic Editor

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#155]
With Armory, the Logic Editor is like an unused organ. Why not put that component to use? Adding a "Logic Editor" option in the Armory Traits type and letting you punch in nodes from the Logic Editor would be a great idea for those already used to that system.
*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Already open at https://github.com/armory3d/armory/issues/47.
