### ISSUE TITLE
we need nodes for save and load

### ISSUE THREAD

**Issue by donjwan88** [armory3d/armory#1552]
The armory must contain a basic nodes to store data  ( save and load )

**Comment by BlackGoku36** [comment]
There is `Read File`/`Json` and `Write File`/`Json` node to save data locally.

*Note: This read/write from `Bundled` folder.*

<img width="306" alt="Screen Shot 2020-02-06 at 2 35 09 PM" src="https://user-images.githubusercontent.com/36535717/73921731-e84c8780-48ed-11ea-9358-f5803dc6c6ad.png">

**Comment by mhreez** [comment]
woooooooow thank you
