### ISSUE TITLE
sleep node not working between tow nodes of gate

### ISSUE THREAD

**Issue by donjwan88** [armory3d/armory#1553]
Thank you for contributing to Armory!

**Description**
Issue description.
sleep node not working between tow nodes of gate and it is display any controller by translate
when I remove node of sleep every thing working fine

in example you cane delete sleep node contain white color

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
What you expected to happen.

**System**
Blender: 2.81a
Armory: 2020.1.0
OS:
Graphics card: gtx1050

**Test File**
*(drag & drop the zipped .blend file here)*
[survival 36.zip](https://github.com/armory3d/armory/files/4106093/survival.36.zip)

**Comment by knowledgenude** [comment]
[gate_test.zip](https://github.com/armory3d/armory/files/5147164/gate_test.zip)

Can't reproduce the issue. Please reopen if your problem was not solved :+1:
