### ISSUE TITLE
FR: relative paths into kha.js

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#1557]
I noticed that putting all files as is into the post folder doesn’t work in all cases (getting 404 for some files that are present near kha.js). Scene.arm and some other files paths must be at root, they are not called relative to kha.js location but to the domain.

Naxela and me would love to be able to change paths.

**Comment by rpaladin** [comment]
Correct me if I'm mistaken, but shouldn't this issue be closed?

<kbd>Blender - Preferences - Add-ons - Game Engine: Armory - Preferences - Armory SDK Manager - Generate Relative Paths</kbd>

![image](https://user-images.githubusercontent.com/69180012/225473672-48a64f19-4334-496c-a7c5-4f30be6d4e4f.png)

To me, it seems like this should have been closed in: #2063

Could be mistaken.
