### ISSUE TITLE
FR: Set Visible Node: add "children" checkbox

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1558]
I'd be more than helpful if the "Set Visible" node had a checkbox "children" (maybe even the option for recursion).

**Comment by knowledgenude** [comment]
This workaround unexpectedly works: 
[getchildren.zip](https://github.com/armory3d/armory/files/5032040/getchildren.zip)


![getchildren](https://user-images.githubusercontent.com/63247726/89480449-bcf70800-d76b-11ea-9a21-73cff34b8f85.jpg)

When children prefix is blank, even the parent will be set to invisible, i don't know why.

**Comment by knowledgenude** [comment]
@MoritzBrueckner , what is better here? A checkbox or an array? With array it can be used to hide an collection

**Comment by MoritzBrueckner** [comment]
I would go for a checkbox. Most of the time this node will probably be used with single object, so people don't want to put that in an array first. If you need to make an entire collection visible, you can either loop through that array or you can make the collection's root object visible (+ children).

**Comment by knowledgenude** [comment]
Closed via https://github.com/armory3d/armory/pull/1864
