### ISSUE TITLE
world sky texture error

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#157]
Well, sky texture doesn't seem to work any longer :P with latest build.

[test.crash.txt](https://github.com/armory3d/armory/files/865736/test.crash.txt)
[test.blend.zip](https://github.com/armory3d/armory/files/865737/test.blend.zip)

**Comment by luboslenco** [comment]
Hm, maybe it's connected to the ['.config' path issue](https://github.com/armory3d/armory/issues/135#issuecomment-288523281)? @arturjpv also reports crash on 'hosek_radiance.hdr', which is a radiance map used for the sky.

**Comment by razvanc-r** [comment]
I'll try moving Armoury out of .config and see what happens

**Comment by arturjpv** [comment]
Yes, It seems the same problem.

test.blend file is crashing inside ".config" path and working outside. I'm having the same logs also than in the ['.config' path issue](https://github.com/armory3d/armory/issues/135#issuecomment-288523281).

If @razvanc-r confirms the same I think we are in the same issue.

**Comment by razvanc-r** [comment]
Yep, works after moving it out of `.config`

**Comment by luboslenco** [comment]
Sorry about the annoying path issues, getting better but takes time.

**Comment by arturjpv** [comment]
Don't worry :-)
