### ISSUE TITLE
Object children do not render when Stream Scene is enabled

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1571]
**Description**
Objects that are child to other objects do not load and do not render when `Stream Scene` is enabled. Additionally, this causes errors when LOD objects are present and `Stream Scene` is enabled since LOD meshes are child objects. 

Cameras that are child to other objects such as players/vehicles also do not load.

**To Reproduce**

1. Start a default blender scene
2. Duplicate (`Shift+d`) the default cube and parent to the other.
3. Enable `Stream Scene`.
4. Run the project

**Expected behavior**
The child objects must also be streamed.

**System**
Blender: 2,.81
Armory:  v2020.2 ($Id: 29eed7c87a5edde6fb0a5ff1814d57116f09cb46 $)
OS: Windows 8.1
Graphics card: Intel HD4500

**Test File**

[StreamSceneBug.zip](https://github.com/armory3d/armory/files/4198902/StreamSceneBug.zip)

**Comment by QuantumCoderQC** [comment]
Hi @luboslenco ,

I would like to improve scene streaming and fix this bug. However, I am not sure where to fix it. I believe the starting point for this is at [here](https://github.com/armory3d/iron/blob/0f6911c6a64abeda727abd1cd2a9865e73513fdd/Sources/iron/Scene.hx#L659).

Any inputs about how to fix this will be great!

**Comment by luboslenco** [comment]
Yes that looks like the starting point, my guess is the children are not being instantiated somewhere along the lines of https://github.com/armory3d/iron/blob/0f6911c6a64abeda727abd1cd2a9865e73513fdd/Sources/iron/data/SceneStream.hx#L73.

**Comment by QuantumCoderQC** [comment]
Closed via [ armory3d/iron#104](https://github.com/armory3d/iron/pull/104)
