### ISSUE TITLE
Bullet Physics memory leak error

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1574]
When adding and removing the same `Rigid Body` for a set number of iterations, the following error appears:

```
armory.system.Starter:79: Cannot enlarge memory arrays. Either (1) compile with
 -s TOTAL_MEMORY=X  with X higher than the current value 67108864, (2) compile w
ith  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (
3) if you want malloc to return NULL (0) instead of this abort, compile with  -s
 ABORTING_MALLOC=0
```

It seems that removing a rigid body does not fully free the memory.

**To Reproduce**

1. Add a relatively complex mesh object in the scene and add a RigidBody to it
2. Set type to `Mesh` and Mass to 0.
3. Add a script to remove and add the rigid body over each iteration, for a set number of iterations. 

**Expected behavior**
The program should ideally consume no extra memory, and execute without errors.

**System**
Blender: v2.81
Armory:  v2020.2 ($Id: 29eed7c87a5edde6fb0a5ff1814d57116f09cb46 $)
OS: WIndows 8.1
Graphics card: Intel HD 4500

**Test File**
[RigidBodyMemoryTest.zip](https://github.com/armory3d/armory/files/4206575/RigidBodyMemoryTest.zip)

[RigidBodyMemoryTestNodes.zip](https://github.com/armory3d/armory/files/4206638/RigidBodyMemoryTestNodes.zip)
**Description**

To run the test file, hit `Play` and to start the iterations, press `Space`.

**Comment by N8n5h** [comment]
You didn't mention if this is on Krom or in C so I take it's Krom from the Test file. It looks like an issue or a limitation of the GC of Kromx, maybe it isn't fast enough to collect the rigid body. 

Maybe testing it with a "slower pace", or removing the rigid body trait (offline) to check if this occurs with normal objects too can give more insight on the problem.

**Comment by QuantumCoderQC** [comment]
Hi,

Yes, this test was done on Krom. I also did the slower test, however, the error pops up at the exact same iteration as if it were done now. This shows that memory wasn't freed, irrespective of the rate of Add/Remove. 

How do you mean "removing the rigid body trait (offline)"?

**Comment by N8n5h** [comment]
Ok. By offline I meant removing the rigidbody trait from Blender and then test again (to make sure the issue is related to rigidbody and not game objects in general), I added "offline" so it wasn't misunderstood as removing it in-game before deleting the object.

**Comment by QuantumCoderQC** [comment]
So, I did some more testing about the issue, and it seems the memory leak happens when adding and removing the `RigidBody` trait to the object.

However, it does not occur if the `RigidBody` is directly added to and removed from the `PhysicsWorld.active.world`. This means there's something wrong the way `RigidBody` trait is handed in Armory3D

**Comment by onelsonic** [comment]
Hi there, just wondering what you are trying to achieve here?
The Armory physic engine is a port of bullet which is mathematically based on real physics.
Having an object with a zero mass should not be possible.
Have you tried to make the Rigid Body type has "Passive" instead, which will be more physically accurate?

**Comment by QuantumCoderQC** [comment]
Hello @onelsonic ,

Yes, I know that it is a port of Bullet Physics Engine. In fact, my first few contributions to Armory were in that area.

According to Bullet Physics, there are two types of rigid bodies: Static and Dynamic. 

Static whose mass must be zero and the RB does not move/ respond to forces. Setting rigid body type to Passive internally sets the mass to zero. 

Dynamic whose mass is non-zero and they do respond to forces. 

Here I am trying to create a Bullet Physics static rigid body, whose shape is a triangle-mesh of the object itself.

**Comment by onelsonic** [comment]
looking at the code, maybe there is a way to turn the velocity (linear and angular) to 0 programmatically for your object instead, to achieve what you need?
 
	m_interpolationLinearVelocity.setValue(0,0,0);
	m_interpolationAngularVelocity.setValue(0,0,0);

the piece of code responsible for this seems to be there : 
https://github.com/armory3d/haxebullet/blob/master/bullet/BulletDynamics/Dynamics/btRigidBody.cpp

**Comment by QuantumCoderQC** [comment]
I guess the problem is not clearly mentioned...It has nothing to do with the mass/velocity.

I re-iterate the issue: Adding a rigid body with zero mass/ with some mass has no issue at all. Everything works perfectly, even the simulations. No problems there.

The problem arises, however, when the rigid body is repeatedly removed and added back, say 100 times. Ideally, it should not cause any errors, because the memory is never expanded. Now comes the issue that I mentioned above in my first post. I get the error midway through the add - remove cycles.

Hope this makes it clear. Please let me know if any more info is needed.

**Comment by onelsonic** [comment]
From my understanding, creating a rigid body add a virtual shell to the object for collisions purposes.
When removing the object, the shell needs to be removed as well.
The accumulation of shells created might fill up your Graphic card memory.
That will be my guess.
Try to inspect all elements present in the scene with the debug console.

**Comment by QuantumCoderQC** [comment]
issue resolved
