### ISSUE TITLE
Collision does not work correctly anymore!

### ISSUE THREAD

**Issue by blackno666** [armory3d/armory#1577]
Armory v2020.2 ($Id: 29eed7c87a5edde6fb0a5ff1814d57116f09cb46 $)
OS: win, Target: krom, GAPI: direct3d11, Blender: 2.81 (sub 16)

See attached file: a "cursor" can be moved and collides with a cube. Once the cube is hit, it is removed.
This works, if the "cursor" is moved immediately after the game is started.

It does **not** work, however, if you start the game, wait for ~10s and then move the "cursor". The collision will not be detected anymore and the cube will note be removed (it still worked in a November 2019 build - I did not test other builds)!

For the attached file to work, you need to assign the bundled "SimpleMoveObject" to the circular object.

If there are problem to reproduce this, please let me know since this seems to be a serious error.

[CollsionFail.zip](https://github.com/armory3d/armory/files/4209009/CollsionFail.zip)

Best regards
blackno666

**Comment by QuantumCoderQC** [comment]
Hi,

In the Cursor and Cube physics properties, uncheck `Force Deactivation` and try again.
I don't think this is an error.

**Comment by blackno666** [comment]
Thanks! That solves the problem. To me, it was absolutely not obvious to uncheck `Force Deactivation`.
