### ISSUE TITLE
UI suggestion: renaming

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#158]
Renaming Armory Traits is a bit of a pain right now. I can't just double click on the names under Armory Traits and rename them. I can't just rename them from the Tree either. I have to rename them (in this case) from the node editor and then I have to correct the 404 error I get when the Tree field turns red because the naming doesn't work anymore and then it updates the Armory Traits field. I would like that to get resolved easily. Thanks.
*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Merging with issue report at https://github.com/armory3d/armory/issues/207.
