### ISSUE TITLE
Found the reason behind armory's light problem

### ISSUE THREAD

**Issue by divineniiquaye** [armory3d/armory#1581]
Thank you for contributing to Armory!

**Description**
its kromx, web build and vs code krom build has no light problem

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
I think u shud change or update kromx

**System**
Blender: 2.82
Armory: 2020.2
OS:win 10
Graphics card: intel hd 4400

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by knowledgenude** [comment]
Follow https://github.com/armory3d/armory/issues/1772#issue-660023398
