### ISSUE TITLE
OpenGL - uniform sampler2D tex

### ISSUE THREAD

**Issue by ArmoryBlender** [armory3d/armory#1586]
Hello!

Right now I'm stuck at figuring out how to use the sampler2D with armory3d. I tried it out with the 'image paramter' nodes but it still doesnt work somehow. The uv isn't unwrapped. I hope someone who knows how to do this can explain this to me.

Thank you and have a nice day!

**Comment by kennylerma** [comment]
Just bumping this.  I've been trying to do the same, but can't get the UVs to properly texture a custom shader.  This is kinda vital if we want to work together as a community adding custom shaders for everyone.
