### ISSUE TITLE
Some blender operators are not supported in Armory

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#159]
Go to `Scripting` layout and type `bpy.ops.wm.collada_import`, it should be a function, but it returns an error:

```py
>>> bpy.ops.wm.collada_import
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/razvan/Itch/Armory3D/Armory/2.78/scripts/modules/bpy/ops.py", line 207, in __repr__
    as_string = op_as_string(idname)
AttributeError: _bpy.ops.as_string: operator "WM_OT_collada_import" could not be found
```
Normal Blender install works as expected.

**Comment by luboslenco** [comment]
What OS is this? Does *File - Import - Collada (Default) (.dae)* in Blender show up for you? Apart from this Python terminal error, any more errors printed to system console?

Seems to work fine here somehow:
```
>>> bpy.ops.wm.collada_import
# Load a Collada file
bpy.ops.wm.collada_import(filepath="", filter_blender=False, filter_backup=False, filter_image=False, filter_movie=False, filter_python=False, filter_font=False, filter_sound=False, filter_text=False, filter_btx=False, filter_collada=True, filter_alembic=False, filter_folder=True, filter_blenlib=False, filemode=8, display_type='DEFAULT', sort_method='FILE_SORT_ALPHA', import_units=False, fix_orientation=False, find_chains=False, auto_connect=False, min_chain_length=0)
```

**Comment by razvanc-r** [comment]
My system is Ubuntu 16.10 64 bit.

Unfortunately I don't see any errors in the console, and there's no `File -> Import -> Collada (Default) (.dae)` either. I'm not sure how to debug this...

**Comment by luboslenco** [comment]
Still an issue on Linux, will have to tinker with the build flags.

**Comment by luboslenco** [comment]
Leaving the default build flags in place for now, to keep the build process as simple as possible..
