### ISSUE TITLE
Armory will not launch from Itch.io Client on Linux

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#1599]
**Description**
When launching Armory3D from the Itch.io client, it will not launch.  This is on Manjaro Linux.  Launching `ArmorySDK/nodejs/node-linux64` results in silent failure, while launching `ArmorySDK/Krom/Krom` results in the following error output:

![image](https://user-images.githubusercontent.com/548168/75908889-f9b77f80-5e18-11ea-871b-35ef20c5925b.png)

**To Reproduce**
Try to launch Armory3D from the Itch.io client on Manjaro Linux.

**Expected behavior**
Armory3D to launch

**System**
Blender: 2.82
Armory: 2020-2 and 2020-3
OS: Manjaro Linux, kernel 5.4.23 x86_64
Graphics card: GeForce GTX 950

**Comment by BlackGoku36** [comment]
That is just sdk, you will need to download blender and install addon using `armory.py` provided in that sdk and than run from blender
