### ISSUE TITLE
Audio Systems?

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#16]
How are the audio systems in the engine so far? We've seen a lot of visuals but haven't heard a lot about the audio portions. Is 5.1 and 7.1 support added yet and do you have audio editing tools in the engine?

**Comment by luboslenco** [comment]
Indeed, the sound is still at very primitive stage, that's why it's quiet. There is a Kha branch with positional 5.1 sound support, so the first step will be likely to get going from that. No audio editing yet either.

**Comment by George-the-1st** [comment]
Great, I have a sound system that can handle 5.1. I'll make sure to give it a test when you release it as part of a build.
