### ISSUE TITLE
WASM discussion Armory2020

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1602]
Hi there,
I did some digging with WASM and I am wondering why recoding Iron in C when JavaScript can be converted into native binary code.

Here are some thoughts, Armory is already producing JavaScript code
so if the goal is to improve performances, we can turn this JavaScript code into WAMS.

takes the JavaScript, turn it into Typescript and turn this Typescript code into WAMS.
There is a project that can help with this, take a look at : assemblyscript

https://github.com/AssemblyScript
https://docs.assemblyscript.org/

performance wise the difference between this WAMS code vs the Iron C version should be relatively small since both will be native binary code.

@luboslenco let me know what you think.

**Comment by luboslenco** [comment]
Hello,

Why would you expect this to improve the performance? You can already compile Armory straight into C today via HashLink. By compiling Iron as-is you will not get access to the manual memory management and you will also lose access to v8 garbage collector in exchange for a slower one. (not to mention more trouble with threading, SIMD, etc.)

*(Unimportant note - I do not think you can automatically turn JavaScript into TypeScript that AssemblyScript consumes. `AssemblyScript compiles a strict subset of TypeScript (basically JavaScript with types)`.)*

Hope that helps!
