### ISSUE TITLE
Navmash cannot be used in blender 2.82

### ISSUE THREAD

**Issue by qikong333** [armory3d/armory#1607]
blender 2.82

Traceback (most recent call last):
File "F:\YWH\ArmorySDK//armory/blender\arm\props_traits.py", line 365, in execute
value = float(pt.value)
AttributeError: 'ArmTraitPropListItem' object has no attribute 'value'

**Comment by MoritzBrueckner** [comment]
It's already fixed, you should update the Armory SDK

**Comment by qikong333** [comment]
> 它已经固定，您应该更新Armory SDK

Armory SDK 2020.2.0

**Comment by N8n5h** [comment]
@qikong333 Try with the git version of the armory SDK: https://github.com/armory3d/armory/wiki/gitversion

**Comment by MoritzBrueckner** [comment]
@qikong333 Is this still an issue? Did it work for you what N8n5h suggested?

**Comment by knowledgenude** [comment]
Please reopen if your problem was not solved :+1:
