### ISSUE TITLE
Black screen every time I try to run the game Blender 2.82

### ISSUE THREAD

**Issue by Weirdddude** [armory3d/armory#1608]
Trace: TypeError: Cannot read property 'hxBytes' of undefined
    at Function.haxe_io_Bytes.ofData (<anonymous>:6060:13)
    at Function.kha_LoaderImpl.loadBlobFromDescription (<anonymous>:23002:48)
    at Function.kha_Assets.loadBlobFromPath (<anonymous>:22116:17)
    at Function.iron_data_Data.getBlob (<anonymous>:2221:13)
    at Function.iron_data_Data.getSceneRaw (<anonymous>:2045:17)
    at Function.iron_Scene.setActive (<anonymous>:2983:17)
    at <anonymous>:1025:16
    at new iron_App (<anonymous>:1457:2)
    at Function.iron_App.init (<anonymous>:1476:2)
    at <anonymous>:1024:13

I merely have the default objects in the scene if that does anything (I'm new to this)

**Comment by N8n5h** [comment]
Hi, make sure Armory is properly installed and your copy of the SDK was properly extracted. Take a look at this [guide](https://github.com/armory3d/armory/wiki/setup). 

If you have git installed in your system you can also try using the git version to access the latest version of the SDK: https://github.com/armory3d/armory/wiki/gitversion

**Comment by Weirdddude** [comment]
I have tried installing it both ways and watched multiple YouTube videos on how to install it. I keep getting a black window

**Comment by N8n5h** [comment]
Try with the solutions found here https://github.com/armory3d/armory/wiki/troubleshooting to see if any of them solve your issue.

**Comment by Weirdddude** [comment]
I've gone through all the solutions in that link and I'm still getting the same error. I have a 840 GeForce graphics card and i7 4th gen intel CPU, I did use the mobile preset but that had no luck either. I have downloaded the latest version that was released two weeks ago and it has the same result. I tried  downloading the Visual C++ redistributable 2017 but I apparently already have it installed. I'm still getting the same error message. I really don't understand what is wrong.

**Comment by knowledgenude** [comment]
Try to set the render path to mobile. If this solve the issue, maybe is some graphic feature that is not working for you GPU. If this don't solve the problem, keep the mobile render path and delete de lamp from the scene. But the error message seems to be a problem related to some code. You have already updated Armory to Git version?

**Comment by Weirdddude** [comment]
Yes I have. I have also tried the mobile path method, unless I'm doing it wrong, but that doesn't work either. Do all of the paths in the "Advanced" section while in the add-on preferences have to be filled in? I've also set my render devices to none but no luck. I think it just doesn't like my computer

**Comment by knowledgenude** [comment]
Here is my SDK Manager options: 
![arm](https://user-images.githubusercontent.com/63247726/79869816-5b777d00-83b8-11ea-9c38-5398a5f6a4c4.jpg)

Did you see some error in the console after updating Armory? Or did you see at least a sucessfully update in the console? If this is ok, maybe you can try to update you drivers.

Also, please test this demo in your pc and see if it works: https://armory3d.org/demo/armory_demo_win64.zip

**Comment by knowledgenude** [comment]
Hi again, @Weirdddude! I found a solution for this issue. It happens to me today as you can see below:
![hxbytes](https://user-images.githubusercontent.com/63247726/80848706-7fbe2f80-8bea-11ea-8a93-655d43706dbd.jpg)

If you see the console, the problem will be showed **before the build starts**:

![hxbytes1](https://user-images.githubusercontent.com/63247726/80848750-b005ce00-8bea-11ea-9489-d10fefc049f7.jpg)

So, i am almost sure that the path of your .blend file use a special character. Note that all the path can not have special characters (even the folders names). If it is true, change all the path to a non special character path and the problem will be solved.

**Comment by knowledgenude** [comment]
If this solution don't works, you can reopen the issue.
