### ISSUE TITLE
Publishing has some problems with traits

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#161]
With Armory ~~preview09a~~ github master, when `Publish`ing (instead of `Build`), the `kha.js` file is incomplete. I attached the simple scene I showed you with the hexagonal columns, the `Camera` object has a `Trait` called `CameraLook` which isn't found in the `kha.js` file if `Publish` is used instead of `Build`.
[debug.blend.zip](https://github.com/armory3d/armory/files/870406/debug.blend.zip)

**Comment by luboslenco** [comment]
Looks like dead-code-elimination (auto-enabled on Publish builds) removing code which is not meant to be dead. Will fix.

**Comment by razvanc-r** [comment]
And I completely forgot about the fact that I'm using github master branch... not preview09a as I previously said :)... good thing you mentioned github in #160...

**Comment by luboslenco** [comment]
Dead-code-elimination issues should be now fixed in build 12. :)
