### ISSUE TITLE
I cant add object for parent of weapon 

### ISSUE THREAD

**Issue by mhreez** [armory3d/armory#1625]
Thank you for contributing to Armory!

**Description**
I want to add any object to be the parent of the weapon in the game until I find correct coordinates when catching the weapon,
When I add an Object and add a constrain child of  does not work, I cannot do a game test

Issue description.
I cannot do a game test
**To Reproduce**
1-Add an object to the place I want
2- add constrain child to mak parent for an object

**Expected behavior**
What you expected to happen.

**System**
Blender: 2.82
Armory: 2020.3
OS:
Graphics card: 1050 gtx

**Test File**
you can see this video

https://drive.google.com/open?id=1W63wTAKZqthmBjILpz-dEGhybARkHOkT
*(drag & drop the zipped .blend file here)*

**Comment by Simonrazer** [comment]
Constraints are not supported by Armory as of now, #62
