### ISSUE TITLE
Screen to world space node produces incorrect output.

### ISSUE THREAD

**Issue by QuartzKnight** [armory3d/armory#1626]
Thank you for contributing to Armory!

The Screen to world space node produces an incorrect  output.

Place a camera looking straight down at (0,0,10)
Create a nodetree with a mouse coords node and feed the coords output into the input of a Screen to world space node, probe the output of both nodes and assign the nodetree to an active trait.
Run and check the output of the screen to world space node for different mouse positions, the values are much higher than the camera plane's width and height.

I expected the X value of the output to range from 0 to the with of the camera plane, and for Y from 0 to it's height.

Blender:2.81
Armory:2019.10.0
OS:Windows 7 64 bit

[ScreenToWorldTest.zip](https://github.com/armory3d/armory/files/4382149/ScreenToWorldTest.zip)

**Comment by shedatc** [comment]
Is it somewhat related to the solution proposed here on the forum: [Compute world coordinates from mouse coordinates](https://forums.armory3d.org/t/compute-world-coordinates-from-mouse-coordinates/1496)?

**Comment by knowledgenude** [comment]
@shedatc This is what looks like. Someone could make a pull request for this.

**Comment by knowledgenude** [comment]
Link to https://github.com/armory3d/armory/issues/1866
