### ISSUE TITLE
Unable to run a program targeted to Windows C

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1627]
**Description**
When trying to run a generated program built using VisualStudio on Windows, the application immediately crashes, with the following exceptions: 
```
D3D11CreateDevice: Flags (0x2) were specified which require the D3D11 SDK Layers for Windows 8.1, but they are not present on the system.
These flags must be removed, or the Windows 8.1 SDK must be installed.
Flags include: D3D11_CREATE_DEVICE_DEBUG
Exception thrown at 0x00007FF9D5EE5BF8 in DefaultTest.exe: Microsoft C++ exception: _com_error at memory location 0x0000002D018773B0.
'DefaultTest.exe' (Win32): Unloaded 'C:\Windows\System32\d3d10warp.dll'
DefaultTest.exe has triggered a breakpoint.
```

The test was a default blender scene, and the `graphics API ` option set to `Auto`. 

The program, however, runs without issues in VisualStudio if the `graphics API` is set to `OpenGL`. But the application still does not run outside of VisualStudio when built as a .exe file.

No errors occur during any of the Build/Publish processes.
 
**To Reproduce**
1. Use a default blender scene
2. Build and publish to Windows(C) target.
3. When opened on VisualStudio, the project does not run after build.

**Expected behavior**
The application should run without errors.

**System**
Blender: 2.81
Armory: v2020.3 ($Id: 6b4b39b7e86646e6a4f11bc686d8f5998c2ba58a $)
OS: Windows 8.1
Graphics card: Intel HD4500

**Comment by luboslenco** [comment]
Does switching to release mode in visual studio make it work?

**Comment by QuantumCoderQC** [comment]
No, switch to release also does not solve the issue. The application simply crashes outside of Visual Studio.

**Comment by QuantumCoderQC** [comment]
This issue was solved after copying the generated `.exe` file into the `windows-hl` folder at the project location.
