### ISSUE TITLE
Get latest Armory from GitHub

### ISSUE THREAD

**Issue by anonimo82** [armory3d/armory#1628]
Hello everyone. I'd like to use latest Armory from GitHub, instead of periodically downloading the archive and installing it.
Which repo should I use for this?
I can't find the armory.py in this repo.

Thanks in advance for anything.

**Comment by luboslenco** [comment]
Hi, check here https://github.com/armory3d/armory/wiki/gitversion.

**Comment by anonimo82** [comment]
Wow, fantastic. Thanks

Il gio 26 mar 2020, 08:27 Lubos Lenco <notifications@github.com> ha scritto:
