### ISSUE TITLE
Void is not a value

### ISSUE THREAD

**Issue by moxiaomomo** [armory3d/armory#1631]
Hi @luboslenco ,

**Description**
After I upgraded the SDK from version 2020.02 to 2020.04, it will fail to build or export the project to Windows(C) project when the "Rigid Body" feature is enable. 

**To Reproduce**

- enable the "Rigid Body"

![image](https://user-images.githubusercontent.com/3700410/78330546-c94d3780-75b6-11ea-82d9-f6ed71064f7f.png)

- try to build at target Windows(C)

![image](https://user-images.githubusercontent.com/3700410/78330653-1204f080-75b7-11ea-8d86-7f044c483942.png)

- errors shown when build it

![image](https://user-images.githubusercontent.com/3700410/78330765-4e385100-75b7-11ea-8b7d-fc3038149684.png)

**Expected behavior**
Can build it for project Windows(C) target.

**System**
Blender: 2.82a
Armory: 2020.04
OS: Win10
Graphics card: GeForce RTX 2070

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by QuantumCoderQC** [comment]
Hey @moxiaomomo,

I have just published a PR for the issue, Please try it out and let me know if the issue still persists

Best,
QC

**Comment by moxiaomomo** [comment]
> Hey @moxiaomomo,
> 
> I have just published a PR for the issue, Please try it out and let me know if the issue still persists
> 
> Best,
> QC

Thanks, the new code works well.

**Comment by luboslenco** [comment]
Merged, thanks!
