### ISSUE TITLE
Armature Rig in editor is fine but in game messed up

### ISSUE THREAD

**Issue by Noahthenoob53** [armory3d/armory#1634]
Hey there!

I think this issue is not new. When I use my own rigged animated arms and want to use it in armory3d it gets deformed or just messed up. In the editor its just perfect but like I said in game its screwed up. I tried it millions of times but dont get the results. I really hope that someone can help me!!

![Unbenannt](https://user-images.githubusercontent.com/41879104/78512175-b13a0b80-77a2-11ea-8c75-3f424e95c4bf.PNG)

![Unbenannt2](https://user-images.githubusercontent.com/41879104/78512180-b5febf80-77a2-11ea-8103-cc7ce5eb01b0.PNG)

Have a nice day!

**Comment by N8n5h** [comment]
Hi, did you import the rig from other software or created it from scratch in Blender?
If it's the first one, try playing around with the import settings of Blender and the export settings of the other software.
If it's the second one, try applying the scale of the mesh and the scale of the rig before doing the parenting. Wrong scales can cause issues.
Other than that, make sure the weight values of each individual bones is correct and not causing issues here.

**Comment by Noahthenoob53** [comment]
Hi!

Thank you for your reply!

I will try this out and let you know

Have a nice day

**Comment by Noahthenoob53** [comment]
So I tried it out with applying the right scale and it seems to be much better! Thanks for your reply
