### ISSUE TITLE
Canvas Get Slider and Canvas Get Checkbox are causing C build failure

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1635]
I can't export my project and i am getting a warning about "scene don't have an active camera" but i have a camera in the scene.

I get this error too:

![error](https://user-images.githubusercontent.com/63247726/78571874-1cb0c700-77fd-11ea-9f35-db33171590c6.jpg)

If someone can clarify this for me, i will be gratefully.

**Comment by MoritzBrueckner** [comment]
This actually looks like two different issues:

- The `Void is not a value` error has been fixed a few days ago ([Link](https://github.com/armory3d/armory/pull/1633)), you should update your SDK to the latest [Git version](https://github.com/armory3d/armory/wiki/gitversion).
- The camera message is not an error but a warning instead. With the first issue resolved, the game should run but might have a different behaviour than expected.

  Is the camera linked from another .blend file or is it actually an object of the exported scene? I had some problems in the past with cameras from linked collections, they don't seem to work often.

  Regardless of that, is the camera set in `Properties > Scene Properties > Scene`?

**Comment by knowledgenude** [comment]
Thanks for the answer, @MoritzBrueckner. I will try to update ArmorySDK trough the Git now and see what happens.

The camera is properly set in scene propeties, i really don't know what is happening. Maybe i try to reproduce this in another .blend file later.

**Comment by knowledgenude** [comment]
Warning related to cameras in scene continues even with the update on SDK. But the problem seems to be solved by deleting the cameras and adding new cameras to the scene.

Git update solved the issue related to bullet. But now i got another issue, probably related to wrong logic nodes i do. Can someone tell me what it mean?

When i can export the project to C, i will test Krom exporting again, because i got sucessfully export to it but  i got black screen.

Is this problem related to wrong logic or are the logic nodes that i have used bugged?

![error](https://user-images.githubusercontent.com/63247726/78589012-eb90c080-7815-11ea-84fa-cbdd18d55c14.jpg)

**Comment by MoritzBrueckner** [comment]
It looks the logic nodes are not supported on static targets (C for example) indeed, they return `null` in some cases (for example if the canvas element was not found) but it should be a `Bool` type value.

The issue above occurs when there is no canvas object (or it is not ready yet) or the given element is not found.

I'm not really used to the node system (using Haxe all the time) so I'm not sure if raising an error (e.g. `CanvasGetCheckboxNode: Element [name] was not found!`) or returning a default value (`false` or `0.0` e.g.) + displaying a warning is the better way here. What do you think? Are there cases in which there should be no error when some elements don't exist?

If you understand Haxe, that's my proposed fix for `CanvasGetCheckboxNode`:
**Before**:
```haxe
override function get(from: Int) {
		if (canvas == null) canvas = Scene.active.getTrait(CanvasScript);
		if (canvas == null) canvas = Scene.active.camera.getTrait(CanvasScript);
		if (canvas == null || !canvas.ready) return null;

		// This Try/Catch hacks around an issue where the handles are
		// not created yet, even though canvas.ready is true.
		try {
			return canvas.getHandle(inputs[0].get()).selected;
		}
		catch (e: Dynamic) { return null; }
	}
```

**After**:
```haxe
override function get(from: Int) {
		if (canvas == null) canvas = Scene.active.getTrait(CanvasScript);
		if (canvas == null) canvas = Scene.active.camera.getTrait(CanvasScript);
		if (canvas == null) throw "CanvasGetCheckboxNode: Canvas was not found!";
		if (!canvas.ready) {
			trace("CanvasGetCheckboxNode: Canvas is not ready, returning 'false'");
			return false;
		}

		// This Try/Catch hacks around an issue where the handles are
		// not created yet, even though canvas.ready is true.
		try {
			return canvas.getHandle(inputs[0].get()).selected;
		}
		catch (e: Dynamic) {
			throw 'CanvasGetCheckboxNode: Element ${inputs[0].get()} was not found!';
		}
	}
```

**Comment by knowledgenude** [comment]
I am not a programmer, but i think that i understand what you do in your code. When Checkbox return null, you change it to a string, right?. And you do exactly what it need to be fixed. I tested the Canvas Get Slider node and Canvas Get Check node and it's bugged. You simply can't export any project if these nodes are on some object trait. Even if these nodes are alone in the whole scene, the build will failure.

Here is the test file

:
[Get Slider and Get Check issue.zip](https://github.com/armory3d/armory/files/4440533/Get.Slider.and.Get.Check.issue.zip)

**Comment by MoritzBrueckner** [comment]
Yep, it is an compiler issue so it will fail even if they are used correctly.

You are almost right, but instead of returning `null` it returns `false` in one case and in all the other cases, it raises an error (so it just "quits" the calculation for that frame) with the `throw "Error message"` syntax.

The proposed fix works, yes, but I don't know if that is true for all edge cases and if that new behaviour is intended. Maybe there is some better way, that's why I asked Sandy10000.

**Comment by MoritzBrueckner** [comment]
> Did you think that worth a new topic?

Yes, absolutely, it is an Armory problem.

**Comment by luboslenco** [comment]
Should work the same now like in Krom with https://github.com/armory3d/armory/commit/4c3332858ef0f397d898b3050fd86f80e47868eb. The compiler assumed a return type of `Bool` but it should have been `Null<Bool>`. When null is returned then element does not exist.

**Comment by Sandy10000** [comment]
I was late to notice the message. The problem with the canvas node seems to have been solved already.

Thanks to @knowledgenude for reporting bugs and @MoritzBrueckner and @luboslenco for their support.
