### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1636]
Warning 1. If a new scene is created with new settings, Armory will not recognize the camera.
     How to reproduce:

          1. Create a new .blend file.
          2. Create a camera in the current scene to make sure that the scene have a camera.
          3. Create a new scene with New Settings.
          4. Create a camera in the new scene.
          5. Start the player.

(warning 2 is not a bug, then i removed it)

Warning 3: if the scene name is the same from a mesh name for example, Armory will return a warning.

**Comment by MoritzBrueckner** [comment]
Regarding warning 2: It is a common warning but there is no way around that, other than renaming the trait. It is explained in the [wiki](https://github.com/armory3d/armory/wiki/troubleshooting#warning-trait-names-differ).

I'm investigating the other warnings and hopefully find a solution for it :)

**Comment by knowledgenude** [comment]
This happens with a same mesh and scene name. Already fixed the message.
Here is an example:
[warning.zip](https://github.com/armory3d/armory/files/4452617/warning.zip)

**Comment by MoritzBrueckner** [comment]
Fixed for warning 1: https://github.com/armory3d/armory/pull/1642 (took a little bit to find it but it's basically a one-character fix^^)

_Please don't edit the "warning numbers" in your first post above, otherwise the answers in this issue will make no sense for readers in the future_

**Comment by knowledgenude** [comment]
Sorry, I will edit it back to avoid confusion. But what was the warning 1 that you have fixed? I will assume that was the mesh/scene name for now. I am happy to see that you fixed it!

**Comment by MoritzBrueckner** [comment]
Warning no. 3 also has a fix now: https://github.com/armory3d/armory/pull/1643

Thanks for reporting this :)
