### ISSUE TITLE
How to contribute to Armory Kha?

### ISSUE THREAD

**Issue by Sanva** [armory3d/armory#1637]
Hi!

How should I proceed to contribute to Armory fork of Kha? ( https://github.com/armory3d/Kha )

For example, I would want to create the same pull request I've done here → Kode/Kha/pull/1188 — should I do it, or should I wait [1] till you incorporate the last changes from Kha to the Armory Kha fork? [2]

Thank you for Armory :heart: 

[1] I can patch my copy in me meantime.
[2] I don't really know if that is really intended or it will remain a fork that will eventually diverge.

**Comment by luboslenco** [comment]
Updated https://github.com/armory3d/Kha to latest Kha so your fix should be included now. 🙂
