### ISSUE TITLE
Material Values cant change

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#164]
Hi , i finaly bought armory 10a version. but i cant use it normaly like in the video on main page 5minutes of armory,

i use win7 64
gtx 1080
ryzen 1800
16gb ddr4

1, i cant change any the armory PBR material values or cycles during runtime. if i do then it will not updatethe new color. if i close it and click play in viewport again then its stuck and will not start.

here is "eror" what it says in the blender system console window when it get stuck after i try change material during runtime

Trace: TypeError: Cannot read property 'bytes' of undefined
    at $hxClasses.kha.graphics4.FragmentShader [as __class__] (krom.js:27566:52)

    at Function.kha_Shaders.init (krom.js:15837:37)
    at Function.kha_SystemImpl.init (krom.js:16181:14)
    at Function.kha_System.init (krom.js:15961:17)
    at Function.Main.start (krom.js:181:13)
    at Function.Main.main (krom.js:174:7)
    at krom.js:30883:6

but sky texture rotation does not make stuck it always...

found out if i delete files where it was saved and run again then the material is updated of new color...

becouse this i cant really use it becouse would need wait about 4-5 seconds everytime to see the changed material values on object..

2. if i add material during runtine, then i get black screens ...

3 cant pin camera options or the armory props , render path or render props doesnt expand to see the options..

4. sometimes it just crash / quits

well i very hope will fix as soon as possible so can use it wonderfully like in the 5 minutes of armory .

**Comment by luboslenco** [comment]
Hello @mushroomeo!

1, 2 - The reason is Armory now uses the new shader builder which does not implement live reload yet. Sorry for trouble - plan to fix that in next build (out next week if everything goes well).

3 - Does that happen with camera object selected? Any Python errors in the console? This should not happen.

4 - Can you reproduce this? If so then .blend files are welcome, might be able to fix that. :)

**Comment by mushroomeo** [comment]
hi finaly found out how to reproduce it. so if i change material values during runtime in viewport and then close it and run again its stuck. and then when i save it and open the blend file and click on play in viewport then it immediatly quits. 

[Armory Blend Files.zip](https://github.com/armory3d/armory/files/956902/Armory.Blend.Files.zip)

found out i dont need change values i just drag material node little during runtime and then close and run again and it stuck too. i add screenshot how it looks when it stuck. it has that white like around blender window borders..
![stuck freeze armory look screenshot](https://cloud.githubusercontent.com/assets/9019563/25413410/72344c16-2a2a-11e7-943f-9daf290de276.png)
 
for Point 3. adding screenshot too. even this is like most last important feature fix would like have fixed for now XD
![camera pining doesnt expand armory props](https://cloud.githubusercontent.com/assets/9019563/25413653/281aae2a-2a2c-11e7-96d6-1e86c5d94e22.png)

**Comment by luboslenco** [comment]
Messing with material values during runtime in viewport should be fine now in Build 11. Investigating issues with pinning..
