### ISSUE TITLE
Armory need some more Canvas elements related nodes

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1641]
Actually we have a good amount of Canvas nodes, but it not seems complete because:

We can't change the Checkbox value trought nodes, but slider, texts, etc. we can. If have a way to make a node like "Set Canvas Value" that works in all Canvas elements, this would be great.

Also we need a way to choose between Released, Down and Started in the button element. Already have a way to make this using events, but it act like a Started only.

**Comment by luboslenco** [comment]
See https://github.com/armory3d/armory/pull/1651 👍
