### ISSUE TITLE
Wrong input events due to key repeat on Linux

### ISSUE THREAD

**Issue by razcore-art** [armory3d/armory#166]
For example if *On Keyboard* node is set on `Release` event, after a short while pressing the button will trigger the event even though it's on `Release`, same for `Started`.

Try attached example. I've only tested on the keyboard nodes, but I assume the others are affected as well (Mouse, Gamepad etc.)

[test.zip](https://github.com/armory3d/armory/files/983608/test.zip)

**Comment by luboslenco** [comment]
Thanks for report! Is this on Linux?

**Comment by razvanc-r** [comment]
Well, yes on linux (Ubuntu 17.04), but I assume code like this is OS-independent... :)

**Comment by luboslenco** [comment]
Got some similar troubles reported on the forums, strangely seems to be Linux only. Kha/Kore handles input/os stuff directly, no 3rd party abstraction libs, will investigate any oddities there. :)

**Comment by luboslenco** [comment]
Link to https://github.com/Kode/Kha/issues/820.
