### ISSUE TITLE
Build command failed. Error while executing process -Pls help!

### ISSUE THREAD

**Issue by ozenorhan61** [armory3d/armory#1664]
I'm more new to android development. and i can't solve. I'm getting such an error. SDKs are up to date. I could not run the application somehow. there is always a problem. Very happy if you help. Please... Thanks...

Build command failed.
Error while executing process C:\Sdk\ndk\20.0.5594570\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Sihirlikelimeler\Word_Explorer\proj.android\app\jni\Android.mk NDK_APPLICATION_MK=C:\Sihirlikelimeler\Word_Explorer\proj.android\app\jni\Application.mk APP_ABI=x86 NDK_ALL_ABIS=x86 NDK_DEBUG=1 APP_PLATFORM=android-19 NDK_OUT=C:/Sihirlikelimeler/Word_Explorer/proj.android/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Sihirlikelimeler\Word_Explorer\proj.android\app\build\intermediates\ndkBuild\debug\lib NDK_TOOLCHAIN_VERSION=clang -j4 NDK_MODULE_PATH=C:/Sihirlikelimeler/Word_Explorer/cocos2d;C:/Sihirlikelimeler/Word_Explorer/cocos2d/cocos;C:/Sihirlikelimeler/Word_Explorer/cocos2d/external NDK_DEBUG=1 MyGame}

make: *** No rule to make target `MyGame'.  Stop.

![image](https://user-images.githubusercontent.com/63757066/79398132-8876fa80-7f88-11ea-9ef6-71b63254bd25.png)

**Comment by knowledgenude** [comment]
Hi, can you send the .blend? If you can't, did you already tested with another .blend? I don't have problems exporting to Android, maybe you do some wrong logic or configured Android Studio in a wrong way.

**Comment by ozenorhan61** [comment]
exactly which file should i send to you? close to 1gb in total.

knowledgenude <notifications@github.com>, 16 Nis 2020 Per, 02:46 tarihinde
şunu yazdı:

**Comment by ozenorhan61** [comment]
I am grateful to you for your return

Orhan ÖZEN <ozenorhan61@gmail.com>, 16 Nis 2020 Per, 03:05 tarihinde şunu
yazdı:

**Comment by knowledgenude** [comment]
What about the logic you put on it? If the file have 1gb, you can try to reproduce the logic and send me a .blend. If you can separate a .blend for me without textures, etc. to reduce the size, i can try to help you. Also, when you play the game in Armory player, you got some warning or error in the Blender console? Already tryed to export for Windows (Krom)?

**Comment by ozenorhan61** [comment]
Sorry, I don't know your language very well. When you say "blend" what
files do you mean? I'm so sorry I can't really understand what you're
saying. can you show me an example?

knowledgenude <notifications@github.com>, 16 Nis 2020 Per, 03:13 tarihinde
şunu yazdı:

**Comment by knowledgenude** [comment]
.blend is the file generated by Blender. When you save your project, you get a .blend. Use the Blender in english language, it is better for comunicate in the comunity. I am not english too, but it is a universal language that i have to use here. You can use google translater too. I wanna help, but i need the file to test.

**Comment by MoritzBrueckner** [comment]
I think there is probably a misunderstanding: this place is the issue tracker for Armory3D (a game engine for the software Blender), NOT a forum for Cocos2D (your error message looks like that)

**Comment by ozenorhan61** [comment]
Sorry, I can't create the file. If I give you a link, is it possible to
download the whole project and make arrangements?

knowledgenude <notifications@github.com>, 16 Nis 2020 Per, 03:28 tarihinde
şunu yazdı:

**Comment by ozenorhan61** [comment]
The application I use is for Android Studio. I think you are talking about
a different program?
Orhan ÖZEN <ozenorhan61@gmail.com>, 16 Nis 2020 Per, 03:34 tarihinde şunu
yazdı:

**Comment by knowledgenude** [comment]
I am not understanding you, @ozenorhan61. If you are not using Armory3d, you have to go in the page of the game engine you are using to be helped. Here is just about Armory3d. Good luck, guy! Don't give up.

**Comment by ozenorhan61** [comment]
[resolved]..All files coming out of zip must be in the c folder.
