### ISSUE TITLE
node like line trace in unreal

### ISSUE THREAD

**Issue by mhreez** [armory3d/armory#1670]
you can make node like line trace in unreal it is very useful and very easy to use 

like this 
https://www.youtube.com/watch?v=yBmPxGHu3uo

**Comment by knowledgenude** [comment]
Hi, @mhreez. Armory already have a Physics Ray Cast node. It is the same that Line Trace.

You can put 2 emptys to represent the start and the end of the Ray Cast.

Use a Get Object and a Get Location node for each empty. Set Collision Filter to 1 in the Physics Ray Cast node.

Also, you can set a object to hit location if you need.

It is really very useful, sadly isn't working in Android :/

**Comment by mhreez** [comment]
thank you  but I tried a lot with it but could not do that. Can you send a file that has been using the node in it?

**Comment by knowledgenude** [comment]
The trait is commented like a tutorial, make sure to set Collision filter in RayCast propeties to 1, i don't know why it comes with a zero by default.

Until now i don't know what the normal value means... maybe it is the normal direction to set as a rotation. I will test it later

[New Folder.zip](https://github.com/armory3d/armory/files/4497964/New.Folder.zip)

**Comment by MoritzBrueckner** [comment]
> Until now i don't know what the 'normal' value means... maybe it is the normal direction to get as a rotation.

That's the normal vector of the surface at the hit position. This graphic shows it very well:
![](https://www.iforce2d.net/image/raycasting-output.png)
Image source: https://www.iforce2d.net/b2dtut/raycasting (not Armory related, I just searched for "ray cast normal")

**Comment by knowledgenude** [comment]
So, the normal vector can be used for stuff like that?

![maxresdefault](https://user-images.githubusercontent.com/63247726/79673971-15060080-81b5-11ea-9390-a2f911e3d248.jpg)

 I don't understand too much by the image, it looks for me like a rotation value given by the normal direction.

So, I will make a pull request for this example, thank you @MoritzBrueckner!

**Comment by MoritzBrueckner** [comment]
> So, the normal vector can be used for stuff like that?

Yes :) For this particular example you would have to calculate the reflection of the ray's direction vector (that's the line coming from the left in the billard picture) off the normal vector and you would get the vector that is going to the right in the picture (the normal vector lays "in the middle" of both displayed lines"). Vector reflections are a little bit more complicated and I'm not sure if there is a node for it. It doesn't look like the `Vector Math` node supports it, I can open a PR for that tomorrow :)

If that wasn't clear, this is an image that explains reflections off a normal vector very well (on the left side):
![](https://asawicki.info/files/Reflect_Refract.png)
Source: https://www.asawicki.info/news.php5?x=tag&tag=rendering&page=5

> I don't understand too much by the image, it looks for me like a rotation value given by the normal direction.

I'm not sure how much you know about vectors, but we are probably talking about the same thing. Basically, a vector is just a multidimensional value (like an array) that can represent a position or (in this case) a direction, so the normal vector is just the direction the surface at the hit position is "looking at". You can of course use this for rotation.

In the first image two posts above, the red points are on the ray line (the points actually don't matter here, the fraction neither does). That ray hits the polygon and the green normal vector represents the direction the face that was hit is "looking at".

Sorry if this answer is a little bit overkill, I just try to explain it as good as possible :)

**Comment by knowledgenude** [comment]
I know that vectores can be way complicated. I find out when i tryed to understand how to get the distance between two objects. It is easy when you have just one vector, just subtracting the distances and getting the product that is the wanted distance. But when you have three vectors with positive and negative values... my brain is not advanced for this now.

Also, as you can see i don't know how to do a pull request. :/

**Comment by MoritzBrueckner** [comment]
> Also, as you can see i don't know how to do a pull request. :/

It is described here: https://github.com/armory3d/armory/wiki/contribute
If I get the time I will add some more information to that wiki page :)

What you did is to create a pull request on your own fork and you merged the content of a branch of your fork to the master branch of also your fork. Instead you have to go to the Armory examples repository and open a pull request there.

**Comment by knowledgenude** [comment]
I will wait for the tutorial update. I tried to understand and follow it but seems that it was made for those who are already used to GitHub. Demonstrating the steps with images would also be interesting. Thank you for the informations.

**Comment by MoritzBrueckner** [comment]
Its updated now. More information is probably coming when I open a new PR sometime.

@mhreez Is this issue resolved now? If yes, you can close it :)

**Comment by mhreez** [comment]
> Its updated now. More information is probably coming when I open a new PR sometime.
> 
> @mhreez Is this issue resolved now? If yes, you can close it :)

Thank you
