### ISSUE TITLE
No play button and Armory options

### ISSUE THREAD

**Issue by surya178099** [armory3d/armory#1677]
![Capture](https://user-images.githubusercontent.com/48434643/80299242-914da480-87b0-11ea-9eca-7c56d997a567.PNG)

Armory is not starting showing above error.
my laptop has 
i5 2520m processor
4gb ram
no GPU
just hd 3000
HP elitebook 8460p

**Comment by luboslenco** [comment]
Which Armory version? If you are on the latest then you will need Blender 2.8.
