### ISSUE TITLE
Build error when textures contain foreign characters

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#168]
`Scene built in 260.0129120349884
Traceback (most recent call last):
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\props_ui.py", line 543, in execute
    make.play_project(True)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\make.py", line 340, in play_project
    build_project(is_play=True, in_viewport=in_viewport, target=state.target)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\make.py", line 258, in build_project
    export_data(fp, sdk_path, is_play=is_play, is_publish=is_publish, in_viewport=in_viewport)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\make.py", line 125, in export_data
    write_data.write_khafilejs(is_play, export_physics, export_navigation, dce_full=is_publish)
  File "C:/Users/blake/Downloads/Armory_p10a_win64/Armory/armsdk//armory/blender\arm\write_data.py", line 104, in write_khafilejs
    f.write(add_assets(ref))
  File "C:\Users\blake\Downloads\Armory_p10a_win64\Armory\2.78\python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 83-85: character maps to <undefined>

location: <unknown location>:-1

location: <unknown location>:-1
`
Some of my textures contained Cyrillic characters but renaming it solved the problem. Just thought you should be aware.

**Comment by luboslenco** [comment]
Testing a fix for this, could you try to put your Cyrillic characters back?

Patched in https://github.com/armory3d/armory/commit/419b3a999c30dd04430cae6636b82138e7126600.

**Comment by fractalfederation** [comment]
Tested with latest Armory and it built without errors using the Krom runtime. Thanks!

I am getting the following error when using Browser of Electron runtimes:

C:\Users\blake\Downloads\Armory3D\Armory\armsdk\iron\Sources/iron/data/Mesh.hx:275: characters 16-24 : kha.arrays.Uint32Array should be Array<Int>
C:\Users\blake\Downloads\Armory3D\Armory\armsdk\iron\Sources/iron/data/Mesh.hx:275: characters 16-24 : For function argument 'x'

Haxe compiler error.
Build failed, check console

If it's not related, I can make a new issue for it.

**Comment by luboslenco** [comment]
Hm, is there any chance your Kha copy is not the latest from git?

**Comment by fractalfederation** [comment]
Git says it's up to date. I used the official under user Kode. You have your own fork, was I suppose to use that one?

**Comment by luboslenco** [comment]
Kode/Kha is perfect. One more try, maybe out of date iron clone? (This commit should have got rid of that error https://github.com/armory3d/iron/commit/75157154dcd2c60d4a506f97d0ecb06907dabab4).

**Comment by fractalfederation** [comment]
Deleted the iron directory and cloned a new copy. Electron and Browser runtimes are working again.
