### ISSUE TITLE
arm.SimpleRotateObject does not have field speed(Float) - Error

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1680]
Using the latest github repo the SimpleRotateObject does not work anymore
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/SimpleRotateObject.hx

I have the following on Android : 

`Uncaught exception: arm.SimpleRotateObject does not have field speed(Float)`
The App then crash on Android.

The speed value is specified in the .hx file and in Blender:
`	var speed: Float = 0.01;`

<img width="276" alt="2020-04-27 20_55_59-Blender_  C__Users_devWin10_Desktop_seed2_seed_123irose blend" src="https://user-images.githubusercontent.com/53947594/80410102-5049b300-88ca-11ea-88d4-90c21c2c269b.png">

The value is not correctly assigned in android but the trait is correctly attached to an object.

**Comment by knowledgenude** [comment]
Is it working on Armory Player? I have experienced issues using float node in a specific way when exporting to Android too. Maybe you should try to delete float from the code you are using and test it again. I don't know if float can be replaced for a integer... I am not a programmer, but if you think that it makes sense, you can try just to better filter the  issue. Also, is the code trying to compare float with a vector?

**Comment by onelsonic** [comment]
Seems like this was caused by another issue elsewhere in the code.
The android debug is not great. Debugging it in the Player helped.
Thanks
