### ISSUE TITLE
SDK error and Code editor 

### ISSUE THREAD

**Issue by FERDA69** [armory3d/armory#1684]
I need help getting started,

When I ran the playground example the game wouldn't run because it couldn't find / couldn't access files.

The SDK wouldn't update because of a similar error and now after uninstall and reinstall the armory3D project explorer etc, do not show up.

Any help or insight is greatly appreciated!

**Comment by FERDA69** [comment]
Also code editor wouldn't run because of access errors (I have the kode.exe pointed and couldn't figure out how to use VS)

**Comment by FERDA69** [comment]
Update - 
Reinstalled everything and project explorer etc show up again.

When I try to run the playground I get the message below:

<img width="666" alt="Capture" src="https://user-images.githubusercontent.com/64674446/80871086-e897bd00-8c67-11ea-9eb4-d2d511e23ff5.PNG">

and kode gives me some error with the Haxe:

![image](https://user-images.githubusercontent.com/64674446/80871114-06fdb880-8c68-11ea-9b4e-a9cec0fc776b.png)

**Comment by FERDA69** [comment]
First update of SDK works but now gives the following when updating:

![image](https://user-images.githubusercontent.com/64674446/80871173-6bb91300-8c68-11ea-8e94-cf49076cdc5f.png)

**Comment by MoritzBrueckner** [comment]
Hi,

it looks like there are a few different issues here:
- You should change the Kha path in the Kode studio settings to the path of Armory's Kha (`YourSDKPath/Kha`). Kode Studio unfortunately uses a very outdated Kha version.
- Unfortunately I cannot reproduce the `arm.SpawnBox` error, maybe this is because of the setup problems you have/had. Did you run the playground file from [latest version of Armory tutorials](https://github.com/armory3d/armory_tutorials/releases/tag/20.03)? What happens if you select the "Spawn" object in the scene and go to `Properties > Object > Armory Traits` and click on "Refresh"?
- That `WinError 145` is indeed a bug. I've looked into the problematic file and there is a line that only works on Unix based systems and on Windows it doesn't. If I get some time tomorrow, I'll take a look. Thanks for reporting :)

**Comment by FERDA69** [comment]
![image](https://user-images.githubusercontent.com/64674446/80894342-763ed100-8c97-11ea-9078-315925f2db8a.png)
I'm not sure if I did the path correct but still have the error on Int16Array

![image](https://user-images.githubusercontent.com/64674446/80894453-3c21ff00-8c98-11ea-8185-8fe9e44cd599.png)
I didn't notice anything happen when I refreshed

I do not think any SDK folder was opened during the update, I've changed the line and restarting 
![image](https://user-images.githubusercontent.com/64674446/80894539-f6196b00-8c98-11ea-90b5-a2df7132a9d5.png)
Build still fails.

I am going to delete everything and restart.

**Comment by MoritzBrueckner** [comment]
I think I found the issue. You must extract the zip of the armory tutorials first (thats why the SpawnBox trait was not found) and the files should not be in the temp folder.

Regarding the Kode Studio thing: That looks correct. Is the krom path also set accordingly?

**Comment by FERDA69** [comment]
That might of been it, I don't remember if I unziped the folder originally, the game builds now.
I do still have two warnings that generate but not sure if its something I need to worry about.

![image](https://user-images.githubusercontent.com/64674446/80895114-7c847b80-8c9e-11ea-8e30-8709e2b603e3.png)


Haxe is still generating an error in Kode
![image](https://user-images.githubusercontent.com/64674446/80895210-a5594080-8c9f-11ea-96fe-2e74bd5a808a.png)
Should I try re-downloading?

I have not git bashed the folder and need some clarification what I'm doing when I do it
![image](https://user-images.githubusercontent.com/64674446/80895216-b3a75c80-8c9f-11ea-934f-bdf3eddd3347.png)

Which folder is it referring to
![image](https://user-images.githubusercontent.com/64674446/80895241-cfaafe00-8c9f-11ea-9a4f-16ba338f25ec.png)

**Comment by FERDA69** [comment]
![image](https://user-images.githubusercontent.com/64674446/80896513-45b56200-8cac-11ea-8ab9-3b1a024b9572.png)
Starting a new drawing and an error generates, the console still shows text when played in blender but when ran through Kode it shows this.

I think after I have Kode fixed I'm ready to get going, thanks for the help!

**Comment by MoritzBrueckner** [comment]
From where do you have this manual page? I think it is from the very old manual on armory3d.org?

The new manual is located in the [wiki](https://github.com/armory3d/armory/wiki) of this repository, there is also a page dedicated to [using Git](https://github.com/armory3d/armory/wiki/gitversion). You should never clone Armory directly into a Blender folder.

I have no idea what could cause the last error you described.

**Comment by FERDA69** [comment]
I've made a lot of progress, thanks for the help!

![image](https://user-images.githubusercontent.com/64674446/81022316-90f57f00-8e2a-11ea-8929-ef1a262c5930.png)

It was from the old manual, can you explain this to me?
I somewhat understand github but don't know how to get it to function

![image](https://user-images.githubusercontent.com/64674446/81022916-1fb6cb80-8e2c-11ea-895f-ac9f70d6acf2.png)

Can you help me with this error?

Any direction on some better / most up to date tutorials?

**Comment by FERDA69** [comment]
![image](https://user-images.githubusercontent.com/64674446/81024417-a1105d00-8e30-11ea-9136-f61734ecda47.png)

I am having an issue with the scripting basics tutorial

**Comment by MoritzBrueckner** [comment]
Hi, what exactly don't you understand? How to execute the git commands?

First of all, you don't need to use the Git version, the monthly release should be sufficient to get started. The Git version is helpful if you want to use the latest features or want to help developing.

GitHub is not Git, GitHub is just one of many websites where you can host projects that use Git.
To execute git commands, you have to install Git first and after that start the command line/terminal of your operating system and navigate to a folder where you want the SDK to be.

In your screenshots, it looks like the SDK was installed to the Blender directory but you should not do that. Using Armory from a sort of protected path like `C:\Program Files\...` is error-prone. If you don't use the Git version, Armory will automatically detect the SDK path it was installed from upon install and link to it.

**Comment by FERDA69** [comment]
With the basic issues I'm having I think I'll manually update for now.

I've moved the SDK from C:\Program Files\Blender Foundation to C:\Users\Ferda\Documents\

I get a cache error a lot and just had a performance error pop up recommending another builder in Kode, I will see how moving the file improves things but any recommendations on improving things like that?

**Comment by MoritzBrueckner** [comment]
Without knowing the errors in detail, it is hard to guess what's causing them.

Caching in Armory (if that's what you're talking about) is a little bit unstable at the moment. Pressing the `Clean` button removes the cache, there is also an option to disable the caching altogether, it is called `Cache Build` and enabled by default.

Whats that Kode error you're talking about?

**Comment by FERDA69** [comment]
![image](https://user-images.githubusercontent.com/64674446/81218066-d20ca100-8f9a-11ea-963f-8bd6b2aa5730.png)
![image](https://user-images.githubusercontent.com/64674446/81218098-e0f35380-8f9a-11ea-851b-53acbc949bc9.png)

I'm not sure if this is Armory caching or Kode.

It seems like each time we use a new function it errors that function and after a few restarts it works again, but not sure.

**Comment by MoritzBrueckner** [comment]
I get the build cache error too - even in VS Code. But that's not a big problem usually.

Regarding the second error: If you think this is a Kode Studio bug, you should open an issue in the [repository of Kode Studio](https://github.com/Kode/KodeStudio), so Robert (the maintainer of that program) can fix it. **But**, it looks like there is also an error in your code. It is a little bit strange that `iron.Trait` is not found. Can you take a look in the SDK folder and see if the Iron subdirectory actually has content in it? If no, make sure to download Armoy from itch.io, the GitHub releases don't include submodules (I wonder why) so they are not really usable until GitHub implements this.

Maybe all of this needs way better documentation in the wiki, if you want you can improve it by sharing your findings :)

**Comment by FERDA69** [comment]
I don't think it is problem with Kode Studio because I can start a project out of it and no errors show. I think it is something with my Haxe or maybe python.

![image](https://user-images.githubusercontent.com/64674446/81461824-8eb55c80-916b-11ea-8226-95ea4d5888c1.png)

Do I need a rendering path or anything else?

![image](https://user-images.githubusercontent.com/64674446/81461923-52363080-916c-11ea-8abe-77468d8e9226.png)
This is currently repeatable error when making a new project.

![image](https://user-images.githubusercontent.com/64674446/81461940-71cd5900-916c-11ea-80ce-4fab95721a8c.png)
![image](https://user-images.githubusercontent.com/64674446/81461949-83166580-916c-11ea-92c8-b9b7e8d4fc3e.png)
![image](https://user-images.githubusercontent.com/64674446/81461963-988b8f80-916c-11ea-8bcf-3fcadc434f04.png)
![image](https://user-images.githubusercontent.com/64674446/81461974-ae995000-916c-11ea-851e-0d3168d47e16.png)

Any settings in Haxe that look wrong?
I'm not sure what json is but I keep seeing it trying to find errors...
![image](https://user-images.githubusercontent.com/64674446/81462068-3717f080-916d-11ea-85bf-c221b713bd26.png)


![image](https://user-images.githubusercontent.com/64674446/81461997-cc66b500-916c-11ea-9c42-40f628308115.png)

**Comment by FERDA69** [comment]
I am confident it is a setting error, once haxe caches I should have full function but cannot figure where it's wrong. 
I am definitely going to add anywhere I think additional setting info is needed.

iron is in ArmorySDK

![image](https://user-images.githubusercontent.com/64674446/81462279-af32e600-916e-11ea-9fe4-2b0febc8d4a7.png)

Watching some youtube videos on Kode and found that I should install node? 
Not sure but thanks again

**Comment by MoritzBrueckner** [comment]
It's really strange..

> Watching some youtube videos on Kode and found that I should install node?

You don't need to install node.js, it is not required.

My last idea: could you post the khafile.js of your project? Maybe there are some misconfigured paths.

**Comment by FERDA69** [comment]
Here is the folder structure:
![image](https://user-images.githubusercontent.com/64674446/81480935-032ee080-91ea-11ea-81db-be6ade923f71.png)
![image](https://user-images.githubusercontent.com/64674446/81480949-12159300-91ea-11ea-9d63-a2705cae3f51.png)
and
C:\Program Files\Blender Foundation\

Its not letting me attach the khafile.js
![image](https://user-images.githubusercontent.com/64674446/81481035-851f0980-91ea-11ea-9ed8-eed84a7bcb1b.png)
Let me know if this works!
[Sources.zip](https://github.com/armory3d/armory/files/4604231/Sources.zip)


If it is a configuration issue what are some good rules of thumb to make sure everything is going and looking where it should?

I have multiple blend files in my test folder, when building a game would it be advisable to use multiple blend projects?

**Comment by FERDA69** [comment]
I hope this isn't a user error... if there is not anything wrong in the khafile and you are available to it, I've really appreciated your help and if you could please reach out to the e-mail in my profile, I would be interested in more expertise

**Comment by MoritzBrueckner** [comment]
I unfortunately can't test your file as there is no blend file (so Armory doesn't work, there is nothing to export) and the khafile does reference your local, absolute paths. But it looks correct.

I still do not understand if you try to run the game via Armory's UI in Blender or with Kode Studio (the screenshots say Kode Studio but you said otherwise in some posts).

- Can you run the Armory examples by now? If not, it is definitely a setup issue.
- Can you enable `Generate Relative Paths` in Armory's setting and try again (you need to compile from Blender once for this to take effect)

Do you have discord? If yes, there is a Armory channel (better than doing support per mail and there are more people that can help): https://discord.com/invite/axq6qWV

**Comment by MoritzBrueckner** [comment]
Hi @FERDA69,

I now had the same issue you mentioned [here](https://github.com/armory3d/armory/issues/1684#issuecomment-623768855) and opened a pull request over on the Kha repository that hopefully fixes this: https://github.com/Kode/Kha/pull/1206. May I ask to what target you were compiling?

Did you find a solution for the other issues?

**Comment by MoritzBrueckner** [comment]
@FERDA69 Please reopen if the issues still persists
