### ISSUE TITLE
Booleans starting with 'True' instead of 'False'

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1689]
Boolean property should start as False, but this is not happening here:

[BoolTest.zip](https://github.com/armory3d/armory/files/5379355/BoolTest.zip)

**Comment by knowledgenude** [comment]
I can't reproduce the steps to reach this result. Tryed duplicating objects, copying physics properties, etc. I really can't tell what is happening here. Test file:

On Init will prints the starter value of each object boolean property. Some booleans returns true i don't know why. This already happened to me two times. This can cause a "hard" logic problem because the user will not expect this happening and will not be able to track the bug in some cases.

[BoolTest.zip](https://github.com/armory3d/armory/files/4629621/BoolTest.zip)

**Comment by knowledgenude** [comment]
Unfortunately this is an annoying Haxe bug that i can't figure out. It is happening even in a fsm test script.
I have not a single line assingning a false value to a variable, but the compiler assigns false to it eventually.

**Comment by MoritzBrueckner** [comment]
This looks like a Blender UI issue to me. The property in the file seems to be `True` but it isn't displayed in the UI, the checkbox in the property list is completely invisible. I have no idea why this happens, I tried a lot of different things but nothing worked so far. It seems broken in both Blender 2.8 and 2.9.

Screenshot from a different file with a bool, float and a string property:
![screenshot](https://user-images.githubusercontent.com/17685000/108527086-2a1a5700-72d2-11eb-8b3f-1962461899f1.png)

If you click on the very right side of the row, you can actually toggle the boolean but you won't see it (wait for the correct tooltip).

**Comment by knowledgenude** [comment]
@MoritzBrueckner , i also don't know why this happens. Thanks for your reply, I guess you got notified about my previous comment, that was just a user error. I searched for "myVar = false" and didn't find that, but the variable actually was set to false in another way like "myVar = anotherVar".

About the properties panel maybe would be better to just leave it as a string "false" or "true" if this problem is so hard to find out, or just force all booleans to start as false while this bug is not solved (this bug is very annoying and may confuse people, or they could think it is a Armory bug). As the value can't be visible set, all starting as false would not be a bigger problem. What do you think?

**Comment by MoritzBrueckner** [comment]
I found a solution (the new `layout.introspect()` feature is really great for debugging!) and it was actually pretty simple. But I have still no idea what *exactly* `layout.use_property_split` (see PR) does, it is undocumented. PR: https://github.com/armory3d/armory/pull/2113

Now, if you open your file again with the PR applied, you can see that the property was actually `True` (default is `False`), so I guess that you probably clicked a bit too far to the right once^^

**Comment by knowledgenude** [comment]
That is really great, many thanks! :smile:
