### ISSUE TITLE
Build error, error X3004: undeclared identifier 'gl_FragCoord'

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#169]
`
Armory v17.05
OS: win, Target: krom
Scene built in 0.1371018886566162
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (BallMat_data.arm).
Exporting asset 1 of 1 (MazeMat_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (blur_adaptive_pass_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvTex_Rad_InvY_SSAO_SMAA_CToneFilmic.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_quad_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssr_pass_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (supersample_resolve_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvTex_Rad_InvY_SSAO_SMAA.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (scuffed-plastic-ao.jpg).
Exporting asset 1 of 1 (scuffed-plastic-normal.jpg).
Exporting asset 1 of 1 (scuffed-plastic-rough.jpg).
Exporting asset 1 of 1 (scuffed-plastic2-alb.jpg).
Exporting asset 1 of 1 (topanda.hdr).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (topanda_irradiance.arm).
Exporting asset 1 of 1 (topanda_radiance.hdr).
Exporting asset 1 of 1 (topanda_radiance_0.hdr).
Exporting asset 1 of 1 (topanda_radiance_1.hdr).
Exporting asset 1 of 1 (topanda_radiance_2.hdr).
Exporting asset 1 of 1 (topanda_radiance_3.hdr).
Exporting asset 1 of 1 (topanda_radiance_4.hdr).
Exporting asset 1 of 1 (topanda_radiance_5.hdr).
Exporting asset 1 of 1 (topanda_radiance_6.hdr).
Exporting asset 1 of 1 (topanda_radiance_7.hdr).
Exporting asset 1 of 1 (topanda_radiance_8.hdr).
Exporting asset 1 of 1 (topanda_radiance_9.hdr).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.001.arm).
Exporting asset 1 of 1 (mesh_Cube.002.arm).
Exporting asset 1 of 1 (mesh_Sphere.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (BallMat_mesh.frag.glsl).
C:\Users\blake\Downloads\build\temp\BallMat_mesh.frag.hlsl(63,72-83): error X3004: undeclared identifier 'gl_FragCoord'

Shader compiler error.
Build failed, check console
`
[LAB.zip](https://github.com/armory3d/armory/files/998165/LAB.zip)

I get this error when attempting to build a default scene (just a cube, light and camera). I have latest everything, git cloned iron and armory.

**Comment by luboslenco** [comment]
This should be now resolved if you pull latest armory and kha (with submodules using `git submodule foreach --recursive git pull origin master` and `git pull origin master`).

(The reason was that by cloning latest Kha Direct3D11 backend got activated, which is not yet 100% implemented, but soon.)

Patched in https://github.com/Kode/khamake/commit/de591693045b31a6e163a08fcc77e7d030abb221 and https://github.com/armory3d/armory/commit/1f392aaf24e38be24d4b632ce5d91f77597c2dbb.

**Comment by fractalfederation** [comment]
Working now.
