### ISSUE TITLE
Shadows bug

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#1692]
hi. as soon as i add second light to scene and run armory then the its all black. or it just failing to build. or second light doesnt work in game...

so i can have only 1 sun light and 1 point,spot,area : (

**Comment by knowledgenude** [comment]
According to this report, you can have more lamps in the exported build: https://github.com/armory3d/armory/issues/1581

I don't know if you can use more lamps in the Krom publish build, but if you can, then you can tweak your lamps trough there until the issue becomes solved, as it is faster to get than C builds.

**Comment by knowledgenude** [comment]
Follow https://github.com/armory3d/armory/issues/1772#issue-660023398
