### ISSUE TITLE
Build error, Type not found : GetRotationNode on logic node tree

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#170]
`Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
C:\Users\blake\Downloads\Sources/arm/node/Camera.hx:22: characters 25-40 : Type not found : GetRotationNode
Haxe compiler error.
Build failed, check console`

[scene1.zip](https://github.com/armory3d/armory/files/998458/scene1.zip)

Attached .blend file. I get the error when using the Get Rotation node.

**Comment by luboslenco** [comment]
Nice! Fixed typo in https://github.com/armory3d/armory/commit/e9bfdab2b0b5ca5aad29207db1c0bdc822042f24.

For the 'do while mouse is pressed' this should work:
<img width="349" alt="onmouse" src="https://cloud.githubusercontent.com/assets/3685704/26024174/d0c563d2-37cc-11e7-821a-10d1e18942ea.png">
