### ISSUE TITLE
Improve Play Sound Node

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1703]
The Play Sound node should be like:

![playsound](https://user-images.githubusercontent.com/63247726/82042695-b7b08280-9680-11ea-8b5a-b34eb41db1e8.jpg)

Play - Plays the sound

Pause - Pauses the sound

Stop - Stops the sound

Repeat - If checked will Repeat the sound, but i wonder if is not better to make a Loop input instead of repeat, like:

![playsound](https://user-images.githubusercontent.com/63247726/82044062-07904900-9683-11ea-9bfb-8441b4a23690.jpg)

Loop work in this case would be: if the input is activated and the audio already done its loop, then the audio will be started again and again... I don't know about nodes internal work.

Out - ...

Done - Useful for play a sequence of different sounds separately

Running - Useful to avoid conflicting sounds

Also i think that can have practice way to sync audio and animations but i don't know if it is good in the same node or with another node like "Get Animation Frame".

The use would be: "When reloading animation is on frame 1 or more, then Play Sound..."

**Comment by MoritzBrueckner** [comment]
HI, had some spare time, so here it is: https://github.com/armory3d/armory/pull/1705

**Comment by knowledgenude** [comment]
Thank you so much, @MoritzBrueckner!
