### ISSUE TITLE
Physics Ray Cast / Pick Object don't works in C targets

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1706]
Tested in release and debug mode

The test file contains an exported release apk

[tests.zip](https://github.com/armory3d/armory/files/4641529/tests.zip)

**Comment by QuantumCoderQC** [comment]
Thanks for the report!

Unfortunately, it is also the case with Windows(C) targets. Both Release and Debug variants do not react to ray cast and Pick Object.
