### ISSUE TITLE
trace does not print customParams on krom

### ISSUE THREAD

**Issue by tong** [armory3d/armory#1714]
When using the krom target `trace` does not print custom params to console.
```haxe
trace("A","B","C");
```
Prints:
`my.Game:55: A`

Should:
`my.Game:55: A, B, C`

Works as expected with html5 target.

**Comment by N8n5h** [comment]
I think it might be a limitation/problem with Haxe. The language allows you to override the default behavior of trace and [that's what it's being used for Krom](https://github.com/armory3d/Kha/blob/cc8e0b169325e031c912ec51d702ab2797e62337/Backends/Krom/kha/SystemImpl.hx#L136) and it seems the first argument is being taken into account and the rest is ignored.
