### ISSUE TITLE
Help with a forum post or pull request

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1719]
I can't create a forum account to post this file, and i don't know if this fit into a game example for Armory.

This is the first game i have "finished" in Armory, but i will not publish it because of some bugs not good for this kind of game, but i think it is good for a example. The game is not well done but ok.

If someone could please post it in the forum or create a pull request for Armory examples, i will be grateful. No credit is required and it is free for any purpose. Only contains a third party asset that is from HDRI Haven but under cc0.

File
[example_poolgame.zip](https://github.com/armory3d/armory/files/4708006/example_poolgame.zip)

**Comment by N8n5h** [comment]
Wow, nice little game!
> but i will not publish it because of some bugs not good for this kind of game

Really? what bugs exactly?
> If someone could please post it in the forum or create a pull request for Armory examples

Done! https://github.com/armory3d/armory_examples/pull/19

**Comment by QuantumCoderQC** [comment]
Nice game @knowledgenude and runs as expected on Android and Windows too.

**Comment by N8n5h** [comment]
Can you test the PR in Windows, @QuantumCoderQC ? I made a little change to the icon path because it gave me trouble in Linux, so not sure if it works in Windows. Otherwise it's something worth investigating.

**Comment by knowledgenude** [comment]
@N8n5h, thank you! The bugs i see are not a game killer. The two i know is:

1. Sometimes when the ball is on a corner, the shot don't go straight, the ball make a "curve" and don't hit the target.

2. Sometimes when you shot with high strenght, the white ball tresspass the other balls without transfer its force to it, so i reduced the maximum strenght (but it keep happening sometimes). For the table i fixed it by increasing its colliders sizes. It is why all the objects are over sized, to avoid physics bugs.

But the mainly reason i will not publish it, is because i think that the logic trees could be much more simple and readable to add more stuffs in the future, so i just keep it as an experience for me

But the game is playable of course. And thank you for the PR :)

**Comment by luboslenco** [comment]
It's in, awesome game! Many thanks for contributing.
https://github.com/armory3d/armory_examples/tree/master/game_pool
