### ISSUE TITLE
Only one particle system duplicate at a time possible

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1720]
**Description**
If the Paritcle settings have the same name only one of the Particle systems will actually show up in game. If the settings are copied,so the names are different but all the values are all still the same two particle systems show up.

**To Reproduce**
Duplicate a particle system object .

**Expected behavior**
Two of the same particle systems two be at different places now.

**System**
Blender: 2.82
Armory: 2020.6
OS: Win 10 (tested on Krom)
Graphics card: GTX 1060

**Test File**
https://github.com/armory3d/armory_examples/blob/master/particle_examples/mesh.blend
(Duplicate the particle system object)

**Comment by MoritzBrueckner** [comment]
Will be fixed in https://github.com/armory3d/armory/pull/1722, thanks :)
