### ISSUE TITLE
[hl] bullet.RigidBody has no field isKinematicObject

### ISSUE THREAD

**Issue by Sanva** [armory3d/armory#1730]
**Description**

As soon as you try to use `PhysicsDrag`, the project stops compiling for Hashlink targets with the error `.../ArmorySDK-git/armory/Sources/armory/trait/PhysicsDrag.hx:44: characters 43-60 : bullet.RigidBody has no field isKinematicObject` .

I've been trying to tackle the problem studying the Haxebullet WebIDL definition and it looks like the problem has something to do with inheritance ( https://github.com/armory3d/haxebullet/blob/master/Sources/bullet/bullet.idl#L454 ), so:

- Problem: https://github.com/armory3d/haxebullet/blob/master/Sources/webidl/Module.hx#L334
- Is already solved: https://github.com/ncannasse/webidl/pull/6/files

Indeed, overwriting Haxebullet WebIDL sources with current version of ncannasse/webidl solves the build problem — should I create a pull request in armory3d/haxebullet with this update, @luboslenco ?

By the way, picking objects to drag them doesn't work even with the change, but that seems related to fragments of code in Armory that only get included when building for JavaScript or C++ ( e.g. https://github.com/armory3d/armory/blob/master/Sources/armory/trait/PhysicsDrag.hx#L106,L110 ). This last problem may be the same reported in #1706 .

**System**
Blender: 2.82.7
Armory: Git version.
OS: Linux Mint 19.2 (linux 4.15.0-76-generic x86_64)
Graphics card: NVIDIA Quadro M2000M 4 GB

**Test File**
You can see the problem in the example https://github.com/armory3d/armory_examples/blob/master/physics_examples/drag.blend .

**Comment by luboslenco** [comment]
> Indeed, overwriting Haxebullet WebIDL sources with current version of ncannasse/webidl solves the build problem — should I create a pull request in armory3d/haxebullet with this update, @luboslenco ?

That would be awesome!

> By the way, picking objects to drag them doesn't work even with the change, but that seems related to fragments of code in Armory that only get included when building for JavaScript or C++

Maybe `pickConstraint.getFrameOffsetA().setOrigin(newPivotB);` will work for both js and hl now? hxcpp had issues with that before, hence the `#elseif cpp`.

**Comment by Sanva** [comment]
> Maybe pickConstraint.getFrameOffsetA().setOrigin(newPivotB); will work for both js and hl now?

Not for Hashlink, `btGeneric6DofConstraint.getFrameOffsetA` is missing from both WebIDL definition and C++ glue code.
