### ISSUE TITLE
Receive shadows don't work as disabled

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1737]
In material settings there is an option to disable the material shadows receiving, but the option don't work, the material always receive shadows.

**Comment by MoritzBrueckner** [comment]
Hi, it works for me, do you have a minimal example file? Please note that this option only works with forward rendering, otherwise it should be disabled in the UI.

**Comment by knowledgenude** [comment]
Here is an example: [untitled.zip](https://github.com/armory3d/armory/files/4907736/untitled.zip)
I tested it again and it's not working. What option i have to enable in UI?

**Comment by MoritzBrueckner** [comment]
It has something to do with materials for mobile render path, the required code is missing in `make_mesh.py` in `make_forward_mobile()` but it's included in `make_forward_base()`.

I don't know yet if I'm able to fix it (I can't test it on mobile devices, my android builds always fail with the most obscure errors or the built app just crashes instantly) but if I do I'll let you know and open a PR :)

**Comment by knowledgenude** [comment]
Okay. Thank you! If you need, feel free to send me any exported test build and i try to generate an APK from it. ^^  Also if you have some error in Android Studio you can send it too, then maybe we can find a solution for it. But as the mentioned problem is happening inside Armory Player, an apk shouldn't be necessary.
