### ISSUE TITLE
[Question] About generated mesh in Armory/Iron

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#1738]
I am trying to do [marching cubes](https://twitter.com/UrjasviS/status/1263207289735057409) in armory and following the [example](https://github.com/armory3d/armory_examples/tree/master/mesh_generate) to create object. The mesh showed is all squashed because of vertices being Int16Array. So the question is how do I prepare mesh so that it appear normal?

**Comment by N8n5h** [comment]
I assume you have to compress the data  and then pass the scale factor similarly to how the exporter does it 
https://github.com/armory3d/armory/blob/0c9f65ee0b54facf9c260689e0525fc876c52a85/blender/arm/exporter.py#L1159

^ Compute the `scale_pos` via the bounding volume, and then multiply your mesh data by the inverse of that scale. 

You could also try modifying `Geometry` and `MeshData` from iron to support non compressed coordinates values.

**Comment by luboslenco** [comment]
Like N8n5h says 👍, some additional info:
https://github.com/armory3d/iron_examples/blob/master/triangle/Sources/Main.hx#L53
https://www.khronos.org/opengl/wiki/Vertex_Specification_Best_Practices#Attribute_sizes
