### ISSUE TITLE
Saves automatically when you Run player

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#174]
When you start a new file and click Run, and that file hasn't been saved yet, you get an error telling you to save the blender scene. When you open a blender scene from file and click Run, it automatically saves any changes and then begins building.

This isn't a bug but I think it would be safer if you didn't automatically save, and instead detect changes and then prompt the user to save. I was trying to figure out a bug, deleted a mesh and clicked Run and it resaved the file so I'll have to add it back, lol

**Comment by luboslenco** [comment]
Please disable *Save on Build* manually in *Blender - User Preferences - Add-ons - Armory*. There are still occasions when Armory goes as far and crash the whole Blender down, so I left it on by default for now.
![pref](https://cloud.githubusercontent.com/assets/3685704/26025799/b694093c-37ef-11e7-9549-11f4088d9ac8.PNG)
.

**Comment by fractalfederation** [comment]
Thanks!

**Comment by luboslenco** [comment]
Will eventually make it off by default.
