### ISSUE TITLE
Screen Orientation aspect bug

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1748]
When screen orientation sensor is activated for the app, screen aspect is not updated. I don't know about other platform that change screen orientation. A workaround on this is to use "Set Camera" to make the aspect looks right, but is not possible to get the information of sensor i guess, so updating the camera every frame is not a good idea. Maybe updating the camera when screen orientation is changed should fix it for every platform.

Edit: i made a test with resizable screens on pc. In the past i experienced the same aspect issue but i couldn't
reproduce it now. I don't know if this was fixed in some update but i will investigate it more to track the issue

**Comment by Sanva** [comment]
Maybe you are simply forgetting to activate *Resizable* in *Render Properties → Armory Project → Window*?

![armory_window_props](https://user-images.githubusercontent.com/911204/88281959-e4b88b80-cce8-11ea-918a-af8d62bfabbd.png)

With it active you can resize the window and it simply works fine... not really sure about what it does — but without activating it, you can also resize the window [1] but it makes the graphics stretch / shrink. And this behavior translates directly to Android, considering the change of screen orientation like a *window* resize.

[1] At least in Linux — that would be the real error, I think.

**Comment by knowledgenude** [comment]
Okay, I will test it more with some exports and reopen if i find something. Thank you, @Sanva !
