### ISSUE TITLE
Build success! Krom.exe crashes, Browser sort of works, Electron has black screen

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#175]
My scene is pretty complex. It has 3.1 million verts, 5.3 million faces and 6 million tris.

With Krom runtime, it compiles without errors (progress!) but the Krom.exe stops responding and crashes. It was using 2.4 GB of RAM.

With Browser, it compiles without errors but looks like this:
![screen](https://cloud.githubusercontent.com/assets/12836886/26027991/bd3fe986-37e5-11e7-97a3-a5ebd2b7305a.png)

The ceiling and floor are planes. The floor is a carpet image texture and the ceiling is just a white diffuse shader. Not sure why they aren't showing up. The white stuff is suppose to be glass. The couches are suppose to be diffuse shaders with image textures, but it looks weird, they are glossy for some reason.

With Electron runtime, the screen is solid black and then turns white. Waited awhile, never loaded.

**Comment by luboslenco** [comment]
Oh my! Would be curious why Krom goes down since Browser runtime works.

Missing floor and ceiling - try to check *Force No Culling* in *Properties - Camera Data - Armory Render Props*. If that helps then flipping  geometry normals should do.
<img width="373" alt="nocull" src="https://cloud.githubusercontent.com/assets/3685704/26028049/2686abea-3819-11e7-9e66-1bf819a05819.png">

Glossy couches - not sure exactly, if you are running git version you might try to switch *Camera Data - Armory Render Path - Lighting* to *Cycles*. (I will try to properly explain this in the next release notes)

<img width="382" alt="cyc" src="https://cloud.githubusercontent.com/assets/3685704/26028146/d75eee9a-381a-11e7-99b6-69385f5f8d60.png">

**Comment by luboslenco** [comment]
For glass - does it work at all when you use Armory PBR node and lower opacity value? It shouldn't be all white.
![glass](https://cloud.githubusercontent.com/assets/3685704/26028225/7488936e-381c-11e7-8937-93caccf9e6d8.jpg)

**Comment by fractalfederation** [comment]
I did Lighting to Cycles and Force No Culling. Here is a video:

https://youtu.be/6CKSYNMHLWs

**Comment by fractalfederation** [comment]
Also it looks like some of my objects are getting moved. They are in the right place in the viewport but when flying around in Browser runtime, the four jars for example, are on the floor.

**Comment by luboslenco** [comment]
Can you isolate those jars into blend so I could take a look? (likely with parent object if any)

**Comment by fractalfederation** [comment]
[jars.zip](https://github.com/armory3d/armory/files/998929/jars.zip)

Just the jars and a plane. In viewport, jars are above the plane, after compiling Browser runtime, the jars moved.

**Comment by luboslenco** [comment]
Jars be back in the right place now https://github.com/armory3d/iron/commit/e648f1c8de8dda3d2a62e7848a887121975816e6.

About the Krom crash - can you make a scene backup and delete parts of scene to see when it boots up? Maybe it has trouble processing some texture/material/mesh. When running in browser, is there any error message in Developer Console? Browser runs slower and is no capable of voxel gi.

**Comment by fractalfederation** [comment]
Flipping the normals for the ceiling seemed to do the trick but didn't work for the floor. The floor is a single plane, with carpet material applied to some areas and another material applied to the floor of the kitchen and bathrooms. 

[test.zip](https://github.com/armory3d/armory/files/999259/test.zip)

Seems to load with WebGL and Vulkan, the DirectX options are all having issues, basically vertical bands across the screen instead of the shape of the mesh.

**Comment by fractalfederation** [comment]
![apartment09](https://cloud.githubusercontent.com/assets/12836886/26035950/165de94c-38a3-11e7-820b-53fdedbeb869.png)

This is what it looks like with Cycles. One of the other issues is when I use the Glossy texture, it reflects the skybox/HDR image, it's like it's ignoring the walls. Also the walls and ceiling, which are simple Diffuse nodes, are semi-transparent. I switched the walls/ceiling to the Armory PBR node and that worked.

**Comment by luboslenco** [comment]
*"One of the other issues is when I use the Glossy texture, it reflects the skybox/HDR image, it's like it's ignoring the walls."*

For Armory to know about the surrounding geometry, Voxel Global Illumination needs to be enabled. There are finally some examples now showing it off in use:
https://github.com/armory3d/archviz_templates
