### ISSUE TITLE
About some openned issues

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1753]
Hi, @luboslenco. 

There is some issues already "solved" or non sense that still openned. I wonder if i can mention you or someone that can close them to reduce the amount of issues. If you think that this is not necessary i am ok. Also i can mention on repetive issues (taking in consideration the most detailed report)

**Comment by MoritzBrueckner** [comment]
Also, there are a few issues that could have the [good first contribution](https://github.com/armory3d/armory/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+contribution%22) label to give some issues that are easy to fix/easy to implement more attention :)

**Comment by luboslenco** [comment]
Sounds good to me, @knowledgenude @MoritzBrueckner you should be able to close and label issues after accepting the invite. 🙂

**Comment by MoritzBrueckner** [comment]
Oh, that's good to hear :) Thanks for your confidence!

**Comment by knowledgenude** [comment]
Ok, @luboslenco i will do it. Thank you for confidance too!
