### ISSUE TITLE
[hl] RigidBody doesn't work if using Covex Hull or Mesh as shape for collisions

### ISSUE THREAD

**Issue by Sanva** [armory3d/armory#1756]
**Description**
RigidBody doesn't work in C targets if using Covex Hull or Mesh as shape for collisions.

**To Reproduce**
Use some basic setup with a cube resting over a plane. If shape is Covex Hull or Mesh it will work wrong, as if the collisions system where using a very little shape or something like that.

Krom:

![cube-good](https://user-images.githubusercontent.com/911204/86456959-3b066000-bd23-11ea-99c5-4cf7b457c44d.png)

Linux (Hashlink/C):

![cube-weird-position](https://user-images.githubusercontent.com/911204/86456975-40fc4100-bd23-11ea-96b8-35a7883c74b4.png)

**System**
Blender: 2.82.7
Armory: Git version.
OS: Linux Mint 19.2 (linux 4.15.0-101-generic x86_64)
Graphics card: NVIDIA Quadro M2000M 4 GB

**Comment by Sanva** [comment]
This is fixed in https://github.com/Kode/Kha/commit/39e022b2bf921aedfb651954af6ead4a38d09ce4 .

**Comment by onelsonic** [comment]
Hi @Sanva thanks for mentioning it.
When I have some time I will check your Kha repo and do some new tests on Android.
Thank yo[u

**Comment by onelsonic** [comment]
Hi @Sanva, so I had to use the Kha branch of Armory and copy the latest Kha repo over it to overwrite it.
...and it works now, the bullet physics is acting correctly on Android, with the same behavior as on the html5 JS target.
Nice fix 🥇 👍 
Not sure how often it is updated, but the repo of Kha for Armory should be updated for the next monthly packaged download @luboslenco

Nice work!
