### ISSUE TITLE
Adding Cloth/Soft body to an object returns an error

### ISSUE THREAD

**Issue by Venom3456** [armory3d/armory#1760]
**Description**
Adding a cloth / soft body modifier to an object causes the armory player to return these error messages.
To be completely honest, I am just getting started with armory and I've wanted to check whether the engine is capable of usual blender cloth physics (as some video previews have shown to be true). However, even something as simple as the soft body example project causes it to throw errors for me.

![ubpWOD4](https://user-images.githubusercontent.com/67861698/86531722-fc5bdb80-bec3-11ea-90ee-b5427fb0858e.png)

**System**
Blender: 2.82
Armory: 2020.5/2020.6/2020.7
OS: W10
Graphics card: RX 5500 XT

**Test File**

[test.zip](https://github.com/armory3d/armory/files/4874834/test.zip)

**Comment by MoritzBrueckner** [comment]
Hi, this has been fixed in #1755, thanks for reporting though

You should update to the latest Git version (in the Blender user preferences > Addons > Armory)
