### ISSUE TITLE
Bad performance when using many objects (even when linked)

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#1773]
**Description**
When using many objects at a time the performance suffers greatly, even though if the objects are joined into one the performance is fine. Linking object data does not seem to have an effect other than reducing export time.

**To Reproduce**
Example: Create many cubes using some array modifiers. Duplicate that object, apply the modifiers and make all cubes unique with tab -> p -> loose parts. Link their object data with Ctrl-L and set their origins to their geometries. Compare the framerate when showing only the object that is many cubes, and only showing the objects that are many cubes.

**Expected behavior**
The performance with multiple objects to be only slightly worse. In my test scene I get ~300FPS with them being one object and ~30FPS with them being multiple, which is a 10x difference. Not good for any game that wants to use biggere scenes where assets are reused.

**System**
Blender: 2.82
Armory: latest git
OS: Win 10
Graphics card: GTX 1060
(you can shift click the many objects parent render button to hide all cube objects from render)
[objectPerf.zip](https://github.com/armory3d/armory/files/4941395/objectPerf.zip)

**Comment by Simonrazer** [comment]
Disclamer: I do not really no what I am talking about here, I just try to help. Sorry if it is totally useless.

I read that "Mesh Batching" is used to combine the drawing of many static meshes into one Draw call. (https://docs.unity3d.com/Manual/DrawCallBatching.html). When I turn on "Mesh Batch" for this test Scene and put it in RenderDoc, It appears to me (an utter noob) that there is still a lot of stuff done for each object individually!
https://youtu.be/Acfe1zfE6q0
So I guess Mesh Batch not working properly results in bad performance?

**Comment by knowledgenude** [comment]
Good news is that Instanced Children, Batch Materials and Batch Meshes are working very well now in current Git version. I got 60 fps instancing or batching more than 3500 cubes. Tested in Open GL / AMD hardware.

If this still a issue for someone, please reopen :+1:
