### ISSUE TITLE
Error publishing with Asset Compression option

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/armory#1779]
**Description**
If you enable this option, then when publish, for example, in HTML5, the scene will be unloaded as "Scene.arm", but the engine is looking for the "Scene.lz4" file.
I assume there is a similar problem for other platforms.

kha.js:
![Error_asset_compression_part](https://user-images.githubusercontent.com/7114353/88962561-465f9380-d2af-11ea-9e0f-66d0c00c4f5d.jpg)

**System**
System
Blender: 2.82
Armory: git (from 28 July)
OS: Win 10

**Comment by MoritzBrueckner** [comment]
That's interesting. It looks like the scene file is just not exported when asset compression is enabled:

https://github.com/armory3d/armory/blob/ef7ca82978a6910284207407d02749b73985e054/blender/arm/utils.py#L24-L27

I wonder why this was not noticed until now. @luboslenco What was the reason to add a `pass` statement in `utils.write_arm()` in https://github.com/armory3d/armory/commit/8bccdd9879e0dc428fac59d617923e461e64fd3c? Was the lz4 export implemented somewhere else instead? Maybe I'm blind but I can't find it.

**Comment by luboslenco** [comment]
I recall there were some issues with .zip compression and the move to .lz4 is not finished. For Iron I plan to move in the lz4 encoder / decoder from [ArmorPaint](https://github.com/armory3d/armorpaint/blob/master/Libraries/formatlib/Sources/arm/format/Lz4.hx). For Blender side maybe the encode part could be ported from Haxe to Python.

**Comment by MoritzBrueckner** [comment]
Ok, thanks for the information! If you want I can try to port the lz4 encoder to python in a few weeks when I get more time.

**Comment by MoritzBrueckner** [comment]
Hi @luboslenco, how is the second parameter (`oLen`) of `Lz4.decode()` calculated? I want to test if the Python port works but I don't know how to call decode().

**Comment by luboslenco** [comment]
Hi, it's the size of decoded bytes:
```hx
var encoded = Lz4.encode(bytes);
var decoded = Lz4.decode(encoded, bytes.length);
```
The original size has to be stored somewhere along the encoded bytes.

**Comment by MoritzBrueckner** [comment]
Small status update: I got it working (and after a nasty bug with shifting unsigned integers it now works for all files I've tested), **but there is a problem**: The current Lz4.hx doesn't work on static targets due to the use of `js.lib.Int32Array` and `js.lib.Uint8Array`. Kha has an Int32 array (without a `fill`-function but that's not a big problem) but there is no Uint8 array. Are there other alternatives?

**Comment by luboslenco** [comment]
There is `haxe.io.UInt8Array` as well but the best way would be to just add `kha.arrays.Uint8Array` into Kha, I recall Robert mentioning he would not mind to include additional array types.

**Comment by MoritzBrueckner** [comment]
[Done](https://github.com/Kode/Kha/pull/1247). Hopefully everything is correct (this is my first "bigger" commit on the Kha repo).

**Comment by MoritzBrueckner** [comment]
@luboslenco Could you please update the Kha and khacpp submodules so that we can finish the work on this? It's all done and just needs to be committed. Thank you

**Comment by luboslenco** [comment]
Done!
