### ISSUE TITLE
Forward Low rendering doesn't work on mobile + browser artefacts

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#178]
Forward Low rendering doesn't seem to work on mobile (there's just a black canvas). Tried on OnePlus Two phone which webglreport.com says is WebGL 2 capable. None of the demos from the download page work either on mobile. And my project looks like this in the browser (you can see the trail, cause the globe is animated - it looks like it isn't properly clearing the screen in the render loop):

![forward-low-bug](https://cloud.githubusercontent.com/assets/1177508/26056428/9c7e1b1e-3975-11e7-918b-d48f31f71762.png)

Plus some things are not rendered at all (like the transparent clouds and the Sky world shader).

And here's the project:
[bonn.blend.zip](https://github.com/armory3d/armory/files/1000968/bonn.blend.zip)

I'm on Ubuntu Gnome 17.04 if that has anything to do with it.

**Comment by razvanc-r** [comment]
Oh! It seems that I was lying. The demos from the download page are working actually, but I need to "activate" them by tapping the canvas element, otherwise it just stays blank (and black). On the other hand, the project I uploaded here unfortunately doesn't render even if I tap on the canvas element :/.

Furthermore, the demos from the download page... they are viewable as explained above, but they are super super slow, like 1-2 FPS :)

**Comment by luboslenco** [comment]
Mobile (forward) preset should actually work on mobile browser now.
