### ISSUE TITLE
edit script button got misdirected to wrong file location 

### ISSUE THREAD

**Issue by poonilli** [armory3d/armory#1787]
Thank you for reading

**Description**
i am new to armory and when i clicked edit script a ms window popped up and ask what program to open after looking around for a while or maybe 10 seconds idk i clicked notepad. think i could change it later

i can not find the option to change it please help

**To Reproduce**
idk install fresh then see because i have not sone much

thank you
 bpy.context.space_data.context = 'MODIFIER'
bpy.context.space_data.context = 'VIEW_LAYER'
bpy.context.space_data.context = 'OUTPUT'
bpy.context.space_data.context = 'RENDER'
bpy.context.space_data.context = 'TOOL'
bpy.context.space_data.context = 'VIEW_LAYER'
bpy.context.space_data.context = 'OUTPUT'
bpy.context.space_data.context = 'SCENE'
Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

bpy.context.scene.arm_traitlist_index = 0
bpy.context.scene.arm_traitlist_index = 0
Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

Traceback (most recent call last):
  File "D:\ArmorySDK//armory/blender\arm\props_traits.py", line 300, in execute
    sf = open(source_hx_path)
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ArmorySDK//armory/Sources/armory/trait/.hx'

location: <unknown location>:-1

bpy.context.space_data.recent_folders_active = 1
bpy.data.window_managers["WinMan"].addon_support = {'TESTING'}
bpy.data.window_managers["WinMan"].addon_support = {'COMMUNITY'}
bpy.data.window_managers["WinMan"].addon_filter = 'User'

**Comment by MoritzBrueckner** [comment]
Hi, thanks for reporting this!

It looks like you somehow achieved to create a trait with an empty name, usually that should not happen. Could you please describe as detailed as possible what exactly you did (what kind of trait did you use? Bundled? Haxe?). I can't reproduce it.

**Comment by poonilli** [comment]
thanks for the response
i was following this video https://youtu.be/7JLhQgQLX3g?t=178
[https://i.ytimg.com/vi/7JLhQgQLX3g/maxresdefault.jpg]<https://youtu.be/7JLhQgQLX3g?t=178>
Scripting Basics -- Armory 3D Tutorial Series<https://youtu.be/7JLhQgQLX3g?t=178>
In this tutorial we are looking at the two ways to script in Armory. First we will look at attaching traits and using the Haxe programming language. Then we ...
youtu.be

 and when i clicked edit script a window popped up asking how i would lik to open it. i closed the window a few times, then thinking i could just attach it later to what ever editor i wanted to use later i clicked open with notepad. it opened. then i was now what? so i went back through to try to find the option to change it to be opened differently and could not find one. i turn off program without saving, and opened a previous version of the scene. clicked edit script got and error msg.  then i tried again to find an option to change it and found the report a bug button.
 thanks for your time
 tony
 instagram.com/poonilli/


________________________________

**Comment by MoritzBrueckner** [comment]
**Regarding the editor:**
That is a Windows setting which you have to change in your system settings. Windows didn't know how to open a Haxe file and was asking you about how to open it. Now it knows it so it doesn't ask you anymore, that's why you have to change it in the OS preferences. There is also a setting in Armory's user preferences where you can set the editor Armory should use (regardless of the OS setting). Make sure `Show Advanced` is enabled so that you can see the settings:

![2020-08-05 00_09_17-Blender Preferences](https://user-images.githubusercontent.com/17685000/89350256-fbc78800-d6af-11ea-8d34-2d92a7a49fe6.png)



**Regarding the error message:**
I still cannot reproduce it. What is the name of the trait you try to open? Could you please post a screenshot of the trait panel?

**Comment by knowledgenude** [comment]
Please, reopen if your problem was not solved :+1:

**Comment by poonilli** [comment]
sry i tried to get it working and failed. then i downloaded https://store.steampowered.com/app/876160/Occupy_White_Walls/?utm_source=kultura&utm_medium=art&utm_campaign=daisy&utm_term=oww
and im more of a map builder anyways so this has all my interest
thanks
 for your time sry i didnt fix the prob
 tony
instagram.com/poonilli/
[https://cdn.cloudflare.steamstatic.com/steam/apps/876160/capsule_616x353.jpg?t=1596756929]<https://store.steampowered.com/app/876160/Occupy_White_Walls/?utm_source=kultura&utm_medium=art&utm_campaign=daisy&utm_term=oww>
Occupy White Walls on Steam<https://store.steampowered.com/app/876160/Occupy_White_Walls/?utm_source=kultura&utm_medium=art&utm_campaign=daisy&utm_term=oww>
To say it’s a PC sandbox-building, AI-driven MMO where people play with Art, developed by folks who are really into architecture and abstract characters… would be a bit of a mouthful.
store.steampowered.com

________________________________
