### ISSUE TITLE
Delta time is not updating

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1799]
When i print delta value in console with 60 fps, then the delta is 0,0166. But when i force a frame drop to 30/35 fps, the delta keeps in 0,0166.

**Comment by BlackGoku36** [comment]
That is because I think delta time is based on gamelogic loop. (gamelogic loop and rendering loop are diff).
Try doing adding some heavy maths (in update func) and see if it changes.

**Comment by knowledgenude** [comment]
Thanks. I will try this

**Comment by Sanva** [comment]
@knowledgenude if I understand it right, delta time is the elapsed time since the last update.

More information:

- Relevant video about delta time by @lewislepton → https://youtu.be/i65WiX4uHXs
- Wikipedia article linked in above video → https://en.wikipedia.org/wiki/Delta_timing

**Comment by knowledgenude** [comment]
Thank you too @Sanva , i forgot to close this :+1:
