### ISSUE TITLE
Set the "default" vector of Ray Cast node to the end point

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1800]
When Ray Cast is not detecting any object, the vector is something like 'infinite' or 'null', wich is an useless value. Maybe if the default coordinate is set to the end point, it would works better, as the end point is the limit of ray cast.

**Comment by MoritzBrueckner** [comment]
Hi, there is a reason behind this behaviour: if the end point was returned when nothing was hit, you wouldn't be able to differ between a hit and no hit. So `null` is not an useless value here :)

**Comment by knowledgenude** [comment]
Hi @MoritzBrueckner , I think that giving the end point would be more suitable for the ray cast purpose, and we can use the object output to get the 'null' value. Maybe also storing the last normal vector received also would be a good idea, but of course there is a bit longer way to do both :) Anyway if you think that trough the code view is non sense to get the end point there, i don't see problems with that too! ^^

**Comment by MoritzBrueckner** [comment]
Oh indeed, I wasn't thinking of the object output. Having the endpoint then as the output value might be nice to have, but if so, it needs to be documented to not confuse the users

**Comment by knowledgenude** [comment]
Or maybe a new node that receives only "valid" data (not null or infinite) and use a default value if receive null? Maybe this can also be used in future cases. What do you think is better? Also in the vector/normal output can have "Valid Vector" or "Valid Normal" or some other name that expose wich exaclty data will be returned?

About the documentation, i am wondering if i do some full template with nodes and write every step to reach that. If the ray cast node is changed, i can use it to update its part on the wiki
