### ISSUE TITLE
No information in the documentation on where to obtain a VirtualButton for the virtual input

### ISSUE THREAD

**Issue by SeleDreams** [armory3d/armory#1801]
Hello, I am writing a game using armory3d and the iron library and currently I'm having some issues when trying to implement input using virtual input on the iron side of things
![image](https://user-images.githubusercontent.com/16335601/90075952-e7fad200-dcfe-11ea-9fc8-32b1074eb26c.png)

the set function seems to require not a keycode or anything but a virtualbutton, however I didn't find any way to get a virtual button for the input I want, is there any function made to allow it such as getting the virtual button for a keycode or controller ?
it also seems like virtual input was only implemented for buttons while it could benefit a lot from working with axes as well

**Comment by luboslenco** [comment]
The following should work, however I believe only buttons are implemented like you mention.
```hx
keyboard.setVirtual("my_key", "e");
mouse.setVirtual("my_key", "left");
// ...
if (Input.getVirtualButton("my_key").started) {}
```

**Comment by SeleDreams** [comment]
I see, thanks for the help
