### ISSUE TITLE
Weird issue with W / S key inputs

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1802]
I tough that this was a problem related to the gate node, but not. There is some bug related to W/S keys (don't know if this is a Kha issue).

I realized that the problem is also in Armory viewport:

[test.zip](https://github.com/armory3d/armory/files/5184880/test.zip)

A test you can do is: 

Hold A + D, the camera will not move.

Hold W + S, the camera will not move.

Hold A + D and press W or/and S, the camera will not stop. Always will go forward or backward depending on the input.

Test with a custom node: [movement_alpha.zip](https://github.com/armory3d/armory/files/5211983/movement_alpha.zip)

**Comment by MoritzBrueckner** [comment]
@knowledgenude Did you find a solution for this? It's a pretty weird bug.

**Comment by knowledgenude** [comment]
I've openned another issue about the gate nodes. With the example i send in the other issue, this issue is not present for me. Can you test it?

**Comment by knowledgenude** [comment]
I am reopening this, it is not related to Gate Node.

**Comment by knowledgenude** [comment]
This also happens in Blender walk navigation. Probably is related to https://gaming.stackexchange.com/questions/342039/w-a-s-d-keys-and-shift-arent-working-together
