### ISSUE TITLE
Clamp node

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1806]
Blender's one: https://docs.blender.org/manual/en/dev/render/shader_nodes/converter/clamp.html

I don't know if we can achieve this with minimum and maximum in math node

**Comment by BlackGoku36** [comment]
You can, clamp is basically: `Math.min(Math.max(min, val), max)`

**Comment by knowledgenude** [comment]
@BlackGoku36 Its because we have Clamp Vector. Taking in consideration that nodes get more and more confuse when its amount grow up, the better idea is to just have a separated node just for common use. I think this also can improve the performance of the nodes trait
