### ISSUE TITLE
Get Mouse Lock

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1807]
To easily troggle like Lubos example here: https://forums.armory3d.org/t/light-switch-logic-node/1107

**Comment by BlackGoku36** [comment]
Not sure what you meant as link doesn't have anything related to mouse. Mouse lock node already exist

**Comment by knowledgenude** [comment]
@BlackGoku36 , we have **Set Mouse Lock**. Get Mouse Lock is more for don't need an extra boolean variable just to get this info
