### ISSUE TITLE
Changing render engine causing issues

### ISSUE THREAD

**Issue by fractalfederation** [armory3d/armory#181]
Using the p10a_win64 build.

Double click blender.exe
Armory selected by default
Click File > New > Reload Startup File
Loads default cube with Blender Render selected as Engine
Select Armory for engine, Armory Player and Armory Project show up with their options in the Render tab
Switch Engine to Cycles Render
Now there are TWO Cycles Render options listed in the drop-down
Switch Engine back to Blender Render
Armory Player and Armory Project still present

I also had the Armory Player and Armory Project show up, but when expanding them, they were completely empty, no options displayed. I haven't figured out the exact steps to get that to happen again.

**Comment by luboslenco** [comment]
Should be getting resolved now by https://github.com/armory3d/armory/issues/204#issuecomment-322910336.
