### ISSUE TITLE
Question about particle system

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1812]
Hey @luboslenco 

I wanted to try and improve the particle systems a bit. But I could not find where the particle positions are calculated and updated at each frame. I know that gravity and mass of particles are initialized [here](https://github.com/armory3d/iron/blob/0f6911c6a64abeda727abd1cd2a9865e73513fdd/Sources/iron/object/ParticleSystem.hx#L43). But where are the positions of each particle calculated w.r.t time? It does not seem to be happening [here](https://github.com/armory3d/iron/blob/0f6911c6a64abeda727abd1cd2a9865e73513fdd/Sources/iron/object/ParticleSystem.hx#L71) either.

Thanks in advance.
QC

**Comment by luboslenco** [comment]
Hey, the particle positions are calculated in the shader, see https://github.com/armory3d/armory/blob/master/blender/arm/material/make_particle.py.
