### ISSUE TITLE
On Local Axis checkbox for Location input in Apply Force/Impulse At Location

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1813]
I really don't know why this nodes uses the location relative to the object origin. I think this need to be applied in world location, but even trying to use the relative location, the node don't take in count the object rotation too.

Here is the example file: 
[CarPhysics.zip](https://github.com/armory3d/armory/files/5114912/CarPhysics.zip)

**Press 'Space' to accelerate the car**

It works good if the car is not rotated, but if you rotate the car with the PhysicsDrag, you will able to see what i am saying. I think that the **On Local Axis** checkbox is not working.

**Inside the yellow frame**
The properties X, Y, Z are just coordinates that i put to simulate the ray cast start point relative to car origin. You can remove it and put the vector from ray cast start point and disable 'On Local Axis', but it will work even worst.

**Comment by QuantumCoderQC** [comment]
Hi @knowledgenude 

I devised a simple test to check this issue. The apply force node seems to be working as expected.

About the test: I apply force to a cube on the positive y-axis when 'space'  is held. Then I rotate the object and check which direction it moves depending on whether the local axis flag is set. 

Here is the blend file thas has a small "how-to" in it. Try and let me know if this solves the issue.

[ApplyForceOnLocalAxis.zip](https://github.com/armory3d/armory/files/5115274/ApplyForceOnLocalAxis.zip)

**Comment by knowledgenude** [comment]
Hi @QuantumCoderQC , thanks for the reply

Apply Force works properly, the one i said is **Apply Force At Location**:

[ApplyForceOnLocalAxis.zip](https://github.com/armory3d/armory/files/5118415/ApplyForceOnLocalAxis.zip)

Just use space to apply the force and rotate the object. The red arrow is the part to go up, no matter the object rotation and location. It works only before you change the cube location in the world, but i really can't tell what is happening here. Maybe there is some issue with the object transformation  in both nodes (force/ impulse at location behaviours the same).

This two nodes can be used to make hovering objects, see the example in unreal: https://www.youtube.com/watch?v=ko6lDSSNhV8

**Comment by QuantumCoderQC** [comment]
HI @knowledgenude, I believe the physics or the nodes are not the issues here. The application/understanding is the issue. 

The `location` attribute is the location with respect to the `object `to which force/impulse is applied. **Not** with respect to the `world location`.  The `location` attribute defines the point in space where the force **originates** from, and is described with respect to `object` co-ordinates. 

The `force` attribute defines the magnitude and direction of the force in the `world` coordinates. The `on local axis` checkbox describes if the direction of this force is defined with respect to `object rotation`. The implementation of the node can be found [here](https://github.com/armory3d/armory/blob/0d6422f77a485caba5f47c10bd3d54efbaa1347f/Sources/armory/logicnode/ApplyForceAtLocationNode.hx#L23)

To solve your issue, I will provide the node setup here:
[ApplyForceOnLocalAxisAtLocation.zip](https://github.com/armory3d/armory/files/5131260/ApplyForceOnLocalAxisAtLocation.zip)

**Comment by knowledgenude** [comment]
Sorry for the long discussion about this, @QuantumCoderQC . I will represent with images because i can't express this very well with my English. I think that the issue is that the **Location** must consider the object axis too, look why:

Here i leave the force origin location in 0,0,0, then the force is becoming from the middle of the object:

![test](https://user-images.githubusercontent.com/63247726/91338443-533aae80-e7ab-11ea-8b80-33e1d468f870.jpg)

Here i leave the force in 0, 5, 0 (in the front of the rectangle)

![test2](https://user-images.githubusercontent.com/63247726/91339010-39e63200-e7ac-11ea-9a9f-a0d90fc184cc.jpg)

This is pretty much what i want with this nodes, the issue comes when i rotate the rectangle:

![test3](https://user-images.githubusercontent.com/63247726/91339048-48cce480-e7ac-11ea-8d0a-c04e9d60b76f.jpg)

In this case, the force keeps in +Y as it should, but not takes in count the rectangle rotation. I was expecting that **Location** have an **On Local Axis** too, because in 3d space this nodes will work only with objects that are not rotated.

**Comment by knowledgenude** [comment]
This do the work: 
![test](https://user-images.githubusercontent.com/63247726/91349846-44a8c300-e7bc-11ea-8b8c-08657a2733f7.jpg)
[ApplyAtLocation.blend.zip](https://github.com/armory3d/armory/files/5132523/ApplyAtLocation.blend.zip)

Thanks for your help :+1: 

I will leave this open just to help other people trying to do that
