### ISSUE TITLE
Scene 4 manual example crashes to desktop (ooooonce again!)

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#182]
Hello Lubos.

In January I had this issue:
https://github.com/armory3d/armory/issues/113

which was successfully solved. Unfortunetly I could not test the engine much more. Finally I've managed to get some time to return to Armory a little. And the exact same error has returned.

This time, I'm on Linux Ubuntu. I have an Nvidia 1060 with 375.39 in my PC.
I've tried to repeat the solution but when I go to Armory/armsdk/armory/tools/cmft/cmft_new.exe to rename it, I've just found that there is no 'cmft_new.exe' at all. It's directly without the '_new'.

Also, I'm on linux, therefore I think touching the executable will not do anything.
Any fix you could give me?

PD: Not crashes to desktop.
Directly when rendering I have this.
https://cloud.githubusercontent.com/assets/12383027/21958134/99eca5ce-daa6-11e6-9398-8d137929d3b9.jpg    <------------ The jpeg used is from the previous one, cos I'm lazy.

EDIT:
Ok. The linux version.

![new error](https://cloud.githubusercontent.com/assets/12383027/26278991/8920b0d6-3da8-11e7-9bb3-197cbfec7ca3.png)

Also. It happens when I try to use the environment. I have repeated the tutorial step by step, rendering on every step, and it happens at the moment I use the background environment.

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Heyo!

The '_new' is the default one now. Yes, cmft is used for processing environment maps. Can you launch Blender from terminal and see any potential errors? Not sure if this is still related to cmft binary itself or not, maybe it reports something useful there. I guess the same happens when you do *Clean Project* and uncheck  *Properties - Render - Armory Player - Advanced - GPU Processing* option? That would indicate cmft is fine and something else is failing.

**Comment by ja-moli** [comment]
I unchecked GPU processing and did a clean project. Same happens.
Terminal says this:

![new error 2](https://cloud.githubusercontent.com/assets/12383027/26279276/86a62492-3daf-11e7-9274-172831a65d76.png)

**Comment by luboslenco** [comment]
Do you get this same error on scene 4? Could you send me or attach your hdr map? Maybe I will be able to reproduce.

**Comment by ja-moli** [comment]
It's solved.
I've tried Scene4 from github and worked. I have seen that as an environment map it has an .hdr image.
When you download the environment map from the website, http://www.hdrlabs.com/sibl/archive.html
you download a pack of images. Some are .hdr and some are .jpeg. I was using the .jpeg.

The manual, http://armory3d.org/manual/getting_started/scene4.html
doesn't specify you have to use an .hdr environment, so I could not imagine it.
If I try any hdr images, it goes well.

**Comment by luboslenco** [comment]
JPEG should work as well, so still a bug - thanks for discovery! Will take a look and fix. :)

**Comment by luboslenco** [comment]
Appears to also work fine for .jpgs now.
