### ISSUE TITLE
Cannot install solely via clone of armsdk - No Module Named 'start'

### ISSUE THREAD

**Issue by Clockwork-Muse** [armory3d/armory#1837]
**Description**
Attempting to follow the [steps for contribution](https://github.com/armory3d/armory/wiki/contribute) to a specified directory without having an existing armory installation or blend file yields:
>ModuleNotFoundError: No module named 'start' 

.... this at least _appears_ to be implied to work, although I may be misunderstanding something here.

**To Reproduce**
Clone the armsdk repository, or download the packaged tag, to an external directory.
Attempt to install it by pointing to the including `./armory.py` file in the base of the cloned repository.

**Expected behavior**
No error, sdk starts

**System**
Blender: 2.83.5, 2.90
Armory: 20.09
OS: Ubuntu 20.04
Graphics card: GTX 1080

<hr />

Note that in my real use case I can't install the package distributed via itch.io - I'm creating a dockerized development environment, and need an API/command line way to get the SDK.

**Comment by MoritzBrueckner** [comment]
Hi,

did you also clone the SDK's submodules with `git clone https://github.com/armory3d/armsdk.git --recurse-submodules`?
It's a bit unclear from the wiki, I will update it now :)

**Comment by Clockwork-Muse** [comment]
> did you also clone the SDK's submodules with `git clone https://github.com/armory3d/armsdk.git --recurse-submodules`?
It's a bit unclear from the wiki, I will update it now :)

In fact I did not!  Feeling little silly for not doing that.  Seems that was the issue.

(now to get the other necessary libraries...)
