### ISSUE TITLE
armorybench build failed

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#184]
armory preview 11. Build failed with bench2
*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
I pushed an update to [armorbench](https://github.com/armory3d/armorbench1/releases) for Build 11, can you try again? If you still get build failed then also throw me your console log to see what is wrong. Thanks!

(Also, get the latest preview 11a from itch if you are not running that already, should be all good to go for release now.)

**Comment by Xristoskr** [comment]
it work now
