### ISSUE TITLE
Object Output don't return the spawned object name

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1844]
Is not possible to know  the name of the spawned object, see the console:

[spawn_object.zip](https://github.com/armory3d/armory/files/5183509/spawn_object.zip)

**Comment by QuantumCoderQC** [comment]
I cannot confirm this issue.

I get the name of the spawned object. 

`armory.logicnode.PrintNode:13: Cube: Suzanne`

**Comment by knowledgenude** [comment]
@QuantumCoderQC , Suzanne is the object `to be spawned`, not the `spawned` object:

![screenshot1](https://user-images.githubusercontent.com/63247726/92502281-06f16480-f1d6-11ea-9ec8-1b08455cad87.jpg)

I was expecting something like: "Suzanne.001", "Suzanne.002", ...

I also would recommend to improve this node (it is really very useful). If there is some way to remove the `Transform` and implement `Parent` input and `Done` output would be great. But, if the `Transform` input is removed, a checkbox `Visible` must be included. This will leave the user to spawn the object invisible, apply the transforms/logic, and after, set the object visible again using `Sequence` node. If you think that this is a good idea, i will try this in the future. Now i don't understand about transforms and functions.

**Comment by QuantumCoderQC** [comment]
>>I was expecting something like: "Suzanne.001", "Suzanne.002"

`Suzanne` is the `Object`. It can be considered as a `Class`. An instance of `Suzanne` is also of type `Suzanne` (object instance of a class). This is the core of Iron and Armory 3D.

Having different nodes with individual actions is much better than having a single node do multiple actions. This is the principle behind node-based programming. Different actions can be added or removed as needed. Adding multiple actions in one node (such as spawning, parenting, setting visibility all in one node) reduces this flexibility and is also inefficient.

>>If there is some way to remove the Transform and implement Parent input and Done output would be great.

In this case, a `SetParentNode` can be used after `SpawnObject` since not everyone who spawns an object wants a parent to it.

>>But, if the Transform input is removed, a checkbox Visible must be included. This will leave the user to spawn the object invisible,

Adding a checkbox means adding an if statement in the code, which is inefficient. Instead, the `setVisibleNode` can be used after the `SpawnObject` node to achieve the same wherever required. 

>>Note: a good reason to spawn the object invisible is: think in a weapon being spawned, you need to parent it in the player, set its position, rotation, scale, etc. and set its visible.

This can already be done with a node config like this:
`SpawnObject -> SetVisibility(False) -> SetTransform -> SetParent -> SetVisibility(True)`

**Comment by MoritzBrueckner** [comment]
> I was expecting something like: "Suzanne.001", "Suzanne.002", ...
This is Iron's fault. Iron doesn't use unique names and yet it identifies objects by their name which in my opinion is a big flaw. Open the debug console and you will see multiple objects all having the same name.

**Comment by knowledgenude** [comment]
@QuantumCoderQC , i know that it is possible to remove the visibility after the spawn, but when you remove the visibility after the object is spawned, it will "blink", i don't know a better term for this. In this case, if there is some possibility to get the spawned object name (not the instance) to apply the transform and other stuff i mentioned, there is no additional tasks for the node (as transform input will not be in the node).

I talked about `Parent` and `Done` output because they are in the code here: `spawnObject (name:String, parent:Object, done:Object ‑> Void, spawnChildren:Bool = true):Void` Note that i don't know if `Parent` is to spawn the parent or to parent the spawned object.

Here is a node setup for the spawned weapon:

(Looks bigger but is more controllable)

![screenshot1](https://user-images.githubusercontent.com/63247726/92509251-563c9280-f1e0-11ea-8464-4fc53432440b.jpg)

If weapon is spawned visible, it will appear first in where it was spawned in one frame, and after will go to the correct location. This is what i mean by "blink".

But as @MoritzBrueckner said, it is not possible to get the spawned object name currently.

**Comment by QuantumCoderQC** [comment]
A solution/work-around for this is like this:

1. Add the following trait to current Scene:
`OnKeyboard(space) -> SpawnObject(Object_to_be_spawned)`

2. Add the following trait to the weapon/object to be spawned:
`OnInit -> setVisible(Flase) -> SetTransform -> SetParent -> SetVisible(True)`

This solves the `blink` problem for me. This also solves the issue of searching for an object spawned.

Here is a blend file where a 'Cube' is spawned at (0,0,0), made invisible, translated, parented, and made visible again on space bar press
[SpawnInvisible.zip](https://github.com/armory3d/armory/files/5190183/SpawnInvisible.zip)
.

**Comment by knowledgenude** [comment]
@QuantumCoderQC , also just disabling the object render  in the outliner will start invisible. The only problem is that we will can't clone objects that has not made in this parameter. 

We need to see if the function is implemented if set the spawned object visibility will work as well without blink in any FPS and platform, but probably will :) Anyway thanks in advance.

**Comment by MoritzBrueckner** [comment]
@QuantumCoderQC do you know if the logic frame rate can differ from the rendering frame rate? I somehow always thought that a node would block during its execution (probably because that was how scripts worked in the BGE back then).
Maybe (for the far future) a mutex-like node would be nice to ensure that a node group is executed in one render frame... Not sure if this is viable though.

**Comment by QuantumCoderQC** [comment]
@MoritzBrueckner I am not really sure about that as well. But I think they are independent, although I don't have an explanation for it.

**Comment by QuantumCoderQC** [comment]
@luboslenco Could you please clarify if the logic frame rate is independent of the rendering frame rate. Some people on Discord also discussed about this but were not sure.

Thanks
QC

**Comment by luboslenco** [comment]
No, if you halt the game in a trait / logic node the rendering will halt as well.

**Comment by MoritzBrueckner** [comment]
Ok thanks! Then the problem with the blinking might be that the transformation is applied a frame later?

**Comment by QuantumCoderQC** [comment]
@MoritzBrueckner yes, probably. But this won't happen if `on init` is used as input. At least in my case.

**Comment by knowledgenude** [comment]
The blink just happens if the first thing you do is not set the object invisible. If you simple spawn it in a location and after this set another location (in sequence) it will blink in the first location.

I also tested the @QuantumCoderQC example at 30 fps without blinking

**Comment by knowledgenude** [comment]
I can't see a need to get the object name. I tough that the object output were not functional, but i was wrong. I think is possible to use Set Name to give a name for the object in  some cases. Anyway, if there is any other reason to implement such functionality as you said, it is welcome.

I also would recommend to put this info in the Spawn Object description. I just don't do that because i don't have too much knowledge about the technical working of the nodes yet and my english is very poor.
