### ISSUE TITLE
deferred plus 

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#185]
traceback error simple cube scene 
![3](https://cloud.githubusercontent.com/assets/23359603/26578863/2b595f68-453a-11e7-8fdf-4c6aa74a3777.png)

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
This is still experimental only, will fix in next build - thanks for report.

**Comment by luboslenco** [comment]
Should now compile fine, although glitches will show up as it's not complete yet. Will keep improving.

Added new test at:
https://github.com/armory3d/armory_examples/tree/master/renderpath_deferredplus
