### ISSUE TITLE
Problems playing C++ runtime under Linux

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#186]
This happened playing "scene1".

In order to be able to compile I had to install some development dependencies (libxinerama-devel, alsa-lib-devel). After finishing the compilation the program was not able to find some resources:

<pre>
Initializing Haxe libraries
Starting Kore
Could not open file ../krom-resources/Material_001_mesh.vert.glsl.
Error [file_contents,../krom-resources/Material_001_mesh.vert.glsl]
</pre> 

System: Solus 2017.04.18.0 64-bit
GeForce GTX 1060 6GB/PCIe/SSE2

Note: I don't know if this was happening before. Under Linux I have only testes "Play in Viewport" and Krom runtime in the past. As things are getting stable, I'm starting to test new things.

**Comment by luboslenco** [comment]
Have to mention the dependencies somewhere..

Hm, about the crash - could you try again from clean build with 'Armory Player - Advanced - Compiler Cache' disabled?

It looks like I messed up shaders path for C++ builds when hitting Play button - with compiler cache option disabled, shaders are directly embedded into executable (which in turn forces recompilation when materials change, longer build times), so maybe that will do. Nonetheless, fixing the path to make it work properly at all times.

**Comment by arturjpv** [comment]
Yes, it works if I disable "Cache Compiler" in Advanced options. 👍

**Comment by luboslenco** [comment]
This should no longer cause trouble. Also added [note](https://github.com/armory3d/armory_docs/blob/master/platforms/linux.md) about the dependencies.
