### ISSUE TITLE
Strings inputs not working properly

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1862]
(Example removed due to wrong logic)

**Comment by QuantumCoderQC** [comment]
Hi @knowledgenude, I can confirm this issue. It is a more general issue concerning `string `inputs, so renaming the issue would be ideal.

As mentioned [here](https://forums.armory3d.org/t/git-version-engine-printnode-error/4214)

This does not compile:
![Capture0](https://user-images.githubusercontent.com/55564981/93030554-349a3b80-f624-11ea-94d6-b4775d33eff8.PNG)

Whereas this compiles and runs:
![Capture](https://user-images.githubusercontent.com/55564981/93030574-53003700-f624-11ea-9c8d-a9d122e6746b.PNG)

**Comment by knowledgenude** [comment]
@QuantumCoderQC thanks! I will rename the issue.

Anyway if someone have a problem with material variables i found a way to get it working: https://forums.armory3d.org/t/lets-create-more-files-for-tests-and-examples/4208/9
