### ISSUE TITLE
web version of tank games on Firefox in Ubuntu

### ISSUE THREAD

**Issue by razvanc-r** [armory3d/armory#187]
Firefox 53.0.3 (64-bit), Ubuntu Gnome 17.04, this happens with http://armory3d.org/demo/scene5/:

![screenshot from 2017-05-31 09-25-48](https://cloud.githubusercontent.com/assets/1177508/26620497/63944236-45e3-11e7-97cf-4ec816007877.png)

In Chromium it works as expected...

**Comment by luboslenco** [comment]
Can reproduce, investigating.
Seems like even the old [animation demo](http://armory3d.org/demo/animation/deferred/) is busted in latest Firefox..

**Comment by luboslenco** [comment]
Potentially (eg works for me now) fixed in: https://github.com/armory3d/armory/commit/0c0a9c6aaf32abb5a74809f3915b3ba887913af4

Demo updated: http://armory3d.org/demo/scene5/

**Comment by razvanc-r** [comment]
Yep, seems to have worked! What changed? :P

**Comment by luboslenco** [comment]
When reading depth buffer attached to a render target Firefox seems to nuke that even with depth writing and depth testing disabled. I hoped webgl2 would unify behaviour like this, down the road this could run a bit more efficiently in Chrome.
