### ISSUE TITLE
Krom (Windows) - Canvas doesn't work

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/armory#1882]
**Description**
![error_ui](https://user-images.githubusercontent.com/7114353/93742226-6dbf4680-fbf6-11ea-8685-19dae868b55d.jpg) ![error_ui_2](https://user-images.githubusercontent.com/7114353/93749266-4ff7de80-fc02-11ea-89d0-52ac855391b6.jpg)
Added _UI_ in both cases.

_Canvas_ doesn't work

Problems:
- _Debug Console_ does not work, sometimes it is displayed, but in most cases there is simply no text;
- if added to the _UI_, then it is not displayed, and sometimes the application crashes at startup (there is no error in the console).
Clear doesn't help.

I also experimented: it looks like the problem is in Krom, tk. everything works fine in the browser.
When trying to _Clean_ up a project, sometimes I get the message: 
_Armory Warning: Some files in the build folder are locked_
Perhaps this is my PC's problem.

**To Reproduce**
- In a new project, enable _Debug Console_.
- To have more instability, add _UI_ and bind to the scene.

**System**
Blender: 2.83.5
Armory: git commits 5bf0044 (from 18 Sep)
OS: Win 10

**Test File**
[debug_console.zip](https://github.com/armory3d/armory/files/5253965/debug_console.zip)
[debug_console_ui.zip](https://github.com/armory3d/armory/files/5253966/debug_console_ui.zip)

**Comment by MoritzBrueckner** [comment]
I have the same problem with Koui, so its not a particular issue with Zui. This might be related to the latest update of Kha/Krom for the ArmSDK.

**Comment by MoritzBrueckner** [comment]
Looks like this is fixed in the latest SDK to me :) @e1e5en-gd can you confirm this?

**Comment by e1e5en-gd** [comment]
Working =)
