### ISSUE TITLE
selecting objects is super slow

### ISSUE THREAD

**Issue by PostPollux** [armory3d/armory#189]
Just downloaded Armory build 11 under Linux Manjaro.
I then tested some of the example scenes and noticed, that selecting objects with right mouse click is super slow. If I open the same scene with my normal blender selecting in the viewport works fine.

Here a quick video for demonstration:
https://goo.gl/photos/b7Qe9PohE5aLH4Ln9

ps: when something is selected and I try to move the object by just dragging the arrows of the widget with left mouse button, it's also very slow. I think it's the same problem.

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Dang, tried on Ubuntu and seems to work as usual here. Will test on Manjaro too.

Is there any difference if you set Viewport Shading to Solid in Blender? Or if you switch selected engine to Cycles Render / Blender Render?

**Comment by PostPollux** [comment]
Nope. No difference if I select other engines or shading modes. It's always the same with this blender build.

**Comment by PostPollux** [comment]
Sorry! My fault. I found what caused the problem!
I'm running Blender on a Notebook. It has a nvidia graphics card. If I start Blender as it is it, always uses the onboard intel graphics card and not the nvidia one. 
To fix this, I have to start it with "optirun" which forces blender to use the nvidia graphics card. I had edited my starter on the desktop for my normal blender version, but of course I forgot to start the armory one with optirun.
Now when I use optirun everything works fine with armory!

You can close this issue.
Thanks anyway!
