### ISSUE TITLE
Armory Shader Editor

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1896]
If there is an easy and possible way to copy Blender Shader Editor, cut off unsupported stuff and have a own way to organize this nodes (following logic nodes style).

**Comment by MoritzBrueckner** [comment]
I'm not really sure, but wouldn't this break any viewport/Blender support?

**Comment by knowledgenude** [comment]
I also don't know. Is not possible to just edit a Blender/Armory shader trought this second editor? The only difference for me is the organization.

The reason i suggested it, is just to cutoff the unsupported features and leave us to organize these nodes. But if Armory is  intended to support every node in the shader editor, this can't be a good thing.

**Comment by MoritzBrueckner** [comment]
Yes it is possible to create another editor, with "breaking Blender support" I didn't meant breaking it directly but you would have to create two different materials AFAIK, one for Blender and one for Armory.

I think we should instead try to support more nodes and if there are nodes that are unsupported, we maybe should print a warning on export (but let users disable that particular warnings to not annoy them too much^^). Armory started as "[Cycles Game Engine](https://luboslenco.com/notes/)" and the philosophy was and still is to make working with Armory as seemlessly integrated into Blender as possible.

**Comment by knowledgenude** [comment]
Then i think is better to keep the things inside Blender shader editor, thank!
