### ISSUE TITLE
Project build error in Android Studio

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/armory#1899]
**Description**
Empty project build error:
`..\ArmorySDK\Kha\Backends\KoreHL\KoreC\vertexbuffer.cpp:43: error: undefined reference to 'Kore::Graphics4::VertexBuffer::stride()'`

**System**
Blender: 2.83.5
Armory: git, master (9ad68b5)
OS: Windows 10 64-bit
Graphics card: NVIDIA GeForce 930M

**Comment by MoritzBrueckner** [comment]
When compiling to HL/C, I get similar errors:

```
1>vertexbuffer.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol ""public: int __cdecl Kore::Graphics4::VertexBuffer::stride(void)" (?stride@VertexBuffer@Graphics4@Kore@@QEAAHXZ)" in Funktion "hl_kore_vertexbuffer_stride".
```

("Verweis auf nicht aufgelöstes externes Symbol" means "Reference to unresolved external symbol")

This is only one of 168 linker errors: https://pastebin.com/zVAbWXAL 😨 

@luboslenco do you have an idea where this could come from?

**Comment by luboslenco** [comment]
Hm, might be related to the recent Kinc change where Kore sources are no longer included by default. https://github.com/Kode/Kinc/blob/master/updates.md

**Comment by MoritzBrueckner** [comment]
I couldn't get it working using `project.cpp = true;` in both of the generated kincfile.js (probably because it's too late when the project is already built?). Is there some way to manipulate the kincfile via khamake?

**Comment by luboslenco** [comment]
HL compile fixed via https://github.com/Kode/Kha/pull/1251, and Krom crashes should also be resolved now via https://github.com/Kode/Kinc/pull/560. I have also updated https://github.com/armory3d/armsdk to point to the latest Kha, Kinc and Krom.

**Comment by MoritzBrueckner** [comment]
Thank you very much! I think this also fixed https://github.com/armory3d/armory/issues/1882.

However, there is still a crash with Krom, I opened a new issue about that with an example file + crash dump: https://github.com/armory3d/armory/issues/1904.

**Comment by e1e5en-gd** [comment]
Build and running =)
