### ISSUE TITLE
deleting a nonexisting Object freezes the scene

### ISSUE THREAD

**Issue by PostPollux** [armory3d/armory#190]
The "remove object" node freezes the scene if the target object doesn't exist.
I think it would be better if it does just nothing in that case.

Quick video capture:
https://goo.gl/photos/wejPT63EsRoRVavv9

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Ah, agreed. Should now be patched in https://github.com/armory3d/armory/commit/397699484103ddb70432a6cef911fbfd9c1e0382.

**Comment by PostPollux** [comment]
Cool! Thanks for fixing that quick! Love this project...

**Comment by PostPollux** [comment]
By the way, why is self destruct prevented? In some cases that's quite useful.

For example let's say I want to make a game with objects falling from the sky and I get points if i hit them with the mouse before they fall to the ground. So when I click them, they just get removed. In this case I would make an emitter that spawns those new objects and immediately adds the following trait to them:

![delete_self](https://cloud.githubusercontent.com/assets/9008901/26678395/aaed0846-46d0-11e7-974a-c9f728ed7681.png)

At the moment this doesn't work, it just does nothing... Any thoughts?

**Comment by luboslenco** [comment]
Was a silly limitation, fixed in https://github.com/armory3d/armory/commit/e65b6d119a886d950afe8e5098b02c29ca36740f and above trait should function properly now. :)
