### ISSUE TITLE
Krom crashes when printing a long string

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory#1904]
**Description**
Krom crashes when printing an object with the `Print` node or when printing a scene in the Iron code for example, so it's probably caused by string that's too long to print. If I print only a short substring, everything works.

**To Reproduce**
![Node setup](https://user-images.githubusercontent.com/17685000/94815022-5a805800-03fa-11eb-849a-3d198f6fd0e6.png)

**System**
Blender: 2.83.7
Armory: 2020.10
OS: Windows 10

**Test File + Crash Dump**
[CrashPrintObject.zip](https://github.com/armory3d/armory/files/5312334/CrashPrintObject.zip)

@luboslenco Out of interest: are the Kromx binaries already compiled from armorcore?

**Comment by luboslenco** [comment]
Thanks for letting me know - I have updated the binaries with a fix. It is built from the latest armorcore revision (with audio enabled in kincfile).

**Comment by MoritzBrueckner** [comment]
Thanks!
