### ISSUE TITLE
Canvas Editor not working

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/armory#1908]
**Description**
When I click on the _Edit Canvas_ button, I get a message in the console:
`Krom uses API version 5 but Kha targets API version 3. Please update Kha.`

**To Reproduce**
In a new project add Canvas and try to edit it

**Expected behavior**
Worked

**System**
Blender: 2.83.7
Armory: git, master (da1cf33)
OS: Windows 10 64-bit
Graphics card: NVIDIA GeForce 930M

**Comment by QuantumCoderQC** [comment]
I can confirm this issue

**Comment by luboslenco** [comment]
It should work now in the latest git version, updated builds at https://github.com/armory3d/armory_tools/commit/c76b8e3ec69811a17fa74e08d2cd6e88dc20989b.

**Comment by e1e5en-gd** [comment]
It works, thanks =)
