### ISSUE TITLE
Building Armory_p11b_win64 for Android fails

### ISSUE THREAD

**Issue by DualLayer** [armory3d/armory#191]
Hello,

i followed this tutorial http://armory3d.org/manual/getting_started/scene1.html.
Unfortunately when i try building it in Android Studio I get the following errors:

![androiderror](https://user-images.githubusercontent.com/20717445/26942631-0fd01bc4-4c83-11e7-8490-2d97595269f5.png)

This is the blend-file im using:
[main.zip](https://github.com/armory3d/armory/files/1061882/main.zip)

**Comment by luboslenco** [comment]
Heyo,

Can you try to open the Build Variants tab(below) and select armv7 target? You may need to clean up the project, but the build time should also go down considerably.

![bvar](https://user-images.githubusercontent.com/3685704/26943209-07168048-4c85-11e7-949b-a7c03e8b5910.png)

There is also this mobile variant of scene1 example, it will look terrible(it has 'restricted' materials set and disabled world nodes in render-path properties) but should be helpful as a minimal starting point:
https://github.com/armory3d/armory_examples/tree/master/scene1_mobile

**Comment by DualLayer** [comment]
Thanks for the fast reply!
I will try the example.
Selecting the armv7 target solved the issue.
