### ISSUE TITLE
Disable trait node

### ISSUE THREAD

**Issue by biustudio** [armory3d/armory#1912]
Hi, i think the title says it all but it will be cool to disable and enable trait with nodes
![image](https://user-images.githubusercontent.com/46801032/95066301-1f33a100-06fa-11eb-9fb8-d740838f9904.png)

**Comment by knowledgenude** [comment]
Is can do it using `Pause Trait` and `Resume Trait` nodes

**Comment by QuantumCoderQC** [comment]
Also checkout [Add trait to object](https://github.com/armory3d/armory/wiki/reference#add-trait-to-object) and [Remove trait](https://github.com/armory3d/armory/wiki/reference#remove-trait)
