### ISSUE TITLE
 Visual studio code + Kha Extension Pack + Armory - error

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#1916]
Using auto completion with armory and visual studio code.
with the Kha Extension Pack and getting the following error on windows10,
even when restarting Haxe with "F1" >  Haxe: Restart Language Server

-----------------------------------------
```
Haxe language server started
Haxe Path: haxe.exe
Using --server-connect
Haxe connected!
Listening on port 6000
Haxe Path: c:\Users\onelsonic\.vscode\extensions\kodetech.kha-20.4.0\Kha\Tools\haxe\haxe.exe
Using --server-connect
Haxe connected!
Failed - try fixing the error(s) and restarting the language server:

C:\engine\armorySDK2010\iron\Sources/iron/system/Lz4.hx:25: characters 8-29 : Type not found : kha.arrays.Uint8Array
```

**Comment by luboslenco** [comment]
Kha provided with the Kha Extension Pack is outdated. Check here on how to point the `kha.khaPath` to the latest one or the one provided with Armory: https://github.com/armory3d/armory/wiki/setup#vs-code--kode-studio-recommended.

**Comment by onelsonic** [comment]
thanks, it works like a charm now 👍

**Comment by luboslenco** [comment]
Happy to hear!
