### ISSUE TITLE
Wrong number of vertices when optimizing mesh export for SoftBody Physics

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#1920]
**Description**
When exporting objects with the Bullet SoftBody trait, the mesh is exported using an optimized format. This causes vertex count to vary depending on whether UV maps are present.

In this case, I chose a simple `Ico Sphere` with 42 vertices.

The outputs of `trace( cast ( objcet ,MeshObject ).data.geom.positions.values.length / 4 )` for different cases:

|Export Type| With UV map| Without UV map|
|-------------| ------------- | ------------- |
|Optimized Export| 63  | 42  |
|Regular Export| 240  | 240  |

This is important because if a SoftBody of 42 vertices is exported with 63 instead, unlike in graphics, Bullet considers it as completely different vertices. This in turn causes the SoftBody to explode into pieces. 

The regular export however does not change with the presence of a UV map, hence is not of concern here. Bullet needs vertices in an optimized format.

I narrowed down the points where mesh vertices are processed and exported:
[Mesh Export](https://github.com/armory3d/armory/blob/646ff7566993313b744ca58e07db67e036cd4086/blender/arm/exporter.py#L1431)

[Optimized Mesh Export](https://github.com/armory3d/armory/blob/646ff7566993313b744ca58e07db67e036cd4086/blender/arm/exporter_opt.py#L103)

**To Reproduce**
Add any closed object with UV map, shade smooth, and apply SoftBody. The Object explodes. If Object does not have a UV map, SoftBody behaves normally

**Expected behavior**
Regardless of the presence of UV maps, SoftBody must function normally.

**System**
Blender: 2.83
Armory: v2020.10 ($Id: 7e8f665dca6ab1e34e07ad584b86c36a72bf8d03 $)
OS: Windows 10

**Test File**
[VertexCounts.zip](https://github.com/armory3d/armory/files/5355807/VertexCounts.zip)

**Comment by knowledgenude** [comment]
There is also a bug when you enable Cloth physics to UV mapped objects, it don't explodes but don't work properly.

I think that the Soft body physics was even more broken, because i tried to apply it without shading smooth. Is not better to apply shade smooth automatically when enable the soft/cloth physics to any object in the moment of the export?

**Comment by QuantumCoderQC** [comment]
@knowledgenude Yes. The issue also exists in Cloth physics. I am working on improving the physics side of Cloth and SoftBody to more resemble that of Blender (Blender does not use BulletPhysics for Cloth and SoftBody).

However, the main challenge I face is to reduce the vertex count to the actual number of verts. This is partially working right now but needs improvements. 

As for the shading, there is no issue on the graphics side of the game, that is even if the cloth/ SB is made Smooth/Flat, it does not matter. All `Bullet `cares about is the exact numbers of `vertices`, `indices`, and `triangles `without repetition. This is what I want from the [Optimized Export](https://github.com/armory3d/armory/blob/646ff7566993313b744ca58e07db67e036cd4086/blender/arm/exporter_opt.py#L103)

**Comment by QuantumCoderQC** [comment]
Since I worked a bit more on the issue, here is a more detailed report:

For Bullet Physics soft body to work, there must be "connected triangles". That is, if there are two connected faces, they should share a vertex. But this is in general not necessary for graphics. Since in graphics, we can have 2 connected triangles, and each triangle could have different vertices. By different vertices I mean different vertex index (in index buffer), but same 3D coordinate. The reason why this might be necessary in graphics is because of the UV coordinates, Vertex normals and tangents, Vertex colors. So, for example, if we have just one vertex, we cannot have 2 UV coordinates for the same vertex position (due to vertex buffer layout) like in the case below. Below, we have 4 connected faces. But the UVs are not.

Faces:
![Faces](https://github.com/armory3d/armory/assets/55564981/7c996687-2ef2-4a73-9729-e09f9f54e805)

UVs:
![UVs](https://github.com/armory3d/armory/assets/55564981/8e9e7d14-c0bc-4baf-95b9-918642c35cea)

A direct export would lead to soft body breaking. Because, the vertices are not connected.

https://github.com/armory3d/armory/assets/55564981/ffc5c3ab-6338-4be2-be31-f949754ecfc5

For this to work, we need to know the Blender's [`vertex_index`](https://docs.blender.org/api/current/bpy.types.MeshLoop.html#bpy.types.MeshLoop.vertex_index) attribute for each of the Armory's index buffer entries. This mapping is lost at export. Only then can the faces/ vertices be connected properly.

**Comment by QuantumCoderQC** [comment]
Solved with https://github.com/armory3d/armory/pull/2893
