### ISSUE TITLE
Rigid Body doesn't updates when it's own object play an animation

### ISSUE THREAD

**Issue by notwarp** [armory3d/armory#1925]
Thank you for contributing to Armory!

**Description**
Just try the armory_examples/ui_script3d press F5 and when you click on "open" button, you try to pass on the other room, you'll be stuck in front of an invisible wall, this is because the rigid body doesn't follow the animated object, even if you flag "Animated" inside the physics tab properties of the object. Don't know if i missing something but i tried all possible solutions i can think

**To Reproduce**
Just try the armory_examples/ui_script3d

**Expected behavior**
The player should be able to go in the other room during gameplay after the door shift to the right

**System**
Blender: 2.90.1
Armory: v2020.10
OS: Linux Mint 19.3
Graphics card: GeForce GTX 750 Ti oc

**Comment by QuantumCoderQC** [comment]
Hi @notwarp,

This not essentially a bug, rather a mistake in the example. To solve this mistake uncheck the "Gate" object `RigidBody` property `Force Deactivation` to `False`

**Comment by notwarp** [comment]
Hi, thanks for your reply, but even with "Force deactivation" setted to "false" the rigid body doesn't update with the animation

**Comment by QuantumCoderQC** [comment]
Hi again,

I could not reproduce this error when `Force Deactivation` is `False` for the Gate. Maybe try cleaning the project and then run.

**Comment by notwarp** [comment]
ok, i'm sorry, my fault, in the rigid body settings i've forgot to uncheck `deactivation` under `Dynamics`, so we should write some hint on what option are necessary for achieve this effect or anothe when one starts play with the rigid bodies. Thank you in and apologize me again.
