### ISSUE TITLE
PhysX and GameWorks

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#194]
Add optional support for PhysX module and potentially more libs from the [GameWorks SDK](https://developer.nvidia.com/what-is-gameworks).

**Comment by quantum-entangler** [comment]
boo? Not really a fan of closed source evil, but if we can get open-source alternatives as choice, I guess it'll be fine?

TL;DR: Why GameWorks?

**Comment by luboslenco** [comment]
Will be optional module, so only relevant to the users who requested this and want to explicitly plug it in for their projects. Physics system in Armory is already abstracted and prepared for multiple engines.

**Comment by quantum-entangler** [comment]
In that case it makes perfect sense, thanks. 😄

**Comment by luboslenco** [comment]
No prob, the engine itself will never be tied to proprietary software. 😃

**Comment by luboslenco** [comment]
Closing this to be handled as a separate project. Added an example on minimal physics engine impl at https://github.com/armory3d/oimo_module.
