### ISSUE TITLE
Blending broken on RX 5700 XT (possibly other Navi hardware as well)

### ISSUE THREAD

**Issue by Skehmatics** [armory3d/armory#1962]
**Description**
Having any materials that blend causes render pipeline errors on the RX 5700 XT (and maybe other gx10 / navi hardware)

The following exception is thrown every frame:
```
Trace: TypeError: Cannot read property 'setPipeline' of null
    at iron_object_MeshObject.render (<anonymous>:14072:7)
    at iron_RenderPath.submitDraw (<anonymous>:2843:6)
    at iron_RenderPath.drawMeshes (<anonymous>:2805:9)
    at iron_RenderPath.armory_renderpath_RenderPathDeferred.commands (<anonymous>:589:44)
    at iron_RenderPath.renderFrame (<anonymous>:2599:8)
    at iron_object_CameraObject.renderFrame (<anonymous>:12600:26)
    at iron_Scene.renderFrame (<anonymous>:3722:16)
    at iron_App.render (<anonymous>:2386:20)
    at Function.kha_System.render (<anonymous>:22376:3)
    at kha_SystemImpl.renderCallback (<anonymous>:22517:13)
```

And a lot of garbage in the preview:
![image](https://user-images.githubusercontent.com/5824729/97260850-dfcd1180-17da-11eb-9fc2-c83bce0d57d7.png)

**To Reproduce**
On any material, enable blending under Armory Props. The material_translucent/blend.blend example project (attached) is a perfect example

**Expected behavior**
Materials are additively blended 

**System**
Blender: 2.83.5
Armory: latest git (9e8117e) and release (2020.10)
OS: Fedora 32
Graphics card: AMD RX 5700 XT

**Test File**
[armory_examples-20.10_material_translucent.zip](https://github.com/armory3d/armory/files/5443121/armory_examples-20.10_material_translucent.zip)

**Comment by MoritzBrueckner** [comment]
The same happens for me with a Nvidia card, so it's probably not related to a graphics card but instead some error in the render pipeline. It looks like its just missing a call to set the correct render target, however its not rendered at all when doing that (so I think there is a second error thats a bit more difficult to find, it isn't rendered with forward rendering as well).

**Comment by e1e5en-gd** [comment]
There is already such an issue and there is a proposal for a solution, but to what extent it is correct, here is the question (https://github.com/armory3d/armory/issues/1615).

**Comment by MoritzBrueckner** [comment]
Hi @Skehmatics,

this issue should be fixed with https://github.com/armory3d/armory/pull/2114, can you please check out the [git version](https://github.com/armory3d/armory/wiki/gitversion) (or wait until the next SDK is released in a few days) and report back if the error is resolved for you?

**Comment by MoritzBrueckner** [comment]
Closing this issue because there is no answer and the issue seems resolved.
