### ISSUE TITLE
When the `Compilation Server` option is enabled, changes to the project are not applied

### ISSUE THREAD

**Issue by e1e5en-gd** [armory3d/armory#1983]
**Description**
When the `Compilation Server` option is enabled: 
- resizing the window does not change;
- need to clean the cache to “update” every logic change;
- total changes are not applied.

The problem came after the PR https://github.com/armory3d/armory/pull/1973

**To Reproduce**
Change project.

**System**
Blender: 2.83.7
Armory: git, master (f0715ff2b6efca3fe520c70a82833d9b6cefc086)
OS: Windows 10 64-bit
Graphics card: NVIDIA GeForce 930M

**Comment by davidbruce** [comment]
Fix for this: https://github.com/armory3d/armory/pull/1985

**Comment by luboslenco** [comment]
Merged now. 👍
