### ISSUE TITLE
DXF importer can not be enabled when Armory is loaded

### ISSUE THREAD

**Issue by Ryder17z** [armory3d/armory#1986]
**To Reproduce**
1 Install Armory as usual
2 Try to enable the DXF importer

**Problem**
![image](https://user-images.githubusercontent.com/2000703/97945157-eaf9e180-1d86-11eb-931b-7fd6151445ea.png)

**System**
OS: Linux-5.8.16-2-MANJARO-x86_64-with-arch-Manjaro-Linux 64 Bits
Armory: Most recent version available on Nov 1. 2020 (via the official website)
Blender: 2.83.8 (LTS via Steam)
Graphics card: GeForce GTX 1080/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 455.28

While untested, it's possible this issue also prevents the dxf eporter to work as well

**Comment by MoritzBrueckner** [comment]
Hi, this was already fixed in https://github.com/armory3d/armory/pull/1964 and should be included in the last SDK 2020.11, wich was released yesterday (Nov. 2).

Thnks for reporting! If the error still occurs, feel free to reopen this issue.
