### ISSUE TITLE
Bump node does not compile

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#1990]
I don't know if this is already supported but is returning errors:

```
build_untitled/compiled/Shaders/Material_001_mesh.frag.glsl:7: 'n' : undeclared identifier 
build_untitled/compiled/Shaders/Material_001_mesh.frag.glsl:7: '=' :  cannot convert from ' temp float' to ' temp 3-component vector of float'
build_untitled/compiled/Shaders/Material_001_mesh.frag.glsl:7: '' : compilation terminated 
```
```
SPIR-V is not generated for failed compile or link

Compiling shader 1 of 19 (Material_001_mesh.frag.glsl) failed:
Shader compiler error.
(node:7132) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Shader compiler error.
(node:7132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MoritzBrueckner** [comment]
Hi, the bump node is already supported, this problem occurs because of some wrong shader generation. Can you share an example file or a few steps to reproduce?

**Comment by knowledgenude** [comment]
@MoritzBrueckner Hm, maybe i am using it in the wrong way... the nodes sockets are not of the same color, but in eevee it works as expected.

Example: [bump.zip](https://github.com/armory3d/armory/files/5503035/bump.zip)

Setup:
![Captura de tela de 2020-11-06 16-11-26](https://user-images.githubusercontent.com/63247726/98405284-c2a20980-204a-11eb-8ea9-9782e4bcea78.png)

**Comment by MoritzBrueckner** [comment]
There are actually multiple issues here:

- The musgrave texture node was "returning" a color even if it no longer has a color output (not sure if it existed before). PR that fixes this: https://github.com/armory3d/armory/pull/1993
- The bump mapping node tries to access normals that aren't written in the shader yet. This only occurs when the `Armory Project > Export Tangents` setting is active, but if it's not there is another error also happening in the normal map parsing (`'vVec' : undeclared identifier`).

  It seems that there are many open issues with normal maps (also see https://github.com/armory3d/armory/issues/1968), the normal map parsing urgently needs an update. When I try to make bump mapping work with tangents I just get a black mesh, so I still have to figure out what I'm doing wrong.

Thanks for the report as always!
