### ISSUE TITLE
Wiki problem

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory#1992]
Hi @luboslenco,

I made a small mistake with the logic node reference, I accidentally wrote the commit message as the page title in the GitHub UI and the reference page got moved because of that. I pushed a temporary fix (new reference page, because I first didn't realize it got moved) but now the page history is gone, maybe you can revert those changes? It's not possible via the web UI and GitHub doesn't allow non-members to edit the wiki repository in other ways.

Thank you and sorry about that!

**Comment by luboslenco** [comment]
No prob at all, page history is back now.
