### ISSUE TITLE
Auto-build transform matrix

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#200]
Hi @luboslenco,

If only object scale is changed the screen is not updated. See attached test project. (It uses a manual tweener since I could not get the built-in Tween to work, will create separate issue about that).

If i comment out line 15 in MyTrait.hx (disabling the rotation of the cube) the screen is not updated even though the scale is changing from 1.0 -> 0.1 -> 1.0 continuously.

If i leave line 15 active screen is updated as expected, and you can see scale changing.
![peek 2017-06-28 13-35](https://user-images.githubusercontent.com/9007314/27635756-adef4c3c-5c08-11e7-81d1-6d5148a7d285.gif)

Test project: [ManualTweenerTest.zip](https://github.com/armory3d/armory/files/1108571/ManualTweenerTest.zip)

Kind Regards,
Martin

**Comment by luboslenco** [comment]
As of now there is a need to report transform changes when directly accessing location, rotation or scale vectors.

```hx
// Directly accessing location vector
object.transform.loc.x = 2;

// Make sure matrix gets updated next frame
object.transform.dirty = true;

// Alternative - update matrix immediately
object.transform.buildMatrix();
```

This is not very obvious - will try to get rid of it.

**Comment by guzzard** [comment]
Hi @luboslenco,

Very nice! Scale and location work great both individually and together.
![scale_loc](https://user-images.githubusercontent.com/9007314/27741002-135d50f8-5db4-11e7-9874-0ca5568dfe14.gif)


However, I'm having problems with rotation. Seems like the vertices are tweening individually or something, instead of the object as a whole? Or perhaps I'm doing something completely wrong?
![rotation](https://user-images.githubusercontent.com/9007314/27741011-180b3c8c-5db4-11e7-96bf-df3525175539.gif)

```
// should rotate the cube to x:180 y:90 z:0
public function tweenScaleSmaller():Void {
        Tween.to({
            target: object.transform,
            props: { rot: new Quat(0.707,0,0.707,0) },
            duration: 2.0,
            ease: Ease.ExpoOut,
            done: tweenScaleBigger
        });
}
```

```
// rotate back to zero
public function tweenScaleBigger():Void {
        Tween.to({
            target: object.transform,
            props: { rot: new Quat(0,0,0,1) },
            duration: 4.0,
            ease: Ease.Linear,
            done: tweenScaleSmaller
        });
}
```

Kind Regards,
Martin

**Comment by luboslenco** [comment]
Added a dedicated manual page to document the transform behavior: https://armory3d.org/manual/#/code/transform.
