### ISSUE TITLE
Persistent crash

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2001]
After adding many nodes, sometimes Blender crashes randomly when i try to add a new node. The console does not show nothing but this crash log is generated: https://pastebin.pl/view/6c39e89c

**Comment by MoritzBrueckner** [comment]
Hi, is the link to the logfile correct? It doesn't work for me, maybe you can upload the log as a .txt directly here on GitHub?

**Comment by knowledgenude** [comment]
It is crashing a lot, there is two crash logs: 
[crash2.txt](https://github.com/armory3d/armory/files/5526281/crash2.txt)
[crash1.txt](https://github.com/armory3d/armory/files/5526280/crash1.txt)

I will try to find a way to force the crash and send a blend file
 later.

**Comment by MoritzBrueckner** [comment]
Hi, is this still happening for you?

**Comment by knowledgenude** [comment]
I have almost sure this issue died after the Blender 2.93 support, so i will close it. Thanks for the reminder 🙂
