### ISSUE TITLE
Built-in Tween does not work

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#201]
Hi @luboslenco,

I cannot get the Tween functionality to work. Values is not lerped over time, but changes instantaneously.

Related forum thread: http://forums.armory3d.org/t/how-to-get-tweening-to-work/377

Kind regards,
Martin

**Comment by luboslenco** [comment]
Heyo Martin!

Did some work on the Tween system, to update Build 11 just replacing those two files should do:
https://github.com/armory3d/iron/blob/master/Sources/iron/system/Tween.hx
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/NavAgent.hx

Added a new example:
https://github.com/armory3d/armory_examples/tree/master/script_tween

And a minimal code snippet:
```hx
// Tween object location 1 unit up on Z axis
Tween.to({
	target: object.transform,
	props: { loc: new Vec4(0, 0, 1) },
	duration: 1.0
});
```

**Comment by guzzard** [comment]
Hi @luboslenco,

Very nice! Scale and location work great both individually and together.
![scale_loc](https://user-images.githubusercontent.com/9007314/27741002-135d50f8-5db4-11e7-9874-0ca5568dfe14.gif)


However, I'm having problems with rotation. Seems like the vertices are tweening individually or something, instead of the object as a whole? Or perhaps I'm doing something completely wrong?
![rotation](https://user-images.githubusercontent.com/9007314/27741011-180b3c8c-5db4-11e7-96bf-df3525175539.gif)

```
// should rotate the cube to x:180 y:90 z:0
public function tweenScaleSmaller():Void {
        Tween.to({
            target: object.transform,
            props: { rot: new Quat(0.707,0,0.707,0) },
            duration: 2.0,
            ease: Ease.ExpoOut,
            done: tweenScaleBigger
        });
}
```

```
// rotate back to zero
public function tweenScaleBigger():Void {
        Tween.to({
            target: object.transform,
            props: { rot: new Quat(0,0,0,1) },
            duration: 4.0,
            ease: Ease.Linear,
            done: tweenScaleSmaller
        });
}
```

Kind Regards,
Martin

**Comment by luboslenco** [comment]
Should be now fixed in https://github.com/armory3d/iron/commit/08ec953517a288ab7d7ce91e779093a766f057d8. Just copying `iron/system/Tween.hx` from git to sdk will do.
