### ISSUE TITLE
Display operations in node label

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2014]
![Captura de tela de 2020-11-17 19-05-51](https://user-images.githubusercontent.com/63247726/99456357-07aa2380-2908-11eb-853e-9e7bf1c3a92d.png)

![Captura de tela de 2020-11-17 19-09-06](https://user-images.githubusercontent.com/63247726/99456586-67083380-2908-11eb-81fe-92ac7878497e.png)

**Comment by e1e5en-gd** [comment]
An interesting option, but you only need to do this for certain types of nodes. I would suggest only for math nodes, and naming them not `Divide`, but `Math: Divide` and `Vector Math: Divide`, respectively.
My assumptions about the difficulties that may arise for other nodes:
- `'Space' Down` - you can understand that this is `Keyboard`. But beginners can find it difficult to navigate and formulate their questions. He had a problem, how can he understand/remember from the name `‘Space’ Down` that this is the `Keyboard` node?
- `‘Up’ Down`, `’A’ Down`, `‘B’ Down` are the `Keyboard` or `Gamepad` or `Virtual Button` nodes?

If you just add, the name of the nodes can become long, for example, `Keyboard Down ‘Space’`.
You need to be very careful about the name so as not to confuse the user.

By the way, it is possible for nodes in which you can dynamically change the number of parameters, indicate how many values ​​in the name (for example, in arrays, switch and others).

**Comment by knowledgenude** [comment]
@e1e5en-gd , that makes sense. Also as the keyboard node is not that much repeated in the node tree (only a few commands) then the user can name it as it want :+1:

**Comment by MoritzBrueckner** [comment]
Had some ideas, open for discussion:

![nodelabel_merge](https://user-images.githubusercontent.com/17685000/99579128-0cd9a200-29de-11eb-9734-641bbf8f5490.gif) ![nodelabel_loop](https://user-images.githubusercontent.com/17685000/99579130-0d723880-29de-11eb-949b-77c04fb698d0.gif)
![nodelabel_object](https://user-images.githubusercontent.com/17685000/99579136-0ea36580-29de-11eb-8f17-8eb0e9aab1e5.gif) ![nodelabel_timer](https://user-images.githubusercontent.com/17685000/99579138-0f3bfc00-29de-11eb-8e74-8a65a27a121c.gif)

If the sockets from which the values are taken are connected, either only the regular node label is displayed, or in case of the loop node `x...5` is displayed for example if the `From` socket is connected.

**Comment by knowledgenude** [comment]
That is amazing!

One question: the timer node when minimized is bigger than others, there is not a way to take advantage of this and split its label in two lines? Expanding the label vertically seems to use less space than horizontally.

**Comment by e1e5en-gd** [comment]
@MoritzBrueckner, That's cool!

**Comment by MoritzBrueckner** [comment]
Thanks :)

> One question: the timer node when minimized is bigger than others, there is not a way to take advantage of this and split its label in two lines? Expanding the label vertically seems to use less space than horizontally.

I don't think so, would be nice to have though.

**Comment by MoritzBrueckner** [comment]
What about this for the keyboard node (and other input nodes similarly)?

![screenshot](https://user-images.githubusercontent.com/17685000/102026582-f46f6400-3d9e-11eb-9429-e3691f07b167.png)

It omits the state (started, down, released) in the title but still gives enough information for many cases.

**Comment by knowledgenude** [comment]
@MoritzBrueckner  for me it is more than sufficient! With this system would be possible to rename nodes manually? Then maybe if people see the need they can give more specific names for each node they want.

**Comment by MoritzBrueckner** [comment]
You can still rename nodes, but Blender will ignore the dynamic label if a node is renamed.

Apart from that: should I open a pull request for the nodes where we already have a dynamic header design? I'm still open for suggestions.

**Comment by e1e5en-gd** [comment]
The name should always be dynamic, because even if the node is not hidden, then quickly browsing the headers you can understand the logic and structure. You do not need to look at all the fields in a node.

I think it's worth doing PR.
