### ISSUE TITLE
2.9.x Armory Player Error

### ISSUE THREAD

**Issue by RocketNinja15** [armory3d/armory#2031]
Thank you for contributing to Armory!

**Description**
Issue description.
I get this error when I click play on armory player
Traceback (most recent call last):
  File "/Users/***/Downloads/ArmorySDK//armory/blender/arm/props_ui.py", line 732, in execute
    class ARM_PT_ProjectFlagsDebugConsolePanel(bpy.types.Panel):
  File "/Users/***/Downloads/ArmorySDK//armory/blender/arm/make.py", line 519, in play
    arm.utils.fetch_script_props(fn) # Trait props
  File "/Users/***/Downloads/ArmorySDK//armory/blender/arm/make.py", line 308, in compile
    arm.lib.server.run_haxe(arm.utils.get_haxe_path())
  File "/Users/***/Downloads/ArmorySDK//armory/blender/arm/make.py", line 34, in run_proc
    done()
  File "/Applications/Blender.app/Contents/Resources/2.90/python/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/Applications/Blender.app/Contents/Resources/2.90/python/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/***/Downloads/ArmorySDK//nodejs/node-osx': '/Users/***/Downloads/ArmorySDK//nodejs/node-osx'

location: <unknown location>:-1

**To Reproduce**
Steps to reproduce the behavior.
Click play on 2.9.x OSX mojave.
**Expected behavior**
What you expected to happen.
To ope
**System**
Blender: 2.9.x
Armory: Latest
OS: OSX
Graphics card: Intel integrated gpu 6000

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by MoritzBrueckner** [comment]
Hi and thanks for the report! Unfortunately Armory is not yet updated to Blender 2.9, so there is no guarantee that it will work on that Blender version. However, there are plans to update it soon. Do you get the same error message with Blender 2.83 LTS?

**Comment by rekaerst** [comment]
I got similar error using blender 2.91 linux64
```shell
Python: Traceback (most recent call last):
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/props_ui.py", line 839, in execute
    make.play()
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/make.py", line 500, in play
    build(target=runtime_to_target(), is_play=True)
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/make.py", line 388, in build
    export_data(fp, sdk_path)
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/make.py", line 125, in export_data
    ArmoryExporter.export_scene(bpy.context, asset_path, scene=scene, depsgraph=depsgraph)
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/exporter.py", line 154, in export_scene
    cls(context, filepath, scene, depsgraph).execute()
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/exporter.py", line 2154, in execute
    self.export_scene_traits()
  File "/home/arthur/opt/ArmorySDK//armory/blender/arm/exporter.py", line 2596, in export_scene_traits
    out_trait['parameters'] = [str(rbw.time_scale), str(1 / rbw.steps_per_second), str(rbw.solver_iterations)]
AttributeError: 'RigidBodyWorld' object has no attribute 'steps_per_second'

location: <unknown location>:-1
```

**Comment by MoritzBrueckner** [comment]
@rekaerst That error message is related to Blender 2.9 which is not officially supported yet (the Blender Python API changed a bit). Hopefully there will be support for 2.9 soon.

**Comment by onelsonic** [comment]
I double that and maybe recommend skipping all none LTS versions related issues.
Blender is on a speed run with new releases which is good.

- blender 2.83.9 LTS is working perfectly.
- blender 2.90.1 works somehow (if not, please let me know what does not work for you)
- blender 2.91 is incompatible with Armory.

the next LTS versions will be 2.93, 3.3 then 3.7.

![release_cadence_4th_wall-1-1536x336](https://user-images.githubusercontent.com/53947594/100942097-01689980-34fb-11eb-8d75-86067c0e0526.png)
https://code.blender.org/2020/05/long-term-support-pilot/
https://www.blender.org/download/lts/

And some experimental stuff for fun :
https://builder.blender.org/download/branches/
the geometry node branch looks great

**Comment by MoritzBrueckner** [comment]
Yes we should probably start directly with 2.93 support. If i remember correctly @QuantumCoderQC wanted to open a thread on the forums about that soon, we should then discuss how the transition could look like and what tasks are required (I made a small list of things already but it's probably incomplete).

**Comment by RocketNinja15** [comment]
@MoritzBrueckner I don't use LTS... I might try it out because of its long time support

**Comment by MoritzBrueckner** [comment]
As I said above Armory currently only supports 2.8 LTS versions, so please test if the error happens there as well. Otherwise it's probably related to Blender 2.9 and we will need to fix it when the transition to 2.9 starts.

**Comment by MoritzBrueckner** [comment]
Hi @RocketNinja15,

can you please try the following and tell me if your issue still exists (I don't use OSX):

Open `path/to/your/SDK/armory/blender/arm/utils.py` in a text editor. Search for the following lines:
```python
def get_node_path():
    if get_os() == 'win':
        return get_sdk_path() + '/nodejs/node.exe'
    elif get_os() == 'mac':
        return get_sdk_path() + '/nodejs/node-osx'
    else:
        return get_sdk_path() + '/nodejs/node-linux64'
```

and replace them with

```python
def get_node_path():
    if get_os() == 'win':
        return os.path.join(get_sdk_path(), 'nodejs', 'node.exe')
    elif get_os() == 'mac':
        return os.path.join(get_sdk_path(), 'nodejs', 'node-osx')
    else:
        return os.path.join(get_sdk_path(), 'nodejs', 'node-linux64')
```

Then, save the file and restart Blender. If it works, I will open a pull request soon :)

**Comment by simonmueck** [comment]
Hi, @MoritzBrueckner should this fix fork for Windows too?
I tried it out - unfortunately it doesn't work for me :(
(Windows 10 20H2)

**Comment by MoritzBrueckner** [comment]
> should this fix fork for Windows too?

I don't understand what you mean with fork in this context, but it also depends to which problem you refer – unfortunately there are two different error messages posted in this issue. The solution I posted above is for the first error described in the [very-first post](https://github.com/armory3d/armory/issues/2031#issue-753859754) in this issue. It should work on Windows as well.

If you're referring to [this](https://github.com/armory3d/armory/issues/2031#issuecomment-737201334) error message, it is already fixed in the [2.9 branch](https://github.com/armory3d/armory/tree/blender2.9) (via [this pull request](https://github.com/armory3d/armory/pull/2084)). If you know how to use Git, you can checkout the 2.9 branch and it should work. You can follow the development of Blender 2.9 support [here](https://github.com/armory3d/armory/pull/2082) and [in the forum](https://forums.armory3d.org/t/armory-upgrade-to-blender-2-9-x/4400).

**Comment by simonmueck** [comment]
@MoritzBrueckner Got it, thx :)

**Comment by MoritzBrueckner** [comment]
@RocketNinja15 Armory SDK 2021.6 with Blender 2.9 support was released yesterday, please reopen this issue again if the error persists. I will close this for now due to inactivity.
