### ISSUE TITLE
 "compiling" but no window appears macOs + Blender 2.83 

### ISSUE THREAD

**Issue by winniejo** [armory3d/armory#2036]
**Issue description:**
On my macbook pro I am using Blender 2.8.3 and  installed the add-on, went all fine.
When I push the play button (It announcing that) it is "compiling" for 4+ second  and 
then it stops but no additional window appears.

I unticked the cache option, refresh, etc, but It did not help.
What should i do?

 p.s. I also like to check out the Blender 2.79 version but cant find it.

Thanks 
Be save.

Winn

**System**
Blender: 2.83.5
Armory: Armory add on latest version 30 nov 2020*
OS:  MacOS 10.13.xx // (HighSierra)
Graphics card: Macbook pro AMD Radeon HD 6490M 500mb
CPU intel i7

**Comment by MoritzBrueckner** [comment]
Hi and thanks for the report! Could you run Blender from a terminal [as described here](https://docs.blender.org/manual/en/2.83/advanced/command_line/launch/macos.html) and check if there are any error messages?

**Comment by winniejo** [comment]
@MoritzBrueckner Hay I will do that . How do I check error messages by terminal commands.
Or just in Blender .

**Comment by MoritzBrueckner** [comment]
I'm not a macOS user so I cant help you with details here, sorry. Open a terminal and then enter the path to Blender (like described in the article I posted above) to run it from a terminal. It will open as usual and you will see the program output (including error messages) in the terminal window (so run your Armory project in that Blender session to get the error message if there is one).

**Comment by winniejo** [comment]
@ MoritzBrueckner  
Here is the error message its expecting macOs 10.15 Iam guessing 
which My Macbook pro cannot run ny MBP  runs macOs 10.13.

__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.018412113189697266
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib


Haxe compiler error.
Finished in 10.868728160858154
ERROR: Build failed, check console

**Comment by winniejo** [comment]
@ MoritzBrueckner  
Here is the error message its expecting macOs 10.15 Iam guessing 
which My Macbook pro cannot run ny MBP  runs macOs 10.13.

__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.018412113189697266
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib


Haxe compiler error.
Finished in 10.868728160858154
ERROR: Build failed,

**Comment by winniejo** [comment]
@ MoritzBrueckner  
Here is the error message its expecting macOs 10.15 Iam guessing 
which my Macbook pro cannot run my MBP  runs macOs 10.13.

__________  [Armory] Compiling  __________
Exporting Scene
Scene exported in 0.018412113189697266
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK//Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /ArmorySDK/Kha/Tools/haxe/haxe-osx (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib


Haxe compiler error.
Finished in 10.868728160858154
ERROR: Build failed,

**Comment by MoritzBrueckner** [comment]
@winniejo It's possible that the Haxe version that comes with Kha (= the framework Armory is based on) doesn't support your version of MacOS or there are files missing on your OS. You could open an issue [here](https://github.com/Kode/haxe_bin/) to ask if that's the case.

Possibly related:
- https://groups.google.com/g/haxelang/c/IDSvqw2StO8
- https://github.com/HaxeFoundation/hashlink/issues/80
- https://github.com/HaxeFoundation/haxe/issues/6579

**Comment by winniejo** [comment]
@MoritzBrueckner 

Ok will do thanks But I like to download the Armory Blender 2.79 version 
where can I find that?

Thanks 
Winn

**Comment by MoritzBrueckner** [comment]
I'm not sure if that's still available somewhere. Please note that the 2.79 version is unsupported since a long while now and didn't receive any updates and bug fixes since then.

Closing this issue with link to https://github.com/Kode/haxe_bin/issues/3, thanks for reporting.

**Comment by luboslenco** [comment]
Just to note, the old unsupported 2.79 version is available at https://github.com/armory3d/armsdk/releases/tag/0.5.
