### ISSUE TITLE
When opening Canvas Editor: GL Error 1282 // Kinc --> Kore/PipelineStateImpl.c 209 

### ISSUE THREAD

**Issue by Lykdraft** [armory3d/armory#2038]
This is how it looks when we try to open the Canvas Editor on Mac OSX (10.14) now:
(Another user has pointed out the same problem on mac on Discord as well...)

![Screenshot 2020-12-02 at 01 01 40](https://user-images.githubusercontent.com/18437561/100811200-5b555a80-343a-11eb-900c-e3f6820d1622.png)

When looking at the console after opening, it spits this continously:

![Screenshot 2020-12-02 at 01 01 51](https://user-images.githubusercontent.com/18437561/100811206-5db7b480-343a-11eb-915b-f28ac01faee4.png)

This is the latest Armory SDK (2020.12) with Blender 2.83 on OSX 10.14.6

Best,
tL.

**Comment by Lykdraft** [comment]
Follow up:

Looks like this is across OSX 10.13, 10.14 and 10.15, different computers/users.

**Comment by BlackGoku36** [comment]
Opengl is depreciated on apple device. Armory2D need to be compile for metal for it to work

**Comment by Lykdraft** [comment]
?
Why did it work all the time before then?

**Comment by BlackGoku36** [comment]
Dunno how but latest update in armorcore dealt the damage of apple depreciation of opengl. All I know is on mac metal should be used instead of metal.

**Comment by Lykdraft** [comment]
Just took another shot at it. I got it working on OSX. :)

We need to compile -Armory2d from source ->  https://github.com/armory3d/armory2d
Then just proceed how it is mentioned in the description:
Build it via khamake for  **openGL (!)** and put the build/Krom files into ArmorySDK/lib/armory_tools/armory2d/opengl
Then it works.  I am looking at it right now.  Very cool. 

But like I said, I wondered why this just stopped working. Because my Mac didn't change at all in the last two years.
So yes, OpenGL is done on the new macs, but obviously not on slightly older ones. That's what I didn't get.

So probably something broke in between and there is no up-to-date a2d build included in the latest a3d distro.
Maybe this should be changed?
