### ISSUE TITLE
glow and light reflections appearing on objects with last changes

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2039]
Hi there,
it is just me or are you getting some sort of glow and light reflections appearing on objects and around shapes with the recent changes? Not sure if it is the "chromatic aberration shader" changes.

Here is what I get : (same blend file)
Before with SDK-2020-11
<img width="205" alt="before" src="https://user-images.githubusercontent.com/53947594/100827149-5d301580-345c-11eb-9177-66d4f7e6e9b9.png">

After with SDK-2020-12
<img width="205" alt="after" src="https://user-images.githubusercontent.com/53947594/100827212-83ee4c00-345c-11eb-892c-3280b9e2746a.png">

While the chromatic aberration setting is already disabled in post-processing.
<img width="205" alt="2020-12-02 05_10_34-Blender  C__Users_devWin10_Desktop_seed2_seed_bfirst1 blend" src="https://user-images.githubusercontent.com/53947594/100827332-c31c9d00-345c-11eb-9261-937b18bce0dd.png">

Or is it coming from something else? I tried re-using the old version "chromatic_aberration_pass.frag.glsl", but the effect is still here.

**Comment by e1e5en-gd** [comment]
Hi!

If I am not mistaken, this is the related [PR](https://github.com/armory3d/armory/pull/2027).

**Comment by MoritzBrueckner** [comment]
Hm, this doesn't look like chromatic aberration and if it's turned off it is probably not the issue here. Do you use forward or deferred rendering?

Is this one of Armory's demo files?

**Comment by onelsonic** [comment]
using the "**forward clustered**" with a "**LUT texture**" colorgrading for mobile with mobile materials.
a modified demo file, I will see if I can put a file together, Anyone else having the same issue?

**Comment by onelsonic** [comment]
I looked at the PR details.
So activating the `Realtime postprocess` option fixed the random glows and reflections.
Seems like I had it disabled but actually working before.

As now it is working as it should 👍 :smiley:
