### ISSUE TITLE
Problem with On Volume Node

### ISSUE THREAD

**Issue by chuckO99** [armory3d/armory#2044]
Thank you for contributing to Armory!

I have a racetrack which uses the On Volume Trigger to sense the car. The latest rev of Armory seems to have broken this node. The node  works in the Overlap mode, but the Enter or Leave modes won't trigger the event. No error message, the node just doesn't work. It worked fine on Armory 2011

**System**
Blender: 2.893
Armory: 2012
OS: Windows 10
Graphics card: RTX2070 Super

**Test File**
*(drag & drop the zipped .blend file here)*

**Comment by knowledgenude** [comment]
Sorry, this was my fault. Will be fixed in https://github.com/armory3d/armory/pull/2045

Thanks to report! :+1:
