### ISSUE TITLE
Linux problems - Armory p11a

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#205]
Hello,
sorry for the long post.

i recently installed Linux® on one system ( iMac ® late 2009, Linux® Kernel 4.9 AMD® GPU Mesa 13  Debian Based distro) and i have several issues with examples but i would try to solve problems starting from basic cube.
I would try to test Armory on Linux before build a new Linux based system.
I did no t have the same problems with Armory in the same system and Mac Os® Sierra® but when possible i try to use free and open source solutions.

In the same Linux system i am able to run Blender 2.8 that works with OpenGL 3.3

OpenGL info:
`server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 13.0.6
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 13.0.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
`

Starting from cube basic scene ( Armory p11a ):

**1- Play in viewport has strange artifacts in the debug window**
![armory_limux_1](https://user-images.githubusercontent.com/12413409/27710112-d95a74a2-5d1e-11e7-9045-09000ea7e3a3.png)

Console:
`Armory v17.05
OS: linux, Target: krom, GAPI: opengl
Scene built in 0.0036563873291015625
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CToneFilmic.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_quad_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (armory_default.arm).
Exporting asset 1 of 1 (droid_sans.ttf).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CToneFilmic.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CToneFilmic.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Uniform envmapStrength not found.`

**2 If i complile or play in Armory Player in Krom the basic cube nothing happen and if i use Browser HTML5, Firefox®  54 will open an empty screen.

If i play the html from the folder i see a black screen:**

![armory_linux2](https://user-images.githubusercontent.com/12413409/27710276-7393de8c-5d1f-11e7-8781-8f6ee72fef95.png)

Nothing strange in the terminal:

`Armory v17.05
OS: linux, Target: html5, GAPI: opengl
Scene built in 0.003100156784057617
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CToneFilmic.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_quad_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (armory_default.arm).
Exporting asset 1 of 1 (droid_sans.ttf).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CToneFilmic.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvCol_SSAO_SMAA_CToneFilmic.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
`

**if i publish HTML5 from Armory project the basic cube seems to work well**

**if try several Armory examples like gate.blend  i see strange artifacts in html5 when i publish from Armory Project ( the same scene seems to work in "Play in viewport")**

![armory_linux_3](https://user-images.githubusercontent.com/12413409/27710437-0d5775a6-5d20-11e7-9b51-c5077e9785bb.png)

`Armory v17.05
OS: linux, Target: html5, GAPI: opengl
Exporting mesh Text
Exporting mesh Suzanne
Exporting mesh Cube.001
Exporting mesh Cube
Exporting mesh Cube.002
Exporting mesh Cube.008
Exporting mesh Cube.003
Scene built in 0.5582132339477539
Info: Publishing project, check console for details.

Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (Cube_data.arm).
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (Material_001_data.arm).
Exporting asset 1 of 1 (Material_005_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CToneFilmic.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.001.arm).
Exporting asset 1 of 1 (mesh_Cube.002.arm).
Exporting asset 1 of 1 (mesh_Cube.003.arm).
Exporting asset 1 of 1 (mesh_Cube.008.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (mesh_Suzanne.arm).
Exporting asset 1 of 1 (mesh_Text.arm).
Exporting asset 1 of 1 (armory_default.arm).
Exporting asset 1 of 1 (checker.png).
Exporting asset 1 of 1 (checker_rough.png).
Exporting asset 1 of 1 (droid_sans.ttf).
Compiling shader 1 of 1 (Cube_mesh.frag.glsl).
Compiling shader 1 of 1 (Cube_mesh.vert.glsl).
Compiling shader 1 of 1 (Cube_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Cube_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_001_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_001_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_005_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_005_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_005_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_005_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CToneFilmic.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_SSAO_SMAA_CToneFilmic.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Project published
`

**Comment by luboslenco** [comment]
Viewport glitch should be gone in 0.4, Krom fix in progress at https://github.com/Kode/Krom/issues/64.
