### ISSUE TITLE
Renaming Traits in the NodeEditor doesn't update name in the "Armory Traits" panel

### ISSUE THREAD

**Issue by PostPollux** [armory3d/armory#207]
Renaming Traits in the NodeEditor doesn't update name in the "Armory Traits" panel. You can see it in the screencast here:
https://goo.gl/photos/d1BdkZQ8fkddn9pq6

Well, not the most important issue and I'm not sure if this is easy to fix. But it would still be nice if it just works out of the box...

**Comment by luboslenco** [comment]
Fixed now.
