### ISSUE TITLE
Transition to Blender 2.93 LTS

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory#2074]
Hi @luboslenco,

a few of us contributors are [planning](https://forums.armory3d.org/t/armory-upgrade-to-blender-2-9-x/4400) to migrate Armory to the upcoming Blender 2.9 LTS versions ([scheduled for Q2 2021](https://www.blender.org/download/lts/)).

If you're ok with that: could you add a Blender 2.9 branch to this repository so that we're able to create pull requests for that? We would open a main PR to merge the 2.9 branch into master which then would be in draft status as long as we're working on it. It would be awesome if you were adding a Blender 2.9 label as well to make the PRs and related issues (if there are any) more distinguishable.

Also, would it be ok for you to maybe add Zui, Blender and maybe Iron labels? It's unrelated to the 2.9 project but while we're at it... :)

Thank you very much 👍

**Comment by luboslenco** [comment]
It's done! 🙂

**Comment by MoritzBrueckner** [comment]
Thanks :)
