### ISSUE TITLE
Orthographic camera issues

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#208]
Hi @luboslenco,

Using orthographic camera mode results in some strange things.

- perspective is incorrect in "play in viewport" - seems to be based on viewport width/height
- perspective in krom player looks right in 16:9 but incorrect if resolution is changed to some other ratio
- light/shadows don't render correctly with orthographic camera
- changing orthographic camera scale doesn't have any effect on the rendered output, however moving the camera does. Usually it's the other way around.

**1000x1000 orthographic:**
![ortho](https://user-images.githubusercontent.com/9007314/27912177-34afc4d2-625c-11e7-83ef-120007712cfe.png)

**1000x1000 perspective:**
![persp](https://user-images.githubusercontent.com/9007314/27912168-2ce1429e-625c-11e7-885f-854e8ac8ff05.png)

Kind Regards,
Martin

**Comment by luboslenco** [comment]
Applied some fixes in https://github.com/armory3d/iron/commit/4d8e42a779bcd673ebfafc41a0e4e9d0f9e46892.
