### ISSUE TITLE
Use Blender's internal text editor

### ISSUE THREAD

**Issue by anonimo82** [armory3d/armory#2088]
Hello everyone.
I'd like to use Blender's internal text editor instead of VSCode/Kode studio/Sublime text (as explained in the documentation)
Is it possible?

**Comment by MoritzBrueckner** [comment]
Hi,

it is possible, although not recommended for various reasons. Blender's text editor lets you open any file, so you can open the Haxe files and edit them just like you would do it in other editors. But there are disadvantages:

- No syntax hightlighting for Haxe
- No autocompletion
- No other editor plugins for Haxe (Kode Studio is also not connected to the official VSCode plugin repository)
- There is no editor "project" which lets you quickly see all files or search in them

I know, working in another editor can be cumbersome if you need to switch a lot between open windows, but if you use VSCode or Kode Studio you can even run the game from inside the editor with `F5`, so for long coding sessions you don't really need to leave the editor often.

So using these external editors (VSCode has best Armory integration of them) really helps you, especially when working with projects with multiple files and packages. But if you want to use Blender's editor, it will also work.
