### ISSUE TITLE
Improving IK solver and BoneAnimation class

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2089]
Hi @luboslenco ,

The current IK solver in the `BoneAnimation` class has a few shortcomings, and I would like to improve it. Some of the shortcomings are:

1. No definition of chain length. When IK is used on a bone, the entire parent tree is calculated. Not good.
2. No control over iterations/precision. They are fixed
3. The Armature transform is not taken into account at all. That is if the armature object is moved from world origin, IK fails.
4. No option for Pole, causing the bones to rotate any-which ways.

In addition to these IK specific issues, the bone animation class does not prioritize IK, FK and Animation controlled bones. That is, all the bones in the armature are assigned the new transforms based on animation, and then IK/FK is applied on top. 

This means IK and FK must be calculated every single frame, even if the target or the armature itself does not move. In light of these issues, I would like to improve this `BoneAnimation` class.

However, since you suggested that `iron` was being re-written in `C`, I am unsure if my contributions will be useful at all. Hence, I would like to know if I can still continue to develop `iron` in `Haxe` or should I wait for the new `iron` in `C`?

**Comment by luboslenco** [comment]
Improvements to the `BoneAnimation` class written in Haxe are welcome, thanks!
