### ISSUE TITLE
Incorrect dimension depending on object origin point

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2098]
The cube has a dimension of 1, 1, 2;

When the origin point is in its center, the Z dimension is printed correclty (2), but if the origin is on its bottom, the Z dimension is double (4). Is this a bug or it is supposed to be as this?

[dimensions-test.zip](https://github.com/armory3d/armory/files/5898013/dimensions-test.zip)

**Comment by MoritzBrueckner** [comment]
I think this is a duplicate of https://github.com/armory3d/armory/issues/1259
