### ISSUE TITLE
Lowering Roughness strength in Armory PBR shader = Shader compiler error

### ISSUE THREAD

**Issue by nafergo** [armory3d/armory#21]
When using Armory PBR shader, if I lower the Roughness strength... wont compile

ERROR: 0:112: 'assign' :  l-value required "roughness" (can't modify a uniform)
ERROR: 0:112: '' : missing #endif 
ERROR: 0:112: '' :  syntax error
ERROR: 3 compilation errors.  No code generated.

SPIRV is not generated for failed compile or link

Shader compiler error
[system-info.txt](https://github.com/armory3d/armory/files/573421/system-info.txt)
.

**Comment by luboslenco** [comment]
Nice catch - hunted it down, will be fixed in next build.

**Comment by luboslenco** [comment]
Fixed in Build 2.
