### ISSUE TITLE
Spawning object with child objects

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#210]
Hi @luboslenco,

When I spawn an object that has child objects in the hierarchy the child objects are left out.

Example:
![screenshot-area-2017-07-07-141510](https://user-images.githubusercontent.com/9007314/27957429-cac89ad0-631e-11e7-9ae3-1aff245a0663.png)

Spawning the Parent using iron.Scene.spawnObject would result in that only the Parent was spawned, and not the child objects.

I was expecting the whole hierarchy to be spawned. If this is not to be expected, how can do to spawn a hierarchy like this apart from spawning a complete scene?

Kind regards,
Martin

**Comment by luboslenco** [comment]
Fixed for upcoming build 12, `Scene.spawnObject()` will also include children by default now.

Example snippet: https://github.com/armory3d/armory_examples/blob/master/script_spawnobject/Sources/arm/SpawnTrait.hx#L10
