### ISSUE TITLE
Can't get armory to play file

### ISSUE THREAD

**Issue by Nopotato** [armory3d/armory#211]
I'm struggling to get armory to "play" my file. If anyone is willing to try and see if they can play my file, I'd be thankful. I don't get any error messages.
[armory file broken.zip](https://github.com/armory3d/armory/files/1143324/armory.file.broken.zip)

**Comment by Xristoskr** [comment]
it work 
![20](https://user-images.githubusercontent.com/23359603/28158911-eeac326e-67c3-11e7-816b-58c257460527.png)
![21](https://user-images.githubusercontent.com/23359603/28158910-eea60b0a-67c3-11e7-92e4-6b5075a0822d.png)

![20](https://user-images.githubusercontent.com/23359603/28158888-da4a6ca0-67c3-11e7-9f9e-2e6a6ac5b88b.png)

**Comment by luboslenco** [comment]
@Nopotato does pressing *Properties - Render - Armory Player - Clean Project* help?

It appears to work here too(using sun lamp below). What output do you see on your machine? Black screen or nothing starts up at all? Can you try to play in window(F5) or set *Armory Player - Runtime* to *Browser* and try using that?
![img](https://user-images.githubusercontent.com/3685704/28159944-f3bc8cc2-67be-11e7-93db-803dc41d4aa9.jpg)

**Comment by Nopotato** [comment]
I moved all my files to the same directory as armory install is in (it was in dropbox)
I tried playing in window(f5) and it is just black.
When I make a new file and add armory material to the default cube, it will play normally without issue.
Nothing happens if I change Runtime to browser. Same as "krom", the play button removes itself from a pressed state the moment I move the cursor over the image (updating the UI?)
How long do I have to wait after pressing play? Is the file too big for my pc?

**Comment by Nopotato** [comment]
I have found out the trigger for when my files sop working. If I swap rendering engine to something else (cycles or blender game?) and back, I can no longer play the file. Since blender seems to start up files in another rendering engine every now and then, (almost always?) this makes my files not playable after opening them the next day.

**Comment by luboslenco** [comment]
Should be getting resolved now by https://github.com/armory3d/armory/issues/204#issuecomment-322910336.
