### ISSUE TITLE
Logic Node - Set Scene Active - compilation error

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2118]
Thank you for contributing to Armory!

**Description**
Logic Node - Set Scene Active - compilation error

**To Reproduce**
![image](https://user-images.githubusercontent.com/39986875/109386602-f788e380-78fb-11eb-8793-c39ad45ff8eb.png)

**Expected behavior**
Load Scene "Scene.001"

**System**
Blender: 2.83.12
Armory: 2021.2
OS: Windows 10 64Bit
Graphics card: Raden RX 580 4GB

**Test File**
[SetActiveScene.zip](https://github.com/armory3d/armory/files/6054347/SetActiveScene.zip)

**Comment by MoritzBrueckner** [comment]
Hi, the file doesn't include a node tree, I'm not sure if something went wrong when saving it?

I recreated the node setup and got the same error as in [this issue](https://github.com/armory3d/armory/issues/1772), which is related to lights. Either remove the second light (which can be seen in the outliner under `Blender File > Lights`) or enable the new `Shadow Map Atlas` option (see the linked issues for details). For me, everything works fine then.

**Comment by Dzynek** [comment]
![image](https://user-images.githubusercontent.com/39986875/109398943-1610ce00-7940-11eb-8e12-42f655474c71.png)

Works thanks
