### ISSUE TITLE
Use blender wihout code

### ISSUE THREAD

**Issue by lucazanioff** [armory3d/armory#2119]
Hy, hiw can i use blender wihout code?

**Comment by MoritzBrueckner** [comment]
Hi, it is explained very well [in this forum post](https://forums.armory3d.org/t/use-armory-wihout-code-visual-scripting/4503/2), also there is the step-by-step [playground tutorial](https://github.com/armory3d/armory/wiki/playground) which is a good starting point. 

In general, please use the forum for questions and Github for feature requests or bug reports only.
