### ISSUE TITLE
Random "unable to build" error

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#212]
I was just playing arround with voxel GI and Camera setting and soon I got this error and couldnt get it reversed:
**ERROR: build_untitled\compiled\Shaders\deferred_indirect\../std/conetrace.glsl:9: 'voxelgiResolution' : undeclared identifier
ERROR: build_untitled\compiled\Shaders\deferred_indirect\deferred_indirect_Irr_EnvSky_Rad_PCSS_Cycles_VoxelGI_Rad_Irr_SSAO_SMAA_Veloc.frag.glsl:27: '#' : preprocessor directive cannot be preceded by another token
ERROR: build_untitled\compiled\Shaders\deferred_indirect\../std/conetrace.glsl:9: '=' : global const initializers must be constant ' const float'
ERROR: build_untitled\compiled\Shaders\deferred_indirect\deferred_indirect_Irr_EnvSky_Rad_PCSS_Cycles_VoxelGI_Rad_Irr_SSAO_SMAA_Veloc.frag.glsl:27: '' : compilation terminated
ERROR: 4 compilation errors.  No code generated.

ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link

Shader compiler error.
Build failed, check console**

Fix this please this is the third time my test-file gets corrupted

**Comment by luboslenco** [comment]
Heyo,

I need the troubled blend file so I can reproduce an issue and fix it.

You can revert back to defaults by selecting a 'Deferred' render path preset:
<img width="252" alt="a" src="https://user-images.githubusercontent.com/3685704/28237756-fa061d76-6946-11e7-8c8f-7bac452a843b.png">

Clean the project:
<img width="254" alt="b" src="https://user-images.githubusercontent.com/3685704/28237758-feac9d0a-6946-11e7-83a6-c41baf848097.png">

**Comment by luboslenco** [comment]
In build 12 there is now a list of render paths, so when this happens it is possible to delete the render path and create a new one from preset. If you still get it to error due to render path settings then blend file is highly appreciated.
