### ISSUE TITLE
Publishing Project fails for Windows C

### ISSUE THREAD

**Issue by JAWS81** [armory3d/armory#2130]
Thank you for contributing to Armory!

**Description**
Publishing my project fails. Throwing error C3867 and C2296, etc. in den Blender Console. The .sln file get´s created but while debugging these error messages again show up in VS and the .exe is not created. 

**To Reproduce**
When I publish the default Blender file the error message in the Debugger does not show up. But in VS it is present again and the .exe is also not created.

**Expected behavior**
Publishing should finish and work in VS

**System**
Blender: 2.83 LTS
Armory: 2021-3
OS: Windows 10
Graphics card: RTX2080 Super

**Test File**
.txt File with all Warnings
[Armory_publish_message.txt](https://github.com/armory3d/armory/files/6152636/Armory_publish_message.txt)

**Comment by MoritzBrueckner** [comment]
Hi, Armory's Kha version was updated since you opened the issue and I think the errors mentioned above were fixed. Can you please try again if the issue persists?

**Comment by JAWS81** [comment]
Hi,

tested It. Now it published. 
Not sure if what really the cause was as I had to do quite a lot of changes due to the new armory version and having the project rest for some time.

Thanks.
