### ISSUE TITLE
Linking fragment stage: missing entry point

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#214]
Here is the log:

![capture](https://user-images.githubusercontent.com/15915424/28952315-5316a2e4-789e-11e7-8073-38da190c7792.JPG)

I'm afraid I'm unable to find the answer to the problem.

**Comment by luboslenco** [comment]
Any luck with build 12?

**Comment by George-the-1st** [comment]
Yup, It works perfectly on my Windows 7-64 bit edition. I'll try it on Windows 10 relatively soon.

**Comment by George-the-1st** [comment]
By the by, thanks for doing a follow-up. Makes me feel good about the direction this project is going.

**Comment by luboslenco** [comment]
Glad to be helpful!
