### ISSUE TITLE
Instancing is broken.

### ISSUE THREAD

**Issue by Lykdraft** [armory3d/armory#2146]
Looks like instancing is broken. 

Steps:

1) alt-d to create linked copies from cube 

2) ctrl-p parent the linked copies to cube  -- so far so good. children still render... 

3)  On parent cube (under armory props) change instanced children to anything else than off.  --> children won't render anymore... 

- I checked myself on Win and OSX. Same behavior. Latest armorySdk  & armorySdk git

- Was confirmed by another user on Discord.

**Comment by MoritzBrueckner** [comment]
Hi, are you sure that you're using the latest SDK from Git? The issue mentioned in Discord should be fixed already with https://github.com/armory3d/armory/pull/2141 (see https://github.com/armory3d/armory/issues/2142 for reference).

**Comment by Lykdraft** [comment]
I think so.  QuantumCoder confirmed this as well when I posted this two days ago. 
I  use the armoryGit, just updated it a day before that. So... Maybe you try for yourself?
It's quick to find out.

**Comment by Lykdraft** [comment]
Oh, I am sorry, he already did that. 
I didn't see this. 

Sorry 'bout that... :)
