### ISSUE TITLE
Spot light issues

### ISSUE THREAD

**Issue by officialduke99** [armory3d/armory#2148]
Thank you for contributing to Armory!

**Description**
When I add a spot light to my scene, it shines in all directions and is much stronger then in viewport.

**To Reproduce**
Use [this](https://drive.google.com/drive/folders/1Bz-GcA4GrMwUW_kSbFPFCntRZrDrOL2m?usp=sharing) project file

**System**
Blender: 2.83 LTS
Armory: 2021.3
OS: Windows 10 Home
Graphics card: Nvidia GTX 1650

**Comment by pittoy** [comment]
Try to enable the option "shadow map atlasing".
https://github.com/armory3d/armory/wiki/Shadow-Map-Atlasing#enabling-shadow-map-atlasing

It works！

**System**
Blender: 2.93.9 LTS
Armory: 2022.2
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
Hi, I can no longer reproduce this issue. Can you please try it again with a recent SDK?

![Screenshot](https://user-images.githubusercontent.com/17685000/154988669-627f0a66-4bee-4a59-a412-396b9c4c258b.png)

**Comment by MoritzBrueckner** [comment]
In case the issue still wasn't fixed at the time of my comment above, it is probably fixed after https://github.com/armory3d/armory/pull/2442 so I'm closing this issue now. Please reopen if the problem persists.
