### ISSUE TITLE
thick glass

### ISSUE THREAD

**Issue by 958479612** [armory3d/armory#2156]
How to make thick glass in armory3d

**Comment by Lykdraft** [comment]
That sounds more like a tutorial request and not a feature request?
Not sure this is the right address for that... 
Maybe try the forum?  https://forums.armory3d.org/
Or the discord?

**Comment by 958479612** [comment]
https://github.com/armory3d/armory_calibrarion/tree/master/refraction ,The link to this example is missing. I look forward to receiving this example document.    From the:  https://forums.armory3d.org/t/build-12-is-out/424

**Comment by 958479612** [comment]
> 
> 
> 这听起来更像是教程的要求，而不是功能的要求？
> 不确定这是否是正确的地址...
> 也许尝试论坛？ [https://forums.armory3d.org/ ](https://forums.armory3d.org/)
> 还是不和谐？
https://github.com/armory3d/armory_calibrarion/tree/master/refraction ，此示例的链接丢失。 我期待收到此示例文档。 来自： : https //forums.armory3d.org/t/build-12-is-out/424

**Comment by 958479612** [comment]
![QQ截图20210414102613](https://user-images.githubusercontent.com/82086788/114649963-02fd6600-9d14-11eb-9188-f4781906b6f2.png)

**Comment by Lykdraft** [comment]
Oh, I see. I think refraction was bound to voxel GI and as far as I know voxel GI was dropped out of armory3d quite a while ago.
So I am not sure there can be done anything like this right now, but I am not 100% certain about this. 

Maybe someone else who does know more about this can chime in?

**Comment by MoritzBrueckner** [comment]
> I think refraction was bound to voxel GI and as far as I know voxel GI was dropped out of armory3d quite a while ago.
So I am not sure there can be done anything like this right now, but I am not 100% certain about this.

I don't know it either, the linked forum post says "New example - refraction using Voxel GI." so it is probably not supported. But this question is indeed better suited for the forums so I will close this issue.

**Comment by mistajuliax** [comment]
Hi, may be there is a lack of informations in node supported section in the manual. Thick glass is not possible because refraction node is not supported. It is not mentioned in the manual as, specular node, volume scatter, volume absorption, principled volume ...

**Comment by MoritzBrueckner** [comment]
@mistajuliax Thanks for the hint, the list in the wiki now includes a few more nodes.
