### ISSUE TITLE
Self light emission objects

### ISSUE THREAD

**Issue by malublu** [armory3d/armory#216]
![grafik](https://user-images.githubusercontent.com/14329224/29025745-93df274c-7b78-11e7-874b-197b23a6be79.png)

Here a simple example image:

![grafik](https://user-images.githubusercontent.com/14329224/29116535-6063dfb4-7cfb-11e7-9a28-453ae76370a7.png)

Another complexer example:

![grafik](https://user-images.githubusercontent.com/14329224/29116775-3fbf92fc-7cfc-11e7-87fe-82c1a0471315.png)

if i remove the lamp (point lamp) i see nothing

is it fixed with #197?

**Comment by luboslenco** [comment]
Added emission test scene at https://github.com/armory3d/archviz_templates/tree/master/bedroom. 

At this time Voxel Global Illumination is used for emission, which uses voxelized scene data to calculate lighting from surroundings. Other way may be to 'fake' it using bloom(screen-space only), or prebake to textures using Cycles(static).
