### ISSUE TITLE
ik support

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#217]
*(optional - drag & drop zipped .blend file here)*

**Comment by Xristoskr** [comment]
any update

**Comment by luboslenco** [comment]
Sorry, not yet - will try to move this forward for build 15.

There is now animation blending and parenting objects to bones(attaching sword to character hand bone!), would be nice to solve IK next.

**Comment by luboslenco** [comment]
IK support in progress, example will be linked at https://github.com/armory3d/armory/issues/397.
