### ISSUE TITLE
Get Object by Name Logic Node Problem

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2171]
Thank you for contributing to Armory!

**Description**
Get Object by Name Logic Node Problem.
If the Object is in another Scene, this Nod works like a Spawn Object.

![image](https://user-images.githubusercontent.com/39986875/116283177-dde50a80-a78b-11eb-90b0-423759a1abac.png)

![image](https://user-images.githubusercontent.com/39986875/116283227-ed645380-a78b-11eb-9497-58fe750cf024.png)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**
Returning a Reference to the Object

**System**
Blender: 2.83.13
Armory: 2021.4.0
OS: Windows 10 64bit
Graphics card: RTX 2060 Super

**Test File**
[GetObjectByName.zip](https://github.com/armory3d/armory/files/6386340/GetObjectByName.zip)

**Comment by QuantumCoderQC** [comment]
This is most likely due to #1892. 

I suggest we remove the object creation part and return `null` instead. On the other hand, the `Spawn Object node` could use this "object creation" code, since it seems to spawn objects from the active scene only.

**Comment by QuantumCoderQC** [comment]
This issue may be closed if solved.
