### ISSUE TITLE
Temporal Anti Aliasing (TAA) artifact on Krom Linux

### ISSUE THREAD

**Issue by N8n5h** [armory3d/armory#2172]
**Description**
There seems to be an artifact that appears when selecting TAA as an anti aliasing option. Confirmed on Krom Linux, but couldn't reproduce it on HTML5.

See the horizontal divide on the next gif:

![TAA](https://user-images.githubusercontent.com/42382648/116413387-f433aa80-a80d-11eb-9a23-bbe22a0f6c86.gif)

Test file:
[taa_issue.blend.zip](https://github.com/armory3d/armory/files/6392203/taa_issue.blend.zip)

**System**
Blender: 2.83LTS
Armory: latest commit
OS: Ubuntu 20.04.2 LTS
Graphics card: AMD RX 480, Kisak Mesa Drivers

**Comment by e2002e** [comment]
Try enabling auto exposure. It binds the taa texture in the renderpath and for me it fixed the issue even after I disabled it.

**Comment by e2002e** [comment]
Fixed by #2915
