### ISSUE TITLE
No Print no work - Logic Nodes

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2183]
Thank you for contributing to Armory!

**Description**
Sometimes there is a problem that without adding Node Print - the script does not work

![image](https://user-images.githubusercontent.com/39986875/117110182-09688600-ad86-11eb-9437-5dbb4e9524f1.png)

**To Reproduce**
Deleting Node Print makes this script not work

**Expected behavior**
What you expected to happen.

**System**
Blender: 2.83.13 LTS
Armory: 2021.05
OS: Windows 10 64bit
Graphics card: Geforce RTX 2060 Super

**Test File**
[NoPrintNoWork.zip](https://github.com/armory3d/armory/files/6425647/NoPrintNoWork.zip)

**Comment by QuantumCoderQC** [comment]
Hi, from the image of the Node tree, there is a loop that is formed using logic nodes. This is not a good way of making logic code, and Blender also does not like such loops. Hence the red connection. Hence I would not classify this as an issue, rather a logic error.

A better and perhaps simpler way would be to delete all child objects is presented below. It uses events to iterate through the loop and delete child objects.

![image](https://user-images.githubusercontent.com/55564981/117137323-d3d59400-ada9-11eb-95fe-61ea8e3c5a0c.png)

Below I have provided a blend file that uses this node tree to delete child objects. The Scene has 4 cubes as a child objects of another parent cube. When you hit spacebar, the child objects are deleted iteratively. Additionally, I also print the frame numbers and when the child objects are deleted. This is not essential and it works without print logic node too.

[RemoveAllChildrenTest.zip](https://github.com/armory3d/armory/files/6426886/RemoveAllChildrenTest.zip)

**Comment by Dzynek** [comment]
Hello, thanks for the answer

"It uses events to iterate through the loop and delete child objects." A good idea :)

![image](https://user-images.githubusercontent.com/39986875/117281291-c67ce000-ae63-11eb-9134-d5eb550aa814.png)
https://github.com/armory3d/armory/files/6433510/ArrayObjectRemove2.zip
This method also works :)

greetings

**Comment by Dzynek** [comment]
Thank you, you can close the thread :)
