### ISSUE TITLE
[BUG] Unhandled promise rejection error during shader compilation. Causing the game from failing to build/launch.

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2186]
```
MeasureIt: Cleaning data
Info: Saved "untitled.blend"

Armory v2021.5 ($Id: e4b950f78eb7c1ac9e65f2ad87920132e33cc61d $)
Exporting Scene
Scene exported in 10.466s
C:\Users\Oliver\Desktop\Armory test 3.0.0\build_untitled\debug\temp\Cloud_003_shadowmap.frag.hlsl(98,43-58): error X4000: variable 'dotNV' used without having been completely initialized

Compiling shader 4 of 27 (Cloud_003_shadowmap.frag.glsl) failed:
Shader compiler error.
(node:9632) UnhandledPromiseRejectionWarning: Shader compiler error.
(node:9632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Finished in 17.466s
ERROR: Build failed, check console

```

(This is my Blender console from when hitting F5)

Heres the blend file:
[untitled.zip](https://github.com/armory3d/armory/files/6451497/untitled.zip)
https://u.teknik.io/59JyH.blend
(Its the same file on both links)

You can find "Cloud.003" in the object shader editor.

**Comment by QuantumCoderQC** [comment]
Hi, from your file, I was able to run it without any errors. I use the latest git version of the SDK without the 2.9 branch commits. Try cleaning the project once and then try. BTW, Which version of Blender are you using?

![image](https://user-images.githubusercontent.com/55564981/117657783-44a9f100-b19a-11eb-87c0-d458cf7d6296.png)

**Comment by ItsCubeTime** [comment]
> Hi, from your file, I was able to run it without any errors. I use the latest git version of the SDK without the 2.9 branch commits. Try cleaning the project once and then try. BTW, Which version of Blender are you using?
> 
> ![image](https://user-images.githubusercontent.com/55564981/117657783-44a9f100-b19a-11eb-87c0-d458cf7d6296.png)

Hi there, I downloaded Armory from here: https://armory3d.org/download.html about a week or 2 ago. I use Blender 2.83 LTS (downloaded at the same time).

Are there any binaries available for the latest 2.9 version? Im a little short on disk space currently so I would rather avoid building from source for now for that reason (unless all the dependencies are under like 10gb in total)

**Comment by ItsCubeTime** [comment]
Also how did you resize the Krom viewport? I cant quite get the cursor to change to an arrow when putting it at the edge of the window

**Comment by QuantumCoderQC** [comment]
Okay, the version of Blender and the Armory SDK seems fine. But I am not sure if the installation that's causing the issue. Could you try a simple default cube and see if similar error appears.

You can set the window size manually in the output tab
![image](https://user-images.githubusercontent.com/55564981/117659513-52f90c80-b19c-11eb-9d15-b58d18716988.png)

Additionally, you can also set the window to be scalable here. Then you should get a tooltip to expand the window.
![image](https://user-images.githubusercontent.com/55564981/117659694-8e93d680-b19c-11eb-8ff8-ef78bf1a8762.png)

**Comment by ItsCubeTime** [comment]
> Okay, the version of Blender and the Armory SDK seems fine. But I am not sure if the installation that's causing the issue. Could you try a simple default cube and see if similar error appears.

Nope, its just this shader.



> You can set the window size manually in the output tab
> ![image](https://user-images.githubusercontent.com/55564981/117659513-52f90c80-b19c-11eb-9d15-b58d18716988.png)
>
> Additionally, you can also set the window to be scalable here. Then you should get a tooltip to expand the window.
> ![image](https://user-images.githubusercontent.com/55564981/117659694-8e93d680-b19c-11eb-8ff8-ef78bf1a8762.png)

Ah thanks :D

**Comment by MoritzBrueckner** [comment]
I can confirm this issue, I will take a look later but I'm a bit busy right now. @QuantumCoderQC are you on Windows? The error comes from the generated .hlsl file so it probably doesn't occur on other systems.

**Comment by QuantumCoderQC** [comment]
> I can confirm this issue, I will take a look later but I'm a bit busy right now. @QuantumCoderQC are you on Windows? The error comes from the generated .hlsl file so it probably doesn't occur on other systems.

Ah, I was using the one with the zip file. That file did not have this "Cloud_003" shader to it. Now I get the error when I try with the other Blend file provided.  I am on Windows BTW.
