### ISSUE TITLE
[BUG] [Node editor] "Get variable" node not actually parsing the value

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2188]
Demoed here:
https://user-images.githubusercontent.com/20190653/117672572-44b1ed00-b1aa-11eb-91f2-666ba0c4d14c.mp4

[untitled.zip](https://github.com/armory3d/armory/files/6452651/untitled.zip)

Also (from #logic-nodes in the Armory Discord - Values wont show up in the debug console either):
![image](https://user-images.githubusercontent.com/20190653/117673123-c6097f80-b1aa-11eb-8754-033ac5845e82.png)

Tested on Blender 2.83 LTS Armory v. 2021.5.0 (according to the add-ons pane)

**Comment by MoritzBrueckner** [comment]
Hi, this was most likely fixed by https://github.com/armory3d/armory/pull/2439, please reopen if the issue persists in the upcoming SDK.
