### ISSUE TITLE
[Feature request] Integer output from the merge node

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2189]
![image](https://user-images.githubusercontent.com/20190653/117674691-2ea52c00-b1ac-11eb-989c-41f897b80247.png)

The integer output being counted from 0 and representing which input it was called from. 

A possible usecase would be for a character that you might want to be able to move forwards and backwards (and hence reuse the "move" code only multiplying the speed by -1 for reverse/moving backwards).

**Comment by ItsCubeTime** [comment]
Input 0 = 0
Input 1 = 1
Input 2 = 2
etc

Like a reverse switch

**Comment by ItsCubeTime** [comment]
Something else that I think could be useful just in general for the node system when it comes to naming, would be having some extra keywords for the nodes.

Like a node like this could also have the search keywords "join", "execute", "flow", "merge".

**Comment by ItsCubeTime** [comment]
> > A possible usecase would be for a character that you might want to be able to move forwards and backwards (and hence reuse the "move" code only multiplying the speed by -1 for reverse/moving backwards).
> 
> Hello dear, did u already see the `Vector From Boolean` node? Just connect WASD keys on it and multiply the outputed vector by the desired velocity. Probably it needs to be normalized, i don't remember.
> 
> I suppose @MoritzBrueckner is right in his first affirmation, see that behavior (search for "merge"): https://forums.armory3d.org/t/weird-issue/4211/5
> 
> What happens is that the object is moved faster when more inputs are active.
> 
> Merge node actually can be activated multiple times as far i know, so an array of integers makes more sense. Otherwise another node should be created with the `any input` function.

Hi, the node is working like I would expect it to at the moment so the issue you linked is not something g that bothers me, I were indeed looking to execute my move node several times per tick.

For the other issue I think a separate "do only once" node might be better to give the user better control over from when they want extra executions per tick to get filtered away

**Comment by MoritzBrueckner** [comment]
But this behaviour is actually the right one for having this output as the node is executed for each individual input, thus making it possible to get a unique value for the last active input. As I said, I originally confused the functionality of the node a bit.

Maybe, to lower possible confusion, it would be a good idea to keep the name `Merge` and instead add a node switch for either individual execution or per-frame execution if an input is active? Something like `Once Per Input` (default for backwards compatibility) and `Once Per Frame`?

**Comment by ItsCubeTime** [comment]
> But this behaviour is actually the right one for adding the proposed output as the node is executed for each individual input, thus making it possible to get a unique value for the last active input. As I said, I originally confused the functionality of the node a bit.
> 
> Maybe, to lower possible confusion, it would be a good idea to keep the name `Merge` and instead add a node switch for either individual execution or per-frame execution if an input is active? Something like `Once Per Input` (default for backwards compatibility) and `Once Per Frame`?

Sounds like a good solution :)
