### ISSUE TITLE
[Bug] Having a disconnected loop break node in the graph results in a haxe compile error

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2191]
```
Scene exported in 0.013s
C:\Users\Oliver\Desktop\Armory test 3.0.0\Sources/arm/node/NodeTree.hx:118: characters 21-22 : Expected expression or )
ERROR: Build failed, check console
```

The loop break node is meant to be used after a foor loop - however leaving an empty node in the graph results in a compile error, and from the users perspective the message might be a little cryptic.

Not too sure how serious this is as you could probably just open the generated hax file and discover the break statement (or whatevers happening under the hood, I havent actually checked yet).

Feel free to close this if a fix for this feels overkill.

Tested on 2021.05.0

**Comment by MoritzBrueckner** [comment]
Can you maybe share a minimal example (screenshot or blend file)? I can't reproduce it but I'm not sure what you mean with an "empty" node. There is just a loop break without a loop? This works for me.
