### ISSUE TITLE
Nodes, add support for ctrl X "Delete with reconnect"

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2198]
Demonstrated in the shader graph:

https://user-images.githubusercontent.com/20190653/118534858-04bead00-b74a-11eb-99cd-4e493437bbdd.mp4

Currently if you hit ctrl X in the logic node graph the node will get deleted however the connection wont be kept.

**Comment by rpaladin** [comment]
@MoritzBrueckner it appears to be that this issue automatically resolved itself. Possibly Blender updates.

https://user-images.githubusercontent.com/69180012/208323972-6119773b-6f98-4a02-8f99-392c100c319a.mp4
