### ISSUE TITLE
No lights? Shadeless rendering?

### ISSUE THREAD

**Issue by malublu** [armory3d/armory#220]
It is possible to use no lights?

I try to make an isometric world without lights, but with own colors.

Somthing like this:
https://www.blendernation.com/2015/02/09/behind-the-scenes-isometric-illusion/

(and no: i don't remake monument valley in armory 😳 😂, I found it by goole: blender isometric without lights)

**Comment by luboslenco** [comment]
Adding a new example for upcoming build which shows one possible way. The lamps are deleted from scene and the environment is set to white with a strength of 1.0. (Also disabled world radiance/irradiance, tonemap and shadowmap.)

The color can be manipulated using materials as usual (multiple materials per mesh), textures and vertex colors. :)



![shadeless](https://user-images.githubusercontent.com/3685704/29162165-e505d8e0-7db8-11e7-9920-1e64f3a2100b.jpg)

**Comment by malublu** [comment]
Jear 👍 i waiting for it :)

**Comment by luboslenco** [comment]
Example now up!
https://github.com/armory3d/armory_examples/tree/master/material_shadeless
