### ISSUE TITLE
[Logic nodes] New node "Select by last called execution pin".

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2201]
I hope you can excuse my charming dots representing node inputs/outputs.
![image](https://user-images.githubusercontent.com/20190653/118653645-0ccd2a00-b7e8-11eb-91b1-cbeb884e2681.png)

This should work similarily to the select by index node described in #2200, except it should remember which pin was last executed and every time the "Return value" needs to be accessed it will return the cooresponding "Option" based on which of those exec pins was last called.

**Comment by MoritzBrueckner** [comment]
Shouldn't https://github.com/armory3d/armory/issues/2200 be just this? If really both modes (if I understand correctly: keep output or "forget" it after each frame) are required, this could be achieved by a simple checkbox for example.

**Comment by ItsCubeTime** [comment]
> Shouldn't #2200 be just this?

The difference is that #2200 switches by an int (like a C style switch that returns different values for each "case"), while this switches value based on which execution pin  was last called.

Personally I think its cleanest to keep them separate nodes here since the 2 nodes uses different inputs? Might be easier with the code as well.

> If really both modes (if I understand correctly: keep output or "forget" it after each frame) are required, this could be achieved by a simple checkbox for example.

With my "Once per tick" node the user would have the freedom to use it along with any node. 

Not exactly sure how it would be useful combined with this node tho in particular?

**Comment by MoritzBrueckner** [comment]
I personally would go for one node for both and have a switch like `From Index` and `From Input` or something like that. This way similar code is kept at one place and you don't need to replace the node if the inner functionality of your trait changes from using indices to "signals" for example.
