### ISSUE TITLE
[Logic nodes] New node "Once per tick" or "Once per frame". Filters exec output to only execute once every frame maximum.

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2202]
Quite well described by the title maybe but so there would be one input execution pin and one output execution pin. The node will remember if it has been called before at the current frame. If it has not then it will activate its output exec pin, if it has been executed once before that frame then it will simply "do nothing", essentially making sure any nodes after it only runs once every frame maximum (if theres nothing calling the "once per tick" node, ofc then the nodes after wouldnt be executed either).

**Comment by ItsCubeTime** [comment]
> Isn't this exactly the same as the [On Update](https://github.com/armory3d/armory/wiki/reference#on-update) node?

No, this node would take an input, check if the node has been called during the current frame. If it has not it calls the output execution, elsewise it does nothing.

So th difference here is that this node requires to be called/have is input execution pin called.

**Comment by ItsCubeTime** [comment]
A possible usecase would be if you have an event that is called from several locations in your code, this event plugs into a "translate object" node that moves lets say a car, but you want to avoid the car going faster if there are multiple event callers calling every frame.

**This node acts as a filter to make sure whatever comes behind it never gets called twice or more per frame**

**Comment by knowledgenude** [comment]
@ItsCubeTime , the car really will move faster the high the framerate is, but the solution for that case would be **delta time** (search about it). Delta is just an value you multiply by the speed of the vehicle in this case. Its value will vary depending on the framerate and this guarantes that the vehicle speed will be the same independent of fps.

This extra verification in every frame will introduce extra steps that may slow things down. "If fps = x then don't execute" and is more complex to deal. Delta is more optimized and simple :)

As for the per frame execution node, it can be a good idea, but you can already do that trought the existent nodes. We can see on implementing that :)

If u need some examples about anything i may send for u in the forum, so more people could see that.
