### ISSUE TITLE
'Get Scale' logic node completly destroys the execution.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#221]
Hello. I'm tying to make things with logic nodes to get further from the wisdom of the scene 5 tutorial.
On any scene, even the scene5 example .blend file or any other, if you place a 'get scale' node, even if you let it disconnected, the execution fails.

I've tried it on 2 pcs. My one with windows + amd card and the other with linux+nvidia card.

The console says this.
[error when get scale.txt](https://github.com/armory3d/armory/files/1213070/error.when.get.scale.txt)

Having the 'get scale' node placed, even prevents other different scenes located in the same folder to execute.

I think the error is easily reproducible.
Please say if I need to post any specification of my machines.

**Comment by luboslenco** [comment]
Hello. It is a bug present in build 11. :/
Should now be fixed(with several other nodes) in https://github.com/armory3d/armory/commit/def11523a026ad09d74989796aae9a412ff5e3b7, out with build 12 which is being worked on now.

**Comment by ja-moli** [comment]
Ok. Good to hear. I think I will post one or two more issues I have with the current build to help.

**Comment by luboslenco** [comment]
Sounds good, reporting more issues always helps, thanks a ton!

(I think both of us should be able to close it down.)
