### ISSUE TITLE
Blender 2.93.0 beta - Armory Instancing + Blender Link - not working

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2212]
After trying the current repo with Blender 2.93.0 beta,
here are some thought : in order to fully benefit from Blender 2.93.0 Armory needs to support Geometry Node,
and Geometry Nodes really shine when used with blender link objects.
To make it simple you have : geometry node + Blender link = ability to manipulate prefabs.

The first step is to have Blender link objects fully supported.
and to make it efficient for real-time applications we have Armory instancing.

You can read all the details on the above here :
**Blender Link : [https://docs.blender.org/manual/en/latest/files/linked_libraries/link_append.html?highlight=link#link](https://docs.blender.org/manual/en/latest/files/linked_libraries/link_append.html?highlight=link#link)**
and there:
**Armory Instancing : [https://github.com/armory3d/armory/wiki/instancing](https://github.com/armory3d/armory/wiki/instancing)**

To test this I put two files together :

1. the main file is **scene.blend**
2. the assest library bank file is : **libraryassests.blend**

Download the files here : [https://github.com/onelsonic/armory_tests/blob/master/linkedinstancing.7z](https://github.com/onelsonic/armory_tests/blob/master/linkedinstancing.7z)

the file scene file consist of : 
- green cubes (instanced)
- blue cones (instanced)
- red cylinders with physics (instanced)
- a simple plane with physics

the objects that are instanced live in the libraryassests.blend file and can be modified there, modification will replicate in the main file.
What should we see:  in our main file, the red cylinders (except one cylinder located below the plane) are supposed to fall on the "passive" plane.
Then all cubes / cones / cylinders should use Armory instancing.

As illustrated here : 
![Animation](https://user-images.githubusercontent.com/53947594/119418591-9d2fd100-bcf8-11eb-855c-317d57deb779.gif)

So after a few tests we have the following EDIT1 :

| target  | renderer | results |
| ------- | ---------- | ------- |
| HTML5| Mobile  | objects not rendered / cannot check physics |
| HTML5| Desktop | nothing works : objects not rendered / cannot check physics |
| Krom | Mobile | nothing works : objects not rendered / cannot check physics |
| Krom | Desktop | linked objects are rendered when being instanced / when using instancing physics only react to the parent object and not every child objects independently. |

Having this corrected will provide the ability to manipulate prefabs that are optimised for real-time and can be edited inside asset libraries.

**Comment by MoritzBrueckner** [comment]
Thanks, that is a really helpful report :)

For me it doesn't even render the instances correctly in Krom on Windows. I just looked at the exported scene in Renderdoc and it seems that the instances seem to be rendered in different positions only in the depth-only pass for lighting.

In the color pass, all instances seem to be rendered in the same position (the output data of the vertex shader is the same for each instance) even if they have at least some unique vertex data (`TEXCOORD0` which is `ipos`) which is a bit weird. So for me there are shadows in the scene for invisible objects.

**Comment by MoritzBrueckner** [comment]
@onelsonic The rendering should be fixed now, can you confirm? As for the geometry nodes, maybe open another feature request issue for that.

@QuantumCoderQC As for the physics part of this issue, do you think that supporting physics on instances (changing their instance data through some bridge code?) would be pratical? Otherwise I think we can close the issue.

**Comment by QuantumCoderQC** [comment]
> As for the physics part of this issue, do you think that supporting physics on instances (changing their instance data through some bridge code?) would be practical? Otherwise I think we can close the issue.

Yes, it should be possible. Since the instancing used in this case is CPU instancing*, it should be possible to create physics objects without mesh attached to them(maybe RigidBody trait to an Empty objects?). Then set the Vertex Buffer with these transforms, to be sent to the GPU

*CPU instancing: passing the location, rotation and scale datas to the GPU every frame via VB and instanced rendering in GPU

**Comment by onelsonic** [comment]
after new tests:

1. First I found that the Celshade renderer suffer from the same instancing issue : 
https://github.com/armory3d/driver_celshade/blob/master/blender.py
Is there a way to correct this renderer as well?
My tests show that objects are not rendered, only the shadows.

2. Then instancing on mobile/solid renderer is performing correctly now with +80% FPS.

3. Finally Physics does not work on all renderer - Only Gravity does somehow but not Collisions with linked objects.
Linked objects will not collide between each others and/or fall through floors.

I did not noticed it the first time but there is a new alert inside the Blender Physics Panel : 
**_"rigid body can't be child of a non compound rigid body"_** when adding a child object that contains physics.
I did some research and there has been a change to the Rigid Body World from Blender v2.91 onwards which affects parenting of rigid bodies and their constraints.
The new Blender way now is to : leave it un-parented and instead, create a Child Of constraint to get the same effect as before.
https://www.youtube.com/watch?v=E5r6tYRypBo
According to the above, the new way is to use link objects with "Child Of constraint" and have "Instancing" looking for similar "Child Of constraint" objects in order to optimise everything.
<img width="170" alt="2021-05-26 21_50_00-Blender_  C__Users_devWin10_Desktop_seed2_seed_bfirst1check blend" src="https://user-images.githubusercontent.com/53947594/119722376-88744a00-be6c-11eb-9999-3c9bbb252f2e.png">

Here are my updated results :
| renderer | results |
| ---------- | ------- |
| Celshade | nothing works : objects not rendered / no physics |
| Mobile  | linked objects renderered and instanced / Physics collisions not working but gravity does : red cylinders are passing through the plane |
| Desktop | linked objects renderered and instanced / Physics collisions not working but gravity does : red cylinders are passing through the plane |

**Comment by onelsonic** [comment]
I think I found the issue in the Celshade render.
I created a pull request to fix it : https://github.com/armory3d/driver_celshade/pull/11

**Comment by onelsonic** [comment]
Closing this for now.
please note that for now when using instancing the physics only react to the parent object.

as @QuantumCoderQC mentionned it should be possible having separate physics on each instances.
We might need some performances tests to check the benefit of this.

> 
> 
> > As for the physics part of this issue, do you think that supporting physics on instances (changing their instance data through some bridge code?) would be practical? Otherwise I think we can close the issue.
> 
> Yes, it should be possible. Since the instancing used in this case is CPU instancing*, it should be possible to create physics objects without mesh attached to them(maybe RigidBody trait to an Empty objects?). Then set the Vertex Buffer with these transforms, to be sent to the GPU
> 
> *CPU instancing: passing the location, rotation and scale datas to the GPU every frame via VB and instanced rendering in GPU
