### ISSUE TITLE
[2.93] Walk navigation has gone

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2214]
I'm unable to use walk navigation and got the following warning: `Error: Trait 'armory.trait.WalkNavigation' referenced in object 'DefaultCamera' not found`

**Comment by MoritzBrueckner** [comment]
Have you tried disabling DCE (dead code elimination) in the Armory exporter configuration? I had a similar issue that I resolved by adding `@:keep` metadata to the trait class as a workaround. Still a bit strange though why the compiler doesn't recognize on its own that the trait is used somewhere.

**Comment by knowledgenude** [comment]
I don't know what i had done, but now it is working again. Apparently just restarting the PC solved it for me.

Thanks for your help as always :+1:
