### ISSUE TITLE
[Logic nodes] Break for the array loop?

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2218]
![image](https://user-images.githubusercontent.com/20190653/120012076-50414880-bfdf-11eb-8ebd-c785aa51941c.png)

**Comment by MoritzBrueckner** [comment]
The [`Loop Break`](https://github.com/armory3d/armory/wiki/reference#loop-break) node should work here :)

**Comment by ItsCubeTime** [comment]
Ah I forgot about that one :) thanks
