### ISSUE TITLE
Publishing error.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#222]
So... this is half a bug report, half a question.

In my Windows+amd card computer, I seem not to be able to build.
I have followed and downloaded scene5 example, and when I reach the end of the tutorial, it says you can publish the project either in html, or any other target.

If I do, a message appears 'Build failed' Check console.

Console says this.

![error publishing from windows](https://user-images.githubusercontent.com/12383027/29171057-716f3584-7ddb-11e7-8a18-899d9e8ed5ca.jpg)

Now the question.
If I try to do in my linux+Nvidia card computer, publishing happens with no errors, but what I obtain is in the case of html, a group of folders in which one of them is index.html. If I open that file an empty browser opens. It doesn't contain anything. I can play the .html version ok if I use the link from the scene tutorial link.

If I publish for Linux, a group of folders appears, but I don't know what to look to open the game example. I dont find any executable-like icon for Linux... (maybe is there but I haven't found it) What does I suppose I'm looking for?

If I publish for  Windows, to take the build in a pen to my other pc, a group of folders appears, but I don't manage to find any .exe file. Even searching in folders using the search function, looking for '.exe' File. 

Can we have some instructions maybe in the manual on what to expect or do, when publishing projects? 
*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
For the first issue - it appears to be somehow mixing OpenGL and Direct3D. Did you play with Graphics API setting or is it all default? It should work with both now, maybe build 11 being a bit old now is the culprit. Will test.

For the question - started to work on this more and docs are popping up at:
https://github.com/armory3d/armory_docs/blob/master/platforms

Notably Linux and MacOS instructions are still missing, but will fix that. It's probably also safer to use these with git version, or build 12 which should be finally getting out in coming 2-3 days. :)

**Comment by ja-moli** [comment]
I didn't touch anything in the API. All default.
Okm let's wait for build 12 and see what happens.

**Comment by luboslenco** [comment]
Should no longer happen, please reopen if issue persists.
