### ISSUE TITLE
[minor version issue] ArmorySDK-2021-6 still says Version: 2021.5.0 in Armory's addon preferences (in Blender)

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2223]
![image](https://user-images.githubusercontent.com/20190653/121342039-8eb0fe80-c921-11eb-8bef-53f559a477ad.png)

(Screenshot takein in 2021-6)

**Comment by MoritzBrueckner** [comment]
It should be [updated already](https://github.com/armory3d/armsdk/blob/48080d9418be2abcd067d68224b88e00223ec09b/armory.py#L9). Did you use the `Update SDK` operator in the user preferences? Maybe it is unable to update the armory.py file itself. May I ask what your operating system is?

**Comment by ItsCubeTime** [comment]
> It should be [updated already](https://github.com/armory3d/armsdk/blob/48080d9418be2abcd067d68224b88e00223ec09b/armory.py#L9). Did you use the `Update SDK` operator in the user preferences? Maybe it is unable to update the armory.py file itself. May I ask what your operating system is?

Windows and yes, I used the update button
