### ISSUE TITLE
Bone Animations and Blending Improvements

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2244]
Hi @luboslenco ,

The current `Animation` and `BoneAnimation` class in `Iron` are basic and are limited in many aspects.

Some of the down sides are:

1. Cannot play more than one animation at the same time on an Armature
2. Cannot blend different animations and at different intervals. It is hard coded to blend only two animations, the current and the one played before. Hence no control over what to blend.
3. No animation masking. When animation is played, it is played through the armature. But is must be possible to set a mask on the Armature to play animations on certain parts of the Armature. 

With these in mind, I plan to improve these above mentioned classes in iron. But, before I begin experimenting, I would like to know if these changes would be accepted. Or, should I make a separate class for these. 

Best Regards,
QC

**Comment by luboslenco** [comment]
Hi, sorry I missed the post. Would be awesome to have these improvements in the iron classes!
