### ISSUE TITLE
Combination of Gate node and Select node gives false result

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2246]
**Description**

A logic node setup as shown below always prints "A", while it should print "B".

![image](https://user-images.githubusercontent.com/55564981/124327093-d70db600-db87-11eb-947f-6031698b59fa.png)

However, peculiarly, adding a print node in between solves the issue:

![image](https://user-images.githubusercontent.com/55564981/124327452-41bef180-db88-11eb-9b99-210225a144ab.png)

The above node tree prints "false" and "B".

**To Reproduce**
Simply use the provided node setup and check the debug console.

**Expected behavior**
The combination fo these nodes must return proper value.

**System**
Blender: 2.93
Armory: v2021.6 ($Id: 23e3f17083182bae1baa281791b3eb886ccb70fa $)
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
This is probably a *much* more fundamental issue as it looks like and I'm actually pretty baffled that this wasn't much of an issue before.

Have a look at the `node.runOutput()` function:

https://github.com/armory3d/armory/blob/738a2170014d8eabef53c214ac42aee71474ca74/Sources/armory/logicnode/LogicNode.hx#L39-L50

`outputs[i]` contains a list of all nodes that are connected to the output `i`, so `o` is a node here (maybe a bit unfortunate naming). In the inner for loop, we iterate over all the inputs of that node and if the node that is connected to the input of `o` is our current node, the node is executed. So what this means is that when one node is connected multiple times to another node, only the first connection is considered at all (this explains why adding print nodes solves the issue). How could something like this go unnoticed for years? 😮 We should really think about adding some basic unit testing for some classes.

I think we instead need to use `Link` objects like in Blender that store `from` and `to` nodes and indices and then one input and one output each share one link instance. Maybe there are more clever solutions, if you know one let me know :)

**Comment by QuantumCoderQC** [comment]
Nice find!

Now I too am surprised this did not cause much of an issue. Probably because most odes have just one input. 

> I think we instead need to use Link objects like in Blender that store from and to nodes and indices and then one input and one output each share one link instance. Maybe there are more clever solutions, if you know one let me know :)

I think the `LogicNodeInput` somewhat behaves like a `Link`. Its just missing a field.

Current:
https://github.com/armory3d/armory/blob/738a2170014d8eabef53c214ac42aee71474ca74/Sources/armory/logicnode/LogicNode.hx#L59-L68

Modified:
```Haxe
class LogicNodeInput {

	@:allow(armory.logicnode.LogicNode)
	var node: LogicNode;
	var from: Int; // Socket index
        var to: Int; //Socket index of the previous node that connects to this node

	public function new(node: LogicNode, from: Int, to: Int) {
		this.node = node;
		this.from = from;
                this.to = to;
	}
```

Also, we need to modify on the python side here:

Current:
https://github.com/armory3d/armory/blob/738a2170014d8eabef53c214ac42aee71474ca74/blender/arm/make_logic.py#L215

Modified:
```python
f.write('\t\t' + name + '.addInput(' + inp_name + ', ' + str(inp_from) +  ', ' + str(inp_to) + ');\n')
```

Then we could make a check like so:
Current:
https://github.com/armory3d/armory/blob/738a2170014d8eabef53c214ac42aee71474ca74/Sources/armory/logicnode/LogicNode.hx#L39-L50

Modified:
```Haxe
function runOutput(i: Int) {
		if (i >= outputs.length) return;
		for (o in outputs[i]) {
			// Check which input activated the node
			for (j in 0...o.inputs.length) {
				if (o.inputs[j].node == this) {
                                     if(o.inputs[j].to == i) {
					      o.run(j);
					      break;
                                        }
				}
			}
		}
	}
```

What do you think of this solution?

**Comment by MoritzBrueckner** [comment]
Looks good to me :) If you want to create the PR for this, maybe rename `o` to something more verbose while your at it.
