### ISSUE TITLE
Shape keys

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#225]
shape key  didnt work in armory
*(optional - drag & drop zipped .blend file here)*

**Comment by ItsCubeTime** [comment]
Honestly this is a requirement for any game engine. You cant use bones for everything and its far from ideal.

**Comment by Skehmatics** [comment]
This has been a long requested item, so I'm opening a bounty ($75 to start):

https://www.bountysource.com/issues/48360495-shape-keys

**Comment by QuantumCoderQC** [comment]
Hi!

Yes, I had just started working on this. I might have a basic shapekey support sometime early next week. Then required extra features can be added as we go.

**Comment by MoritzBrueckner** [comment]
Closing this issue as shape keys are now implemented in https://github.com/armory3d/armory/pull/2375 by the awesome @QuantumCoderQC!
