### ISSUE TITLE
characters 21-25 : On static platforms, null can't be used as basic type kha.Color

### ISSUE THREAD

**Issue by ItsCubeTime** [armory3d/armory#2253]
![image](https://user-images.githubusercontent.com/20190653/124598757-407e1500-de65-11eb-88a3-a852ff0872dd.png)

[NullCantBeUsedAsBasicTypeKhaColor.zip](https://github.com/armory3d/armory/files/6769997/NullCantBeUsedAsBasicTypeKhaColor.zip)

To reproduce, build the project with the configured settings for android.

**Comment by ItsCubeTime** [comment]
Workarounds are as welcome as solutions. I havent managed to get past this at all - in other words. I cant build for Android at the time being.

**Comment by sh-dave** [comment]
try `var color: Null<kha.Color> = kha.Color.fromFloats(0.1, 0.1, 0.1);` to tell haxe it's a nullable int
