### ISSUE TITLE
TRANSPARENT PROBLEM

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#226]
![31](https://user-images.githubusercontent.com/23359603/29456286-a8840c32-841d-11e7-868d-03da1ae2b1ed.png)

*(optional - drag & drop zipped .blend file here)*
![32](https://user-images.githubusercontent.com/23359603/29456308-bd5dd926-841d-11e7-87e0-5560116ec3e2.png)

**Comment by luboslenco** [comment]
Will investigate.

If you are testing build 12, you can also try the new 'Discard Transparent' feature located in Material Data - Armory Props:
<img width="306" alt="disc" src="https://user-images.githubusercontent.com/3685704/29457082-ba0af04c-8418-11e7-863b-2c405a2058cc.png">

It basically throws aways pixels under specified opacity, so no depth problems (but pixels end up either visible or not).

Example:
https://github.com/armory3d/armory_examples/tree/master/material_discard

**Comment by Xristoskr** [comment]
it work but we have another problem leaf is visible only under specif angle, distance
![35](https://user-images.githubusercontent.com/23359603/29489597-6d283544-852d-11e7-896f-883fdd20a8b6.png)
![36](https://user-images.githubusercontent.com/23359603/29489593-6d19a6c8-852d-11e7-9bb2-6c80b114439d.png)
![37](https://user-images.githubusercontent.com/23359603/29489594-6d1d86ee-852d-11e7-8092-3126b0a452a5.png)
![38](https://user-images.githubusercontent.com/23359603/29489595-6d23065a-852d-11e7-956f-4836b244a10c.png)

**Comment by Xristoskr** [comment]
another problem  shaders bark and leaf
cycles
![41](https://user-images.githubusercontent.com/23359603/29489694-80f4e854-852f-11e7-85c1-63292f01ca68.png)
armory
![42](https://user-images.githubusercontent.com/23359603/29489695-8d132772-852f-11e7-8884-31d3df781c1d.png)

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/570.
