### ISSUE TITLE
Don't know how to cast null(f32) to f64 [Uniforms Manager]

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2265]
This error is in `armory/Sources/armory/trait/internal/UniformsManager.hx:109: characters 26-40 : Don't know how to cast null(f32) to f64` when trying to compile to **Android (C)**

Changing **var value: Float = constant.float** to **var value = constant.float** solved the issue for me, but i don't know what this change can affect

Also i guess there is a typo in the UniformsManager class, we got **"unifrom"** instead of **"uniform"**.

**Comment by QuantumCoderQC** [comment]
Hey @knowledgenude ,

Thanks for pointing the errors out.

Also, could you please check if this fix solves also for Windows C. For me I am able to build and publish without any errors. But when I build the solution in Visual Studio, I get an error with regards to 'Kore::Mouse::unlock'

**Comment by knowledgenude** [comment]
> I get an error with regards to 'Kore::Mouse::unlock'

That is strange. This should be unrelated to this issue, but maybe you could try to build with this fix and see what happens... Any case i can try to build a project later and see if this issue also happens for me :)

And yes! The same error gets fixed for Windows (C) and Linux (C), but unlikely in your  case i am unable to publish a build without the mentioned fix.
