### ISSUE TITLE
Cannot build applications for Windows(C) and Android(C) targets

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2267]
**Description**
The project can be built and published inside of Blender, as a Visual Studio solution or an Android Studio project. 

However, when trying to build the application in Visual Studio or Android studio I get the following errors:
```
1>E:\Armory\ArmorySDK\Kha\Backends\KoreHL\KoreC\system.cpp(49,37): error C2660: 'Kore::Mouse::unlock': function does not take 1 arguments
1>E:\Armory\ArmorySDK\Kha\Kinc\Sources\Kore\Input\Mouse.h(17,8): message : see declaration of 'Kore::Mouse::unlock' (compiling source file ..\..\..\..\Armory\ArmorySDK\Kha\Backends\KoreHL\KoreC\system.cpp)
1>E:\Armory\ArmorySDK\Kha\Backends\KoreHL\KoreC\system.cpp(53,45): error C2660: 'Kore::Mouse::canLock': function does not take 1 arguments
1>E:\Armory\ArmorySDK\Kha\Kinc\Sources\Kore\Input\Mouse.h(14,8): message : see declaration of 'Kore::Mouse::canLock' (compiling source file ..\..\..\..\Armory\ArmorySDK\Kha\Backends\KoreHL\KoreC\system.cpp)
1>E:\Armory\ArmorySDK\Kha\Backends\KoreHL\KoreC\system.cpp(57,46): error C2660: 'Kore::Mouse::isLocked': function does not take 1 arguments
1>E:\Armory\ArmorySDK\Kha\Kinc\Sources\Kore\Input\Mouse.h(15,8): message : see declaration of 'Kore::Mouse::isLocked' (compiling source file ..\..\..\..\Armory\ArmorySDK\Kha\Backends\KoreHL\KoreC\system.cpp)
```

I suspect it is due to some version mismatch.

**To Reproduce**
Build and publish a default cube project to either Windows C or Android. Then, Build the project with Visual Studio or Android Studio. The error should appear. 

**Expected behavior**
The project must build and run.

**System**
Blender: 2.93
Armory: v2021.7 ($Id: 5533755fad0369c580ed2760e777e6d88341d0fb $)
OS: Windows 10

**Comment by MoritzBrueckner** [comment]
> I suspect it is due to some version mismatch.

It could indeed be Armory's Kha version, the last "real" update was 9 months ago but only the Kinc submodule was regularly updated. @luboslenco do you think updating the armory3d/Kha backends and sources would solve this or does it look like a Kha issue?

**Comment by onelsonic** [comment]
I have similar errors trying to build the exported android project on windows10:

short log:
```
C:\armory\Kha\Backends\KoreHL\KoreC\system.cpp:49:29: error: too many arguments to function call, expected 0, have 1
C:\armory\Kha\Backends\KoreHL\KoreC\system.cpp:53:37: error: too many arguments to function call, expected 0, have 1
C:\armory\Kha\Backends\KoreHL\KoreC\system.cpp:57:38: error: too many arguments to function call, expected 0, have 1

C:\armory\Kha\Kinc\Sources\Kore\Input\Mouse.h:17:3: note: 'unlock' declared here
C:\armory\Kha\Kinc\Sources\Kore\Input\Mouse.h:14:3: note: 'canLock' declared here
C:\armory\Kha\Kinc\Sources\Kore\Input\Mouse.h:15:3: note: 'isLocked' declared here

```
full log:
https://github.com/onelsonic/armory_tests/blob/master/full-log.txt

**Comment by QuantumCoderQC** [comment]
Hi @luboslenco ,

Since this is a major issue affecting multiple platforms, I am **bumping** this issue. Some of us developers tried replacing the current versions of Kha and Krom Bin with the latest versions, but still could not get it to work. 

It would be great if you could please spare some time to have a look at this issue. 

A few things to consider about updating to latest versions of Kha and Krom as this offers newer features such as web workers and a few other fixes. This is crucial for further development of NavMesh, Networking and Multithreaded Physics. 

Thanks!

**Comment by MoritzBrueckner** [comment]
Yesterday I tried again to make it work by rebasing armory3d/Kha onto the newest Kode version (this was rather painful) and to use the newest Armorcore, but unfortunately the game just instantly crashed. It didn't look like there is some incompatibility with the changed Krom.hx (apart from `Krom.init()` which I updated accordingly), so I gave up again.

@luboslenco Sorry to bother you again, but this is a really critical issue as half of the targets are basically unusable right now. Maybe, if it's too much work to keep Armorcore compatible with Armory and armory3d/Kha (with all the work going into Armorpaint currently): what about going back to Kode/Krom and Kode/Kha for Armory? I'm not sure, maybe it is a bad idea and I don't like the Chakra compile times, but this way we could have a more stable backend and could even contribute back to the Kha community.

**Comment by luboslenco** [comment]
Sorry about the delay, https://github.com/armory3d/Kha is meant to be a regular, latest Kha. But the problem is that as far as I can tell this still stands:

>  It looks like lockInt16() is no longer available in the kha/html5 backend:
https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/graphics4/VertexBuffer.hx
But it's still available in the other kha backends:
https://github.com/Kode/Kha/blob/master/Backends/Kinc-hxcpp/kha/graphics4/VertexBuffer.hx
https://github.com/Kode/Kha/blob/master/Backends/Krom/kha/graphics4/VertexBuffer.hx
Here are related Kha commits I found:
Kode/Kha@5c0bf12
Kode/Kha@2e456d4
So the lockInt16() is being unified with lock(), but looks like it's not yet finished in the latest Kha.

@MoritzBrueckner did you get around it? We need to get `lockInt16()` working for html5 backend otherwise it will not work.

**Comment by RobDangerous** [comment]
I was summoned via weird comments in a commit of mine. lockInt16 is indeed going away, it's getting replaced by fancier array types which can be used as whetever you like. I think in html5 that already works, please give it a try.

**Comment by onelsonic** [comment]
Sorry, just wanted to add it as a reference link but it weirdly created a comment in the actual Kha repo...
I don't know how

**Comment by RobDangerous** [comment]
You can click on line numbers in diffs (and lots of other places on GitHub) and then just paste the url it creates in the address bar ala https://github.com/Kode/Kha/commit/89b12fbfd0df200273fc98f686b650d3e52999d4#diff-0fac39ebe2094f913aa314ed002792be9a300dfc3bce3f70682098b829cb302dL119

**Comment by onelsonic** [comment]
that's how I do it usually and I just discover it only works on the actual files not commits or PR, where it will create comments that's weird.

**Comment by RobDangerous** [comment]
No worries. Also please create issues and/or discussions in the Kha or Kinc repo for ploblems you run into, everyone - or add comments to existing issues or use a thumbs up to upvote issues (GitHub can nowadys sort by that). I sure have scared some Armory fans away by telling them I can't work on reports ala "crashes in Armory when I do this and that" but once you know it's a Kha or Kinc issue and you have some way for me to look at it without having to click things in Blender (I'm not good at clicking things, haven't played enough fps games) I'd very much like to know about it.

**Comment by MoritzBrueckner** [comment]
The problem seems to be that on html5 `lock()` still/again returns a `Float32Array` ([source](https://github.com/Kode/Kha/blob/e9d23d1c2a34bf4823f078f10be6119c1d1f7e74/Backends/HTML5/kha/graphics4/VertexBuffer.hx#L115), seems to come from [this](https://github.com/Kode/Kha/commit/2e456d4) commit). Is this worth a Kha issue?

As a temporary workaround we could simply move [this line](https://github.com/Kode/Kha/commit/5c0bf12#diff-0fac39ebe2094f913aa314ed002792be9a300dfc3bce3f70682098b829cb302dL120) to the necessary places in Armory/Iron on kha_html5.

**Comment by RobDangerous** [comment]
That's not an issue because in HTML5 Float32Array is just an abstract over ByteArray. As is Int16Array. And that's also the plan for other targets.

**Comment by QuantumCoderQC** [comment]
I was able to adapt `iron` to the git version of Kode and Kha for the html5 target with the following [changes ](https://github.com/QuantumCoderQC/iron/commit/ab66881baac680c59bd2827ff1b31a065713468b). now the default cube scene runs without errors when targeted to html5. 

But unfortunately, targeting to Krom still crashes.

**Comment by QuantumCoderQC** [comment]
This issue was fixed after updating to latest Kode repositories. Thanks a lot @luboslenco !

**Comment by luboslenco** [comment]
Thanks for the https://github.com/Kode/Kha/pull/1357!
