### ISSUE TITLE
Child object does not move, rotate or scale together with parent object

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#227]
Hi @luboslenco,

When parent object is moved/rotated/scaled the child object should also be moved/rotated/scaled but it doesn't happen. See attached test file (keyboard keys t, r, s). Is it a bug or am I missing something?

[bug_report.zip](https://github.com/armory3d/armory/files/1236345/bug_report.zip)

Kind Regards,
Martin

**Comment by luboslenco** [comment]
Marking as OK for now.
