### ISSUE TITLE
Bloom example stopped working with Blender 2.93

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2272]
not sure if it needs specific settings but the Bloom example has stopped working with the upgrade to Blender 2.93 see below:
https://github.com/armory3d/armory_examples/tree/master/render_bloom

Blender 2.93 - Armory 2021.7.0 (current repo) : no Bloom effect
<img width="481" alt="2021-07-14 19_56_38-bloom" src="https://user-images.githubusercontent.com/53947594/125670138-a8d0ac4e-e5e1-403b-9ce5-92aaa6264195.png">

Blender 2.83 - Armory 2021.5.0 : Bloom effect with blue glow
<img width="481" alt="2021-07-14 19_53_17-bloom" src="https://user-images.githubusercontent.com/53947594/125669379-990b190d-8449-425b-a753-8dd78a7a0841.png">

Blend File: [https://github.com/armory3d/armory_examples/blob/master/render_bloom/bloom.blend?raw=true](https://github.com/armory3d/armory_examples/blob/master/render_bloom/bloom.blend?raw=true)

**Comment by tong** [comment]
Works for me.
blender 2.93.1 / armory-git

![Screenshot from 2021-07-14 20-15-05](https://user-images.githubusercontent.com/203646/125672167-b75754df-4fdf-4aaa-bc6d-37977e0bd80f.png)

**Comment by knowledgenude** [comment]
Also works for me. You could try to increase the bloom strenght in the renderpath settings, but seems it is not enabled in the screenshot you send.

**Comment by tong** [comment]
try https://tong.github.io/armory_examples_browser/#examples-render_bloom
… should work.

**Comment by onelsonic** [comment]
thanks for your feedback.
I found the issue, depending on if the HDR option (under Renderer) is ON or OFF the Bloom threshold required to get a similar effect changes...

**Comment by MoritzBrueckner** [comment]
I think this is actually expected behaviour, if you enable HDR you can have colors with values > 1. In order to still display that on a regular computer display there is some tonemapping at the end of the frame to compensate for that, but the bloom shader probably works on the HDR values (if HDR is enabled). Do you know how other engines handle this? Do they automatically change the threshold depending on the HDR setting?

**Comment by onelsonic** [comment]
Yep all good 👍
I made some tests and it behave in a similar fashion as other engines.
Only thing I noticed is a problem with the Bloom on Apple devices now.
I will open it in another issue as I found a fix for it.
Thanks
