### ISSUE TITLE
Armory templates not building with Blender 2.93

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2273]
[https://github.com/armory3d/armory_templates](https://github.com/armory3d/armory_templates)
I tried to compile the templates examples and most of them do not compile in Blender 2.93
I get the following error in most cases :

```
Armory v2021.7 ($Id: 5533755fad0369c580ed2760e777e6d88341d0fb $)
Armory: Using CPU for environment render (might be slow). Enable CUDA if possible.
Exporting Scene
WARNING: Cube.031 users Cube.001 and Cube.002 differ in modifier stack - use Make Single User - Object & Data for now
Scene exported in 12.755s
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Finished in 15.111s
WARNING: 1 warning occurred during compilation
ERROR: Build failed, check console
```

**Comment by tong** [comment]
I am currently working on fixing the errors in armory_templates and armory_examples.
This branch https://github.com/tong/armory_templates/tree/examples-browser-compat already has some of them fixed, more to come. 

See: https://github.com/armory3d/armory_templates/issues/11

**Comment by tong** [comment]
The template projects should now [build without errors](https://github.com/armory3d/armory_templates/actions).
