### ISSUE TITLE
height map pronlem 

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#229]
when i add height map the objecto is invisible
![43](https://user-images.githubusercontent.com/23359603/29562827-9dbdb734-8743-11e7-8220-d504fee2af73.png)
![44](https://user-images.githubusercontent.com/23359603/29562828-9e1fdb4e-8743-11e7-9473-473fd7ad5fd4.png)

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Fixed in https://github.com/Kode/Kore/commit/1f49f63b5cab810b29cce9f21d8e5e8221b6500f, will be included in next release.

**Comment by luboslenco** [comment]
material_tessellation example on Windows + build 14 now working.
