### ISSUE TITLE
Particle emitter issues

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2294]
1. The position of particles from child objects are static
2. Only the child object particles has the size that match Blender viewport

Move the cube around with the physics drag trait
[particle.zip](https://github.com/armory3d/armory/files/6931941/particle.zip)

**Comment by QuantumCoderQC** [comment]
When you mean "Static", do you mean that the particles do not show any physics behavior? In that the particles always move towards the gravity regardless of the orientation of the emitter?

**Comment by knowledgenude** [comment]
No, it just stays static, doesn't move or rotate with the emitter (differently from the particles of its parents)

**Comment by QuantumCoderQC** [comment]
@knowledgenude Please confirm if this issue was fixed.

**Comment by knowledgenude** [comment]
@QuantumCoderQC all issues i mentioned got fixed, thanks!
