### ISSUE TITLE
Bloom exemple issues on Android : Kinc: Uniform PPComp10 / PPComp11 not found.

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2314]
Trying to compile the Bloom example to Android.
I get the following error with a black screen, then the App crashing :
```
W/Kinc: Uniform PPComp10 not found.
W/Kinc: Uniform PPComp11 not found.
```

https://github.com/armory3d/armory_examples/tree/master/render_bloom

**Comment by knowledgenude** [comment]
I don't think bloom is supposed to work in Android, but did you tried any other postprocess filter? IRC if you check the **postprocessing checkbox** in the **renderpath settings** is sufficient to get a black screen in Android (even with everything turned "off"). Maybe that is the main cause of the issue. I would test it again by myself but Android Studio doesn't likes me...

**Comment by MoritzBrueckner** [comment]
Fixed in https://github.com/armory3d/armory/pull/2315.
