### ISSUE TITLE
cant play animation 

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#232]
i create  animation hit f5 and character is  stuck
![51](https://user-images.githubusercontent.com/23359603/29659744-df508a34-88c7-11e7-8f34-879a1ac74f86.png)
![52](https://user-images.githubusercontent.com/23359603/29659749-e0b7a538-88c7-11e7-808d-94134ce3fff9.png)
![53](https://user-images.githubusercontent.com/23359603/29659750-e1670f5a-88c7-11e7-9aa4-910456a46775.png)

*(optional - drag & drop zipped .blend file here)*

**Comment by Xristoskr** [comment]
https://drive.google.com/open?id=0B3hadYdOOg8USGMycnZXc1B3YjA

**Comment by Xristoskr** [comment]
Any news ?

**Comment by luboslenco** [comment]
Thanks for the blend file! I can reproduce the animation is stuck, investigating today.

**Comment by Xristoskr** [comment]
armory support shapekey ?

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/513, still an issue..
