### ISSUE TITLE
Blender UI for Android target version

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2324]
Something seems off with the Blender UI for Android target version : 

**_code :_**
3 values for each field

- Compile Version SDK : default=29, min=26, max=30
- Minimal Version SDK : default=14, min=14, max=30
- Target Version SDK : default=29, min=26, max=30

https://github.com/armory3d/armory/blob/55cfead0844923d419d75bf4bd677ebed714b4b5/blender/arm/props.py#L144-L146

**_Blender interface:_**
1 value for each field

- Compile Version SDK : default=29
- Minimal Version SDK : default=14
- Target Version SDK : default=29

<img width="500" alt="2021-09-06 11_41_15-arm" src="https://user-images.githubusercontent.com/53947594/132196497-a6b8aa1a-058e-4a52-b69c-352b20568be2.png">

**Comment by MoritzBrueckner** [comment]
Hi, what exactly is the issue here? The min/max in the code are hard minimums/maximums for the sliders, that means that you can't change the value outside of the given range. They are not visible in the UI otherwise.

**Comment by onelsonic** [comment]
Ok this is limiting the slider values, fine then.

Only one thing the current Android studio version uses these names now : 
```
<uses-sdk android:minSdkVersion="integer"
          android:targetSdkVersion="integer"
          android:maxSdkVersion="integer" />
```
https://developer.android.com/guide/topics/manifest/uses-sdk-element.html

Here a couples pull request to reflect more modern Android API I have also added the default values for Android Oreo :
https://github.com/armory3d/armory/pull/2326
https://github.com/armory3d/armory/pull/2325
