### ISSUE TITLE
Error while trying to play audio using Browser runtime

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2337]
There is .wav, .mp3 and .ogg formats in the Bundled folder just to make sure.

Test file: [test.zip](https://github.com/armory3d/armory/files/7164594/test.zip)

**To reproduce:** hit play
Tested on Linux

```
Scene exported in 0.001s
(node:5115) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'build_untitled/debug/html5/Step_On_Grass.ogg'
(node:5115) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Finished in 1.669s
WARNING: 2 warnings occurred during compilation
127.0.0.1 - - [14/Sep/2021 12:37:36] "GET /build_untitled/debug/html5/ HTTP/1.1" 200 -
127.0.0.1 - - [14/Sep/2021 12:37:36] code 404, message File not found
127.0.0.1 - - [14/Sep/2021 12:37:36] "GET /build_untitled/debug/html5/kha.js HTTP/1.1" 404 -
127.0.0.1 - - [14/Sep/2021 12:37:36] code 404, message File not found
127.0.0.1 - - [14/Sep/2021 12:37:36] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by tong** [comment]
Does https://disktree.net/app/armory_examples_browser/examples/sound/ work ?
HTML5 requires user gestures to use the webaudio api, maybe it's just a click away ;-)

**Comment by knowledgenude** [comment]
I forgot to attach the example file... i need to remeber to never do two things at the same time :-1: 

> Does https://disktree.net/app/armory_examples_browser/examples/sound/ work ?

It works :)

> HTML5 requires user gestures to use the webaudio api, maybe it's just a click away ;-)

Yes, but for some reason if i have the speaker with a .wav audio file this message appear: "Error: ENOENT: no such file or directory, stat 'build_untitled/debug/html5/Step_On_Grass.**mp3**'"
And then i put a .mp3 inside the folder and the same mensage appear but this time the .ogg file can't be found... Idk what is happening here

**Comment by MoritzBrueckner** [comment]
I can confirm this, but if I remove the .ogg and .mp3 files and keep only the .wav file, everything works (and Khamake only expects .wav files, see [this](https://github.com/Kode/Kha/wiki/Managing-Your-Assets#expected-formats)). Now it could be that Khamake interprets .ogg and .mp3 as blobs or as sounds (the former should be the case), but maybe Armory still tries to access those assets because they are in the Bundled folder an thus added to the Khafile.

**Comment by tong** [comment]
Your project works as it is for me.

Whats does not work is if i remove the Bundled folder the sound attached to speaker is not exported, which is strange since it works for the [sound example](https://github.com/armory3d/armory_examples/tree/master/sound).

**Comment by knowledgenude** [comment]
If i keep only the .wav i get this error:

```
(node:3535) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'build_untitled/debug/html5/Step_On_Grass.mp3'
(node:3535) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Finished in 2.032s
WARNING: 2 warnings occurred during compilation
127.0.0.1 - - [15/Sep/2021 09:58:29] "GET /build_untitled/debug/html5/ HTTP/1.1" 200 -
127.0.0.1 - - [15/Sep/2021 09:58:29] code 404, message File not found
127.0.0.1 - - [15/Sep/2021 09:58:29] "GET /build_untitled/debug/html5/kha.js HTTP/1.1" 404 -
127.0.0.1 - - [15/Sep/2021 09:58:29] code 404, message File not found
127.0.0.1 - - [15/Sep/2021 09:58:29] "GET /favicon.ico HTTP/1.1" 404 -
```
I will close it as isn't related to Armory, later i try to make more tests
