### ISSUE TITLE
Weather system and Day/Night cycles

### ISSUE THREAD

**Issue by chiaravalle** [armory3d/armory#2346]
Please, add to Armory a weather system (rainy, foggy, snow, etc) and a day/night sky/ambient light/etc cycles.

**Comment by HelloAmElio** [comment]
u can already do that with the sky node on the your shaders tab

**Comment by HelloAmElio** [comment]
armory already have somithing similar on your render path  you can enable and configure the fog and the water, for the day and night u can add and modify the sky node for your back ground shader and raing and sow can be made with the particle system :)

**Comment by chiaravalle** [comment]
Yes, but it would be nice to have a preset for these, just for convenience =)

**Comment by MoritzBrueckner** [comment]
Hi, this seems to be a duplicate of https://github.com/armory3d/armory/issues/108, closing this in favor of the linked issue.
