### ISSUE TITLE
2/2.5D camera

### ISSUE THREAD

**Issue by chiaravalle** [armory3d/armory#2347]
Please, add to Armory a 2D and 2.5D camera preset, it should have a fixed orientation and render orthogonal.

**Comment by HelloAmElio** [comment]
you can change the camera preset from perspective to orthographic

**Comment by chiaravalle** [comment]
Yes, but I'll have to manually orientate it. Can I have a preset with isometric/plane view?

**Comment by MoritzBrueckner** [comment]
Hi, can you please elaborate a bit what you mean by "preset"? Like a new entry in the add object menu that creates a preconfigured camera?

**Comment by chiaravalle** [comment]
Exactly

Il Sab 25 Set 2021, 15:48 Moritz Brückner ***@***.***> ha
scritto:

**Comment by tong** [comment]
This sounds way too specific to someones needs to be implemented in armory itself.

**Comment by chiaravalle** [comment]
Well, in truth isometric view is not really orthogonal, when drawing isometric view, you always introduce distortion, because vertically, the size is half as normally, so an isometric camera needs a custom matrix.
I'm in a hurry right now and can't provide so much detail, if there's something unclear, please, let me know.

**Comment by chiaravalle** [comment]
![distortion](https://user-images.githubusercontent.com/71562926/134817935-34e29155-39d1-41dc-acde-3bc531ba19ab.png)
This is an example of how viewing isometric distorts proportions versus normal orthogonal rendering.

**Comment by tong** [comment]
But isn't it still just a matter of rotating the camera to whatever projection view you want to have?

**Comment by chiaravalle** [comment]
Not really, a new projection matrix has to be defined

**Comment by chiaravalle** [comment]
![gizmos](https://user-images.githubusercontent.com/71562926/134818483-6c9050ef-90a6-4f65-8c7c-9b68f6032f7d.png)
Look at the XYZ gizmos and how they distort when using isometric view

**Comment by tong** [comment]
I don't get it.
Imho this is an isometric view:

![Screenshot from 2021-09-26 22-30-03](https://user-images.githubusercontent.com/203646/134823154-b289568e-c086-4cd6-a077-bca1f225e381.png)

I don't see any extra step required todo this.

**Comment by MoritzBrueckner** [comment]
According to [this Blender stackexchange question](https://blender.stackexchange.com/questions/135306/setting-up-an-isometric-view), it should be sufficient enough to set the correct camera angle to correctly achieve that isometric look. So I'm also not sure if this feature is really needed (as it doesn't look to be much work for the user).

Having a bundled camera trait for isometric games or even a small template in the templates repository however could be quite nice :)

**Comment by tong** [comment]
@chiaravalle Here is the screenshots blend file:
[isometric_view.zip](https://github.com/armory3d/armory/files/7232274/isometric_view.zip)

**Comment by chiaravalle** [comment]
Uhm, in fact, your screenshot is an isometric view.
My apologies. I'm used to technical drawing, with which you have to half the vertical size of what you're drawing.
