### ISSUE TITLE
Web in Safari(iOS 15.0.1)Could not link the shader program

### ISSUE THREAD

**Issue by SaxonGao-SZ** [armory3d/armory#2358]
I upgrade my iphone to iOS 15.0.1, Then I got new error in safari
```
Could not link the shader program:
Internal error compiling shader with Metal backend.
Please submit this shader, or website as a bug to https://bugs.webkit.org
compile @ kha.js:formatted:30842
kha_graphics4_PerFramebufferPipelineCache @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
kha_graphics4_ImageShaderPainter @ kha.js:formatted:30842
kha_graphics4_Graphics2 @ kha.js:formatted:30842
kha_js_graphics4_Graphics2 @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
start @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
(anonymous) @ VM41:333
(anonymous) @ kha.js:formatted:30842
(anonymous) @ kha.js:formatted:30842
```
How make it work in Safari iOS 15.0.1?

Project setting:
![image](https://user-images.githubusercontent.com/37361895/136652741-d2f155c5-2c05-4c53-8c0a-c2c19026a2cb.png)

![image](https://user-images.githubusercontent.com/37361895/136652756-c75cd1c5-ef5b-4d09-9595-c715405431d5.png)

![image](https://user-images.githubusercontent.com/37361895/136652775-3d8a15eb-3b61-4f92-a503-29a732c2ce59.png)

**Comment by SaxonGao-SZ** [comment]
tanks.

**Comment by sh-dave** [comment]
Not sure if armory shaders can be fixed by this as well, but [here](https://github.com/Kode/Kha/pull/1369) is the PR for Kha. It might be some kind of naming chaos in the metal shader compiler. `vertexPosition` + `texPosition` are used in Kha, and i simply renamed the 2nd one to `vertexUV` and the link errors were gone.

**Comment by onelsonic** [comment]
@sh-dave nice fix.
I just updated to ios 15 and saw this issue. Nice ! 
It successfully fixed the shaders display using the commit in Kha.

In the other hand I can see another issue : now on iOS only realtime shadows are now in super low resolution and ultra pixelated...

**Comment by sh-dave** [comment]
I think this is another issue, as the shaders are still identical apart from the rename.

**Comment by MoritzBrueckner** [comment]
I'm going to close this now as the issue has been resolved, @onelsonic please open another issue about the shadows, if possible with some screenshots and more information.
