### ISSUE TITLE
android project fails to build in android studio

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#236]
Information:Gradle tasks [:app:assembleDebug]
/home/guzzard/Development/Armory3D/bug_report/build_translate/android-native-build/Sources/src/kha/DisplayImpl.cpp
Error:(59) undefined reference to \`Kore::Display::x(int)'
Error:(67) undefined reference to \`Kore::Display::y(int)'
Error:(75) undefined reference to \`Kore::Display::isPrimary(int)'
Error:error: linker command failed with exit code 1 (use -v to see invocation)
Information:BUILD FAILED
Information:Total time: 5.524 secs
Information:4 errors
Information:0 warnings
Information:See complete output in console

**Comment by luboslenco** [comment]
Fixed in https://github.com/Kode/Kore/pull/210.
