### ISSUE TITLE
android export fails with project using recast

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#237]
Armory v17.08.1
OS: linux, Target: android-native, GAPI: opengl
Exporting mesh Cube.003
Exporting mesh Cube.005
Exporting mesh Plane
Scene built in 0.01901698112487793
Exported modules: ['physics', 'navigation']
Using Kha from /home/guzzard/bin/Armory/armsdk/linux64/Kha
Creating Kha project.
Exporting asset 1 of 1 (nav_Plane.arm).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.003.arm).
Exporting asset 1 of 1 (mesh_Cube.005.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.frag.glsl).
/home/guzzard/bin/Armory/armsdk/armory/Sources/armory/trait/internal/Navigation.hx:17: characters 19-25 : Type not found : Recast

Haxe compiler error.
Build failed, check console
****

**Comment by luboslenco** [comment]
Should be fixed using  https://github.com/armory3d/haxerecast/commit/cfdf2c1e5696f1bd7df2b4524d597dc496c0900b and https://github.com/armory3d/armory/commit/8889ba2bd84e528eb491aaac38ddc811ad36a612. Tested on C++/desktop, will also try on android/ios to be sure.
