### ISSUE TITLE
Wrong normals for two-sided materials

### ISSUE THREAD

**Issue by knowledgenude** [armory3d/armory#2371]
No print because i'm on a potato. Test file:
[two-sided-normals-test.zip](https://github.com/armory3d/armory/files/7437836/two-sided-normals-test.zip)

**Comment by MoritzBrueckner** [comment]
This may have been a Kha issue that is fixed now: https://github.com/Kode/Kha/issues/1405. However let's still keep this issue open for a little while until armory3d/Kha and the Armorcore binaries are updated to make sure that things are working correctly.

**Comment by MoritzBrueckner** [comment]
Seems to be working correctly now.
