### ISSUE TITLE
sound.cpp:5:10: fatal error

### ISSUE THREAD

**Issue by Afir1** [armory3d/armory#2377]
**Description**
Android studio apk build error
ArmorySDK\Kha\Backends\Kinc-HL\KoreC\sound.cpp:5:10: fatal error:
**To Reproduce**
Try to build default scene using android studio.

**System**
Blender: 2.93.5
Armory: ArmorySDK-2021-11
OS: windows 10

QuantumCoderQC fix suggestion:
Change #include <kinc/audio1/stb_vorbis.c> to #include <kinc/libs/stb_vorbis.c>

**Comment by MoritzBrueckner** [comment]
This was fixed in https://github.com/Kode/Kha/pull/1373, thanks for the report :) Until the the Kha version is updated in Armory, please use above workaround.
