### ISSUE TITLE
exported html5 build: some files missing

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#238]
Some files are not exported with the build causing 401 errors when trying to play the project in a browser.

GET XHR http://localhost:8000/Material_001_data.arm [HTTP/1.0 404 File not found 0ms]
LoaderImpl.hx:150: Error loading Material_001_data.arm  kha.js:15396:3
loadBlob failed  kha.js:16784:4
GET XHR http://localhost:8000/Material_data.arm [HTTP/1.0 404 File not found 0ms]
LoaderImpl.hx:150: Error loading Material_data.arm  kha.js:15396:3
loadBlob failed  kha.js:16784:4
GET XHR http://localhost:8000/world_Irr_EnvSky_Rad_LDR.arm [HTTP/1.0 404 File not found 0ms]
LoaderImpl.hx:150: Error loading world_Irr_EnvSky_Rad_LDR.arm  kha.js:15396:3
loadBlob failed

However it works fine with using Armory Player to test the project in a browser. Only exporting fails.

**Build log play:**
Armory v17.08.1
OS: linux, Target: html5, GAPI: webgl
Scene built in 0.006192922592163086
Exported modules: ['physics', 'navigation']
Using Kha from /home/guzzard/bin/Armory/armsdk/linux64/Kha
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (recast.js).
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (Material_001_data.arm).
Exporting asset 1 of 1 (world_Irr_EnvSky_Rad_LDR.arm).
Exporting asset 1 of 1 (nav_Plane.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.003.arm).
Exporting asset 1 of 1 (mesh_Cube.005.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_001_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_001_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_LDR.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_LDR.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.

**Build log export:**
Armory v17.08.1
OS: linux, Target: html5, GAPI: webgl
Exporting mesh Cube.003
Exporting mesh Cube.005
Exporting mesh Plane
Scene built in 0.019074201583862305
Exported modules: ['physics', 'navigation']
Using Kha from /home/guzzard/bin/Armory/armsdk/linux64/Kha
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (recast.js).
Exporting asset 1 of 1 (nav_Plane.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.003.arm).
Exporting asset 1 of 1 (mesh_Cube.005.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-image.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.

**Comment by luboslenco** [comment]
Fixed! https://github.com/armory3d/armory/commit/2238ee90bed008ec469752b519c31f1ab2afa6d7
