### ISSUE TITLE
Linux Mint 18: Blender locks up after pressing play.

### ISSUE THREAD

**Issue by K9Crunch** [armory3d/armory#24]
Version: Armory_p01_linux64.tar.bz2

(Tested on two different computers.)

Computer: NUC5i7RYH (Intel NUC)

     -OS: Linux Mint 18 with kernel 4.4.0-45-generic

Computer: Alienware 15 laptop (Tested with the Nvidia driver, then with the intel driver, same result.)

     -OS: Linux Mint 18 with kernel 4.4.0-45-generic

     -OS: Windows 10. (Windows 10 worked, however I had to use 7-Zip to uncompress the file because window’s builtin unzip kept complaining about file paths are too long.)

I had to install these missing dependencies on Linux Mint:
libOpenImageIO.so.1.6
libboost_locale.so.1.58.0
libjemalloc.so.1

After pressing "Play in Viewport" It will compile then nothing happens and I cannot click on anything in blender. (The viewport does not update, it just shows the cube as it was before I pressed play.) Since I cannot click the stop button I have to close the console window to end blender.

**Intel NUC - Console output**
Color management: using fallback mode for management
Read new prefs: /home/will/.config/blender/2.78/config/userpref.blend
found bundled python: /home/will/Downloads/Armory/2.78/python
Info: Total files 1 | Changed 1 | Failed 0
Exporting mesh Cube
Scene built in 0.0019407272338867188
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_CompoFXAA.arm).
Exporting asset 1 of 1 (deferred_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (deferred_path_low.arm).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoFXAA.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoFXAA.vert.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Compiling code.
Done.

**Alienware 15 with INTEL driver enabled - Console output:**
Color management: using fallback mode for management
Read new prefs: /home/will/.config/blender/2.7
Warning! Unable to find a multisample pixel format that supports exactly 16 samples. Substituting one that uses 8 samples.
found bundled python: /home/will/Downloads/Armory/2.
read blend: /home/will/Desktop/untitled.bl
Exporting mesh Cube
Scene built in 0.002157926559448242
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO.ar
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_C
Exporting asset 1 of 1 (deferred_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_SSAO
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO.ar
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (deferred_path_low.arm).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.fr
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.ve
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_C
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_C
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.frag.gl
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.vert.gl
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.fr
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.ve
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.frag.gl
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.vert.gl
Compiling shader 1 of 1 (world_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-image.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Compiling code.
Done.

**Alienware 15 with NVIDIA driver enabled - Console output:**
Color management: using fallback mode for management
Read new prefs: /home/will/.config/blender/2.
found bundled python: /home/will/Downloads/Armory/2.
read blend: /home/will/Desktop/untitled.
Exporting mesh Cube
Scene built in 0.0024814605712890625
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO.
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_
Exporting asset 1 of 1 (deferred_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO.
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (deferred_path_low.arm).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.frag.
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.vert.
Compiling shader 1 of 1 (deferred_indirect_EnvCol_
Compiling shader 1 of 1 (deferred_indirect_EnvCol_
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.frag.
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.vert.
Compiling shader 1 of 1 (world_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-image.frag.glsl).
Compiling shader 3 of 8 (painter-image.vert.glsl).
Compiling shader 4 of 8 (painter-colored.vert.glsl).
Compiling shader 5 of 8 (painter-text.vert.glsl).
Compiling shader 6 of 8 (painter-text.frag.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Compiling code.
Done.

**Comment by luboslenco** [comment]
Thanks for report! 'Play in Viewport' is definitely broken on Linux, will fix in the next build.

**Comment by luboslenco** [comment]
'Play in Viewport' no longer freezes on Linux in Build 2.
