### ISSUE TITLE
Splitting Armory player window area crashes on stop

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#240]
1. was not able enable addon first, had to delete the addons folder inside C:\Users\Myname\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons
then it worked

when i install Armory manually in Blender 2.79 RC2 then its working just dont have the play in viewport button which is unuseable for me... becouse time / patiency...

2. play in viewport windows size streched not same like camera..

3. apply rotation and scale completely messed up the objects location in armory... had to make them as one object to have them same location like in blender

4. camera view is not synchronized with viewport..

5. in armory viewport flying near messhes makes like shadows move ...

6. if armory vieport running and spliting window and then click on stop does crash

![armory enable bug](https://user-images.githubusercontent.com/9019563/29871193-2d3c3316-8d8b-11e7-9870-b6deb013399c.jpg)
![armory streched window and object loc](https://user-images.githubusercontent.com/9019563/29871219-4434887a-8d8b-11e7-9617-954c45eb6c72.jpg)

[Armory Game Files.zip](https://github.com/armory3d/armory/files/1263444/Armory.Game.Files.zip)

**Comment by luboslenco** [comment]
Should behave better now. Continuing with issue 6. at https://github.com/armory3d/armory/issues/123.
