### ISSUE TITLE
MeshBatch cleanup crash

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#2404]
Removing a scene when `arm_batch` is defined will crash the app. `MeshBatch.remove()` calls itself recursively. Also it doesn't seem to clean up the `nonBatched` array, so it should most likely look something like this:

```
public function remove() {
	for (b in buckets) b.remove();
	for (m in nonBatched) m.remove();
}
```

This still isn't enough to fix the issue though; it will assert a bit later with

```
GL Error 1282 ../../../Kha/Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/vertexbuffer.c.h 156
GL Error 1281 ../../../Kha/Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/vertexbuffer.c.h 226
GL Error 1281 ../../../Kha/Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/vertexbuffer.c.h 226
GL Error 1281 ../../../Kha/Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/vertexbuffer.c.h 226
../../../Kha/Kinc/Backends/Graphics4/OpenGL/Sources/kinc/backend/graphics4/vertexbuffer.c.h:128: kinc_internal_g4_vertex_buffer_set: Assertion `buffer->impl.initialized' failed.
```

As i currently don't have time to investigate this issue further i disabled batching and everything runs fine again. Just thought i'd let you know.

**System**

Blender: 2.93.5
Armory: armsdk 001142f923608ea8b2d56a1a353d6613f30166cc (with some unrelated manual merges)
OS: debian 9
Build: hashlink

**Comment by sh-dave** [comment]
Hm, look's like the followup crash is unrelated to batching as it started to happen for un-batched now as well :cry:

**Comment by MoritzBrueckner** [comment]
Hi,

do you have a stack trace for the assertion above? Otherwise I can try to reproduce it later on Windows.

I suspect that this either happens because a vertex buffer is deleted twice, or that an already deleted vertex buffer is used again (which could explain the other GL errors above). There is the `MeshBatch.Bucket.vertexBufferMap` where the vertexBuffers might still be referenced, so probably `Bucket.remove()` should look similar to this:

```haxe
public function remove() {
	vertexBuffer.delete();
	indexBuffer.delete();
	vertexBufferMap.clear();
	meshes = [];
}
```

maybe that works in combination with also clearing the `buckets` map and the `nonBatched` array in `MeshBatch.remove()` which still hold references to the removed objects?

**Comment by sh-dave** [comment]
No sorry i don't have a stacktrace available. And i think the Map.clear() won't be enough, as the map holds it's own VertexBuffer instances (created in `extractVertexBuffer`), so they should be deleted as well?

**Comment by MoritzBrueckner** [comment]
Hi, I thought I'd give this issue a try but I wasn't able to reproduce it after applying your fix for `remove()` to prevent the recursive self-call. Do you have an example file for the crash?

This is the file I used for testing: [2404-Issue-MeshBatchCleanupCrash.zip](https://github.com/armory3d/armory/files/7714698/2404-Issue-MeshBatchCleanupCrash.zip)
Does the crash also happen for you with that file? You can switch scenes with keys 1 and 2.

I was using hashlink on Windows 10 with OpenGL. DirectX outputs some refcount warnings (not sure where they come from and what they mean) but it also works. There is also no memory leak which I would suspect would happen if there were some shaders that are not correctly deleted.

**Comment by sh-dave** [comment]
Nope, your file works ok with the change applied on linux-hl as well. Might be an issue in my projects setup.

**Comment by MoritzBrueckner** [comment]
> Might be an issue in my projects setup.

Hi, did you find out more already? If you can still reproduce the issue, does the error only happen after switching back to a scene with mesh batching that was active before?

**Comment by sh-dave** [comment]
No, didn't have time to investigate this further. I'll close the issue now as your example worked for me as well.
