### ISSUE TITLE
Mouse sensitivity different depending on build type

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#241]
In play in viewport and in HTML5 builds in the browser, the mouse sensitivity is much higher compared to  Krom and C++ builds. This is on Linux, don't know if any other OS is affected.

**Comment by guzzard** [comment]
@luboslenco, mouse sensitivity is different in Chromium compared to Firefox as well. Tested on both Linux and Windows. See attached videos.

[chromium_firefox_test.zip](https://github.com/armory3d/armory/files/1540784/chromium_firefox_test.zip)

**Comment by luboslenco** [comment]
That is crazy. :O It's also a pretty big difference. Will have to look up how Kha handles this.

**Comment by luboslenco** [comment]
Appears to be ok now.
