### ISSUE TITLE
Problems compiling.... everything done like in readme, but Type not found : kha.arrays.ByteArray

### ISSUE THREAD

**Issue by jellyneck84** [armory3d/armory#2415]
When trying to compile armorypaint, i always get the following error:

Command i used:
c:\Compile\Armorpaint\armorpaint>node armorcore/make -g direct3d11
Using Kha from c:\Compile\Armorpaint\armorpaint\armorcore

Error message:
Compiling shader 8 of 8 (painter-video.vert.glsl).
c:\Compile\Armorpaint\armorpaint\Libraries\iron\Sources/iron/data/Geometry.hx:9: characters 8-28 : Type not found : kha.arrays.ByteArray
c:\Compile\Armorpaint\armorpaint\Libraries\iron\Sources/iron/data/Geometry.hx:31: characters 23-32 : Type not found : ByteArray

Haxe compiler error.

Any ideas on this? 

Thanks for your help.

**Comment by MoritzBrueckner** [comment]
Hi,

this is the wrong repository for this issue, please open this issue again on the [Armorpaint repo](https://github.com/armory3d/armorpaint).

Just by looking at the error message and at the Iron sources it seems to me that you're using an old version of Kha. Maybe the Kha files in [Armorcore](https://github.com/armory3d/armorcore) need to be updated.
