### ISSUE TITLE
Haxe compiler error error

### ISSUE THREAD

**Issue by alisahanyalcin** [armory3d/armory#2417]
**Expected behavior**
When I run node armorcore/make -g direct3d11 I get an error

and this is my error;
A:\armorpaint\Libraries\iron\Sources/iron/data/Geometry.hx:9: characters 8-28 : Type not found : kha.arrays.ByteArray
A:\armorpaint\Libraries\iron\Sources/iron/data/Geometry.hx:31: characters 23-32 : Type not found : ByteArray

Haxe compiler error.

**System**
Armory: last version i think
OS: windows 11

**Comment by Vyounesky** [comment]
Hello , I get the same ERROR too, can you tell me please how do you fix it ?
OS: Windows 10

**Comment by alisahanyalcin** [comment]
> Hello , I get the same ERROR too, can you tell me please how do you fix it ? OS: Windows 10 git version 2.34.1.windows.1 Node.js version : v16.13.1 Chocolatey v0.11.3

I was getting this error in [armorpaint](https://github.com/armory3d/armorpaint), I accidentally wrote it here while looking at the armor related repos. If you are getting this error in armorpaint, follow the steps below;


```
git checkout 1bdd741
git submodule update --init --recursive
```

![image](https://user-images.githubusercontent.com/34830846/148419792-b213a0ee-63ac-4359-a068-649fab418409.png)

**Comment by Vyounesky** [comment]
thank you, I just ignore it and continue to follow the procedure, now I'm in Visual Studio :)

**Comment by Vyounesky** [comment]
thanks
