### ISSUE TITLE
Kode Studio - Krom debug broken

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#242]
When trying to debug through Kode Studio Krom runtime is not possible to use. This error is thrown:

Launch canceled.
******** Unhandled error in debug adapter - Unhandled promise rejection: {"id":34497,"format":"Compilation failed."}

HTML5 runtime works fine.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/616.
