### ISSUE TITLE
[html5] Broken sound export

### ISSUE THREAD

**Issue by tong** [armory3d/armory#2435]
*.ogg is exported whereby *.mp3 expected.

```sh
Armory v2022.2 ($Id: 1343c1509066ed57ea07fbd2df9e079cf4c92932 $)
Exporting Scene
Scene exported in 5.622s
(node:1602026) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'build_first_person/debug/html5/fire0.mp3'
(node:1602026) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MoritzBrueckner** [comment]
What extension has the original asset file?

**Comment by tong** [comment]
wav

I am not aware of any changes responsible for this so let me double check tomorrow before doing any investigation as it might just be some dependency failure on my side.

**Comment by tong** [comment]
Just checked the [armory sound example](https://github.com/armory3d/armory_examples/tree/master/sound) and the error persists.

With wav files as source asset only the first file is exported to ogg then the error occurs. Setting the sound quality to 1.0 in blender removes  the `quality` parameter from `khafile.js` but still exports (only the first sound file) to ogg with same quality/size.

When exporting to krom with quality of 1.0 the wav file is copied as expected. With quality < 1.0 it converts to ogg but with same quality regardless the quality param.

**Comment by tong** [comment]
Strangely i can only reproduce this when using armory, not with standalone kode/kha but the error persists when using armory with kode/kha. (???)

**Comment by MoritzBrueckner** [comment]
Hm, I couldn't reproduce it so far with the latest SDK on Windows. What I did:

1. Open the sound example file from above,
2. Duplicate the speaker
3. Set another file from the `/Bundled` directory as the sound in the duplicated speaker
4. Select browser as runtime and play

I also tried unchecking the "Stream" checkbox in the armory props of the second speaker, and it also worked without problems. Is your khamake submodule inside the Kha submodule up to date?

However I experienced some similar issues in the past, but I can't remember what it was... Probably related to the quality setting and whether the audio was streamed or not, I think there was different behaviour on different platforms.

**Comment by tong** [comment]
The error happens if the path to the ffmpeg binary is not set in preferences.
Shouldn't just 'ffmpeg' be used as a default value for this?
I guess pretty much everyone has it in PATH and if not, the error message would actually tell why the export fails.

**Comment by MoritzBrueckner** [comment]
Great that you found the problem! Did I understand it correctly that Khamake silently fails or chooses different formats when ffmpeg is not present?

**Comment by tong** [comment]
I think it's both.  
The error happens around here: https://github.com/Kode/khamake/blob/b8b1bf93e1c3238b316f05d4b6a26bdee68dace9/src/Exporters/Html5Exporter.ts#L218 (with the error message above).
