### ISSUE TITLE
EvIlGoldeN

### ISSUE THREAD

**Issue by Hasnain9921** [armory3d/armory#2459]
**Which armory version is suitable for blender version 3.0.1**

**Comment by MoritzBrueckner** [comment]
Hi, there currently is no Armory version for Blender 3 as Armory only supports LTS versions (so currently that is 2.93) to be more stable. Armory will switch to Blender 3.3 LTS once it is released.

Development will happen in the https://github.com/armory3d/armory/tree/blender-3.3-lts branch which you can already use in Blender 3 (it's work in progress though and newer Blender versions may introduce breaking changes at any time).
