### ISSUE TITLE
Objects not always available on notifyOnInit() in HTML5 builds

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#246]
Sometimes objects in the scene are not available on notifyOnInit() in HTML5 builds. This issue affects empty objects and perhaps other object types. Mesh objects seem unaffected. Also, the problem does not occur when playing in viewport, Krom etc.

Console output from example when running in browser:
MyTrait.hx:23: EmptyObj cube1: null
MyTrait.hx:24: EmptyObj cube2: null
MyTrait.hx:23: Cone cube1: Mesh Object Cube1
MyTrait.hx:24: Cone cube2: Mesh Object Cube2

blend file: [html5_bug.zip](https://github.com/armory3d/armory/files/1270179/html5_bug.zip)

**Comment by luboslenco** [comment]
The problem may be the other objects are still being loaded. Currently the solution is to replace `notifyOnInit()` with `iron.Scene.active.notifyOnInit()`. The later gets called once all objects are added to the scene.

I think `trait.notifyOnInit()` as it is right now is confusing, will change that to work like you expected - ie. call it once all objects are available. Doing pre-init stuff will be still possible using `trait.notifyOnAdd()`.

**Comment by luboslenco** [comment]
`notifyOnInit()` is now called once all objects are available, should prevent these issues in the future.
