### ISSUE TITLE
Collision box differences between Eevee and Armory3D bullet

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2463]
Hi Fellas,
Thank you all for your fantastic work on Armory3D. I would like to report an issue which IMHO limits the use of Armory3D, especially compared to UPBGE. 

Just saw a vid on YT about a contraption where a double cone seems to roll uphill. The center of mass
is, of course, lowered during the action. I tried it in Blender and it even works there. 
![Eevee_Bullet](https://user-images.githubusercontent.com/89656885/159071168-e03238c5-4bc5-47f1-b7bb-fb6152c04e8f.jpg)
In Armory3D, however, its running not so well and stops prematurly. 
![Armory3D_Bullet](https://user-images.githubusercontent.com/89656885/159071286-a5010121-04ac-46a6-8b95-fbf82a2df7d6.png)

I think this is due to the fact, that the collisions shapes in Eevee and Armory3D differ too much. 
Any plans to improve that in the future? 

See example file "Fake Antigravity.blend".
[Collisionshape_issue.zip](https://github.com/armory3d/armory/files/8307132/Collisionshape_issue.zip)

**Comment by rpaladin** [comment]
I agree, Convex Hull physics should work for the boxes, as they have no concave mesh openings.
Alternatively, I was able to get the physics to run relatively as expected by switching both boxes physics type to `Mesh` instead of `Convex Hull`.

https://user-images.githubusercontent.com/69180012/159077232-a9828936-84ed-4d20-aa76-9fb23116ef04.mp4

**Comment by StrandedAlien** [comment]
Yes, but if you rewind/reset the animation to frame Zero it does not work. You started somewhere in the frame count middle with your video. Check and you will see that in case it works, physics animation does not start at frame 0. I had that as well and was very disappointed to realize that i tricked myself. It really seems not to behave alike in Eevee and Armory. Would be nice if it did.

**Comment by rpaladin** [comment]
> if you rewind/reset the animation to frame Zero it does not work. You started somewhere in the frame count middle with your video. Check and you will see that in case it works, physics animation does not start at frame 0.

I set my animation frame to start on `frame 0` and it still doesn't work if the physics type is any other except `Mesh`.

![image](https://user-images.githubusercontent.com/69180012/159085173-b6c6b226-5f0c-457b-9008-09bfcdea3714.png)

**Comment by StrandedAlien** [comment]
Hey, thanks for trying. What else did you change and what OS are you on? I am on Arch Linux/Manjaro and no it still does not work. I put everything on mesh but no dice:
![Screenshot_2022-03-18_23-19-30](https://user-images.githubusercontent.com/89656885/159092973-3987f61e-de14-47e0-ba67-afc5d60a13de.jpg)
Even worse than before, but seems to appear some fractions of a second later. 2 bad.

**Comment by StrandedAlien** [comment]
Thanks for the help. Not a bug. Please close.
