### ISSUE TITLE
wav to ogg conversion on build/export does not happen

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#247]
wav files are not converted to ogg files as expected, and therefore fail to play.

```
Could not open file hit0.ogg.
Could not open file hit2.ogg.
```
related: https://github.com/armory3d/armory_examples/issues/5

**Comment by luboslenco** [comment]
Should be now resolved in https://github.com/armory3d/armory/commit/52c1b7b45d3d1d32393d7bc60bff216d6068e7a8, https://github.com/armory3d/armory/commit/0a848c9646640e6315c232f691eb350e2a5f2796 and https://github.com/armory3d/iron/commit/54cac77117e3a59d2df74e3c6e8bf35093d235df.

On top of that sound/texture quality can now be tweaked in *Properties - Render - Armory Project - Sound/Texture Quality*. It's global setting for now, but can be later turned into per-asset setting as well.

Also, reducing *Texture Quality* below 1.0 should trigger using compressed textures in Kha, untested though. :)
