### ISSUE TITLE
On Event node does not compile

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2473]
Hello!

Following compile error:
armory3d_learn/sh3d1/Sources/arm/node/NodeTree.hx:34: characters 16-25 : armory.logicnode.OnEventNode has no field property0 (Suggestion: property1)

Haxe compiler error.
Finished in 15.910s
WARNING: 3 warnings occurred during compilation
ERROR: Build failed, check console
Project cleaned
Armory v2022.3 ($Id: c827a2b355b5e8a6d619bcce080bfd14378e0ddb $)

**To Reproduce**
Just try to compile a node setup with on event node

Also note that 22.04 still shows 22.03 when compiling.

Workaround i found: Replace property1 with property0 in OnEventNode.hx

You might want to consider to release new versions maybe every two or three month. This would give some time for testing.
I cannot really enjoy minor improvements that much, when having to swallow shot targets (HL, Android). 

Armory3D is fantastic, its like giving Blender a fourth dimension. Thank you for your work and please continue.

Cheers mates!

**Comment by MoritzBrueckner** [comment]
Hi,

because of the fact that it shows "22.03" when compiling it seems that your Armory update wasn't successful on your machine. The compile error probably happens because the event node that was updated wasn't replaced with the new version in your file because Armory only updates logic nodes when the Armory version number changes.

The download from itch.io however has the correct version number, so it's probably an issue on your end, maybe some files weren't correctly replaced? After updating the SDK path (it doesn't matter whether you downloaded the SDK from itch.io or if you used the `Update SDK` button in the preferences), always make sure to restart Blender or to have `Armory Preferences > Show Advanced > Developer Settings > Symlink armory.py` enabled, but the latter is rather experimental.

I hope this helps!

**Comment by StrandedAlien** [comment]
Hi,
thanks for the answer, but it was not helpful. Tried it, did not change a thing. Going back to 22.03 however solves the problem.
I would upload the blend, but it uses heavy pbr textures and an event-driven Koui menu to change animations and is therefore big and needs to be setup on your end.

**Comment by MoritzBrueckner** [comment]
The version number in the code is 22.04 (see [this](https://github.com/armory3d/armory/blob/f3f6467fe9f6de954b9af3f6f41689e0227d2877/blender/arm/props.py#L26) and [this](https://github.com/armory3d/armsdk/blob/7ef643fcff7ef7f88d198201881c03d0c840f929/armory.py#L9)) and it's also like that in the SDK on itch.io (I just tested it myself), so there must be something wrong with your installation. Can you please tell as precisely as possible how you updated Armory?

**Comment by StrandedAlien** [comment]
Of course. I repeated it several times now. The current log, it says 22.04 now but still has the same problem.
I remove the plugin in preferences with the remove button, close and restart Blender. Then i use the install button in preferences to install Armory by pointing to armory.py in the SDK22.04 folder, the i close and restart Blender. I now load my blend and try to compile without success. Log now:

Armory v2022.4 ($Id: dfdf68b8f477b8e62d033e9dd3edba7e6c8f331a $)
Using CPU for environment render (might be slow). Enable CUDA if possible.
Exporting Scene
WARNING: Material node type TEX_IMAGE not supported
Scene exported in 0.028s
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/Slidernodes.hx:22: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:21: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:38: characters 12-21 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:55: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:72: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:89: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:106: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:123: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:140: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:157: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)

/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:174: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:191: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:208: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)
/run/media/pas_ton_biz/Boot-NTFS/armory3d_learn/sale_truc_machin/animations/Animals/Alpaca2/Sources/arm/node/NodeTree.hx:225: characters 16-25 : armory.logicnode.OnEventNode has no field property1 (Suggestion: property0)

Haxe compiler error.
Finished in 12.124s
WARNING: 1 warning occurred during compilation
ERROR: Build failed, check console

Dommage! Schade.

**Comment by MoritzBrueckner** [comment]
But [`property1` exists](https://github.com/armory3d/armory/blob/f3f6467fe9f6de954b9af3f6f41689e0227d2877/Sources/armory/logicnode/OnEventNode.hx#L7) in `OnEventNode.hx`, and I downloaded the SDK from itch.io again and checked it and it also exists there. Can you please check whether your local `SDK/armory/Sources/armory/logicnode/OnEventNode.hx` is equal to the file in the link above?

**Comment by StrandedAlien** [comment]
I freshly unpacked the SDK again and now it just works. Very strange, never experienced something similar, but hey, it works now. Thank You, Moritz, for your patience. Dankeschön! Screenshot 
![Screenshot_2022-04-03_22-37-30](https://user-images.githubusercontent.com/89656885/161447812-e8862d47-bd31-49f6-8cbb-8b728e2f191c.jpg)
:

**Comment by rpaladin** [comment]
Helloi, I am the person who implemented the new OnEvent node changes.

I wonder/suspect somehow if your `__pycache__` folder was saving a older copy of the `LN_on_event.py` file which in turn was overriding the newer v2 py file.

![image](https://user-images.githubusercontent.com/69180012/161454719-e7ca4d11-ba37-44fb-b6d9-d53f51dc51eb.png)

**Comment by StrandedAlien** [comment]
Yes Rpaladin, must have been something like that. Makes sense to me. I think this is a rare case scenario and i consider it solved (for me). Btw. you are ex BGE developper, that´s really cool. Hope to see more stuff from you. Ride On! Or is it Dev On?

Thanks for all the help, from ppl above.

**Comment by MoritzBrueckner** [comment]
Hi, glad that it works now, but I have to revisit my statements from above: it looks like there is actually an issue when updating the SDK from within the user preferences. @ rpaladin also experienced it now (see `#armory-dev` if you're on the Discord server) and we probably found the reason: armory.py simply isn't updated. It is re-linked from the SDK after each update and everytime the SDK path changes or Blender is started (in case it was changed locally), but the file isn't downloaded from the latest version.

So this is an actual bug, thanks for the report!

Regarding the `Uncaught exception: Null access`: can you please try to create a small example project where this happens or somehow work out a pattern that causes this? Is there a way to run a debug session to find out where the error is after compiling with make (I'm not a linux user)? You might want to open another issue for this so that we can keep track of it.

*Btw, +1 for using Koui, I hope it works well :)*

**Comment by StrandedAlien** [comment]
Thanks for the extra point and the answer to my secondary reports. I tried and it is the exactly same error with the plain default cube scene. In order to debug i guess we needed a debug release generated as per default armory generates only a release version. However, i checked the export options and "No traces" is unchecked. The tool tip there says something about trace calls. I am just an ambitious user and no Dev. I will google "debug make compiles" and give it a shot. Then we´ll see about opening another issue. See screenshot:


![defcube](https://user-images.githubusercontent.com/89656885/161636325-fea6ec73-49fe-45c1-bfe3-684086308f0e.jpg)
