### ISSUE TITLE
Realtime Viewport Glitch

### ISSUE THREAD

**Issue by JeremiahTDK** [armory3d/armory#248]
*(optional - drag & drop zipped .blend file here)*

Hey,Lubos! I wanted to say that there's something wrong with Armory's realtime viewport. Every time I try to see the dielectric material,it always comes up white and blank. The same goes for metallic material,except it's shiny. Could you please fix the issue?

![screen shot 2017-09-15 at 9 33 16 am](https://user-images.githubusercontent.com/31992914/30489172-2929ab46-99fc-11e7-9265-d306b470fb93.png)

**Comment by AndreaMonzini** [comment]
Hello, i think would be useful if you write the OS and hardware system to try to reproduce the problem.

**Comment by JeremiahTDK** [comment]
The operating system is Mac OS Sierra.

**Comment by luboslenco** [comment]
Should be ok now.
