### ISSUE TITLE
I got Armory to function on macOS

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#2485]
**Description**
Armory3D will fail to build anything on macOS normally. This is largely due to binaries not being executable. I ran the following and now Armory is able to run the necessary binaries to compile a scene:

```
chmod +x "~/Library/Application Support/Blender/2.93/scripts/addons/armsdk/Kha/Kinc/Tools/kraffiti/kraffiti-osx"
chmod +x "~/Library/Application Support/Blender/2.93/scripts/addons/armsdk/lib/armory_tools/cmft/cmft-osx"
chmod +x "~/Library/Application Support/Blender/2.93/scripts/addons/armsdk/Kha/Tools/haxe/haxe-osx"
chmod +x "~/Library/Application Support/Blender/2.93/scripts/addons/armsdk/nodejs/node-osx"
```

In the future, these files need to be included as executable in the zip, or the addon needs to automatically apply the correct permissions on first run.

Please note, this is the addon path for Blender on macOS. Any users who install Armory through the addons preferences will have it arrive here. There are also still further issues preventing builds from working, but at the very least this allows the components of Armory to run.

**System**
Blender: 2.93.9 LTS
Armory: 2022-5
OS: macOS Monterey
Graphics card: Apple Silicon M1 (aarch64)

**Comment by TriVoxel** [comment]
Update: The files seem to have been moved so you may need to find the new ones to use this fix.

Now, it seems macOS bombards you with a warning every time Armory tries to run one of its dependencies. I got a popup for kinc, haxe, etc. You then need to go into your privacy settings and allow it to run, and then clean and re-run the build process and click "allow" on the new popup, and then re-run the build until all the popups are gone. Now I'm getting a new error: "Could not load krom.js, aborting." after building my scene.

**Comment by MoritzBrueckner** [comment]
Fixed in https://github.com/armory3d/armsdk/pull/54.
