### ISSUE TITLE
Armory cannot build default cube on macOS

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#2486]
**Preface**
This is a continuation of issue #2485 where I re-configured the binary permissions to allow Armory to function properly.

**Description**
Trying to build the default cube on macOS results in an error. Here's the console log:

```
Armory v2022.5 ($Id: 66867b70c66af1cd002b5e5b76d9e7931b05e7fb $)
Using CPU for environment render (might be slow). Enable CUDA if possible.
Saved: '/path/to/default_cube/build_default_cube/compiled/Assets/envmaps/env_World.jpg'
 Time: 00:00.07 (Saving: 00:00.00)

Exporting Scene
Scene exported in 0.002s
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1024:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at fs.stat (~/Library/Application Support/Blender/2.93/scripts/addons/armsdk/Kha/Tools/khamake/out/ShaderCompiler.js:350:55)
    at ~/Library/Application Support/Blender/2.93/scripts/addons/armsdk/Kha/Tools/khamake/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
Finished in 24.001s
ERROR: Build failed, check console
```

Please note, I've modified the file paths to hide personal information.

**To Reproduce**
Save and build the default cube scene.

**System**
Blender: 2.93.9 LTS
Armory: 2022-5
OS: macOS Monterey
Graphics card: Apple Silicon M1 (aarch64)

**Comment by e2002e** [comment]
Beware of non ascii characters in armory, they are not supported, so if your project's or armsdk's path does not comply to that it maybe the issue.

**Comment by TriVoxel** [comment]
@e2002e It seems to affect me no matter where the SDK is placed, and no matter the project name. :(

**Comment by MoritzBrueckner** [comment]
Does it work when you move the SDK into a different folder than `Application Support/Blender`? It looks like a permission error that is triggered somewhere down the line in Khamake.

**Comment by TriVoxel** [comment]
@MoritzBrueckner Yes. I've tried from /home/username/Downloads . This path has no spaces or special characters. Also, please keep in mind, "Application Support/Blender" is the path where Blender stores all its settings and addons for macOS. So if this is the case, this bug should still be remedied. I will try again with the latest SDK, but last I knew, both the release versions and source versions of Armory seem to fail entirely on macOS. It could be because I'm on Apple Silicon, but I've tried forcing Blender into x86 mode and it still doesn't work.

**Comment by TriVoxel** [comment]
See https://github.com/armory3d/armory/issues/2485#issuecomment-1186035153

So it seems that the macOS libraries can execute now, but unfortunately macOS blocks each and every one of them. Either way, I unblocked all the Armory binaries, and it seems to pass the default cube test in HTML5. I can build it, and it pops up in my browser. Awesome! Unfortunately, Krom doesn't work. Attempting to build the default cube now results in "Could not load krom.js, aborting." after compiling the scene. :(

**Comment by MoritzBrueckner** [comment]
> Also, please keep in mind, "Application Support/Blender" is the path where Blender stores all its settings and addons for macOS. So if this is the case, this bug should still be remedied.

It is, but from Blender's perspective the SDK is technically not really part of the addon. It is loaded in at runtime. I'm not sure how other addons with binary executables handle this, but for Armory you should not move the SDK in system directories with possibly restricted permissions. If you think that it's a fault of the binaries then maybe Lubos can help here.

> Unfortunately, Krom doesn't work. Attempting to build the default cube now results in "Could not load krom.js, aborting." after compiling the scene

Yep, that's a known issue. I opened a bug report for this: https://github.com/armory3d/armorcore/issues/44. If you have more information or you know how to debug Krom, please let Lubos know in the linked issue.

**Comment by MoritzBrueckner** [comment]
Fixed in https://github.com/armory3d/armsdk/pull/54.
