### ISSUE TITLE
Ocean broken

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#249]
here it is : 
ERROR: build_exterior\compiled\Shaders\water_pass\water_pass_Irr_EnvSky_Rad_EnvClouds_SSRS_VoxelGI_Rad_Irr_SSAO_SMAA_Veloc.frag.glsl:80: 'seaFreq' : undeclared identifier
ERROR: build_exterior\compiled\Shaders\water_pass\water_pass_Irr_EnvSky_Rad_EnvClouds_SSRS_VoxelGI_Rad_Irr_SSAO_SMAA_Veloc.frag.glsl:80: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/armory/commit/51eac232fee211e5bd92d77c9ea3417d99e1ea85, thanks for report! Was a problem with ocean pass not properly registered in Render Path.
