### ISSUE TITLE
Better warning messages for incompatible socket types

### ISSUE THREAD

**Issue by Himik-NAV** [armory3d/armory#2490]
Hi 
Shader to RGB supported_nodes or not supported_nodes?
on wiki - 
https://github.com/armory3d/armory/wiki/supported_nodes
in project Shader to RGB does not work... may by i do wrong?

![image](https://user-images.githubusercontent.com/96059151/168821825-3b872a76-5054-4499-88aa-7e8b5c4ebba2.png)

**Comment by MoritzBrueckner** [comment]
Hi,

the Shader to RGB node is not supported, but it's internal identifier is not called `VALTORGB` (that's the color ramp node). The Shader to RGB node is called `SHADERTORGB`:

![grafik](https://user-images.githubusercontent.com/17685000/168893346-a43d7765-8c47-4c77-9e86-d9e20b057384.png)

However in your case the problem is not the Shader to RGB node, but actually the Color Ramp node, which cannot be directly connected to the material output node because it doesn't have a shader output. I think the warning message in this case is pretty misleading, I will try to implement a better one, thanks for the report :) Until then let's keep this issue open.

**Comment by Himik-NAV** [comment]
is there an alternative way to implement a Shader to RGB node?

**Comment by MoritzBrueckner** [comment]
Not really, although you could always implement something similar yourself in Haxe (by modifying Armory's renderpath) but it's not easy and you would probably need to render the object if not even the scene twice per frame to get correct values.

Maybe there are other ways to achieve what you want to achieve? Feel free to open a thread on the forum or ask on the Discord server, maybe someone has a good idea :) The "Shader to RGB" node now has an entry in the wiki page btw.

**Comment by Himik-NAV** [comment]
![image](https://user-images.githubusercontent.com/96059151/168901429-44e2fcd7-f766-4dd6-bd4c-c8f71b838797.png)

(I'm trying to achieve the Cell Shading effect)
Since it won't work through Shader to RGB, I'll look for other solutions.
Thank you all )))

**Comment by MoritzBrueckner** [comment]
Maybe give https://github.com/armory3d/driver_celshade_example a try.

**Comment by Himik-NAV** [comment]
I've already tried it. It looks good... but! I need my own cartoon material with more functional settings (are you planning to introduce support for the "Shader to RGB" node in the near future?)

**Comment by Himik-NAV** [comment]
> 



> Maybe give https://github.com/armory3d/driver_celshade a try ([example project](https://github.com/armory3d/driver_celshade_example)).

I've already tried it. It looks good... but! I need my own cartoon material with more functional settings (are you planning to introduce support for the "Shader to RGB" node in the near future?)

**Comment by cyclonecopp** [comment]
> > 
> 
> > Maybe give https://github.com/armory3d/driver_celshade a try ([example project](https://github.com/armory3d/driver_celshade_example)).
> 
> I've already tried it. It looks good... but! I need my own cartoon material with more functional settings (are you planning to introduce support for the "Shader to RGB" node in the near future?)

Hi, I made a light based cell shade from looking at the image u provided above with armory, you should join the discord (https://discord.gg/P39XFugMCb) for extended help.
![image](https://user-images.githubusercontent.com/46801032/168971234-759f96c5-a7a3-46f6-88b9-272d382a5b72.png)
not sure that what u exactly want but it may help, or at least the knowledge in which it was built from.

**Comment by Himik-NAV** [comment]
> 
Hello. Tthanks ) I will definitely study it... In the meantime, I'm trying to do it myself
![image](https://user-images.githubusercontent.com/96059151/168990939-c5e87504-4264-41a5-a262-661dfb90ed81.png)

**Comment by Himik-NAV** [comment]
> > > 
> > 
> > 
> > > Maybe give https://github.com/armory3d/driver_celshade a try ([example project](https://github.com/armory3d/driver_celshade_example)).
> > 
> > 
> > I've already tried it. It looks good... but! I need my own cartoon material with more functional settings (are you planning to introduce support for the "Shader to RGB" node in the near future?)
> 
> Hi, I made a light based cell shade from looking at the image u provided above with armory, you should join the discord (https://discord.gg/P39XFugMCb) for extended help. ![image](https://user-images.githubusercontent.com/46801032/168971234-759f96c5-a7a3-46f6-88b9-272d382a5b72.png) not sure that what u exactly want but it may help, or at least the knowledge in which it was built from.

Hello. Tthanks ) I will definitely study it... In the meantime, I'm trying to do it myself
![image](https://user-images.githubusercontent.com/96059151/168991860-05682599-b697-489f-95b5-797677e67adb.png)

**Comment by cyclonecopp** [comment]
looking good 👍
