### ISSUE TITLE
Error playing scene on Wayland display manager

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#2491]
**Description**
Trying to play the scene using Krom whist on the Linux Wayland display manager results in an error. Works in browser.
```text:
Scene exported in 1.213s
Finished in 6.915s
Neither wayland nor X11 found
```
**To Reproduce**
Try running Armory 3D on Linux in a Wayland session. For me, I'm running Gnome.

**Expected behavior**
Game window opens.

**System**
Blender: 2.93.9 LTS
Armory: GIT
OS: Fedora 36 GNOME on Wayland
Graphics card: AMD Radeon RX 5700 XT

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/2487.
