### ISSUE TITLE
Problem with html5 publish and exe as fullscreen

### ISSUE THREAD

**Issue by ManPython** [armory3d/armory#2497]
Thank you for contributing to Armory!

**Description**
I can't adopt or adjust the config settings to have full screen `broweser vieport` in html and .exe

**To Reproduce**
I build normalny by play the html and exe

**Expected behavior**
I expecting full screnn in `broweser vieport` without vertical or horizontal scroll

**System**
Blender: UPBGE 0.3 Alpha /
Armory: 2022.05
OS: w10
Graphics card: gtx  res 1920:1080
Browsers: FF, this same IE

**Test File**

![armory_html_full_screen](https://user-images.githubusercontent.com/25403861/169865048-f71f3839-ad69-4822-94e1-feedce5f2bf2.png)

+ F11 in browser

![armory_html_full_screen_f11](https://user-images.githubusercontent.com/25403861/169865051-bb83881c-d76d-41ff-95cb-f44f3bd39e39.png)

+Exe

![armory_html_full_screen_exe](https://user-images.githubusercontent.com/25403861/169865553-47f95000-4a18-4912-af66-f693ef1b407e.png)

**Comment by ManPython** [comment]
Can be closed as resolved.
I did not know the effect of window and fullscreen build and cache.
https://github.com/armory3d/armory/issues/908

**Comment by MoritzBrueckner** [comment]
> I did not know the effect of window and fullscreen build and cache.

I'm not sure if I understand that correctly. I tested it and it seems that you don't need to clear the build cache in order for different window settings to take effect. If I change from "Window" to "Fullscreen" for example I can directly re-play the game with the new settings without having to click on "Clean" first.

If I misunderstood you and there still is something weird with the cache we can reopen the issue again.

> BTW.. when trying regist:
https://forums.armory3d.org/auth/failure?message=redirect_uri_mismatch&origin=https%3A%2F%2Fforums.armory3d.org%2Ft%2Fprivacy-question%2F4864&strategy=github
Sorry, there was an error authorizing your account. Please try again. 

CC @luboslenco, maybe you can notify Xananax about this?
