### ISSUE TITLE
No lamp = black screen

### ISSUE THREAD

**Issue by nafergo** [armory3d/armory#25]
You always need a lamp (even if it has strength of 0) to see something. 

- If you play (Electron) without a lamp in an active layer, only using a sky texture (world) to light scene, you get a black screen 
- if you play (Electron) with a 0 strength lamp in an active layer, only using a sky texture (world) to light scene, everything goes ok

INFO
Armory3D:
Armory_p01_linux64

Blender:
version: 2.78 (sub 0), branch: master (modified), commit date: 2016-10-31 20:56, hash: 519259a, type: Release
build date: 2016-11-02, 19:55:35
platform: Linux

Python:
version: 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609]

OpenGL:
renderer:	'GeForce GTX 660/PCIe/SSE2'
vendor:		'NVIDIA Corporation'
version:	'4.5.0 NVIDIA 367.57'

**Comment by guzzard** [comment]
I get the same results

**Comment by luboslenco** [comment]
Fixed in Build 2.
