### ISSUE TITLE
Ocean doesn't reflect objects

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2508]
The Ocean shader doesn't reflect hdri environment map,
And it simply doesn't reflect anything else than the sky.
I know this is just demanding but I do not understand much about shaders and since you guys do I hoped that you would take a bit of time to add this feature.

**Comment by e2002e** [comment]
When adding a plane at the same level as the water, the reflection is there (metallic 1 roughness 0), and also the refraction even though the alpha is set to 1.

**Comment by e2002e** [comment]
I'm reopening since the ocean doesn't reflect environment textures.
Maybe it is just not implemented ?
Setting sky to preetham works.

**Comment by e2002e** [comment]
I am having an issue with uniforms that are not passed to the shaders, specifically I need P projectionMatrix, added it to the json file but it isn't found.

**Comment by e2002e** [comment]
I am stuck with hitcoords that are not taking normals into account and also are limited to a part of the screen (the right).

**Comment by shayneoneill** [comment]
e2002e , the general protocol is one issue per ticket. You have three issues here and the second and third one will probably be ignored because they arent the first issue.

**Comment by e2002e** [comment]
Honestly I'm trying to better an engine and so did open issues as needed, being taken into consideration is a plus for the dev in the end.
The hitCoords show which part of the screen will be projected back to the ocean.

**Comment by e2002e** [comment]
This is a feature request, the Ocean must reflect objects and to do this is copied code from the ssr pass to the ocean shader.
Maybe another way would be of implementing the current ocean shader to a material node that can handle ssr by default.
The issue that i am facing is with retrieving the projection matrix, passing it as an uniform is not working yet i'm sure it did at some point after modifying deferredrendering.hx, i even got real reflections yet they were distorted.

**Comment by e2002e** [comment]
That's fixed on my fork, for now I'm waiting on maintainers.

**Comment by MoritzBrueckner** [comment]
Link to https://github.com/armory3d/armory/pull/2531.

In the future it would be better to split different unrelated changes into different pull requests, this way Lubos could decide what to merge and the different changes show up in the release notes :)
