### ISSUE TITLE
remove object node

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#251]
The "remove object" node removes the object selected to be removed, thats working, but it also removes the object on which the trait with that node is applyed on. 
[objectnode.zip](https://github.com/armory3d/armory/files/1315129/objectnode.zip)
Dont think you need that file to understand but I'll upload it anyways

**Comment by luboslenco** [comment]
Nice catch! Should be now fixed in https://github.com/armory3d/armory/commit/86c3df653e10b82e6805b20f90a26e0cde9af323.
