### ISSUE TITLE
Tesselation shader won't compile.

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2518]
Hello, i have 3d scans textures with normal and height (walls and roofings), when using tesselation with the displacement node, the roofings is good, but not the walls.
ERROR: /home/yvain/Documents/Game/Models/build_houses/compiled/Shaders/Walls_mesh.tese.glsl:29: 'wtangent' : undeclared identifier 
ERROR: /home/yvain/Documents/Game/Models/build_houses/compiled/Shaders/Walls_mesh.tese.glsl:29: 'cross' : no matching overloaded function found 
ERROR: /home/yvain/Documents/Game/Models/build_houses/compiled/Shaders/Walls_mesh.tese.glsl:29: '' : compilation terminated 

It was working until a point which I don't remember, my setting are pretty much to all on except for the resolution.
It doesn't come from the UV, i tried generated mapping. I tried deactivation the voxel AO too.

**Comment by e2002e** [comment]
On the functional shader:
in vec3 tc_wposition[];
in vec3 tc_bposition[];

on the disfunctional one:

in vec3 tc_wposition[];
in vec3 tc_wtangent[];

No bposition, and error is about wtangent, what do you think affects that ? shaders settings are the same.

**Comment by e2002e** [comment]
That now works with 'precompute tangents' off, wonder why only one of my material was being processed here and why it fails.

**Comment by MoritzBrueckner** [comment]
> That now works with 'precompute tangents' off

So it still doesn't work when that option is on? It's great that you managed to solve it for your project, but it still looks like a bug to me.

**Comment by e2002e** [comment]
I couldn't make it work with these option enable, I got rid of the file and don't know how to reproduce, same setup is working as expected with the same textures.
