### ISSUE TITLE
Terrain generator doesn't care about number of sectors

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2522]
I am trying to generate a terrain with the bundled feature but whatever number of sectors I choose, the result are two squares. One corresponding to the heightmap, the other just a plane.
![Capture d’écran du 2022-07-21 19-06-44](https://user-images.githubusercontent.com/29781855/180273763-dd414129-a239-4f63-b543-4dba677e59bf.png)

**Comment by QuantumCoderQC** [comment]
Hi, the terrain generation requires one image per sector, properly named. The documentation on this was missing so I added some [here](https://github.com/armory3d/armory/wiki/terrain#terrain-generation)

I believe, in your test, you used just one image but multiple sectors?

**Comment by e2002e** [comment]
Yes that is right, thanks for the hint
