### ISSUE TITLE
Not able to find armory.py

### ISSUE THREAD

**Issue by AJPietan** [armory3d/armory#2550]
So Im downloading armory for the first time and the "armory.py" that the tutorial said to click was not in the download.  So I looked at the github code and it wasn't there either. Am I doing something wrong or did I miss understand the instructions?

Blender: 3.2.2
Armory: Latest as of 08/11/22

**Comment by rpaladin** [comment]
It should be in the armsdk that you download from [itch.io](https://armory.itch.io/armory3d). Here's what it should look like.

https://github.com/armory3d/armsdk/blob/main/armory.py

**Comment by MoritzBrueckner** [comment]
Closing this for now, we can reopen the issue if the problem persists even after a correct installation.
