### ISSUE TITLE
bones animation keep crashing since July 07 repo

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2554]
Hi there I keep getting my html5 projects crashing when they contains bones animations since the july 07 repo and forward. 
Seems like the changes in iron for : relative-bone-constraint 
might be the culprit.

I am getting the following javascript error now and all animations stop: 
```
VM16:1 Uncaught TypeError: Cannot read properties of null (reading 'elements')
    at Me.getElement (<anonymous>:1:79474)
    at <anonymous>:1:31809
    at ja.update (<anonymous>:1:49588)
    at fh.task (<anonymous>:1:381355)
    at S.executeTimeTasks (<anonymous>:1:380255)
    at S.executeFrame (<anonymous>:1:379385)
    at k (<anonymous>:1:419053)
```

**Comment by MoritzBrueckner** [comment]
Do you have an example file? I tested some of the animation examples with the latest SDK and I can't reproduce it. Also, you may get a more verbose error message if you temporarily disable `Armory Exporter > Minify JS`.

**Comment by onelsonic** [comment]
so it seems like it's the ZUI 2D canvas that is throwing errors in Javascript that stop all animations.
---------

```
    M["armory.trait.internal.CanvasScript"] = Le;
    Le.__name__ = "armory.trait.internal.CanvasScript";
    Le.__super__ = Oa;
    Le.prototype = Na(Oa.prototype, {
        get_ready: function() {
            return null != this.canvas
        },
        notifyOnReady: function(a) {
            this.onReady = a
        },
        getElement: function(a) {
            for (var c = 0, b = this.canvas.elements; c < b.length; ) { ###################### >>> Uncaught type error cannot read property of null (reading elements)
                var d = b[c];
                ++c;
                if (d.name == a)
                    return d
            }
            return null
        },
```

another JS error : 
---------------------------
VM15:formatted:31872 Uncaught ff {message: 'End before you begin', __previousException: undefined, __nativeException: ff, value: 'End before you begin'}

```
        disableScissor: function() {
            this.scissorEnabled = !1;
            this.flush();
            this.g.disableScissor()
        },
        begin: function(a, c) {
            null == a && (a = !0);
            if (null == ab.current)
                ab.current = this;
            else
                throw L.thrown("End before you begin");
            this.g.begin();
            a && this.clear(c);
            this.setProjection() 
```
Whitout the

**Comment by onelsonic** [comment]
Something must be wrong with the commit below.
https://github.com/armory3d/iron/commit/fe7733899313bea3f20d0ce7ba3b6517a0190512?diff=split

Reverting this commit fix the error, 
and the error comes from iron and when you have some Canvas element (that uses Zui 2D Canvas.)

When you have a simple 2D UI canvas and an Haxe Trait that manipulate this 2D Canvas.
When exporting to html5, the JavaScript will crash and throw the error stopping the code and thus all bones animations.


Example of Haxe trait:
```
package arm;
import iron.Scene;
import armory.trait.internal.CanvasScript;
import armory.system.Event;
import kha.System;

class CanvasUi extends iron.Trait {

	var canvas:CanvasScript;
	var itemtnot = true;
	var uioff = true;
	
	public function new() {
		super();
		
		notifyOnInit(function() {
			canvas = Scene.active.getTrait(CanvasScript);
			if (itemtnot) {
				itemtnot = false;
				canvas.getElement("logo").visible=true; //false
			}
		});
	}

}
```

**Comment by MoritzBrueckner** [comment]
The linked commit is not the actual problem, but it probably makes the problem visible since the order in which traits are initialized has changed.

When the `CanvasScript` trait is instanced, the canvas is not guaranteed to be directly available. Instead, there is some potentially asynchronous code that could defer it. So instead of directly accessing the canvas, you need to run your code when the canvas is ready. Here is the working code:

```haxe
package arm;
import iron.Scene;
import armory.trait.internal.CanvasScript;
import armory.system.Event;
import kha.System;

class CanvasUi extends iron.Trait {

	var canvas:CanvasScript;
	var itemtnot = true;
	var uioff = true;

	public function new() {
		super();

		notifyOnInit(function() {
			canvas = Scene.active.getTrait(CanvasScript);
			canvas.notifyOnReady(() -> {
				if (itemtnot) {
					itemtnot = false;
					canvas.getElement("logo").visible=true; //false
				}
			});
		});
	}
}
```

**Comment by onelsonic** [comment]
yes moving the canvas manipulation code inside on notifyOnReady fixed the animation problem.

I will just update all canvas code.
Thank you.

(And maybe some old canvas examples can break the same way, 
this is good to know.) 👍 

```
canvas.notifyOnReady(() -> {
	canvas manipulation code
});
```

**Comment by MoritzBrueckner** [comment]
Added a small note in the wiki: https://github.com/armory3d/armory/wiki/traits#canvas-trait-events
