### ISSUE TITLE
Web workers do not work on Krom

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2558]
Web workers do not work on Krom, whereas, works as expected on HTML5.

**Description**
As a test, I used a simple JS file and created a worker thread with it. I then do a `postMessage` on the thread and listen for any events from the worker.

The JS script looks like so:
```JS
onmessage = function(message){
    console.log("hi from JS");
    let x = 10;
    self.postMessage(x);
}
```
And the Haxe script looks like so:
```Haxe
package arm;

class MyTrait extends iron.Trait {
	public function new() {
		super();

		notifyOnInit(function() {
			var worker = new js.html.Worker('testscript.js');
			trace(worker);
			worker.addEventListener("message",function (data:Dynamic){
				trace("Event !");
				trace(data.data);
			});
			worker.postMessage("Hello");
			
		});
	}
}

```

When run, I get the following output on HTML5:
```
Log.hx:66        arm/MyTrait.hx:9: [object Worker]
testscript.js:2  hi from JS
Log.hx:66        arm/MyTrait.hx:11: Event !
Log.hx:66        arm/MyTrait.hx:12: 10
```

And below is the output on Krom:
```
arm/MyTrait.hx:9: {

}
```

Some more info: 
1. Basic web workers on Krom were implemented here: https://github.com/armory3d/armorcore/pull/19
2. Krom is already built with `WITH_WORKER` enabled.

**To Reproduce**
Run the provided test file on Krom and on HTML5 (Browser)

**Expected behavior**
Web workers should work on krom.

**System**
Blender: 2.93
Armory: 2022.08
OS: Windows

**Test File**
[KromWorkerTest.zip](https://github.com/armory3d/armory/files/9436472/KromWorkerTest.zip)

**Comment by tong** [comment]
I think you are supposed to use `kha.Worker`:

```haxe
var worker = kha.Worker.create(MyWorker);
trace(worker);
worker.notify(data -> {
  trace(data);
});
worker.post(23);
```
But there seem to be other issues making krom unable to load the worker here: https://github.com/armory3d/Kha/blob/dfce2f932bd036e40d2574e170c06236d81cfac9/Sources/kha/Worker.hx#L71

**Comment by QuantumCoderQC** [comment]
@ tong, thank you for the reply. I am not sure if we want `kha.Worker.create()`. 

@SunDaw sorry to ping you, but could you please confirm the usage of krom workers in armory, that was implemented by you in armorcore. I am not sure if my usage(as mentioned in my first post) is wrong or if it is a bug.

Thanks!

**Comment by QuantumCoderQC** [comment]
This is not a bug rather an incorrect usage of the implemented web workers.
To fix this, in the above example JS script, remove `self` from `self.postMessage`. 

`console.log` is not implemented.

Thanks to @ SunDaw for the clarifications on this.
