### ISSUE TITLE
Remove only parent Option for remove object

### ISSUE THREAD

**Issue by vuaieo** [armory3d/armory#2570]
it would be very usefull to have option "keep children" for Remove Object node so only the parent object is removed and children are not removed.
this is because if you work with many objects with rigid bodys and constraints in blender you want to move them , simulate, reset rotation. so having parented them all to empty is very useful and in blender if you parent rigid bodys and constraints to empty and run physics simulation then it still works. but in armory not. and if doing for all the objects object constraint > child of then the screen is black so i think its bug or so..
then could have simple nodes like : On init > remove object (keep children or remove only parent ) and then only empty is removed on game star. so can move that object very nicely around in blender and in game would work same lile in blender...

**Comment by MoritzBrueckner** [comment]
Implemented in https://github.com/armory3d/armory/pull/2591.
