### ISSUE TITLE
Camera settings different in Armory compared to settings in Blender

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#258]
Expected camera in Armory to have the same FOV etc as the render in Blender.

**Cycles render example**
![cycles](https://user-images.githubusercontent.com/9007314/31013905-9077a510-a518-11e7-8573-113e60494c3d.png)

**Armory play**
![armory](https://user-images.githubusercontent.com/9007314/31013908-929903fc-a518-11e7-8eb3-03cbdc3cccf3.jpg)

**Comment by luboslenco** [comment]
Patched in https://github.com/armory3d/armory/commit/361962430965d31ffcff64415ddb60a10d81baec, seems to work well so far.

![cam](https://user-images.githubusercontent.com/3685704/31933502-92ed52dc-b8a9-11e7-866c-fca35ab83aad.jpg)

**Comment by guzzard** [comment]
yes, works great!
