### ISSUE TITLE
Mesh appears transparent

### ISSUE THREAD

**Issue by songproducer** [armory3d/armory#26]
I managed to work around this by adding a solidify modifier. But it's still tricky to get a solid appearance at the edges of separate objects.
http://i.imgur.com/ZisvrFN.png

**Comment by luboslenco** [comment]
Looks like there are culling issues. In Blender, enter Edit mode, select all faces - press space - *Make Normals Consistent*. Alternatively, you might need to select the problematic faces individually - press space - *Flip Normals*.

There is a way to disable culling but that will also impact performance. In World data - Armory Props - Flags, check *Force No Culling*.

Let me know if this worked, if so I will add it to the docs.

**Comment by songproducer** [comment]
Thanks, making the normals consistent worked!
