### ISSUE TITLE
Rendering issues, opacity (Armory PBR)

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#261]
**Cycles**
![cycles](https://user-images.githubusercontent.com/9007314/31037030-2be85f7a-a56f-11e7-85e5-dc97405eb438.png)

**Armory**
![armory](https://user-images.githubusercontent.com/9007314/31037032-2fb01512-a56f-11e7-923e-88f520d4f16e.jpg)

**Issues**
- Cloud color
- Shadows black
- Clouds visible on dark side of sphere where there is no light

**Project file**
[render_test_2.zip](https://github.com/armory3d/armory/files/1394034/render_test_2.zip)

**Comment by guzzard** [comment]
Opacity seem to have broken completely in build 14 rc0?

**Armory**
![build14rc0](https://user-images.githubusercontent.com/9007314/31710312-e4a2b7e8-b3f4-11e7-90e1-cc1766308048.jpg)

**Comment by luboslenco** [comment]
<img width="293" alt="inner" src="https://user-images.githubusercontent.com/3685704/31712068-51925476-b3fa-11e7-86ea-edf3ece07628.png">

It seems to be due to the inner sphere object being hidden (or not?). It will still look like your previous picture though, need to fix this.

**Comment by guzzard** [comment]
@luboslenco ah yeah sorry.. inner sphere was hidden. Still looks like the first picture when unhiding the sphere.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/624.
