### ISSUE TITLE
Rendering issue, layer weight (Armory PBR)

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#262]
**Cycles**
![cycles](https://user-images.githubusercontent.com/9007314/31037645-51677e0e-a572-11e7-82af-a8f12ff77b4c.jpg)

**Armory**
![armory](https://user-images.githubusercontent.com/9007314/31037647-53254ff0-a572-11e7-95d8-66ffb56bb3a2.jpg)

**Issues**
- Layer weight node not working as expected

**Project file**
[render_test_3.zip](https://github.com/armory3d/armory/files/1345793/render_test_3.zip)

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/624.
