### ISSUE TITLE
Rendering issue, shadows

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#263]
**Cycles**
![cycles](https://user-images.githubusercontent.com/9007314/31049938-d4665bf0-a63e-11e7-9482-a5e19340827e.jpg)

**Armory 2k shadow map**
![armory_2k_shadow_map](https://user-images.githubusercontent.com/9007314/31049939-d79c73b8-a63e-11e7-9046-4f68e074c19a.jpg)

**Armory 8k shadow map**
![armory_8k_shadow_map](https://user-images.githubusercontent.com/9007314/31049940-da9b08cc-a63e-11e7-9892-e84c80ffc396.jpg)

**Issue**
- Regardless of shader shadows are not smooth (tested Armory PBR, Principled BSDF, Diffuse BSDF).

**Project file**
[render_test_5.blend.zip](https://github.com/armory3d/armory/files/1346789/render_test_5.blend.zip)

**Comment by guzzard** [comment]
Noticed that it looks much better when setting shadow map to "none":question: 
![armory_no_shadow_map](https://user-images.githubusercontent.com/9007314/31115199-aa0ac15e-a821-11e7-87ce-72b41ff14a9a.jpg)

**Comment by luboslenco** [comment]
Have to be tweaked using the `Lamp Data - Armory Props - Bias` value. :/ Atleast till we get rid of the shadowmaps.
