### ISSUE TITLE
[Feature Request] End frame for play action from node

### ISSUE THREAD

**Issue by rpaladin** [armory3d/armory#2635]
Currently the `Play Action From` logic node doesn't have a `End Frame` input, only `Start Frame`. Having a extra input to state the end frame would be handy, otherwise a custom layout such as the one shown below will need to be setup to manually check whether a certain frame has been reached.

![image](https://user-images.githubusercontent.com/69180012/197361658-65338bed-ec76-477a-afc7-6b500d3aa464.png)

**Comment by t3du** [comment]
i agree this would be very useful, when i looked the node in order to do it i figured out that the function in which the node is based do not had that parameter, perhaps that is why is not included
