### ISSUE TITLE
Using Zui breaks code completion in that specific file in Kode Studio

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#267]
Using Zui breaks code completion in that specific file in Kode Studio. Code completion still works in other files though.

To reproduce add:
import zui.*;

and class variable

var ui:Zui;

After this code completion stops working.

*(this is perhaps more related to Kode Studio than Armory?)*

**Comment by luboslenco** [comment]
Yup, or maybe [vshaxe](https://github.com/vshaxe/vshaxe). Updating to new Kode Studio for next build, maybe we will get lucky and the issue fixes itself.

**Comment by guzzard** [comment]
Still the same, no code completion in the files using Zui :-(

**Comment by luboslenco** [comment]
As a workaround it seems to work after running the project once in Kode Studio(F5), this will make it pick up libraries from `khafile.js`.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/692.
