### ISSUE TITLE
Gamepad input not working (Krom/C++)

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#268]
On Arch Linux, getting input from gamepad is not working with Krom and C++ builds, however Browser is working. Tested an old USB controller (kernel driver) and a wireless XBOX 360 controller ([xboxdrv driver](http://pingus.seul.org/~grumbel/xboxdrv/)). 

Tested in a minimal Kha project, and same thing there, input works fine in HTML5 builds, but no input is registrerad when running Krom.

**Comment by guzzard** [comment]
Created an issue in the Krom repo.. https://github.com/Kode/Krom/issues/57

**Comment by luboslenco** [comment]
You fixed it!:)
