### ISSUE TITLE
Zui and canvas not working on 2022.12 SDK

### ISSUE THREAD

**Issue by QuantumCoderQC** [armory3d/armory#2685]
Zui canvas causes errors in browser targets.

@luboslenco 

This bug is already fixed with https://github.com/armory3d/iron/commit/aab5a7104afd5b0454064f33634bafe40083928b and https://github.com/armory3d/zui/commit/148328dd32ab698a96ffead0f13ea1f6ea154e27. However, the fix is not included in the 2022.12 version of the SDK. Could you please make a new sub-release both on the GitHub and on Itch.io with the fix included.

Thanks : )

**Comment by luboslenco** [comment]
The `ArmorySDK-2022-12a` build should already include those. Or is there still an issue?

**Comment by QuantumCoderQC** [comment]
Thanks!
I hadn't noticed the 2022-12a at the time of writing the issue. The fix is included.
