### ISSUE TITLE
Armory just play with an empty scene.

### ISSUE THREAD

**Issue by wcarige** [armory3d/armory#269]
*(optional - drag & drop zipped .blend file here)*
![untitled-1](https://user-images.githubusercontent.com/7854507/31305262-8e43a3a2-aaea-11e7-85fa-4c2f7005429c.jpg)

**Comment by luboslenco** [comment]
There were some changes in latest b2.79 release breaking mesh export in armory :(. Bundled Blender should still work fine, and the issue will be fixed in upcoming build 14 (already fixed in git). Sorry for trouble!

**Comment by luboslenco** [comment]
Should be now resolved in build 14.
