### ISSUE TITLE
Emission color doesn't output/display correctly if overlay setting enabled

### ISSUE THREAD

**Issue by rpaladin** [armory3d/armory#2694]
Possibly related to: https://github.com/armory3d/armory/pull/2638

Unrelated, is it normal that materials marked as overlay aren't affected by world shading or the renderpath?

![image](https://user-images.githubusercontent.com/69180012/227363501-c0cb0d81-600d-483f-84a0-2b5dc56f2d76.png)

**Comment by e2002e** [comment]
The overlay meshes are drawn at the end of the render path's fucntions, they are not being shaded.
The emission material doesn't hold diffuse color so is rendered black, while the other shaders you tested do render with their base color, but don't emit nor get shaded.
I am going to work on that today.
