### ISSUE TITLE
Armory Traits - Kode Studio launches with previous session file/folder instead of script you want to edit

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#27]
Following tutorial "Scene 1", clicking on "Edit Script" I assume it should launch Kode Editor with the correct folder and file selected, so you can just start editing, but instead it launches the previous session (empty if never started before). You have to manually open the correct folder and file to start editing.

INFO
Arch Linux 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux

Armory_p01_linux64 - PLUGIN ONLY, not the custom blender build

Blender 2.78 (sub 0)
	build date: 2016-10-27
	build time: 06:09:01
	build commit date: 2016-10-24
	build commit time: 12:20
	build hash: e8299c8
	build platform: Linux
	build type: Release

Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602]

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 780/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 375.10
OpenGL core profile shading language version string: 4.50 NVIDIA

**Comment by luboslenco** [comment]
Fixed in Build 2.
