### ISSUE TITLE
Armory blender 28 experimental missing lib under Linux

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#270]
Ok!

It's been a while :-) not much time for testing recently.

Today I updated to last version of Armory in Itch and Armory_b13_linux64_blender28_experimental is not able to start due to a missing lib: libOpenImageIO.so.1.7.

The previous version (Armory_build13_linux64) works ok. It's based on libOpenImageIO.so.1.6.

It seems that blender28_experimental still bundles libOpenImageIO.so.1.6 instead of libOpenImageIO.so.1.7.

**Comment by luboslenco** [comment]
Thanks for reporting! Will try to fix the libs for upcoming build. Both 2.79 and 2.8 versions are managed for now, till 2.8 gets mature. :)

**Comment by luboslenco** [comment]
@arturjpv missing libs issue should be gone now!

**Comment by arturjpv** [comment]
It's working!

**Comment by arturjpv** [comment]
Closing issue
