### ISSUE TITLE
Gamepad release event triggered on start - Linux

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#271]
First time any gamepad input is registered all buttons/axis are activated. I think as a part of Kha setting up the controller and getting all axis and buttons etc.

It would be good to somehow handle this, so that first time input is handled by Armory and does not forwarded to the game code. If first input can only be triggered physically by using the gampad, then perhaps it's possible to filter out which button or axis triggered the first input and only forward that to the game code?

**Comment by luboslenco** [comment]
Hm, is this still an issue? Both html5 and native?

**Comment by guzzard** [comment]
Hi @luboslenco, 'released' is triggered for all buttons upon starting play. So it would be nice if there was a way to suppress that first initial 'released' from triggering, either in Amory, or in Kha. I guess it's coming from Kha..

Issue is that if you have any logic, for example skipping an intro video connected to a button 0/A/Cross release, that intro video would be skipped every time, and never play etc..

**Comment by luboslenco** [comment]
Did some testing and it appears ok now.
