### ISSUE TITLE
Color Ramp and Vector Curves nodes

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#274]
Finish implementation of these nodes.

**Comment by Gerkinfeltser** [comment]
My thoughts exactly! Right now it appears Color ramps only pay attention to the first two nodules.

**Comment by Gerkinfeltser** [comment]
Here's an example of color ramps. Other then constant interpolation type, the other types only register the initial two color nodules. (This is using 2.8 0.4b though it works the same on 2.7 afaik.)

![blender_2018-06-22_16-33-52](https://user-images.githubusercontent.com/1477787/41798113-70cc136a-763a-11e8-8329-5beaeb572c97.png)

[colorrampTest.zip](https://github.com/armory3d/armory/files/2129081/colorrampTest.zip)

**Comment by luboslenco** [comment]
Linear color ramps should be ok now. 🔨

**Comment by FuriouZz** [comment]
Does this ColorRamp node can work for the World Output ?

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/905.
