### ISSUE TITLE
Visual artifacts in specular lighting when dotNL < 0

### ISSUE THREAD

**Issue by MoritzBrueckner** [armory3d/armory#2792]
When looking at a face whose normals point away from a sun lamp (i.e, `dotNL` < 0), there are some visible artifacts depending on the material's roughness value (example file attached below):

![specular_wrong](https://user-images.githubusercontent.com/17685000/217962130-be31c3fd-36d9-46cb-9638-220f2ee6c8ac.png)

This issue was introduced in https://github.com/armory3d/armory/pull/2653, I could pinpoint it to `g2_approx()` in *brdf.glsl*. In the above picture on the right you can see an example material with a texture, on the left there is a color ramp driving the roughness from -0.5 to 0.5 (the blue bar on top marks the range from 0 to 1). As you can see, at a roughness of ~0.8 there are some visible artifacts and roughness values > 0.8 and < 1 seem to output 0.

When reversing the changes from https://github.com/armory3d/armory/pull/2653, the example looks correct again (apart from roughness values > 1, which probably shouldn't happen in practice anyways):
![specular_correct](https://user-images.githubusercontent.com/17685000/217962462-49f850c1-1359-4183-a153-e184d2df7ca1.png)

When clamping `nl` in `specularBRDF()` to [0, 1] (actually, using `max(0, nl)` should be sufficient), the issue is gone. However, I'm not sure whether this is the correct approach to solve this, and whether `nh`, `nv` and `vh` should be clamped as well (and if so, whether this should be done only in `specularBRDF()` or everywhere/globally in the lighting shader code). [This blog post](http://filmicworlds.com/blog/optimizing-ggx-shaders-with-dotlh/) as well as [this one](https://www.jordanstevenstechart.com/physically-based-rendering) clamp all the dot values, [this post](https://schuttejoe.github.io/post/ggximportancesamplingpart1/) uses a not further explained `BsdfNDot` function to calculate the angle dot products which might also contain some clamping.

@LVutner Sorry to ping you, do you know an answer to this by chance? Also, out of curiousity, what did you mean with `NdotL cancels out later` [here](https://github.com/armory3d/armory/blob/c70f376452912ee5efad5a2976507d603e56766a/Shaders/std/brdf.glsl#L38)?

**Test File**
[Issue_BRDF.zip](https://github.com/armory3d/armory/files/10702464/Issue_BRDF.zip)

**Comment by LVutner** [comment]
Hello

I thought the dot products are already clamped before **specularBRDF()** call. My bad. 
Your approach is correct, dot products passed to **specularBRDF()** should be clamped (0.0-1.0).


Why we are using **4.0 * NdotV** as denominator, instead of **4.0 * NdotL * NdotV**?
That's because we don't multiply **sdirect** by NdotL, thus we can ignore NdotL and use shorter denom.
