### ISSUE TITLE
Please remove In and Out nodes from Logic Nodes Get Canvas

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#2798]
![image](https://user-images.githubusercontent.com/39986875/219383767-d927c9ff-7fd0-4126-8519-de2a4268930e.png)

Please remove In and Out nodes from Logic Nodes Get Canvas

![image](https://user-images.githubusercontent.com/39986875/219383046-b23b880d-6184-4b22-ac0a-0bf6c02d0017.png)

**System**
Blender: LTS 3.3.3
Armory: 2023.2
OS: Windows 11

**Comment by Dzynek** [comment]
Fixed
[LN_get_canvas_location.zip](https://github.com/armory3d/armory/files/10758680/LN_get_canvas_location.zip)

**Comment by rpaladin** [comment]
@Dzynek please create a PR instead of sharing the fixes here. 🙂

**Comment by Dzynek** [comment]
@rpaladin Sorry, I'm not good at programming and I don't know what "PR" means?

Fixed
[LN_get_canvas_scale.zip](https://github.com/armory3d/armory/files/10760370/LN_get_canvas_scale.zip)

**Comment by rpaladin** [comment]
PR = Pull request.

**Comment by Dzynek** [comment]
@rpaladin I deleted the files (previously uploaded here) with my fixes (for Canvas Logic Nodes) because they didn't work properly.
