### ISSUE TITLE
Subsurf/shading random behaviour

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#28]
![suzanne](https://cloud.githubusercontent.com/assets/9007314/20078924/c40c247c-a542-11e6-9984-7d66cfca5bcd.jpg)

Getting some strange behaviour with subsurf and shading. Project attached here: [suzanne.zip](https://github.com/armory3d/armory/files/576811/suzanne.zip)

INFO
Arch Linux 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux

Armory_p01_linux64 - PLUGIN ONLY, not the custom blender build

Blender 2.78 (sub 0)
build date: 2016-10-27
build time: 06:09:01
build commit date: 2016-10-24
build commit time: 12:20
build hash: e8299c8
build platform: Linux
build type: Release

Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602]

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 780/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 375.10
OpenGL core profile shading language version string: 4.50 NVIDIA

**Comment by luboslenco** [comment]
Modifiers should work more reliably in Build 2. Please reopen on issues.
