### ISSUE TITLE
RigidBody warning message

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#280]
Warning message seen in Kode Studio output:

```
../Armory/armsdk/armory/Sources/armory/trait/physics/RigidBody.hx:15: characters 21-56 : Module armory.trait.physics.oimo.RigidBody does not define type RigidBody
```

**Comment by luboslenco** [comment]
Is this with Armory Project  - Modules - Physics set to Oimo? Does `Armory/armsdk/lib/oimo` folder exists?

**Comment by guzzard** [comment]
@luboslenco the folder exist, however Physics is set to 'Bullet'.

**Comment by guzzard** [comment]
seem to have gone away by itself.. weird.. closing!
