### ISSUE TITLE
NavMesh Obstacles

### ISSUE THREAD

**Issue by BlueCatGamess** [armory3d/armory#2805]
Perhaps a good feature is a bundled trait "NavMesh Obstacle", when we assign this to an object and when navmesh is generated it automatically avoids objects with NavMesh Obstatle trait. It is useful when the player needs to avoid a static object (such as a stone) and that object cannot be joined to the ground mesh, because if you do this, the object's materials (stone) will be modified.

**Comment by rpaladin** [comment]
This issue is a duplicate to #243
