### ISSUE TITLE
Example scene in iOS very slow

### ISSUE THREAD

**Issue by stellanhaglund** [armory3d/armory#281]
Hi i ran the mobile scene example from the previous version of Xcode, then everything was fine.

Then i updated to Xcode 9 i think the version is, now the rotation of the Suzanne is not rotating smooth at all anymore, just jumping steps now and then.

**Comment by luboslenco** [comment]
Heyo,

Thanks for letting me know, will check it out! Are you testing on device or simulator?

**Comment by stellanhaglund** [comment]
I used the simulator.

**Comment by luboslenco** [comment]
Did some investigation, looks like it's getting resolved in XCode 9.1.

Pasting from [this topic](https://forums.developer.apple.com/thread/83570?start=59):

>This bug is fixed in Xcode 9.1 beta 2.
> There is a bug in OpenGLES.framework in the iOS 11/tvOS 11/watchOS 4 Simulators that causes them to skip loading the LLVM JIT and fall back to interpreting shaders. This has a severe performance impact on the Simulator since it is entirely software-rendered OpenGL (this includes CoreAnimation, SceneKit, etc).

**Comment by stellanhaglund** [comment]
That's great!
Also there was some problem with sys_command in Sys.winrt.cpp, and specifically this line `int result =  system(val_string(cmd));` but maybe that's something for kha?

**Comment by luboslenco** [comment]
Oh Xcode 9.1 now out, and using the latest [Kode/Kha](https://github.com/Kode/Kha) seems to also compile with no issues, so perhaps this is fine now.
