### ISSUE TITLE
ARCore and ARKit Support

### ISSUE THREAD

**Issue by HeadClot** [armory3d/armory#282]
Hey Lubos,

Would it be possible to get [ARCore](https://developers.google.com/ar/discover/#supported_devices) and [ARKit](https://developer.apple.com/arkit/) support for Armory3D?

**Comment by luboslenco** [comment]
There has been a hololens integration merged into Kore recently (https://github.com/Kode/Kore/pull/214), maybe ARCore and ARKit fall somewhere in that area. Will consult @robdangerous to learn about his plans. :)

**Comment by razcore-art** [comment]
This is fairly hidden, but http://www.artoolkitx.org/ is the (open source) continuation of artoolkit and seems like they're on the way of supporting arcore & arkit so might be worth checking out.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/1034.
