### ISSUE TITLE
Voxel GI emission requires lamp

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#285]
-Eveything is black (whole screen) if there is no lamp in the scene
-Object with emision just emits light in the direction where the obligatory lamp is (it seems like that, not sure tho)

**Comment by Simonrazer** [comment]
[vgiemission bug.zip](https://github.com/armory3d/armory/files/1433877/vgiemission.bug.zip)
here a .blend

**Comment by luboslenco** [comment]
Thanks, this will come handy!

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/495.
