### ISSUE TITLE
Change storage node functionality location.

### ISSUE THREAD

**Issue by Armory-Community-Channel** [armory3d/armory#2856]
![s](https://user-images.githubusercontent.com/116981508/232575531-457c03f2-deb0-44a3-bc2c-06afec7e5b30.PNG)
By default the storage node stores the data in the saved games folder in the C drive but I think it would make more sense for it to add it to the project folder. This would make accessing it much easier and generally just makes more sense in my mind.

**Comment by Armory-Community-Channel** [comment]
Probably more cons than pros.

**Comment by MoritzBrueckner** [comment]
To quote @ QuantumCoderQC on Discord:

> "This would quickly become complicated when you want to publish to different platforms. Each platform has a dedicated way of saving game data. You cannot have the same path for android, ios and windows..."

I agree with this, it's probably best to stick to Kha's implementation for which we know that it works, so for now I will close this issue (it's probably more of a Kha issue anyways). The storage paths are documented [here](https://github.com/armory3d/armory/wiki/reference_basic#write-storage).
