### ISSUE TITLE
Debug console is broken

### ISSUE THREAD

**Issue by e2002e** [armory3d/armory#2875]
Hi, we currently cannot use the debug console (Ubuntu 22.04).
armsdk/armory/Sources/armory/ui/Canvas.hx:5: characters 1-29 : Type not found : zui.GraphicsExtension
armsdk/armory/Sources/armory/trait/internal/DebugConsole.hx:88: characters 26-32 : Type not found : Canvas

**Comment by MoritzBrueckner** [comment]
Hi, you need to update Zui (see https://github.com/armory3d/armory/pull/2874 and https://github.com/armory3d/zui/pull/164).

**Comment by e2002e** [comment]
Hi, thanks for the info.
Since you'r "here", just want to share my advances with voxel gi : https://forums.armory3d.org/t/voxel-gi-with-clipmaps/5242
I'll need some advise for compute shaders and also gpu particles.
