### ISSUE TITLE
Soft Shadow build fail (Build 14)

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#289]
Fails to build the F5 thing if Soft Shadows is set to "Auto" or "On". That says the console:

Armory v17.10
OS: win, Target: krom, GAPI: opengl
Exporting Scene
Armory Warning: Armory Warning: No camera found in active scene
Armory Warning: No camera found in active scene layers
Armory Warning: Creating default camera
Scene built in 0.015569448471069336
Exported modules: []
Running:  ['C:/Users/SK/Desktop/Armory/Armory/armsdk//nodejs/node.exe', 'C:/Users/SK/Desktop/Armory/Armory/armsdk//win32/Kha/make', 'krom', '-g', 'opengl', '--to', 'build_build_2/window']
Using Kha from C:\Users\SK\Desktop\Armory\Armory\armsdk\win32\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (blur_adaptive_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA_CToneFilmic.arm).
Exporting asset 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (ssr_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (sss_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (translucent_resolve_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (world_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (noise64.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (Sky_irradiance.arm).
Exporting asset 1 of 1 (Sky_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_translucent.frag.glsl).
Compiling shader 1 of 1 (Material_translucent.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_voxel.frag.glsl).
Compiling shader 1 of 1 (armdefault_voxel.geom.glsl).
Compiling shader 1 of 1 (armdefault_voxel.vert.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA_CToneFilmic.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA_CToneFilmic.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssr_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssr_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (sss_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
ERROR: C:\Users\SK\Desktop\Armory\blends\b\build_build_2\compiled\Shaders\sss_pass\sss_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl:101: 'sssWidth' : undeclared identifier
ERROR: C:\Users\SK\Desktop\Armory\blends\b\build_build_2\compiled\Shaders\sss_pass\sss_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl:101: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.

ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link

Compiling shader 1 of 1 (sss_pass_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (translucent_resolve_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (translucent_resolve_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_Irr_EnvSky_Rad_PCSS_CSM_Rad_Irr_VoxelGI_SSAO_SSS_SMAA.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-text.vert.glsl).
Compiling shader 6 of 8 (painter-video.frag.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-image.vert.glsl).
Done.
Build failed, check console

**Comment by luboslenco** [comment]
Thanks a ton for opening the issues, more patching tonight!

**Comment by luboslenco** [comment]
Do you still have `.blend` for this one? Seems to be ok now.

**Comment by Simonrazer** [comment]
Yep here it is
[bug.zip](https://github.com/armory3d/armory/files/1405783/bug.zip)

**Comment by luboslenco** [comment]
It builds!
