### ISSUE TITLE
animation_instanced example project model/rendering issues

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#29]
![animation_instanced](https://cloud.githubusercontent.com/assets/9007314/20079182/df78cff2-a543-11e6-8cf7-5ab3e1ea6db8.jpg)

Tested in Windows as well to rule out Linux specific issues. Perhaps some recent change in Armory has broken the sample project? animation example project which uses the same model does not have this issue.

INFO Linux
Arch Linux 4.8.6-1-ARCH #1 SMP PREEMPT Mon Oct 31 18:51:30 CET 2016 x86_64 GNU/Linux

Armory_p01_linux64 - PLUGIN ONLY, not the custom blender build

Blender 2.78 (sub 0)
build date: 2016-10-27
build time: 06:09:01
build commit date: 2016-10-24
build commit time: 12:20
build hash: e8299c8
build platform: Linux
build type: Release

Python 3.5.2 (default, Jun 28 2016, 08:46:01)
[GCC 6.1.1 20160602]

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 780/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 375.10
OpenGL core profile shading language version string: 4.50 NVIDIA

INFO Windows
Windows 8.1

Armory_p01_win32 - with bundled Blender, Python etc.

Renderer: Intel(R) HD Graphics 3000
Vendor: Intel
OpenGL Version: 3.1.0 - Build 9.17.10.4229
Shading language version: 1.40 - Intel Build 9.17.10.4229

**Comment by luboslenco** [comment]
Yup, was a recent change unfortunately. I added support for
https://www.khronos.org/registry/webgl/extensions/OES_element_index_uint/
to make rendering meshes with high indices count possible, and did not update instanced rendering part. Will be fixed in next build.

**Comment by luboslenco** [comment]
Fixed in Build 2.
