### ISSUE TITLE
Rigidbody Spawn Problem (Build 14 (and 13+12 too I think))

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#290]
When spawning a Rigidbody via the "Spawn Object" Node, it ignores the Transform plugged into this Node and places it at 0,0,0,

**Comment by luboslenco** [comment]
Very nice bug discovery. Should be now resolved in https://github.com/armory3d/armory/commit/219e1e8ede16ad1bad2ea5c7ee57ee008510a12b.

Build 14 has a built-in updater located in Armory add-on preferences, which may work to fetch this patch. But it may also break since it's new/untested feature.

**Comment by Simonrazer** [comment]
Yes it is working now!
