### ISSUE TITLE
WARNING: Node tree "wall": material node type MIX_RGB not supported

### ISSUE THREAD

**Issue by onelsonic** [armory3d/armory#2901]
Thank you for contributing to Armory!

Issue description : 
After upgrading to Blender 3.6 
the standard blender material node MIX_RGB is not supported anymore.
<img width="200" alt="MIX_RGB" src="https://github.com/armory3d/armory/assets/53947594/b04d381d-d06e-40d0-bce9-a2458a3eb479">
and returns the following : WARNING: Node tree "wall": material node type MIX_RGB not supported

**To Reproduce**
Just add an object with the MIX_RGB node in its material.

**Expected behavior**
What you expected to happen : the MIX_RGB node should render correctly.

**System**
Blender: 3.6.0
Armory: latest GIT repo
OS: win10

**Comment by onelsonic** [comment]
need further tests

**Comment by MoritzBrueckner** [comment]
The Mix RGB node was replaced with a more generic mix node in 3.4 (see https://github.com/armory3d/armory/issues/2821), but the [Blender release notes](https://wiki.blender.org/wiki/Reference/Release_Notes/3.4#Compatibility) state that "_The "MixRGB" node for Shader and Geometry Nodes is converted to the new "Mix Node" on loading_". So if this isn't the case, this is likely a Blender bug.
