### ISSUE TITLE
Looking for possibility to switch back to old bloom effect. If not too much work. It simply was looking better IMHO.

### ISSUE THREAD

**Issue by StrandedAlien** [armory3d/armory#2912]
Hi,
Impossible to restore the old more natural look of bloom for the glow wires of my IN14 Nixie tubes. The only way back: Rolling back everything and compile with older version of Armory SDK B4 the change. With the new Bloom effect (see PIC 1) the range of settings does not allow me to show this washed out effect like seen on the second picture (old bloom effect). Everybody who has ever seen some real Nixie tubes will have to admit, that it looks a lot like in the second pic. Such an effect is not to achieve anymore with the new bloom. Similar for Neon tubes. Was better before. Now the wires are always way to sharp.

New bloom effect:
![image](https://github.com/armory3d/armory/assets/89656885/e1942555-dd79-4abe-8c0b-e7d17c8fbcfe)

Old bloom effect:
![image](https://github.com/armory3d/armory/assets/89656885/1ecebbba-a15b-4d89-9a67-a93cbf749c9c)

**Comment by MoritzBrueckner** [comment]
Hi, you can still achieve the look of the bottom picture by decreasing the bloom radius:
![Bloom](https://github.com/armory3d/armory/assets/17685000/4939decb-044f-40d4-b6c6-2cb4c7245aeb)

![Blender bloom settings](https://github.com/armory3d/armory/assets/17685000/ee7d2060-64c4-4c44-a4be-c5bf520da6cd)
