### ISSUE TITLE
[Suggestion] locking axis translation and rotation through the UI

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#292]
Right now it's possible to lock axis translation and rotation through script using `RigidBody.setAngularFactor(x,y,z)` and `RigidBody.setLinearFactor(x,y,z)`.

It would be nice to be able to set this through the UI without having to add a script etc. Similar to how it's done in BGE, Unity and others.

![image](https://user-images.githubusercontent.com/9007314/31885676-94d5f800-b7f1-11e7-82bb-7a0e34c4019a.png)

**Comment by luboslenco** [comment]
Done! Can now access Linear/Angular factor in `Armory Props` using https://github.com/armory3d/armory/commit/505ccb7cafd50f53b1eca1dfaaf08204862182db. Setting to 0 locks the axis.

**Comment by guzzard** [comment]
awesome :-)

**Comment by guzzard** [comment]
have tested rotation and it's working very nicely! :+1:
