### ISSUE TITLE
Groups management using Logic nodes

### ISSUE THREAD

**Issue by samvila** [armory3d/armory#294]
Hi,

It would be nice to have some way to manage objects based on groups using logic nodes. That way we can for example place several objects on a group call 'enemies' and then if in a game is needed to destroy all the enemies at once using a power up or something we can use the node group to deal with each individual object under the category 'enemies'.

**Comment by luboslenco** [comment]
Logic nodes are now capable of basic group management. `Group` node returns an array which can be accessed using array nodes like usual. Print names of all objects in group:

<img width="710" alt="1" src="https://user-images.githubusercontent.com/3685704/33258760-f059e9a0-d35a-11e7-8d80-b04c0fc6df82.png">

Add/Remove object to/from group:

<img width="698" alt="2" src="https://user-images.githubusercontent.com/3685704/33258770-f3508d3a-d35a-11e7-9546-c1adf73ef858.png">

Add/Remove group itself at runtime:

<img width="533" alt="3" src="https://user-images.githubusercontent.com/3685704/33258777-f658c736-d35a-11e7-81b4-3bdffabfca6d.png">
