### ISSUE TITLE
C Target on Linux results in black screen

### ISSUE THREAD

**Issue by ruapotato** [armory3d/armory#2949]
**Description**
Trying to export for Linux(C) does not work right. It ends up as a black screen. Run logs:
```
$ ./sound_1_0_0 
Starting KincHL
Using OpenGL version 4.6 (forward-compatible).
iron.data.Data:424: {url : ./data/Scene.arm, error : Could not load blob(s)}
```

**To Reproduce**
 * Install Debian 11
 * Download blender blender-3.6.4-linux-x64
 * Download ArmorySDK2310.zip
 * Install plugin and enable
 * Load Sound example.
 * Select `linux-hl` from Amory Exporter and hit Publish
 * Build project with 
    - `cd ~/Downloads/armory_examples-22.06/sound/build_sound/linux-hl-build/Release`
    - `make -j4`
 * Run with `./sound_1_0_0 `

**Expected behavior**
A window of the Sound example.

**System**
Blender: blender-3.6.4-linux-x64
Armory: ArmorySDK2310
OS: Debian 11
Graphics card: GTX 1060

**Comment by Onek8** [comment]
For hashlink you need to move your binary from the linux-hl-build/ (release or debug folder) and move it into the actual linux-hl folder where the "data" folder is which causes iron.data.Data:424: {url : ./data/Scene.arm, error : Could not load blob(s)}
Sorry for this confusion :) should fix your problem

**Comment by ruapotato** [comment]
@Onek8 That was it. Thank you so much!
After copying the binary to `../../linux-hl/` and running it from that folder, things started working.
