### ISSUE TITLE
Read scene structure using logic nodes

### ISSUE THREAD

**Issue by samvila** [armory3d/armory#295]
It would be interesting to have some logic nodes to read how the scene is being structure and a way to alter this.

For example a node that reads the scene and tells you how many objects are on it and their names. If this node is used on an specific object it provides you with any child object with the name. This would be very beneficial for keep track on game elements on the scene on the runtime and deal with some of these elements individually if needed.

**Comment by luboslenco** [comment]
It is now possible using `Scene Root` and `Get Children` nodes, added example at https://github.com/armory3d/armory_examples/blob/master/logic_tests/logic_scenetree.blend.

**Comment by samvila** [comment]
Hi Lubos, thanks  for this. That said I think this is not the best approach to manage items on a game. For example with your method you remove an specific object from it's parent as far as I know. 

In my opinion we should have another set of nodes to deal with blender groups:


![](https://docs.blender.org/manual/en/dev/_images/editors_3dview_object_properties_relations_groups_panel-outliner.png)

Using Blender groups instead of parent/child relationship could be very beneficial. The nodes could be something like this:

- Create group
- Delete group
- Add objects from Group
- Remove object from the group
- Retrieve objects from the group

Just my opinion.

**Comment by luboslenco** [comment]
Yes, working on that as part of your request at https://github.com/armory3d/armory/issues/294, this will only do for reading scene structure. :)

**Comment by samvila** [comment]
Awesome. Thanks Lubos. I like what you did on having nodes for get children. It's great that on Armory you can set parents from objects to objects but that's a different type of workflow. It would be also nice to have a node in Armory to unparent objects.

**Comment by luboslenco** [comment]
Added a proper `Clear Parent` node now, which acts like the `Clear Parent` operator in Blender.
<img width="460" alt="clp" src="https://user-images.githubusercontent.com/3685704/33244832-aa644b2c-d2fe-11e7-9522-d845bdc5da7d.png">

**Comment by samvila** [comment]
Hi Lubos, I updated the sdk to the latest version but I can't find this node or the unparent node. Do you know why?

**Comment by luboslenco** [comment]
If there is no `armsdk/armory/blender/arm/logicnode/action_clear_parent.py` file present then it's the updater to blame. It has issues on repeated updates..

Possible solutions:
- Hit `Restore SDK` first, then `Update SDK` in armory addon preferences
- Install the [latest addon](https://github.com/armory3d/armory/blob/master/blender/addon/armory.py) manually which should have no issues
- New builds up in coming days :)

**Comment by luboslenco** [comment]
Using the latest windows build (v0.1b+), updater should reaaally fetch updates properly now.
