### ISSUE TITLE
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#296]
Lubos,

tank you for all the great work you put into Armory. I've been following the development lately and it's awesome what you have achieved so far.

However, I have the abovementioned issue when trying to activate the Armory Addon in Blender. I downloaded Armory_b14_win64 from the website (I get the same results with Armory_b13_win64). I unzip and then I start Blender.exe. I go to File / preferences / Addons to activate 'Render: Armory' (that is not enabled by default). This gives the following exception:

![image](https://user-images.githubusercontent.com/33040347/31911411-d59848e4-b840-11e7-9d3e-9974adc1c486.png)

```
Traceback (most recent call last):
  File "D:\Programs\Armory\Armory_b14_win64\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "D:\Programs\Armory\Armory_b14_win64\2.79\scripts\addons\armory.py", line 22, in <module>
    from bpy.types import Operator, AddonPreferences
RuntimeError: bpy.types.AddonPreferences subtype could not be generated, this is a bug!
```

The version Armory_b13_win64_blender28 works without any issues.

Best regards
-Sebastian

**Comment by donalffons** [comment]
... I fixed it by deleting the C:\Users\[...]\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend and restarting Armory / Blender

**Comment by luboslenco** [comment]
Thanks for the kind words @donalffons, it really means a lot. Happy you made it work in the end. I wonder if this is somehow caused by Armory itself.
