### ISSUE TITLE
Deferred rendering on mobile

### ISSUE THREAD

**Issue by montonero** [armory3d/armory#299]
Armory has a lot of great samples, but only one (scene1_mobile) runs on mobile, and it looks, well, quite basic.
It would be great to have more that look semi-descent on Android/iOS with better shading and post processing effects.

Tank demo game (scene5) is a good candidate as it has physics/input/scripting which all can be tested together with deferred shading.

**Comment by montonero** [comment]
By the way, more than half of Android devices have OpenGL ES 3.0 support now: https://developer.android.com/about/dashboards/index.html

**Comment by luboslenco** [comment]
Sadly very much true. Planning to hook up some touch-based gizmo controls soon, and then get on to more mobile-tuned examples.

**Comment by takhimi** [comment]
Do you plan to integrate other mobile services and API ? IAP, Ads, Gamecenter and etc2 ?

**Comment by montonero** [comment]
Integrating native mobile services and other native libraries can be done
in pure haxe / kha.
I have done some work and will try to release something as kha samples.
Is there anything particularly you are looking for?

**Comment by takhimi** [comment]
Really ?? That is awesome. My suggestions are

Ads
1)Admob (Banner, Interstitial, Rewards) Android, IOS
2)Chartboost (Android, Amazon, IOS)
3)Adcolony or maybe Vungle ?

Social Services
1)Google Play Services (Leaderboards, Achievement, and etc)
2)GameCenter (Leaderboards, Achievement and etc
3)Facebook API ?
4)Amazon Gamecircle

Desktop game services
1)Steam API
IAP (IOS, Android, Amazon)

**Comment by luboslenco** [comment]
- Forward path supports additional effects like ssr now
- Deferred path also has support for lighter Mobile materials now
