### ISSUE TITLE
ArmourPaint isnt wroking

### ISSUE THREAD

**Issue by MHS5706** [armory3d/armory#2997]
I followeed every step and it was going smoothly till I tried to open the program to see if it works, and it doesnt run at all and it creates a "kinc.dmp" file and that has this inside when opened in visual stuido
![image](https://github.com/armory3d/armory/assets/159597258/cd7cc9ff-e8b9-458f-87e2-8e72b20b8695)

**Comment by MoritzBrueckner** [comment]
Hi, this is the wrong repository (it's for the Armory 3D game engine), please reopen this issue at https://github.com/armory3d/armortools.
