### ISSUE TITLE
Add support for "parent to bone"

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#301]
Hello,

I want to create an industrial assembly line simulation involving a couple of robots like this one.
![image](https://user-images.githubusercontent.com/33040347/32070024-3bf82a36-ba8b-11e7-86d2-4416054ffed0.png)

In this context I have the following issue (simplified example):
Currently Armory only seems to support armatures using the Armature Deform Modifier. The "parent to bone" method seems to be not supported.
![image](https://user-images.githubusercontent.com/33040347/32070707-80910eea-ba8d-11e7-951f-03a076464cda.png)
![image](https://user-images.githubusercontent.com/33040347/32070236-02f7a8fa-ba8c-11e7-8ca1-4e0701956bdf.png)
[armature animation1.zip](https://github.com/armory3d/armory/files/1419630/armature.animation1.zip)

The aramature deform modifier in this case is not well suited, as it is very slow (at least inside Blender). There are other drawbacks as well.

I hope this can get implemented soon :). I already love Armory!

Best regards
-Sebastian

**Comment by luboslenco** [comment]
Hello Sebastian,

Amazing project you are working on. I have added support for "parent to bone" method (patches https://github.com/armory3d/iron/commit/7fbee21abf59989fdf268c8b17ffb622a3a7141f and https://github.com/armory3d/armory/commit/09ca7dff2840f2ec3df6bd1651baf818ef695732). Using build 14, `User Preferences... - Addons - Armory - Armory Updater` and then restarting Blender should be able to fetch those.

I only briefly tested using your .blend file, issues may appear on non-simplified scenes. Please let me know if that is the case.

![bone](https://user-images.githubusercontent.com/3685704/32145863-81108082-bccf-11e7-8eaa-a0d355bbb021.jpg)

**Comment by donalffons** [comment]
That's awesome, Lubos. Thanks for your responsiveness.

There are however a couple of issues with the non-simplified model. Some objects are not transformed correctly.
![image](https://user-images.githubusercontent.com/33040347/32147872-44212716-bcee-11e7-9f96-1ea0c144006f.png)

I attached the non-simplified model as a reference for you.
[Robot Animation2.zip](https://github.com/armory3d/armory/files/1425459/Robot.Animation2.zip)

Quick explanation of the rig: Only the red bones (named axis-1, axis-2, ...) are moving. The gray bones (link-1, link-2, ...) are static.
![image](https://user-images.githubusercontent.com/33040347/32147898-db754782-bcee-11e7-8da7-67685421ee8d.png)

**Comment by luboslenco** [comment]
Pushed a fix in https://github.com/armory3d/armory/commit/b728165799a2b6c31090ffbf975fcde8bbef93a1. The robot appears to work now! Any more issues you can spot?

![bones2](https://user-images.githubusercontent.com/3685704/32150556-eb26ffce-bd14-11e7-9845-f09ee030763a.jpg)

**Comment by donalffons** [comment]
I can confirm that :). It's working flawlessly now.

https://s3.amazonaws.com/donalffons-interface/Armory/Robot%20Test%2001/html5/index.html

If you're interested, I will keep you updated on my little use-case for a (more or less) interactive assembly line simulation in Armory.

Thank you, Lubos!

**Comment by luboslenco** [comment]
Incredible. Definitely interested (and ready to fix more issues you may encounter)!

**Comment by AndreaMonzini** [comment]
It works very well even on my old iMac ( 2009) !
I only noticed some z buffer or coplanar problems with shadows

![screen shot 2017-10-31 at 6 58 21 pm](https://user-images.githubusercontent.com/12413409/32240476-bc891bac-be6d-11e7-8dc7-6269d736e5d1.png)

**Comment by donalffons** [comment]
It's awesome that it works even on old hardware! Thanks for your feedback.

The Z Buffer problem is not Armory's fault, but mine - the floor plane and the robot's base plate were both on exactly the same level. I fixed that in the little demo now.

...and Lubos, I am honored to have this featured on your website :).

**Comment by AndreaMonzini** [comment]
i'm testing this project on mobile and unfortunately it doesn't work:
iPad® 3 iOs® 9= Black window
iPad® Air iOS® 11= Black Window

**Comment by luboslenco** [comment]
The trouble is mobile has limited access to webgl extensions. Try locating `Properties - Render - Armory Render Path` and set Preset to `Mobile Low` (or manually set `Renderer` to `Forward` and `Materials` to `Mobile`). Ideally also use just one dynamic light. In the future there should be an option to handle this 'fallback' automatically.

**Comment by tarwin** [comment]
That's super awesome. And it works perfectly for me too (Chrome / MacOS). One quick question: is there a default HMTL loader display? Also, is there a way to have all assets packaged somehow because it takes FOREVER to load just because there are so many TINY files.

**Comment by luboslenco** [comment]
Hey @tarwin, there is a loader display(tiny red bar), but only shows up for 'Publish' builds right now. This also enables dead-code-elimination to shrinks the JS file. It is also possible to export full scene into a single file (and then compress this file), have to expose & document these better. :)
![capture](https://user-images.githubusercontent.com/3685704/32404043-9e0e3b16-c148-11e7-9a08-3768967f11e2.PNG)
