### ISSUE TITLE
Vertex groups

### ISSUE THREAD

**Issue by BaHO4ka-1** [armory3d/armory#3017]
What about adding the ability to work with Blender's vertex groups? Like, adding, removing, a function that will allow to get all vertices in a vertex group, a function that will check if a certain vertex is in a vertex group?

**Comment by t3du** [comment]
I wanted to add vertex group for a long time, I just did it Im gonna make the PR. Values will exist in a variable in object class, so you can retrieve them, modify them, compare them, use them even though object does not have geometry like mesh curves.

![image](https://github.com/user-attachments/assets/f2b2223d-07a3-4cfa-9ae9-11387dc23f44)


![image](https://github.com/user-attachments/assets/3e9131eb-f231-453f-be02-1bbc581f04f8)

**Comment by BaHO4ka-1** [comment]
Thanks
