### ISSUE TITLE
Build 14a Setting Armory Project to fullscreen will crash to desktop when run in viewport

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#302]
Example open scene5, In Armory Project->Window:->Set to Fullscreen (Default is window)
Click "Play in Viewport". 

Will crashed to desktop.

Win 10 64Bit

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/armory/commit/ffe3271f0a86f706f4b98c043b687b602eac9fe7. Thanks a ton for reporting this!
