### ISSUE TITLE
Tooltips for logic nodes.

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#303]
I'd really like to see solid tooltips for the logic nodes. It makes it easy to do rapid prototyping when you forget what a given node might stand for. I put a link below for an example.

https://docs.blender.org/manual/en/dev/getting_started/help.html

**Comment by luboslenco** [comment]
Refer to the http://armory3d.org/manual/#/logic_nodes/nodes for now, PRs for more nodes welcome!
