### ISSUE TITLE
Mobile and Desktop game services

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#304]
Hi

Looking at the awesome armory growth, I'm really impressed at the armory3d. In my opinion, right now maybe it is time that armory starts to provides critical features for the user for monetization and mobile and desktop services.

Right now for mobile, if we want to published our games and have monetize it for mobile, we can only sell the game on IOS and android. Would be great if all the critical services are integrated officially in armory for us to use (in logic nodes and scripting). My suggestions for the critical services to be included in armory officially are as follows..

Ads
1)Admob (Banner, Interstitial, Rewards) Android, IOS
2)Chartboost (Android, Amazon, IOS)
3)Adcolony, maybe Vungle also ?

Social Services
1)Google Play Services (Leaderboards, Achievement, and etc)
2)GameCenter (Leaderboards, Achievement and etc
3)Facebook API ?
4)Amazon Gamecircle (Leaderboards, Achievement and etc)

IAP
1)IOS, MacOS
2)Android
3)Amazon

Desktop game services
1)Steam API (Achievements, Cloud saving, etc)

Regards

**Comment by Kotarosdevgame** [comment]
Yes i aggree with takhimi Mobile and Desktop game services would ne nice

**Comment by luboslenco** [comment]
Linking to the list of currently available Kha libraries:
https://github.com/Kode/Kha/wiki/Libraries#wrappers-for-native-libraries
