### ISSUE TITLE
Download link on github itself or instruction to build from source with revision

### ISSUE THREAD

**Issue by MadMcCrow** [armory3d/armory#3041]
I'm developing a tool to make games with Haxe, Nix (the language) and nixpkgs (the packet manager). The idea is providing an all-in-one shell environment for linux and MacOS (with the help of nix-darwin) to write, build, and distribute games made with Haxe. I've already done the necessary setup to support the heaps game engine and raylib (with hxcpp). I thought that having Armory3D would be the logical next step. 

I can get blender LTS (prebuilt, building on nix-darwin is broken ATM), but unfortunately, to get Armory working I would either need a guide to build the SDK from source, or a direct link download that does not require authentication (nor does expire) that can be scripted. 

I've also noticed there are no "releases" here on GitHub (at least since 2021), even thought this would be the perfect place to get the engine from.

Thank you in advance for your help, and don't hesitate to ask if there's anything I can do to help!

**Comment by luboslenco** [comment]
Hi, check here for releases: https://github.com/armory3d/armsdk/releases.
