### ISSUE TITLE
Better file and folder structure for published game

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#305]
Moving forward for production ready game, maybe it is time that we have a better folder structure when we published our games. Example, any effects in "Effects" folder and etc.

![armory file structure](https://user-images.githubusercontent.com/4146156/32153490-dc892978-bd65-11e7-92c1-791086ba4dc6.jpg)

**Comment by luboslenco** [comment]
Assets are now placed in `/data` folder for published games.
