### ISSUE TITLE
"Portal"- Logic Node

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#307]
I think it would be handy if there could be a "Portal In" Node, in which you plug in objects/values that you need in another Logic Node Trait. In this trait you create a "Portal Out" Node, give it the name of the "Portal In" node, and all the outputs magicly appear. A little bit like the Node group nodes in Cycles materials.

**Comment by Simonrazer** [comment]
This node or another concept of global variables is starting to become realy needed for the ACXT3R-project, mainly for hit recognition and the enemys reaction to that, which are in 2 different traits.

**Comment by luboslenco** [comment]
I added a new example which makes it possible to call node groups from other node groups. There is no input/output sharing yet, so output has to be set by a global property.

https://github.com/armory3d/armory_examples/tree/master/logic_callgroup

![call](https://user-images.githubusercontent.com/3685704/32623737-6b07dad6-c587-11e7-90c1-7263dd024e59.jpg)

To communicate with other logic trees - example on events:
https://github.com/armory3d/armory_examples/tree/master/logic_globalevent
