### ISSUE TITLE
Audio/Sound not working in Krom

### ISSUE THREAD

**Issue by Naxela** [armory3d/armory#308]
Hi, I'm not sure if the issue is already brought up, but I think it might be related to this [issue](https://github.com/armory3d/armory_examples/issues/5), basically sound doesn't work in Krom, although I can confirm though, that on Windows audio works perfectly fine with Native C++ and Browser runtimes.

**Comment by luboslenco** [comment]
Fix incoming https://github.com/Kode/khamake/pull/123.

**Comment by luboslenco** [comment]
Krom should be ok now, viewport to go: https://github.com/armory3d/armory/issues/253.
