### ISSUE TITLE
'PlayAction' node not does not work with Armature

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#309]
Hi Lubos,

I want my robot animation to play, after some event is triggered. While that works with an object, it does not seem to work with the armature.
![image](https://user-images.githubusercontent.com/33040347/32234374-e69b11d6-be5c-11e7-8ad7-f8475741fe02.png)

I set up my NLA tracks / action like this:
![image](https://user-images.githubusercontent.com/33040347/32234273-9ef6ed82-be5c-11e7-9169-d0121b1d6fc8.png)

When the user clicks, I want suzanne and the robot to move, using the following node setup:
![image](https://user-images.githubusercontent.com/33040347/32234343-d0317444-be5c-11e7-89f6-aafcd4a43406.png)

That gives the following error message:
![image](https://user-images.githubusercontent.com/33040347/32234432-0c5465bc-be5d-11e7-8b35-7bca30780a8a.png)

If I disconnect or delete the two nodes, controlling the robot, it works fine for suzanne.

[Issue.zip](https://github.com/armory3d/armory/files/1431373/Issue.zip)

**Comment by luboslenco** [comment]
Patched! (https://github.com/armory3d/iron/commit/b9bfbddb3e1b39bc8d9a1c6d1a5a18e50c39d19c, https://github.com/armory3d/iron/commit/3f9cd98541dcdc89304718d5de3ad8e7c101f79a and https://github.com/armory3d/iron/commit/464545052e7864b1710c2cfac134fbf5f7026d32)

Also monkey should no longer disappear for a single frame when switching action. Let me know if it works for you.

**Comment by donalffons** [comment]
Works perfect!
