### ISSUE TITLE
BPR and Cycles Transparency not working!

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#31]
Whenever I try to add transparency either with the BPR or with the cycles node, the mesh just dissapear! I've tried several ways and checking the type of viewport transparency and no success. I can only render solid objects without transparency. (Using Windows 10)

**Comment by E25543** [comment]
Hello Jean,

here's Lubos' answer in case you did not get it.

"To enable it, in Camera data - Armory props - Render path select deferred_path_high. Obviously there is no way to intuitively discover this, working on render path generator which will enable needed features automatically(and more) to fix it."
https://github.com/armory3d/armory/issues/63

I confirm it works! (in a browser)

**Comment by luboslenco** [comment]
Still working to make this more pleasant, continuing at https://github.com/armory3d/armory/issues/87.
