### ISSUE TITLE
Inconsistency with 'Set Parent' Node?!

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#310]
I have the following setup:
![image](https://user-images.githubusercontent.com/33040347/32252940-825127f6-be98-11e7-8774-d43064d34314.png)

Suzanne should be parented to the respective cube. The difference is that the box on the right side has an idle animation (no motion).

When I click the mouse button, the left and right side behave differently. The right suzanne jumps.
![image](https://user-images.githubusercontent.com/33040347/32252986-cf0439c6-be98-11e7-9f83-76046b61fe29.png)

I think they should behave in the same way. My preference would be to have no jumping (i.e. left side behaviour).

[Issue.zip](https://github.com/armory3d/armory/files/1432596/Issue.zip)

**Comment by luboslenco** [comment]
Good catch - should be now fixed in https://github.com/armory3d/armory/commit/932b3827d5d7d4166913a4bd143a58c9765897ca and https://github.com/armory3d/iron/commit/e53515752a8a43ba0753a6c88a362aa86f6d7fee.

**Comment by donalffons** [comment]
Yes sir!

There are two other issue, that are related to parenting I think.
I want my robot to pick up suzanne (parenting to an empty called TCP) and move her, then drop her.
![image](https://user-images.githubusercontent.com/33040347/32272131-091071fc-befd-11e7-8401-4f7a6fe56503.png)
In blender that (kinda) looks like this:
[render0000-0300.zip](https://github.com/armory3d/armory/files/1433887/render0000-0300.zip)

**Issue 1:**
There is some lag between Suzanne and the TCP empty, as you can see here (left click to run):
https://s3.amazonaws.com/donalffons-interface/Armory/Robot%20Test%2005/html5/index.html
At the end of the example, it crashes because of Issue 2.

**Issue 2:**
After the robot drops Suzanne, I want to remove the parenting relationship between the TCP and her. My attempt gives an error:
![image](https://user-images.githubusercontent.com/33040347/32272223-6bfdb842-befd-11e7-9f60-fbcf21ce6f1b.png)

[Issue.zip](https://github.com/armory3d/armory/files/1433923/Issue.zip)

**Comment by donalffons** [comment]
Brilliant! With the un-parenting feature at hand, I am able to continue.
Thank you Lubos! :)
