### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by yulbryn** [armory3d/armory#312]
Is there any way to have global variables available in armory Traits ?
If not, how about having an editable list somewhere in the render panel ?

**Comment by yulbryn** [comment]
One global variable (not editable) I would also like to find is the path of the current project (to use relative paths in code).

**Comment by Simonrazer** [comment]
They start to become realy needed for the ACXT3R-project, mainly for hit recognition and the enemys reaction to that, which are in 2 different traits.

**Comment by luboslenco** [comment]
Added two logic node examples which could aid in this. Ideally we would keep logic trees mostly self contained so it's easy to share them around in different blend files.

- Sending event in one logic tree, then getting notified in another logic tree: 
https://github.com/armory3d/armory_examples/tree/master/logic_globalevent
- Setting a custom (global) property for object, scene root, or global object:
https://github.com/armory3d/armory_examples/tree/master/logic_setproperty

@yulbryn I suspect you are not talking about logic nodes? Would you be able to move code accessing current project path into the build system / `khafile.js`? That one should have `__dirname` value defined.

There is also a possibility to read files at [compile time](https://github.com/jasononeil/compiletime) in Haxe. And perhaps also resolve path to a file using a [macro](https://api.haxe.org/haxe/macro/Context.html#resolvePath).

**Comment by Simonrazer** [comment]
It seems like the "Send global event" node is not working, I get this error: 
`C:\Users\SK\Desktop\ACXT3R\Sources/arm/node/Laser.hx:8: characters 29-65 : Type not found : armory.logicnode.SendGlobalEventNode`
But thanks for adding it!

**Comment by luboslenco** [comment]
Are you on the latest armory(should have mention that)? If so can you check for `armory/Sources/armory/logicnode/SendGlobalEventNode.hx` file?

**Comment by Simonrazer** [comment]
yes i am running the latest version, at least that what the console says. here is the file and the .blend:
[globalevent.zip](https://github.com/armory3d/armory/files/1458897/globalevent.zip)

**Comment by yulbryn** [comment]
@luboslenco I was indeed not talking about nodes but having global variables available in Sources hx files.
In fact, I am looking for a clean way to read an dynamic file (here containing a json) that is continuously read at runtime and written by an other app/process.

**Comment by yulbryn** [comment]
I too have an "Undefined" node in the logic_setproperty example, even with SDK updated on 2.79.

**Comment by luboslenco** [comment]
- Project path is now accessible using `Main.projectPath`
- Added an example on reading property set from logic nodes in script: 
https://github.com/armory3d/armory_examples/tree/master/script_logic_talk/property
- Added an example on reading script properties in other scripts, this allows to set values in UI and read them anywhere:
https://github.com/armory3d/armory_examples/tree/master/script_properties_global

![capture](https://user-images.githubusercontent.com/3685704/32656663-1cecb506-c613-11e7-887a-a1a606e082eb.PNG)

It looks like updater is sometimes not working properly, will check it out. Perhaps `Restore SDK` and then `Update SDK` again would do as a workaround.

**Comment by yulbryn** [comment]
Restore then Update worked. Seems the updater needs some improvements :).

**Comment by yulbryn** [comment]
I did not know you could add Armory Traits to the scene! This is an elegant solution, close to the one I had.

**Comment by Simonrazer** [comment]
@luboslenco yes restoring SDK and then updating with restarts inbetween made it work and also the "Ghost" button in the physics-tab show up!

**Comment by luboslenco** [comment]
Awesome! I will dig up why the updater is not pulling properly, at least the workaround worked. 

Yeah, scene traits still quite recent, but seem to work ok.:) They will get instantiated before object traits as one would expect.
