### ISSUE TITLE
Recreating the 'script_linkedgroup' example gives error

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#314]
I want to use group linking for my little use case. Unfortunately Armory always gives me the same error message:
![image](https://user-images.githubusercontent.com/33040347/32299598-75787a66-bf56-11e7-9c27-9d62417b3855.png)

I tried to narrow down the problem by starting with the script_linkedgroup example. In the example folder, I created a new blender file (i.e. File => new), named linkedgroup - copy.blend.
![image](https://user-images.githubusercontent.com/33040347/32299666-b19e5330-bf56-11e7-9021-99d8f0163b87.png)
In this file, I tried to recreate the contents of the linkedgroup.blend (more or less) exactly.

1. I linked in the 'PinGroup' group from pin.blend
2. moved the 'PinGroup' object to 2nd layer
3. created the floor plane, assigned rigid body (not dynamic), unlinked the 'RigidBodyWorld' group in outliner (probably has no influence...)
4. created new haxe script trait for 'Camera' object, class: PinSpawner

After I run and click the left mouse button, I get the error. Am I missing something?

[script_linkedgroup.zip](https://github.com/armory3d/armory/files/1435850/script_linkedgroup.zip)

**Comment by luboslenco** [comment]
Fixed now! Thanks again for reporting these. (https://github.com/armory3d/armory/commit/8be4c457c9f4a19f16acc28a428862ff2333a57a)

**Comment by donalffons** [comment]
Cool! 👍
