### ISSUE TITLE
Material Compile Error X3004 Fragment Shader

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#318]
Tried to build in latest git version to test this out: https://github.com/armory3d/armory/commit/8efdc60e82f39f6a5eada6977d7a7c116ed53fa6

Now I'm getting this error: Material_mesh.frag.hlsl(34,49-60): error X3004: undeclared identifier 'gl_FragCoord'

**Comment by luboslenco** [comment]
Hm, it looks like you are using Direct3D renderer. Will have to handle it differently there. Or is this happening even on default settings(OpenGL)? Maybe a bug in Armory triggering wrong graphics api somehow.

**Comment by Defaultsound** [comment]
Hmm, now I'm not sure. I think I may have pulled from Git incorrectly? I believe I am on the default settings. I haven't switched any renderer settings as far I as I know.

**Comment by Defaultsound** [comment]
Okay I did a build to windows with OpenGL through Visual Studio and it seems to work. The compile error happens when you press play in viewport. So not sure what happens there.

![image](https://user-images.githubusercontent.com/5720489/32406982-72e59a3e-c179-11e7-88e3-7f50eb7a9ef6.png)

**Comment by luboslenco** [comment]
No need to build the git pull, changes will work automatically.

Argh, I know the cause. There is a [regression](https://github.com/Kode/khamake/issues/118) in latest Kha which prevents setting a graphics api for Krom player. Using Kha from Build 14 should work. 

Build 14 also has an experimental updater in `User Preferences... - Add-ons - Armory`, which can pull the repositories for you. You would still need to revert Kha to Build 14, sorry for trouble. ;/

![capture](https://user-images.githubusercontent.com/3685704/32407014-58bbba72-c182-11e7-92ff-cf897fae02b0.PNG)

**Comment by Defaultsound** [comment]
Ah thanks, I was looking for that, couldn't see where it was. I'll give it another go soon.
