### ISSUE TITLE
"Gate" node not working with objects?

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#319]
I wanted to have a Trait in which a Laser is asked what his first contact was and then it is checked if that is Suzanne, to do that I have a "Gate"-Node set to equal, in the red input an "On Update", in the first Value a "get Object" with Suzanne as name and in the secound Value "get first contact" from "Self".If I hit anything with the Laser, it crashes, but when I hit Suzanne it does what comes out of the "Gate"-Node and then crashes.
[objectnode.zip](https://github.com/armory3d/armory/files/1443828/objectnode.zip)
If there is no way of just checking if two objects are the same, maybe a "get Object name" node can come inbetween the object-nodes and the gate-node. (If the Gate-node can handle a String)

**Comment by Simonrazer** [comment]
It doesnt crash when the red input of the "Gate"- node is fed with an "On Contact"- node, whose input objects are 1."get object" suzanne and 2. "self".

**Comment by luboslenco** [comment]
Hm, the problem appears to be that Suzanne and Laser have different collision groups, which prevents `Get First Contact` from catching the collision. You could now use `Properties - Physics - Armory Props - Ghost` which prevents the collision response but getting the contacts should still work.
