### ISSUE TITLE
Mix RGB & Mix Shader nodes don't work!

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#32]
I am trying to combine several different textures to create a terrain, and whenever I use a Mix RGB node to combine two textures, it doesn't work! It doesn't blend them, nor does it works with a stencil texture. That is something very important for me as an artist, so I can have control over my textures.

 Unless there is another way of doing this?

**Comment by JeannotLandry** [comment]
Still an issue with build 3. I would like to be able to use multiple textures on terrains (mix grass, dirt, rocks) but it doesn't work. Eagerly awaiting for that feature to be implemented.

**Comment by luboslenco** [comment]
Hi,

If still broken, can you provide me with .blend file to replicate & fix?
