### ISSUE TITLE
Node to output a bool if object has any contact

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#320]
All current object-contact nodes need an input for an secound object with wich the "main" one (of interest) collides with. Realy handy would be a Node which has only one "object"-input, which outputs a bool whose Value is true if the object has any contacts with any other object at all, and false if not.

**Comment by luboslenco** [comment]
Want to roll this for regular volume triggers, right now it's only sort of doable with rigid body & physics nodes.
![nodes](https://user-images.githubusercontent.com/3685704/32419847-391581e4-c281-11e7-92ff-90dc44974fb8.PNG)

There is now also a way to turn rigid body into volume trigger using `Properties - Physics - Armory Props - Ghost`.

**Comment by Simonrazer** [comment]
I cant find "Ghost", there is just "Soft body margin" in the physics-tab-> armory props.

**Comment by luboslenco** [comment]
Updating to latest [git armory](http://armory3d.org/manual/dev/gitversion.html) should solve that.
