### ISSUE TITLE
Play Action Node on Armature gives error: "cannot read property 'length' of null'

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#321]
Another robot, another problem :). The problem only arises with this special rig.

This one is hanging from the ceiling. It has an idle animation assigned to it. There is some logic that should play the same idle animation, when the left mouse button is clicked.
![image](https://user-images.githubusercontent.com/33040347/32414262-5c89c45e-c223-11e7-9244-b5dec8e84ba3.png)

When I click the left mouse button, I get the following error message:
![image](https://user-images.githubusercontent.com/33040347/32414268-7f93f992-c223-11e7-95c6-09af3e98622d.png)

[Issue.zip](https://github.com/armory3d/armory/files/1443954/Issue.zip)

**Comment by donalffons** [comment]
...and by the way. Here is a bit of a progress report (Play with left mouse click. Trackball view with left mouse / right mouse button):
https://s3.amazonaws.com/donalffons-interface/Armory/Robot%20Test%2023/html5/index.html
Unfortunately it crashes and freezes in the end for some reason.

Weird thing is that if I have lights in my scene, it does not properly execute the node tree and stops the animation halfway through.
https://s3.amazonaws.com/donalffons-interface/Armory/Robot%20Test%2023-lights/html5/index.html
...I might open another ticket because of this. The good thing is that this version does not crash in the end.

**Comment by luboslenco** [comment]
Applied a fix at https://github.com/armory3d/iron/commit/5f5b0812aca1781828ea9f671b0f383342cdd361. Was a problem of blend time finishing sooner that action itself.

**Comment by donalffons** [comment]
Confirmed :)
