### ISSUE TITLE
Bump node causes build failed

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#322]
When I added bump node(Shift A->Vector->Bump) to material nodes, I will have build error until I deleted the bump node. 
I think this is a critical nodes since we can invert the normal maps if needed. 

![bump node error](https://user-images.githubusercontent.com/4146156/32428705-2011fc00-c302-11e7-85e1-600175093305.jpg)

**Comment by Simonrazer** [comment]
Can cofirm that

**Comment by luboslenco** [comment]
Fixed Bump node support, for proper output height socket needs Image Texture input for now. Added new example at https://github.com/armory3d/armory_examples/tree/master/material_bump.
![capture](https://user-images.githubusercontent.com/3685704/32490716-6f8954a6-c3b4-11e7-9bb3-f0964a6476ac.jpg)

For inverting normal maps, check here: https://github.com/armory3d/armory_examples/tree/master/material_normalmap.
![capture2](https://user-images.githubusercontent.com/3685704/32490721-7d0d4a7e-c3b4-11e7-9e7d-7f4f7ea4d0af.jpg)
