### ISSUE TITLE
Anisotropic filtering not working in viewport

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#323]
Not sure if im missing some settings. But it seems missing anisotropic filtering to me ? Will anisotropic filtering enabled even when the camera is set to "Viewport"

![anisotropic not working](https://user-images.githubusercontent.com/4146156/32432437-9f05d24c-c312-11e7-8fad-48881d388c00.jpg)

**Comment by luboslenco** [comment]
@takhimi is there anything of interest if you look into `Window - Toggle System Console`? Preferably after cleaning the project and hitting Build. Is the texture power of 2? Camera set to "Viewport" should be ok.

**Comment by takhimi** [comment]
@luboslenco There is no error in the console.

[Test2.zip](https://github.com/armory3d/armory/files/1445769/Test2.zip)

**Comment by takhimi** [comment]
@luboslenco Yup, I think something is wrong with anisotropic filtering. Maybe it is just running in anisotropic level 1 ? Bellow is the same file running with Texture filtering set to "linear"

![armory linear filtering](https://user-images.githubusercontent.com/4146156/32470421-be4d28a0-c392-11e7-8ff7-1845fe517699.jpg)

The ground texture looks cleaner. I would like to suggest that we have options to set the anisotropic filtering level ( from 1 to 16x) same like what we have with MSAA options. 

Not sure if is related to game engines technologies or something, but with some game engines we have options to enable anisotropic filtering(including AF level) and also option to turn on trilinear filtering  to clean up the texture further. We can use both at the same time.

**Comment by luboslenco** [comment]
Fix incoming https://github.com/Kode/Kore/pull/234.

**Comment by luboslenco** [comment]
@takhimi can you give it a spin in Krom window(F5) using the new v0.1 build?

**Comment by takhimi** [comment]
![armory 0 1 anisotropic filtering](https://user-images.githubusercontent.com/4146156/33380083-e94ccb5e-d554-11e7-8849-e50851357d93.jpg)

This is solved on krom but does not work on the viewport.

The movement of the fps is different right now, the fps hand is lagging a bit. Is this on purpose?

**Comment by luboslenco** [comment]
In my case the hands & gun were not moving vertically at all, pushed a [fix](https://github.com/armory3d/armory_examples/commit/1be4984da1290f5842c68342b02621bab033d7ce) for that. I am not sure if it's the same issue you experienced?

**Comment by takhimi** [comment]
Yes. I guess that was it!. Any chance that you can make the player rotation without dragging the mouse soon?

**Comment by luboslenco** [comment]
Yes, should be there by the next week. :)

**Comment by takhimi** [comment]
Awesome! Just to let you know that i really like your engine. I rarely open unity or ue4 anymore. Keep up the good work.

**Comment by luboslenco** [comment]
Aniso should work in viewport as well now.
