### ISSUE TITLE
[Feature Request] Integrate Kha2D into armory by default.

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#324]
@luboslenco This is just a suggestions and request. Since Armory is already going to be an awesome 3D game engine, why not integrate Kha2D into it by default to make it easier to develop 2D games also with armory. That way some of us would not need to rely to Unity or other game engine to develop 2d games and just focus on Kha and Armory.

You would also increase your potential audience and supports from 2d game developer and not just 3d game developer. But I think you need to implement level editor like tiled also.

Btw I'm having fun with kha and armory, I'm just hoping that I can ditched my other game engines in my pc someday..

**Comment by luboslenco** [comment]
Anything specific you need from Kha2D? You can create a `/Libraries` directory in your project root(where .blend resides) and clone [Kha2D](https://github.com/Kha-Samples/Kha2D) into it. Now you can access it from scripts like in usual Kha project.

For tile map editing check out [sprytile](https://chemikhazi.itch.io/sprytile) if you haven't already, amazing tool!

PS: Super happy you have fun with kha & armory!

**Comment by takhimi** [comment]
@luboslenco I will probably need to start creating a mini 2d game first to see what is missing. I've been testing and playing armory too much.  :)

Any chance you will update all the kha ads , iap, and google and apple gamecenter plugin and etc to be use with armory ? I noticed that you already have them ? But it has not been updated for more than 1 year. Would probably make Armory more valuable with an official monetization options.

**Comment by luboslenco** [comment]
Mobile services - yup, will get to that.:)
(tag https://github.com/armory3d/armory/issues/304)
