### ISSUE TITLE
Add rotation constraints and position constraints to tilesheets

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#325]
Based on the https://github.com/armory3d/armory_examples/tree/master/tilesheet_walkcycle 

I would like to request option to add "rotation constraints" and "position constraints" to the tilesheet based on axis like unity. So that if we can apply rigidbody to the tilesheet and make the duck to jump by impulse or something. Without the rotation constraints, the duck may land on his head or on his side if he falls down and he might upside down.

The position constraints would be important for example there is an explosion and the duck tilesheet might change position on the y axis. I think this would be important if we want to do a 2.5d/2d platformer or even sidescroller games?.

![inspector-rigidbody](https://user-images.githubusercontent.com/4146156/32473421-6a3d8556-c3a2-11e7-8f54-35299ca215be.png)

http://forums.armory3d.org/t/play-and-pause-tilesheet/495/4

**Comment by luboslenco** [comment]
Check here: https://github.com/armory3d/armory/issues/292. You should be able to set `Linear/Angular factor` to 0 in `Physics - Armory Props` to freeze it.
