### ISSUE TITLE
Rigidbody constraint type "Generic" causes error

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#326]
I just found out about rigidbody constraint. But when I enabled it, armory will have error when I clicked play in viewport or when I try to play. I use the type "Generic" to disable rotation or axis. 

![armory constraint generic error](https://user-images.githubusercontent.com/4146156/32480339-2ac3bd88-c3c9-11e7-80d5-a11be93c0826.jpg)

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/533.
