### ISSUE TITLE
Armory does not respect Object Constraint and Transform Locks options

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#327]
I tried with regular blender and the cube wont move or fall down which is correct. However with Armory , the cube will still fall down and landed on the ground

![armory does not respect object constraints and transforms locks](https://user-images.githubusercontent.com/4146156/32486196-de16ffe6-c3e0-11e7-9824-ce339953e6ab.jpg)
.

[constraint.zip](https://github.com/armory3d/armory/files/1449364/constraint.zip)

**Comment by luboslenco** [comment]
Constraints are not supported yet. :/ Merging with issue https://github.com/armory3d/armory/issues/62, thanks for test file!
