### ISSUE TITLE
Play on viewport should start the current active scene.

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#329]
I played the armory bowling game example and noticed some odd behavior. Sometimes it will start at Menu scene, and sometimes it will start at game scene when I clicked on the play on viewport button and it does not respect the current active scene. This bug is kinda strange since it is intermittent. 

![armory play on viewport scene](https://user-images.githubusercontent.com/4146156/32523053-bff844b0-c454-11e7-8af8-815c9012bc2b.jpg)

I think this bug can be reproduce if you : -

1)Goto menu scene
2)Unselect the camera at the menu scene (A)
3)Goto game scene 
4)Unselect all (double A)
5)Goto menu scene
6)Click on "Play on viewport"

For me it will play at Game scene and not Menu scene.

**Comment by luboslenco** [comment]
Nice report, fixed now! https://github.com/armory3d/armory/commit/7923f1a68a4c7f52d99f4f2f60be13ec2a0d9251

**Comment by takhimi** [comment]
@luboslenco tried the latest versions from github. Seems like the cache does not clear at all this time. I need to click "Build" button before clicking "Play on viewport" or else it will always retain the last active scene.

I already clean the cache and project before testing. Last loaded active scene will always remains untill I click build button (or until I clicked clean project and cache manually)

**Comment by luboslenco** [comment]
That is weird, seems to work ok here for some reason. Will test on another machine. I also pushed another fix for shader cache, perhaps it's related and helps.

**Comment by takhimi** [comment]
@luboslenco Okay now it works. 
1)Delete and reinstall armory sdk and example
2)Update to current sdk
3)It now follows active screen.

Maybe you should remove the "Play Active Scene" checkbox and always play the current active scene. But on the Armory Exporter group, you add a list of scenes as an option to make startup scene when published ? Just a suggestions.

**Comment by luboslenco** [comment]
That sounds good, will do that. Continuing at https://github.com/armory3d/armory/issues/330.
