### ISSUE TITLE
Explicitly specify the startup scene when published

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#330]
@luboslenco , I think it would be great if we can explicitly specify the startup scene when we published our games, it may avoid any confusing and frustrating later on to see that the published game actually start the wrong scene.

![armory published startup scene](https://user-images.githubusercontent.com/4146156/32523739-a3554454-c457-11e7-91b3-fd48fd566faa.jpg)

**Comment by luboslenco** [comment]
Yup that is a very good idea. In the meantime it is possible to uncheck `Armory Project - Play Active Scene` and specify one manually, but it's a global setting for both play and publish..

**Comment by luboslenco** [comment]
Start-up scene is now selected in Armory Exporter panel (https://github.com/armory3d/armory/commit/c2606569ea712d348fb3c6585b3482c5149df6d6).
