### ISSUE TITLE
Add notifyOnCollisionEnter and notifyOnTriggerEnter

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#331]
@luboslenco  I noticed that Armory is missing these notifications. Is it possible to to add them ? 

I noticed that we have logic node for GetFirstContact and VolumeTriggerNode but is it possible to have something like notifyOnTrigger or notifyOnCollision and we can get the object that it collides or Triggered from that notifications ?

Can you give a script example for both cases, collisions and triggered?

I tried to do this

`package arm;
import armory.trait.physics.RigidBody;

class CubeTest1 extends armory.Trait {

	var rbs:Array<armory.trait.physics.bullet.RigidBody> = [];
	var contactName:String;
	var contactObject:iron.object.Object;
	var physics : armory.trait.physics.PhysicsWorld;

	public function new() {
		super();

		 notifyOnInit(function() {
			  physics = armory.trait.physics.PhysicsWorld.active;
			
		 });

		 notifyOnUpdate(function() {
			 	rbs=[];
			 	
				rbs = physics.getContacts(object.getTrait(RigidBody));
				if(rbs!=null){
						contactName=rbs[0].object.name;
					
						if (contactObject == null)
						{
							contactObject = iron.Scene.active.getChild(contactName);	//suppose to be "Plane" but it return some weird name text like "U n i f o r m  e n v m a p S t r e P l a n"
						//	contactObject = iron.Scene.active.getChild("Plane");
			  				trace(contactName); //suppose to be "Plane" but it return some weird name text like "U n i f o r m  e n v m a p S t r e P l a n"
							
						} 

						if(contactName=="Plane")
						{
							contactObject.remove();	
						}
						
				}
			
		 });

		// notifyOnRemove(function() {
		// });
	}
}
`

Is this the proper way ?

**Comment by takhimi** [comment]
From the code, if i tried to get the object based on contactObject.name. But I failed to removed it. It does not return "Plane"

[ContactTest1.zip](https://github.com/armory3d/armory/files/1452653/ContactTest1.zip)

**Comment by takhimi** [comment]
So if the object collides with any object with the name "Plane" the plane or object will be destroyed.

**Comment by luboslenco** [comment]
It's a bit easier now, for collision:

```hx
notifyOnInit(function() {
	var body = object.getTrait(RigidBody);
	body.notifyOnContact(function(body2:RigidBody) {
		var o = body2.object;
		if (o.name == "Plane") o.remove();
	});
});
```

For volume trigger (no physics):
```hx
notifyOnUpdate(function() {
	var plane = Scene.active.getChild("Plane");
	if (plane == null) return;
	var t1 = object.transform;
	var t2 = plane.transform;
	if (t1.overlap(t2)) plane.remove();
});
```
