### ISSUE TITLE
Armory Camera Orthographic problem 

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#332]
I tried to set the camera as orthographic, but somehow it only comes up with blackscreen and a part of white cube or something.

![armory camera orthographic problem](https://user-images.githubusercontent.com/4146156/32534773-06c685e0-c492-11e7-9618-a432a2e9e7d1.jpg)

On the left is render image and on the right is armory viewport.

I think camera orthographic is important for few types of games maybe like a 3d platformer, and few other type of games.

There is no error in system console.

**Comment by luboslenco** [comment]
Merging with https://github.com/armory3d/armory/issues/332. (Possible temporary workaround - modify fov of perspective camera.)

**Comment by takhimi** [comment]
@luboslenco Not sure if this is the same issue. I get black screen and not distorted like issue no 208.

**Comment by luboslenco** [comment]
It's only to keep things linked, so when fixing ortho cam it's easy to gather all related issues in one place. (This issue is still visible in https://github.com/armory3d/armory/issues/208.)
