### ISSUE TITLE
Strength not working for Bump and Normal Map node

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#333]
1)Latest github armory version
2)No error in system console.
3)Clear cache and project
4)I cant see the bump in armory viewport.

![armory bump node example not working](https://user-images.githubusercontent.com/4146156/32548392-72ab4fba-c4c0-11e7-81a9-c4dc935810bc.jpg)

**Comment by takhimi** [comment]
The new normal map invert example is working great. I hope you dont mind I'm reporting alot of things here.

**Comment by luboslenco** [comment]
Looks like shader compilation troubles, pushed a fix now which should help.

**Comment by takhimi** [comment]
@luboslenco it now works but the strength value does not work for bump node and normal maps node. It will stay the same, does not matter if I set the strength to 0 or really high for bump node and normal map node.

**Comment by Simonrazer** [comment]
For me there is now no difference between normal map plugged in and not(effect just not there). Latest update, all material modes tested.

**Comment by luboslenco** [comment]
What are you seeing in the normal map example? Solid cube?
https://github.com/armory3d/armory_examples/tree/master/material_normalmap

![32490721-7d0d4a7e-c3b4-11e7-9e7d-7f4f7ea4d0af](https://user-images.githubusercontent.com/3685704/32624635-14dda0b6-c58a-11e7-93bf-d18c9868ab39.jpg)

**Comment by Simonrazer** [comment]
Damn it always posting to quick, the example works totaly fine, but the bumpnode still doesnt work. Sorry for that

**Comment by luboslenco** [comment]
Strength should now work properly for `Bump` and `Normal Map` nodes. https://github.com/armory3d/armory/commit/d80a4fce5256eda4577ab47be6e8a5af7a49a896
