### ISSUE TITLE
Voxelgi + Play in Viewport broken in Blender 2.79

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#334]
The voxelgi teaspots demo has artifacts when play on viewport, but it does not have any problem when played on Armory player.

![armory voxelgi_teaspots artifacts when play on viewport](https://user-images.githubusercontent.com/4146156/32549269-c6852860-c4c3-11e7-9661-e290d023ee57.jpg)

**Comment by luboslenco** [comment]
To play in viewport, Blender 2.8 is needed(plus still experimental). Adding a new page to document this:
https://github.com/armory3d/armory_docs/blob/master/graphics/global_illumination.md

**Comment by luboslenco** [comment]
Warning will be also print to console now. (https://github.com/armory3d/armory/commit/9a3880e72cbcddccef4f90fe3e3b87277d6487b9)
