### ISSUE TITLE
Logic Nodes don't execute correctly in HTML5

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#335]
I'm having another issue with my assembly line scene. Although I already had it working fine, now it does not play the animation properly when I export to HTML 5. The execution seems to only follow the two routes marked in green, but it ignores the two routes marked in red. And also it quickly stops the execution somewhere at the location marked in purple.
![image](https://user-images.githubusercontent.com/33040347/32582810-ecfb02d0-c4f0-11e7-9934-12ba46dceeac.png)

In the Blender viewport, however, everything works fine. Maybe the issue is related to branching off into many paths?!

Link to HTML5 example: https://donalffons-interface.s3.amazonaws.com/Armory/Robot%20Test%2028/html5/index.html
Link to blend file: https://donalffons-interface.s3.amazonaws.com/Armory/Robot%20Test%2028/Issue.zip

Hope you can help, Lubos!

**Comment by donalffons** [comment]
Jfyi, I think the problem marked with the purple x's has been resolved with the commit armory3d/iron@6476d7b.
The rest of the problem still remains.

**Comment by luboslenco** [comment]
Was an issue with async object spawning, applied a fix at https://github.com/armory3d/iron/commit/5fd7868b0ccce803653f946532e0ba37b480fb17 now.

PS: That is a ridiculously cool scene!

**Comment by donalffons** [comment]
Great stuff :)
