### ISSUE TITLE
Get all childs in active scene

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#336]
Not sure if there is a functions for this in armory. But I would like to request or suggest that we have this function

armory.Scene.active.getAllChild()

It will return as Array:String. That way if we have Cube.001, Cube.002,Plane, Plane.002. After that we can iterate it and use something call StringTools.startswith(string,string) to do something if it is a Cube or Plane or etc and pass into the parameter  cube1 = armory.Scene.active.getChild("Cube.001");

This might be useful if we spawn object randomly or if we are not sure how the scene is constructed or designed by the game designer.

Another request is to have something like "string.contains" from C# in StringTools class. Instead of just "startwith" or "endwith", maybe having "contains" in StringTools would also be beneficial.

Thanks

**Comment by sh-dave** [comment]
```string.contains``` is called [string.indexOf](https://api.haxe.org/String.html#indexOf) in haxe, you don't even need StringTools for that.

**Comment by luboslenco** [comment]
Use `Scene.active.meshes` property to get all mesh objects. You can also access [lamps, cameras, etc.](https://github.com/armory3d/iron/blob/master/Sources/iron/Scene.hx#L42) this way if needed. Alternatively, it is possible to traverse `Scene.active.root.children` - this will have the same hierarchy like the scene in Blender outliner.

For each object you can then access the [name](https://github.com/armory3d/iron/blob/master/Sources/iron/object/Object.hx#L12) property.

Good idea for a new doc..

**Comment by takhimi** [comment]
@sh-dave  Thank you for that.
