### ISSUE TITLE
Material Movie result in black cube in browser

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#337]
1)Latest git
2)Tested with latest stable chrome and firefox
3)Clean and clear cache and project
4)Already pointed ffmpeg to binary to the binary file (D:\FFmpeg\bin\ffmpeg.exe) in the addon.
5)Noticed some error in system console

![armory material_movie black cube](https://user-images.githubusercontent.com/4146156/32637791-cf79f19c-c5f6-11e7-8f57-4b5a257a41fa.jpg)

![armory material_movie black cube 2](https://user-images.githubusercontent.com/4146156/32637793-d5a8ccc8-c5f6-11e7-9d17-4f2d803e6004.jpg)

**Comment by luboslenco** [comment]
Works nowadays!
