### ISSUE TITLE
Script & logic node to retrieve and set elements of canvas

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#338]
I've looked at the endless runner example to understand on how to update hud or canvas element like text score , lives and etc. Somehow I cant make it to work.

I get error cannot read property "GetElement" of null. Meaning that it cant find the canvas. I already tried attaching the UICanvas myCanvas to the Gems and camera but it still wont work.

Is it possible for you to put more examples on how to manipulate UI Canvas from script and also logic node ?

There are not many examples on how script and logic node can manipulate the canvas and the canvas elements

Example:-
1)How to change a text in canvas (for scores, lives and etc) and maybe retrieve the text back.
2)How to change an image by script or logic node (for changing the image source on runtime (mute and unmute image))
3)Can we move and tween the element position, height and width ?

Thanks

**Comment by luboslenco** [comment]
Phew, added an example at https://github.com/armory3d/armory_examples/tree/master/ui_canvas.
