### ISSUE TITLE
AmorUI Editor Issues and suggestions

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#339]
1)When I changed the canvas width and height , it does not changed immediately. I need to click save and close the UI editor and reopen it back to get the canvas size updated.

2)Please add panning to the editor (maybe using middle mouse button? Or having horizontal and vertical scrollbar.

3)I tried to edit and design elements with canvas size of 640x960 and it is really big. Can you add in zoom in and zoom out feature ?

4)More elements added. Panel, Tab, Combobox, List and etc.

5)Grid snapping and grid size changing.

6)Change opacity of an image

7)Change the button color and its text font.

8)Change the text font and color of Text element

9)Canvas background color. 

Thanks

**Comment by luboslenco** [comment]
Moving to https://github.com/armory3d/armorui/issues/1, tons more to do on the ui.. thanks for report!
