### ISSUE TITLE
Android build failed with an exception

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#340]
1)Using Android Studio 3.0
2)All sdk ,ndk ,cmake are installed and updated from the SDK manager
3)Latest git version
4)Select variant ReleaseArm7
5)key signing is done and setup
6)Test by creating new project in Android studio and build apk is success.

![armory android build failed](https://user-images.githubusercontent.com/4146156/32663476-0887fe30-c669-11e7-8855-da2fd41d2286.jpg)

**Comment by luboslenco** [comment]
Merging with linked issue at https://github.com/armory3d/armory/issues/348.
