### ISSUE TITLE
ammo.js Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#341]
This exception is thrown if I leave a browser build running for some time, seems random.. sometimes after a couple of minutes, sometimes after a quite long time like 30+ min.

Main.hx:28: Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 67108864, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

Something using more and more memory over time until that happens?

**Comment by luboslenco** [comment]
This looks like ammo.js / emscripten error. I don't suppose you are spawning some physics stuff as the time passes? I will double check the rigid body code, and also updating to webassembly version soon.

**Comment by guzzard** [comment]
Hi @luboslenco, not spawning anything during runtime. Have a couple of boxes and a character in the scene which all have rigid bodies. One thing that is running all the time is the character animations.

**Comment by luboslenco** [comment]
Merging into https://github.com/armory3d/armory/issues/835.
