### ISSUE TITLE
Weird bug: Armature Action does not play when light source is present?!

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#342]
This one is super weird. Follow the steps below with the attached blend file.

[Weird Bug.zip](https://github.com/armory3d/armory/files/1463985/Weird.Bug.zip)

To reproduce the bug:
- Open the blend file
- Hit 'play in viewport'
- The robot is not moving (there is also no error message)

To 'fix' the bug:
- Save the blend File as 'weird bug2.blend"
- Delete the point light
- Save the blend file and hit File/Revert (that seems to be necessary to reproduce)
- Hit 'play in viewport'
- The robot moves as it should

**Comment by luboslenco** [comment]
Ouch! Was an issue with culling, which prevented animation update. Fix in https://github.com/armory3d/iron/commit/6476d7be20cc21931430e55bb715f72a87850f9c.

**Comment by donalffons** [comment]
Halleluja! :)
That one gave me a headache. Thanks for taking care so quickly!
