### ISSUE TITLE
Multiple 'Spawn Object' nodes don't execute in HTML5

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#343]
There is a problem if multiple 'Spawn Object' nodes are executed in parallel, as in this example:
![image](https://user-images.githubusercontent.com/33040347/32694233-5a59ddc8-c73b-11e7-9df0-24a2e058478c.png)
If I run this in the blender viewport, I get the expected console output: "1, 2, 3".
However, if I run it as HTML5, I only get one number (seems more or less randomly) in my webbrowser's console.
It seems like this problem only affects 'Spawn Object' nodes.

[SpawnBug.zip](https://github.com/armory3d/armory/files/1464202/SpawnBug.zip)

(this is probably also closely related to [this issue](https://github.com/armory3d/armory/issues/335))

**Comment by luboslenco** [comment]
Looks good now.

<img width="528" alt="spawn" src="https://user-images.githubusercontent.com/3685704/33201848-802eb0d2-d0fa-11e7-91d7-4888d15b956b.png">

**Comment by donalffons** [comment]
Perfect!
