### ISSUE TITLE
'Remove Object' node does not work with 'Batch Meshes' project flag enabled

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#344]
The title says it all. The following node setup works fine by default. The cube spawns after 2 seconds (it does not spawn by default), then disappears after another 2 seconds.
![image](https://user-images.githubusercontent.com/33040347/32698414-d6a072ba-c7a5-11e7-917c-b0c554ba5a5c.png)

When I enable the 'batch meshes' flag, the cube does not disappear from the scene in Armory.

![image](https://user-images.githubusercontent.com/33040347/32698426-f481f970-c7a5-11e7-9643-8923c51388fe.png)

[BatchMeshesBug.zip](https://github.com/armory3d/armory/files/1464572/BatchMeshesBug.zip)

**Comment by luboslenco** [comment]
Fixed! https://github.com/armory3d/iron/commit/734ecf61e2ba658a34f0b2f628a5782231167baa

**Comment by donalffons** [comment]
Thank you, Sir!
