### ISSUE TITLE
Support linked group proxies

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#345]
It would be very helpful for bigger projects, if Blender proxies would be supported on linked groups. See the attached example. All 4 cubes are part of a group and have been linked using File/Link/.../Group. Then, in the main file with the group instance selected, I created a proxy (Ctrl + Alt + P) for one of the cubes and animated it.
The result in Blender:
![image](https://user-images.githubusercontent.com/33040347/32701179-23e1ff3c-c7d1-11e7-84ef-30c1f04a859c.png)

And in Armory:
![image](https://user-images.githubusercontent.com/33040347/32701186-4cfd2bbc-c7d1-11e7-9fb3-9ed64bada3b9.png)

[Linked Group Proxies.zip](https://github.com/armory3d/armory/files/1464889/Linked.Group.Proxies.zip)

**Comment by luboslenco** [comment]
Attached example should work now (after enabling `Spawn` on `Group_proxy` object).
