### ISSUE TITLE
Missing group for group instance disables Armory

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#346]
Again, this problem comes from a fairly complex scene, that I wanted to export with Armory.

The problem is caused when there is a  group instance, referencing a group that does not exist. In the example file, there is an empty "Absperrhahn", referencing a non-existing group named "Absperrhahn".
![image](https://user-images.githubusercontent.com/33040347/32703657-38016b92-c7f9-11e7-82e4-6745e79ede89.png)

When I run this scene in Armory, I get no error message. After compilation, the 3D view does not change to the 'Armory view'.
Obviously, this is a mistake in the scene. However, it would help a lot if Armory was more tolerant with this problem and just ignore the empty / group.

[MissingGroup.zip](https://github.com/armory3d/armory/files/1465140/MissingGroup.zip)

**Comment by luboslenco** [comment]
Hm appears to be ok now.

**Comment by donalffons** [comment]
Yes, it works fine now.
