### ISSUE TITLE
Error when linking a non-export object through group

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#347]
I defined a group 'Group' in 'GroupDefinition.blend'. Part of this group is one object, that should not be exported to Armory (property is unchecked in object settings).

![image](https://user-images.githubusercontent.com/33040347/32704001-d2dc0596-c7fe-11e7-98b6-3af681e60c62.png)

If I link this group and make a group instance my in 'Main.blend' file and hit play, I get the following error message
![image](https://user-images.githubusercontent.com/33040347/32704024-136a7138-c7ff-11e7-9e81-bc9530881734.png)

[Linked Non-Export Object.zip](https://github.com/armory3d/armory/files/1465162/Linked.Non-Export.Object.zip)

**Comment by luboslenco** [comment]
These reports are gold. Fixed in https://github.com/armory3d/armory/commit/961283dbb2fc59b635dc16be1d5ddde698240e99.

**Comment by donalffons** [comment]
![image](https://user-images.githubusercontent.com/33040347/33225329-92d2c450-d175-11e7-9e35-f089e8b8f2c6.png)

This happens when I just open the example from the original post and hit 'Play in Viewport'.

**Comment by luboslenco** [comment]
How did you update? Both armory and iron repositories up to date?

If you are using built-in updater install the latest add-on from https://github.com/armory3d/armory/blob/master/blender/addon/armory.py, it should fix some issues with it.

**Comment by donalffons** [comment]
I just deleted Armory from my hard drive. Then I copied a freshly downloaded version. Went to File / User preferences / Addons / Armory and hit Update SDK. Then I restarted Armory, opened the main.blend and hit 'play in viewport'. Same error. I also tried manually downloading armory.py and replacing it in the folder. No change.

Armory and iron seem to be up-to-date
![image](https://user-images.githubusercontent.com/33040347/33229829-38fb4238-d1d7-11e7-9d9f-0ee367fe29a0.png)
![image](https://user-images.githubusercontent.com/33040347/33229832-53c971d4-d1d7-11e7-8529-2187dbdc109a.png)

**Comment by luboslenco** [comment]
Uh, that should be all good. Do you get the same error for other scenes? No luck after `Armory Project - Clean`? The missing function `shadowTestCascade` should be located at [armory/Shaders/std/shadows.glsl]( https://github.com/armory3d/armory/blob/master/Shaders/std/shadows.glsl#L109).

**Comment by donalffons** [comment]
Ah, damn. Simply hitting clean did the job! I must have had some old files flying around in that folder.

Thanks for solving it :). Looking forward to the release :)).

**Comment by luboslenco** [comment]
Dang, sorry for the trouble. I will make sure Armory does a full rebuild after using the updater, to prevent old cache.
