### ISSUE TITLE
Having an image file named "return.png" in canvas will make armory failed to build C++

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#348]
1)Latest git (return to stable and update to latest sdk)
2)Open armory and save it new file.
3)Click on camera and create new UICanvas and edit it.
4)Add or drag image named "return.png" into Assets tab in ArmorUI editor.
5)Click "Image" to create image on the canvas with image of "return.png"
6)Save canvas
7)Change runtime to C++
8)Click play
9)Error in system console
10)Loses a couple of hair

Solution
11)Delete that image in canvas 
12)Delete that image filename at the "Assets" tab
13)Rename the png to "return2.png" and the problem solved. Now I can use it in the UI editor without error in C++ runtime.

[SpaceInvaderTest.zip](https://github.com/armory3d/armory/files/1466143/SpaceInvaderTest.zip)

![return png causes build error1](https://user-images.githubusercontent.com/4146156/32717213-c5e68d76-c893-11e7-921c-b741bfb2b01d.jpg)

![return png canvas](https://user-images.githubusercontent.com/4146156/32717225-ceaa77ec-c893-11e7-9a08-e03449bc9290.jpg)

I hope you fix this bug. I really tought the project has been corrupted and redo the same thing like 3 times. :)

**Comment by takhimi** [comment]
@luboslenco 

The dangerous thing about this bug is, I can still generate Android project and open it with android studio.

This bug here https://github.com/armory3d/armory/issues/340 is actually related to this return.png bug.

**Comment by luboslenco** [comment]
Dang. I hope there is plenty of hair left up there! The issue here is how Kha processes assets, which causes trouble when clashing with language keywords. Nonetheless Armory will now warn when this happens.

`Armory Warning: File "Assets/return.png" contains reserved keyword, this will break C++ builds!`
