### ISSUE TITLE
DebugDraw.line() lifetime

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#349]
Would be really nice to have a lifetime variable in seconds on the DebugDraw.line() function, where 0.0 would mean only show during that frame, 1.0 one second etc.

![image](https://user-images.githubusercontent.com/9007314/32730498-8d8a1756-c887-11e7-8e68-afc8f7f96751.png)

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/350.
