### ISSUE TITLE
Armory Updater error

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#351]
I get this error when I try to update:
```
error: Your local changes to the following files would be overwritten by merge:
        blender/arm/make_renderer.py
        blender/arm/utils.py
        blender/arm/write_data.py
Please commit your changes or stash them before you merge.
Aborting
Updating 9a640e1..402a710
Already up-to-date.
```
I didnt touch any of these files, I have no idea of coding. Did it update and just didnt do anything to these files? Do not know, restoring SDK and updating afterwards fixed it. That shouldnt happen once released, so I am reporting anyway, hope it helps.

**Comment by luboslenco** [comment]
Testing a fix, you can grab the latest addon file at https://github.com/armory3d/armory/blob/master/blender/addon/armory.py. It should always fetch a fresh clone now.

**Comment by luboslenco** [comment]
v0.1 now comes with updated updater(duh) out of the box.
