### ISSUE TITLE
material_sss failed to run with latest build

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#352]
Not sure if you already known this error. But I'm going to report it here just in case.

![armory material_sss example failed to run](https://user-images.githubusercontent.com/4146156/32890736-fb88e900-cb0a-11e7-9947-2dbb3c621552.jpg)

**Comment by luboslenco** [comment]
Back to normal! Armory now (finally) supports cascaded shadow maps, had to adjust some things.
