### ISSUE TITLE
Handle logic node null output

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#353]
When there is a Variable which is "null", and plug it into basicly anything appart from a "Is Not None/True/None..."-node , the F5 thing freezes on the first frame. This may be not a bug, but I cant think of any way to get arround this when using "Get Contacts" and "Array Get"-0. "Get first Contact" has that problem too, I think.
 I can imagine it not being possible to change a Variable which is "null", but there should be a way to use another variable to feed into other nodes as long as the Variable you actualy need to be fed in those nodes is "null", to get arround that problem. 
Maybe a "Is Null Switch" node, in which you plug in the variable you need once it is nomore "null" and another one which is being put out (on the right side) as long as the variable is "null".
[null.zip](https://github.com/armory3d/armory/files/1479671/null.zip)

**Comment by Simonrazer** [comment]
Or maybe make the nodes which output a "null" variale just nolonger do that, maybe make it to a integer 0 or something. Others probably know that better than me, just some ideas

**Comment by luboslenco** [comment]
Logic nodes should be null safe now. https://github.com/armory3d/armory/commit/e05ca352dda8513df510acf85ac248465209f8d5
