### ISSUE TITLE
Received error "Cannot enlarge memory arrays"

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#354]
Hi @luboslenco 

I have created a small terrain for testing. When I have added subsurface modifier to get smoother terrain, it will output this error in viewport. 

![armory cannot enlarge memory array](https://user-images.githubusercontent.com/4146156/32936691-45857bcc-cbb0-11e7-943b-e4b710f98bdd.jpg)

I have added rigidbody (mesh) type to the terrain plane so that my character can move and not fall down. I dont think the polygon on the terrain mesh is too much for such small size. 

[TerrainTest4.zip](https://github.com/armory3d/armory/files/1481517/TerrainTest4.zip)

If I remove the subsurf modifier, it will run. Do you plan to improve armory terrain workflow ?

**Comment by luboslenco** [comment]
Yes, plan to improve that, at this time Armory has no real terrain support yet.

The amount of vertices seems to be too much for physics engine to handle. In the meantime potential fix is to keep separate mesh for collision(like in scene5 tanks example).

**Comment by luboslenco** [comment]
Separate mesh for collision still needed. Will be fixed with the new terrain system.
