### ISSUE TITLE
Bowling example error with latest armory git

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#355]
Latest git version. Tried to restore stable, and update again with latest. Still the same with latest git.
The example will work with stable sdk. Not sure if you already known this bug, but I will report this bug just in case.

![armory latest git bowling example does not work](https://user-images.githubusercontent.com/4146156/33009144-d2f6434e-ce10-11e7-8171-adee43465a13.jpg)

**Comment by luboslenco** [comment]
Should be all good now. 🌞 (https://github.com/armory3d/armory/commit/2110c42755d987b87bbaea9775359d6ac5403787)
