### ISSUE TITLE
Freezing when object removed

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#357]
When an object(1) is removed which is colliding with another object (2) and 2 is using the "get contacts" node and does something with its output, for ex. prints it, and 1 is removed, the game freezes. 
[contactfreez.zip](https://github.com/armory3d/armory/files/1488664/contactfreez.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/c916d4bae855d9f7477291cc1d01bed22ed787cf.
