### ISSUE TITLE
Krom player fullscreen does not centered to the monitor

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#359]
This happens on stable and latest git.

1)Open any example or project
2)Select Krom runtime in the Armory Player properties.
3)In Armory Project properties, choose fullscreen
4)Play in Armory Player
5)The game or project is played but not centered correctly to the screen

![armory krom player fullscreen offset bug](https://user-images.githubusercontent.com/4146156/33052656-e164f93a-ceaa-11e7-9a30-457ba80e07b2.jpg)

*This is running on dual monitor setup (Extended monitor configuration but not surround)
**The project will centered correctly when switch to C++ runtime.

**Comment by luboslenco** [comment]
Fixed in upcoming build. (https://github.com/Kode/Krom/pull/59)

**Comment by luboslenco** [comment]
Fixed in v0.1!
