### ISSUE TITLE
Shading artifacts in Preview 2

### ISSUE THREAD

**Issue by arturjpv** [armory3d/armory#36]
Preview 1 was creating perfect smooth shading surfaces. Preview 2 is creating ripples when shading a smooth surface.

Although the effect seems subtle, when animating the object or navigating through the scene, the effect is strong enough to attract the eye continuously.

See attached image for comparison.

![armoryrenderdiff](https://cloud.githubusercontent.com/assets/1221735/20240344/48487214-a916-11e6-9f86-f1e3d90bd364.png)

System: macOS Sierra, Intel HD Graphics 6000
Blender: 2.78a (not using embedded blender inside the sdk)
Armory: p1 and p2

**Comment by luboslenco** [comment]
Hm, I think the cause may be that I reduced default *Shadows Bias* value in lamp data properties. When the value is too low, shadow acne can appear(potentially that ripples). When the value is too high, shadows are less accurate.

Have to get rid of that value as soon as possible..

<img width="326" alt="screen shot 2016-11-12 at 22 31 12" src="https://cloud.githubusercontent.com/assets/3685704/20240985/ce50413c-a927-11e6-949b-d89836adfc21.png">

**Comment by arturjpv** [comment]
Yes, you are right. Is due to the shadow bias value. Raising the shadow bias fixes the issue.

Shadow bias fights are always unexpected :-)

**Comment by arturjpv** [comment]
Closing issue
