### ISSUE TITLE
Crash on object spawn

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#360]
The F5 thing crashes when you spawn an object from "Array get", here the .blend.
[spawnbug.zip](https://github.com/armory3d/armory/files/1496032/spawnbug.zip)

**Comment by luboslenco** [comment]
Seems to be good now. (https://github.com/armory3d/armory/commit/7f6975bda1a274a256885762d88bd44e37a47507, https://github.com/armory3d/armory/commit/afba2f1853eb34b1cf7e33af91a91f1b99840cce)
