### ISSUE TITLE
Vertex Colours sometimes get averaged across mesh

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#361]
For some reason when trying to paint solid transitions between faces Armory tries to average the colour across vertices. This seems to an issue when adding more vertices to and object.

In the Shadeless example this also happens. Its fine when you have a default cube for example, but add a loop cut and shade a face a different colour, it just doesn't play well.

Expected:
![image](https://user-images.githubusercontent.com/5720489/33177356-42233e3e-d05a-11e7-86df-59d0025fbd73.png)
Result:
![image](https://user-images.githubusercontent.com/5720489/33177370-4e7bc886-d05a-11e7-94d8-87686a40dd07.png)

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Should be now fixed in https://github.com/armory3d/armory/commit/4fba94f8a264c2e3c682d3928c469f4c1cbed315, thanks for reporting!

**Comment by Defaultsound** [comment]
So just did a quick test, seems its fixed for some objects, but not all

Planes seem to have an issue, maybe its too thin?

![image](https://user-images.githubusercontent.com/5720489/33180929-4db862fe-d066-11e7-8c84-82f40275cbaf.png)

**Comment by luboslenco** [comment]
Weird, can you please share the blend file with me? Will dig into it further.

**Comment by Defaultsound** [comment]
Sure,

[shadeless.zip](https://github.com/armory3d/armory/files/1499738/shadeless.zip)

**Comment by luboslenco** [comment]
Seems to be an old mesh cache generated before the fix, can you try cleaning the project?

**Comment by Defaultsound** [comment]
![image](https://user-images.githubusercontent.com/5720489/33182001-1cb587dc-d06a-11e7-9164-97364fe8961c.png)

You were correct. I had to delete the entire engine though, cleaning project didn't seem to do enough. Thanks :+1:

**Comment by luboslenco** [comment]
I have added a mechanism to auto-recache on armory update, so hopefully it will not pop up again.
