### ISSUE TITLE
On Volume Trigger doesn't take scale into account

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#363]
So if you are to scale a trigger volume at run-time, the new scale doesn't add to the volume trigger. It still references the original scale of the mesh.

![overlap1](https://user-images.githubusercontent.com/5720489/33209795-86915aaa-d10f-11e7-9c93-fbc93598daed.gif)

![overlap2](https://user-images.githubusercontent.com/5720489/33209796-8ab5286e-d10f-11e7-838f-823a67f7073e.gif)

Not sure if this could be fixed.

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
This should be now resolved in https://github.com/armory3d/iron/commit/fadb6fe4c3e0f13ead708a56f4d7c39f63edeb01 and https://github.com/armory3d/armory/commit/bd4a954b26bd1e72773e221e166cff73e31638d6.

**Comment by Defaultsound** [comment]
All good thanks :) 

![overlap3](https://user-images.githubusercontent.com/5720489/33258768-909a107e-d352-11e7-9d84-9dc09a6a686f.gif)

**Comment by luboslenco** [comment]
Yay that looks cool!

**Comment by Momowitch** [comment]
Hello,
it doesn't works again.

**Comment by QuantumCoderQC** [comment]
> Hello,
> it doesn't works again.

Hello @Momowitch ,

It seems to be still working even after scaling. I used a simple node setup and here is the result when scaling:

![VolumeTrigger](https://user-images.githubusercontent.com/55564981/76143571-cc690c80-6078-11ea-9b9d-f2a59b1c1383.gif)


Note: If you are using code to do the scaling, then `syncTransform()` must be called on the scaled RigidBody

**Comment by Momowitch** [comment]
[sample.zip](https://github.com/armory3d/armory/files/4301822/sample.zip)
This is sample. You see what i mean.

**Comment by QuantumCoderQC** [comment]
@Momowitch 

I do not understand what you are trying to achieve here. maybe you could explain a bit.

**Comment by Momowitch** [comment]
I want to select objects in the scene like in strategy games.
