### ISSUE TITLE
Transform locks

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#364]
As the title says, transform locks for Rigidbodys would be handy. Or the that it works to get the location via Logic nodes, and set for ex. Z to 0 (via get transform separate transform separate vector) , but currently such a setup doesn't change the ways the object moves,.

**Comment by luboslenco** [comment]
Will do. For rigid bodies, could you achieve what you are after by setting `Properties - Physics - Armory Props - Linear Factor - Z` to `0`? That should prevent the movement on Z axis. (Related: https://github.com/armory3d/armory/issues/292)

**Comment by Simonrazer** [comment]
Oh yes that works I did not see those values somehow.

**Comment by luboslenco** [comment]
Transform locks are now also taken into account. https://github.com/armory3d/armory/commit/262813cedffe0ab6cc49b4d0ca6e35ea2e6cc8b9
