### ISSUE TITLE
Crash when speaker in scene

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#367]
The scene crashes on the first frame (or earlier) if there is a Speaker with an Audio-clip selected in the scene, and sound quality is not set to 1. If the speaker has no sound selected, everything is fine.

**Comment by Simonrazer** [comment]
Also it crashes always with the "Jethit" sound while it works (under the above conditions) with the "firelaser" sound. https://drive.google.com/drive/u/0/folders/0B34rrtUThORyTVkzZ3RRUDNVVWM

**Comment by luboslenco** [comment]
Sound quality < 1 (converts to ogg) fix coming in next build. Related https://github.com/armory3d/armory/issues/308 and https://github.com/Kode/khamake/pull/123.

**Comment by luboslenco** [comment]
Krom should be ok, viewport to go: https://github.com/armory3d/armory/issues/253.
