### ISSUE TITLE
Nodes not doing what they should

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#368]
In this .blend all the cubes should remove themselves when "k" is pressed. but some of them don't. Also the lighting is broken but don't mind that.
[nodesproblem.zip](https://github.com/armory3d/armory/files/1503732/nodesproblem.zip)

**Comment by luboslenco** [comment]
Fix in https://github.com/armory3d/iron/commit/a209b9480f917f5a137de170e2e2c1fbe4078381.
