### ISSUE TITLE
Timescale speed manipulation in armory (pause /resume) 

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#369]
I would like to request timescale manipulation in armory. If it is already there, could you please add an example on this ?

Also it would be great if I can make certain objects not affected with timescale changes. For example in Unity I can make certain object not effected when I set the timescale speed to 0. So I can use that objects (pause dialogs) to still play animations and response when user click resume button.

**Comment by luboslenco** [comment]
There is a way to achieve this through scripts now using `Time.scale = 0.5;`. Per-object control or logic nodes still to do.

(A 'low level' logic node way to set the `Time.scale` property manually: )
<img width="600" alt="scl" src="https://user-images.githubusercontent.com/3685704/33262806-dd1b6410-d367-11e7-842f-ae2f845ca33d.png">

**Comment by takhimi** [comment]
Wow!. Didnt know that. Thanks.

**Comment by luboslenco** [comment]
Added a proper `Set Time Scale` logic node now.
