### ISSUE TITLE
Uploading HTML5 build to Itch.io

### ISSUE THREAD

**Issue by Defaultsound** [armory3d/armory#370]
Hi,

Just wanted to test and see if I could upload a HTML5 project to Itch.io.

Almost got it to work, however, it seems some files are not being loaded, not sure if its not finding the correct path, or if this is an issue with Itch.

![image](https://user-images.githubusercontent.com/5720489/33263241-f93ba242-d360-11e7-87fd-acf089021041.png)

I've tried uploading a .zip of the html5 and html5-resources folders together. Maybe I am missing some extra folders?

**Comment by luboslenco** [comment]
Investigating. `html5` folder should be all that is needed. Is this using `Publish` button in the Armory Exporter?
<img width="239" alt="publish" src="https://user-images.githubusercontent.com/3685704/33263414-19e26162-d36a-11e7-959d-92f3bc4b1a89.png">

**Comment by Defaultsound** [comment]
Ah, that's what I didn't do. having a bit more luck, however its stuck loading: 

![image](https://user-images.githubusercontent.com/5720489/33263699-ac137362-d362-11e7-87b2-cba9f06d71f0.png)

**Comment by luboslenco** [comment]
Dang, was an issue in Armory not setting the render path properly. Pushed a fix now.

**Comment by Defaultsound** [comment]
Sucess! https://defaultsound.itch.io/cubeman-bombs-away?password=armory

**Comment by luboslenco** [comment]
Super cool. I will be around for more bug fixing!
