### ISSUE TITLE
Latest navmesh examples is not working with latest armory git, not responding error.

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#371]
1)Tried to restored stable, restart armory, update armory and then restart and the result is the same.
2)Open latest navmesh example from git (fresh copy)
3)I have "not responding" on armory window and it will froze when I run it in viewport and try to click on the plane to make the robot move to that location

Win10 64bit
8gb ram
gtx970

**Comment by luboslenco** [comment]
It's back on using https://github.com/armory3d/iron/commit/824965ff8cbf905d815f763e7cda5e956c014741, thanks for continuous testing. Doing some more examples updating today, will fix the animations..
