### ISSUE TITLE
Integrate Newton Dynamics physics into Armory

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#375]
Not sure on the performance compared to bullet or physx but might be useful for someone that rely on physics accuracy behavior for his or her game/applications or apps.

The developer of newton dynamics claimed that newton is better than physx. So if you are interested @luboslenco 

https://www.youtube.com/watch?v=OVN3jB-MrT0

https://www.youtube.com/watch?v=ejdbYssqaL4

http://newtondynamics.com/forum/newton.php

**Comment by luboslenco** [comment]
Definitely interested but keeping focus on the bullet for now. Nonetheless this can now be handled as a standalone module if anyone is up for some fun, and I have added an example on minimal physics engine implementation at https://github.com/armory3d/oimo_module.
