### ISSUE TITLE
Console message characters separated by spaces and half-trimmed (windows 10)

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#377]
Console message characters separated by spaces and half-trimmed (windows 10):

(1) Tried to display a custom message / system generated message in the console;
(2) Message characters were separated by space and half-trimmed.

Platform: Windows 10
![console_message_characters_separated_by_space](https://user-images.githubusercontent.com/17811339/33314087-85681f46-d467-11e7-9c72-8ecd97f98094.JPG)
Test blend file attached here:
[Console_Message_Characters_Separated_By_Space.zip](https://github.com/armory3d/armory/files/1509366/Console_Message_Characters_Separated_By_Space.zip)

/Milo

**Comment by MLHX** [comment]
Hi @luboslenco 
I have done some more test, and found that this problem only happened when playing in view port. When using F5 to play in Krom, actually the messages could be displayed fine:

![capture_01](https://user-images.githubusercontent.com/17811339/33519341-c63b3bb8-d7df-11e7-9a50-23a6c81d08db.JPG)
![capture_02](https://user-images.githubusercontent.com/17811339/33519342-d221c15e-d7df-11e7-8703-631dfc9e37ee.JPG)
![capture_03](https://user-images.githubusercontent.com/17811339/33519348-e2df324c-d7df-11e7-8e54-18f3344b211d.JPG)
![capture_04](https://user-images.githubusercontent.com/17811339/33519349-e62d69d2-d7df-11e7-92c9-5f306bed44d4.JPG)

I think there is something wrong when the traced message passed to blender's console.
Hope this will help.
/Milo

**Comment by MiloHX** [comment]
Hello @ubaldy,
Here is the spec of my computer:
**Windows 10 Pro
NVIDIA GTX 980
i7-6700k**

And Here is the test blend file I used (press P to test):
[Console_Output.zip](https://github.com/armory3d/armory/files/1913519/Console_Output.zip)
![capture01](https://user-images.githubusercontent.com/17811339/38784986-5fbc7538-414c-11e8-9cf9-4282afb91be5.JPG)
![capture02](https://user-images.githubusercontent.com/17811339/38784987-5fee1aac-414c-11e8-8f7b-e7ef155ac2df.JPG)

**Comment by luboslenco** [comment]
Should be now fixed when playing in viewport using `Armory_04b_win64_b28`.
