### ISSUE TITLE
Request ragdoll examples

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#379]
I would like to request ragdoll examples. Particularly, an example on when we shoot the enemy and the enemy health is below 0, the ragdoll will be activated and the npc or enemy will fall down. Please show on how the ragdoll is setup and how to start or activate the ragdoll effect when needed.

**Comment by luboslenco** [comment]
Basic ragdoll example has been added at https://github.com/armory3d/armory_examples/tree/master/physics_ragdoll.
