### ISSUE TITLE
Issues on Linux

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#38]
This video shows some of Armory issues on Linux:

https://youtu.be/5DliremqAE8

Armory 3D issues on Linux 1
Unfourtunately, the voice didn't record.

As you can see, most of them are at the world tab features.
I hope this helps and that they can be soon fixed:)

Some aspects to mention:

- PCSS looks slightly weird.
- The reflections ain't enabled by default(should be).
- Effects(except for clouds) don't seem to work. Clouds work well, maybe could be a bit more performance-friendly, though.
- VGI and volumetric fog makes the Armory not start at all.
- In the editor some of inputs don't accept inputted text.
- Game will crash when no camera in scene.

**Comment by luboslenco** [comment]
Critical stuff like 'Game will crash when no camera in scene' is now fixed. Please feel free to open more issues with specific problems.
