### ISSUE TITLE
animation_sword example does not work. The character is invisible.

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#382]
Latest git from armory and armory_examples. I cant see the character in krom and viewport.

**Comment by luboslenco** [comment]
Found the culprit, object and bone were using the same name 'body', which confused the exporter. I have updated the example and will also properly fix the exporter so bone names do not conflict with object names. :)

**Comment by luboslenco** [comment]
Resolved in https://github.com/armory3d/armory/commit/65e930683bd18c0d7f77489bdd5a78a894c2703b.
