### ISSUE TITLE
Particle Info node's Age doesn't work as expected/shown

### ISSUE THREAD

**Issue by Gerkinfeltser** [armory3d/armory#383]
I'm unable to get the Particle Info node to work as it does in the [v0.1 video](https://youtu.be/2-xkLH5FjPw?t=2m) when appling the attached material to the particle mesh in the example particles\mesh.blend. Is there some trick to get it to function correctly?

![blender_2017-11-30_17-15-37](https://user-images.githubusercontent.com/1477787/33457953-3f580fac-d5f2-11e7-8b37-6c9876972044.png)

**Comment by luboslenco** [comment]
Hello @Gerkinfeltser,

To utilize `Particle Info` node particles need to be rendered and also simulated fully on the GPU:

- Check `Properties - Particle System - Armory Props - GPU Simulation`.

<img width="292" alt="screen shot 2017-12-04 at 13 34 21" src="https://user-images.githubusercontent.com/3685704/33553231-2aade532-d8f8-11e7-98bb-715148b66d7a.png">

- Select referenced Dupli Object (object being emitted) and set `Properties - Materials - Armory Props - Particle` to `GPU`.

<img width="329" alt="screen shot 2017-12-04 at 13 34 54" src="https://user-images.githubusercontent.com/3685704/33553294-6ae05a04-d8f8-11e7-8a56-25b2f46b573b.png">

Not ideal workflow yet as it's quite un-intuitive. I will eventually make armory set this out automatically. CPU simulation is more effective to emit high-poly meshes, while GPU is effective to simulate hordes of lower poly meshes or accessing particle infos. The rendering itself is always done using GPU instancing.

(some [related](http://armory3d.org/manual/remarks/supported_particles.html) info)

**Comment by Gerkinfeltser** [comment]
Ah! Ok, that did it! Thanks so much @luboslenco!

**Comment by luboslenco** [comment]
No prob! Some of the outputs of Particle Info can still be different/wrong compared to Cycles, but will take care of that.. 😃

**Comment by Gerkinfeltser** [comment]
Also, am I correct in assuming the "Lifetime" output in the Particle Info node isn't functioning yet?

**Comment by luboslenco** [comment]
Should now return lifetime as well.
