### ISSUE TITLE
Mac Armory v01 Build damaged and can't be opened

### ISSUE THREAD

**Issue by Bocaj22** [armory3d/armory#384]
This is pretty straight forward, I downloaded the mac armory v01 zip and uncompressed it, then I tried to open it but it took forever to verify then said the file was damaged, I also tried opening it in Terminal but it said the same. I also redownloaded the file in case the old zip was damaged, but it made no difference. Could someone take a look at it? Thanks.

**Comment by luboslenco** [comment]
Heyo @Bocaj22,

What macOS version are you on? I tested on High Sierra 10.13.1, it shows the verify dialog but somehow passes it successfully. Can you try to extract it in some other place? I extracted straight in the `/Downloads` folder but heard it can cause issues. Does [this](https://discussions.apple.com/thread/7682929?start=0&tstart=0) help?

**Comment by Bocaj22** [comment]
Its just Sierra 10.2.6.

**Comment by Bocaj22** [comment]
I extracted it form download and a folder I created for Armory

**Comment by Gerkinfeltser** [comment]
Sorry to interject but Armory's windows builds also take forever for me to unzip. I've never had issues with the build being corrupt however (so perhaps my issue & yours aren't related). It just always surprises me how long Armory takes to unpack compared to other Blender builds and until today I thought it might be due to my non-SSD drive being the issue but another Windows computer with an SSD takes long as well.

**Comment by Naxela** [comment]
I get the same long periods of time using the Windows explorer unpacker (sometimes with an occasionally error too). Using direct unpacking (non drag'n'drop) in 7zip makes it much easier and faster on both SSD (about 30-60 seconds) and non SSD. At least worth a try (on any platform) if you haven't already, at least in my experience

**Comment by luboslenco** [comment]
@Bocaj22 Did you had any luck? It looks like an issue running software from 'non-identified' developers. If you check `Preferences - Security & Privacy - Allow apps downloaded from`, do you have an option to select `Anywhere`? If not, running  `sudo spctl --master-disable` in terminal should restore that option.

<img width="780" alt="gate" src="https://user-images.githubusercontent.com/3685704/33554571-8769180a-d8fd-11e7-97a0-bb097a323783.png">

For unzip speeds, I have also been testing using 7zip on Windows and did not notice this. Looks like windows unpacker has trouble with archives containing lots of smaller files (for Armory that is Blender + Kode Studio + libraries to power game engine). Perhaps I could also reintroduce uploading 7zip archives along the default .zips, or a self-extracting .exe with no need to have 7zip installed.

**Comment by Bocaj22** [comment]
HUH, it seems to opens now.

**Comment by luboslenco** [comment]
Uh, but hey that's good news!
