### ISSUE TITLE
Request flowmap support

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#386]
*(optional - drag & drop zipped .blend file here)*
Could you add Flowmap support ? https://blenderartists.org/forum/showthread.php?429674-UPBGE-flowmap-node-structure-(faking-water-flow)

**Comment by Gerkinfeltser** [comment]
I reconstructed the node setup in cycles.

Cycles can render it assuming you switch out the time attribute node for the key-framed value one** but Armory kind of chokes on the math & mixRGB nodes it seems. "undeclared identifiers" is what the console reports.
[flowmap.zip](https://github.com/armory3d/armory/files/1524315/flowmap.zip)
**
![blender_2017-12-02_17-42-12](https://user-images.githubusercontent.com/1477787/33520412-58d85b8e-d788-11e7-8d81-3e0b369b4d58.png)

![scratch](https://user-images.githubusercontent.com/1477787/33520442-dcfbabfa-d788-11e7-9009-0416ff180295.png)

**Comment by luboslenco** [comment]
Nice! Did some fixes, seems to run in the latest armory now.

**Comment by mistajuliax** [comment]
Ok great, thank you Gerkinfeltser to share this node setup i will try this. And thank you Lubos to fix permanently issues we can find.

**Comment by Gerkinfeltser** [comment]
Excellent! Thanks Lubos (& the person who setup that flowmap stuff in UPBGE as well) & glad to be of assistance mistajuliax! Gave me a chance to do a bit more flowmap grokking! ;)
