### ISSUE TITLE
Export separate camera object for viewport camera

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#388]
If there are objects parented to the camera and you hit F5 with Camera set to Viewport in the "Armory Player" tab the object parented to the camera is parented to the camera you are looking through while playing. Found this while experimenting, wanted to see the rotation of the camera in game because it is invisible.
[objectparentbug.zip](https://github.com/armory3d/armory/files/1523707/objectparentbug.zip)

**Comment by FuriouZz** [comment]
Pull request #963

Commit https://github.com/armory3d/armory/pull/963/commits/193204024ba018e2c2b9f3689dddcaf736a244b4
