### ISSUE TITLE
OpenCL error in Windows 7

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#39]
OpenCL error (-4): CL_MEM_OBJECT_ALLOCATION_FAILURE in cIEnqueueNDRangeKernel

Error shows up after trying to render in Viewport using Ctrl+Z. It also happens when I click the button but the error is different. The error is Uncaught TypeError: Cannot read property 'length' of null. Also the progress bar on the top left instantly reaches 50% before stopping for a second and the black screen shows up where this second error shows up when I use the button.

I am using Windows 7 64-bit SP1 Ultimate edition. I am using the second release of Armory and the custom SDK provided on the download. I am also using the custom Armory PBR textures for everything (the two items both primitives) and the world has a sky texture. A camera is in scene and the file is saved.

**Comment by luboslenco** [comment]
Ctrl+Z in viewport will currently render with Cycles not Armory, do Cycles work? I need blend files, otherwise it's hard to guess;)

**Comment by George-the-1st** [comment]
Ya, I saw that before but then that got strange on me as well so I thought I should mention it. Regardless, here is the file: 
[simple.zip](https://github.com/armory3d/armory/files/587867/simple.zip)

**Comment by luboslenco** [comment]
There seems to be Armory PBR node instead of sky in world nodes, which is odd. But the error was usage of internal 'Arm' world, fixed in next build.
