### ISSUE TITLE
[Feature Request] "and" Node

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#390]
a "and" node would be really handy, I think about a node in which you plug in 2/more red inputs, like the "merge" node, only with the difference that it outputs the red thing only when all inputs are active. Currently I am using a workaround in which booleans are set to true or false if a red thing is active or not, and then stack "is true" nodes.

**Comment by Devination** [comment]
I've opened a PR #529 that should give you these features. Check it out 👍

**Comment by luboslenco** [comment]
It's in!
