### ISSUE TITLE
Can't rename new Armory Traits

### ISSUE THREAD

**Issue by matthewswallace** [armory3d/armory#391]
*(optional - drag & drop zipped .blend file here)*
![screenshot 2017-12-02 10 05 45](https://user-images.githubusercontent.com/123816/33517352-92911612-d748-11e7-9efb-8efd38f8dd18.png)
After creating a new Armory Trait, double clicking doesn't allow me to rename it.

[Armory.zip](https://github.com/armory3d/armory/files/1523928/Armory.zip)

**Comment by luboslenco** [comment]
Uh, will fix the description. If you are creating a new Haxe trait, click the `New Script` button below. That will create the `.hx` file and afterwards press `Edit Script` to open it up in Kode Studio. If you want to reuse already created trait, then it will show up in the `Class` list.

For nodes just switch to the 'Logic Nodes' type and select from the `Tree` list.

Perhaps good topic for a new manual page.

<img width="253" alt="trait" src="https://user-images.githubusercontent.com/3685704/33517405-1d90925c-d784-11e7-9242-d685e02a60a0.png">
