### ISSUE TITLE
Support dynamic mesh physics shape

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#392]
I'm having trouble with the pick object node.

![image](https://user-images.githubusercontent.com/33040347/33518992-39a60d22-d79e-11e7-9a82-f46aee60b0be.png)

It keeps showing 'null'... Is this a bug or am I missing something?
[Cell1.zip](https://github.com/armory3d/armory/files/1524079/Cell1.zip)

**Comment by luboslenco** [comment]
Logic nodes placed in the 'Physics' category will only work on rigid bodies. To make picking fast `Pick Object` node is using bullet behind the scenes. If you setup a rigid body it should work.

Hm, perhaps I can add a warning message when physics nodes are used but no rigid body is found.

<img width="238" alt="screen shot 2017-12-02 at 20 23 33" src="https://user-images.githubusercontent.com/3685704/33519043-1e9e1dd4-d79f-11e7-8665-7de583aeecc5.png">

**Comment by donalffons** [comment]
Thank you! A warning message would be great. Maybe it's just me - but I had this working before and just forgot to activate the rigid body physics.

**Comment by luboslenco** [comment]
Will do! Keeping open to not forget.:)

**Comment by donalffons** [comment]
... oh and I have want an L-shaped object in my scene to be pickable.
![image](https://user-images.githubusercontent.com/33040347/33519161-a0be75b4-d7a1-11e7-87db-3a9d1f01bd63.png)
I just noticed, that the mesh shape seems not to be implemented yet. Would be great if this can be done some time in the future (: .
![image](https://user-images.githubusercontent.com/33040347/33519171-ce4aa494-d7a1-11e7-9963-b4c0481b5cce.png)

**Comment by luboslenco** [comment]
Mesh is apparently working only for static meshes right now, will take care of that.

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armory/issues/600.
