### ISSUE TITLE
Play Action node does not work when no animation is assigned

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#394]
This one has been bugging me for quite a while:

![image](https://user-images.githubusercontent.com/33040347/33526150-f9a5dd7a-d83c-11e7-9a0b-de9cc6fc7110.png)

This setup gives the following error (unless I assign some kind of 'idle' animation):
![image](https://user-images.githubusercontent.com/33040347/33526137-a9d49e94-d83c-11e7-8508-1ccfeda64ab5.png)

[playaction.zip](https://github.com/armory3d/armory/files/1524811/playaction.zip)

**Comment by luboslenco** [comment]
Testing a fix at https://github.com/armory3d/iron/commit/ae8866484e062ba1efdf77266ad3ef7d7552d9e9 and https://github.com/armory3d/armory/commit/025b1b17c4ff42f9cc3d7a59769aa334d5809359.

**Comment by donalffons** [comment]
Works!
