### ISSUE TITLE
Armatures Animates Incorrectly Without Image Texture

### ISSUE THREAD

**Issue by SolarLune** [armory3d/armory#396]
Hey, there. 

So, the issue I'm having seems to be based around a bug where an armature doesn't deform an object correctly if it doesn't have an image node. I'm not able to reproduce the situation with a simpler mesh, so I'm not sure if that's the entirety of the issue, but that is something I'm seeing. Here's an example blend file showcasing the problem. The outline surrounding the character doesn't animate correctly on playback. Add an Image Texture node and connect it to the Material Output path, and the Outline will then animate correctly.

[ArmatureAnimationIssue.zip](https://github.com/armory3d/armory/files/1528398/ArmatureAnimationIssue.zip)

I'm using Armory 3D v0.1 on Solus OS (Linux).

**Comment by luboslenco** [comment]
Appears to work now.
