### ISSUE TITLE
Setting iron.system.Time.scale doesn't affect RigidBody

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#398]
Setting Time.scale to 0.1 slows down animations, but rigid bodies are not affected, objects still move at the same speed etc.

I tried setting armory.trait.physics.PhysicsWorld.active.world.stepSimulation(0.1) as well but it had no effect either.

**Comment by luboslenco** [comment]
Patched in https://github.com/armory3d/armory/commit/21089a1448d1fbe75bb8de4f7b3e217a14431bb8.
