### ISSUE TITLE
Sticky keyboards input bug in viewport

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#399]
1)Latest armory git
2)Latest armory example git
3)Open template_first_person example
4)Play on viewport
5)Try playing the game and move really fast like quake style gaming or movement.
6)Sometimes there is a lag or the player got stucked of almost 1 seconds while moving
7)Good news is that it only happens on viewport, not on armory player (krom runtime)

gtx970
i7 2600k
win10 64bit
8gb ram

**Comment by luboslenco** [comment]
Appears ok nowadays using b2.8.
