### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#40]
i start built in armory then save hit play in viewport and white screen
![2](https://cloud.githubusercontent.com/assets/23359603/20247026/0f6260ca-a9cc-11e6-91ef-38e40a4aa679.png)
![3](https://cloud.githubusercontent.com/assets/23359603/20247028/0f73c6a8-a9cc-11e6-9991-bd28df8d85b7.png)
![4](https://cloud.githubusercontent.com/assets/23359603/20247027/0f6d57e6-a9cc-11e6-92b6-9c2b32ba67eb.png) 
windows 10

**Comment by luboslenco** [comment]
Hm, did you install Haxe before? Looks like there is some conflict, either odd Kha version or odd Haxe version. It should not require haxelib at all.

**Comment by Xristoskr** [comment]
no i try it another  computer and give some error

**Comment by luboslenco** [comment]
Maybe a problem with non-standard characters in path? Could you try moving the SDK to 'C:\Dev' or something like that just to see if it makes a difference?

Does it work if you press Play(F5) to run it in separate window?

**Comment by Xristoskr** [comment]
Some problem again with built in version
Ps i try example and work only scene 1( addon version)

**Comment by luboslenco** [comment]
Wait so scene 1 works? Will recheck it all tomorrow and hopefully figure it out.

**Comment by Xristoskr** [comment]
Addon work 
Built in version doesnt work

**Comment by RedFrostGames** [comment]
I'm also getting the problem even after installing haxe. here is my console:
![image](https://cloud.githubusercontent.com/assets/23486940/20324911/61d89f24-ab50-11e6-8388-e7da450993c9.png)

**Comment by luboslenco** [comment]
@RedFrostGames Does it work if you setup Armory as [add-on only](http://armory3d.org/manual/getting_started/setupaddon.html)? Haxe is bundled in sdk, no installation needed.

**Comment by RedFrostGames** [comment]
How do I do that

**Comment by RedFrostGames** [comment]
because I purchased the armory from itch.io

**Comment by luboslenco** [comment]
Check here: http://armory3d.org/manual/getting_started/setupaddon.html

**Comment by RedFrostGames** [comment]
I cant find the download

**Comment by luboslenco** [comment]
You already have it, it's the one from itch. SDK is located in the folder you unpacked.

**Comment by RedFrostGames** [comment]
so what is the issue?

**Comment by luboslenco** [comment]
Well, you mentioned it does not work, does it work this way? (since Xristoskr mentions that worked for him).

**Comment by RedFrostGames** [comment]
I'm not sure what he did to fix it

**Comment by luboslenco** [comment]
http://armory3d.org/manual/getting_started/setupaddon.html

You already have the download, you can then install it as a regular add-on in regular Blender.

**Comment by RedFrostGames** [comment]
well that what I have had from the start

**Comment by RedFrostGames** [comment]
Can we skype about this some time? my skype name is rcplaneflyer1001 if you're interested.

**Comment by Xristoskr** [comment]
Hey lubos you can make tutorial video
