### ISSUE TITLE
Mouse wheel cords not working

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#400]
When printing "Mouse Cords"-"Wheel" it always says 0. Since it is the integer kind of green, I assumed it would go up and down with scrolling.

**Comment by luboslenco** [comment]
Mouse wheel input is not implemented when playing in viewport, will fix. Krom player or HTML5 builds should be ok.
(related: https://github.com/armory3d/armory/issues/239)

**Comment by Simonrazer** [comment]
It does also not work in the F5 thing, neither with Krom or Browser

**Comment by luboslenco** [comment]
Dang, that is weird. You are testing on Windows right? Does this node setup always print 0?

<img width="491" alt="wheel" src="https://user-images.githubusercontent.com/3685704/33680011-97edd93a-dac0-11e7-9d93-b6544e1a29ff.png">

**Comment by Simonrazer** [comment]
Yes it does always print 0, tested with latest and before updated the latest stable build was restored.

**Comment by luboslenco** [comment]
Tested on Windows 10 + Krom, I am not sure why it differs but runs ok here. Any special hardware you are using? When you enable `Armory Project - Debug Console` in Armory, are you able to scroll in that (provided there is enough items for scrollbar to show up)?

**Comment by Simonrazer** [comment]
Now it is working, if I scroll up it says 1, when down -1, and resets to 0 on the next frame I do not scroll on. Seems to be working fine now.
