### ISSUE TITLE
Crash involving Nodes + Physics

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#402]
In the first .blend the F5 thing crashes after a couple seconds after the ball hit the ground, but only if the FPScontrolls - Trait is activated on the Player. In the second .blend this doesn't happen, it is basically a rebuild of the first one with everything I thought that could cause it, so maybe it helps.

[physicbug.zip](https://github.com/armory3d/armory/files/1536718/physicbug.zip)

**Comment by luboslenco** [comment]
Now patched in https://github.com/armory3d/armory/commit/b7b9dd6b33f91f244701bd950489b609b2eaff6e, the first blend should no longer crash.
