### ISSUE TITLE
Sun lamp not working in Firefox

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#408]
**Chromium**
![image](https://user-images.githubusercontent.com/9007314/33729609-7ac99826-db7e-11e7-861f-5ab4502c6e8c.png)

**Firefox**
![image](https://user-images.githubusercontent.com/9007314/33729540-5156176c-db7e-11e7-8961-7e7181652f5a.png)

**Firefox console log:**
![image](https://user-images.githubusercontent.com/9007314/33729521-4200a57a-db7e-11e7-8b2b-5e7c046949d0.png)

**Comment by guzzard** [comment]
Related forum post: http://forums.armory3d.org/t/help-with-mouse-navigation-not-keyboard/551/11?u=guzzard

**Comment by luboslenco** [comment]
Checking it out. Does setting `Armory Render Path - Cascades` to 1 change anything?

**Comment by guzzard** [comment]
Setting cascades to 1 had no effect, same errors in console log and no visible change.

**Comment by luboslenco** [comment]
Fix pushed, seems to do the trick here: https://github.com/armory3d/armory/commit/34fd94af8a8b7f8d35088cb2e94cb52e4fbacef9

**Comment by guzzard** [comment]
Yes, working for me as well! :+1: :+1:
