### ISSUE TITLE
Ocean example+debug console+vsync off will hanged or froze krom

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#410]
1)Latest git armory and armory examples
2)Open ocean example
3)Disable vsync
4)Enable debug console
5)Fullscreen
6)Play in armory player(Krom)
7)Will froze or hanged the krom player or game

If I enabled vsync, it will plays just fine. My guess is that the speed is too high when the vsync is off and the debug console cant handle it. :)

**Comment by luboslenco** [comment]
Yo, runs good now using v0.2 for me.
