### ISSUE TITLE
Armory cannot play

### ISSUE THREAD

**Issue by yutigi** [armory3d/armory#413]
![blender_2017-12-10_01-32-37](https://user-images.githubusercontent.com/32337861/33798396-26a1c94e-dd4a-11e7-8b0b-86a1ea627213.png)

**Comment by luboslenco** [comment]
Hi @yutigi, select `Cycles Render` to work with Armory. This is to make Armory work with both Cycles and Eevee engines, there is no more separate 'Armory' engine.

But there are apparently some other issues you are running into. How did you install Armory? Please paste the command line output - press `Window - Toggle System Console` in Blender to show it up. If you are running armory as add-on, can you also try the bundled one to see if it that works?

**Comment by yutigi** [comment]
![image](https://user-images.githubusercontent.com/32337861/33802060-fe50bcc8-dda0-11e7-872c-5b4e9a57f350.png)

Hi @luboslenco,

I installed Armory from this [repository ](https://github.com/armory3d/armory), And follow instruction from [armory manual](http://armory3d.org/manual/getting_started/setupaddon.html). 

![image](https://i.imgur.com/f1Sqd2Y.png)
I also tried Armory with Example file. Node and properties was show in Blender but when I try to click "Play" button, It throw me an error.

**Comment by luboslenco** [comment]
You will need to clone the full sdk, not just this repo. I have started a repository which will link to everything, allowing for a single all-in-one clone. It's not yet functional as I need to push new armory builds first (this week) to align some things, but once ready it will be available at https://github.com/armory3d/armory_sdk.

I will also add info on this to the https://github.com/armory3d/armory_docs/blob/master/dev/gitversion.md.
