### ISSUE TITLE
Render-to-texture bug in HTML5

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#414]
In this test scene, I get the following error when I export to HTML5. It works fine in the blender viewport.
![image](https://user-images.githubusercontent.com/33040347/33800384-31726730-dd3f-11e7-8680-20eca544c0d7.png)
![image](https://user-images.githubusercontent.com/33040347/33800394-599ec302-dd3f-11e7-930a-12f19030823e.png)

I abused the MirrorTexture trait with flipped UV's on the plane to give me the POV of the little truck.

I can resolve the issue by un-parenting the 'mirror' camera from the 'cube' object.

[omnimovetest.zip](https://github.com/armory3d/armory/files/1545199/omnimovetest.zip)

**Comment by donalffons** [comment]
Oh noo, I just noticed that this has nothing to do with parenting the camera. This error seems to occurr randomly.

**Comment by luboslenco** [comment]
This is awesome.:) Should now be fixed in https://github.com/armory3d/armory/commit/cd985f073a4cf86aa360d965d96fd54f99c62c2c.

**Comment by donalffons** [comment]
Yay!
Seriously, you're doing a hell of a job here. Out of curiousity  - what is the difference between 
    notifyOnInit(init);
and
    iron.Scene.active.notifyOnInit(init);
and why does it fix this bug?

**Comment by luboslenco** [comment]
It's a pleasure to work on armory together and improve it for everyone!

I have added a new manual page on trait events, have to make this less of a mystery. Hope this explains it:
https://github.com/armory3d/armory_docs/blob/master/essentials/traits.md#trait-events

MirrorTexture trait depends on camera object to construct itself, so we need to wait till the scene is fully ready.

**Comment by donalffons** [comment]
That's clear now. Great documentation. Thanks a lot!
