### ISSUE TITLE
Add support for @prop on bundled scripts

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#417]
Currently not possible to have UI parameters on bundled scripts. Would be really nice to have.

**Comment by luboslenco** [comment]
![capture](https://user-images.githubusercontent.com/3685704/33846018-9a070f5a-dea5-11e7-8956-b66f87f71b98.PNG)

Testing in https://github.com/armory3d/armory/commit/35d55677378baf5dd9fb8cd212a816614517806a. :)

If bundled trait was added before this commit, you may need to re-assign it or simply hit `Refresh` button down there. Now we should be able to make bundled traits nicely configurable.

**Comment by guzzard** [comment]
Closing since it's working fine!
