### ISSUE TITLE
Light leaks between seams or joints

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#419]
1)Latest git armory and armory example
2)I dont think this happens in build 14 
3)Not sure how to solve this.
4)Happens on viewport and Krom

![armory light leaks between seams](https://user-images.githubusercontent.com/4146156/33881765-c9dce184-df70-11e7-9702-3b30066d040a.jpg)

**Comment by luboslenco** [comment]
To fix the leaks lowering `Properties - Lamp Data - Armory Props - Bias` will help. I have also updated the example and lowered it to `0.5`.

Will try to make the bias value smarter so there is no need to tinker with it manually.. The cause of leaks is that shadow maps have limited precision.

**Comment by takhimi** [comment]
@luboslenco When I open the endless runner, it still shows 1.0 for the bias. (I deleted all examples and copied back from latest git to confirmed and it is 1.0)

**Comment by luboslenco** [comment]
What in the world, seems to be ok here. Does this work? https://github.com/armory3d/armory_examples/archive/master.zip

**Comment by takhimi** [comment]
![armory bias still 1 0](https://user-images.githubusercontent.com/4146156/33884610-521172cc-df7b-11e7-8a59-c157d9be0434.jpg)

**Comment by luboslenco** [comment]
Oh noes, found it! For v0.1 release I normalized `Bias` property to 1.0 by default. There was same migration code which auto-updated it to 1.0 for older projects to prevent issues.

For latest git versions, armory now auto-rebuilds project when new git version is fetched. This also triggered the migration code for said bias property..

Updating armory to https://github.com/armory3d/armory/commit/ba8289b6369d9ae008df89a74cb0ea4c1b5d920a and then loading fresh game_endlessrun .blend should do. 👼

**Comment by takhimi** [comment]
Yup. It is fixed. Thanks
