### ISSUE TITLE
Windows SDK Errors 

### ISSUE THREAD

**Issue by PivotPointPress** [armory3d/armory#42]
Have no idea what this means 

Build started 11/13/2016 4:05:19 PM.

     1>Project "C:\Armory\Amory Testing\build\windows-build\Armory Building Scene 9.vcxproj" on node 1 (default targets).

     1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Armory\Amory Testing\build\windows-build\Armory Building Scene 9.vcxproj]
     1>Done Building Project "C:\Armory\Amory Testing\build\windows-build\Armory Building Scene 9.vcxproj" (default targets) -- FAILED.

Build FAILED.

       "C:\Armory\Amory Testing\build\windows-build\Armory Building Scene 9.vcxproj" (default target) (1) ->
       (Desktop_PlatformPrepareForBuild target) ->
         C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\Win32\PlatformToolsets\v140\Toolset.targets(34,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Armory\Amory Testing\build\windows-build\Armory Building Scene 9.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.29

Compilation failed.
Build failed, check console

**Comment by luboslenco** [comment]
Did you change runtime to 'Native'? I need details!

**Comment by PivotPointPress** [comment]
I started from scratch with a new file and have not received the same errors.  I will post the file if I am able to replicate the errors.  For now you can probably mark this as closed

**Comment by SolarLune** [comment]
You can close an issue yourself by pressing the "Close Issue" button at the bottom of this page.

**Comment by luboslenco** [comment]
Alright, I am 99% sure you switched to 'Native' runtime and that requires Visual Studio installed, since it needs to compile C++ code. I think I will have to make some issue template to encourage pasting blend files, otherwise this will get quite hard to manage.

But now, somebody has to press that button. 4 8 15 16 23 42.
