### ISSUE TITLE
[Renderpath Question] Post-process passes in the renderpath

### ISSUE THREAD

**Issue by Naxela** [armory3d/armory#421]
Hi Lubos!

This isn't an actual bug but more a question into the renderpath (in a lack of a better place to ask). Basically the short version of the question is: what is the correct way to introduce post-process effects as passes?

Presumably, it's probably my understanding of passes and the pipeline that is flawed, but what I've tried so far is attaching a shader after the compositor pass (in RenderPathCreator.hx) and gotten it to work (it's a very simple "**fragColor.rgb *= (1.5,1,1);**"  appended to a frag pass shader template).

```
		#if rp_compositornodes
		{
			path.drawShader("compositor_pass/compositor_pass/compositor_pass");
		}
		#else
		{
			path.drawShader("copy_pass/copy_pass/copy_pass");
		}
		#end

		#if rp_my_little_pass
		{
			path.drawShader("my_little_pass/my_little_pass/my_little_pass");
		}
		#end
```

My problem is that the result becomes very dark, presumably due to skipping the compositor pass. So, I'm thinking that I probably need to create a framebuffer object (I think?) that is then passed to the next pass using functions like path.setTarget and path.bindTarget?

![no_my_little_pass](https://user-images.githubusercontent.com/5429817/33884717-16d4dc42-df41-11e7-81cb-1aa005989375.png)

![with_my_little_pass](https://user-images.githubusercontent.com/5429817/33884728-207de842-df41-11e7-9d04-adfab194f43c.png)

**Comment by luboslenco** [comment]
Yes, it's like you said - `path.drawShader("my_little_pass/my_little_pass/my_little_pass")` will over-write compositor.

In some cases, compositor is the final pass and draws directly into the 'screen'. I am not sure if it's a possibility for your goal but ideally you would add a custom pass just before the compositor pass:
https://github.com/armory3d/armory/blob/master/Sources/armory/renderpath/RenderPathCreator.hx#L891

I have started a new, spartan, and probably not yet very clear doc:
https://github.com/armory3d/armory_docs/blob/master/dev/renderpath.md#adding-post-processing-pass

It shows a sample on how to perform a custom pass and then copy it back so the compositor will pick it up and push it onto the screen. Let me know if that helps - still lots to do to improve the workflow.

**Comment by Naxela** [comment]
That's fantastic! - I can't wait to try out the various possibilities with this!
Furthermore, the new docs also answered some questions about custom geometry passes that I was bound to ask at some point anyway 👍
