### ISSUE TITLE
armory dont work in 2.8

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#422]
hi i just installed armory on 2.8 and it doesnt work. i did exactly like in manual guide is written...

but it gives me error it never worked for me on 2.8
[armory 2.8 bug screenshots.zip](https://github.com/armory3d/armory/files/1553198/armory.2.8.bug.screenshots.zip)

**Comment by luboslenco** [comment]
Only builds marked as `blender28_experimental` on itch.io will work. I will also make sure to update those soon. I will tighten up the support once b2.8 reaches a state where it no longer introduces breaking changes.

**Comment by mushroomeo** [comment]
oh okay, when i saw the video of 0.1 that is said upgrade to 2.8 i thoughts is possible already and was looking every day for the armory 2.8 build. but then i thought it means i have to install it as addon in 2.8... well thanks much for info cant wait for new builds : )

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/572.
