### ISSUE TITLE
RigidBody scaling, convex hull scaling disabled

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#425]
With https://github.com/armory3d/haxebullet/pull/9 and https://github.com/armory3d/armory/pull/424 all rigid body types scale correctly except convex hull. Convex hull stays the same size regardless of object scale. It seems this is [on purpose](https://github.com/armory3d/armory/blob/master/Sources/armory/trait/physics/bullet/RigidBody.hx#L308)?

**Comment by luboslenco** [comment]
Patched in https://github.com/armory3d/armory/commit/0f85786eb0ddc396f30906fd3178ca099340785d.
