### ISSUE TITLE
Krom window crash

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#427]
armory_examples-17.12 > voxelgi_teapots

Play in view-port:

![gi](https://user-images.githubusercontent.com/3727523/33934889-d3aab62c-e002-11e7-8dc8-3a7d021b0aa0.png)

When hitting stop it crashes

In Krome is fine, but vert bad FPS.

My rig:

Intel i3-6100 4x
NVIDIA GeForce GTX 750 Ti
8 GB RAM
Windows 10 (up to date)

**Comment by luboslenco** [comment]
Heyo,

Check here for the requirements: http://armory3d.org/manual/graphics/global_illumination.html.
It needs blender 2.8 which gets rid of the legacy opengl stuff. There are also some perf tips, if it's too heavy then voxel ao mode may perform better.

git armory now also auto-disables voxel gi in viewport when running in b2.79, and prints a warning to the console.

Related: https://github.com/armory3d/armory/issues/334

**Comment by trsh** [comment]
@luboslenco voxel ao crashes in view-port play. This is also due 2.79?

**Comment by trsh** [comment]
Eh, no, now every Krome build is crashing

**Comment by trsh** [comment]
It just opens and closes, no red flags in console, strange

**Comment by trsh** [comment]
All happened after windows update this morning. Duno if it's related

**Comment by luboslenco** [comment]
Hm weird.:/ Is Krom crashing for every project, or just one specific blend? If it's specific to one blend file, can you paste it here?

**Comment by trsh** [comment]
@luboslenco all. Even tutorial 1 monkey :)

**Comment by trsh** [comment]
@luboslenco if you can suggest, how I can provide additional logs for you? I know only have to open Blender console and that one doesn't show any errors.

**Comment by luboslenco** [comment]
Yo! Do C++/Browser run-times work fine? Did you try re-downloading the sdk in case Windows update damaged something?

I also compiled the latest Krom binaries at https://github.com/Kode/Krom_bin/tree/master/win32. Those files would go to `Armory/armsdk/win32/Krom/win32`.

**Comment by trsh** [comment]
@luboslenco 

I did a web build, it worked and then also Krom started working. Duno what the problem was. Sorry for bothering you.

**Comment by luboslenco** [comment]
Not bothering at all. It's likely some bug in the build system, please let me know if it happens again. Usually cleaning the project should do.
