### ISSUE TITLE
Mouse reposition

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#429]
1)Latest armory and armory example git
2)Tried the fps template example
3)When moving mouse it does not change rotation of the player view

**Comment by luboslenco** [comment]
Eh, you are fast! It requires compiling the latest https://github.com/Kode/Krom build. I have pushed the updated ones for Windows at https://github.com/luboslenco/Krom_bin/tree/master/win32, in Armory it's placed at `armsdk/win32/Krom/win32`,

Will ship it with upcoming build. If nothing explodes I will also let Armory updater handle more to have this auto-updated.

If you select C++ runtime then it should work as is, provided there is a Visual Studio installation.

**Comment by takhimi** [comment]
Hehehe. Been waiting for this for quite some time. For sure I am happy to see it. Is this going to lock the mouse at the center of the screen ? How about reposition the mouse ?

**Comment by luboslenco** [comment]
Yes, locks the mouse at the center. This is how it's supposed to work:
![lock](https://user-images.githubusercontent.com/3685704/34043334-e7d92e90-e1a0-11e7-9b61-c8e1f2ce76c9.gif)

Mouse reposition - not yet, but will do once this works reliably on all desktop OSs.:)

**Comment by guzzard** [comment]
@luboslenco works in Linux also? :grin:

**Comment by luboslenco** [comment]
Looks like yes https://github.com/Kode/Kore/blob/master/Backends/System/Linux/Sources/Kore/Input/Mouse.cpp#L14?

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/374.
