### ISSUE TITLE
[12.17] addon not working

### ISSUE THREAD

**Issue by Franck7L** [armory3d/armory#430]
Hi,
I've tried to follow the addon installation process and got traceback error as I hit the Play button.
It seems something is wrong when entering the SDK path in the addon options, it automatically adds a "/" at the end of the string and the traceback error is showing wrong paths with a mix of "\\" and "/".
Best,
F

**Comment by luboslenco** [comment]
Hello! If you are on Windows, there is a new build on itch tagged as `Armory_v02rc0` which seems to work for me (even though it still appends "/", will look into it) . Other OS builds to follow soon. If you get a chance to test it and still get a traceback error, please also paste it here.
