### ISSUE TITLE
KinematicCharacterController - slope issue (JS)

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#434]
Difference in how ammo.js/Bullet 2.82 and C++/Bullet 2.87 handles slopes.

![slope_issue](https://user-images.githubusercontent.com/9007314/34250851-78a9c870-e63e-11e7-9ea6-1063ad21c80b.gif)

**Comment by luboslenco** [comment]
Linking this issue to https://github.com/armory3d/armory/issues/442.
