### ISSUE TITLE
KinematicCharacterController <--> RigidBody interaction issues - pushing

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#438]
Issues in the interaction/collision handling between KinematicCharacterController and RigidBodies.

KinematicCharacterController can be pushed quite easy, but it's very difficult to push RigidBodies. The shape used for KinematicCharacterController also affects this with some differences  in the result.

![interaction_issues](https://user-images.githubusercontent.com/9007314/34262675-560fa5ee-e66d-11e7-81d0-84d0070f23ed.gif)

**Comment by luboslenco** [comment]
Linking this issue to https://github.com/armory3d/armory/issues/442.
