### ISSUE TITLE
Asynchronous Spacewarp

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#44]
https://developer.oculus.com/blog/asynchronous-spacewarp/6 Essentially, I would like this technology to be implemented when VR becomes something to focus on. Right now, I can tell you from looking at the bleeding edge versions of Armory that critical bugs haven't even been fixed yet so this shouldn't be a concern but still, something to take note of.

**Comment by HeadClot** [comment]
Worth noting that this would reduce the system requirements for VR if done right.
I know that Oculus has said this in the above article.

**Comment by George-the-1st** [comment]
Ya I know, and imagine if this was done on this engine first or this early (or even within the next year). It would be a leading feature in the industry as a whole.

**Comment by SolarLune** [comment]
Just wanted to pop in to say that that link doesn't work.

**Comment by George-the-1st** [comment]
darn, they moved it. I'll change it relatively soon.

**Comment by luboslenco** [comment]
The link appears to be https://developer.oculus.com/blog/asynchronous-spacewarp now.

**Comment by luboslenco** [comment]
Link to issue https://github.com/armory3d/armory/issues/1034.
