### ISSUE TITLE
"Build failed, check console" error

### ISSUE THREAD

**Issue by ArgosOz** [armory3d/armory#444]
You may try to open and build the blend file from [Material Tesellation](https://github.com/armory3d/armory_examples/tree/master/material_tessellation) project.

Here's the error from the console:

```
ERROR: Linking fragment stage: Missing entry point: Each stage requires one entry point

SPIR-V is not generated for failed compile or link
```

The problem is related to the current version of Armory add-on.

---

Smoke.blend from [Particles](https://github.com/armory3d/armory_examples/tree/master/particles) project throws the same error.

---

Ok... this is weird...

When it throws the error once, it's impossible to build some projects unless you restart Blender.

**Comment by luboslenco** [comment]
Tested on the latest git, seems to be back in order again.
