### ISSUE TITLE
Soft body broken on C++

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#446]
My simple test scene...
![image](https://user-images.githubusercontent.com/33040347/34425756-47851924-ec2f-11e7-8f27-268a2e8ee95b.png)
...gives the following error when running in visual studio (compilation works fine):
![image](https://user-images.githubusercontent.com/33040347/34425750-3c6877f2-ec2f-11e7-88e8-89c74a186d46.png)

[untitled.zip](https://github.com/armory3d/armory/files/1592301/untitled.zip)

**Comment by luboslenco** [comment]
Fixed the error with https://github.com/armory3d/armory/commit/4170df9f654c7d3e17bf5cd290a645f86c0bd4c1.
