### ISSUE TITLE
Set project bundle & icon

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#448]
https://play.google.com/store/apps/details?id=com.ktxsoftware.kore

----> id=com.ktxsoftware.kore

**Comment by sh-dave** [comment]
You can already change it via khafile.js, see here: https://github.com/Kode/Kha/wiki/khafile.js#set-specific-options-for-the-android-native-target

**Comment by guzzard** [comment]
It's possible to change it yes, but default should be empty or invalid so the user **HAVE** to change it.

**Comment by luboslenco** [comment]
Latest armory sets it to package specified in Armory Project - Package, I could move this property to the exporter panel instead? But then it would not affect the actual Haxe sources path.

**Comment by guzzard** [comment]
As long as the user is forced to change it in order to be able to produce a valid package :+1:

**Comment by takhimi** [comment]
@luboslenco 
Maybe we can have the user to fills in some details regarding the project information at armory? As you can see from picture below are some of duplicate information needed when exporting to multiple platforms. 

![armory project details suggestions](https://user-images.githubusercontent.com/4146156/34462349-24b252f4-ee7d-11e7-9c7a-7c17d5bb2165.jpg)

I also would like to request to specify the project icons at Armory before export ? If it is possible. I think this would streamline the workflow a lot.

By default maybe you can display or fills in with default or generic details like "com.company.productname" and etc. When user click on "Publish" button, you can check if it is still "com.company.productname" or not and just need to display error that the details are not fills in correctly like Unity or Construct 2 did right now. So this will force the user to change or at least fills in correctly the project details or info if they have forgotten to do so.

Anyway, happy new year guys!!

**Comment by Kotarosdevgame** [comment]
Hey also the korefile.js
need it to change too
project.targetOptions = {"html5":{},"flash":{},"android":{"package":"org.kdgames.kd"},"ios":{}};

**Comment by luboslenco** [comment]
Bundle and icon properties added to Armory Exporter.
