### ISSUE TITLE
Linked objects do not showup in Armory 

### ISSUE THREAD

**Issue by PivotPointPress** [armory3d/armory#45]
When using Linked objects the armory engine does not render them.  Appended objects do work.  This will be a huge deal for game creation.  This is on a windows machine.

**Comment by luboslenco** [comment]
Please provide test blend files to reproduce if possible. The basic scenario works but I suspect something goes wrong when it gets more complicated.

![linked](https://cloud.githubusercontent.com/assets/3685704/20296878/92b2c0fe-ab0d-11e6-9766-28f378df401b.jpg)

**Comment by PivotPointPress** [comment]
Attempted to reproduce the issue with my laptop and couldn't get past a black screen.  On my home machine the engine would run but not show the Linked objects in the scene.  My best guess is some thing with the textures.  Neither of my machine have very high end Video card.  The laptop has a Geforce 840m with 2 gigs of memory and the Home machine is a Geforce 550 ti with only 1 gig.  Could part of the problem be GPU memory.  All the items I am building have 2048 textures.  Perhaps I should lower the textures sizes for testing purposes?

**Comment by luboslenco** [comment]
Should work on older GPUs if you switch renderer to 'forward' or 'forward_low', in Camera data - Armory Props.

**Comment by luboslenco** [comment]
Improved support for linked objects in Build 3. In case of more issues just reopen this.
