### ISSUE TITLE
Material Parameters

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#451]
Unreal Engine 4 allows you to create materials with parameter nodes.  Basically, these are special nodes with changeable properties, such as numbers, colors, textures, vectors, etc.  They allow you to create multiple instances of the same material with differing properties without having to recompile the material.

I would love to see this implemented in Armory, especially if material instances could be created or tweaked from code at runtime.

More info here: https://docs.unrealengine.com/latest/INT/Engine/Rendering/Materials/HowTo/Making_Parameters/

**Comment by Gerkinfeltser** [comment]
Seconded. Yeah, those are super useful for Particle Materials.

**Comment by luboslenco** [comment]
`RGB`, `Value` and `Image Texture` material nodes can be controlled at run-time now.

Added a new example (needs git armory):
https://github.com/armory3d/armory_examples/tree/master/material_params

**Comment by Megalomaniak** [comment]
Uniforms would be pretty great. But then I'd prefer GLSL as nodes over a uber-shader approach any day.
