### ISSUE TITLE
Bundled scripts aren't showing up

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#452]
Not sure what i did, but the bundled scripts aren't showing up in this file.
Haxe scripts seem to work fine (see ArcBallCopy.hx on the camera object).

Version: Armory_v01b_win64.7z from itch.io
[cathedral.zip](https://github.com/armory3d/armory/files/1609300/cathedral.zip)

They don't even show up when i create a new scene (File -> New) after i loaded this one.
It works when i restart blender, and try to add a trait to the cube in blenders default scene.

**Comment by luboslenco** [comment]
Appears to work now on git version, maybe we get lucky and the issue got fixed.
