### ISSUE TITLE
Logic nodes output colours

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#453]
All those nodes have green outputs, which could make recognizing their type of output harder.

![problem](https://user-images.githubusercontent.com/30187223/34648619-d323e5a4-f39c-11e7-8ff9-2be1ff06bed5.JPG)

**Comment by ubaldy** [comment]
Is this a request for color coded types?

**Comment by luboslenco** [comment]
Array socket is now color coded. The rest is colored as values for now to keep number of colors reasonable.
