### ISSUE TITLE
Problem with several materials and one mesh

### ISSUE THREAD

**Issue by Daniel-Ayala** [armory3d/armory#456]
When assigning a second material to a mesh, the faces with one of the materials have no collisions.
  
In the attached file: move with WASD. Orange parts of the mesh let the ball go through.
[mm(errors).zip](https://github.com/armory3d/armory/files/1616149/mm.errors.zip)

**Comment by luboslenco** [comment]
Thanks for report! Should be now fixed in https://github.com/armory3d/armory/commit/09a91b14dfd6d9059b5881533196d3d7e38f0f3c.
