### ISSUE TITLE
Moving away form initial camera FoV removes GI

### ISSUE THREAD

**Issue by Daniel-Ayala** [armory3d/armory#458]
I have a project where the camera follows a rolling ball. However, the further it gets form the initial position (where the camera looked at initially), the less GI there is.

Near the starting point:
![image](https://user-images.githubusercontent.com/12978863/34780384-4b77f512-f623-11e7-9f2c-f215926b8ba4.png)

Far from the starting point:
![image](https://user-images.githubusercontent.com/12978863/34780335-2cd34c4c-f623-11e7-8afe-0ded492e4da0.png)

Specially noticeable on the ball and some corners.

Find the proje
[marble.zip](https://github.com/armory3d/armory/files/1619395/marble.zip)
ct attached (move with WASD).

**Comment by Simonrazer** [comment]
Voxel GI and AO are currently totally broken for me, at least with sun lamps. GI only processes in some places (it seems like that), the rest is very dark and AO works correctly, but also darkens the whole scene. Revoxelize is turned off.
 Point lamps seem to still work pretty good.
[gibug.zip](https://github.com/armory3d/armory/files/1622776/gibug.zip)
(the above .blend is totaly black everywhere there is mesh for me)

**Comment by luboslenco** [comment]
Should be ok nowadays with revoxelization enabled.
