### ISSUE TITLE
Is it possible to make the y - axis vertical instead of making the z axis the vertical axis

### ISSUE THREAD

**Issue by Raj2032** [armory3d/armory#459]
I was wondering if there could be an option given to users that can replace the y and the z axis. I mean isn't it a little weird how the z axis is representing the vertical view? And shouldn't the z axis point to the depth instead?

**Comment by Daniel-Ayala** [comment]
This is three-dimensional space. The z axis in world space always goes up. What you call "depth" depends on the position of the camera, and is the z axis in screen space.

**Comment by Raj2032** [comment]
I understand but like is it not possible to change it and make the y axis
go up and down? Just like in Maya and Unity how up and down is the y axis?

**Comment by luboslenco** [comment]
I could add that option but we would need Blender to enable this as well, which I think is unlikely.

**Comment by Raj2032** [comment]
But Blender is Open Source, so isn't it possible to modify their code?

**Comment by luboslenco** [comment]
It is possible but would you want me to spend 100 hours on it? I can fix 10s of armory-code issues in that time.:)

Armory needs to co-op with Blender as much as possible to keep advancing. For every step we have to consider how much time will it cost - otherwise we will not be able to reach 1.0 this year.

**Comment by luboslenco** [comment]
That would be something like an armageddon mission. We would all die.

**Comment by Raj2032** [comment]
I mean like we just work with Blender to include that option to users?
