### ISSUE TITLE
Is it possible to 'materialise' the game engine by giving users the option to change to material design?

### ISSUE THREAD

**Issue by Raj2032** [armory3d/armory#460]
Blender does not tend to have a nice user interface (UI) so I was wondering if it is possible to give users the option to use material design, or by default use a material design UI? This will give a feeling of a modern, yet powerful piece of software to use?

**Comment by zauberparacelsus** [comment]
Probably related to #451

**Comment by Raj2032** [comment]
Nah this issue is different, I am referring to the user interface of the
game engine itself.

**Comment by Raj2032** [comment]
Material Design is Google's made user interface.

**Comment by sh-dave** [comment]
You can try to find a better theme here: https://www.blendswap.com/terms/category/blender-themes

**Comment by Raj2032** [comment]
I mean like to try and completly redesign the user interface for Blender,
by removing all the layout etc and then use material user interface.

**Comment by luboslenco** [comment]
This is out of scope for armory project - however blender 2.8 comes with further ui refinements which I hope will suit you!
https://code.blender.org/2017/10/blender-2-8-design-document/
https://www.blender.org/2-8/
