### ISSUE TITLE
The ability to save external blend files

### ISSUE THREAD

**Issue by Raj2032** [armory3d/armory#461]
If a user imported an external blend file to the main blend file, if the user decided to modify the external model, allow the user to save changes directly to the external blend file.

**Comment by luboslenco** [comment]
Do you mean linking or appending? On `File-Append` a copy is created, but if you do `File-Link` you should be able to jump between multiple .blends and have each one saved individually. Some more info at http://armory3d.org/manual/essentials/workflow_multiuser.html.

**Comment by Raj2032** [comment]
What does appending mean in Blender?

**Comment by Raj2032** [comment]
Ignore my last message, so like you can link other blend files to the
current main blend file, am I correct?

**Comment by luboslenco** [comment]
Yo, correct! Please move further discussion on this to forums, as we would be emailing everyone watching this repository.
