### ISSUE TITLE
LoadBar broken?

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#463]
Somehow the load bar is not showing up any more, when I publish my projects.

In Main.hx, it seems to export correctly:
![image](https://user-images.githubusercontent.com/33040347/34897451-570ece9c-f7ee-11e7-96e5-2264c2f64a65.png)

Even in kha.js, the code of LoadBar.hx is there:
![image](https://user-images.githubusercontent.com/33040347/34897494-82b248a8-f7ee-11e7-9b10-ce703d8f4d11.png)

Here is a relatively large test scene, that I created from scratch: 
[LoadBar.zip](https://github.com/armory3d/armory/files/1627661/LoadBar.zip)

**Comment by donalffons** [comment]
Awesome! I love it :)! I noticed some other broken things in some of my old test scenes. Will open separate issues.
Thanks, Lubos!

**Comment by luboslenco** [comment]
Sounds good, and huge thanks for testing!
