### ISSUE TITLE
DebugDraw bounds function is not working correctly (rotation and scale not applied)

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#464]
It didn't calculate the rotation and scale. Checked the source code,  it only calculates translation...I guess this function is not finished yet?
/Milo
![screenshot from 2018-01-17 13-23-26](https://user-images.githubusercontent.com/17811339/35027101-b2aee180-fb89-11e7-9a97-8fd4b0d6a18d.png)

**Comment by luboslenco** [comment]
Was not finished, but now patched in https://github.com/armory3d/armory/commit/7044c708a872fd590b50e892893b1124739411ad.

**Comment by MLHX** [comment]
it works! Thanks.

/Milo
