### ISSUE TITLE
Incorrect rotation in rigged/animated object

### ISSUE THREAD

**Issue by Daniel-Ayala** [armory3d/armory#465]
Hi. In trhe attached project (in the starting location), I have placed a simple animated object. An arm with a cube at the end. I ahve set up deformation based on vertex groups and applied the armature modifier.

When I hit play in the timeline, the animation plays correctly, with the arm swinging. However, when the scene is played in Armory, the arm is rotated. An interesting fact: an invisible cube used for phisics does not get rotated
[marble.zip](https://github.com/armory3d/armory/files/1644706/marble.zip)

**Comment by luboslenco** [comment]
Cool! Been pushing more fixes, arm position should be correct now + invisible physics cube also gets rotated.
