### ISSUE TITLE
Branch node only following true output

### ISSUE THREAD

**Issue by Ejnallid** [armory3d/armory#467]
![capture](https://user-images.githubusercontent.com/35704059/35239224-caf405f0-ffa7-11e7-8ed4-9f4149a3cbea.PNG)

When using the branch node I have found that it only uses the true output. I have a gateway node going into a branch node so that I can get a true and false statement which then changes a property value accordingly. However I have found that only the true output is ran although it is worth mentioning that the true output is only ran when it should and it does not run when the false output should. The blue line in the image is the line that works and the red doesn't.

**Comment by Simonrazer** [comment]
You can't plug a red output into a yellow (boolean) input! You have to duplicate your existing gate node, change the type to "Not Equal" and plug its output into "Set Property"-> in.
Or you can get logic_pack and use the inverse node.

**Comment by Ejnallid** [comment]
ah.............. that's embarrassing.......

**Comment by Simonrazer** [comment]
don't worry, happens to me all the time 🙂

**Comment by Ejnallid** [comment]
Still having issues as its now only running the bottom not equal gate. It shouldnt run it at the beginning as the variable is already 0 and then it keeps running it whenever I press RMB. Print nodes are there for debugging
