### ISSUE TITLE
BGE logic conversion

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#47]
I know logic nodes are being implemented, but what about the BGE logic bricks? I've been able to do pretty cool stuff with those logic bricks, I love how simple it is to use (although I am sure Logic Nodes will be too).

So are there any plans on adapting the BGE logics, or it will really only have its own logic?

**Comment by bibleuspro** [comment]
@luboslenco When you get to this and feel like adding help wanted, I may be able to make some headway on this if you point in right direction. I don't know BGE but believe playing nice with them/taking good leaving bad will help everyone and maybe the 2 become one. I will add Armory branding is better, and general scope is much more attractive. However the BGE, playing with BMD Decklink showed real vision as well, as well as in other areas, like that they are listed in developer.blender.org hopefully BGE reaches out to you or vice versa to collaborate.

**Comment by luboslenco** [comment]
Sounds good! Waiting for logic nodes situation in Armory to progress / mature so there is better ground for this.

**Comment by luboslenco** [comment]
Putting this on hold for now - logic nodes are getting better but still have tons of work to do and want to prevent going out of focus till it's rock solid.
