### ISSUE TITLE
Mesh position mismatch between viewport and browser builds

### ISSUE THREAD

**Issue by FireSlash** [armory3d/armory#470]
Oddly enough, the viewport view is putting my meshes in a totally different place than the browser builds (launched from either kode studio, or the "play" button in blender).

In viewport view, the relative positions are consistent with what I'd expect, but they're all offset down and to the right for some reason. Unclear why, but not really the end of the world?

In browser view, the absolute look like what I would expect, but the floor tiles have a bizarre Z offset putting them above the player camera (They're invisible in the screenshot because all we're seeing is the backfaces, though you do see the lighting on the wall objects being clipped)

Tested with Armory 0.1b
Demo blend: [bug_01_demo.zip](https://github.com/armory3d/armory/files/1663073/bug_01_demo.zip)
Side by side comparison: https://imgur.com/a/WczrJ

There's a good chance I'm doing something very dumb, but it seems like my stupidity should be reflected equally in both views.

**Comment by luboslenco** [comment]
Hm, probably something off in Armory. Are you able to also pack in your `StageRenderer.hx` trait for me?

**Comment by FireSlash** [comment]
Ah, whoops. Those aren't packed in the blend. 

Here is a zip of the sources folder. [cralwler_bug_01_sources.zip](https://github.com/armory3d/armory/files/1671428/cralwler_bug_01_sources.zip)

**Comment by luboslenco** [comment]
Appears to produce the same output now using the new 0.2 builds.
