### ISSUE TITLE
Soft Body explodes with more than one material assigned

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#473]
Hi!

There is an issue with soft bodies. I made a test scene, that looks like this:
![image](https://user-images.githubusercontent.com/33040347/35485379-493316de-045f-11e8-880d-724612e7d6f2.png)

1, 2 and 3 are soft bodies. The ground is a static rigid body with mesh collision. The issue is with model no. 2.

1. is working fine. This model has only one material assigned
2. is exploding into black spikes. This model has two materials assigned
3. is working fine. It has two materials assigned.

[SoftBodyMaterials.zip](https://github.com/armory3d/armory/files/1671415/SoftBodyMaterials.zip)

**Comment by luboslenco** [comment]
Yo! I think I did something, can you try using https://github.com/armory3d/armory/commit/2ba40e088ffd0d5905b8d6469c7b9518fccaab83?

**Comment by donalffons** [comment]
Works perfectly! Thank you!
