### ISSUE TITLE
Problem in Call Node Group

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#475]
There seems to be a problem with the Call Node Group.
When you do inside an object translation or do a send event, the compilation fails.

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
I have fixed one Call Node Group issue in https://github.com/armory3d/armory/commit/8bfc99c27984573adf39ea6d8285e92f7b27da39, not sure if it's the exact one you are facing though. Please always paste .blend and compilation error whenever possible, so I can make sure the reported bug is fixed.

Anyway, hope the patch mentioned above helps!

**Comment by Didiercode** [comment]
Here the screen copy for compilation error ... more after making the special blend file for showing this problem, consider that translation is ok ... mistake I suppose was due that the Trait wasn't added to object cube, even if the Node Group was called apparently without error.

![image](https://user-images.githubusercontent.com/20455592/35510033-b9da9118-04f6-11e8-8de6-aabcaf16c686.png)

[pour_issue_475.zip](https://github.com/armory3d/armory/files/1673485/pour_issue_475.zip)

**Comment by luboslenco** [comment]
Thanks, pushed another fix at https://github.com/armory3d/armory/commit/9e6bbe2bd7d1554a510d520d4e6777ca0ae9120e. Also, there should be no need to add trait which you are calling through `Call Node Group` to object now.
