### ISSUE TITLE
Setting opacity on one material in a multi-material object changes the last material opacity

### ISSUE THREAD

**Issue by f-rank** [armory3d/armory#477]
![image](https://user-images.githubusercontent.com/1836566/35623777-b27c9fe4-0684-11e8-97d2-f693dc4f15fd.png)

Bottle with a cap on top, one single mesh.
Cap part is one material the rest is assigned a diff material, when I do F5->HTML and play it, the bottle disappears, even at low values, though it is the cap material that had its opacity changed.
No matter the material that has its opacity changed, the second material always disappears, not respecting the opacity number set.

![image](https://user-images.githubusercontent.com/1836566/35623921-3257453e-0685-11e8-93c3-03a98f9c53f7.png)

**Comment by luboslenco** [comment]
Need to fix mixing translucent and opaque materials, merge with https://github.com/armory3d/armory/issues/588.
