### ISSUE TITLE
Diff results in HTML and Krom

### ISSUE THREAD

**Issue by f-rank** [armory3d/armory#478]
[pack_shot_background.zip](https://github.com/armory3d/armory/files/1682688/pack_shot_background.zip)

Weird banding mostly.

**Comment by trsh** [comment]
@f-rank I don't think VoxelGI is supposed to work in HTML builds. So that could the difference?

**Comment by f-rank** [comment]
@trsh if it isn't supposed to, it sure is rendering with the look I like in html builds and banded in krom builds. I can try an .sln in visual studio but at the moment I havn't got used for that.
Being that the html build looks correct and presents no banding because of what looks like lighting issues in krom. The difference goes the other way so to speak.
If the krom renderring looked like the html build everything would be ok.

![krom_and_html5](https://user-images.githubusercontent.com/1836566/35712921-8f62930e-07bc-11e8-9f53-d8f848ec2449.png)
krom is to the left, html is to the right.

**Comment by f-rank** [comment]
![vs2017_krom_html](https://user-images.githubusercontent.com/1836566/35713430-2a95e522-07bf-11e8-93af-324d8c56703b.png)
Left to right: vs2017 build, kha build, html build.

**Comment by trsh** [comment]
As VoxeGI, I suspect, doesn't work at HTML, it can NOT look the same. Try turning it of, and then do comparing ;)

**Comment by f-rank** [comment]
@trsh, it is the other way around in this case isn't it. If you notice, html is rendering without issue and the other builds have an obvious huge artifact.
If anything had to be turned off it would have to be for the visual studio or krom build.

**Comment by trsh** [comment]
@f-rank maybe it some issue with GI, could be. I also have experienced some strange things with it turned on. So maybe you don't need it? It can be turn off in settings.

**Comment by trsh** [comment]
@f-rank Im sure @luboslenco will look into your example, when he get's to it

**Comment by f-rank** [comment]
Yep pretty sure it is a GI thing. Turning off does correct the odd banding. Good thing there are blender files to throw aroun

**Comment by f-rank** [comment]
Yep pretty sure it's some odd GI issue.
Thanks @trsh.

**Comment by luboslenco** [comment]
Should now match better in 0.4.
