### ISSUE TITLE
Autoexposure makes remanence and artefacts

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#479]
When autoexposure is enabled i have black glitches on screen and remanence .... 
[Artefacts.zip](https://github.com/armory3d/armory/files/1685261/Artefacts.zip)

[autoexposure_test.zip](https://github.com/armory3d/armory/files/1685267/autoexposure_test.zip)

**Comment by luboslenco** [comment]
Pushed some patches so at least the glitches should be gone. There is no histogram yet, it just takes the average luminance of the current frame. Will add histogram along the way!

**Comment by mistajuliax** [comment]
Ok i will try it. If bugs vanished i will close the issue. Thanks a lot for replying quick ! keep the great job Armory is amazing :)

**Comment by mistajuliax** [comment]
Remanence artefacts vanished ... But i still have weird color behavior ... i'm expected when caemra is near to a dark area autoexposure make the light brighter and when it is far it's darker. I don't get the result, i get only color changes. May be an example is needed with a an adequate scene to properly set up  autoexposure.

**Comment by mistajuliax** [comment]
Hi, in last build i noticed autoexposure is better and seems to work when zoom in/out, but mouse navigation still causes glitches and color glitches ... but it's seems better.

**Comment by adriansnetlis** [comment]
I can confirm that auto exposure does weirdly affect your colors as you navigate the scene. The calculation and execution seems off. I thought it was supposed to add bias to exposure, but it appears to affect different color channels differently.

**Comment by luboslenco** [comment]
Please disregard this feature for now, I will add some developer mode flag and hide these till fully implemented.:)

**Comment by adriansnetlis** [comment]
I am wondering if changing line 391 of armory/Shaders/compositor_pass/compositor_pass.frag.glsl from
```fragColor.rgb *= vec3(1.0) - min(expo, vec3(autoExposureStrength));```
to
```fragColor.rgb *= 1.0 - min(length(expo), autoExposureStrength);```
would make it work better. Anyways, I know this would not be a permanent solution anyways. I may look into better ones myself and share them if I'm successful ;)

**Comment by mistajuliax** [comment]
Hi @luboslenco, autoexposure fixes seems to work. i will check and make tests but i have no artefactx anymore since last 5 hours fixes ! :)

**Comment by luboslenco** [comment]
Happy to hear that artifacts are gone. Also exposed auto-exposure speed now.
