### ISSUE TITLE
bug when enabling armory

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#481]
hi i tryed the new 0.2 version and got bug

![screenshot_1](https://user-images.githubusercontent.com/9019563/35714175-7291e14e-07cb-11e8-891d-9edf5fdca213.jpg)

somehow every time i had bugs with new version except first time... i remember had to delete whole AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons folder to able to run it

**Comment by AFWSI** [comment]
Are you sure there’s not two addon files with the same name? It’s been a while since I got a duplicate error ,but I think this is the error you get in blender, when you have the addon in appdata and the addons folder.

**Comment by mushroomeo** [comment]
oh the multiple addons message can ignore. its only because i did try install it as addon after the bug happened... so its not the problem. did screenshot after

**Comment by luboslenco** [comment]
It's conflicting with some other add-on for some reason I think. If this still happens please reopen with a list of addons and I will test it.
