### ISSUE TITLE
Keyframes make objects vanish after loop.

### ISSUE THREAD

**Issue by f-rank** [armory3d/armory#482]
When keyframes are set just close enough it makes the object vanish after one run, so the loop suddenly misses objects for some reason. Blend file shows the minimum case problem after hitting play/F5 and watching one run of the animation.

[anim_bug.zip](https://github.com/armory3d/armory/files/1689699/anim_bug.zip)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/iron/commit/ee71ef79d2f27981473992260f2208a8caf6e90d, thanks for report.
