### ISSUE TITLE
Voxel GI + SSAO = artifacts

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#483]
In the "teapots" example, when you turn on SSAO instead of RTGI there are artifacts on screen.

**Comment by luboslenco** [comment]
Unable to get that here, any other changes apart from SSAO you can think of? Maybe it's something worse which gets randomly triggered. Can you share a screenshot?

**Comment by Simonrazer** [comment]
Oh yes, revoxelize+temporal filter is on. here the screenshot
![bug](https://user-images.githubusercontent.com/30187223/35820967-ae50c144-0aa7-11e8-90fd-dbc87126ec07.JPG)
and the .blend
[teapots.zip](https://github.com/armory3d/armory/files/1696240/teapots.zip)

**Comment by luboslenco** [comment]
Oho, perfect. Should be good now https://github.com/armory3d/iron/commit/c278037e4cc71609be03e7ae62a6b07dab295024.
