### ISSUE TITLE
Mesh object with empty mesh crashes C++ build

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#487]
I made a simple test scene, again:
![image](https://user-images.githubusercontent.com/33040347/35776641-6e0fd654-09a0-11e8-8c4c-0c2b00ca9281.png)

The object named "Tile_+014_+002_L15" causes the issue. It is pretty much just an empty mesh object with no mesh.

After publishing this to Windows / C++ and compiling it with visual Studio (Release + Debug gives the same result), I get the following exception error from VS:
![image](https://user-images.githubusercontent.com/33040347/35776636-56ad2688-09a0-11e8-864b-8cb486e2e603.png)

[Citybug.zip](https://github.com/armory3d/armory/files/1692683/Citybug.zip)

**Comment by luboslenco** [comment]
Whoa, great catch. Fix at https://github.com/armory3d/armory/commit/e8346a0911ab55a179a975e3c7c06b93be58c3eb.

**Comment by donalffons** [comment]
Thank you, Sir!
