### ISSUE TITLE
Object with decal can't be correctly spawned

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#488]
If you spawn an object that has "decal" enabled in its material, it will only spawn copys at the same place of its original when called to spawn with logic nodes. Here the .blend. Just try it out with the sphere or decal off instead.
[decalbug.zip](https://github.com/armory3d/armory/files/1692787/decalbug.zip)

**Comment by luboslenco** [comment]
Fix https://github.com/armory3d/iron/commit/641fbde508d42bcfade3b4f0ba816405c86e1ecd. Decals still troubling, looks like they are not able to overlap, so more fixes to come.
