### ISSUE TITLE
Contact Shadows

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#49]
Unreal Engine 4.14 was released today, and one new rendering feature it adds is "contact shadows", which allows detailed objects to cast high-quality shadows by using the screen-space depth buffer information.

Excerpt:
> The Contact Shadows feature adds a short ray cast in screen space against the depth buffer to know whether a pixel is occluded from a given light or not. This helps provide sharp detailed shadows at the contact point of geometry. There are a number of reasons why shadows through other algorithms may have missing or blurry contacts. Typically it is due to lack of resolution or a depth bias. Regardless of the reason, the new Contact Shadows feature can fill in the gap very well for a small cost.

![example image one](https://docs.unrealengine.com/latest/images/Support/Builds/ReleaseNotes/2016/4_14/image_7.gif)

![example two](https://docs.unrealengine.com/latest/images/Support/Builds/ReleaseNotes/2016/4_14/image_6.gif)

**Comment by bibleuspro** [comment]
I believe we already have this right?
![image](https://cloud.githubusercontent.com/assets/19825051/21563629/40d2d88a-ce41-11e6-94b0-45e7558ba6ab.png)

**Comment by luboslenco** [comment]
First implementation of screen-space ray-traced shadows is in.
Enabled in *Camera - Armory Render Props - SSRS*.
Ray Step can be adjusted in *Armory Render Props - Advanced - SSRS*.
