### ISSUE TITLE
Idea for LODs.

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armory#490]
I was playing around with the LOD blend example and thought of something that might improve the way LODs are done. Can Armory edit modifier while in play mode? If not possible, it would kinda rule out my idea.

OK, I tried to find the example of what I was thinking ,but I can’t find it. I seen where somebody made a script/addon that you could type into a string property for the number of faces you wanted for LODs. It would then edit the decimate modifier to match the number of faces in the string property. 

What I was thinking for Armory, in Armory props for LODs you could have like two settings. One setting to choose distance and a string property to choose the number of faces for that distance. This way you could just have one mesh with a modifier and cut down on the number of faces/polygons for the scene.

**Comment by luboslenco** [comment]
Sadly Blender modifiers need to be handled at build-time. For run-time, shader-based techniques are preferred.

**Comment by BransonGitomeh** [comment]
hey @luboslenco for instance when doing terrain, what if we wanted to use chunks to remove some of the land thats not visible from runtime? ie just a square around the user with distance. as the player is walking around, we remove some of the chunks behind him and place more infront of him. based on a predefined height map and probably also placing details like grass, trees and rocks clouds, smoke and more. for far away objects what if a user wants to add fake planes with tree images with an alpha so it looks like a large forest etc

can this all be done in shaders? we would definately need to maybe write some haxe to make the plane meshes, set their subdivisions and assign the materials .

what do you think? many thanks.
