### ISSUE TITLE
Rigidbody - if "linear factor" is set to 0,0,0, the object does not affect other objects

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#491]
It seems like if "linear factor" is set to 0,0,0, the object does not effect any others anymore. It would be handy if it would be possible to turn off gravity or influence of other objects for the object the player is controlling.

**Comment by luboslenco** [comment]
Not sure I can reproduce, perhaps bullet puts the body into sleep or something? Try to uncheck `Physics - Armory Props - Force Deactivation`. If it still happens then please throw me a blend file.

**Comment by Simonrazer** [comment]
For my testing toggeling that doesn't help. Here the .blend. The sphere should be able to move the plank, which is locked in location and rotation, but not on rotation Z. Right now the ball passes through it, but when you turn on Linear Factor for it it works, but he gets pulled down by gravity.
[physbug.zip](https://github.com/armory3d/armory/files/1711601/physbug.zip)

**Comment by luboslenco** [comment]
Looks like Bullet cancels those out because both have zero linear velocity. Setting sphere to linear velocity of 1 and using `Set Velocity` node instead seems to work.
