### ISSUE TITLE
Emission broken

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#495]
It seems like Voxel GI ->emission Voxels is always turned on. If I recall correctly, only when it is turned on do meshlights light the scene, but now they can always when Voxel GI is turned on.

**Comment by Simonrazer** [comment]
Also in the Armory PBR nodegroup the emission color is ignored, while it has color when only an "emission" node is used. But even with only the "emission" node the color is shifted in hue, for ex. form red to yellow.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/495.
