### ISSUE TITLE
Spawn Scene does not work with rigid bodies

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#496]
Another blender test file. There are two scenes inside, "Scene" is the main scene:
![image](https://user-images.githubusercontent.com/33040347/36066937-9df95634-0eb3-11e8-82db-94805650cf60.png)

"Scene.001" should be spawned when the left mouse button is pressed.
![image](https://user-images.githubusercontent.com/33040347/36066947-b7d6ac82-0eb3-11e8-863f-a91cf9630b39.png)

"Scene.001" contains a rigid body only. When I execute and click the left button, execution stops with this error message:
![image](https://user-images.githubusercontent.com/33040347/36066954-d66472f6-0eb3-11e8-8ae7-f106602d2d13.png)
[spawnscene.zip](https://github.com/armory3d/armory/files/1713780/spawnscene.zip)

**Comment by luboslenco** [comment]
Very nice. Testing a fix at https://github.com/armory3d/iron/commit/dc504cc16655ff61ffd456268abb17710918ca8b and https://github.com/armory3d/armory/commit/9dca209d7743855b21eda6500bb30838b22517a7. Armory tried to wrongly re-instate physics world when the second scene was added, should no longer happen.

**Comment by donalffons** [comment]
Works like a charm now 👍
