### ISSUE TITLE
Ray-traced GI problems

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#498]
It seems like this option does not have any effect on the visuals, so an example where a change is visible would be neat, and everything looks broken when there is something that could reflect meshobject with emission in the scene.

**Comment by luboslenco** [comment]
I think the problem may be that the effect is toned down. Using strength=4.0, steps=64 seems to work.
![capture](https://user-images.githubusercontent.com/3685704/38167321-ab206e50-3533-11e8-95c7-b44adc775a0a.PNG)
