### ISSUE TITLE
Suggestion: include materials with fake users

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#499]
One thing that I noticed during using Armory is, if the material is not attached to any object, it will not be compiled even if I have added a fake user to it 
Since I am loading some materials dynamically during run time, they are not attached to any objects. For these cases, currently I have to add a dummy object to ensure the material get compiled.
So here is my suggestion: _Force materials with fake users to be included when building._

/Milo

**Comment by luboslenco** [comment]
Patched! https://github.com/armory3d/armory/commit/80737797d4dea73482f058a769b2551ea8ee8b4a

**Comment by MLHX** [comment]
That's great!
