### ISSUE TITLE
example first person error

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#50]
![5](https://cloud.githubusercontent.com/assets/23359603/20313619/27f4a82e-ab60-11e6-9b12-379338268f70.png)
![6](https://cloud.githubusercontent.com/assets/23359603/20313620/282845d0-ab60-11e6-8222-8659b7df14a8.png)

**Comment by KosLooney** [comment]
The rsplit function expects to find a "\"(on Windows) in the filepath:
`return s.rsplit(os.path.sep, 1)[1]`

For now you can place the checker texures in a subfolder:
![image](https://cloud.githubusercontent.com/assets/18315413/20365621/d7839d44-ac47-11e6-8305-3048dac01117.png)
