### ISSUE TITLE
Adding a single bone to a mesh leading up to three different problems.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#502]
[untitled3.zip](https://github.com/armory3d/armory/files/1718383/untitled3.zip)

Hello. 
Now that Armory can have animated characters if they are exported from mixamo, this past weekend I began a serious 48h fight with the engine with this though in mind: 'If mixamo rigs works, mine can too'.

I was destroyed.
==================================
So before  doing more tests, I have thought in doing a simpler approach: 
To simply add a bone to a cube, and add an animation to see what happens. (Deconstructing the problem in smaller steps).

At this moment, this is what I have tried.
Test1. Default cube. One bone inside of it. Detached. Render. No problem.

Test2. Default cube. One bone inside of it. Attach the cube to the bone. Automatic weighs. Render. No problem.

Test3. Default cube. One bone inside of it. Attach the cube to the bone. Automatic weights. 1 Keyframe LocRot added. Render. -----------> This can lead up to three different issues.

Possible issue 1: The cube gets rendered. But displaced in space. (File attached, please observe the difference of the location between the box seen from within the viewport and the box when the scene is rendered (F5). When in viewport you must see the scene from inside of the placed camera to see the differences. Those differences didn't happen in test1 and 2).
Possible issue 2: The cube is not rendered at all. I think there is a similar bug reported, but in the example reported by donnalfons, there was some parenting done to a pair of cubes. I just want to point that maybe is the same. Maybe not. In my case, there is no parenting to a couple of cubes. Just one. In my case you dont need the cube moving. Just adding one single keyframe creates the problem.
Possible issue 3: Krom.exe has stopped working. Renderer crashes and closes.

I don't know exactly how to reproduce the problem, to achieve the results of issues 1, 2, or 3. It seems aleatory. When the third issue happens, I need to fully delete all the .blend files, and extra folders created by Armory to make the renderer work again, therefore, I have deleted all the stuff, and last time I have repeated the test, It has resulted in the issue 1, which I am providing. If I manage to obtain issues 2 and 3 
 again I will provide example files.

=================
And still, I don't know why mixamo rigs works and mine's not.

Hope this helps. Keep fighting!

**Comment by f-rank** [comment]
Also got this with a rigged character and thought I had messed something up, the object was displaced, actually in a comical way when rendered but everything looked ok in the 3D view.

**Comment by RNavega** [comment]
Does it make a difference if you set the skinning mode to CPU, GPU DUAL-QUATERNION or just GPU?

**Comment by ja-moli** [comment]
RNavega. Sir, you must be something like an angel sent by God.
I didn't knew about these options, but changing to GPU only method is giving me some good results when creating my very own character animations for the first time in my life with Armory (but it doesn't fix the problem mentioned with the example with the cube above displacing the cube in the renderer, you can try)
Anyways, i will keep exploring those options and seeing what happens. If I manage to produce some character animation thanks to that option, I will be making my next videotutorial about that. Thanks. I hope this gets better and better with every patch.

**Comment by zicklag** [comment]
You also might be able to gather some helpful info from this [armory example](https://github.com/armory3d/armory_examples/tree/master/animation_sword). It has a fully animated character in it. I haven't looked at how it is setup but it works perfect on my computer ( though I haven't tried it with the Krom backend, I'm not sure if that makes a difference ).

**Comment by RNavega** [comment]
If there's still a transform problem I would try playing around with clearing transforms and clearing the mesh -> Armature parenting.

Some possible causes (outside of it being a bug):
The Armature object (not the bones themselves, but the Armature object containing them) has its own transform. I would try Alt + G, Alt + R and Alt + S to clear that, and do the same for the mesh.

I would also try unparenting the mesh from the armature. That's a Blender convention anyway, it makes no visual difference. Then see if the export still shows the problem.

Lastly, if nothing else works: with the mesh parented to the armature like usual, selecting the mesh and doing Alt + P -> Clear Parent Inverse to see if that does anything to the export.

**Comment by ja-moli** [comment]
I can confirm that Issue 2 happens because Armory seems to have some problem with location, rotation and scale. When made an 'apply location', rotation and scale (ctrl+a), to the cube, it gets rendered. The problem now is that if you animate with it a simple move forward, cube remains still when rendered. I will record videos with the issue later.

**Comment by ja-moli** [comment]
Here is the video describing my last comment.
https://youtu.be/74VsmaHmrlk

I hope this can be fixed. If Armory can't animate a single cube...

**Comment by StrayEddy** [comment]
Big issue yes. Can't animate a simple custom character...that's bad news for me, real bad news

**Comment by zicklag** [comment]
I have been able to get rigs to work with character meshes in Armory. I've been able to just borrow the rig from the [animation_movebone](https://github.com/armory3d/armory_examples/tree/master/animation_movebone) example and add my own mesh to it in the past. I haven't done it very recently, but it should be possible to get it to work.

**Comment by N8n5h** [comment]
I know that this is a bit old, but I did some tests and I was unable to reproduce the issue with the latest version of Armory and Blender 2.81 following the steps of the OP in a more streamlined way: https://streamable.com/cghhw

Can you try to reproduce the issue in the latest version of Armory/Blender?

**Comment by knowledgenude** [comment]
Reopen if the issue stills :+1:
