### ISSUE TITLE
"Ocean" modifier not working correctly

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#506]
After and while an "Ocean" modifier was used, all planes which intersect with 0 on the Z axis (just tested with planes) but the one that has the modifier on it are being used as places to show the beautiful ocean.

**Comment by luboslenco** [comment]
Ocean setup is now simplified and checking `Armory Render Path - World - Ocean` is enough to enable it. It is still drawn at Z=0 and only where objects are drawn though, will add more parameters in the future.
