### ISSUE TITLE
Environment texture not working (in Tutorial 4)

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#507]
In Armory_Examples, tried to run tutorial 4, failed with the following error:

![screenshot from 2018-02-14 09-07-07](https://user-images.githubusercontent.com/17811339/36182876-ac4e7326-1166-11e8-8b88-d882d3989490.png)

/Milo

**Comment by luboslenco** [comment]
Looks fine now but this issue seems to pop up every once in a while.. will keep an eye on envmaps.

**Comment by MiloHX** [comment]
@luboslenco 
I just had more test with the newest build. I still get this error in Linux, while Windows works fine.

**Comment by luboslenco** [comment]
@MiloHX any luck with 0.4 build on Linux?

**Comment by MiloHX** [comment]
@luboslenco can confirm it works now! case closed.
