### ISSUE TITLE
when there is object with translucency and there is no lamp in the scene, game will fail to start

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#508]
(1) Created a scene with an object with Armory PBR with opacity < 1.0 and no lamp
(2) Run it, it failed with the following error:
![screenshot from 2018-02-15 16-05-39](https://user-images.githubusercontent.com/17811339/36246309-203c59fc-126a-11e8-9ce0-3e6bdb86815e.png)

[Translucency.zip](https://github.com/armory3d/armory/files/1726766/Translucency.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/2549f91ec6975a1c7b931ac087d8ddf6c0c8aa4b. The problem is that translucent objects are only lit by direct light as of now, so they will not get rendered in scene with no lights. But at least it will not crash now.

**Comment by MLHX** [comment]
Great, tested OK.
