### ISSUE TITLE
Debug with Krom failed in Kode Studio (Linux)

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#509]
Try to debug any project with Krom in Kode Studio on Linux, got the following errors:
![screenshot from 2018-02-15 21-08-04](https://user-images.githubusercontent.com/17811339/36260549-ba00a0a2-129c-11e8-905d-3abdd55e360a.png)

/Milo

**Comment by luboslenco** [comment]
Sadly only HTML5 debug works in Kode Studio as of now. 😢 But hopefully that will change.
(Merge with https://github.com/armory3d/armory/issues/242.)
