### ISSUE TITLE
Materials, metallic = black

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#51]
Trying to figure out how to create proper maps which work as expected in Armory. However metallic map causes the metallic parts of object to turn black. This is using a generic metalness/roughness flow in Quixel 2.0. Perhaps I'm using the wrong workflow when creating the textures, what is the correct workflow to use?

**3DO/Toolbag2 renderer in Quixel**
![3do_toolbag2](https://cloud.githubusercontent.com/assets/9007314/20370409/d4f9cf82-ac5e-11e6-8c80-a16508c54abd.png)

**Armory with the metallic map enabled**
![amory3d_with_metallic](https://cloud.githubusercontent.com/assets/9007314/20370420/ec90de92-ac5e-11e6-9e20-59b8f341687d.png)

**Armory without the metallic map enabled**
![amory3d_without_metallic](https://cloud.githubusercontent.com/assets/9007314/20370431/f9005d4c-ac5e-11e6-8312-f3de3943a3b7.png)

**Material in Blender**
![blender_material_setup](https://cloud.githubusercontent.com/assets/9007314/20370439/005b6e2e-ac5f-11e6-843f-c3332ed98f0f.png)

**Metallic map**
![metallic_map_1024](https://cloud.githubusercontent.com/assets/9007314/20370446/07623dba-ac5f-11e6-99fb-94f3cec97b14.png)

**System info**
Tested in Arch Linux with p02 build as add-on, and with p02 build in Windows 8.1.

**Comment by luboslenco** [comment]
Setup looks good to me. My first guess is that there is no radiance map which causes black reflections. 

Can you try to place environment map into world nodes, or just check if 'sky radiance' is enabled in world data - armory props? (I should probably enable that by default, want to get rid of that settings altogether. Problem is radiance maps need textureLod() shader function which is not available on very old hw).

**Comment by guzzard** [comment]
Yes, that was the problem! Thanks!

Hmm.. I seem to have some issues still though with roughness.. have to turn it up to 2.0 to get the correct metal look, but at 2.0 the rest of the model is too rough.. will test some more and open another ticket if i think it's an issue.

**Comment by luboslenco** [comment]
Would definitely love to hear more about it, we can tune the values internally to match the 'expected' look based on some reference.
