### ISSUE TITLE
canvas .blend file doesn't render

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#510]
Hello. 
In the main announce of the Armory v.0.2, 
it is stated you can use the example, https://github.com/armory3d/armory_examples/tree/master/ui_canvas
to study user interface.

I cannot render the scene. 
When I load it up, and press f5, first says 'Build failed, check console'
Then the consoles shows this line
'Type not found : arm.CanvasTrait'

This didn't worry me at all, since most examples gives this error. I always fix it by going to Panel(the panel depends on the example)>Armory Traits>And deactivating the 'class', which at that moment is in red.

However, when I do this in this example file, and I press f5 again, it gives error. 
Krom.exe has stoped working.

The console says all this.
![canvas error](https://user-images.githubusercontent.com/12383027/36276358-f560a21e-128d-11e8-9898-ddd67740d961.jpg)

Hope this can be fixed.

**Comment by AFWSI** [comment]
I played around with this the other day with no issues. You must be doing something wrong for it not to work.

**Comment by luboslenco** [comment]
Heyo, looks like armory has trouble locating the project sources. Did you get all of the files placed alongside the .blend located at https://github.com/armory3d/armory_examples/tree/master/ui_canvas?

The whole pack can also be downloaded at https://github.com/armory3d/armory_examples/releases. It should be enough to extract this archive and then just open & run blends inside.

**Comment by ja-moli** [comment]
Thankyou. I was very accustomed to simply download the blend file and open it up when looking for examples. Now it works.
