### ISSUE TITLE
rigify animation broken

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#513]
i create walk cycle with rigify but something strange happen when i hit f5 
![13](https://user-images.githubusercontent.com/23359603/36339307-0946d30a-13cb-11e8-92b5-cd6556f3db0c.png)
![15](https://user-images.githubusercontent.com/23359603/36339319-35ef286c-13cb-11e8-95d4-110d053f3206.png)
![16](https://user-images.githubusercontent.com/23359603/36339320-3978f9f4-13cb-11e8-9594-9cc2973a9cfd.png)
@luboslenco  Do you find the solution

*(optional - drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Heyo, do you still have the .blend?

**Comment by Xristoskr** [comment]
yes but i want to send it via email because is private

**Comment by Xristoskr** [comment]
Did you receive it ?

**Comment by luboslenco** [comment]
Continues at https://github.com/armory3d/armory/issues/972.
