### ISSUE TITLE
Batch Meshes breaks level of detail

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#515]
While level of detail is generally working, e.g. if I start a new scene, it is not working with this particular test scene: 
[City2.zip](https://github.com/armory3d/armory/files/1734803/City2.zip)

![image](https://user-images.githubusercontent.com/33040347/36353184-6953b2d8-14c3-11e8-806f-456735149049.png)

Also, I experienced some more or less random crashes with this scene.

**Comment by donalffons** [comment]
...and also: when I enable 'Debug Console', I get the following error messages:
![image](https://user-images.githubusercontent.com/33040347/36353713-ffb7b62e-14c9-11e8-8537-4bad83874a96.png)
![image](https://user-images.githubusercontent.com/33040347/36353714-078d9b34-14ca-11e8-99b7-c2e295f1f5c5.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/3878a29e5f662784c4c3abded53e0d54fd4257b6.
