### ISSUE TITLE
black artifacts on tessellated displacement

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#516]
There are very ugly black artifacts/100% black shadows, I don't know if they are just broken shadows, on objects with tessellated displacement. Textures too big to fit in here, so a download-link to a demonstrative .blend: https://drive.google.com/file/d/17mRbDbQAxdF1jyLZfmDUeeLhX8CpnuBz/view?usp=sharing
use f+g to move the lamp, on the rock material it is the most apparent

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/abbf8aae045744012b4d3a107f6b7d7324c34804.
