### ISSUE TITLE
Animation bug if only animating one axis with more than two keyframes

### ISSUE THREAD

**Issue by lassipe** [armory3d/armory#518]
Example .blend is attached. 

Only Z axis is animated (which is extremely useful in many cases). Right cube has 2 keyframes and works correctly, left cube has 3 keyframes and jumps down random amount at the end of each animation cycle.

Armory 0.2 official windows build.

[animation_bug.zip](https://github.com/armory3d/armory/files/1737491/animation_bug.zip)

**Comment by luboslenco** [comment]
Appears to be ok now in 0.4.
