### ISSUE TITLE
Empty scene cannot be played after commit 5c33d3b

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#519]
(1) Create empty scene with only camera
(2) run it, failed:
![screenshot from 2018-02-20 09-44-13](https://user-images.githubusercontent.com/17811339/36403900-a9bd99a0-1622-11e8-9ff1-3271c6f6fb8b.png)
/Milo

**Comment by luboslenco** [comment]
This should do https://github.com/armory3d/armory/commit/5d219a258618e5b4c5322127c2ce9548bcec83d1.

**Comment by MLHX** [comment]
It works now!
