### ISSUE TITLE
Exception when trying to use height map

### ISSUE THREAD

**Issue by guzzard** [armory3d/armory#52]
Got this error message, and project fails to start in play mode (black screen).

[8864:1117/210018:INFO:CONSOLE(26673)] "Uncaught Error: Could not link the shader program:
Varyings with the same name but different type, or statically used varyings in fragment shader are not declared in vertex shader: te_texCoord", source: file:///E:/Armory/projects/test01/build/html5/kha.js (26673)

Height map settings, displacement and shadows at default (14/7)

**Comment by luboslenco** [comment]
Fixed.

Height maps will not render on HTML5 target though, as no tessellation is available there yet.
