### ISSUE TITLE
 Scene with Rigidbody enabled objects failed to play after 5c33d3b

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#520]
Any Scene with Rigidbody object failed to play after 5c33d3b:

![screenshot from 2018-02-20 10-01-32](https://user-images.githubusercontent.com/17811339/36404354-1c226884-1625-11e8-8dcf-f783b0ac8211.png)

**Comment by luboslenco** [comment]
Fixed (https://github.com/armory3d/haxebullet/commit/8b58d94e0f267204f52da898b97db57e4f0211b7), thanks for notice!
