### ISSUE TITLE
Emission issues

### ISSUE THREAD

**Issue by Gerkinfeltser** [armory3d/armory#521]
Armory's PBR material seems to ignore the Base Color when Emission is turned on. Even when Armory PBR group is entered and Emission node's output is routed directly into the Group Output's Surface input, color is not passed.

Attached blend's game toggles an Armory's PBR material with Emission set to 1.0 to a standard Cycles Emission material with roughly the same settings.

Cycles Emission:
![blender_2018-02-20_17-16-45](https://user-images.githubusercontent.com/1477787/36452631-4ee69e64-1663-11e8-9095-158bf88a675c.png)

Armory PBR Group:
![blender_2018-02-20_17-16-28](https://user-images.githubusercontent.com/1477787/36452634-528ef926-1663-11e8-93af-0ddb570ad3b3.png)

![blender_2018-02-20_17-17-16](https://user-images.githubusercontent.com/1477787/36452638-5709828c-1663-11e8-9313-71ed322299e5.png)

![blender_2018-02-20_17-17-48](https://user-images.githubusercontent.com/1477787/36452644-5a52d826-1663-11e8-9d1e-576ed7518c66.png)

**Comment by Gerkinfeltser** [comment]
Here's the blend screenshotted above.
[armoryEmissionIssue.zip](https://github.com/armory3d/armory/files/1742130/armoryEmissionIssue.zip)

**Comment by luboslenco** [comment]
Some emission improvements have been made in recent releases, but will need to land raytracing features at https://github.com/armory3d/armory/issues/1268 for further improvements.
