### ISSUE TITLE
Level of detail does not work with this mesh

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#522]
For this test scene, I started off from the lod example and added my own mesh:
![image](https://user-images.githubusercontent.com/33040347/36478222-45b2b1b0-1704-11e8-8a05-491d18b7283c.png)

Suzanne's LOD changes as it should, but not my own mesh. There is no error message.

[lod.zip](https://github.com/armory3d/armory/files/1743835/lod.zip)

**Comment by donalffons** [comment]
...thinking out loud: The problem seems to be with the screensize / the MeshObject class. Screensize seems to be always 1, because transform.dim is measured, including the origin point.
![image](https://user-images.githubusercontent.com/33040347/36643683-7c09de20-1a4f-11e8-86b0-9d784ccb05b0.png)

And transform.dim seems to be set using object.raw.dimensions.
![image](https://user-images.githubusercontent.com/33040347/36644404-3414a1ee-1a5a-11e8-8009-96c82139ea4d.png)

I think it would be better to calculate the screensize without considering the point of origin.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/b3ab78765343b153a434a4c276221ca0b0313997.
