### ISSUE TITLE
Html5 dynamically switch shaders/renderpath based on platform?

### ISSUE THREAD

**Issue by nassosyian** [armory3d/armory#524]
Is it possible to switch shaders/materials and/or renderpath based on 
whether a platform (iOS/Android/Desktop) 
supports certain optional WebGL features like EXT_draw_buffers or OES_texture_float?

iOS is famous for not supporting EXT_draw_buffers and since it has a big market share
i was wondering if there was anything one could do to detect features on load and make the appropriate changes.

thanks in advance

**Comment by luboslenco** [comment]
Still in the works..right now some custom JS would be needed to load different version manually.

**Comment by luboslenco** [comment]
Putting the built-in switch on hold for now, hoping to get around the extension madness with [webgpu](https://en.wikipedia.org/wiki/WebGPU) in the future.
