### ISSUE TITLE
Total Omni shadow wierdness

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#527]
Pointlamps can only have soft shadows if "Omni" is turned off. I think the tradeoff is ok, but it is really confusing if the user doesn't know that.

**Comment by Simonrazer** [comment]
At least it is in the softshadow example like this, selfmade it is even stranger

**Comment by Simonrazer** [comment]
Ok, it seems like in the softshadow example if I make the spotlamp a pointlamp it can make shadows, and even soft ones if Omni is turned off. 
Everywhere else, even with the same lamp settings the pointlamp can't even produce any shadows if Omni is turned off. 
But it makes a slight difference if the lamp has been created as Spotlamp and the made a pointlamp, then it has a bit of shadow.

**Comment by luboslenco** [comment]
Removed the omni checkbox, point lamp is now always omni. The checkbox was from the past when armory did not support cubemap shadows. Spotlamps with high `Size` can be used instead when one direction is enough.
