### ISSUE TITLE
Normal map screws with shadow

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#528]
Alonside with not cooperating with "Texture Mapping" node, sometimes making the model appear black, throwing sometimes an error which I can not replicate anymore, Normal maps seem to screw with the lightning of objects. In this case the textured thing is darker on a part that is very exposed to the sun, while it works on another part.
[normalbug.zip](https://github.com/armory3d/armory/files/1756033/normalbug.zip)

**Comment by luboslenco** [comment]
I think the textures are missing.:(
