### ISSUE TITLE
WebGL 2 support

### ISSUE THREAD

**Issue by llim1** [armory3d/armory#53]
Chrome opens, black screen, whole chrome window flashes black for a second and then returns to toolbar + black screen. Pressing f12 in chrome, console shows this: 
![capture](https://cloud.githubusercontent.com/assets/7635369/20459113/95043e9e-ae84-11e6-804a-fd6aa1123b22.PNG)

Usually restarting Armory/Chrome/Whole computer solves the issue but it's persisting this time. Deleting khafile, build, and sources and rebuilding doesn't fix it. Using deferred_path_high with HDR lighting. Build completes with no errors.

**Comment by luboslenco** [comment]
Hi,

Can you try to run it in lower resolution and see if that helps? (lowering *Render panel - Dimensions - Resolution* should also do the trick). If it does then my first guess is that deferred_high is placing too much pressure on WebGL and in turn the context is lost to prevent hanging the browser. Does it work with non-high *deferred_path*? Will investigate further based on your findings.

**Comment by llim1** [comment]
Running at 960x540 still produces the same results. Also tested with forward low, deferred, deferred low, and hybrid. Oddly enough, removing object 'armory_high_textured_1pc.004' from the scene will allow it to display just fine on deferred high and 1080p. Also, keeping the object in the scene but removing all textures works fine too. Haven't been able to get any more specific than that. I've attached the blend file with textures (108mb, gun_test4) and one without (19mb, gun_test5) if bandwidth is an issue. The model is rather high poly but that was not an issue in the past, as it was working not even 2 hours ago!

http://bit.ly/2eSlijf

**Comment by zauberparacelsus** [comment]
108mb with textures, and 19mb without?  How many textures are you using, and at what resolution are they?

**Comment by luboslenco** [comment]
@llim1 Nice, that sounds like a good sign. Will check the blend, thanks!

**Comment by llim1** [comment]
@zauberparacelsus 4K textures from substance, not worrying about file sizes right now haha. Also 22mb HDR. Haven't gotten around to splicing similar textures together (diffuse, normal etc) A lot of wasted space actually. Possibly some doubles from testing..

**Comment by luboslenco** [comment]
Hm, I downloaded textured version *gun_test4.blend*, hit Play in browser and it seems to work for me. Hate when that happens. If possible, can you also upload your *build/html5* folder? The size of that folder is 80.6MB here.

**Comment by llim1** [comment]
Uploaded it to the same folder, the previous link should work. If it doesn't, here's a direct one: http://bit.ly/2g5XJj6 (80.8MB)

**Comment by luboslenco** [comment]
Somehow it still works here. Are you on Chrome 54+? If you have Firefox handy, does that also fail? Will it work if you split the high-poly mesh into two parts? It shouldn't be an issue though. I will try on another machine tonight.

**Comment by llim1** [comment]
Chrome version is 54.0.2840.99 (official build). Firefox works fine, latest version. I also found out that removing any the 'grip' object will also allow the scene to render on chrome. Connecting _only_ the Base Color texture will render fine, but adding any other texture throws the context out the window. Very odd, I'm beginning to think it's something with my chrome installation. Splitting the mesh into 2 doesn't work either. Will try re-installing chrome and seeing if that helps.

**Comment by luboslenco** [comment]
It is odd indeed, maybe Chrome is caching things in some crazy ways, but probably not. I encountered this myself too in some cases, browsers are just not fun at times.

Now that WebGL2 is slowly rolling out for real this should be hopefully getting better. With WebGL2, lots of extension stuff will finally be standard. Will also ensure Armory does no harm in this regard if anything gets discovered.

**Comment by llim1** [comment]
Tried reinstalling chrome with no avail. I'm moving onto bug-testing native builds since that's the direction I planned on using Armory anyways. Well, openVR implementation specifically. Figure we should keep the issue open until WebGL2 is fully released for anyone else having a similar issue. Thanks for the help!

**Comment by luboslenco** [comment]
Kha/Armory now runs WebGL2 by default.
