### ISSUE TITLE
[Featrue Request] UI Canvas Editor: UI Scaling (similar to ArmorPaint)

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#531]
Since ArmorPaint now support UI Scaling, it is much appreciated that this feature could also be implemented in UI Canvas Editor.

/Milo

**Comment by luboslenco** [comment]
There is now a `UI Scale` option In armory add-on preferences, which will scale up the ui editor. Needs 0.3 + latest git (armory updater should do!) The canvas being edited will not get scaled up yet, will fix that by adding zoom.

![capture](https://user-images.githubusercontent.com/3685704/38167858-fbbc22be-353d-11e8-81b2-445eaaad5b87.PNG)
