### ISSUE TITLE
Set scene nodes not traveling properly between scenes.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#532]
[Alpha.zip](https://github.com/armory3d/armory/files/1767135/Alpha.zip)

Hello. 

I have studied game_bowling example, and I am applying what I have seen there.
I want to create a small intro made of static images.
In this intro, 'Button next' takes you to next static image, and 'button prev' takes you to previous static image.

I am using 'set scene' nodes to achieve that.

The problem is that, while everything seems to be ok in the logic node's code, Armory doesn't travel across scenes well.

If we render the project as is, it goes  --------------> Scene intro, scene1, and scene 2. Then it cannot travel from scene2, to scene 3.

If we set the scene on scene 2, then it goes ------------> scene2, scene3.  And from scene 3, we can travel back to 2, and 1. But once in 1, if we press next, it doesn't go to 2, it goes directly to 3.  

So it seems that there is something in scene1 that is provoking any error.

I hope you can fix this.

**Comment by ja-moli** [comment]
I've managed to have it working.
It seems Armory cannot handle UI on the scenes, if all the events have the same name. I mean, the scenes are different, and the UI canvas traits too on every scene, but if you enter inside the canva's traits, I have set all the buttons to have the same event name. I have repeated the work, but inside every scene, I have renamed the event's names with different names. Then it works as wanted.

**Comment by luboslenco** [comment]
Should be resolved using https://github.com/armory3d/armory/commit/f456cc9c0229903008c4c87faad3c475a3efb4a2.

**Comment by ja-moli** [comment]
What? Who?
Artist alert! Artist alert!
I'm not a programmer. I don't understand that sir!
You mean that is a fix that will be included in next version ....¿?

**Comment by Naxela** [comment]
Yes, it's available from next version, but you can also get it now by updating the sdk through git:
See: [http://armory3d.org/manual/#/dev/gitversion](http://armory3d.org/manual/#/dev/gitversion) for more info if you want the fix right away :)

**Comment by luboslenco** [comment]
Also out now in 0.3. 😃
