### ISSUE TITLE
Get location comparison with gate never equal

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#534]
If you compare two objects' locations with the gate node it never outputs when they are equal, even though they are.

**Comment by luboslenco** [comment]
This can be tricky due to floating point inaccuracies. Something like this should be more reliable:
![capture](https://user-images.githubusercontent.com/3685704/36907156-22d4fcf8-1e38-11e8-95cb-a3d75fb70f89.PNG)

**Comment by Simonrazer** [comment]
thanks, this could do the thing I want. I mean it even doesn't say equal if the 2 objects have the same position in Blender and no Rigidbody attached.

**Comment by MadMinstrel** [comment]
Float comparisons come up a lot in 3d and many people aren't aware of float precision issues. A general built in float gate/compare node with an accuracy setting would be a nice usability boon.

**Comment by luboslenco** [comment]
Added 'Almost Equal' to Gate node in https://github.com/armory3d/armory/commit/7f728d78b24a9fd016dfc33c9f1c8fba6fa58c14.

![capture](https://user-images.githubusercontent.com/3685704/40853537-b9d4a0c6-65ce-11e8-95ed-e797e7869b97.PNG)
