### ISSUE TITLE
main.hx present but got "Type not found : armory.data.Config"

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#535]
Hello,
I tried my first build on Windows using Armory as Add-On.
NVidia GTX 970, Windows 10 Entreprise, Armory 0.3.0 (git)

Using E:\armory\armory_ci\test1\untitled .blend
When I hit Play i get:
```
...
Compiling shader 8 of 8 (painter-video.frag.glsl).
E:\armory\armory_ci\test1\Sources/Main.hx:39: characters 12-18 : Type not found : armory.data.Config
E:\armory\armory_ci\test1\Sources/Main.hx:40: characters 21-27 : Type not found : armory.data.Config
E:\armory\armory_ci\test1\Sources/Main.hx:49: characters 8-14 : Type not found : armory.object.Uniforms
E:\armory\armory_ci\test1\Sources/Main.hx:60: characters 40-73 : Type not found : armory.trait.internal.SpaceArmory
E:\armory\armory_ci\test1\Sources/Main.hx:62: characters 46-52 : Type not found : armory.renderpath.RenderPathCreator

Done.
Finished in 2.6811563968658447
Build failed, check console
```
I zipped main.hx and the blend file.
[untitled.zip](https://github.com/armory3d/armory/files/1768862/untitled.zip)
[Main.zip](https://github.com/armory3d/armory/files/1768836/Main.zip)
Thanks!

**Comment by luboslenco** [comment]
Heyo,

Looks like some non-complete SDK issue, it's unable to locate the armory sources located in this repository. Can you tell me more about your setup? Is this Armory from itch or cloning yourself? If you are cloning yourself, did you clone complete sdk from https://github.com/armory3d/armsdk?

**Comment by j2l** [comment]
Thanks Lubos for replying quickly and your great tool!
You spot it, I cloned it myself. 
Thanks for your detailed reply, it works now.
I understand and respect your business decision, but I don't have 50$ to pitch in the dark right now. I need to test html export limitations with my other components (mostly mobile web viewer) before considering buying it. If you have a complete html demo somewhere (with player's controls, shaders, ...), I'd love to test it :)
