### ISSUE TITLE
PBR in html?

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#537]
In addition to not seeing the cube dropdown (browser initiates the viewer while dropping the cube, is there a way to defer action until it initiates?)

I noticed that my glass Cycles Material is not showing in krom and browser.

![armory glass issue](https://user-images.githubusercontent.com/65325/36848405-70a7a462-1d61-11e8-844b-6afe3f8d6819.PNG)

Here are the nodes:
![image](https://user-images.githubusercontent.com/65325/36848606-0d1cb8dc-1d62-11e8-89f8-c34ba2fba2f3.png)

**Comment by j2l** [comment]
Oops, just noticed the PBR node opacity.
Well I hope we could get other materials in the future :)
Feel free to close this one once it's read.

**Comment by j2l** [comment]
Removing occlusion from PBR make it work 
But opacity, metallic, normal map, roughness are not showing.

**Comment by luboslenco** [comment]
Any chance you still have .blend file around? 👼

**Comment by j2l** [comment]
I made many tests in generic files (test, test1, ...) and don't remember if I saved this non-working project sorry. 
But if I stumble on it I'll let you know.
