### ISSUE TITLE
vr_dino broken

### ISSUE THREAD

**Issue by j2l** [armory3d/armory#538]
Testing the vr_dino example with my Vive in Chrome (not working in FF for unknown reasons), I end up with:
![image](https://user-images.githubusercontent.com/65325/36895077-de0fbfa6-1e0d-11e8-98a7-34a9bf62569e.png)
VrInterface.hx errors (I can't find it).

EDIT: waiting 5 mins shows something appearing:
![image](https://user-images.githubusercontent.com/65325/36895338-d5ae4566-1e0e-11e8-9e02-7ab07053d807.png)

**Comment by luboslenco** [comment]
Link to issue https://github.com/armory3d/armory/issues/1034.
