### ISSUE TITLE
Voxel GI and Raytraced GI causes problems with emission objects

### ISSUE THREAD

**Issue by Naxela** [armory3d/armory#539]
It seems that having both Voxel GI and Raytraced GI turned on at the same time causes problems with emissive voxels. Voxel GI + other SSGI options works fine though.

With Voxel GI + SSAO:
![voxel_gi_with_ssao](https://user-images.githubusercontent.com/5429817/36911356-95c46d74-1e43-11e8-8083-33ff0fe528f1.jpg)

With Voxel GI + Raytraced GI:
![voxel_gi_with_raytracedgi](https://user-images.githubusercontent.com/5429817/36911396-b72c9676-1e43-11e8-8a14-43313e82b1e8.jpg)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/521.
