### ISSUE TITLE
Viewport

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#54]
Hey i run viewport and then close blender without stop viewport but the view is continue and must restart pc to stop this ( addon version win 10)

**Comment by luboslenco** [comment]
Uh! Working on [new player](http://forums.armory3d.org/t/news-on-build-3/95), should no longer happen in the next build.

**Comment by Xristoskr** [comment]
Thanks for reply i will try it next build 
Ps when it comes

**Comment by luboslenco** [comment]
No prob - sorry for troubles.
Ps: End of next week if I don't sleep too much. 😈
