### ISSUE TITLE
[Cloth Physics]Pin option doesnt' work if object has been scaled.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#541]
Hello. I have been practising with physics and physics examples. 
I've discovered that the pinning option doesn't work if the object has been scaled. 
I don't need to provide any blend file. Just use
https://github.com/armory3d/armory_examples/tree/master/physics_constraint

And then scale a little the plane. If you render, the pinned group doesn't work at all and the plane falls.
Hope you can fix. Greetings.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/874.

**Comment by DevMagicLord** [comment]
Pin does not work following this tutorial
https://www.youtube.com/watch?v=sqfGdDoGRlo
