### ISSUE TITLE
[Cloth Physics]Screen renders completly black if physics objects have several vertices deleted.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#542]
Hello. I am still playing with physics examples. 
I have discovered that the scene renders completly black if one object with cloth physics enabled (and a pin group added) has several vertices deleted. 
To replicate the bug, just use this scene
https://github.com/armory3d/armory_examples/tree/master/physics_constraint

And then select the plane. Go edit mode. Press ctrl+i, to invert selection. All vertices but the ones pinned will be selected. Delete them. 
If you now render, it renders black.

Why someone would want to do this, would you ask.
Well, let's say that for some physics in complex objects, you need only one line of vertices animated with cloth, as you can see in this example. 

https://blender.stackexchange.com/questions/41235/rig-that-reacts-to-gravity

**Comment by ja-moli** [comment]
Another way to replicate black screen whitouth plane.

Inside previous example. Create a box. Delete on the box all the vertices but 2 consecutives. We want an straight line of 2 vertices. Extrude 2 more vertices from an edge. We want a straight line of 4 vertices.
Apply cloth physics. If you render right now, still no problem. 
Select the first vertex. Go to group data panel. Apply a group to it. Go physics panel, add pinning. Select the previously group that is only 1 vertex, we just created. If we render now, it renders black.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/874.
