### ISSUE TITLE
Bloom is mirrored on the opposite side

### ISSUE THREAD

**Issue by Naxela** [armory3d/armory#543]
I've been spending some time messing around with shaders, and upon stumbling into a problem I noticed that the bloom shader seems to have the same effect, namely that the effect sort of bleeds unto the opposite side of the screen - is there someway to clamp the effect to the edge/border somehow when that occurs?

![bloom_bleeding](https://user-images.githubusercontent.com/5429817/36978107-c0e2a966-2083-11e8-8d57-f2f68f1b4bab.gif)

**Comment by luboslenco** [comment]
Hm, are you running armory 0.2 or git? Should be fixed on git hopefully (https://github.com/armory3d/iron/commit/28218a717a719686e6e2779361a7ab537672c69c).

**Comment by Naxela** [comment]
Ah, I realized I hadn't updated in a while and I missed that iron commit - Fantastic! :)
