### ISSUE TITLE
[Cloth Physics]Mesh following bones constrained to mesh with cloth phyisics not showing any animation.

### ISSUE THREAD

**Issue by ja-moli** [armory3d/armory#544]
Well. 
As I have previously said in 
https://github.com/armory3d/armory/issues/542

I'm making a lot of tests, trying to achieve this.
https://blender.stackexchange.com/questions/41235/rig-that-reacts-to-gravity

I have bypassed the error described in my previously said issue, using instead a straight line of vertices, a line of vertices with some width.

![phys](https://user-images.githubusercontent.com/12383027/37008628-538a3f04-20e3-11e8-939f-d00961fa0673.jpg)

Armory has not crashed then, with any of the previously described problems.  (Also, you must have the caution of NOT scaling the mesh, to not to happen which I described in my other post, not linked here).

I have then added some empties to the line, and I have added bones, constrained with Inverse Kinematics to the empties. When added another mesh to follow the bone's movement, the mesh just stay static in the final frame.
I have attached a blend file. You can observe differences when animating from from viewport, and animating when rendering with F5.

[test physics.zip](https://github.com/armory3d/armory/files/1783196/test.physics.zip)

EDIT: I'm aware that Armory still can't do IK. Still I wanted to post this, and I will revisit this issue to declare if in the following versions with IK support adress this issue or not. The goal is to provide characters with physic's clothes/hair throught bone chains, in real time.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/874.
