### ISSUE TITLE
Problem with Voxel GI and position of Objects

### ISSUE THREAD

**Issue by TaarSirion** [armory3d/armory#546]
I noticed that if you have objects below (0,0,0) that weird artifacts show up on the objects.
For example like these:
![armoryissue](https://user-images.githubusercontent.com/13316152/37084475-e9679d9a-21f2-11e8-8503-84be5ae26dad.png)

But if you but them above (0,0,0) the artifacts disappear:
![armoryissuefixed](https://user-images.githubusercontent.com/13316152/37084536-17577f7c-21f3-11e8-8b5a-81f093dda07b.png)

The artifacts seem to increase/worsen the lower one goes.

**Comment by ubaldy** [comment]
Would you be so kind as to leave a .blend file? This speeds up debugging the issue by over a factor of 10!

**Comment by luboslenco** [comment]
Looks like this is gone now.
