### ISSUE TITLE
Commented @prop is still treated as prop in blender

### ISSUE THREAD

**Issue by kevinresol** [armory3d/armory#549]
This still shows up as a parameter in blender UI (itch.io v0.2)

```haxe
// @prop
var speed:Float = 5;
```

**Comment by kevinresol** [comment]
I can see that currently it uses [simple string parsing](https://github.com/armory3d/armory/blob/5626003eadfba580d87db1b6ada7d0e58b25aa7b/blender/arm/utils.py#L186)

Maybe using a proper haxe parser is better: https://github.com/Simn/haxeparser

**Comment by luboslenco** [comment]
Yup, proper parser would be handy, especially if we add more stuff like `@prop`. Pushed a quick fix in the meantime https://github.com/armory3d/armory/commit/462af79e61e799ee57e9ebbef8804e54e5776ceb.
