### ISSUE TITLE
Name 'nodes' is not defined.

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#55]
I posted these on the forum but I wanted to have it on this list to ensure you have it marked as solved and also to get confirmation for myself that it is solved (perceived as solved). This should be the only post that is configured like this and future ones should be done one post per error. Please forgive this unusual format.

All of this took place on a Windows 7 SP1 64-bit Ultimate edition version with a custom computer and all AMD hardware. High level parts (including graphics card) were present.

Previous Errors:

Uncaught TypeError: Cannot read property 'length' of null

http://forums.armory3d.org/uploads/default/original/1X/b26da437998d51cb039868198f4ded6ec2148631.png 

TypeError: Cannot read property 'irradiance' of null (ect. in included log)

http://forums.armory3d.org/uploads/default/original/1X/eb83951f30c9033d57efbb5361a9bfed660c22c0.JPG 

FileNotFoundError (blender console errors both from same project. Pardon image quality due to strange capturing system at the time)

http://forums.armory3d.org/uploads/default/original/1X/b6b47af8c69ee48c37b151b3d6e1f9b7009d794c.JPG 

http://forums.armory3d.org/uploads/default/original/1X/dca0cb0bc09a7b72f3f4bb09e7522672ce26335e.JPG 

Excuse any inconvenience by this particular post. It is a one time affair.

**Comment by luboslenco** [comment]
Isn't this the same thing like this?
https://github.com/armory3d/armory/issues/39#issuecomment-261985760
If this is a different issue, blend file works the best so I can replicate it.

**Comment by George-the-1st** [comment]
That sent up a different error code so I thought it was a different issue. Two files are associated with these bugs. One of them is the simple file (found here: 
[simple.zip](https://github.com/armory3d/armory/files/604706/simple.zip)
which is associated with I believe one or two of the errors above and the second one is associated with my still being worked on cathedral file but I don't want to share that publicly just yet so I will instead share it with you personally using the messaging system on the forums. Please do NOT share these incomplete files. I trust you with this. You should find the second file by the time you read this message.

**Comment by luboslenco** [comment]
Hm, you are still using 'Armory PBR' in world nodes instead of sky(or hdr map, or nothing). Also do not use 'Arm' world in build 2. In next build that will work fine, but for now create a 'clean' world(there should be a default 'World' world in the scene, not sure if you deleted that).

![simple](https://cloud.githubusercontent.com/assets/3685704/20499590/5c7a88a8-b032-11e6-9e05-3e2893744506.jpg)

**Comment by George-the-1st** [comment]
I have some good news and bad news. The good news is that I am now capable of playing the simple scene. Yay. The bad news is that my pre-existing and more complex scene with the cathedral has this error that is thrown up when i attempt to run the render: 
![capture](https://cloud.githubusercontent.com/assets/15915424/20503272/d817d2ae-b00f-11e6-8461-d8164de461c4.JPG)

**Comment by luboslenco** [comment]
Should be now fixed.
