### ISSUE TITLE
Turn world to "off" in render path cause ghost effect

### ISSUE THREAD

**Issue by MLHX** [armory3d/armory#554]
(1) Turn world to "off" in render path;
(2) Run the game and move the camera, frame is not cleaned correctly:
![screenshot from 2018-03-16 15-07-49](https://user-images.githubusercontent.com/17811339/37507935-d359f60c-292b-11e8-816e-d9faf8bcfd3e.png)

Blend file:
[world_off.zip](https://github.com/armory3d/armory/files/1818231/world_off.zip)

/Milo

**Comment by MLHX** [comment]
I think this might be the expected behavior, since the world is not rendered so I should fill up the screen with objects. Feel free to close the issue if this is the case!

**Comment by luboslenco** [comment]
Yup, only set background to "Off" when it is completely occluded by geometry. Generally the best way is to keep it at "Clear" which fills it with color, or use "World" when envmap/sky should be rendered.

I have cleaned up the render path UI in the latest git, more docs on all of the toggles soon!
