### ISSUE TITLE
Type not found : BtTypedConstraintPointer with Git version

### ISSUE THREAD

**Issue by Devination** [armory3d/armory#555]
I followed the [instructions in the documentation](http://armory3d.org/manual/#/dev/gitversion?id=manual-clone) on how to manually clone Armory so I could make contributions to it. When I try to run any scene with RigidBody physics, I get the following error:

`D:\Armory02_win64\Armory\armsdk\armory\Sources/armory/trait/physics/bullet/PhysicsConstraint.hx:17: characters 9-33 : Type not found : BtTypedConstraintPointer`

Also, during the cloning process I skipped the `cd win32` part since Kha wasn't in there initially. Kha was in the armsdk/ directory with armory/ and iron/

**Comment by luboslenco** [comment]
Oh no I missed this. The simplest way now is to recursively clone the armory sdk:
https://github.com/armory3d/armsdk

This also fetches the latest Kha, Krom and libs (haxebullet) to prevent errors like this. In `Blender - User Preferences... - Add-ons - Armory`, point SDK path to the newly cloned armsdk.

The other (lighter) way is to use Armory Updater, which does `git clone` internally as well. So after updating, `Armory/armsdk/armory` and others will become git repositories.

And I will update the docs to reflect this.

**Comment by luboslenco** [comment]
New doc is up!
http://armory3d.org/manual/#/dev/gitversion
