### ISSUE TITLE
Crash in new baking tool

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#556]
1) New project - change Armory preset to Lightmaps
2) Add plane under cube
3) Add all objects to Armory bake (cube and plane)
4) Press Armory bake
5) When done, press apply in same section
6) Run in view-port (or play via Krome)

Crash!

**Comment by trsh** [comment]
7) Reopen scene
6) Run in viewport

No Crash, but scene only partly lightmaped

**Comment by luboslenco** [comment]
Screenshot, .blend, console output, anything helps. Note that the plane is a single-face geometry, it will not get baked from both sides.

**Comment by trsh** [comment]
@luboslenco 

Blend is default one when starting project..

Armory v0.3.0 ($Id: 779f2b146b510055bb5510bcd4638bc9d3f20757 $)
OS: win, Target: krom, GAPI: opengl
Exporting Scene
Armory Info: Writing E:\GAMES\Armory02_win64\kaka/build_untitled/compiled/Assets/unpacked/Plane_baked.jpg

**Comment by trsh** [comment]
With this one also > https://github.com/armory3d/armory_examples/tree/master/material_baked

**Comment by trsh** [comment]
Armory v0.3.0 ($Id: 779f2b146b510055bb5510bcd4638bc9d3f20757 $)
OS: win, Target: krom, GAPI: opengl
Exporting Scene
Armory Info: Writing E:\GAMES\Armory02_win64\Bake/build_baked/compiled/Assets/unpacked/Box_baked.jpg

**Comment by luboslenco** [comment]
Got it! I realize it is a default one, but seeing the exact blend state when the crash occurred is very helpful. Pushed a fix now, should perhaps no longer crash.

**Comment by trsh** [comment]
@luboslenco not crashing now, but had to create a fresh project.
