### ISSUE TITLE
Voxel GI mesh edges too bright (0.3)

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#557]
The edges of objects are bright than their faces which are directly pointed at the sun.
![bug](https://user-images.githubusercontent.com/30187223/37733698-3a4f85ea-2d49-11e8-9fb6-57ebff802392.JPG)

[giedge.zip](https://github.com/armory3d/armory/files/1835015/giedge.zip)

Btw, the new UI changes are awesome!!!! But why can you don't tick the box behind post-process and set it to "Off"? Is turning it off twice better?

**Comment by Simonrazer** [comment]
It worked in v0.2.
![bug](https://user-images.githubusercontent.com/30187223/37838582-94a52958-2eb8-11e8-9d7c-9c125ac812d1.JPG)

**Comment by luboslenco** [comment]
Will fix! 🔨 

Glad you like the new UI. I have further adjusted the labels a bit for more clarity. ie the first checkbox is to completely disable post-processing passes, and the second enum is to set anti-aliasing:

![aaa](https://user-images.githubusercontent.com/3685704/37839602-2251104e-2ebb-11e8-8656-72d24906e19a.PNG)

**Comment by luboslenco** [comment]
Bright edges should be gone now.
