### ISSUE TITLE
Batch meshes destroys mesh V0.3

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#561]
![batch](https://user-images.githubusercontent.com/30187223/37876596-fa1c88fc-304e-11e8-82f8-58732c140c68.JPG)
Performance improvement is about 25fps, but these meshes are broken. 
https://drive.google.com/open?id=1u3h6OSmYe-me7wVMPqK-D1AkQTdZ2S4j

**Comment by trsh** [comment]
@Simonrazer isn't this fixed? We are using Batch in our new example and 3.0. If so please close this issue :)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/bdb824c5e4783bf5e559166b73e7bef4d39eb2aa.
