### ISSUE TITLE
Voxel GI makes window Not responding (v0.3)

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#564]
With default New scene, on cube, etc.
No error in console.

**Comment by trsh** [comment]
Playing via Krom, my rig GTX 750 Ti

**Comment by trsh** [comment]
Windows 10

**Comment by luboslenco** [comment]
@trsh please use the edit button to minimize email traffic.  I need more details - the best way to debug is to compile to C++ and run in Visual Studio, that will spit out more info.

**Comment by trsh** [comment]
@luboslenco deal. Will do tmrw :)

**Comment by trsh** [comment]
@luboslenco 

I got stuck on building C++

E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/RenderPathDeferred.hx:189: characters 14-36 : Unknown identifier : getRenderCaptureFormat
E:\GAMES\Armory02_win64\Armory\armsdk\Kha\Backends\Kore/kha/compute/Compute.hx:57: characters 70-82 : Type not found : Float32Array
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:5: lines 5-466 : Defined in this class
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:328: characters 3-33 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:329: characters 3-33 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:330: characters 3-33 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:335: characters 4-41 : Class<kha.compute.Compute> has no field setSampledCubeMap
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:339: characters 4-41 : Class<kha.compute.Compute> has no field setSampledTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:368: characters 3-32 : Class<kha.compute.Compute> has no field setMatrix
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:378: characters 3-30 : Class<kha.compute.Compute> has no field compute

korefile found.
Creating Windows project files.
Done.
Finished in 14.472659587860107
Build failed, check console

**Comment by luboslenco** [comment]
Sorry, the compile error should go away using the new 0.3 build. 😈

**Comment by trsh** [comment]
Is this normal when compiling?

```
E:\GAMES\Armory02_win64\Armory\armsdk\Kha\Backends\Kore/kha/compute/Compute.hx:57: characters 70-82 : Type not found : Float32Array
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:5: lines 5-467 : Defined in this class
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:330: characters 3-33 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:331: characters 3-33 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:332: characters 3-33 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:337: characters 4-41 : Class<kha.compute.Compute> has no field setSampledCubeMap
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:341: characters 4-41 : Class<kha.compute.Compute> has no field setSampledTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:358: characters 3-32 : Class<kha.compute.Compute> has no field setMatrix
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:380: characters 3-30 : Class<kha.compute.Compute> has no field compute
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:394: characters 2-31 : Class<kha.compute.Compute> has no field setShader
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:395: characters 2-32 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:396: characters 2-44 : Class<kha.compute.Compute> has no field setTexture3DParameters
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:397: characters 2-39 : Class<kha.compute.Compute> has no field setSampledTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:398: characters 2-32 : Class<kha.compute.Compute> has no field setTexture
E:\GAMES\Armory02_win64\Armory\armsdk\armory\Sources/armory/renderpath/Inc.hx:399: characters 2-29 : Class<kha.compute.Compute> has no field compute
```

**Comment by luboslenco** [comment]
Are you sure you are running the latest 0.3 (non-alpha) build from itch.io?

**Comment by trsh** [comment]
@luboslenco will re-download, and report back shortly.

**Comment by trsh** [comment]
@luboslenco !

```
Falling back to the system's preferred mix format.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Uniform envmapStrength not found.
Starting application
GL Error 1280 e:\games\armory03_win64\armory\armsdk\kha\kore\backends\graphics4\opengl\sources\kore\computeimpl.cpp 231

GL Error 1280 e:\games\armory03_win64\armory\armsdk\kha\kore\backends\graphics4\opengl\sources\kore\computeimpl.cpp 231
```

This line keeps repeating until I kill the window.

**Comment by luboslenco** [comment]
Aha, progress! Hm, to narrow it down, can you try running this example?
https://github.com/Kha-Samples/ComputeShader

You will need to compile that manually, aka `node Kha/make -g opengl`

**Comment by trsh** [comment]
@luboslenco 

`GL Error 1280 e:\games\armory03_win64\armory\armsdk\kha\kore\backends\graphics4\opengl\sources\kore\computeimpl.cpp 430`

But I can see the red crazy triangle :)

**Comment by trsh** [comment]
@luboslenco 

as same happens with latest Kha and that official example, I reported it to Kha  https://github.com/Kode/Kha/issues/794

**Comment by luboslenco** [comment]
Hm, voxelization in armory uses the conservative rasterization, so the output will not be fully correct without that extension. To use git version:
http://armory3d.org/manual/#/dev/gitversion?id=manual-clone

**Comment by trsh** [comment]
@luboslenco 

It's not supported by lot's of GPU's http://feedback.wildfiregames.com/report/opengl/feature/GL_NV_conservative_raster . 

Maybe we can think of alternatives?

**Comment by luboslenco** [comment]
The alternatives may be slower and will bring more complexity, I need to make it fast first. Once it gets fast I will expand the compatibility.

**Comment by trsh** [comment]
Great! However the kha fix introduces check for conservative rasterization support. This is a must be, because otherwise gl errors spam the run-time until it dies.

**Comment by luboslenco** [comment]
Yes, it's a good fix.

**Comment by trsh** [comment]
@luboslenco 

> I need to make it fast first. Once it gets fast I will expand the compatibility.

You might want to Look into Crtyteks SVOTI tech. It has nice performance- tested it my self. Basically from what I understood, they do lods for voxel sparse octree. Can comment any further.
