### ISSUE TITLE
material_tessellation example failed with latest Armory 0.3 git

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#565]
1)Latest Armory 0.3 git and armory example git

![material_tessellation_failed](https://user-images.githubusercontent.com/4146156/37940204-f2b3185a-3199-11e8-9541-498e84442be5.jpg)

**Comment by luboslenco** [comment]
Also back now. (https://github.com/armory3d/armory/commit/5278226b4ccad6d7aa6420a19287de0e6c42905f) 🔥
