### ISSUE TITLE
Voxel GI makes stuff red

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#567]
This happened to me now often enough that I am sure that it is a problem, but I do not have any idea what exactly causes it and what makes it disappear. Sometimes when changing something it makes everything appear reddish in F5 when VXGI ist turned on, maybe when changing a normal map of an object but not sure. A mixture of Clearing the project and recreating the lamps in the scene fixes it, and it frequently occurs in the sponza project and is really annoying.
https://github.com/Simonrazer/Sponza

EDIT: now it was triggered by turning "batch meshes" on and fixed by "Clear Project"-> F5 -> delete an recreate lamp

**Comment by luboslenco** [comment]
Fix attempt at https://github.com/armory3d/iron/commit/b136db428cfc350aa5976b577609385d5ff22d29. (Tries to properly cover the voxelized volume in a shadowmap, which is used to inject lighting into the voxels.)

**Comment by trsh** [comment]
Can this be re-tested?
