### ISSUE TITLE
Ctrl+Z uses default Cycles while Armory is the selected renderer

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#57]
Using any of the buttons marked "Play in Viewport" or a variation work to render in Armory but the Ctrl. + Z shortcut I usually use always uses default Cycles instead and this behavior is not consistent with the default design philosophy that other renderers use when installed in Blender.

**Comment by luboslenco** [comment]
For me Ctrl+Z performs undo, do you mean Shift+Z? If so, then pressing that in BGE (which is real-time like Armory) seems to do nothing.

It is probably better to think of Armory as an extension to Cycles. Shift+Z to render the preview, P (like BGE) to play in real-time.

**Comment by George-the-1st** [comment]
Pardon, wrong shortcut. Also, you are probably correct at the end of the day. Consistency in shortcuts between BGE and Armory would be a good idea.
