### ISSUE TITLE
Transparency broken

### ISSUE THREAD

**Issue by trsh** [armory3d/armory#570]
Without option Discard:

![no_discard](https://user-images.githubusercontent.com/3727523/37969384-3c0d9662-31d9-11e8-93a5-95ba47de9d05.png)

Looks ugly, but on camera/view-port movement doesn't glitch.

![discard](https://user-images.githubusercontent.com/3727523/37969541-a8f9e7da-31d9-11e8-8199-241017b8a38e.png)

Looks better. No alpha sorting issue? But When moving away and back to the flowers object, it flickers like some badly antialiased edge or old pixel game. When moving really fast, can see texture lines created, etc.

Dark edges are created around the leaves. Have to tweak mesh opacity higher, but then leaves look cut.

Playground: https://github.com/trsh/Armory3DSponza

**Comment by AFWSI** [comment]
Yeah, I noticed this same thing. I posted on Armory forums about this. I thought it was something wrong with my texture/image ,but it doesn’t show this cloudy artifacts when I look at it in GIMP. If I render in cycles it doesn’t show this either.

**Comment by trsh** [comment]
@luboslenco. How about this for v0.4? Seems like a very important thing for games.

**Comment by luboslenco** [comment]
Should be better on latest git.
