### ISSUE TITLE
Game bowling examples, black screen after changing scene default to "Menu" and play

### ISSUE THREAD

**Issue by takhimi** [armory3d/armory#571]
-Latest Armory git and armory_examples git

1)Open game_bowling example and click "Play" button. It will run ok (The default scene is "Scene" and I can switch to Menu while playing the game without problems. Exit the game.
2)Open another scene called "Menu" and click Play button. It will be black screen. 
3)Same thing happens if I published the the game. 

Basically if I start the game with "Menu" scene it will be black. The menu canvas are not drawn.

**Comment by luboslenco** [comment]
Fixed! (https://github.com/armory3d/armory/commit/7ac97b638e5dec650801898b7986df896b33e5ba, https://github.com/armory3d/iron/commit/aeea554d34af0f8bd167385733fcb92839d93235)
