### ISSUE TITLE
Blender 2.8 - AttributeError: 'Object' object has no attribute 'layers'

### ISSUE THREAD

**Issue by ImmanuelSamuel** [armory3d/armory#572]
Basic scene with cube - Blender 2.8 addon + git pull master
I get the error ```AttributeError: 'Object' object has no attribute 'layers'``` when pressing play.

```
File "/path/to/armsdk//armory/blender/arm/exporter.py", line 811, in export_object
    if bobject.layers[l] == True:
AttributeError: 'Object' object has no attribute 'layers'
```

**Comment by luboslenco** [comment]
Keeping an eye on b2.8 compatibility now, basics should be working.
