### ISSUE TITLE
[Feature Request] 64 bit coordinate system

### ISSUE THREAD

**Issue by ImmanuelSamuel** [armory3d/armory#573]
Would love to see this. I went through the Kha and Krom sources and seems like all of that needs to be changed. Since @luboslenco has extensive experience with Kha and have written demos for the project maybe you have a say to the Kha team to bring this feature.

Might probably open issue at Kha repo? and maybe we can use this one for future when Kha implements it?

This may be a great feature to really push game studios to this engine. Few game studios have given up using unreal and moved to engines like unigine for the 64 bit coordinate system and maybe a3d can be the better alternative.

Interesting forum thread
https://www.gamedev.net/forums/topic/689162-unigine-2-and-its-64-bits-coordinate-precision/

One of the responses there is:

> You don't need double precision for vertices on the GPU. Model-space vertex positions are usually close to origin, and final NDC coordinates are also close to origin. If you use a model->world matrix followed by a world->projection matrix then you'll end up in trouble because world-space coordinates are massive... So you just have to be sure to use a single model->world->projection matrix which has been calculated by the CPU in double precision before being truncated to single precision and sent to the GPU.

Still some planet models can still have large values.

Update: Might have written the post too soon. Seems like virtual 64 bit coordinate system is the way to go along with inverted depth buffers. Any plans on eventually making this as core functionality?

**Comment by luboslenco** [comment]
(related https://github.com/Kode/Kha/issues/789)

**Comment by luboslenco** [comment]
Added an experimental flag which can be enabled by adding `project.addDefine('arm_centerworld');` into a khafile. This will prevent massive world space coords. For extremely large models it's probably better to split them into smaller pieces for now, to aid in culling.
