### ISSUE TITLE
Deferred Path on macOS fails building some shaders

### ISSUE THREAD

**Issue by anadin** [armory3d/armory#576]
MacBook Pro 15"
Radeon Pro 560 4096 MB
Intel HD Graphics 630 1536 MB
macOS 10.13.4 

This is happening in the archery template with no changes, load, go to Render tab and press Armory Play button

`
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 5.807137966156006
GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled

GLSL compiler error: ERROR: 0:5: '' :  extension 'GL_ARB_shader_image_load_store' is not supported
ERROR: 0:7: 'image3D' : Reserved word. 
ERROR: 0:7: 'image3D' : syntax error: syntax error

GLSL linker error: ERROR: One or more attached shaders not successfully compiled
`

I had similar problem with the vehicle template - switching to forward, building and then back to deferred seems to have fixed it there but not for archery. With Archery it will actually run in forward (even with the errors) but all I get is a white window in the player when in deferred.

**Comment by anadin** [comment]
Also getting an error when building for iOS

libc++abi.dylib: terminating with uncaught exception of type spirv_cross::CompilerError: At least ESSL 3.10 required for shader image load store.

**Comment by luboslenco** [comment]
For the templates, you need to turn voxel ao off (`Armory Render Path - Global Illumination`) on macOS, because Apple stopped supporting opengl past version 4.1 in favor of metal. Resetting the whole preset by selecting `Deferred` or `Mobile` in `Armory Render Path - Preset` should also do it.

I will make Armory properly report this in the interface to make it less cryptic, sorry for trouble. Once our metal backend gets more mature I will make it the default on macOS.

**Comment by anadin** [comment]
Ah cool thanks @luboslenco, I was mislead a little by this in the terminal..

`Armory Warning: Disabling Voxel GI - unsupported target - use Krom instead`

Which is there when playing in Viewport but not when playing in a seperate window.

Happy to help testing/working with Metal when it comes along - my experiences with it in UE4 are v. positive.

**Comment by luboslenco** [comment]
Auto-disables voxels on macos for now, to pass the compilation.
