### ISSUE TITLE
Armory bake Smart UV instead of Lightmap pack (?)

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#578]
It seems like the bake tool currently uses "Smart UV" unwrap for the objects UVs, but wouldn't "Lightmap Pack" be better? It covers the texture way better and since it is baking streching is not a problem.

**Comment by luboslenco** [comment]
Yes! I recall having some trouble with lightmap pack, it's currently commented out here:
https://github.com/armory3d/armory/blob/master/blender/arm/props_bake.py#L140.
Will sort that out.

**Comment by luboslenco** [comment]
Unwrap type can now be set in bake panel. (https://github.com/armory3d/armory/commit/23e17c7a2bce0e4aef4377bf6f3adace2a7a637e)
