### ISSUE TITLE
Armory bake denoising [Feature request low prio]

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#579]
Would be really cool if the baked textures could be denoised like this: https://www.youtube.com/watch?v=AlkJxHT6Z50

**Comment by ubaldy** [comment]
Similar to this:
https://docs.blender.org/manual/en/dev/render/cycles/settings/scene/render_layers/denoising.html
?

**Comment by luboslenco** [comment]
Will rely on built-in Cycles denoising for this.

**Comment by Simonrazer** [comment]
Not available for baking (yet), it says it in the manual! Well I hope they will get it working some time.

**Comment by ubaldy** [comment]
Oops, sorry I missed that!
