### ISSUE TITLE
(Feature request) C++ programming.

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#58]
Looked to see if you have C++ scripting among the other types under Armory Traits and ,unfortunately, I didn't see the option. I would like this option to be added. Thankyou.

**Comment by zauberparacelsus** [comment]
I'd suggest using Haxe, which has a somewhat familiar syntax to C++ and is translated to C++ when building for a native target.

PS: There is no such thing as C++ Scripting.

**Comment by George-the-1st** [comment]
Drat ya it's a programming language. i don't know why I derped on that.

**Comment by luboslenco** [comment]
For performance heavy things you can write C++ code(for native targets), but for traits Haxe, JS or Python is recommended. See [Bullet](https://github.com/armory3d/haxebullet) integration for one of the ways to interact with C++.

**Comment by Justinfront** [comment]
George-the-1st i promise you will like Haxe and it's not hard to get started

**Comment by George-the-1st** [comment]
I guess I'll adjust. Regardless, back to bug reporting.

**Comment by luboslenco** [comment]
Hm, would you prefer to write traits in C++ over any of Haxe/JS/Python? If so, what are the reasons? Is it because of familiarity with C++? As mentioned, perf. heavy code can be moved to C++.

**Comment by George-the-1st** [comment]
I've been working on learning C++ and haven't gotten around to the other languages I've wanted to get into (Python, rest of the C family, ect.) As a result, I wanted to double up on my work and be able to learn while coding for my projects and that is the biggest reason thus far. Also, while C++ is a 'heavier' language in comparison to scripting languages it is able to handle just about everything I've come across (even if it isn't the most efficient in a given scenario) and since I don't have any current projects for browser based games and even a 2000s computer is relatively fast and has enough storage space to handle the inefficiencies of coding entirely in C++. my currently small gaming projects don't need to really fit into tight file sizes or run really efficiently. Thus, a "one size fits all" mentality is what I've taken until I see the benefit of having a hybrid solution with lighter tasks taking up something like Python and heavier tasks taking up C++ overweighing the downside of learning two languages simultaneously or I get to a proficient level with C++ and I can begin learning other languages.
