### ISSUE TITLE
some Armory Unsolidifying errors

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#580]
*(optional - drag & drop zipped .blend file here)*
1.play in scene doesnt work. only in viewport. same with exported build on windows

2.when installed armory in official blender 2.79b to try if scene play works ( because i remember many versions ago it did work ) and later i started bundled armory blender and it had addons conflicts.

![armory enable bug again](https://user-images.githubusercontent.com/9019563/38453595-7d59e9d6-3a58-11e8-9fb4-c720909f02e5.jpg)

3.playing with deffered and TAA makes armory / blender freeze or cant use blender viewport and need to restart armory.

4. when running armory in viewport and adding ojects , materials or editing mesh then  rigid body objects resets from start position.

maybe could make material updates seperate from physics and all...

5. when running armory in viewport and adding ojects , materials or editing mesh armory doesnt update location or many changes. so need to click on Clean button in Armory Player options and run again armory to be able to update.

its like after editing mesh in edit mode makes almost never update it to armory...
this is really bad one...

found out that need do apply scale or  rotation / scale in object mode and click on something else, then it updates the mesh change after 1-2 secs
sometimes doesnt update even doing apply scale and click on other objec or etc...

strange that some operators do update object immediatly like destructive extrude

6. sometimes adding material textures in material node editor makes buggy looking.. but after playing with scale value then it solves sometimes..
sometimes long time not updating even doing everything that updates

7. tryed archery template and if i set option in render path to MAX (game) deferred and turn off post process then i get error if trying to run armory that says: shader data "copy_pass" not found!

and blender freezes too..

8. if you change some sliders on blender while holding mouse still and move on armory window then the viewport moves.. same from armory viewport to blender windows..

maybe could make like shift + F to more armory viewport and disable the mouse activity on it...

9. if armory is running and i make apply rigid body then blender quits/crash but then if i load auto save and do it again then i can enable and disable rigid body options while armory is running

and if rigid body is on passive mode and you move object then you need click somewhere else to update location...

10. armory viewport suddenly crash / stops if clicking on nodes in logic node tree

11. this is not bug but more liek of feature request.
even with all the bugs mentioned here.i the armory could be really revolutionary but the biggest problem still exists for creating some simple game is logic nodes. they 
are just to hard. its like i would need to study math / haxe language to be able to create something because my brain is bad to learn so much. and i think im not the only one thinking same.. i saw people ask on forums how to do just simple color change or so... T_T

so my begging you is that you really need to simplify logic nodes for example like in the BGE brick nodes...

after all this is biggest disadvantage of creating something usefull gameplay fun. and graphics not really so important anymore in games anyway...

its physics, AI, and many different variety of gameplays in game...

12. the most bad bug is that armory viewport turns off if nodes are added in Logic node tree window and clicking on some nodes or even objects in 3D viewport.

this bugs is most terrible because cant learn them normal the nodes by creating something. wasting to much time by clicking on play in viewport and waiting few seconds

please fix this pls pls pls

**Comment by ubaldy** [comment]
Hey @mushroomeo , if you supply .blend files demonstrating these issues I may be able to solve some of them 😁

**Comment by luboslenco** [comment]
0.4 begins with new viewport integration to address those issues, live-sync is not yet in but coming.
