### ISSUE TITLE
going back from baked to no bake problem

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#584]
How to properly get rid of the baked lightmaps again? If I just remove the objects out off the list and set the renderpath to "Deferred" the lightmaps are still visible, and if I shift-delete them in Blender and restart Blender afterwards all objects are in strange black shades.

**Comment by luboslenco** [comment]
I think removing the materials with `_baked` suffix should do, and perhaps removing the additional bake uv maps. But it's a good point to have this option built-in in the interface, will add that.

**Comment by luboslenco** [comment]
Added `Remove Baked Materials` button into Armory Bake.
