### ISSUE TITLE
Some memory bug

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#586]
*(optional - drag & drop zipped .blend file here)*
played long time with rigid bodys while armory running in viewport and then got this error

[untitled.zip](https://github.com/armory3d/armory/files/1899228/untitled.zip)

Exporting asset 1 of 1 (mesh_Cube.019.arm).
Exporting asset 1 of 1 (mesh_Cube.020.arm).
Exporting asset 1 of 1 (mesh_Cube.021.arm).
Exporting asset 1 of 1 (mesh_Cube.022.arm).
Exporting asset 1 of 1 (mesh_Cube.023.arm).
Exporting asset 1 of 1 (mesh_Cube.024.arm).
Exporting asset 1 of 1 (mesh_Cube.025.arm).
Exporting asset 1 of 1 (mesh_Cube.026.arm).
Exporting asset 1 of 1 (mesh_Cube.027.arm).
Exporting asset 1 of 1 (mesh_Cube.028.arm).
Exporting asset 1 of 1 (mesh_Cube.029.arm).
Exporting asset 1 of 1 (mesh_Cube.030.arm).
Exporting asset 1 of 1 (mesh_Cube.031.arm).
Exporting asset 1 of 1 (mesh_Cube.032.arm).
Exporting asset 1 of 1 (mesh_Cube.033.arm).
Exporting asset 1 of 1 (mesh_Cube.034.arm).
Exporting asset 1 of 1 (mesh_Cube.035.arm).
Exporting asset 1 of 1 (mesh_Cube.036.arm).
Exporting asset 1 of 1 (mesh_Cube.161.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (bloom_pass.frag.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass.frag.glsl).
Compiling shader 1 of 1 (blur_gaus_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (pass_viewray2.vert.glsl).
Compiling shader 1 of 1 (ssgi_blur_pass.frag.glsl).
Compiling shader 1 of 1 (ssgi_pass.frag.glsl).
Compiling shader 1 of 1 (ssr_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_002_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_002_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_002_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_004_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_004_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_004_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_005_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-image.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.

Armory v0.3.0 ($Id: bebbb7fa00e259ed7a026970637a60b0abab7b52 $)
OS: win, Target: krom, GAPI: opengl
Armory Warning: Disabling Voxel GI - unsupported target - use Krom instead
Armory Warning: Disabling soft shadows - "Armory Render Path - Cascades" require
s to be set to 1 for now
Exporting Scene
Scene built in 0.02000117301940918
Exported modules: ['physics']
Shader flags: ['_Irr', '_EnvSky', '_Rad', '_EnvClouds', '_EnvStr', '_CSM', '_RTG
I', '_SSGICone9', '_Brdf', '_IndPos', '_SSAO']
Armory Warning: Use Blender 2.8 to run Voxel GI in viewport
Running:  ['C:/Users/azuma/Desktop/Armory/armsdk//nodejs/node.exe', 'C:/Users/az
uma/Desktop/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion',
 '330', '--to', 'build_untitled', '--nohaxe', '--noproject']
Using Kha from C:\Users\azuma\Desktop\Armory\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (Material_002_data.arm).
Exporting asset 1 of 1 (Material_004_data.arm).
Exporting asset 1 of 1 (Material_005_data.arm).
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (noise256.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Cube.001.arm).
Exporting asset 1 of 1 (mesh_Cube.002.arm).
Exporting asset 1 of 1 (mesh_Cube.003.arm).
Exporting asset 1 of 1 (mesh_Cube.007.arm).
Exporting asset 1 of 1 (mesh_Cube.016.arm).
Exporting asset 1 of 1 (mesh_Cube.017.arm).
Exporting asset 1 of 1 (mesh_Cube.018.arm).
Exporting asset 1 of 1 (mesh_Cube.019.arm).
Exporting asset 1 of 1 (mesh_Cube.020.arm).
Exporting asset 1 of 1 (mesh_Cube.021.arm).
Exporting asset 1 of 1 (mesh_Cube.022.arm).
Exporting asset 1 of 1 (mesh_Cube.023.arm).
Exporting asset 1 of 1 (mesh_Cube.024.arm).
Exporting asset 1 of 1 (mesh_Cube.025.arm).
Exporting asset 1 of 1 (mesh_Cube.026.arm).
Exporting asset 1 of 1 (mesh_Cube.027.arm).
Exporting asset 1 of 1 (mesh_Cube.028.arm).
Exporting asset 1 of 1 (mesh_Cube.029.arm).
Exporting asset 1 of 1 (mesh_Cube.030.arm).
Exporting asset 1 of 1 (mesh_Cube.031.arm).
Exporting asset 1 of 1 (mesh_Cube.032.arm).
Exporting asset 1 of 1 (mesh_Cube.033.arm).
Exporting asset 1 of 1 (mesh_Cube.034.arm).
Exporting asset 1 of 1 (mesh_Cube.035.arm).
Exporting asset 1 of 1 (mesh_Cube.036.arm).
Exporting asset 1 of 1 (mesh_Cube.161.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (bloom_pass.frag.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass.frag.glsl).
Compiling shader 1 of 1 (blur_gaus_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (pass_viewray2.vert.glsl).
Compiling shader 1 of 1 (ssgi_blur_pass.frag.glsl).
Compiling shader 1 of 1 (ssgi_pass.frag.glsl).
Compiling shader 1 of 1 (ssr_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_002_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_002_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_002_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_004_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_004_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_005_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-image.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.frag.glsl).
Done.
C a n n o t   e n l a r g e   m e m o r y   a r r a y s .   E i t h e r   ( 1 )
  c o m p i l e   w i t h     - s   T O T A L _ M E M O R Y = X     w i t h   X
  h i g h e r   t h a n   t h e   c u r r e n t   v a l u e   6 7 1 0 8 8 6 4 ,
  ( 2 )   c o m p i l e   w i t h     - s   A L L O W _ M E M O R Y _ G R O W T
H = 1     w h i c h   a l l o w s   i n c r e a s i n g   t h e   s i z e   a t
  r u n t i m e   T r a c e :   T y p e E r r o r :   c . p r i n t E r r   i s
  n o t   a   f u n c t i o n
         a t   s a   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 3 1 1 : 2 5 6 )
         a t   F a   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 1 3 : 1 5 )
         a t   e n l a r g e M e m o r y   ( e v a l   a t   < a n o n y m o u s
 >   ( k r o m . j s : 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 2 7 : 5 4 )
         a t   u o   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 4 7 : 3 5 9 7 4 8 )
         a t   i c   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s >
Armory v0.3.0 ($Id: bebbb7fa00e259ed7a026970637a60b0abab7b52 $)
OS: win, Target: krom, GAPI: opengl
Armory Warning: Disabling Voxel GI - unsupported target - use Krom instead
Armory Warning: Disabling soft shadows - "Armory Render Path - Cascades" require
s to be set to 1 for now
Exporting Scene
Scene built in 0.021001100540161133
Exported modules: ['physics']
Shader flags: ['_Irr', '_EnvSky', '_Rad', '_EnvClouds', '_EnvStr', '_CSM', '_RTG
I', '_SSGICone9', '_Brdf', '_IndPos', '_SSAO']
Armory Warning: Use Blender 2.8 to run Voxel GI in viewport
Running:  ['C:/Users/azuma/Desktop/Armory/armsdk//nodejs/node.exe', 'C:/Users/az
uma/Desktop/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion',
 '330', '--to', 'build_untitled', '--nohaxe', '--noproject']
Using Kha from C:\Users\azuma\Desktop\Armory\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (ammo.js).
Exporting asset 1 of 1 (Material_002_data.arm).
Exporting asset 1 of 1 (Material_004_data.arm).
Exporting asset 1 of 1 (Material_005_data.arm).
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (hosek_radiance.hdr).
Exporting asset 1 of 1 (hosek_radiance_0.hdr).
Exporting asset 1 of 1 (hosek_radiance_1.hdr).
Exporting asset 1 of 1 (hosek_radiance_2.hdr).
Exporting asset 1 of 1 (hosek_radiance_3.hdr).
Exporting asset 1 of 1 (hosek_radiance_4.hdr).
Exporting asset 1 of 1 (hosek_radiance_5.hdr).
Exporting asset 1 of 1 (hosek_radiance_6.hdr).
Exporting asset 1 of 1 (hosek_radiance_7.hdr).
Exporting asset 1 of 1 (noise256.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Cube.001.arm).
Exporting asset 1 of 1 (mesh_Cube.002.arm).
Exporting asset 1 of 1 (mesh_Cube.003.arm).
Exporting asset 1 of 1 (mesh_Cube.007.arm).
Exporting asset 1 of 1 (mesh_Cube.016.arm).
Exporting asset 1 of 1 (mesh_Cube.017.arm).
Exporting asset 1 of 1 (mesh_Cube.018.arm).
Exporting asset 1 of 1 (mesh_Cube.019.arm).
Exporting asset 1 of 1 (mesh_Cube.020.arm).
Exporting asset 1 of 1 (mesh_Cube.021.arm).
Exporting asset 1 of 1 (mesh_Cube.022.arm).
Exporting asset 1 of 1 (mesh_Cube.023.arm).
Exporting asset 1 of 1 (mesh_Cube.024.arm).
Exporting asset 1 of 1 (mesh_Cube.025.arm).
Exporting asset 1 of 1 (mesh_Cube.026.arm).
Exporting asset 1 of 1 (mesh_Cube.027.arm).
Exporting asset 1 of 1 (mesh_Cube.028.arm).
Exporting asset 1 of 1 (mesh_Cube.029.arm).
Exporting asset 1 of 1 (mesh_Cube.030.arm).
Exporting asset 1 of 1 (mesh_Cube.031.arm).
Exporting asset 1 of 1 (mesh_Cube.032.arm).
Exporting asset 1 of 1 (mesh_Cube.033.arm).
Exporting asset 1 of 1 (mesh_Cube.034.arm).
Exporting asset 1 of 1 (mesh_Cube.035.arm).
Exporting asset 1 of 1 (mesh_Cube.036.arm).
Exporting asset 1 of 1 (mesh_Cube.161.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (bloom_pass.frag.glsl).
Compiling shader 1 of 1 (blur_adaptive_pass.frag.glsl).
Compiling shader 1 of 1 (blur_gaus_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (pass_viewray2.vert.glsl).
Compiling shader 1 of 1 (ssgi_blur_pass.frag.glsl).
Compiling shader 1 of 1 (ssgi_pass.frag.glsl).
Compiling shader 1 of 1 (ssr_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_002_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_002_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_002_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_004_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_004_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_005_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.frag.glsl).
Done.
C a n n o t   e n l a r g e   m e m o r y   a r r a y s .   E i t h e r   ( 1 )
  c o m p i l e   w i t h     - s   T O T A L _ M E M O R Y = X     w i t h   X
  h i g h e r   t h a n   t h e   c u r r e n t   v a l u e   6 7 1 0 8 8 6 4 ,
  ( 2 )   c o m p i l e   w i t h     - s   A L L O W _ M E M O R Y _ G R O W T
H = 1     w h i c h   a l l o w s   i n c r e a s i n g   t h e   s i z e   a t
  r u n t i m e   T r a c e :   T y p e E r r o r :   c . p r i n t E r r   i s
  n o t   a   f u n c t i o n
         a t   s a   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 3 1 1 : 2 5 6 )
         a t   F a   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 1 3 : 1 5 )
         a t   e n l a r g e M e m o r y   ( e v a l   a t   < a n o n y m o u s
 >   ( k r o m . j s : 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 2 7 : 5 4 )
         a t   u o   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 4 7 : 3 5 9 7 4 8 )
         a t   i c   ( e v a l   a t   < a n o n y m o u s >   ( k r o m . j s :
 1 6 0 : 1 2 ) ,   < a n o n y m o u s > : 4 9 : 2 4 2 1 6 0 )

**Comment by nextdimension** [comment]
I've been playing around with it for quite a while and I haven't crashed yet.

**Comment by ubaldy** [comment]
There could be a leak... I don't have arm.PhysicsDrag so I cannot test at the moment. Should this .blend file work without any option changes?

**Comment by ubaldy** [comment]
You are spawning the object that spawns the objects. Thus you get an exponential increase in objects. Try not spawning a spawner, then you might get the results you want!!

![memory_issue_2](https://user-images.githubusercontent.com/31992088/38899358-95b6ff40-4265-11e8-81c4-9947c2a1a694.PNG)

**Comment by mushroomeo** [comment]
cool thanks. you right it worked.after i didnt spawn spawner object i didnt get anymore this error  but the first few times i didnt spawn any objects and i was just playing around with materials and had this error.
well thanks for help

**Comment by ubaldy** [comment]
No problem. If you run across this error again and you are not spawning spawners then I would like to debug that one too.

**Comment by ubaldy** [comment]
Hey @mushroomeo , would you consider this issue resolved?

**Comment by luboslenco** [comment]
Merging with similar issue at https://github.com/armory3d/armory/issues/341.
