### ISSUE TITLE
Fix mixing translucent and opaque materials

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#588]
cycles
![96](https://user-images.githubusercontent.com/23359603/38678660-54e766a2-3e6a-11e8-8257-84210cbfdede.png)
armory
![97](https://user-images.githubusercontent.com/23359603/38678676-5ddcf0ec-3e6a-11e8-8df8-faabf69053ed.png)

*(optional - drag & drop zipped .blend file here)*

**Comment by AFWSI** [comment]
Words would help a little. Is no transparency the issue? It looks like you are not using the same material on both.

**Comment by Simonrazer** [comment]
That the base tree disappears is strange, try checking "Discard" in the leaves material and disconnect all normal maps.

**Comment by Xristoskr** [comment]
https://drive.google.com/open?id=122mjUjeMC0yvKVCbM-44LeHtoakS8RHE here the blender file

**Comment by Simonrazer** [comment]
There are no textures! Please pack them in the .blend

**Comment by Xristoskr** [comment]
https://drive.google.com/open?id=1ChcksRYAT1zpbN3bO6bZZrF1fiHey2qX

**Comment by Simonrazer** [comment]
It seems like for transparency to work properly on an object it can only have material assigned to it, and I also had troubles with using an images alpha channel. Tess displacement is way to exaggerated, or unnoticeable when turned down to a degree where there are no more glitches. The leave material currently has "Discard" disabled, but it also looks fine but different with it turned on. 
https://drive.google.com/file/d/1aEDLK1jcJj3vtSLJW5OkeVshoLYLr8wt/view?usp=sharing

**Comment by Xristoskr** [comment]
It work now but the bark texture is darker and leaf seems transparent to
some points and fake


Στις Πέμ, 12 Απρ 2018 - 19:36 ο χρήστης Simonrazer <notifications@github.com>
έγραψε:

**Comment by luboslenco** [comment]
Pushed more fixes, opaque parts should now be really opaque.
