### ISSUE TITLE
Solidify Modifier active after deletion

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#59]
I used a solidify modifier on a maze that I'm working on for a prototype because I wanted to easily add thickness. Now, I'm afraid that after removing the modifier while still rendering in armory, the solidify modifier's effects continued to last even after multiple refreshes. File is here: 
[simple.zip](https://github.com/armory3d/armory/files/605519/simple.zip)

(Note: file will be duplicate name of other files I use, I reuse the same file while testing and pull out interesting and useful things from it into different files. This will continue for a while until my first round of tests are complete.

**Comment by George-the-1st** [comment]
Note: Armory build 'clean' button fixes this.

**Comment by luboslenco** [comment]
Nice catch! Should be resolved in next build (https://github.com/armory3d/armory/commit/33a3974961bff412f8fe70b205e89fc13e00bfb2).
