### ISSUE TITLE
Particle simulation speed change if on GPU/not

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#590]
The particle simulation speed is way faster when "GPU Simulation in the Particle settings-> Armory props is turned on.
[partspeed.zip](https://github.com/armory3d/armory/files/1904352/partspeed.zip)

**Comment by ubaldy** [comment]
Same results. Particle lifetimes are very different between CPU and GPU simulation.

**Comment by luboslenco** [comment]
gpu/cpu particle lifetime is more in line now.
