### ISSUE TITLE
"Canvas Set Text" node broken

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#592]
F5 player crashes when node is activated, happens in every .blend. (Node for hiding Text field would be nice)

**Comment by ubaldy** [comment]
.blend file example reproducing issue please?

**Comment by Simonrazer** [comment]
Here:
[setcanv.zip](https://github.com/armory3d/armory/files/1928888/setcanv.zip)

**Comment by ubaldy** [comment]
Hey @Simonrazer , I do not believe the canvas is included in the .blend file. Would you include it? Thanks!

**Comment by Simonrazer** [comment]
Oups forgot that, sorry 
[setcanv.zip](https://github.com/armory3d/armory/files/1934486/setcanv.zip)

**Comment by Simonrazer** [comment]
Thanks a ton!

**Comment by luboslenco** [comment]
Will now also work when the canvas is a trait of camera. https://github.com/armory3d/armory/commit/c0546350890c47ad041804f9fd7b96118244dede
