### ISSUE TITLE
Unconnected Redirect node throws python error

### ISSUE THREAD

**Issue by MadMinstrel** [armory3d/armory#595]
Just having an unconnected redirect node anywhere in a logic graph throws a python error at build time. This is particularly insidious because a redirect node with no connections just looks like a tiny yellow dot and can be hard to spot.

[redirect_fail.zip](https://github.com/armory3d/armory/files/1911916/redirect_fail.zip)

**Comment by ubaldy** [comment]
This seems to work, will do proper pull request when I get the chance.

In file: 
armsdk/armory/blender/arm/make_logic.py
In function:
build_node

Replace

    if node.type == 'REROUTE':
        return build_node(node.inputs[0].links[0].from_node, f)

With

    if node.type == 'REROUTE':
    	empty = True
    	if len(node.inputs) > 0:
    		if len(node.inputs[0].links) > 0:
    			empty = False

    	if not empty:
    		return build_node(node.inputs[0].links[0].from_node, f)
    	if empty:
    		return None

**Comment by ubaldy** [comment]
Fixed? Close? Yes?

**Comment by MadMinstrel** [comment]
Tested, fixed, thanks! :D
Closing.

**Comment by ubaldy** [comment]
Thank you as well for the information used to solve the problem :)
