### ISSUE TITLE
Test mobile browsers

### ISSUE THREAD

**Issue by ghost** [armory3d/armory#60]
Hello!

I just tested a simple scene on a few browsers/devices. As I am new to Armory, it's the beginner scene that consists in Susanne/Monkey rotating.

MacOS (latest available update): Safari, FireFox, Chrome -> OK
PC: Win7 and Win10 (latest available update respectively): Chrome, FireFox ->  OK
IE and Edge -> FAILED
Android (latest) -> FAILED
iOS (latest) -> FAILED

Althought there's still a lot to do, I think it's a very interesting addon for Blender.

Keep up the good work!  ;-)

**Comment by luboslenco** [comment]
Heyo @E25543,

Thanks for kind feedback! Which render path did you use for camera? It defaults to deferred. Unfortunately some browsers do not provide extensions required for more featured rendering. To run on those, you need to strip down graphics settings.

This one should run on everything, including mobile:
http://armory3d.org/demo/animation/forward_low/ 

To target mobile, doing native builds is recommended if possible - more performance & features. I will also do my best improve support for all browsers.

There is not yet an automatic fallback to less demanding render-path but would like to roll something eventually(something that developer still has control of). That way it should run everywhere out of the box, but it will look uglier on less features browsers. :)

**Comment by E25543** [comment]
Nice!

I'll try that. Maybe the easiest solution about "selecting the proper render for a browser" would be a Javascript that select which scene/files to download (client-side). This would have the benefit the download seize as low as possible.

If you're ok with this, let me write this for you so you can focus on more interesting stuff. Besides, it's an interesting exercise for me as I am learning Javascript.

**Comment by E25543** [comment]
It did work fine on iOS.

Still some problems on Android (Firefox and Chrome).
Detail: on iOS, browser, the Navigation: Walk is tough with a touch screen.

Armory is really interesting!

**Comment by luboslenco** [comment]
Totally ok with that!:)

Regarding Android, do you mean it still does not start at all? It runs here on Galaxy S6 & Chrome but that is relatively high end device.

Regarding navigation, would like to roll some basic touch friendly controls for that eventually.

**Comment by E25543** [comment]
Just tested with Nexus 5X + Nougat and Samsung Note4 + Marshmallow: black screen.

It works (but lags) with a 5 yrs old iPad!  ; )

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armory/issues/178.
