### ISSUE TITLE
Support dynamic mesh physics shape

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#600]
if i set in blender rigid body to active and mesh collision, it doesnt work. its still like using box or other collision option but on passive rigid bodys works
[Rigid Mody mesh Bug.zip](https://github.com/armory3d/armory/files/1921911/Rigid.Mody.mesh.Bug.zip)

**Comment by anadin** [comment]
@mushroomeo have you got latest? and which object is not behaving, at first glance it seems OK here

latest git version on macOS


![rigidok](https://user-images.githubusercontent.com/2351943/38914334-4fd6202e-4322-11e8-8400-e15cac5d1eb7.gif)

**Comment by mushroomeo** [comment]
Ubaldy you rightz about this standing arch but its because its set to passive, here i updated the file and now try run the rigid bodys in blender and then in armory and see the difference..

[Rigid Mody mesh Bug Updated.zip](https://github.com/armory3d/armory/files/1926276/Rigid.Mody.mesh.Bug.Updated.zip)


for me in blender it works now after i set high mass for arch / door object and the cube handing inside lower but in armory is bugged and doesnt have mesh collision..

**Comment by anadin** [comment]
oh wow yeah thats really obvious now.. def. something v. odd going on here

**Comment by ubaldy** [comment]
I have trouble following your description @mushroomeo. Which object does not have collision?

For me the Armory3D simulation is more well behaved than the blender one!

**Comment by anadin** [comment]
So I still see a problem. Here with Blender Physics the small cube runs under the arch no issues
![blenderphysics](https://user-images.githubusercontent.com/2351943/39425870-bf24ce10-4cc0-11e8-85c7-53cf394fd680.gif)

And here with Armory, the cube causes the Arch to kick upwards
![armoryphysics](https://user-images.githubusercontent.com/2351943/39425889-dd79cbf4-4cc0-11e8-9f89-ad613636b2a5.gif)

**Comment by NothanUmber** [comment]
Thanks for reporting and looking into this. Also ran into that problem (with 0.4b, Blender 2.79). also have an arc shaped form that is unsurpassable for other objects (only the bounding box seems to be considered for collision)..

**Comment by luboslenco** [comment]
Added support for dynamic mesh physics shape in the latest git armory.
