### ISSUE TITLE
Adding Material node to graph causes crash

### ISSUE THREAD

**Issue by MadMinstrel** [armory3d/armory#602]
I've encountered a situation where just adding a Material node to a graph, connected or not, causes the game to crash. Sorry for not providing a more minimal file, but I couldn't figure out what exactly the problem is to isolate it.

To reproduce:
1. Open attached file and press P
2. Right-Click the green field to spawn some blue spheres on it. Notice they scale up slightly on mouse over. This is the way it's meant to work.
3. Now, add a Material node to the "highlight" graph, which should be open in the node editor. No need to connect it to anything.
4. Press P and try to spawn some spheres. Notice the game is frozen and there's an error in the console.

[material_node_fail_2.zip](https://github.com/armory3d/armory/files/1926504/material_node_fail_2.zip)

**Comment by ubaldy** [comment]
When I first open the project, MyCanvas trait on the scene is red. I overcame this by creating an empty canvas for it and running the project. Right clicking does not do anything though. 

I added the Material node and did not get the crash. 

Hope my input helps.

**Comment by MadMinstrel** [comment]
Thanks for checking it out. I'm a silly duck, never noticed the canvas is stored outside the .blend file. Sorry about that. I've updated the file.

**Comment by ubaldy** [comment]
Confirmed. That is strange. I will export it and debug it and see what jumps out :)

**Comment by ubaldy** [comment]
Here is my first dive. The only way I know how to debug this is with exporting to C++. I don't know how to debug Krom or else I would :) and exporting HTML fails complaining that it cannot find a Pen.

In the function MaterialData_obj::parse

HXLINE(  59)			 ::Dynamic raw = ::iron::data::Data_obj::getMaterialRawByName(( (::Array< ::Dynamic>)(format->__Field(HX_("material_datas",31,2a,02,22),hx::paccDynamic)) ),name);

The value of raw after this line is NULL which then gets dereferenced later on causing the exception. This gives me a pretty good idea of where to look in the actual haxe code so I will do that next!

**Comment by MadMinstrel** [comment]
The issue is now fixed. Thank you!
Closing.
