### ISSUE TITLE
Play in viewport bug

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#604]
just found new bug

![armory bug](https://user-images.githubusercontent.com/9019563/39079430-c8c73ece-451a-11e8-94fa-c621957d00f2.jpg)

[some bug.zip](https://github.com/armory3d/armory/files/1934073/some.bug.zip)

**Comment by ubaldy** [comment]
This isn't a bug. You didn't finish configuring the constraints. Your constraints have no objects associated with them.

**Comment by luboslenco** [comment]
Will no longer error out using https://github.com/armory3d/armory/commit/1e8ef7aaa51956494c75f22137d5926d50eba92d (but like mentioned objects have to be assigned).
