### ISSUE TITLE
"On Init" sometimes acting like "On Update"

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#607]
If the "On Init" node is connected to "Spawn Object" the Cube rotates the whole time and every frame a new Obstacle is being spawned. But if "On Init" isn't connected to "Spawn Object" the cube only rotates on the first frame.
![bug](https://user-images.githubusercontent.com/30187223/39091977-8e308436-4601-11e8-8679-a81521b97233.JPG)
[oninit.zip](https://github.com/armory3d/armory/files/1935252/oninit.zip)

**Comment by ubaldy** [comment]
Hey @Simonrazer,
This is a recurring problem. If you spawn a spawner you get really weird effects.
On init is not broken. You are spawning infinite Obstacle objects which all have a unique On Init.

**Comment by Simonrazer** [comment]
Dang it, this already happened to me twice, should have noticed that. Sorry

**Comment by ubaldy** [comment]
It is okay! These issues are really helping me learn Armory3D. This is an extremely flexible framework. I will think of a way to implement a warning for cycles like this. Don't be sorry for helping improve the engine :)
