### ISSUE TITLE
Fixing render capture

### ISSUE THREAD

**Issue by q3o** [armory3d/armory#608]
Hi,
I'm finally getting where I want with armory, which is totally awesome btw. So I've got to setup a scene that when played it works great.
Now I would like to pump it up and render, ideally an animation. It looks great, not cycles, but almost there and If I can get few seconds render per frame it would be awesome for my purposes.
I setup the path, choose the format, and set the file type accordingly (8bit - jpg rgb) and when I render, even with a simple cube+camera+light scene, it gives our an error. On console it shows and error on line 192 of renderpathdeferred.hx.
If I choose foward, it finishes ok but I don't get a jpg anywhere. If I change that line to a fixed value, according to Inc.hx "RGBA32" it finishes ok but I don't get a jpg either any where.
Any help?
Just a simple example
Thanks Oscar
[untitled.zip](https://github.com/armory3d/armory/files/1936447/untitled.zip)

**Comment by luboslenco** [comment]
Hey @q3o ,

Oh no, pushed a fix at https://github.com/armory3d/armory/commit/69716d53468c32249ca24115d96d0a4be27375b4. If you are able to use [Armory Updater](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater) then it should work now (hopefully).

**Comment by q3o** [comment]
Thanks there.
I've used the updater and it has update to 0.4 just fine. The process of render doesn't produce an error now, yet when it finishes building the scene, nothing shows up and there is not an output file on the destination folder.
Any help on figuring out what I'm doing wrong?
Thanks
Oscar

**Comment by luboslenco** [comment]
There must be some more issues. To verify that at least something is working, can you try this example?
https://github.com/armory3d/armory_examples/tree/master/render_capture

- Pressing `Armory Render - Render` should print *"Output image captured into Blender - UV/Image Editor - Render Result"* in the console and render result should be present in image editor.
- Pressing `Armory Render - Animation` should output image frames in `blend_root/out` folder.

**Comment by luboslenco** [comment]
Putting on hold as capture is better facilitated by eevee now.
