### ISSUE TITLE
Print Krom output to console on Windows

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#609]
In Windows, when I place a “trace(…)” in HAXE code or Use print node, there is no output in console using Krom to run the game. The trace message will show up when play in viewport (but due to issue 337 the message is incomplete with blanks inserted)

**Comment by luboslenco** [comment]
That is not good. Did Kode Studio work before for you? Is this only this particular project or nothing works?

One thing that I think can go wrong - try to select `Browser` runtime, hit `Armory Player - Build` and then run in Kode Studio. (I will try to resolve that tonight so this is only a temporary solution.)

Krom will also output traces/errors into .txt file in the next build. I hope to sort the direct print to console too, somehow it is not straightforward on windows.

**Comment by MiloHX** [comment]
@luboslenco 
Kode Studio works fine for me before. I re-download Armory then the debug issue is gone! However I still have to change one Kha source to make it work. 

1. Downloaded v0.3 form itch.io, then update it to the latest build using updater;
2. Start an empty project, add a cube and a lamp, run the project once with F5, and it works:
![capture_trace_01](https://user-images.githubusercontent.com/17811339/39297435-1ccc84c0-4976-11e8-92a5-53c414c2c75f.JPG)
3. Attach HAXE script to the cube then open Kode studio, I got error from `Pen.hx` of kha. 
![capture_trace_02](https://user-images.githubusercontent.com/17811339/39297685-bcd867f4-4976-11e8-8cfe-da8c4c9b6c65.JPG)
4. Download the latest `SystemImpl.hx` from Kha Github to replace existing one: `Armory\armsdk\Kha\Backends\HTML5\kha\SystemImpl.hx`. After this Kode Studio got no error.
5. Add `trace("Hello World");` in the script, and run it in Armory viewport, It is expected with blanks inserted:
![capture_trace_04](https://user-images.githubusercontent.com/17811339/39298422-bc69d8e6-4978-11e8-83d0-472f15b71011.JPG)
7. Try to run in HTML5 and Krom, I didn't find the traced message in the console.
8. Try to debug in Kode Studio, it worked this time.
![capture_trace_05](https://user-images.githubusercontent.com/17811339/39299624-c2226840-497b-11e8-880b-b5234b91c031.JPG)

**Comment by Naxela** [comment]
This seems to work now with the latest git version + latest copy from krom bin! 👍 (tested on both W10 and W7)

**Comment by MiloHX** [comment]
@Naxela @luboslenco 
Hey I tested this on windows 10,  and it still didn't work...did I do something wrong? 
Please see the attachment (b2.8). it works when I use viewport rendering, but doesn't work when play in krom (both print node and trace() in script)
[print_messages.zip](https://github.com/armory3d/armory/files/2121250/print_messages.zip)

**Comment by Naxela** [comment]
@MiloHx After you updated from Armory updater, did you copy over the new Krom build from the krom bin (https://github.com/armory3d/Krom_bin) - I had to do that before it worked

**Comment by MiloHX** [comment]
@Naxela Thanks! I can confirm this works. I will close this issue once the fix is in the official build.
