### ISSUE TITLE
(Feature Request) Mouse/Pointer Lock

### ISSUE THREAD

**Issue by llim1** [armory3d/armory#61]
Recently I've been trying to get proper first-person camera controls working with traits, specifically pointer lock. The introduction to [this article](https://www.chromium.org/developers/design-documents/mouse-lock) describes what I'm trying to do very well. I've got camera rotation when the mouse is moved done but I can't figure out how to lock the pointer. 

Things I've tried: 
`SystemImpl.lockMouse();`    hides cursor and locks mouse to window, but mouse movement cannot be measured. (`Input.deltaX/Y` & `Input.x/y` gives 0, `Input.moved` returns false, etc.)
`Mouse.get().lock();`    does nothing as far as I can tell
`Mouse.get().hideSystemCursor();` only hides the cursor, not what I need
`SystemImpl.requestFullScreen();` goes fullscreen in chrome builds but nothing on native windows build, still does not do what I need

Is there a way to use `SystemImpl.lockMouse();` to keep the mouse in place and focused and then measure the _movement_ of the mouse instead of its x and y position, that'd be ideal. If not, hopefully it's something that can be implemented!

**Comment by luboslenco** [comment]
Mouse movement should now be properly reported when using `SystemImpl.lockMouse();` (https://github.com/armory3d/iron/commit/5e4d3c9c2c634c8343efec05f0d5aee9ca0a5543)

Also renamed `Input.deltaX/Y` to `Input.movementX/Y` to keep consistent with Kha. To fetch movement directly from Kha, same thing that Input helper does can be used in any trait:

```hx
public function new() {
    kha.input.Mouse.get().notify(null, null, moveListener, null);
}

function moveListener(x:Int, y:Int, movementX:Int, movementY:Int) {
    
}
```
Hopefully this enables the ideal solution!

**Comment by llim1** [comment]
Works great on native build. Thanks!
