### ISSUE TITLE
Armory Player wont work in Linux with Krom

### ISSUE THREAD

**Issue by MordragT** [armory3d/armory#610]
Hello,
when i am try to start the Armory Player with Krom in an empty session the Player Window closes immediatly.
The Error i am getting:

`Armory v0.4 ($Id: 84782cad1841eb80213f4caf1d1c83c17172a8bd $)
OS: linux, Target: krom, GAPI: opengl
Exporting Scene
Scene built in 0.015439271926879883
Exported modules: []
Shader flags: ['_Irr', '_EnvCol', '_CSM', '_SMAA', '_SSAO']
Running:  ['/home/tom/Bin/git/armsdk//nodejs/node-linux64', '/home/tom/Bin/git/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--to', 'build_Start/debug']
Using Kha from /home/tom/Bin/git/armsdk/Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_001_data.arm).
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (mesh_Suzanne.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (ssao_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_001_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_001_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 5.701606750488281
0
Trace: TypeError: Krom.lockVertexBuffer is not a function
    at $hxClasses.kha.graphics4.VertexBuffer.lock (krom.js:33013:21)
    at $hxClasses.kha.graphics4.ImageShaderPainter.initBuffers (krom.js:31209:102)
    at new $hxClasses.kha.graphics4.ImageShaderPainter (krom.js:31166:7)
    at new $hxClasses.kha.graphics4.Graphics2 (krom.js:31981:22)
    at Function.kha_SystemImpl.init (krom.js:18995:90)
    at Function.kha_System.init (krom.js:18752:17)
    at Function.Main.start (krom.js:220:13)
    at Function.Main.main (krom.js:176:7)
    at krom.js:35238:6`

Some additional Information:
I am using the addon of Armory cause the Blender version wont start (some error related to a bpy import libary missing)
OS: Manjaro Linux
Kernel: 4.17
GPU: R9 270x
Blender 2.79
I am using the armsdk git but i updated the submodules to the latest version.
When i am using the Browser everything works,
and the C++ Runtime ends with an error.
I am starting blender with:
`env CYCLES_OPENCL_SPLIT_KERNEL_TEST=1 MESA_GL_VERSION_OVERRIDE=3.3 blender`
because otherwiese Cylces cant use my GPU and Armory wont detect the opengl version 3.3 but a 3.1 version.

Maybe someone got a idea whats the Problem.

**Comment by luboslenco** [comment]
Hello,
There may have been some mismatch of Kha and Krom binaries, hopefully as is in order now. And the latest `Armory_04b_linux64` should work on Manjaro too.

For Innos!
