### ISSUE TITLE
MirrorTexture.hx:18: characters 14-65 : iron.data.CameraData has no field mirror

### ISSUE THREAD

**Issue by NinthJake** [armory3d/armory#611]
"Programs\Blender\Armory\armsdk\armory\Sources/armory/trait/MirrorTexture.hx:18: characters 14-65 : iron.data.CameraData has no field mirror"

Armory version 0.3.0 Windows x64
Target: krom, GAPI: openGL

All the examples refuse to compile because of this error.

**Comment by luboslenco** [comment]
I am confused, there should be no `armsdk\armory\Sources/armory/trait/MirrorTexture.hx` file in 0.3. What is your setup? Regular itch.io 0.3 build or git clone?
