### ISSUE TITLE
"Spawn Object" node only working ~12 times + looking direction makes a difference

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#613]
This drives me insane. 
https://www.youtube.com/watch?v=V_yBe7GEY04
(I did not press space) After that no more objects spawn
[spwnobj.zip](https://github.com/armory3d/armory/files/1947376/spwnobj.zip)

**Comment by luboslenco** [comment]
Was a culling issue, pushed a fix at https://github.com/armory3d/iron/commit/a3c260d9c8dd07081acc9d1eb23023ac98b45209. Hopefully it works now and restores your sanity!

**Comment by Simonrazer** [comment]
Yes it works now, thanks!
