### ISSUE TITLE
Viewport glitch when renderer type set to "Deferred" for many projects

### ISSUE THREAD

**Issue by Gerkinfeltser** [armory3d/armory#615]
**Problem:**
When playing some/many projects in the viewport, the viewport player does not finish its start up routine. There are no reported errors in the console even claiming `"Finished in ..."` but the info bar "Building" indicator doesn't progress past 50% and the stop/pause never turn into actual buttons, remaining only as just unpushable text and icons. The game itself runs but there is no way to end it short of killing blender and graphical glitches can often be observed. The graphical glitch generally appears as a sort of silhouette of the Blender infobar with the before mentioned "Building" progress bar cut out of it. You can see a screenshot of the issue in action below.

**Background:**
I've been confounded by this frequently occurring issue but was never able to pinpoint a cause or get a solid repro until loading a few of the armory example files. I've found that both the [particles's hair.blend](https://github.com/armory3d/armory_examples/blob/master/particles/hair.blend) and [voxelgi_teapot's blend file](https://github.com/armory3d/armory_examples/blob/master/voxelgi_teapots/teapots.blend)s exhibit this behavior for me when loading the untouched github files.

**Workaround:**
In finding a consistent repro, I found the work-around to make these projects run "correctly" is to toggle the renderer Armory Render Path section of the Rendering tab from "Deferred" to "Forward". I'm still unsure as to the underlying cause of this issue...

**The glitch & button-less buttons:**
![2018-04-26_22-45-28](https://user-images.githubusercontent.com/1477787/39361917-76e13b46-49f2-11e8-8672-3a46e8d11e1f.png)

**With "Forward" renderer all is good:**
![blender_2018-04-26_22-44-52](https://user-images.githubusercontent.com/1477787/39361923-7d85eeec-49f2-11e8-8a6d-1c3191118a4a.png)

**Comment by SCLDGit** [comment]
Just raised a similar issue. On my end, it is caused by enabling TAA. Disabling TAA causes the issue to go away. It would seem to be some kind of framebuffer issue.

**Comment by Gerkinfeltser** [comment]
Thanks for an updated workaround @SCLDGit! I shall close this one and defer to your [issue](https://github.com/armory3d/armory/issues/623) as it seems to have gotten the attention of Lubos.
