### ISSUE TITLE
Sounds not playing for more than a couple seconds

### ISSUE THREAD

**Issue by Ejnallid** [armory3d/armory#617]
*(optional - drag & drop zipped .blend file here)*
Sounds don't seem to play for more than a couple seconds in Armory and is at a lower pitch. Simonrazer had a look and he found the same as well as the sound example. I would appreciate this being done ASAP if possible. Thanks

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/Kode/Krom/pull/70, will have to compile new Krom binaries next.

**Comment by luboslenco** [comment]
Updated a patched Windows Krom binary: https://github.com/armory3d/Krom_bin/blob/master/win32/Krom.exe
This can be copied into `Armory/armsdk/Krom/win32`.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/634.
