### ISSUE TITLE
"physics.getContacts" only returns contacts with dynamic objects

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#619]
I think there should be a way to include not-dynamic objects (like the terrain the Player walks on, hoped the trigger boy down there does that but doesn't) in this array to for example see if a foot objects makes contact with anything so he is allowed to jump.
Would be extremely handy in a FPS script, seems like you (@luboslenco ) didn't find a solution for this as well :) (These are the remains of a FPS template script, removed and added some stuff (but mostly removed))

[usecase.zip](https://github.com/armory3d/armory/files/1968377/usecase.zip)

(Also if I parent the "Jumper" cube to the Player it moves with it but X and Y axis are swapped. Not sure if my programming mistake somewhere tho)

**Comment by luboslenco** [comment]
- Dynamic + static: seems to work now, ie. a dynamic player object should report a contact with static plane and then be allowed to jump
- Static + static: this will not report a contact point, may be a physics engine optimization
