### ISSUE TITLE
Collision with objects sometimes causes game to freeze

### ISSUE THREAD

**Issue by Ejnallid** [armory3d/armory#621]
*(optional - drag & drop zipped .blend file here)*
When colliding with objects the game will sometimes freeze the screen even if the required actions such as playing a sound is carried out.

This only happens on some objects with normal traits such as rigid body applied

**Comment by luboslenco** [comment]
Sorry need more info to reproduce and fix, example blend would be handy.

**Comment by luboslenco** [comment]
Appears to no longer freeze on git armory.
