### ISSUE TITLE
Last sound played will play again when colliding with an object

### ISSUE THREAD

**Issue by Ejnallid** [armory3d/armory#622]
*(optional - drag & drop zipped .blend file here)*
When colliding with an object so that something else will happen, the previous sound played will play again on this collision regardless of whether it or another sound ought to be played.

This only happens on objects that have the node tree selected as a trait.

As well as playing the sound I found it also executes the node related to the sound such as adding 1 to a value

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/621.
