### ISSUE TITLE
TAA causes inability to stop Armory or otherwise interact with Blender with playing in viewport

### ISSUE THREAD

**Issue by SCLDGit** [armory3d/armory#623]
When enabling TAA and playing in viewport, graphical errors occur and I am unable to stop playback without restarting Blender.

GTC 780Ti and GTX 980, both with latest drivers.
*(optional - drag & drop zipped .blend file here)*
![armory error](https://user-images.githubusercontent.com/20480896/39830405-6135f952-538f-11e8-9820-6a44aa161c4b.PNG)

**Comment by luboslenco** [comment]
Viewport player is being reworked for b2.8 in armory 0.4, this particular glitch should be gone.
