### ISSUE TITLE
Tessellation leaves gab on meshes 

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#625]
Tessellation leaves gabs at the faces of all meshes I try but the example one. If there is special way the UVs/the mesh has to be made, please but that in the documentation!
[face gab.zip](https://github.com/armory3d/armory/files/1992728/face.gab.zip)
![s](https://user-images.githubusercontent.com/30187223/39885435-e46456d6-548c-11e8-94af-a7029b39978b.PNG)

**Comment by Megalomaniak** [comment]
Could you perhaps also include some information about the hardware this occurs on in case someone can't confirm on their machines(not that I have tested).

**Comment by zauberparacelsus** [comment]
do all the faces have edge splits on them?

**Comment by Simonrazer** [comment]
win 10 gtx 1060 6gb i5 6500
nope no modifiers no nothing everything just done in editmode.

**Comment by Simonrazer** [comment]
That's it, it was set to Flat while it seems like only Smooth is working properly. Or maybe Flat is supposed to do that but I can not imagine when you would want that effect. Thanks a ton for figuring this out! Gonna leave this open and let @luboslenco decide what to do about it ("fix"/but that in manual).

**Comment by Megalomaniak** [comment]
Right, as I suspected. Tessellation is dependant on surface normals and flat shading splits the normals.

**Comment by Megalomaniak** [comment]
@luboslenco Unless you actually consider this a big bug, I think it's safe to close this?

**Comment by Megalomaniak** [comment]
@luboslenco Maybe include the image from the OP in documentation as well(if it's OK with @Simonrazer)?
