### ISSUE TITLE
Congratulation on achieving the patreon goal !!!

### ISSUE THREAD

**Issue by gamergamesz** [armory3d/armory#626]
With this goal achieved, the Armory3d has unlocked the new community members and list of upcoming issues and all that great stuff with it! Hope to see the armory among big engine soon....!

![screenshot 8](https://user-images.githubusercontent.com/13883739/40122866-638c23f8-5942-11e8-8b50-0413f1316e75.png)

CONGRATULATION and have a great day!!!

**Comment by Simonrazer** [comment]
![c](https://user-images.githubusercontent.com/30187223/40128734-a295b8a8-5932-11e8-992d-4770615abb5a.PNG)
I would wait at least a month until everyone that only subscribed to grab it for 10$ instead of 50$ is gone.

**Comment by gamergamesz** [comment]
Sob! Sob!

**Comment by Simonrazer** [comment]
Yay it is back up to 1602$.

**Comment by gamergamesz** [comment]
I am 10 minute late to post this update sob!

**Comment by luboslenco** [comment]
Insanity! 🎉 Will see how apocalyptic the transition will be, have to survive that.:)

**Comment by slightfx** [comment]
Hi @luboslenco, when do you plan on releasing the engine?
