### ISSUE TITLE
Shutdown node only works if active on first scene run

### ISSUE THREAD

**Issue by Ejnallid** [armory3d/armory#627]
The shutdown node only seems to work on the scene first run. For example, if you make a node tree and apply it to a scene which once initialises waits a couple seconds and then shutsdown, this will only work if this scene is the first run. It wont work if you are on a different scene and then you set the scene to the one with the shutdown node.

At least thats what I can find from it.

Example blend below shows it working when Win scene is played first but not when redirected to it from Game when the enemy is touched.

[GameWorking.zip](https://github.com/armory3d/armory/files/2009937/GameWorking.zip)

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/armory/commit/2610dca848f8944a2ca1663326684e8572ac76c9, thanks for report.
