### ISSUE TITLE
Opacity in Armory PBR not working

### ISSUE THREAD

**Issue by E25543** [armory3d/armory#63]
Hello,

On Windows7, creating a material "Armory PBR", I was unable to change Opacity.

1 = total opacity
<.99 = no opacity at all.

Textures with alpha maps are very useful. If someone knows a workaround, please let me know. Otherwise, I think something is missing.

**Comment by luboslenco** [comment]
To enable it, in *Camera data - Armory props - Render path* select *deferred_path_high*. Obviously there is no way to intuitively discover this, working on render path generator which will enable needed features automatically(and more) to fix it.

**Comment by E25543** [comment]
I did some testing.

Alpha test: turned opacity of 0.5.

Armory PBR: renders pitch black;
Armory PBR.001: renders pitch black;
Deferred_path:  renders pitch black;
Deferred_path_high: renders pitch black;
Deferred_path_low: renders fine; Alpha test failed;
Forward_path: renders fine; Alpha test failed;
Forward_path_low: renders fine; Alpha test failed; Causes other texture flicker (blue, black);
Hybrid_path: renders pitch black;
pathtrace_path: does not compile.
VR_Path: renders fine; Alpha test failed;

I hope that helps. Don't worry about polishing things. Make Armory solid as it's really a fantastic project. We will teach others how to do stuff, don't worry. 

If you need some testing, don't hesitate!

**Comment by E25543** [comment]
Just read posts about new player. It will probably fix these issues.

**Comment by JeannotLandry** [comment]
Transparency is working for me. As long as the deffered poth is set to high, there is a few things that are un-intuitive, but I got it working!

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armory/issues/87
