### ISSUE TITLE
Browser export broken

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#630]
Browser export seems to be broken even in empty .blends. Happens on Win 8.1/10 gt(x) 620m/1060
Here the console output of the material_baked example:

![c](https://user-images.githubusercontent.com/30187223/40277701-099cfa9a-5c24-11e8-9996-1f904a99d7b7.JPG)

**Comment by sh-dave** [comment]
Seems to be an old Kha version, try updating it.

https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/SystemImpl.hx#L1065

**Comment by Simonrazer** [comment]
Thanks, adding that method to this file "Armory03_win64\Armory\armsdk\Kha\Backends\HTML5\kha" made it work! Probably missing a lot of other stuff to actually make a pen work but I do not care about that.

**Comment by luboslenco** [comment]
Also fixed out of the box in 0.4.
