### ISSUE TITLE
Armory Installation: Docs aren't any clear (urgent)

### ISSUE THREAD

**Issue by abhaskumarsinha** [armory3d/armory#633]
Hello, everyone here,

I'd like to draw your attention to the Armory Installation.

I downloaded the armory from the GitHub source and then according to instructions, 

Then I extracted the contents of it and I tried to see any blender.exe in it, but there wasn't any. Please help, it's a bit urgent case.

Also, I'm amazed to see the whole stuff was under 1 mb,

I'd appreciate if you'd help me know what's the wrong thing I did and can help me to figure the correct way out.

Also, I wanted to know if it'd support opengl2.x graphics card or not

Thanks in advance,
Best Regards

**Comment by Simonrazer** [comment]
Armory is not released yet! Lubos is still working on a new release, it will be out soon. What you downloaded was the sourcecode, which you will have to compile, but you will also have to include Irno and Kha, so I have no idea how to do this.

**Comment by Wigatron** [comment]
I am looking forward to Lubos releasing the new build. I imagine there is a fair amount of work involved.

**Comment by Wigatron** [comment]
Any update on when this may be release?

**Comment by garyritchie** [comment]
The downloads page has been updated: http://armory3d.org/download.html
There are versions for Blender 2.8 and 2.7.

**Comment by luboslenco** [comment]
Also, to clone armory from git check here: http://armory3d.org/manual/#/dev/gitversion?id=manual-clone.
