### ISSUE TITLE
Sound Broken on Krom Linux

### ISSUE THREAD

**Issue by Ejnallid** [armory3d/armory#634]
*(drag & drop zipped .blend file here)*
I have been trying to add sound to my game by opening the sound, giving it a fake user, and then selecting it in the play sound node. However, the sound does not at all play when on my Mac. I have also tried the sound example and that does not work.

When I tried to play sound on Windows, it played the very first bit of the sound and then stopped without playing all the way through. This was both for my own sound as well as the example sound blend.

This is a major stopping point at the moment.

**Comment by luboslenco** [comment]
Not sure which armory version you are on, but can you try the [sound example](https://github.com/armory3d/armory_examples/tree/master/sound) with 0.4 build on Windows? Is that not working either?

**Comment by adriansnetlis** [comment]
Regarding sounds:
On Linux when I run the third person template in Krom, the sound sometimes randomly either works or doesn't work. It appears to be totally random.

**Comment by zicklag** [comment]
I have the same problem with all of the armory shooter templates that sound is broken on Linux, but I think it is only for Krom. I haven't spent the time to compile a C++ build recently, but last I checked I'm pretty sure it worked. It also works in the browser.

**Comment by luboslenco** [comment]
Fixed at https://github.com/Kode/Krom/pull/123.
