### ISSUE TITLE
Texture Arrays

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#635]
Would it be possible to implement support for Texture Arrays?

Texture Arrays would (as I understand it) allow for textures in materials to be addressed by index instead of explicitly, which in turn would make materials more reusable, and would also make things more amenable to render batching and in theory reduce the amount of draw calls.

Though, texture arrays do have a limitation, in that all of the textures must have the same format (ie: they all must have the same dimensions and same channels).

Not sure how this would play out in the cycles node, or if it would be possible to use in that.

**Comment by luboslenco** [comment]
Kha can do [texture arrays](https://github.com/Kode/Kha/blob/master/Sources/kha/graphics4/Graphics.hx#L35) nowadays if one wishes to access that manually. For swapping material textures - [material params](https://github.com/armory3d/armory_examples/tree/master/material_params) is probably the easiest solution.
