### ISSUE TITLE
Problem with game templates with the V0_4 lite win64

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#638]
I start to put info here on the forum (and found the link for issues later ) 
http://forums.armory3d.org/t/v0-4-release-lite-game-templates-bug/1055?u=didier

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Are you able to locate the `SimpleRotateObject.hx` file in your extracted sdk?
https://github.com/armory3d/armory/tree/master/Sources/armory/trait

**Comment by Didiercode** [comment]
Yes
![image](https://user-images.githubusercontent.com/20455592/40905492-56561c02-67de-11e8-9e71-684c7aeaacb4.png)

**Comment by luboslenco** [comment]
Probably somehow related to https://github.com/armory3d/armory/issues/639.
