### ISSUE TITLE
Build Fail - 64bit Linux, Armory Builds 3 & 4

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#64]
```
Use Avastar's native template system
read blend: /home/zauber/Armory/ArmoryTest.blend
Error, region type 4 missing in - name:"Action", id:12
Scene built in 0.002378225326538086
```

**Comment by luboslenco** [comment]
Hi,

Is this the full output? Blend file is always helpful if possible.

**Comment by zauberparacelsus** [comment]
Full output is as follows:

```
zauber@daedalusMK3:~/Desktop/blender-2.77a-linux-glibc211-x86_64$ ./blenderconnect failed: No such file or directory
Read new prefs: /home/zauber/.config/blender/2.77/config/userpref.blend
found bundled python: /home/zauber/Desktop/blender-2.77a-linux-glibc211-x86_64/2.77/python

/home/zauber/.config/blender/2.77/scripts/addons/generic_note.py:61: SyntaxWarning: name 'TW' is assigned to before global declaration
  global TW
archimesh: added to phytonpath
archimesh: Imported multifiles
read blend: /home/zauber/Armory/ArmoryTest.blend
Error, region type 4 missing in - name:"Action", id:12
Scene built in 0.0013649463653564453
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.arm).
Exporting asset 1 of 1 (deferred_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Plane.001.arm).
Exporting asset 1 of 1 (deferred_path_low.arm).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.vert.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Haxe compiler error.
Build failed, check console
```

And I've attached a copy of the .blend file.


[ArmoryTest.blend.zip](https://github.com/armory3d/armory/files/614706/ArmoryTest.blend.zip)

**Comment by luboslenco** [comment]
Thanks! Seems to work here so far, also tried running in separate window. Will boot to Linux tonight, hopefully can reproduce it there.

Another idea, maybe Armory does not play well with some add-ons?

![test](https://cloud.githubusercontent.com/assets/3685704/20648562/c6e6c068-b4aa-11e6-8be8-29027788d6bb.jpg)

**Comment by zauberparacelsus** [comment]
> Another idea, maybe Armory does not play well with some add-ons?

Could be.  Here's a list of the addons I'm using, though I'm not sure which ones blender has enabled by default:
- 3D View: Display Tools
- Add Curve: Extra Objects
- Add Curve: IvyGen
- Add Curve: Sapling Tree Gen
- Add Mesh: Archimesh
- Add Mesh: Extra Objects
- Compositing: Real Camera (disabling this one, it was a POS)
- Import-Export: Autodesk 3DS Format
- Import-Export: BioVision Motion Capture (BVH) format
- Import-Export: FBX Format
- Import-Export: Import Images as Planes
- Import-Export: STL Format
- Import-Export: Scalable Vector Graphics (SVG) 1.1 Format
- Import-Export: Standard PLY format
- Import-Export: UV Layout
- Import-Export: Wavefront OBJ format
- Import-Export: Web3D X3D/VRML2 format
- Mesh: Bsurfaces GPL Edition
- Mesh: Inset Polygon
- Mesh: LoopTools
- Mesh: MeshLint: Like spell-checking for your meshes
- Node: Generic Note Node
- Object: Avastar
- Object: Cell Fracture
- Object: Maelstrom Height Handler (custom addon I used for making my webcomic)
- Render: Auto Tile Size
- Render: Baketool
- Render: Cycles Render Engine
- Render: POV-Ray 3.7
- Rigging: Rigify
- UV: Bake UV-Texture to Vertex Colors
- UV: Copy and Paste UV

**Comment by zauberparacelsus** [comment]
Well, I removed a few addons.  Real Camera, Render Music (not listed above) and one of two copies of archimesh (I had manually installed it before it was included in blender).

Play in Viewport still does not work, however.  I just get the following output on my command line, which does not reveal any problems:

```
zauber@daedalusMK3:~/Desktop/blender-2.78a-linux-glibc211-x86_64$ ./blender
Read new prefs: /home/zauber/.config/blender/2.78/config/userpref.blend
found bundled python: /home/zauber/Desktop/blender-2.78a-linux-glibc211-x86_64/2.78/python
version 3 imported

/home/zauber/.config/blender/2.78/scripts/addons/generic_note.py:61: SyntaxWarning: name 'TW' is assigned to before global declaration
  global TW
archimesh: Imported multifiles
read blend: /home/zauber/Armory/ArmoryTest.blend
Scene built in 0.0012497901916503906
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.arm).
Exporting asset 1 of 1 (deferred_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Plane.001.arm).
Exporting asset 1 of 1 (deferred_path_low.arm).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.vert.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-image.frag.glsl).
Compiling shader 3 of 8 (painter-image.vert.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-colored.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Haxe compiler error.
Build failed, check console
```

**Comment by luboslenco** [comment]
Somehow Haxe compiler has trouble. Is this happening on stand-alone Blender or the bundled one with Armory? (or both?)

**Comment by zauberparacelsus** [comment]
Standalone blender, I think?  I didn't realize a copy of blender was bundled with Armory

**Comment by zauberparacelsus** [comment]
I get the same error on the bundled copy

**Comment by luboslenco** [comment]
Just tested on Linux Mint and it works there (also tested Ubuntu earlier). What distro are you using? Have to figure this out.

**Comment by zauberparacelsus** [comment]
I'm using 64-bit Ubuntu 16.04, with Blender version 2.78a

**Comment by zauberparacelsus** [comment]
I've tried running Armory on blender after having done a factory reset on blender, so it had all default settings.  Same problem :-/

**Comment by zauberparacelsus** [comment]
My installed haxe version was out of date (3.1.x), so I updated it to 3.2.1. Still having the same problem.

Is Armory capturing/hiding the output of the Haxe compiler and just reporting its own output?  And if so, is the haxe compiler's output recorded anywhere that it can be viewed?

**Comment by luboslenco** [comment]
Armory, (ie. Kha) runs at Haxe 3.3 minimum. But installed Haxe version should not have anything to do with Armory, it includes it on it's own.

Can you locate the compiler at `Armory/armsdk/linux64/app/extensions/kha/Kha/Tools/haxe/haxe-linux64`? What output do you get running `./haxe-linux64` from terminal in that folder?

**Comment by zauberparacelsus** [comment]
the linux64 directory does not have an app subdirectory.  There is a bin subdir, but it only has kodestudio under it.

**Comment by zauberparacelsus** [comment]
Okay, the app directory was actually under the linux64/resources directory.

Running ./haxe-linux64 results in a segmentation fault.

**Comment by luboslenco** [comment]
I apologize, updated previous post with missing 'resources' dir.

**Comment by zauberparacelsus** [comment]
I ran haxe-linux64 under GDB, and got this:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff66b7202 in GC_find_limit_with_bound ()
   from /usr/lib/x86_64-linux-gnu/libgc.so.1
```

Then I enter continue...
```
Continuing.
[New Thread 0x7ffff647c700 (LWP 4753)]
[New Thread 0x7ffff5c7b700 (LWP 4754)]
[New Thread 0x7ffff547a700 (LWP 4755)]
[New Thread 0x7ffff4c79700 (LWP 4756)]
[New Thread 0x7ffff4478700 (LWP 4757)]
[New Thread 0x7ffff3c77700 (LWP 4758)]
[New Thread 0x7ffff3476700 (LWP 4759)]

Thread 1 "haxe-linux64" received signal SIGSEGV, Segmentation fault.
0x00007ffff2834245 in neko_val_id () from /usr/lib/libneko.so.2
```

**Comment by luboslenco** [comment]
I tried installing Haxe 3.2.1 on my Ubuntu box to see if there are conflicts but it still seems to run fine here.

Can you try to temporarily uninstall Haxe? Did you try downloading the SDK again in case of corrupted files?

**Comment by zauberparacelsus** [comment]
I downloaded it, but before unpacking it, I compared the prior preview03 archive with the fresh one, and they both had different sha512 hashes.  However, I still have the same problem after unpacking the fresh archive.

Uninstalling Haxe had no effect either.

**Comment by luboslenco** [comment]
That is odd. Kha now uses latest Haxe 3.4.0 rc1, I will update Armory to include this (in the next build if no issues appear) and we will see if that helps.

**Comment by zauberparacelsus** [comment]
Issue has not gone away with Build 4

**Comment by luboslenco** [comment]
Sorry, did not manage to update Kha in time:/ Working on it now.

**Comment by zauberparacelsus** [comment]
Not entirely sure, but I think the issue may be because I am using an older Ubuntu (16.04), so the system libs may not be what haxe is expecting.  That probably explains the GDB output I posted above.

**Comment by zauberparacelsus** [comment]
I am currently upgrading my system to Ubuntu 16.10.  Two months is probably long enough for most of the post-release bugs to have been shaken out, lol.  Once the upgrade is done, I'll report whether or not it has fixed the build errors in Armory.

**Comment by zauberparacelsus** [comment]
Problem continues after upgrading to Ubuntu 16.10 :-/

**Comment by zauberparacelsus** [comment]
Hmm.  Based on the GDB output, it looks like it's using my system's installed version of Neko.  A quick check seems to indicate that the Armory SDK does not package its own Neko.

Perhaps the real problem is that it is trying to use an incompatible version of Neko?

**Comment by zauberparacelsus** [comment]
Problem fixed on my end.  The real problem was that I did not have libgc-dev and neko-dev installed.

**Comment by zauberparacelsus** [comment]
Additional note: libgc-dev is not required to make Armory work for me.  Armory continues to work with libgc-dev uninstalled.

The neko-dev package is still required, however.  Perhaps the neko headers can be packaged with Armory to prevent this issue in the future?

**Comment by luboslenco** [comment]
Build 6 will now run out of the box on freshly installed Ubuntu 16.10, but I am still unsure about the neko issues.

**Comment by luboslenco** [comment]
Using the latest Kha with bundled Haxe now.
