### ISSUE TITLE
Issue With Shadows

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#640]
I noticed a problem with shadows in Armory 0.4 (Blender 2.8). It seems to be a problem with object frustum culling or shadow clipping planes.

Here's a video to explain the issue (occurs by default in the third person template):
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/V8H7-2HtYlc/0.jpg)](https://www.youtube.com/watch?v=V8H7-2HtYlc)

**Comment by luboslenco** [comment]
Added `Armory Render Path - Shadows - Cascade Bounds` property which will scale up the bounds to prevent this, at a cost of shadow quality.
