### ISSUE TITLE
Armory 0.4 doesnt run

### ISSUE THREAD

**Issue by mushroomeo** [armory3d/armory#641]
*(drag & drop zipped .blend file here)*

downloaded armory 0.4 on blender 2.79 and 2.8 and both doesnt work..
on 2.79 and 2.8 version the play / start button doesnt appear so i deactivated all addons and still didnt run..

then i downlaoded official blender 2.8 and installed armory as addon and the button START appeared but if i click on it then the armory options in properties > Render options appears. but still doesnt run

[armory start problems.zip](https://github.com/armory3d/armory/files/2067981/armory.start.problems.zip)

**Comment by luboslenco** [comment]
Checking it out at existing issue at https://github.com/armory3d/armory/issues/639.
