### ISSUE TITLE
Installing Add-on is not working...

### ISSUE THREAD

**Issue by AdityaSrivastava2819** [armory3d/armory#645]
Hi, I just downloaded Armory version 0.4 for Blender 2.79. I wanted to install it as an add-on. I followed the steps that were written in the docs and tried installing the add-on in blender (that I had downloaded from blender.org) but it doesn't work. However, in the Blender.exe that came with the Armory download, the SDK works. Please look into this. There is no sense in having multiple copies of the same software on the same computer. Thanks! <3
[Issue.zip](https://github.com/armory3d/armory/files/2071396/Issue.zip)
That is the .blend file.

**Comment by AdityaSrivastava2819** [comment]
Yes, the panels do not show up. I removed and reinstalled add-on various
time but the panels didn't show up.

**Comment by luboslenco** [comment]
Sorry I need all the details - any errors in the console? Can you paste a screenshot of armory in add-on preferences? In https://github.com/armory3d/armory/issues/644 it apparently works, only the node search is broken, wonder what is causing it in this case.

**Comment by AdityaSrivastava2819** [comment]
Here, the add-on panel and console
![2018-06-06_19-35-02](https://user-images.githubusercontent.com/37951362/41043377-73a731f8-69c1-11e8-82fe-36d2f9ad68a7.png)
#641 
In my armory bundled SDK is not shown in add-on preferences.

**Comment by AdityaSrivastava2819** [comment]
Alright! Finally it's working!!!!! <3
