### ISSUE TITLE
Can the Voxelization be brought down to OpenGL 4.4

### ISSUE THREAD

**Issue by AdityaSrivastava2819** [armory3d/armory#647]
*(drag & drop zipped .blend file here)*
Hi, I have a GPU with OpenGL 4.4. I can't use the voxel illumination with it so I was just asking uh it can be brought down a little. (I'm just behind by 0.1)  :'(

**Comment by luboslenco** [comment]
What GPU and OS? Is Voxel AO not working either? (For example the [playground & tanks turorials](https://github.com/armory3d/armory_tutorials).)

**Comment by AdityaSrivastava2819** [comment]
Hi, I have NVIDIA GEFORCE 730 and Wondows 10. I was just checking the
Armory docs so that I can actually make something and I saw that
Voxelization required OpenGL 4.5. And I have OpenGL 4.4. I yet have to try
it. I'll try and tell you about it by 1:30 P.M. GMT.
Thanks
Aditya

**Comment by gamergamesz** [comment]
well voxelgi is not working for me even i have 4.5 gl (960m), win10. It just hang and shows not responding in krom, in both 2.79 and 2.8

**Comment by AdityaSrivastava2819** [comment]
Hi, I just checked and Voxel AO works.

**Comment by luboslenco** [comment]
@gamergamesz is Voxel AO working for you or also not responding?

**Comment by gamergamesz** [comment]
Ao is working fine for me

**Comment by gamergamesz** [comment]
Sorry, Voxel GI works for me on a new scene in b2.79 and 2.8 when the scene is small, but it did not work on me for third and first person template as i guess it is a bit heavy for that
