### ISSUE TITLE
New Traceback (most recent call last) error

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#65]
This one has to do with the cathedral again. Different error this time. 64-bit version of Build 3 Windows.

![capture](https://cloud.githubusercontent.com/assets/15915424/20651557/ba2d391e-b4b5-11e6-9e4e-d80e790e4a5f.JPG)

**Comment by luboslenco** [comment]
Looks like the last one posted in: https://github.com/armory3d/armory/issues/55#issuecomment-262087759

Also, did you try to remove all stuff from compositor nodes? Maybe something is not playing well with Armory there.

**Comment by George-the-1st** [comment]
Will try. Attempting soon.

**Comment by luboslenco** [comment]
Oki, please continue in the linked issue.
