### ISSUE TITLE
What are the Armory_04 packages on itch.io?

### ISSUE THREAD

**Issue by Sondro** [armory3d/armory#651]
Hi, I keep trying to download the  28/27 files but I keep getting disconnected and it doesn't support resuming.

Is it possible to get the 7z off github or can you mirror to gumroad which doesn't disconnect you and supports resuming.

Thanks.

**Comment by luboslenco** [comment]
Hello, you could try cloning the sdk manually from github. Check here:
http://armory3d.org/manual/#/dev/gitversion?id=manual-clone

Let me know if that works.

**Comment by Sondro** [comment]
Is it just the armsdk?

I already have that cloned as part of armory, but haven't tried doing anything with outside of zui/kha stuff.

Will try to go through some tutorials.

Thanks.

**Comment by luboslenco** [comment]
Yes, armsdk contains several submodules.
