### ISSUE TITLE
Krom Error on start on Windows 7 64bit

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#652]
Krom error on start on Windows 7 64bit, 8GB ram, GTS 450 - (Armory_04_win64_b27)

![krom_error_on_start](https://user-images.githubusercontent.com/39986875/41027671-f1146916-6977-11e8-951d-07b13b911b97.png)

Armory_04_win64_b28 (krom work only inside Blender 2.8 Window)

![blender2-8krom](https://user-images.githubusercontent.com/39986875/41028326-710d8a66-6979-11e8-9568-20a7d81cb405.png)

Export to Website HTML5 work fine

Regards :)

**Comment by nanderson00** [comment]
I get this error too. Windows 7, 64 bit Build 04 2.8

**Comment by luboslenco** [comment]
If we are lucky it should be fixed in the latest `Armory_04b_win64` build.
(Related: https://github.com/Kode/Kore/commit/29f6dee0f9a91e1e6ad01f9badde80e00b588191)

**Comment by Megalomaniak** [comment]
I can confirm as fixed on my side.

**Comment by Dzynek** [comment]
This problem has been fixed, thanks :-)
