### ISSUE TITLE
b28 No Output Node and Only Principlied Volume Available for Surface Materials.

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#653]
This bug appeared out of nowhere. All the shaders except for principlied volume as well as output node disappeared from list of shaders in Armory for surface materials (world materials still have everything and function fine). If I switch render engine to Eevee or Cycles, I can access those nodes. Principlied BRDF and output nodes do seem to work, but the Transparent BRDF shader doesn't work - it only removes any color saturation from base color.

**Comment by luboslenco** [comment]
Should be non-issue now in 0.6 (using standard Blender).
