### ISSUE TITLE
Node Labels lead to strange behaviour

### ISSUE THREAD

**Issue by zaethan** [armory3d/armory#654]
If you assign the same label to two different nodes, they will somehow share their value.
So if you have two different Integer nodes which you label as "Index" they will always be the same integer.
If you have a more complex node setup, this can mess things up quite a bit if you only wanted to keep it somewhat organized by labelling the nodes (so you know why you've put them there).
![screenshot_20180606_202015](https://user-images.githubusercontent.com/39460066/41051390-4ab8b452-69b6-11e8-9c58-1dc095ceab3a.png)
This prints out "0" after one second and "2" after 3 seconds although I have never modified the variable of the lowest Integer node.
![screenshot_20180606_202352](https://user-images.githubusercontent.com/39460066/41051585-d57151a8-69b6-11e8-8901-e9b8bc2daf47.png)
This is the upper Integer.
![screenshot_20180606_202414](https://user-images.githubusercontent.com/39460066/41051589-d81f33ca-69b6-11e8-80f2-a2ceebaff55e.png)
This is the lower Integer.
They clearly have a different name while sharing the same label...

**Comment by Simonrazer** [comment]
I think the value isn't assigned to a specific node but rather its name or a generated one if there is none, so the two Integers labeled Test will always have the same value as each other depending on which the last one was set two. IMO this is more a feature then a bug because if you have really huge setups and you need to change a variable that is far away you can simply name it and use it there without having to rout the cables through the whole tree.

**Comment by zaethan** [comment]
I can see your point. Using it like that, it can actually quite useful.
However, I still think that this could become problematic, especially when you want to process information instead of storing variables for later use. I noticed it when doing some vector math and both nodes were labelled "Direction". They produced the same output although they had different inputs. Here is a quick example I put together.
![screenshot_20180607_150919](https://user-images.githubusercontent.com/39460066/41101762-5f8dda06-6a65-11e8-9605-bfa0adf965c4.png)
Based on which one was evaluated first, I get either "0 0 0 0 0 0" or "3 4 5 3 4 5" although they both actually have different inputs and thus "should" produce different results...

**Comment by luboslenco** [comment]
Pushed a patch, logic nodes are no longer linked by labels. Instead, set the `Node Editor - Properties - Armory Logic Node - ID` property to share data between nodes. Should make it more obvious and prevent strange behavior.

Added an example:
https://github.com/armory3d/armory_examples/blob/master/logic_basics/linked_variable.blend
