### ISSUE TITLE
Feature: Using Subdivision Surface for LOD

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#656]
Right now, Armory allows you to make LODs based on the Decimate modifier.  I think it would be a good idea, however, to allow it to also create LODs based on the Subdivision Surface and Multiresolution modifiers.

**Comment by zauberparacelsus** [comment]
It occurs to me that this could probably be done by taking advantage of tessellation, especially if the Subsurf modifier can be used to drive the tessellation.  Even more so if the Crease edge property is used.

**Comment by luboslenco** [comment]
To achieve this (and keep things simple) assign lod meshes manually for now, instead of using auto-generate.
