### ISSUE TITLE
Krom shows black screen, no errors reported

### ISSUE THREAD

**Issue by Sylfa** [armory3d/armory#659]
Same effect on both new blend file and the playground tutorial blend using the medium path, the Krom player shows up but is just black, no error in the blender system console.

This is using Armory03_win64 download on quite a weak system: Win7 64bit, 4Gb ram, Nvidia GeForce GTS 240

Tried installing Haxe to see if that made any difference, can't use the Armory_04_win64_b28 download as Blender 2.8 fails to run on my machine in it's current state.

#652 may be related, but no error popups are happening

**Comment by luboslenco** [comment]
Any progress using the latest `Armory_04b_win64_b27` build?

**Comment by Sylfa** [comment]
Armory_04b_win64_b27 seems less erratic, but on both 03 and 04b it works if I swap to DirectX11 (though not every time on the older version).

Neither version work on Auto nor OpenGL however, the bigger issue being that it believes OpenGL should work and displays a black screen instead of giving an error.

My apologies about the late response, real life got in the way.
