### ISSUE TITLE
Manjaro 17.1.10 64bit -black screens

### ISSUE THREAD

**Issue by maniutek08** [armory3d/armory#660]
Armory 04 Krom - black screen
Armory 04 Browser - OK

Armory 04a Krom - black screen
Armory 04a Browser - black screen

**Comment by maniutek08** [comment]
Edit : armory don't like linked cameras

Armory 04a Krom - black screen
Armory 04a Browser - now OK

**Comment by zaethan** [comment]
This might be related (atleast the part about the krom window):
https://github.com/armory3d/armory/issues/553
You can try the workaround for legacy shaders presented there.
Also try to use a forward instead of a deferred render path.

**Comment by maniutek08** [comment]
Legacy Shaders + Forward works. Thanks

**Comment by luboslenco** [comment]
@maniutek08 does the latest `Armory_04b_linux64` build work for you even with legacy shaders disabled?

**Comment by maniutek08** [comment]
Yes, the latest version works well now : without Legacy shaders enabled and Armory Render Path set to deferred. Great!

**Comment by luboslenco** [comment]
Hooray! 🎉 Thanks for testing!
