### ISSUE TITLE
Scene objects not visible in game

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#666]
I modified the template games third person and first person.
When i run the game all objects are invisible, only the new ones i added are visible ? 

https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/FloorInvisible.jpg?raw=true

https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/objectsInvisible.jpg?raw=true

The two projects can be downloaded here : 

[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/first_person_bug.zip](url)

[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/third_person_bug.zip](url)

**Comment by DevMagicLord** [comment]
My bad, some how in the Outliner View list , all objects was set to Restrict Rendering.
This is not a bug.

**Comment by luboslenco** [comment]
Oki, closing.
