### ISSUE TITLE
No such file or directory error on project build

### ISSUE THREAD

**Issue by grove212** [armory3d/armory#671]
I'm not sure why but that's what comes up after i save, switch to cycles and press F5. Haven't changed anything. Win 64 b27 version. Dose anybody know what's the problem?
![image](https://user-images.githubusercontent.com/40127228/41195749-0e5c9982-6c3c-11e8-83a9-ed22745797d9.png)

**Comment by luboslenco** [comment]
Does it work if you use only `a-z` characters in .blend file name? Something like `aaa.blend`?

**Comment by grove212** [comment]
@luboslenco nope

**Comment by grove212** [comment]
Though archery and fps samples work. No idea why.

**Comment by luboslenco** [comment]
Maybe an issue with permissions? Does using location like `C:\Users\user_name\Documents` work?

**Comment by grove212** [comment]
@luboslenco finally works! Thank you.
