### ISSUE TITLE
Advanced shaders (Glass, Refraction, SSS, Velvet)

### ISSUE THREAD

**Issue by Halocom** [armory3d/armory#672]
Hello, i discovered Armory recently (who seem to be very great) and i tried it but i met issues with materials creation, i have the feeling only Diffuse Shader and Glossy shader are 100% rendered as they should be, the Glass shader display nothing, the velvet shader doesn't display well, SSS shader/Refraction Shader display a diffuse shader.

It could be awesome with Armory to reproduce materials exactly like they should be ;-)

**Comment by DevMagicLord** [comment]
I agree, SSS and refraction should be working.

**Comment by adriansnetlis** [comment]
You should enable refractions and SSS in render path. Also, I would highly reccomend sticking to Principlied BSDF shader.

**Comment by luboslenco** [comment]
Linking to raytracing at https://github.com/armory3d/armory/issues/1268 for further improvements on this.
