### ISSUE TITLE
Play/Pause animation node

### ISSUE THREAD

**Issue by montedre** [armory3d/armory#673]
Wpuld it be possible to change the play animation/action node to play the action once and add a repeat checkmark?  There seem to be quite a few issues that stem from trying to use the trigger volumes and actions.  For instance trying to enter the volume and open a door and then have it close when you leave.  When you enter the volume the action repeats.  

Let me know if I am missing something.  
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Any issues doing something like this? That will pause the action as soon at it plays once.
<img width="544" alt="scr" src="https://user-images.githubusercontent.com/3685704/41198230-c319637c-6c74-11e8-8614-920cabebd093.png">

**Comment by montedre** [comment]
I have tried that as part of the what the different setups I have used.  I can just never get it to work right.

**Comment by luboslenco** [comment]
The mentioned setup is used in examples:
https://github.com/armory3d/armory_examples/tree/master/logic_gate
https://github.com/armory3d/armory_examples/tree/master/logic_triggers

Can you post your blend? Will try to see what is different.
