### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#676]
I modified the third person template player code removing the IK.
The games runs , but it freezes when i press a key or a mouse button.

The project can be downloaded here 
[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/third_person_freeze_bug.zip](url)

**Comment by luboslenco** [comment]
Restoring the removed `anim = findAnimation(object.getChild("Armature"));` line in `ThirdPersonController.hx` will work.
