### ISSUE TITLE
Type not found : Main

### ISSUE THREAD

**Issue by SauceBBQ** [armory3d/armory#677]
I launched Armory b27 and Armory b28 unpacked with 7zip (I also tried with WinRar for b27).
So I started blender in Armory various folders (b27 or b28) blender worked flawlessly until I pressed the **Play** button, (F5) 
So I rebooted my Windows 10, and again, blender asked me to watch in the console. Therefore, here is what it says:

`Armory v0.4 ($Id: 97fc5021306ba3e6d744b62e6614e853412df34b $)
OS: win, Target: krom, GAPI: opengl, Blender: 2.80 (sub 17)
Exporting Scene
Exporting mesh Cube
Scene built in 0.010529041290283203
Exported modules: []
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_CSM', '_SMAA', '_SSAO']
Running:  ['C:/Productivitee/Armory_04_win64_b28/Armory/armsdk//nodejs/node.exe', 'C:/Productivitee/Armory_04_win64_b28/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--to', 'build_Playground3/debug']
Using Kha from C:\Productivitee\Armory_04_win64_b28\Armory\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.vert.glsl).
Compiling shader 2 of 8 (painter-colored.frag.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-text.vert.glsl).
Compiling shader 6 of 8 (painter-video.frag.glsl).
Compiling shader 7 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-image.vert.glsl).
Type not found : Main

Done.
Finished in 1.0906658172607422
Build failed, check console`

_Up here is what happens when I try to play_

_The console also shows that at the beggining:_

`Read prefs: C:\Users\Pierre Garcia\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Productivitee\Armory_04_win64_b28\Armory\2.80\python
Traceback (most recent call last):
  File "C:\Productivitee\Armory_04_win64_b28\Armory\2.80\scripts\modules\addon_utils.py", line 338, in enable
    mod = __import__(module_name)
  File "C:\Users\Pierre Garcia\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\__init__.py", line 83, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__, "bpy" in locals())
  File "C:\Users\Pierre Garcia\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\developer_utils.py", line 39, in setup_addon_modules
    modules = import_submodules(names)
  File "C:\Users\Pierre Garcia\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\developer_utils.py", line 30, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "C:\Productivitee\Armory_04_win64_b28\Armory\2.80\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Pierre Garcia\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\animation_nodes\sockets\object_group.py", line 3, in <module>
    from bpy.types import Group
ImportError: cannot import name 'Group'
Read blend: F:\Productivit├®e\Armored\Playground3.blend`

*([Playground3.zip](https://github.com/armory3d/armory/files/2088107/Playground3.zip)
)*

**Comment by luboslenco** [comment]
- Try to disable animation_nodes temporarily to see if that helps
- Try to save the blend in a safe/writable path like `C:\Users\user_name\Documents\test`

**Comment by SauceBBQ** [comment]
Thanks a lot, I tried the 2nd option (only) and it works perfectly now!
(I have no animation nodes enabled)
