### ISSUE TITLE
Publish Website HTML5 - IOS not work, IE11 not work

### ISSUE THREAD

**Issue by Dzynek** [armory3d/armory#678]
Hi

I would like to report that not work: HTML5, webgl (Publish)

Not work:  Ipad IOS 11.4 on Safari and Chrome, only white page.
Not work:  IE11 on Windows 7 64bit

Work: Xiaomi MI4C Android 5.1.1, Internal and Chrome
Work: Chrome, Firefox, Windows 7 64 bit

An example download and created today 11.06.2018 (armory_examples-master, armory_04b):
[cube](http://dzynek.pl/armory3d/cube_test/)
[cube mobile](http://dzynek.pl/armory3d/cube_mobile/)
[animation](http://dzynek.pl/armory3d/animation/)
[animation mobile](http://dzynek.pl/armory3d/animation_mobile/)

Blender scenes:
[animation_monile.blend](http://dzynek.pl/armory3d/animation_mobile/animation_monile.blend)
[animation.blend](http://dzynek.pl/armory3d/animation/animation.blend)

screenshots:
![ie11-1](https://user-images.githubusercontent.com/39986875/41240477-e034f468-6d9a-11e8-9ebe-0232d79a200f.png)
![ie11-2](https://user-images.githubusercontent.com/39986875/41240479-e05d6bdc-6d9a-11e8-8332-9bf7170cbf87.png)
![ie-animation](https://user-images.githubusercontent.com/39986875/41240480-e0834172-6d9a-11e8-9803-f9040aabb2fd.png)
![ie-version](https://user-images.githubusercontent.com/39986875/41240481-e0aca882-6d9a-11e8-8900-403c923534cb.png)

**Comment by luboslenco** [comment]
Safari (iOS/desktop), Chrome (Android/desktop), Firefox and Edge should work now using git armory and render path preset set to `Mobile`.

Internet Explorer has limited extension support, you might need to disable shadowmaps in render path properties.

**Comment by Dzynek** [comment]
Test Armory_04_win64_b27 on Ipad and IOS 11.4.1 Safari not work :(

**Comment by luboslenco** [comment]
Try using [Armory Updater](https://armory3d.org/manual/#/dev/gitversion?id=armory-updater) to get the latest/git version (if you are not using that already).

I am uploading first 0.5 builds asap where it should all work out of the box, just fixing a few more bugs now.:)

**Comment by Dzynek** [comment]
Git version ( Armory Updater) works, thanks 👍
