### ISSUE TITLE
GLIBC_2.25 not found in ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by jeyfrinjulian** [armory3d/armory#679]
Hi, tested Armony with blender 2.8 not initialize and my concole report:

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /home/juliandev/Descargas/Armory/libpython3.6m.so.1.0)

error relationed with python 3.6
Help!

**Comment by luboslenco** [comment]
For Ubuntu 16.04 the error will go away if you delete the `Armory/libpython3.6m.so.1.0` file. For Ubuntu 17.10 or newer it should work right away. Hope that helps!
(Related: http://forums.armory3d.org/t/armory-b28-glibc-2-25-not-found/1136)

**Comment by jeyfrinjulian** [comment]
thanks, solved

**Comment by maximstewart** [comment]
This doesn't work for me. I get:
./blender: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by aquaristar** [comment]
Me too. How can I resolve this problem without rebuild on lower version ubuntu?
