### ISSUE TITLE
Vertex Color

### ISSUE THREAD

**Issue by xziayro** [armory3d/armory#68]
Hi, 

I'm very glad to test Armory, so far it is crazy amazing ! 
However, I have a question about shader and vertex color. Is the vertex colors are accessible in Armory? I'm currently using the vertetx color as the base color for my object but it seems not to work. Is it a bug or is it only because the vertex color are ignored in Armory? 

Regards,
Stéphane

**Comment by luboslenco** [comment]
Hello,

Really flattered you like it! I added a short page on [Vertex Colors](http://armory3d.org/manual/graphics/vertexcolors.html) to the manual. At least the simplest case of using Attribute node connected to Color should work. Let me know how it goes.

**Comment by xziayro** [comment]
Wow, thanks for this fast answer. Using invalidate cache worked !

However, now I have a problem using color ramp node. I'm using a color ramp node to modify the vertex color. if I don't use the color ramp, Armory render the vertex color corrrectly. But when the attribute node go through a color ramp node , everything is the color of the fisrt slot (i.e. as if the input value of the color ramp node is 0). I tested with some other input for the color ramp (for instance, a geometry->position node) and it does the same. So it's not a problem with the Attribute node but rather with the color ramp.

Any hint on this matter?

**Comment by luboslenco** [comment]
Ah, have to improve the cache mechanism.

For the color ramp node(and most of the nodes), that's where the preview struggles. Focusing on a general issues for one more build(2 weeks). After that the plan is to finish the new material parser and make material system actually usable.:)

**Comment by xziayro** [comment]
Ok, i'll wait until then so. I'll parse directly the colormap into the vertex colors for now. 

Thanks again!

**Comment by luboslenco** [comment]
No prob! Shoot me with more issues & feedback anytime.
