### ISSUE TITLE
Support for more than one UV-Map (and vertex-colors)

### ISSUE THREAD

**Issue by 8BitsGotByte** [armory3d/armory#681]
In other engines it is possible to use different UV maps on certain parts of your shader. Would be great to have this in Armory as well.

Haven't seen more than one set of vertex colors used in other engines, so this might be a technical limitation, but would also be very useful in some cases to have that power.

**Comment by 8BitsGotByte** [comment]
thx, totally missed that example when I was looking through the repository. will take a look :)

**Comment by 8BitsGotByte** [comment]
Looks like there is some wired behavior going on when combining multiple UV maps with displacement. That's why I thought multiple UV maps were not supported yet. Try switching the UV maps in the node editor. On the first UV map the displacement works fine but on the second it is ignored.

[displacement.zip](https://github.com/armory3d/armory/files/2095926/displacement.zip)

**Comment by luboslenco** [comment]
Aha, great catch. I think it should work now. https://github.com/armory3d/armory/commit/e7768afe387d943348ce4187fc0f0e12cb1e89fa
