### ISSUE TITLE
Armory_04b_mac_b27 is not opening on macOS 10.12.6

### ISSUE THREAD

**Issue by SvenStober** [armory3d/armory#683]
Software error.

**Comment by 1l0** [comment]
Try to use Terminal to launch the app by like following command.
```
{YOUR_ARMORY_DIR}/blender.app/Contents/MacOS/blender
```

**Comment by luboslenco** [comment]
Launching from terminal should work, sorry for trouble. Alternatively there is a way to [setup armory manually](http://armory3d.org/manual/#/getting_started/setup?id=using-armory-as-add-on).
