### ISSUE TITLE
Remove Object Particles

### ISSUE THREAD

**Issue by Kame7C0** [armory3d/armory#685]
Armory_04b linux64 b27

Using "Remove Object" node on object with particles hangs Armory.

Examples:
- simple
[particle object remove bug.zip](https://github.com/armory3d/armory/files/2097475/particle.object.remove.bug.zip)
- wierd behaviour
[spawn and remove object with particles.zip](https://github.com/armory3d/armory/files/2097496/spawn.and.remove.object.with.particles.zip)

**Comment by luboslenco** [comment]
Thanks for report! Pushed a fix at https://github.com/armory3d/iron/commit/a532d8910e98e6f173da942bae90a7e31aa45bd4, both examples should run properly now.

([updater](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater) can fetch the latest armory)
