### ISSUE TITLE
getPixels or at not available ?

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#686]
into a logic node, something like   

**camera.data.renderTarget.getPixels();** // returns an error camera.data.renderTarget is null

or   **camera.data.renderTarget.at(10,10);** // idem error 

for the Html5 target ... bug or not ?

for info the trace of camera.data
 
				// 	renderTarget : null, 
				// raw : {
				// 	name : Camera, 
				// 	fov : 0.5033799409866333, 
				// 	near_plane : 0.10000000149011612, 
				// 	far_plane : 100.00006103515625, 
				// 	frustum_culling : true, 
				// 	clear_color : 0.05087608844041824,0.05087608844041824,0.05087608844041824,1
				// }, 
				// name : Camera

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Try https://github.com/armory3d/armory_examples/tree/master/screen_image to retrieve rendered image. `camera.renderTarget` is valid when the final target is texture, not screen.

**Comment by Didiercode** [comment]
Thank Lubos, I tried with that in first but didn't suceed to make a getPixel or at on the image or g too ... is there something I missed ?

**Comment by luboslenco** [comment]
Aha, might have been a webgl backend issue, fix in progress:
https://github.com/Kode/Kha/pull/828

Krom should however work (this is also how armorpaint exports the textures). Will try to update the example.

**Comment by Didiercode** [comment]
I just retried with Krom, and effectively their is no error with it (getPixel or at ). I will continue in Krom, waiting for Browser. Thank Lubos again for the nice work !

**Comment by luboslenco** [comment]
https://github.com/Kode/Kha/pull/828 now merged, will be also included in next armory build.
