### ISSUE TITLE
Converter "math" node issue

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#687]
![converter math node issue](https://user-images.githubusercontent.com/7542691/41417947-0205f640-6fef-11e8-991b-cfc2b5c74db6.jpg)
![converter math node issue 2](https://user-images.githubusercontent.com/7542691/41417957-07579946-6fef-11e8-9042-4109a99fc526.jpg)

Math node doesn't show anything :( whereas in manual it is said to be supported unless it's another math node ?! 

I have a predator cloak shader that is working realtime in eevee, using converter math node and refraction node. Refraction could be replace by transparent even if the effect is worth. It would be great to have refraction shader work in armory without VXGI enabled ...

Cheers.

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Please *(drag & drop zipped .blend file here)* if possible.

**Comment by mistajuliax** [comment]
This shader needs refraction, or unless glass ior, emission to work properly and math node ... 
I noticed when i prepared the scene that preview material doesn't work as expected too. You can try this shader in an eevee build to see the effect ...

[Stealth_predator_like_shader_test.zip](https://github.com/armory3d/armory/files/2105529/Stealth_predator_like_shader_test.zip)
[Stealth_predator_like_shader_test_eevee.zip](https://github.com/armory3d/armory/files/2105559/Stealth_predator_like_shader_test_eevee.zip)

**Comment by luboslenco** [comment]
Great, thanks. Linking to the existing https://github.com/armory3d/armory/issues/624 issue to keep it together.

**Comment by mistajuliax** [comment]
I forget something important, the material is animated, so you have to press play to see it in action !
