### ISSUE TITLE
Kode studio doesn't recognize import haxebullet.* in blender 2.8 build

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#692]
Only got this error in blender 2.8 build, it is OK in blender 2.79 build.
And the project can be compile and run/debug fine. It is only affecting the editor syntax checking.
![capture](https://user-images.githubusercontent.com/17811339/41462102-5098c01e-70c4-11e8-8ffc-7c430c05458c.JPG)
![capture2](https://user-images.githubusercontent.com/17811339/41462193-9d6e656a-70c4-11e8-8690-36cf3cd60334.JPG)

**Comment by MiloHX** [comment]
@luboslenco 
About the referenced issue #267, change the ZUI option in Armory Project from "Auto" to "Enabled" would solve that problem.
![capture](https://user-images.githubusercontent.com/17811339/41466571-6c486600-70d5-11e8-9ae7-1fb395e83507.JPG)
So I don't know if this is the same issue, since there is no option to enable/disable haxebullet...

**Comment by MiloHX** [comment]
@luboslenco 
Hey I found something. Seems in 2.8 build, Kode Studio doesn't like the double slash here:
![capture](https://user-images.githubusercontent.com/17811339/41493974-cc9cddbe-713f-11e8-87b0-4875e4d7a85b.JPG)

A temporary solution for this is to configure a Khafile with the same line but with single slash at that place. Hopefully this temp fix can be removed soon:
![capture2](https://user-images.githubusercontent.com/17811339/41494016-598a970c-7140-11e8-9046-eb2f4655cf51.JPG)

**Comment by luboslenco** [comment]
Double slash should be gone now. (https://github.com/armory3d/armory/commit/8c5c8bd1b03920a7e6b933b86f707b40297978aa)
