### ISSUE TITLE
Visual nodes quick search and groups

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#694]
Hi,

There is some improvments that could make visual scripting a must.
I take Unreal 4 example because it's a good example.

1 ) Nodes quick context search 
Instead of selecting nodes in the lower menu,
press space to show a quick search dialog with nodes list or type few letters and the search function will propose the nodes beginning with those letters it found.

https://i.stack.imgur.com/2s8o8.png

2) create nodes groups with title and color option

https://www.computerscienceforkids.com/wp-content/uploads/2017/02/Unreal-Engine-RPG-Blueprints-Tutorial-by-Kidware-Software-15-1030x564.png

**Comment by adriansnetlis** [comment]
The 2nd one is possible. Use Ctrl + J. You can set title for it too, not sure about color.

**Comment by DevMagicLord** [comment]
Cool.
