### ISSUE TITLE
android compile error Uniform lightDir not found.

### ISSUE THREAD

**Issue by jeyfrinjulian** [armory3d/armory#696]
Hello, I intent compiled for my device android version 7  and my apk only screen gray, no show my scene and only debug:

06-15 22:55:39.621 4192-4192/? I/art: Late-enabling -Xcheck:jni
    Reinit property: dalvik.vm.checkjni= false
06-15 22:55:39.641 4192-4199/? I/art: Debugger is no longer active
    Starting a blocking GC Instrumentation
06-15 22:55:39.869 4192-4192/? I/InstantRun: starting instant run server: is main process
06-15 22:55:39.902 4192-4192/? I/HwCust: Constructor found for class android.app.HwCustActivityImpl
06-15 22:55:39.921 4192-4192/? I/HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
06-15 22:55:39.937 4192-4192/? I/HwSecImmHelper: mSecurityInputMethodService is null
06-15 22:55:40.325 4192-4192/? I/HwPointEventFilter: do not support AFT because of no config
06-15 22:55:40.391 4192-4217/? I/kore: Initializing Haxe libraries
06-15 22:55:40.399 4192-4217/? I/kore: Starting Kore
06-15 22:55:40.400 4192-4217/? W/libOpenSLES: class OutputMix interface 0 requested but unavailable MPH=43
06-15 22:55:40.402 4192-4217/? I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
06-15 22:55:40.403 4192-4217/? W/AudioTrack: AUDIO_OUTPUT_FLAG_FAST denied by client; transfer 1, track 44100 Hz, output 48000 Hz
06-15 22:55:40.417 4192-4217/? W/kore: Uniform projectionMatrix not found.
06-15 22:55:40.419 4192-4217/? W/kore: Uniform projectionMatrix not found.
06-15 22:55:40.421 4192-4217/? W/kore: Uniform projectionMatrix not found.
06-15 22:55:40.442 4192-4217/? W/kore: Uniform N not found.
    Uniform WVP not found.
    Uniform W not found.
    Uniform lightColor not found.
    Uniform lightDir not found.
    Uniform lightPos not found.
    Uniform envmapStrength not found.
    Uniform LWVP not found.
    Uniform shadowsBias not found.
    Uniform shirr not found.
06-15 22:55:40.443 4192-4217/? W/kore: Uniform LWVP not found.
06-15 22:55:40.907 4192-4217/org.armory3d.arm W/kore: Uniform N not found.
    Uniform WVP not found.
    Uniform W not found.
    Uniform lightColor not found.
    Uniform lightDir not found.
    Uniform lightPos not found.
    Uniform envmapStrength not found.
    Uniform LWVP not found.
    Uniform shadowsBias not found.
    Uniform shirr not found.
06-15 22:55:40.908 4192-4217/org.armory3d.arm W/kore: Uniform LWVP not found.
06-15 22:55:40.909 4192-4217/org.armory3d.arm I/kore: Starting application
06-15 22:55:51.826 4192-4192/org.armory3d.arm I/hwaps: JNI_OnLoad
06-15 22:55:51.827 4192-4192/org.armory3d.arm I/Hwaps: APS: version is 3.3.14
06-15 22:55:51.829 4192-4192/org.armory3d.arm W/ApsUserFeedback: APS: User feedback is not supported

**Comment by luboslenco** [comment]
Hello! The `Uniform not found` error should be now fixed in [git armory](http://armory3d.org/manual/#/dev/gitversion?id=armory-updater), sorry for trouble.
