### ISSUE TITLE
Better Math node

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#697]
Hi,

Getting another Math node with event input,output and variable to store the result would make less connections and would make the graph more clear and Math would be faster to use.
(i don't like a lot the actual way to do math on event).

https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/mathnode.jpg?raw=true

![Node](https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/mathnode.jpg?raw=true)

**Comment by luboslenco** [comment]
Implement this as a node for the [logic_pack](https://github.com/armory3d/logic_pack) first. For core nodes we need to be careful to not end up with 1000s of them, as it is tempting to add node for every situation but also dangerous in the end.
