### ISSUE TITLE
Quick object placement brush tool

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#698]
Hi, 

99% People making 3D games will use a brush paint tool similar to that one : 
 
https://www.youtube.com/watch?v=B1aR7x7zhJM

Could Armory get brush tool to quickly place objects on a level, with options like random rotation, random offsets min max, or random scale min and max values.

**Comment by luboslenco** [comment]
There are existing Blender tools like the [Asset Sketcher](https://blendermarket.com/products/asset-sketcher-v10) (paid). If there are solid free alternatives we can link to them in the docs, suggestions welcome!

**Comment by AFWSI** [comment]
Why not use weight paint, vertex groups, and particle systems?

**Comment by Gerkinfeltser** [comment]
Baked particle system would work as well for grass/foliage

**Comment by DevMagicLord** [comment]
No.
Because the request is a tool to place grass on some particular places and surfaces, not to put grass everywhere using a particle system.

**Comment by Simonrazer** [comment]
You can also paint particles. When you have your Hair emitter selected put the Hair number to zero and switch to the "Particle Edit" mode and use the add tool.

**Comment by Gerkinfeltser** [comment]
Yep, as Simonrazer says. Textures & vertex groups can also be used with particle systems to define areas where particles are desired.

**Comment by luboslenco** [comment]
Particles are rendered using instancing as well.
