### ISSUE TITLE
Object hardware instancing

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#699]
Hi,

Armory could get hardware instancing, to be able to draw hundred object detail without performance impact, for example grass, rocks or detail objects.

There is existing systems with optimisations like camera fov culling, max distance display and fade in out distances like this one 
https://www.youtube.com/watch?v=Q3-_xad_ofs

**Comment by luboslenco** [comment]
Related examples:
https://github.com/armory3d/armory_examples/tree/master/instancing
https://github.com/armory3d/armory_examples/tree/master/animation_instanced
https://github.com/armory3d/armory_examples/blob/master/particles/hair.blend
