### ISSUE TITLE
Crepuscular Rays

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#7]
One graphical feature that would be nice to add is crepuscular rays, also known as "god rays", referring to shafts of light seen from clouds or when sunlight is occluded.

**Comment by adriansnetlis** [comment]
Cool! I am about this. Just note - many engines which has crepuscular rays don't offer one option - setting turbidity of air. However, you could make them that the user could set the turbidity of rays(the higher turbidity(e.g. more polluted air, more dust, more water particles), the stronger the rays. Also would be cool to have option for air color(e.g. if the air is full of water, the god rays will be pale, almost white, but if the air is full of dust, rays will most likely be yellowish).

Good luck!:)

**Comment by zauberparacelsus** [comment]
I think I'd like to change this request to one for a general volumetric rendering feature, since "god rays" are just one of the effects that volumetric rendering can accomplish.

**Comment by JeannotLandry** [comment]
I think having both volumetrics and god rays would be a good ideas since not everyone will develop games that are targeted at high end machines. So having also the ability to somewhat fake it should be a must.

**Comment by luboslenco** [comment]
Merging this issue with https://github.com/armory3d/armory/issues/115.
