### ISSUE TITLE
Progress bar broken

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#70]
Progress bar loads to 50% immediately and then stops until render starts. Bug is in windows at least (figures windows would be the one with the broken progress bar) on all versions up until now. Essentially it makes the progress bar useless. Also, progress bar continues to display 50% while Armory runs (tested in electron mode).

**Comment by marcclintdion** [comment]
Do you mean the standard Blender progress bar or something specific to Armory?  If you mean the Blender progress bar, that's been failing even for people not using armory.  

There is a bug in the main Blender source.  I'm not sure when it started though. I just started using Windows again recently and noticed the problem.

**Comment by ubaldy** [comment]
Isn't that the compiling progress bar? Progress bars that only reference 2 stages would do this, I don't think it is a bug. Unless Armory interacts with the progress bar while it is compiling? I guess that would be a nice feature :) Would consider it low priority though.

**Comment by luboslenco** [comment]
Instead of progress bar at 50%, 'Compiling..' label is shown now.
