### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#701]
In the third person template, running near floor cube side corners there is some bug display with a plane showing and hiding.

Download the game Blender file here 
[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/third_person_display_bug.zip](url)

![bug](https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/planeMesh.gif?raw=true)

**Comment by luboslenco** [comment]
Back-faces are culled. Can be configured in `Properties - Material - Armory Props` or disabled in `Armory Render Path - Renderer - Culling`.
