### ISSUE TITLE
Emission Shader Doesn't Cope Well With Shadows

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#702]
Whenever an object with emission shader receives a shadow, that shadow seems to cause the object to have negative values or either extremely high values (beyond what numbers GLSL can process normally). That can be told by the artifacts seen in SSR.
Here's a video explaining the bug: https://www.youtube.com/watch?v=FUOkwbCfz6I&feature=youtu.be

Honestly, emission shader should have no reaction to shadows whatsoever in my opinion. Since the shader simulates object that absorbs 100% of incoming light and emits light by itself.

**Comment by DevMagicLord** [comment]
I agree, emissive material does not receive shadows (tested on Unreal 4).

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/521.
