### ISSUE TITLE
Shadow display bug

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#704]
There seem to be a shadow bug when the player rotate around.
Is there some setting to avoid it ?

![shadow bug](https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/shadowBug.gif?raw=true)

**Comment by luboslenco** [comment]
https://github.com/armory3d/armory/issues/640

**Comment by DevMagicLord** [comment]
Does this shadow bug has a higher priority than other bugs ?
