### ISSUE TITLE
Linux KodeStudio libgconf-2.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by juanantoniogit** [armory3d/armory#705]
when push the kode studio button in Properties / Render / Armory proyect. nothing happens
![captura de pantalla_2018-06-17_22-45-26](https://user-images.githubusercontent.com/25645174/41511899-391fc38e-7280-11e8-91a4-7ccabc97624b.png)

I need install kode studio?
How do I do it?

**Comment by luboslenco** [comment]
Should now work out of the box in 0.5a.
