### ISSUE TITLE
Build fails in Android Studio: CMAKE_C_COMPILER not set

### ISSUE THREAD

**Issue by armoryous** [armory3d/armory#708]
I would like to start testing simple scenes created in Armory3D on Android. The problem is I can not open project in Android Studio without errors. Android Studio is 'bigger' than Armory3D so I guess the problem is with Armory3D or with some thing I am doing bad in Armory3D.

I have no idea what to do and where to find help. Yes, I know Google. I didn't found answer.

If you know why this is happening please tell me.
This is what Android Studio tells to me:

```
Build command failed.


Error while executing process C:\Users\Robert\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\Robert\Desktop\build_untitled\android-native-build\untitled\app -BC:\Users\Robert\Desktop\build_untitled\android-native-build\untitled\app\.externalNativeBuild\cmake\release\armeabi -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi -DANDROID_NDK=C:\Users\Robert\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Robert\Desktop\build_untitled\android-native-build\untitled\app\build\intermediates\cmake\release\obj\armeabi -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=C:\Users\Robert\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\Robert\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_PLATFORM=android-15 -DCMAKE_CXX_FLAGS=-frtti -fexceptions  -DANDROID_ARM_MODE=arm}


 (include)   CMakeLists.txt 
Open File ///Under this error


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage


-- Configuring incomplete, errors occurred!


Build command failed.


Error while executing process C:\Users\Robert\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\Robert\Desktop\build_untitled\android-native-build\untitled\app -BC:\Users\Robert\Desktop\build_untitled\android-native-build\untitled\app\.externalNativeBuild\cmake\debug\armeabi -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi -DANDROID_NDK=C:\Users\Robert\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Robert\Desktop\build_untitled\android-native-build\untitled\app\build\intermediates\cmake\debug\obj\armeabi -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=C:\Users\Robert\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -DCMAKE_TOOLCHAIN_FILE=C:\Users\Robert\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DANDROID_PLATFORM=android-15 -DCMAKE_CXX_FLAGS=-frtti -fexceptions  -DANDROID_ARM_MODE=arm}


 (include)   CMakeLists.txt 
Open File ///Under this error


CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage


-- Configuring incomplete, errors occurred!
```

[Open FIle.txt](https://github.com/armory3d/armory/files/2112253/Open.FIle.txt)

**Comment by luboslenco** [comment]
Hello, is this with Android NDK installed? ([manual](http://armory3d.org/manual/#/platforms/android?id=native-c))

**Comment by armoryous** [comment]
Yes. I have installed it

**Comment by Ogimle** [comment]
same problem
ubuntu 18.04x64
download latest studio
studio download sdk then ndk 17 
i generate android project from example game_endlessrun
open in studio
project download dependencies build tools 25.0.2 then cmake

when "Build -> Refresh Linked c++ project" then got error same in topic
when "Build -> Make Project" then error

> Cause: executing external native build for cmake /home/elmigo/dev/armory_examples/game_endlessrun/build_endless/android-native-build/endless/app/CMakeLists.txt

and loh at attached file
[makelog.txt](https://github.com/armory3d/armory/files/2172951/makelog.txt)

**Comment by Ogimle** [comment]
same problem
ubuntu 18.04x64
download latest studio
studio download sdk then ndk 17 
i generate android project from example game_endlessrun
open in studio
project download dependencies build tools 25.0.2 then cmake

when "Build -> Refresh Linked c++ project" then got error same in topic
when "Build -> Make Project" then error

> Cause: executing external native build for cmake /home/elmigo/dev/armory_examples/game_endlessrun/build_endless/android-native-build/endless/app/CMakeLists.txt

and loh at attached file
[makelog.txt](https://github.com/armory3d/armory/files/2172951/makelog.txt)
