### ISSUE TITLE
krom scenes fail white screen mac 03_27, when debug flickers badly.

### ISSUE THREAD

**Issue by Justinfront** [armory3d/armory#709]
All complex scenes seem to fail on mac using 03, for instance when trying your repos:
Armory_Examples
Armory_Templates

Both not rendering on 03 build unless I turn on debugging and then on the tank ( where discovered debug made a difference ), the screen is flickering from light to dark. With screen grab it seems to look ok:
<img width="1275" alt="tanks0" src="https://user-images.githubusercontent.com/489459/41602993-ee93e44e-73d3-11e8-8ed7-07d7db9377ef.png">
WITH DEBUG OFF get white screen only for Krom.

Seem to run ok in firefox but the line edges when not moving objects, do horizontally change brightness slightly but not significantly but mention incase related.

Lots of the Iron_Examples worked.

Tried updating sdk and it failed.
<img width="1618" alt="blendersdkupdate" src="https://user-images.githubusercontent.com/489459/41603263-8777d1ca-73d4-11e8-9322-486e0ff33a91.png">

I tried all the mac download version and Kode could not be opened from Blender on any of them, textmate opened on 03 which I guess is expected.  On 04_28 I could run Kode by going into the blender package and opening it direct, but to run the app I had to change my global Kha.  On 04_27 I could not create nodes.  In all cases I had put the armory folder in my Applications folder is that a bad idea?

**Comment by Justinfront** [comment]
running Sierra
MacBook Pro (Retina, 15-inch, Mid 2014)
2.8 GHz Intel Core i7
NVIDIA GeForce GT 750M 2048 MB
Intel Iris Pro 1536 MB

let me know if you need some more testing or more details.

**Comment by luboslenco** [comment]
Hello, please report issues from the latest armory builds only (currently 0.4). To update, try doing a [manual clone](http://armory3d.org/manual/#/dev/gitversion?id=manual-clone) instead, as the security features of macOS may prevent the armory updater from working.
