### ISSUE TITLE
black pixels on edges Ubuntu 18.04

### ISSUE THREAD

**Issue by arttuautio** [armory3d/armory#710]
When I open Blender and launch Armory window with basic settings, I see some glitchy black pixels on edges. Them vanish quite fast if I look around. Glitches might appear occassionally.
![armorybug](https://user-images.githubusercontent.com/36882665/41617666-c7d5c60c-7409-11e8-9ee8-5bbf46b87cc8.png)
I have Acer Aspire E5-551 with Ubuntu 18.04
AMD® A8-7100 radeon r5, 8 compute cores 4c+4g × 4
I am pretty newbie in reporting bugs so what extra info you need?

**Comment by zicklag** [comment]
I have the same issue on Ubuntu 16.04.

@arttuautio I'm not a developer, but so far it looks like the output from `glxinfo | grep OpenGL` is the most useful general system information for graphics stuff. :slightly_smiling_face: 

**glxinfo | grep OpenGL:**
```
OpenGL vendor string: X.Org
OpenGL renderer string: AMD MULLINS (DRM 2.50.0 / 4.13.0-32-lowlatency, LLVM 5.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.2.8
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
OpenGL ES profile extensions:
```

**Comment by luboslenco** [comment]
Hopefully ok now since moving to core profile on Linux.
