### ISSUE TITLE
if a scene has transparent object, debug in Kode Studio will fail (both 2.79 and 2.8)

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#711]
Cannot debug in Kode Studio if a scene has any transparent object.

![capture](https://user-images.githubusercontent.com/17811339/41653179-d0a950ba-74b7-11e8-9cdb-b814bf4dfb0f.JPG)

Attachment is for 2.79. 
[Translucent.zip](https://github.com/armory3d/armory/files/2118877/Translucent.zip)

**Comment by luboslenco** [comment]
Fixed, was caused by webgl1 compatibility issue.
