### ISSUE TITLE
UV Maps switch unpredictable depending on where render setting is set to active

### ISSUE THREAD

**Issue by 8BitsGotByte** [armory3d/armory#712]
I included the blend file below because the bug is quite hard to describe. Try setting the render on the different uv maps to active and see what happens. Depending on which on is set to active the result in armory change even though every uv map is specified in the material to be used on a different texture. And none of the results match what it should actually look like.
![screenshot 2018-06-20 12 41 58](https://user-images.githubusercontent.com/40199415/41653794-74745f90-7487-11e8-9971-1504576f6144.png)
[testScene01.zip](https://github.com/armory3d/armory/files/2118902/testScene01.zip)

**Comment by luboslenco** [comment]
Specifying uv map should be ok now, however only 2 uv maps per mesh are supported currently. Armory will print a warning `Plane exceeds maximum of 2 UV Maps supported`.
