### ISSUE TITLE
Fedora Linux - missing shared library with Blender 2.8

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#713]
Hello this is the terminal log when i try to run Armory_04_linux64_b28
```
[linux@localhost Armory]$ ./blender
./blender: error while loading shared libraries: libbsd.so.0: cannot open shared object file: No such file or directory
```
Watching the folders,  Blender in Armory_04_linux64_b28 is saw as a library:

![screenshot from 2018-06-20 16-47-04](https://user-images.githubusercontent.com/12413409/41666279-6c62740e-74aa-11e8-8a50-7a6f5d5ba451.png)

While with Armory_04_linux64_b27, Blender is saw as an executable and it works:

![screenshot from 2018-06-20 16-47-21](https://user-images.githubusercontent.com/12413409/41666315-89bd98ee-74aa-11e8-888c-5aa593577ca9.png)

My system : Linux Fedora 28, AMDGPU RX 580

**Comment by luboslenco** [comment]
Fixed in Armory 0.5.
