### ISSUE TITLE
Symantec Endpoint Protection Notification

### ISSUE THREAD

**Issue by Vgrischenko** [armory3d/armory#714]
Hello, tonight my Symantec antivirus show notification about risk from kraffiti.exe in Armory3d blender build.

![armory3d_risk](https://user-images.githubusercontent.com/40451081/41700442-fab66b94-7530-11e8-843f-726a321de700.png)
![armory3d_risk2](https://user-images.githubusercontent.com/40451081/41700510-3941d380-7531-11e8-8085-22f631d94767.png)

**Comment by rovacado** [comment]
http://forums.armory3d.org/t/false-virus-flag/1101

Verified false possitive. Not sure there's much that @luboslenco can do

**Comment by rovacado** [comment]
@Vgrischenko Its likely your browser. it looks like you may be using Internet Explorer 10 from the styling on the top bar, that browser has been discontinued by Microsoft for a few years now, and discourse forum (the forum software used) may not support it any longer. Id recommend upgrading to internet explorer 11 or edge if you want to stick with Microsoft web browsers or check out firefox or chrome if you don't mind the slight hassle of changing to a different company

**Comment by luboslenco** [comment]
(kraffiti repository for inspection [here](https://github.com/Kode/kraffiti). It is a simple image converter program.)

**Comment by Vgrischenko** [comment]
@luboslenco thanks! Want to believe that safe to be used and make undo in Symantec. 
Let Kraffiti free :))

@rovacado same things with other web browsers and on three friends computer too. Main page http://armory3d.org/ and community works good. But clicks on Forums (Discuss!) go to white page, that all. Sorry for off-topic.

**Comment by luboslenco** [comment]
Sorry, not sure about the forum access. Not aware of any blocks here.:(
