### ISSUE TITLE
Compiled.glsl not found

### ISSUE THREAD

**Issue by RienoIvan** [armory3d/armory#715]
Hi. I get this error message whenever I try to launch the player in the Blender 2.79 version.
![armorybug](https://user-images.githubusercontent.com/40461831/41717022-f4252874-758a-11e8-86e5-b0f498b6d342.png)

Specs: AMD A6-9220 with AMD Radeon 530 | Windows 10 (x64)

**Comment by luboslenco** [comment]
Hello, try to save your .blend file into a directory like `C:\Users\user_name\Documents\test` first to see if that works. Check if something on your system is not preventing Armory from writing files.

**Comment by TheTyrant** [comment]
I've gotten that issue as well. Did this being with not finding certain png files? I came to this after having to locate or create several Png's including Noise8.png and others.

**Comment by RienoIvan** [comment]
It works fine now. Thanks!
