### ISSUE TITLE
DetourCrowd support

### ISSUE THREAD

**Issue by slapin** [armory3d/armory#719]
As Armory have Recast support, it should be logical for it to support DetourCrowd as it uses Detour for navigation, which allows for large crowds control on scene lightly.

**Comment by DevMagicLord** [comment]
I never seen a great example of Crowd usage on others 3D engines.
Do you have some game example in particular ?

**Comment by slapin** [comment]
Urho3D supports DetourCrowd and it works great. As for game - I did some
experiments myself and was really amazed by how cool it is.
The main feature for me is I can control agents individually or as
groups.Recast supports area tags and Crowd can use them to avoid or prefer
the area.
For example one can use Crowd for vehicles and pedestrians allowing
separation of sidewalk and traffic area and letting crosswalks work with
street light simulation.
Also one can use either non-physic control over agents or physics based
control as it is aware of current agent location not enforcing it, so one
can fixup the routes
using raycast or alternate navigation means.

you can see videos like https://www.youtube.com/watch?v=9RnI77QeuKA
https://www.youtube.com/watch?v=R0vFwI2P09M or other my videos to see what
it can do.

**Comment by luboslenco** [comment]
Linking to https://github.com/armory3d/armory/issues/243.
