### ISSUE TITLE
Generate mesh at runtime

### ISSUE THREAD

**Issue by xziayro** [armory3d/armory#72]
I have a small question/suggestion. 

I'm working on a CAD visualizer (for now it is on THREE.js, but I would like to transfert it on armory when Armory will be robust enough). I haven't yet put my hands on the code for Armory but I was wondering if it will be possible to load/generate mesh at runtime? If so, then move/instanciate the mesh and finally apply a shader on it.  

Moreover, I looked the builded files (.arm) but I did not find the correct encoding of the file to read them. Are they binary files or just plain text?

**Comment by luboslenco** [comment]
That sounds pretty cool!

Added a new page to manual - [Generate mesh](http://armory3d.org/manual/scripting/generate_mesh.html). It is rather simple and talks about mesh data only, can expand on it further eventually. I changed a few things in Armory to make it a little cleaner, before the new build is out [git version](http://armory3d.org/manual/enginedevelopment/gitversion.html) is needed to run that.

Full scene format is defined [here](https://github.com/armory3d/iron/blob/master/Sources/iron/data/SceneFormat.hx), however it is not yet documented and may still change, so probably not that useful.

Yes, .arm files are binary by default. But if you uncheck *Render tab - Armory Build - Advanced - Minimize Data* it will turn them into plain json next time you build and the structure will look like the scene format linked above.
