### ISSUE TITLE
Ocean example should support underwater

### ISSUE THREAD

**Issue by slapin** [armory3d/armory#720]
Ocean example should support underwater, that would be nice to make it more complete.
Can't guess how to make it myself :(

**Comment by DevMagicLord** [comment]
This could be an option we could choose to use or not.

**Comment by slapin** [comment]
Yes, but in example demo there should be able to demonstrate how to do
underwater.

The problem is like "I have an ocean now what?" style, as be able to dive
into such
nice water is first wish for us mere mortals left without Summer vacation...
That would allow my endless procedural world to be converted to Armory.
Even though character animation
is not mature in Armory, as asset pipeline is so great in Armory I can do
many things much faster in Armory than
in Urho3D and as Armory supports the same architectures as Android and I
can still write C/C++ code for things
which need to be fast, that would allow me to move my development to Armory
and finish my game being faster
and far more satisfied and less demotivated.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/965.
