### ISSUE TITLE
Add Armory to AUR

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#724]
Hey!
This request is not related to Armory directly, but rather to it's delivery.
As an Arch Linux based distribution user, I really love to use pacman with AUR as the place to get software as it provides one place for all my programs, enables very easy way to keep my software up to date and manages dependencies automagically. I would really love to see Armory 3D available on AUR.

How I see it possible:

- Package named `armory3d` is installable on AUR. It contains the Blender add-on.
- Another package named `armory3d-sdk` as a dependency for `armory3d`. This contains the Armory 3D SDK.
- `blender` is another dependency of Armory 3D.
- Once you install `armory3d`, you can enable it in Blender's add-on tab. It should automatically set the SDK path to be the path of the SDK files installed by `armory3d-sdk` package. However, user can change that in case he/she needs to use custom version of the SDK.

Do you think this could be done for Armory 3D?

**Comment by luboslenco** [comment]
There are 6 versions of Armory to manage as of now (2.79/2.8 for win/linux/macos), I fear that adding more would slow down the release process.:(

With that said, now that Armory is FOSS you could distribute it yourself as well if you wish. I would probably wait just a bit to get out of the 0.x releases, slowly getting there.
