### ISSUE TITLE
Reload armory addon without blender restart

### ISSUE THREAD

**Issue by slapin** [armory3d/armory#725]
When writing custom nodes restarting blender every time is not nice...
Isn't there some way? I know that plugin development for Blender is likely ends up the same
because of caching, but nodes are not technically plugins so maybe it is possible to reload them
on request?

**Comment by luboslenco** [comment]
(ref: https://gist.github.com/FuriouZz/ccb24f6510140b215e31be3fe5e092c1)

**Comment by FuriouZz** [comment]
Investigate https://github.com/wisaac407/blender-script-watcher

**Comment by luboslenco** [comment]
Looks like there would be further issues in b28 and ideally we keep it non-hacky, putting on hold for now..
