### ISSUE TITLE
Event system example request

### ISSUE THREAD

**Issue by slapin** [armory3d/armory#726]
I think the common use case would be to send events in node system for complex script to handle.
Also script could send events which are handles by node system.
In general node system is good for some direct operations and tweaking of some vars and controls.
Also (in future) driving animation tree. But complex logic (like utility AI or low level behaviors) is not a strong point of node system, this is where script or native code works best. So implementing complex stuff in script and simple but flexible stuff in node system (like high level logic, animations, etc.) looks natural. But that requires for some mechanism to interchange information between nodes and scripts. I think the best way is event system. If such interchange is already implemented I'd like to see example of implementation, if not then I'd like to consider it as feature request.

**Comment by luboslenco** [comment]
Added some basic examples at https://github.com/armory3d/armory_examples/tree/master/logic_events.
