### ISSUE TITLE
Bullet and physics are disabled by default and settings are ignored

### ISSUE THREAD

**Issue by slapin** [armory3d/armory#727]
I have to manually add arm_physics, arm_bullet and haxebullet library to khafile.js every time.
if I save project in blender all physics settings are removed.

**Comment by luboslenco** [comment]
`Armory Project - Modules - Physics` can be set from `Auto` to `Enabled` now, to enable physics at all times. https://github.com/armory3d/armory/commit/ba87005efb11c49ed28ed52f69543bd07d596c2a

**Comment by slapin** [comment]
Thanks a lot!
