### ISSUE TITLE
Forward renderer only shows 1 light

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#729]
Simple scene setup:
![image](https://user-images.githubusercontent.com/33040347/41821230-c0ea1640-77dd-11e8-8656-baf005295fc3.png)

With deferred renderer, 3 lights are visible
![image](https://user-images.githubusercontent.com/33040347/41821261-303a26f2-77de-11e8-9f52-81363fef58b5.png)

With forward renderer, only 1 light is shown
![image](https://user-images.githubusercontent.com/33040347/41821268-46044904-77de-11e8-8f88-8c125f294c21.png)

[forwardlights.zip](https://github.com/armory3d/armory/files/2130985/forwardlights.zip)

**Comment by donalffons** [comment]
Hi @luboslenco , I wanted to give this a little bit of a bump. Just checked out the new 0.5 builds and noticed that the issue still persists, there.
As always: You're doing a hell of a job. Love the direction, this is going in.

**Comment by zicklag** [comment]
I would really like to get this fixed, too. The Forward renderer is a lot faster than the Deferred renderer on small devices and I would really like to be able to target them as well.

**Comment by donalffons** [comment]
Awesome, thanks Lubos for fixing this. I did not try it yet, but I will soon :). Will leave this open, but feel free to close it whenever you want.

**Comment by luboslenco** [comment]
Should run out of the box in 0.6alpha. Lots of little fixes still needed but will take care of that for the final release. 🙂 

![2](https://user-images.githubusercontent.com/3685704/50395143-7e613500-0762-11e9-9504-62333459dd98.PNG)
