### ISSUE TITLE
Transparent background

### ISSUE THREAD

**Issue by xziayro** [armory3d/armory#73]
Is it possible to render a transparent background while using a world background for ligthing? I mean, as in Cycle to have a hdri (or sky texture) background for the glossy/diffuse/... rays and a transparent one for the camera ray.

**Comment by luboslenco** [comment]
Not yet implemented but on the radar, should be easy.

**Comment by luboslenco** [comment]
Now possible using `Render - Film - Transparent` option. (https://github.com/armory3d/armory/commit/d92387d6e6513cf3de4f740af9744c3746412ff3)
