### ISSUE TITLE
Point light artifacts with deferred rendering

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#730]
These weird artifacts show up with point lights close to a surface in deferred rendering mode. Also the camera distance / angle seems to play a role.

![image](https://user-images.githubusercontent.com/33040347/41821377-d14e16a6-77df-11e8-8143-b9a27432f535.png)

[forwardlights.zip](https://github.com/armory3d/armory/files/2130995/forwardlights.zip)

**Comment by adriansnetlis** [comment]
They come from shadows. Adjusting bias could help this. Try to avoid putting lights so close. In most cases you don't need to anyways. Keep them at least 0.1 m away. If you're still getting artifacts then, improving shadow resolution or bias can reduce them (but note that resolution affects performance, while bias offsets shadows). Also, adjusting clipping could help (you can end up increasing close-up bit-depth by adjusting clipping). I don't know if there is option for 16-bit shadows, but if there is, try enabling it.

**Comment by donalffons** [comment]
Thank you @adriansnetlis for bumping me into the right direction! I was trying to lower the bias value all the time, but instead I had to increase it.

![image](https://user-images.githubusercontent.com/33040347/41843491-efde357c-786d-11e8-8677-0af852c67ffc.png)

Thanks again!
