### ISSUE TITLE
node 'Input -> Keyboard' doesnt react to Esc and Ctrl buttons

### ISSUE THREAD

**Issue by Azim-D3Tm** [armory3d/armory#731]
node 'Input -> Keyboard' doesnt react to Esc and Ctrl buttons, and probably some more

Armory v0.4 ($Id: 97fc5021306ba3e6d744b62e6614e853412df34b $)
OS: win, Target: krom, GAPI: opengl, Blender: 2.79 (sub 0)

*(drag & drop zipped .blend file here)*
[ControlTest.zip](https://github.com/armory3d/armory/files/2132801/ControlTest.zip)

**Comment by Muzz** [comment]
The bug is simply that in Iron input, it has the enums names esc and ctrl, while the logic node has the full names. Changing the names to the full names in the input.hx makes it work.

**Comment by luboslenco** [comment]
Should work properly now using git version.
