### ISSUE TITLE
Screen refresh/update is random

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#732]
When being in a loop nodes/events, with no inputs interactions, the screen refresh is random ... how to fix that ?
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Sorry I do not know what this means, can you show an example?

**Comment by Didiercode** [comment]
For example with the tanks (on Html5): 
- if from a trait X, you call the TankTree trait through an event you sent to it (so not using keyboard !) ;
- then you send back from this TankTree another event that is intercepted by the calling another trait X; 
- you are not sure that the tank moved/rotate
- if you try for too to read position or rotations, they are false

maybe if it was possible to force the screen refresh or use an existing node that create same effect  ?

**Comment by Didiercode** [comment]
I just discovered the problem: if you do Print/Trace during the loop, there is a kind of bufferization that feeds and prevents the screen update.

**Comment by Didiercode** [comment]
[TankAuto.zip](https://github.com/armory3d/armory/files/2134413/TankAuto.zip)
this an example to test why the tank don't move correctly .. since we can see with the trace that actions/events are well created/sent.


-There is a Sequenceur trait added on tank1
-tank2 is inactivated.

**Comment by Didiercode** [comment]
It seems that the SendEvent or SendGlobalEvent are not accepting that we modify the Event name during execution.

**Comment by Didiercode** [comment]
[TankAutov1.zip](https://github.com/armory3d/armory/files/2136660/TankAutov1.zip)

Here a variant for tests and strange others behaviors appears :
- in this test, only an event "wait" is sent by trait Sequenceur and the receiving trait Tanktree uses a GetProperty/Gate to act the good action. With a sleep node we see tank moving.
- the number of time the event "fait" will be accepted is random ... !! (see at decrementation of the property epoch)

**Comment by luboslenco** [comment]
`Send Event` nodes should now work correctly in regard of event name changes.
