### ISSUE TITLE
Most Efficient Method of Doing a Split Screen

### ISSUE THREAD

**Issue by zicklag** [armory3d/armory#733]
Hi, I am wanting to setup a split screen mode for a game that I am making and I wanted to know what the best way to do that was from a performance perspective. I tested out the [camera texture example](https://github.com/armory3d/armory_examples/tree/master/camera_texture) that lets you take the render output of a camera and use it as a texture for a plane. That could be one way to do split screen, just to line up textured panels in front of the camera, but I wasn't sure if there was any performance disadvantages to that when I don't really need the textured panels to be in 3D space. Would it be better to try and take the render output of the cameras and put them in a 2D Zui element? Is there another way to do split screens?

**Comment by luboslenco** [comment]
Hello, I started toying with proper split screen feature at https://github.com/armory3d/armory_examples/tree/master/split_screen (needs latest git version). There may be issues with culling, not finished yet.

**Comment by zicklag** [comment]
Oh, sweet! I haven't done much with Armory yet, but I was going to start trying to make a split screen feature as soon as I could figure it out. Cool that you started on it.

BTW your source code is very clean and readable. Everything that seems like it should be simple ends up being simple and easy to understand in your source code. It's awesome. I can't wait to get more into it ( and try out your example :slightly_smiling_face: ).

**Comment by zicklag** [comment]
I tried out the example. I love how elegant the code for the armory Trait was in your example. Keep up the good work!

**Comment by luboslenco** [comment]
Yay, thanks for kind message, happy the example was helpful! 🙂
