### ISSUE TITLE
Debugging properties similar to BGE

### ISSUE THREAD

**Issue by AFWSI** [armory3d/armory#735]
Unless I'm missing something, seeing the status of "properties" is difficult in Armory. Would be nice to do something similar to the BGE.

Option to enable debug for each property in BGE
![blender_game_properties](https://user-images.githubusercontent.com/24877571/41924614-218762f2-7930-11e8-9ce7-9e703c1bbe66.jpg)

Shows the status of the enabled properties
![blender_game_debug](https://user-images.githubusercontent.com/24877571/41924646-2e6903e0-7930-11e8-890e-5e83c42e0c30.jpg)

Right now, I only see one thing being displayed at the top and it doesn't seem to update to a different property.
![debug_info](https://user-images.githubusercontent.com/24877571/41924724-5d991dee-7930-11e8-85cb-3c424749f3f7.jpg)

Multiple properties created in Armory
![armory_debug_properties](https://user-images.githubusercontent.com/24877571/41924753-74ef8406-7930-11e8-8797-4b752dd9f3f1.jpg)

My idea was maybe have a debug node where you just use the "Get Property" node and plug into a "Debug Node". The debug node would be like maybe a Print node and a On Update node combined?

Then you could do something like this in the "Debug Info" or just make a new tab for displaying properties.
![debug_info_improved](https://user-images.githubusercontent.com/24877571/41924795-8cbb7716-7930-11e8-9b0f-1fdc11f49852.jpg)

**Comment by luboslenco** [comment]
Added [one way](https://github.com/armory3d/armory_examples/blob/master/logic_basics/watch_variable.blend) now by enabling `Watch` property in `Logic Nodes Editor - Properties - Armory Logic Node`. Afterwards the variable will be monitored in the debug console.

![capture](https://user-images.githubusercontent.com/3685704/42077142-2d93c992-7b78-11e8-983c-2415035c17ce.PNG)

**Comment by AFWSI** [comment]
AWESOME, I’ll be sure to check this out later today.
