### ISSUE TITLE
Roughness + Metalic broken

### ISSUE THREAD

**Issue by xziayro** [armory3d/armory#74]
I've been testing a lot Armory this two days. Awsome! 

It seems there is something broken when using metallic  = 1 and roughness. For roughness <0.5, Armory seems to apply a roughness = 0, and when roughness >= 0.5, the results looks like if roughness = 1, see attached images).

Ps: I didn't managed to find information on what is the roughness strength. 

![screenshot from 2016-11-29 12 27 26](https://cloud.githubusercontent.com/assets/16816796/20708721/990d0624-b631-11e6-97bf-4df49e143321.png)

![screenshot from 2016-11-29 12 27 44](https://cloud.githubusercontent.com/assets/16816796/20708725/9b1ab650-b631-11e6-894e-373c275996e7.png)

**Comment by luboslenco** [comment]
Hm something is off with the roughness, either shaders are picking wrong mip-level or maps are generated wrong. Will investigate.

**Comment by xziayro** [comment]
Just fyi, i tested with power of 2 hdri and non power of 2 hdri and it
still does the same.

**Comment by luboslenco** [comment]
Metallic parameter now fixed.
