### ISSUE TITLE
Get crash when open some of the projects in armory_examples

### ISSUE THREAD

**Issue by wicast** [armory3d/armory#740]
Using armory 0.4, Windows10.

particles/bunny: As you play or export, It gets crash, and no useful log in console.

oceans: I can't open it.
![ocean](https://user-images.githubusercontent.com/2603937/41968063-e2f1afd2-7a35-11e8-8e41-9d58c953a64e.JPG)

linked-proxy: After you export or play it. You can't reopen it.
![link](https://user-images.githubusercontent.com/2603937/41968153-1d9dad0c-7a36-11e8-923d-9a05573b433d.JPG)

**Comment by luboslenco** [comment]
Hello, please use Blender 2.79 for general armory usage, need to wait a bit more for b2.8 to get ironed out. Once there I will make sure to retest all of the examples.:)
