### ISSUE TITLE
Looks like it is not possible to spawn scene with physics

### ISSUE THREAD

**Issue by slapin** [armory3d/armory#743]
Looks like it is not possible to spawn scene with physics, as it leads to hang.
If spawned scene is with RigidBody the scene is stuck somewhat...
If I remove RigidBody from object it imports fine.

Any ideas?

Also I can't make spawned scenes with cameras work, but that is probably some other
unrelated thing...

**Comment by luboslenco** [comment]
Should be fixed now at https://github.com/armory3d/armory/commit/5ddb0e32d19c0a9da258b19a62390cd77a4195f5.

**Comment by slapin** [comment]
Thanks tested it, works great with git version.
