### ISSUE TITLE
Kode Studio - fix Krom debug

### ISSUE THREAD

**Issue by Muzz** [armory3d/armory#745]
[recreation.zip](https://github.com/armory3d/armory/files/2144082/recreation.zip)

Hi! I've been playing with Armory today and really liking it. Running from blender works fine, but having issues when building from krom ide.

This is just using the blender packaged with 04.

For minimal recreation steps:

Open scene. 
Set renderpath to high 
add a script trait to box.
press f5 and run, it works
now open script, and run from krom ide

With Krom debug on:
![](https://cdn.discordapp.com/attachments/454251181032734720/461783310063108098/unknown.png)

With Html5 Debug on:
![](https://cdn.discordapp.com/attachments/454251181032734720/461782722977857536/unknown.png)

Hope that's enough information.

**Comment by Muzz** [comment]
I got some help from milo in the discord.

This seems to be a fix:

Try this: (1) Close Kode Studio
(2) In Armory Player Tab, Clean the project
(3) Choose Runtime to Browser, then Play the project once in Armory
(4) Open Kode Studio, choose HTML5 to debug again

Not sure what that implies, but should help!

**Comment by luboslenco** [comment]
Krom should now launch properly from within KodeStudio in 0.5a.
