### ISSUE TITLE
Shader compiler error when set translucent

### ISSUE THREAD

**Issue by Hazukiaoi** [armory3d/armory#746]
When I set Armory PBR Opacity less then 1, will Shader compiler error

And the log here
Armory v0.5 ($Id: 7a1b4d39eb6568a933a1f63d17aa1a41a4e40ee6 $)
OS: win, Target: krom, GAPI: opengl, Blender: 2.79 (sub 1)
Exporting Scene
Armory Warning: No camera found in active scene
Armory Warning: No camera found in active scene layers
Armory Warning: Creating default camera
Scene built in 0.03198742866516113
Exported modules: []
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_CSM', '_SMAA', '_SSAO', '_Deferred', '_CSM', '_SMAA', '_SSAO']
Running:  ['D:/ArmoryBlender2.79/Armory/armsdk//nodejs/node.exe', 'D:/ArmoryBlender2.79/Armory/armsdk//Kha/make', 'krom', '--ffmpeg', 'D:\\ArmoryBlender2.79\\Ext\\ffmpeg.exe', '-g', 'opengl', '--shaderversion', '110', '--to', 'build_Test/debug']
Using Kha from D:\ArmoryBlender2.79\Armory\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_001_data.arm).
Exporting asset 1 of 1 (Material_002_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Plane.001.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (ssao_pass.frag.glsl).
Compiling shader 1 of 1 (translucent_resolve.frag.glsl).
Compiling shader 1 of 1 (translucent_resolve.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_001_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_001_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_001_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_002_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_002_shadowmap.vert.glsl).
Compiling shader 1 of 1 (Material_002_translucent.frag.glsl).
Compiling shader 1 of 1 (Material_002_translucent.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Done.
Finished in 4.235611200332642
Build failed, check console

**Comment by adriansnetlis** [comment]
```
Compiling shader 1 of 1 (translucent_resolve.frag.glsl) failed:
Shader compiler error.
```
Ye, the shader isn't right. Console doesn't tell what's wrong exactly, tho.

**Comment by luboslenco** [comment]
Is this with `Legacy Shaders` option enabled? Did you have issues with `Legacy Shaders` off?

**Comment by Hazukiaoi** [comment]
yes ,Legacy Shaders is enabled.
And turn Legacy Shaders off issues is fixed
