### ISSUE TITLE
Publish Error Class<kha.SystemImpl> has no field getPen

### ISSUE THREAD

**Issue by Hazukiaoi** [armory3d/armory#747]
I make a small game and it run in editor.But when i publish ,it say 

D:\ArmoryBlender2.79\Armory\armsdk\Kha\Sources/kha/input/Pen.hx:10: characters 9-26 : Class<kha.SystemImpl> has no field getPen

Game logic only use node editor.

Armory v0.5 ($Id: 7a1b4d39eb6568a933a1f63d17aa1a41a4e40ee6 $)
OS: win, Target: html5, GAPI: webgl, Blender: 2.79 (sub 1)

And the project file here
[Car_002.zip](https://github.com/armory3d/armory/files/2146031/Car_002.zip)

**Comment by luboslenco** [comment]
Looks like some version mismatch, are you using the latest `Armory_04b` as a base before updating to git version?

**Comment by Hazukiaoi** [comment]
Yes, I use latest Armory_04b download from itch and updating to git version

**Comment by luboslenco** [comment]
The error should be cause by a missing `getPen()` function at:
`D:\ArmoryBlender2.79\Armory\armsdk\Kha\Backends\HTML5\kha\SystemImpl.hx`

I am not sure why it's missing though.

Reference:
https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/SystemImpl.hx#L1076

**Comment by Hazukiaoi** [comment]
May be is update error.
I re-install the Armory 04b and update to git version is success export.
