### ISSUE TITLE
Skybox gets darker depending on Camera clipping. 

### ISSUE THREAD

**Issue by Muzz** [armory3d/armory#749]
100 Clipping
![image](https://user-images.githubusercontent.com/2074204/42131579-962d0366-7d48-11e8-9bad-779b6c5e3f1a.png)

1000 Clipping
![image](https://user-images.githubusercontent.com/2074204/42131580-a31b2e86-7d48-11e8-9937-8c5dd2fbdb64.png)

10000 Clipping.
![image](https://user-images.githubusercontent.com/2074204/42131582-aea45bba-7d48-11e8-9bf1-2ef0b3075b1e.png)

thanks!

**Comment by luboslenco** [comment]
Heyo, do you still have .blend for this? It seems to work ok here but maybe I am not triggering the issue properly.
