### ISSUE TITLE
HDR file throws invalid input in cmft

### ISSUE THREAD

**Issue by maximstewart** [armory3d/armory#750]
Environment Texture for the World Output node doesn't work or isn't implemented in Linux. I get a stack trace when running the game trying to use the Environment Texture. In addition, other nodes don't seem to actually work on the World Output node but they don't throw errors. It just seems like Environment Texture throws an error.

![screenshot_2018-07-01_15-23-28](https://user-images.githubusercontent.com/5226479/42138430-f31846e0-7d42-11e8-82de-af8d64907e51.png)
![screenshot_2018-07-01_15-24-06](https://user-images.githubusercontent.com/5226479/42138431-f3277e26-7d42-11e8-9871-f95cdb166d72.png)
![screenshot_2018-07-01_15-28-10](https://user-images.githubusercontent.com/5226479/42138453-6527bd74-7d43-11e8-941f-fec41d2f6a7c.png)

**Comment by luboslenco** [comment]
Hey, are you able to share the hdr.png map? Can you check this example to see if that works?
https://github.com/armory3d/armory_calibration/tree/master/env

**Comment by maximstewart** [comment]
Hi, OK, I just moved to Ubuntu 18.04 in order to eventually try out Armory with Blender 2.8 (Still on Armory Blender 1.79). I still get the same issues with my HDRs giving stack traces when using the  Environment Texture for the World Output node. Now, the test HDR you linked worked and no traces were generated.
I've attached a few of the HDRs that don't work.

NOTE: You'll need to change their extensions back to HDR since Github wont accept the extension type but does accept PNG. My bigger ones that are 21+ megs in size wont upload so am using my smaller sized ones. Neither the small nor large sized images work and throw errors except for the one you gave for me to test which does work.

![mealie_road_1k](https://user-images.githubusercontent.com/5226479/42547835-ae2269dc-8489-11e8-9341-e909f23f89d7.png)

![Uploading mossy_forest_1k.png…]()

![pond_1k](https://user-images.githubusercontent.com/5226479/42548016-83efdf18-848a-11e8-9d72-57e70d91ef53.png)

I took a screenshot of the images in Ghex to see if there were any differences but the only one I could tell is that the one that worked has RADIANCE in the beginning whereas my larger HDR that can't be attached has HDR near the beginning. One of my smaller HDRs has just RGBE. I don't know if this implies that the ones I have aren't true HDR or what but figured it could help you out.

![screenshot_2018-07-10_21-49-34](https://user-images.githubusercontent.com/5226479/42548195-91f7d06a-848b-11e8-994d-54a3b3f971cc.png)

**Comment by luboslenco** [comment]
Tried to investigate and it looks like the correct magic for the format is `#?RADIANCE` ([?](https://en.wikipedia.org/wiki/Radiance_(software)#HDR_image_format)). So the RGBE magic fails in [cmft](https://github.com/dariomanesku/cmft) which we use for environment map processing as it expects the `#?RADIANCE` header. Trying to open the file in renderdoc also fails. Replacing the header with `#?RADIANCE` should at least make it work.

**Comment by maximstewart** [comment]
Thanks for the update!! I'll check it out 'n see what I can get from it =]
