### ISSUE TITLE
Materials from linked blend file can not be found in nodes

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#751]
When referencing a material in a linked blend file, node tree won't be able to find it.
Rendering with linked materials work just fine.

[material_params.zip](https://github.com/armory3d/armory/files/2153331/material_params.zip)

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armory/commit/cd71de53591ef11d7f56c659216cdb44378a28da. 🔨
