### ISSUE TITLE
BlendSpace 1d,2d

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#754]
*(drag & drop zipped .blend file here)*

**Comment by slapin** [comment]
What is this? Could you explain? Is this that new godot thing added recently? Please add references to a things.

**Comment by Xristoskr** [comment]
https://docs.unrealengine.com/en-us/Engine/Animation/Blendspaces yes basically something similar to godot and ue4

**Comment by slapin** [comment]
This requires for animaion tree to be implemented first, which I really
really wait for.
@lubos do you have any roadmap for such things you could share?

I wonder what input in Blender could serve as data source for such thing?
I think animation tree is most important thing to get animations right...
As there is nothing
to source blendspace to.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/717.
