### ISSUE TITLE
Bullet function clearForces() not working

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#755]
try to use `clearForces()` for pausing a game, got error:
```
static public function pauseGame() {
    game_paused = true;
    for (rb in PhysicsWorld.active.rbMap) {
        rb.disableGravity();
        rb.body.clearForces();
        if (rb.body.isActive()) rb.body.setActivationState(BtCollisionObject.ISLAND_SLEEPING);
    }
}
```

![capture](https://user-images.githubusercontent.com/17811339/42219129-5cf2e2c6-7efd-11e8-9362-dafb62352232.JPG)

**Comment by MiloHX** [comment]
By the way, is there a better way to globally pause/resume the bullet physics simulation? I cannot find a good way to pause a game right now.

**Comment by luboslenco** [comment]
Did some [fixes](https://github.com/armory3d/armory/commit/370319a40d04fab1f4245633e49875793ef9c33b), to pause physics simulation:
`PhysicsWorld.active.timeScale = 0.0;`

To resume:
`PhysicsWorld.active.timeScale = 1.0;`

**Comment by MiloHX** [comment]
@luboslenco PhysicsWorld.active.timeScale is private currently, so I cannot directly access it. Should it be changed to public? Or maybe add getter/setter to use it?
