### ISSUE TITLE
Não aparece o armory

### ISSUE THREAD

**Issue by luan3dr** [armory3d/armory#759]
*(drag & drop zipped .blend file here)*
já baixei duas vezes fiz o mesmo processo e nada não aparece nada﻿

**Comment by luboslenco** [comment]
Sorry, please keep the issues in English.

(Based on translation - "Armory does not appear" - if you are on Windows press `Window - Toggle System Console` in Blender for potential errors. If you are on Linux/macOS, try starting from terminal.)
