### ISSUE TITLE
MSbuild.exe is not recognized

### ISSUE THREAD

**Issue by RedFrostGames** [armory3d/armory#76]
There have definitley been improvements from the previous build; less errors but this is what I'm getting this time when I press p:
![image](https://cloud.githubusercontent.com/assets/23486940/20862019/29bbad18-b96d-11e6-864b-da6bafb92c03.png)

**Comment by luboslenco** [comment]
Hi,

Happy to hear that! If you want to build for Native, you need a C++ compiler:
https://www.visualstudio.com/vs/community/

For development Krom/Electron is recommended, as the build times are way faster.

**Comment by RedFrostGames** [comment]
Ok, Armory appears to be working now sometimes. Thank you.

**Comment by luboslenco** [comment]
Wait, what does it mean sometimes? If stuff that should work still doesn't then more reports are always welcome.

**Comment by RedFrostGames** [comment]
When I used the scene1.blend, it worked all of the time but when I tried to play a blend that I had already made in the built in game renderer, 
![image](https://cloud.githubusercontent.com/assets/23486940/20868918/8cc0d0dc-ba35-11e6-86e2-39016db24c36.png)

**Comment by luboslenco** [comment]
General error handling now improved. Please open more issues with specific blend files producing errors.
