### ISSUE TITLE
Object quick placement tool

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#761]
This is a very needed tool for any 3D scene editing.

The suggested Blender addon "Asset Sketcher" is not a solution, the last plugin update is several years ago.
It has not been updated to work with BLender 2.7 and 2.8.

**Update logs

***21 June 2014***

    Tested the addon with Blender 2.69 and it seems to work fine here. Added Blender 2.6x to supported versions in the description.**

Armory will need a quick placement brush tool.

**Comment by luboslenco** [comment]
Hello,

The last update for Asset Sketcher at [blender market](https://blendermarket.com/products/asset-sketcher-v10) is dated 04 December 2017 and is marked as b2.79 compatible. Please use the existing topic at https://github.com/armory3d/armory/issues/698.
