### ISSUE TITLE
mesh directly parented to bone (not armature deform) not correctly positioned in some case

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#762]
If a bone has an unconnected parent bone, any mesh directly parented to the bone will get some offset in armory comparing to blender scene:
Test file (2.79): [bone_parent.zip](https://github.com/armory3d/armory/files/2175448/bone_parent.zip)
![capture](https://user-images.githubusercontent.com/17811339/42441681-58c9f62e-839b-11e8-9c52-7d92ea56c061.PNG)
![capture1](https://user-images.githubusercontent.com/17811339/42441688-5f40494a-839b-11e8-8c56-b0d171efa5b0.PNG)

**Comment by luboslenco** [comment]
Test file gives correct result now!
