### ISSUE TITLE
Problem with Remove Object Node

### ISSUE THREAD

**Issue by bigmanjoe** [armory3d/armory#764]
Okay so I have an invisible block set up to remove the laser shots when it is hit. It works fine unless you fire too fast. Then it does not seem to work eventually completely freezing up.

It could be my setup but I don't know. I have fiddled with the logic tweaked things and none of it worked so I went back to the original node set up.

[RemoveObjectGlitch.zip](https://github.com/armory3d/armory/files/2178530/RemoveObjectGlitch.zip)

**Comment by luboslenco** [comment]
Hey that looks cool. It should no longer freeze in [git version](https://armory3d.org/manual/#/dev/gitversion?id=armory-updater) now.

**Comment by bigmanjoe** [comment]
Better than it was, thanks!

**Comment by Chris200k** [comment]
Hello,

is the problem really fixed? I made a test and download your example. The remove node only works, if 1 Laser is "visible". If you fire faster, the other lasers wont be destroyed. I checked the oncontactnode.hx and the changes from git were in it.

Bye
Chris (sorry for bad english)
