### ISSUE TITLE
Liquid simulation not working

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#77]
Title says it all. Windows 7 Ultimate 64-bit OS and the file will be waiting in your forum inbox Lubos.

**Comment by George-the-1st** [comment]
turns out, regardless of the liquid simulation or not, the file I gave you gives a black screen when you render it. Though, when rendering with a debug window the debug window updates although nothing else does. Oh, and the debug window has a shadow imprint on the image layered under it. I know this because I expanded some things and collapsed them in the debug window and it left an imprint on the black screen so that also has to get fixed.

**Comment by luboslenco** [comment]
I am unable to find the blend file, last message I have from you is 4 days ago. Why not just attach the blend file here? Make it easier for me:)

Also, there is no such feature in Armory yet.

**Comment by George-the-1st** [comment]
ok then, I'll send it now. Oh and that would explain why it doesn't work, heh. Still, blackout problems are something that happened with and without the liquid simulation.
[simple.zip](https://github.com/armory3d/armory/files/635442/simple.zip)

**Comment by luboslenco** [comment]
Blackout now fixed.
