### ISSUE TITLE
[Enhancement] "Random (Transform)" Node and "Switch or Case Statement" Node

### ISSUE THREAD

**Issue by maximstewart** [armory3d/armory#771]
I would love to see a "Random (Transform)" node option in Armory. It'd be helpful in doing stuff like setting an object to jump randomly in a predefined space. Setting random scaling would be cool too but I'm personally looking for random jumping.

Also, it'd be cool to have a  "Switch or Case Statement" node where the Random (Int) node can select a certain action such as spawning an object or deleting it. I'm thinking you could take the "Sequence" node and change it a little to where you have an "int" slot plus the "in" slot. From there, you can add a number of case checks and attach nodes to each and the "in" input will select which to run.

I'd be happy to try and code this but don't know where to start to help you out. If I think I've figured out how to add new nodes and know how to do it, I'd be happy to help add them. If you have any tips on where I can start to learn the code that'd be helpful too. =]

**Comment by luboslenco** [comment]
Sorry about delayed response - `Switch (Int)` / `Switch (String)` etc. nodes would be handy! There is an intro to creating logic nodes in the manual at: https://armory3d.org/manual/#/dev/logicnodes

Actual example commit on the recent addition of `Contains String` node: https://github.com/armory3d/armory/commit/094c0e9597023025eca525d173e6f6d29b5201b6

Would something like this work for your random transform usage?
![capture](https://user-images.githubusercontent.com/3685704/43646464-4bfa51f2-9735-11e8-84a1-6a960f74aad7.PNG)

We could cook a helper node for that in the logic pack:
https://github.com/armory3d/logic_pack

**Comment by maximstewart** [comment]
Ironically, two hours after my submitting this ticket, I had quite literally seen a YouTube video that showed how to add nodes. I apologies for not coming back and editing this post to correct it. XD

As for the second part, that kinda works but what's needed is an "in" node so that one can do timings and a "object" node to select which object to do the transform. I know that if the node group is assigned to an object it'll do the transform on the object but there should be more control if wanted/needed. Since I am now aware of how to add nodes, I'll start looking to adding the two I requested.

**Comment by Devination** [comment]
@maximstewart there is a way to dynamically add slots to a node. Check out my PR #529 for an example. When set to the "And" or "Or" modes, the Gate node has the ability to add/remove inputs via a button.

**Comment by team9hacker** [comment]
@Devination Hey, that's good to know!! Thanks for the info. =]

**Comment by maximstewart** [comment]
OK, I've been trying to make a "Look At" node for practice before doing the others but keep getting issues with it.

Here's what it looks like:
![lookat](https://user-images.githubusercontent.com/5226479/43999305-73390dc6-9dcf-11e8-94b4-1b42f5a9c17d.png)

Here's the code:
![lookatcode](https://user-images.githubusercontent.com/5226479/43999321-c109688e-9dcf-11e8-8e75-96ad6dc2c4aa.png)

Basically, anything I do with the matrix causes the view/game to freeze up. Leaving them commented out makes the game work but without functionality for the node.

Note: The first object is supposed to be looking at the second object.

**Comment by maximstewart** [comment]
Closed since I created one of the nodes and #808 adds the switch node.
My Transform node the way I want it:  https://github.com/maximstewart/Created-Armory-Nodes
