### ISSUE TITLE
Shader compile bugs in Kode/Krom

### ISSUE THREAD

**Issue by poke1024** [armory3d/armory#772]
Probably a problem with Kha.

Somehow, debugging via Krom got permanently broken in all my Armory projects for me (worked fine like 15 min ago). Cleaning projects and manually throwing away `build` folders doesn't help. Projects work fine when running them through "Play" (and Krom) from Blender. HTML5 target also works fine in Blender and in Kode (i.e. shader compile works for HTML5).

Using Armory_04_mac_b28.

I have no idea how to debug this.

Output in Kode:

Using Kha from Home/Downloads/Armory 2/blender.app/armsdk/Kha
Creating Kha project.
Exporting asset 1 of 1 (armdefault_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Plane.004.arm).
Exporting asset 1 of 1 (mesh_Plane.008.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (ssao_pass.frag.glsl).
Compiling shader 1 of 1 (ssao_pass.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl).
Compiling shader 1 of 1 (armdefault_mesh.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl).
Compiling shader 1 of 1 (armdefault_mesh.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.frag.glsl) failed:
Shader compiler error.
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl).
Compiling shader 1 of 1 (armdefault_shadowmap.vert.glsl) failed:
Shader compiler error.
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl) failed:
Shader compiler error.
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl) failed:
Shader compiler error.
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl) failed:
Shader compiler error.
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl) failed:
Shader compiler error.
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl) failed:
Shader compiler error.
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl) failed:
Shader compiler error.
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl) failed:
Shader compiler error.
Compiling shader 8 of 8 (painter-video.vert.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl) failed:
Shader compiler error.
Done.
Discovering targets via http://127.0.0.1:14290/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:14290
Discovering targets via http://127.0.0.1:14290/json
Paths.scriptParsed: resolved krom.js to Home/Desktop/Nape/build/krom/krom.js. webRoot: Home/Desktop/Nape/build/krom
SourceMaps.getMapForGeneratedPath: Finding SourceMap for Home/Desktop/Nape/build/krom/krom.js by URI: krom.js.temp.map and webRoot: Home/Desktop/Nape/build/krom
SourceMaps.loadSourceMapContents: Reading local sourcemap file from Home/Desktop/Nape/build/krom/krom.js.temp.map
SourceMap: creating for Home/Desktop/Nape/build/krom/krom.js
SourceMap: sourceRoot: file:///
SourceMap: sources: ["Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/HxOverrides.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/Lambda.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/List.hx","Home/Desktop/Nape/Sources/Main.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/Reflect.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/Std.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/StringTools.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/Type.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/UInt.hx","/private/var/folders/pp/n5gfd7pd5r924mt65zdnm7b00000gp/T/AppTranslocation/62B0181F-DD4A-4E77-96BA-BC71E5B8BEFC/d/blender.app/armsdk/iron/Sources/iron/Trait.hx","Home/Desktop/Nape/Sources/arm/Box2DWorld.hx","Home/Desktop/Nape/Libraries/nape/nape/geom/Vec2.hx","Home/Desktop/Nape/Libraries/nape/zpp_nape/geom/Vec2.hx","Home/Desktop/Nape/Sources/arm/ExtractMesh.hx","/private/var/folders/pp/n5gfd7pd5r924mt65zdnm7b00000gp/T/AppTranslocation/62B0181F-DD4A-4E77-96BA-BC71E5B8BEFC/d/blender.app/armsdk/armory/Sources/armory/data/Config.hx","/private/var/folders/pp/n5gfd7pd5r924mt65zdnm7b00000gp/T/AppTranslocation/62B0181F-DD4A-4E77-96BA-BC71E5B8BEFC/d/blender.app/armsdk/armory[...]
SourceMap: webRoot: Home/Desktop/Nape/build/krom
SourceMap: resolved sourceRoot file:/// -> 
SourceMaps.scriptParsed: Home/Desktop/Nape/build/krom/krom.js was just loaded and has mapped sources: ["Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/HxOverrides.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/Lambda.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/List.hx","Home/Desktop/Nape/Sources/Main.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/Reflect.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/Std.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/StringTools.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/js/_std/Type.hx","Home/Downloads/Armory 2/blender.app/armsdk/Kha/Tools/haxe/std/UInt.hx","/private/var/folders/pp/n5gfd7pd5r924mt65zdnm7b00000gp/T/AppTranslocation/62B0181F-DD4A-4E77-96BA-BC71E5B8BEFC/d/blender.app/armsdk/iron/Sources/iron/Trait.hx","Home/Desktop/Nape/Sources/arm/Box2DWorld.hx","Home/Desktop/Nape/Libraries/nape/nape/geom/Vec2.hx","Home/Desktop/Nape/Libraries/nape/zpp_nape/geom/Vec2.hx","Home/Desktop/Nape/Sources/arm/ExtractMesh.hx","/private/var/folders/pp/n5gfd7pd5r924mt65zdnm7b00000gp/T/AppTranslocation/62B0181F-DD4A-4E77-96BA-BC71E5B8BEFC/d/blender.app/armsdk/armory/Sources/armory/data/Config.hx","/private/var/folders/pp/n5gfd7pd5r924mt65zdnm[...]
Invalid JSON from target: (Unexpected token 
 in JSON at position 149): {"method":"Log.entryAdded","params":{"entry":{"source":"javascript","level":"log","text":"Trace: TypeError: Cannot read property 'bytes' of undefined
    at new $hxClasses.kha.graphics4.FragmentShader (krom.js:31682:54)
    at Function.kha_Shaders.init (krom.js:18996:36)
    at Function.kha_SystemImpl.init (krom.js:19585:14)
    at Function.kha_System.init (krom.js:19345:17)
    at Function.Main.start (krom.js:220:13)
    at Function.Main.main (krom.js:176:7)
    at krom.js:157463:6","timestamp":0}}}
Error handling message from target: Unexpected token 
 in JSON at position 149
Websocket closed
Terminated: websocket closed
Terminated: Got disconnect request

**Comment by poke1024** [comment]
Only happens with 2.8, seems to be related to macOS specific tmp paths, that no longer exist at the time of calling:

<img width="1269" alt="console-bug" src="https://user-images.githubusercontent.com/11859538/42990111-0bc6f556-8c02-11e8-8737-35166a93d1d9.png">

No problems with 2.7.

**Comment by poke1024** [comment]
For the record, I finally tracked this down to the following `direct3d11` reference (which doesn't work on macOS):

```
 let options = {
                from: args.cwd,
                to: path.join(args.cwd, 'build'),
                projectfile: 'khafile.js',
                target: 'krom',
                vr: 'none',
                pch: false,
                intermediate: '',
                graphics: 'direct3d11',
```

in https://github.com/Kode/vscode-krom-debug/blob/acdaecde02adc053225daf449c966685c08b2942/src/chromeDebugAdapter.ts.

(i.e. the version currently pinned inside Kode Studio).

In master, this is no longer there, so maybe everything works once Kode Studio updates to a new vscode-krom.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/745.
