### ISSUE TITLE
[BUG] Spawning scene with rigid body stops the physics. 

### ISSUE THREAD

**Issue by tomankirilov** [armory3d/armory#775]
When using the logic nodes and I try to spawn a rigid body it works just fine if there is no other rigid body in the scene. The moment another rigid body exists - the physics just stop working. It also breaks if I spawn more then one rigid body. The first one works (if there is no other in the scene) but the second one breaks.

[main.zip](https://github.com/armory3d/armory/files/2200301/main.zip)

**Comment by gamergamesz** [comment]
just give your base i.e terrain a passive rigidbody with terrain box checked below in Armory props [main.zip](https://github.com/armory3d/armory/files/2200361/main.zip)

**Comment by luboslenco** [comment]
Should no longer freeze in git armory.
