### ISSUE TITLE
Is there an example of network communication that can be used?

### ISSUE THREAD

**Issue by plumsky** [armory3d/armory#776]
I want to connect a game server by TCP, is Armory now can support this?

**Comment by xwolf47** [comment]
Oh.., this is not Armory‘s busniess. Haxe can do this job. 
Create a new script for any object (like plane) in blender, 
switch for object -> Armory Traits -> New Script -> type name 'NetworkTrait' -> Edit Script
Input code below example:
```
package arm;
import sys.net.Socket;
import cpp.vm.Thread;

class NetworkTrait extends iron.Trait {
	static var mClient = new sys.net.Socket();
	var mReadThread:Thread;

	public function new() {
		super();

		mClient.connect(new sys.net.Host("localhost"), 3001);

		mClient.write("Hello, I'm Armory!");

		mReadThread = Thread.create(netWork);
	}

	static function netWork() {
		while(true) {
			mClient.write("I'm waiting your talk!");
			mClient.waitForRead();
			var msg = mClient.read();
			trace(msg);
		}
	}
}
```
Compile it for cpp.
If have local server with 3001 port, it will work. Good luck!

**Comment by plumsky** [comment]
Thanks! It's good for start!

**Comment by moxiaomomo** [comment]
> Oh.., this is not Armory‘s busniess. Haxe can do this job.
> Create a new script for any object (like plane) in blender,
> switch for object -> Armory Traits -> New Script -> type name 'NetworkTrait' -> Edit Script
> Input code below example:
> 
> ```
> package arm;
> import sys.net.Socket;
> import cpp.vm.Thread;
> 
> class NetworkTrait extends iron.Trait {
> 	static var mClient = new sys.net.Socket();
> 	var mReadThread:Thread;
> 
> 	public function new() {
> 		super();
> 
> 		mClient.connect(new sys.net.Host("localhost"), 3001);
> 
> 		mClient.write("Hello, I'm Armory!");
> 
> 		mReadThread = Thread.create(netWork);
> 	}
> 
> 	static function netWork() {
> 		while(true) {
> 			mClient.write("I'm waiting your talk!");
> 			mClient.waitForRead();
> 			var msg = mClient.read();
> 			trace(msg);
> 		}
> 	}
> }
> ```
> 
> Compile it for cpp.
> If have local server with 3001 port, it will work. Good luck!

It seems that now we should use `sys.thread.Thread` instead, as `cpp.vm.Thread` is deprecated.

**Comment by PowerBroker2** [comment]
> Compile it for cpp.

How do you do that?

**Comment by Onek8** [comment]
https://github.com/armory3d/armory_examples/tree/master/network_zui_chat
