### ISSUE TITLE
Use relative paths in khafile.js

### ISSUE THREAD

**Issue by sh-dave** [armory3d/armory#778]
Trying to setup #777,

i noticed that the generated `khafile.js` contains quite a lot of absolute paths. This is a bit inconvenient when i want to try and build the project on a machine without armory installed (say a VM to test building on another platform). I want to just checkout, `node Kha/make whatever` and let it run. What i think about doing, would be to add add a checkbox 'Generate relative paths' in the `Armory Project / Build` panel, and then try to update the code where `khafile.js` is written. (The default setting would be to leave it unchecked, as i guess not a lot of people are going to benefit from it).

Do you think this is a viable idea, or have a better suggestion?

**Comment by luboslenco** [comment]
Would be a nice addition. Unless there is a reason to have it per-project, maybe stuck it into [armory.py](https://github.com/armory3d/armory/blob/master/blender/addon/armory.py) as a global user setting?

I think the original reason for moving to absolute paths by default was .blend file referencing assets from various disks on Windows, or something like that.

**Comment by luboslenco** [comment]
Added option into Armory add-on preferences to generate relative paths. https://github.com/armory3d/armory/commit/6642f5a3a12d74b32dbbcb16d88b4fdfb1ce544a

**Comment by sh-dave** [comment]
Oh wow cool already done, wanted to wait until blender 2.8 support is fully done before i dive into.
