### ISSUE TITLE
Auto-clean when making module changes

### ISSUE THREAD

**Issue by poke1024** [armory3d/armory#779]
This can be confusing for newbies. If you change anything in the modules settings, you need to "Clean" or otherwise things won't take effect in Kode (i.e. symbols won't appear):

<img width="405" alt="modules" src="https://user-images.githubusercontent.com/11859538/42990156-389f4c54-8c02-11e8-8d1b-a730fd1b7222.png">

Would be nice if there'd be an auto-clean here.

**Comment by luboslenco** [comment]
Pushed a fix at https://github.com/armory3d/armory/commit/563ec2eb44afcfd4c964413216ab67669220b906.
