### ISSUE TITLE
No transparent Shadow

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#78]
I managed to get the transparency working (works with BPR as long as its not set to 1, but works best with Cycles nodes).

Now the shadow being cast on the ground doesn't take the transparency into consideration!

See the forum post for a visual : http://forums.armory3d.org/t/transparency-tests/117

Let me know if you need the .blend

**Comment by luboslenco** [comment]
Continuing at https://github.com/armory3d/armory/issues/87
