### ISSUE TITLE
Instancing not working

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#781]
Run the instancing example with 2.79 build, I got this:
![capture](https://user-images.githubusercontent.com/17811339/43083058-2e0b8b2c-8ec8-11e8-9e27-812252c27fa5.JPG)

**Comment by MiloHX** [comment]
The celshade forest template which used instancing also got this problem:
![capture2](https://user-images.githubusercontent.com/17811339/43084900-2b080ee2-8ecc-11e8-9823-5d54eb2fc561.JPG)

**Comment by luboslenco** [comment]
Need to update Kha/Krom binaries for this, will pack Armory 0.5 builds this week. 📦

**Comment by MiloHX** [comment]
@luboslenco OK I will test it once 0.5 is out! BTW, I found that so far instancing only supported location. Will rotation and scale be added later?

**Comment by MiloHX** [comment]
Test OK in 0.5 alpha

**Comment by luboslenco** [comment]
Cool! Added a ticket for rot/scale support. https://github.com/armory3d/armory/issues/801
