### ISSUE TITLE
Logic Nodes aren't connecting to the object

### ISSUE THREAD

**Issue by Zeph-dev** [armory3d/armory#783]
When I use the Logic Bricks and connect it with an object, I build it, and it desn't do anything, or the object simply disappears. I use Blender 2.79, with Armory as an add-on. I'm not entirely sure on how to install it, but it seemed to work, but it just doesn't do anything when I make a build.

Please tell me if there is something I'm doing wrong or if this has already been asked, I'm still learning how to use GitHub. 

TIA,
Zeph

**Comment by Simonrazer** [comment]
Please include the .blend in a .zib so the problem is easier to see

**Comment by Zeph-dev** [comment]
Ah sorry, my bad, I didn't connect the nodes to the object properly. It works fine now! :)

**Comment by gamergamesz** [comment]
Close the issue then
