### ISSUE TITLE
Spawn object node broken

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#785]
If the Spawn object node is present in the tree this shows up in the console:

> 
> Compiling shader 8 of 8 (painter-video.vert.glsl).
> C:\Users\SK\Desktop\Armory\Armory\armsdk\armory\Sources/armory/logicnode/SpawnObjectNode.hx:24: characters 2-7 : Type not found : Scene
> 
> Done.
> Finished in 3.5207395553588867
> Build failed, check console

Context doesn't matter, otherwise empty .blend is enough

**Comment by luboslenco** [comment]
Argh, fixed in https://github.com/armory3d/armory/commit/fa05a3f599aab53be23cc5239cbdd1383e668cd8, thanks!
