### ISSUE TITLE
error_play viewport

### ISSUE THREAD

**Issue by egycno** [armory3d/armory#786]
Hi ,When I click the Play button, I get this
![the problem](https://user-images.githubusercontent.com/31624258/43529356-f1578a3e-955f-11e8-94bb-5f37a8e391c4.png)
os : windows 10 64bit
gpu : intel hd 3000

**Comment by luboslenco** [comment]
Hey, what is your armory version? Regular windows build from itch.io?

**Comment by egycno** [comment]
v4, I downloaded armory from itch.io

**Comment by luboslenco** [comment]
The only reason I can think of is that you are mixing projects with amorpaint in the same folder. Try to place your project in a separate one.

**Comment by egycno** [comment]
no , it is not

**Comment by luboslenco** [comment]
Can you elaborate on that? Did using separate folder not fix it? Sorry I need more details otherwise I am unable to help.

**Comment by egycno** [comment]
![info2](https://user-images.githubusercontent.com/31624258/43536637-f6dd39e2-9571-11e8-8cb1-402c0e476248.png)
![info3](https://user-images.githubusercontent.com/31624258/43536638-f754fd60-9571-11e8-8b10-fcc5819bf08f.png)
![info4](https://user-images.githubusercontent.com/31624258/43536639-f7b540f8-9571-11e8-9d20-acbc12d3765c.png)
![info](https://user-images.githubusercontent.com/31624258/43536641-f82b0180-9571-11e8-9505-a4d08bfa1009.png)

**Comment by luboslenco** [comment]
Try saving your .blend file into separate folder like `C:\Users\your_username\Documents\Test` and play from there like mentioned.

If that does not help, you could search for the `copy_mrt3_pass` file to see what pulls it in - this file should not exist at all in Armory 0.4 - that is why I guessed it is being referenced because of armorpaint by placing these projects in the same folder. 

Last resort - try updating your Armory to git version using the [updater](https://armory3d.org/manual/#/dev/gitversion?id=armory-updater).

Hope that helps.

**Comment by egycno** [comment]
It works, but when I try to open armorpaint.blend gives me the previous error message, and when I open my file, I get the message back, but when I go restart blender, my file works well.
I think the problem is actually in armorpaint, so how do I open the armorpaint.blend file and make it play without getting the same error message ?

**Comment by egycno** [comment]
Ok,The problem of running Armory has been solved, but there is still another problem , I did the last tips on armorpaint.blend file " I copied armorpaint.blend  only from the original armorpaint file to the test file " and after that I clicked the play but I did not  get the Message , I got this
![the problem 2](https://user-images.githubusercontent.com/31624258/43682569-917b2f6e-982d-11e8-9a36-0aa6459526fc.png)
I'm sorry if I bothered you with a lot of questions

**Comment by egycno** [comment]
the console :
Read prefs: C:\Users\╪¿┘ê╪»┘è\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 44100hz instead
found bundled python: C:\Users\Public\Pictures\Armory\2.79\python
Read blend: C:\Users\Public\Pictures\test3\armorpaint.blend

Armory v0.4 ($Id: 97fc5021306ba3e6d744b62e6614e853412df34b $)
OS: win, Target: krom, GAPI: opengl, Blender: 2.79 (sub 0)
Armory Warning: World - unable to open //Env\cay.hdr
Exporting Scene
Armory Warning: Material Material/tex.jpg - file not found(//tex.jpg)
Scene built in 0.015436887741088867
Exported modules: ['ui']
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_SMAA', '_Veloc', '_SSAO', '_gbuffer2']
Running:  ['C:/Users/Public/Pictures/Armory/armsdk//nodejs/node.exe', 'C:/Users/Public/Pictures/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--to', 'build_armorpaint/debug']
Using Kha from C:\Users\Public\Pictures\Armory\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (mesh_Plane.arm).
Exporting asset 1 of 1 (mesh_Sphere.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (droid_sans.ttf).
Compiling shader 1 of 1 (bloom_pass.frag.glsl).
Compiling shader 1 of 1 (blur_gaus_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.frag.glsl).
Compiling shader 1 of 1 (compositor_pass.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect.vert.glsl).
Compiling shader 1 of 1 (deferred_light.frag.glsl).
Compiling shader 1 of 1 (deferred_light_quad.frag.glsl).
Compiling shader 1 of 1 (pass.vert.glsl).
Compiling shader 1 of 1 (pass_copy.frag.glsl).
Compiling shader 1 of 1 (pass_lamp_volume.vert.glsl).
Compiling shader 1 of 1 (pass_viewray.vert.glsl).
Compiling shader 1 of 1 (pass_viewray2.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend.vert.glsl).
Compiling shader 1 of 1 (ssgi_blur_pass.frag.glsl).
Compiling shader 1 of 1 (ssgi_pass.frag.glsl).
Compiling shader 1 of 1 (taa_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.frag.glsl).
Compiling shader 1 of 1 (world_pass.vert.glsl).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Type not found : arm.App

Done.
Finished in 13.614105939865112
Build failed, check console
ui_do_but_textedit: utf8 char '╪ñ'
ui_do_but_textedit: utf8 char '╪«'
ui_do_but_textedit: utf8 char '┘ë'
ui_do_but_textedit: utf8 char '╪│'
ui_do_but_textedit: utf8 char '╪«'
ui_do_but_textedit: utf8 char '┘à'
ui_do_but_textedit: utf8 char '╪½'

**Comment by luboslenco** [comment]
> I did the last tips on armorpaint.blend file " I copied armorpaint.blend only from the original armorpaint file to the test file "

I am not sure I follow. Nonetheless, to compile git version of armorpaint you will need to use git version of armory (see [note](https://github.com/armory3d/armorpaint/blob/master/README.md)). It's probable better to play with armory first before jumping onto armorpaint development.
