### ISSUE TITLE
Armory can't open 4K size texture ... build failed each time

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#787]
*(drag & drop zipped .blend file here)*
i have a window opened says to me can't open png files ... So is there a texture milit size ?? my color.png is about 33mo

**Comment by luboslenco** [comment]
Does it fail with every 4k sized texture or just this one? What target - Krom + Windows?

**Comment by mistajuliax** [comment]
It seems to work now, i can't reproduce the bug ... But iyt was in krom with git version ...
