### ISSUE TITLE
Disappearing faces and unchanged objects

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#79]
When played in browser mode, my file has the walls of my basket/floor disappear but not the base. The normals are all correctly oriented on all objects and this doesn't occur when played in electron mode. Also, none but one cube has the subdivision surface modifier applied to it actually show up rendered in either mode (I used Ctrl+L to link the modifier data, that may have something to do with it in which case it is a bug that needs to be sorted). File is a newly generated one here: 
[simple 1.zip](https://github.com/armory3d/armory/files/635566/simple.1.zip)

**Comment by luboslenco** [comment]
Appears to be working now.
