### ISSUE TITLE
Cloth driver no collision

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#790]
in armory from git Build failed. 
![build failed](https://user-images.githubusercontent.com/7542691/43653946-eb1a0ade-9749-11e8-8d2f-8c4a66af6a59.jpg)
In armory 04 from itchio, build work but collision doesn't. I made a simple setup, a cube as collider, and a cloth driver to deform my mesh. 
[Collisions_test.zip](https://github.com/armory3d/armory/files/2258053/Collisions_test.zip)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/874.
