### ISSUE TITLE
Hue Saturation Value node is off

### ISSUE THREAD

**Issue by zaethan** [armory3d/armory#794]
It looks like the "hue" variable is interpreted differently in blender and in armory.
![image](https://user-images.githubusercontent.com/39460066/43665380-395fbe20-9770-11e8-9203-b137fd514ef1.png)
Blender maps the hue like this:
- 0 as -180° rotation
- 0.5 as 0°
- 1 as +180°

as described here https://docs.blender.org/manual/en/dev/render/cycles/nodes/types/color/hue_saturation.html under properties hue, I would _guess_ that armory probably maps the hue like this
- 0 as 0° rotation
- 1 as 360°

**Comment by luboslenco** [comment]
Thanks for mentioning the fix! Should be ok now.
