### ISSUE TITLE
Software requirement for Armory3d

### ISSUE THREAD

**Issue by TheCoderAsif** [armory3d/armory#795]
Is there any software required for Armory3d.
Also I'm having some trouble.
![arm](https://user-images.githubusercontent.com/25789388/43676612-56c36668-97a9-11e8-9b52-dc12d8efc5bc.PNG)

*(drag & drop zipped .blend file here)*

**Comment by sh-dave** [comment]
I think you might be missing an installed [git](https://git-scm.org).

**Comment by TheCoderAsif** [comment]
But I don't think git is required for blender or armory3d...

**Comment by sh-dave** [comment]
Hm, did you click the `update sdk` button, because
`subprocess.open(['git', 'clone', 'https://github.com/armory3d/armory' ...)`
in the callstack looks like it?

**Comment by luboslenco** [comment]
Armory Updater needs git, some more info:
https://armory3d.org/manual/#/dev/gitversion?id=armory-updater

When using regular releases, git is not required.
