### ISSUE TITLE
IK goal parented to armature solving wrong

### ISSUE THREAD

**Issue by antomicek** [armory3d/armory#796]
If I parent "goal" object to armature and translate whole armature, IK solving is wrong. 

Also it would be great to set how many bones are in chain. Or controlling influence/animation ratio (like in blender inverse kinematics bone constrain.
*(drag & drop zipped .blend file here)*
![ik node](https://user-images.githubusercontent.com/42112273/43685376-500e8c44-98b2-11e8-8987-37aa1030add8.jpg)

**Comment by Didiercode** [comment]
Trying to replace the actual mesh Alpha_Surface with another one isn't trivial ... did you test it ?

**Comment by QuantumCoderQC** [comment]
Fixed via #2206 

May be closed
