### ISSUE TITLE
Error First Compile intent "Type not found: Main"

### ISSUE THREAD

**Issue by Emiliano6aston** [armory3d/armory#797]
Hello! I got this error the first time i pick the button compile. I try downloading and installing all over again  and not work. 
Console text:
"Read prefs: C:\Users\Emiliano\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
AL lib: (EE) UpdateDeviceParams: Failed to set 48000hz, got 192000hz instead
Warning! Unable to find a multisample pixel format that supports exactly 2 samples. Substituting one that uses 4 samples.
found bundled python: C:\Dev\Armory\2.79\python
path not found
path not found
Info: Total files 1 | Changed 1 | Failed 0

Armory v0.4 ($Id: 97fc5021306ba3e6d744b62e6614e853412df34b $)
OS: win, Target: krom, GAPI: opengl, Blender: 2.79 (sub 0)
Exporting Scene
Exporting mesh Cube
Scene built in 0.009994268417358398
Exported modules: []
Shader flags: ['_Irr', '_EnvCol', '_Deferred', '_CSM', '_SMAA', '_SSAO']
Running:  ['C:/Dev/Armory/armsdk//nodejs/node.exe', 'C:/Dev/Armory/armsdk//Kha/make', 'krom', '-g', 'opengl', '--shaderversion', '330', '--to', 'build_Demo_A3D/debug']
Using Kha from C:\Dev\Armory\armsdk\Kha
Creating Kha project.
Exporting asset 1 of 1 (Material_data.arm).
Exporting asset 1 of 1 (shader_datas.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (smaa_area.png).
Exporting asset 1 of 1 (smaa_search.png).
Exporting asset 1 of 1 (World_irradiance.arm).
Compiling shader 1 of 1 (Material_mesh.frag.glsl).
Compiling shader 1 of 1 (Material_mesh.vert.glsl).
Compiling shader 1 of 1 (Material_shadowmap.frag.glsl).
Compiling shader 1 of 1 (Material_shadowmap.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-image.frag.glsl).
Compiling shader 3 of 8 (painter-image.vert.glsl).
Compiling shader 4 of 8 (painter-text.frag.glsl).
Compiling shader 5 of 8 (painter-text.vert.glsl).
Compiling shader 6 of 8 (painter-colored.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
Type not found : Main

Done.
Finished in 3.6488232612609863
Build failed, check console"

**Comment by luboslenco** [comment]
Hello! Try saving your .blend in a safe path like `C:\Users\user_name\Documents\test`, otherwise Windows may prevent writing the files.

**Comment by Emiliano6aston** [comment]
Mmm. Ok I will try that.

**Comment by Emiliano6aston** [comment]
Thanks, Thath work!
