### ISSUE TITLE
Using vertex colors for displacement throws compilation error.

### ISSUE THREAD

**Issue by 8BitsGotByte** [armory3d/armory#798]
Would love to use vertex colors as a mask to limit displacement but it seems the shader compiler is not ok with it.

![screenshot 2018-08-06 11 50 07](https://user-images.githubusercontent.com/40199415/43710510-22cb7abc-9970-11e8-8391-fe665b35b092.png)

Blender scene: [displacement.zip](https://github.com/armory3d/armory/files/2262062/displacement.zip)

**Comment by luboslenco** [comment]
Fixed now, thanks for opening an issue!

**Comment by 8BitsGotByte** [comment]
No thank you for being so active and giving us the amazing armory 3d :)
