### ISSUE TITLE
Particle smoke example build failed 

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#799]
![12](https://user-images.githubusercontent.com/23359603/43728608-48f49b36-99ae-11e8-9a0b-53db71efbbe9.png)
![13](https://user-images.githubusercontent.com/23359603/43728609-4957c260-99ae-11e8-940a-60a3b6ecd028.png)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
It's back, thanks! https://github.com/armory3d/armory/commit/dfe3e04606bc4c89d544427b758fd198349e8d4a
