### ISSUE TITLE
Cloth Simulation

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#8]
Just occurred to me that cloth simulation would be a nice addition.  Should be possible to implement, as Unity3D and Unreal Engine are both able to do real-time cloth physics.

**Comment by adriansnetlis** [comment]
Hi! I am ready to help. I can do 2 soft-body physics components.
One is the shape-match version. Similar to what's used by BGE. Not as realistic, but easy to set up(for user). The second one would be like Rigs of Rods or BeamNG - full spring/mass system. Requires more advanced setup from user side(e.g. must put springs where he/she wouldn't expect to), but is very realistic and can be used for many things.

Are you interested?:)

**Comment by luboslenco** [comment]
@adriansnetlis Totally! Just give me some time to finish the docs to make contributing easy:)

**Comment by adriansnetlis** [comment]
@luboslenco Great! I'll get ready to work.
Note that I'm working on a Rigs of Rods project called 'Next Sim' (http://forum.rigsofrods.org/thread-367.html) and thus my experience is getting bigger and I am learning more about soft bodies each minute. I hope to help you as much as possible because this is the best game engine project that I've ever seen in my life:)

**Comment by adriansnetlis** [comment]
https://www.youtube.com/watch?v=VZXJpsycTNU
This is how my soft-body physics system tests looks. It's yet early WIP and lacks of some features(e.g. visual skinning). I'd love to see this in Armory engine once it's done!:)

**Comment by JeannotLandry** [comment]
That is pretty cool! I don't like the way BGE handles soft bodies, there should be an easier way using vertex groups as opposed to adding manual constraint and trying to match them to certain vertex.

**Comment by bibleuspro** [comment]
One nice thing about playing nice with BGE is they have tasks on developer.blender.org and visibility.
Here is cloth issue that could get more eyes.
https://developer.blender.org/T45576

**Comment by luboslenco** [comment]
Basics are now available in https://github.com/armory3d/armory_examples/tree/master/physics_softbody, will eventually take it further.
