### ISSUE TITLE
Celshader driver option ghosts into other projects

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#800]
Problem:

The "Forest" example for the celshading driver contains an option to pick between `Armory` and `Celshade`. Which works fine in the example. Upon opening another project the options persist. If you pick celshade you can't compile anymore. If you reopen the current project the options will be gone and no way of going back to `Armory`.

Steps:

1. Open [forest.blend](https://github.com/armory3d/armory_templates/tree/master/celshade)
2. Open another project
3. Option from forest.blend persists.

**Comment by luboslenco** [comment]
Fixed! https://github.com/armory3d/armory/commit/0750dcbc14e61f0f8ea92767678df8f9637f46d6
