### ISSUE TITLE
update excuting on object that was removed previous frame. Causes null crash.

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armory#803]
Hello. I am working on a space shooting game and documenting how it's done for the community on YouTube. 

Every frame I check the bullet to see if the has a collision or is so old it should be removed. 

After calling the object.remove() function sometimes(it is not consistent) the next update will still attempt to to call my object. However this object is now removed so the game crashes. I'm guessing some kind of race condition exists in the Armory engine where the remove and update functions are out of sync?

![screen shot 2018-08-08 at 6 10 27 pm](https://user-images.githubusercontent.com/2245494/43872392-61229986-9b36-11e8-88e5-5f5cd0f41ba2.png)

If you could take a look @luboslenco I would greatly appreciate it. thank you.
https://github.com/kenthinson/Armory3D_SpaceGame

**Comment by luboslenco** [comment]
Hey, this should be fixed now on git armory, sorry for delay!
https://github.com/armory3d/iron/commit/d427e39ffa42a22c00b4daecde80e6c834389165

**Comment by kenthinson** [comment]
@luboslenco Totally awesome. You rock! Will test it :)

**Comment by kenthinson** [comment]
@luboslenco seems to be fixed. Closing the issue Great job🥇
