### ISSUE TITLE
"Can not enlarge memory" error when Rigid body type "Animated" Check box is enabled.

### ISSUE THREAD

**Issue by cumminham** [armory3d/armory#805]
I am not a coder myself so i hesitate to call this a bug, I'm almost certain it is in fact a bug due to the fact that it only triggers if the check box Labled "animated" in the rigid body type tab  is enabled.
it functions as expected but it seems to cause crashes after running for a couple of minutes. (8-10)
ive been told this seems to be a memory leak... but i don't know.

[game test.zip](https://github.com/armory3d/armory/files/2276720/game.test.zip)

**Comment by cumminham** [comment]
I did a test that were i took the raycast example and checked the animated box. It hit the error slower then before... like an hour or two... but im now 100% sure its the animated check box that needs tweaking.

**Comment by luboslenco** [comment]
Merging into https://github.com/armory3d/armory/issues/835. Thanks for test file, I am on it. 🙂
