### ISSUE TITLE
[Shader]Attaching attribute time to multiple nodes, with texture node, results in krafix error

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#807]
Error:
`ERROR: E:\Files\Blender\TestFolder\build_box\compiled\Shaders\Blip_translucent.frag.glsl:50: 'Attribute_Fac_res' : undeclared identifier`

steps:

1. Include a texture node
2. Create attribute node, set name to time
3. Connect Fac to multiple nodes

Additional information render path preset set to "Max", don't think this matters

Fix:

Create separate Attribute nodes for outputs.

[Blip.zip](https://github.com/armory3d/armory/files/2280602/Blip.zip)

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armory/commit/9f2033c36a5fc83f671836d37f707731fe6d880e.
