### ISSUE TITLE
Sound does not work on Mac OS

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armory#809]
Sound does not on mac os when using the krom runtime. 

I tried using the example project file and also my own  project no sound when using krom.

I also saw in the terminal output it's trying to load .ogg files instead of the included .wav files for some reason. I'm not sure why as I dont see anything about .ogg in the example project.

If I compile to HTML5 the sound works in a browser. If I compile to c++ the app says it compiles successfully but then it crashes right after launch.

![43869243-69b4ecb2-9b26-11e8-98cd-c49a45fcec83](https://user-images.githubusercontent.com/2245494/44001078-db7d5512-9ddf-11e8-9158-3c81945b8047.png)

**Comment by luboslenco** [comment]
Should be resolved now in ArmorySDK1909. Please download & setup the sdk from scratch from itch.io.
