### ISSUE TITLE
Request : Emission and refraction work without vxgi 

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#813]
*(drag & drop zipped .blend file here)*

**Comment by thesupremeliverwurst** [comment]
I support this proposition, but see the inherent difficulty, especially with refraction, as it's usually ray-traced. We could probably write our own shaders for it, but I have no experience whatsoever in the field. As it stands, the current glass, translucency, etc. is slightly broken, especially in 2.79. I might do some research on how to write that custom shader.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/521.
