### ISSUE TITLE
Particles problem

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#814]
I try to create waterfall with particles but i cant see them here the file 
[WAE.zip](https://github.com/armory3d/armory/files/2284134/WAE.zip)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Thanks for sharing the blend. It will show up now, just unwrap the particle plane first.

I have also added a new warning message and Armory will print `Geometry Plane.001 is missing UV map` to easily detect this.
