### ISSUE TITLE
Upgrade to Blender 2.8 Alpha 2

### ISSUE THREAD

**Issue by luboslenco** [armory3d/armory#816]
Wrap up Armory 0.5 release with latest b2.8 support.

**Comment by AndreaMonzini** [comment]
Hi, you can connect Blender and Ardour Daw timeline using Jack audio.

**Comment by luboslenco** [comment]
0.5 builds completed. Writing more docs, examples and release notes, then onto [0.6](https://github.com/armory3d/armory/projects/3)!

**Comment by Modanung** [comment]
Does this mean Armory will adopt Blender's new UI as well? I quite dislike some of the changes and I'm looking for a Blender fork that will not go along.
