### ISSUE TITLE
tessellation example build failed

### ISSUE THREAD

**Issue by Xristoskr** [armory3d/armory#817]
![15](https://user-images.githubusercontent.com/23359603/44086946-dda296de-9fc6-11e8-8e2a-17a45060d684.png)
![14](https://user-images.githubusercontent.com/23359603/44086951-e15d656a-9fc6-11e8-9626-fc81cb9fdc71.png)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
If you are using armory updater, are you on the latest version? This should be already fixed.
