### ISSUE TITLE
Armory failling on new build 4, even with the default cube, cam & light scene!

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#82]
So first run with the new build (ran the provided blender). So as usual, the first scene is the simple default scene with the cube, camera and lamp. So first test, try to play that, failed. I tried changing the path, I've deleted all other versions, etc.... Still gives me that same issue. 

Here is the console error:

Read new prefs: C:\Users\Jeannot\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend
found bundled python: E:\Armory\Armory_preview04_win64\Armory\2.78\python
measureit: Imported multifiles
version 3 imported
archimesh: Imported multifiles
serving at port 6687
trying to save userpref at C:\Users\Jeannot\AppData\Roaming\Blender Foundation\Blender\2.78\config\userpref.blend ok
<!> event has invalid window
MeasureIt: Cleaning data
Info: Total files 3 | Changed 3 | Failed 0
MeasureIt: Cleaning data
Exporting mesh Cube
Scene built in 0.008006572723388672
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.arm).
Exporting asset 1 of 1 (deferred_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO.arm).
Exporting asset 1 of 1 (brdf.png).
Exporting asset 1 of 1 (noise8.png).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (deferred_path_low.arm).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_CompoTonemap_CompoFXAA.vert.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (mesh_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (shadowmap_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO.vert.glsl).
Compiling shader 1 of 8 (painter-colored.frag.glsl).
Compiling shader 2 of 8 (painter-colored.vert.glsl).
Compiling shader 3 of 8 (painter-image.frag.glsl).
Compiling shader 4 of 8 (painter-image.vert.glsl).
Compiling shader 5 of 8 (painter-text.frag.glsl).
Compiling shader 6 of 8 (painter-text.vert.glsl).
Compiling shader 7 of 8 (painter-video.frag.glsl).
Compiling shader 8 of 8 (painter-video.vert.glsl).
E:\Armory\Sources/arm/node/NodeTree.hx:11: characters 18-26 : Type not found : ThisNode

Haxe compiler error.
Build failed, check console

**Comment by luboslenco** [comment]
Fixed nodes in https://github.com/armory3d/armory_examples/tree/master/scene1, can you get it to work now? Or did you use a different file as a base?

**Comment by JeannotLandry** [comment]
I simply used the provided blender with the default scene. I also tried the scene you've just provided, same issue. But it might be on my side. I will make a bit of cleanup and completely erase traces of the previous versions. I also had previously downloaded the zip version, now downloading the 7z version instead and trying that out.

**Comment by luboslenco** [comment]
There is no difference between 7z and zip versions apart from size. Can you save the default blend file on your machine and attach it here?

**Comment by JeannotLandry** [comment]
Well, I am trying to delete any version right now and its not letting me!

**Comment by JeannotLandry** [comment]
![cannotdeletearmoryfolders](https://cloud.githubusercontent.com/assets/14031486/21058719/a965b49e-be15-11e6-89ad-476f25b9cc44.jpg)
 Weird!

**Comment by JeannotLandry** [comment]
I am putting version 4 back and I will see if it fixes it or not, then I will attach the .blend if not.

**Comment by JeannotLandry** [comment]
Well, even trying to change the folder from place it gives me a long path error... Using windows 10 64 bits here. But I skipped the error, it moved it and now it works. So this is not an armory issue. Its a code 18! (18 inches behind the screen lol :P ).

You want me to close this issue or you do it?

**Comment by luboslenco** [comment]
It is Armory to blame for using the long paths, will make it as short as possible for next build:) Glad if somehow worked in the end. Tracking the issue here for reference: https://github.com/armory3d/armory/issues/80.
