### ISSUE TITLE
Armory cannot display full opaque whenever some portion of one material has opacity < 1.0

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#822]
Armory cannot display full opaque whenever some portion of one material has opacity < 1.0:
![unknown](https://user-images.githubusercontent.com/17811339/44249616-43cf1500-a223-11e8-8b4c-6a1f2eccd434.png)

Result: Left: Cycles; Right: Armory:
![unknown 1](https://user-images.githubusercontent.com/17811339/44249631-55182180-a223-11e8-8009-307e07f9975a.png)
Test File:  
[Transparency_test.zip](https://github.com/armory3d/armory/files/2296101/Transparency_test.zip)

System: Windows 10; GPU: GTX1070 Max-Q

**Comment by luboslenco** [comment]
Merging with issue at https://github.com/armory3d/armory/issues/768. It's the weakness of [wboit](http://casual-effects.blogspot.com/2015/03/implemented-weighted-blended-order.html) technique, will rework it for 0.6 to fix this. Thanks for including test file!
