### ISSUE TITLE
[FEATURE REQUEST] Armory for XR games

### ISSUE THREAD

**Issue by AdityaSrivastava2819** [armory3d/armory#823]
Hi Lubos
Is it possible to use Armory to create AR and VR games? XR games made in armory would surely be cool
P.S. This is a feature request. I saw it on the roadmap.
*(drag & drop zipped .blend file here)*

**Comment by sh-dave** [comment]
Not sure if it still works, but maybe try the [vr dino example](https://github.com/armory3d/armory_examples/tree/master/vr_dino).

**Comment by HeadClot** [comment]
@AdityaSrivastava2819 Currently it is possible to make VR games with Armory 3D. Unsure about AR games.

**Comment by luboslenco** [comment]
Merge with https://github.com/armory3d/armory/issues/282.
