### ISSUE TITLE
Mesh data not updated after doing undo

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#824]
![capture](https://user-images.githubusercontent.com/17811339/44266776-67638100-a25e-11e8-8f18-f32a09cb2067.JPG)

File:
[Voxel_AO.zip](https://github.com/armory3d/armory/files/2297214/Voxel_AO.zip)

**Comment by kenthinson** [comment]
@MiloHX what exactly is not matched? looks correct to me.
![screen shot 2018-08-17 at 7 54 40 am](https://user-images.githubusercontent.com/2245494/44272931-f9ce3b00-a1f2-11e8-9148-8d777f6cd09f.png)

**Comment by MiloHX** [comment]
@kenthinson Hello, the left yellow cube is not in the same size. This phenomenon can be created in these steps:
(1) in EDIT mode, scale one object up
(2) F5 to run Armory
(3) in OBJECT mode, Ctrl-Z
(4) F5 to run Armory again
(5) mistmatched

**Comment by kenthinson** [comment]
@MiloHX thanks for the clarification

**Comment by kenthinson** [comment]
@MiloHX I am testing the blend file here interesting that is it working correctly for me. Maybe @luboslenco  can shed some light on it for you. Also just to make sure. You are running the newest git code correct?

![screen shot 2018-08-17 at 10 05 50 am](https://user-images.githubusercontent.com/2245494/44279227-72d68e00-a205-11e8-940d-e82dc7350707.png)

**Comment by MiloHX** [comment]
@kenthinson, yes the easy way to fix this is tab into edit mode on that object. Lubos acknowledged about this issue in Discord, it is due to the undo(Ctrl Z) handling.

**Comment by luboslenco** [comment]
Should be fine now in b2.8.
