### ISSUE TITLE
Voxel AO is not initialized correctly when the scene is spawned

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#825]
If a scene is spawned, Voxel AO will not be initialized correctly:
![image](https://user-images.githubusercontent.com/17811339/44274292-60476d80-a274-11e8-8e22-59909493c027.png)

Test File (Press Enter in the "Start" scene to switch to "Main" scene)
[Voxel_AO.zip](https://github.com/armory3d/armory/files/2301530/Voxel_AO.zip)

**Comment by MiloHX** [comment]
I wonder if there are other settings other than Voxel AO having the same issue, better check!

**Comment by luboslenco** [comment]
Scene will now get revoxelized on switch.
For per-frame voxelization `Armory Render Path - Global Illumination - Revoxelize` can be enabled.
