### ISSUE TITLE
GPU Matrix skinning mode does not apply the armature scale

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#827]
In the attached example, if you use GPU dual quat skinning, the armature scale (0.25) will be applied. and the model is matching with the blender scene:
![image](https://user-images.githubusercontent.com/17811339/44292657-91499180-a2b8-11e8-9c68-b3ae653796d4.png)

Switch to GPU matrix skinning, the armature scale is ignored which makes the model scale up 4 times:
![image](https://user-images.githubusercontent.com/17811339/44292668-a7575200-a2b8-11e8-9410-2535c5380118.png)

Test File: [Matrix_Skinning.zip](https://github.com/armory3d/armory/files/2298971/Matrix_Skinning.zip)
Current temporary solution is to keep the armature scale to 1.0 when using matrix skinning.

/Milo

**Comment by luboslenco** [comment]
Using dual quat skinning exclusively now as it was performing the best.

**Comment by MiloHX** [comment]
@luboslenco referring to #376, bone scaling animation requires Matrix skinning, is there an alternative method using dual quat since Matrix skinning is gone?
