### ISSUE TITLE
Debug Console problems

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#83]
Debug console is unresponsive when clicking "play in viewport" button. Numbers do not move meaning no indication of the changing framerate is happening. Also, drop down menus also do not work. This same bug is not visible in either the electron, Krom, or browser mode so this is specifically in the noted configuration. Note that the drop down menus work perfectly in all other modes as well.

**Comment by luboslenco** [comment]
Is this on every blend scene? Note that you have to hover mouse over console to tag redraw.

**Comment by George-the-1st** [comment]
It appears not to be on every blend scene. It is on the one marked simple.blend though (you have access to that one from past but I'll link it here anyway). Hovering over it appears to do nothing though at least I'm seeing responsiveness after hovering over the console. This should update automatically though which I hope will be the case soon. Also, I noticed while dragging down the window to look into the log that the screen squeezes in on itself and this includes the console. I would suggest making it so that at least the console itself will stay the same but will simply be moved off screen as I make room for another console. It just seems like the digital equivalent of a welding spot when compared to the rest of Blender and the quality of your other work. (file: 
[simple.zip](https://github.com/armory3d/armory/files/642890/simple.zip) )

**Comment by luboslenco** [comment]
Console will now auto-update every second. Keeping further development at https://github.com/armory3d/armory/issues/85.
