### ISSUE TITLE
[Bug] Endless runner sample 0.5alpha bug

### ISSUE THREAD

**Issue by nassosyian** [armory3d/armory#830]
downloaded the 0.5alpha/blender2.79 build, updated the sdk,
tried to run “game_endlessrun” sample in HTML5 (browser)
and found a bug as shown in the following video

https://www.youtube.com/watch?v=puLwwYthpVk

the bug did *not* appear in the Krom build

**Comment by kenthinson** [comment]
looks like this was fixed with [0b184bf](https://github.com/armory3d/armory_examples/commit/0b184bfa4ce4b14bae02c167e7cbc6762ac3c28f)

**Comment by luboslenco** [comment]
Yes, sorry forgot to report. Should be good now.
