### ISSUE TITLE
Physics - objects getting stuck

### ISSUE THREAD

**Issue by AdityaSrivastava2819** [armory3d/armory#831]
Hey,
I was trying out the 3rd person shooter template and wanted to see the physics. So, I shot some boxes and finally got these images:-
 
![krom_2018-08-18_15-26-13](https://user-images.githubusercontent.com/37951362/44299684-ace48480-a318-11e8-806c-dd9d7d2e1099.png)

![krom_2018-08-18_15-26-29](https://user-images.githubusercontent.com/37951362/44299689-bff75480-a318-11e8-8475-39a29a412f4c.png)

See. That is not how it should behave in real life. Is this a bug of the physics engine or is it due to the settings of the template? Also is bullet engine good for making games?

One last thing, the crosshairs are not where the shots go, the gun is more like an automatic grenade launcher.

Oh, and that box is not touching the wall.
*(drag & drop zipped .blend file here)*

**Comment by kenthinson** [comment]
Yes in the discord people were talking about this bug. You can see even with a simple scene the object it floating. 
![screen shot 2018-08-18 at 11 27 08 am](https://user-images.githubusercontent.com/2245494/44302254-bf8b9900-a2d9-11e8-997e-c7cb52ff4a2b.png)

**Comment by AdityaSrivastava2819** [comment]
Yeah, in the template too, some objects were kinda floating and some cans
died not fall properly but stood in a peculiar manner.

**Comment by luboslenco** [comment]
Rigid bodies should no longer get stuck / float in odd angles. https://github.com/armory3d/armory/commit/c05ff52ece506b97d2b2e4ce872b4d274616135e
