### ISSUE TITLE
Icon setting in exporter not working for Krom

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#832]
I have tried to add an icon to the Armory Exporter setting. When exporting, the icon was copied to the root folder, other than that nothing happened. Is this feature not finished yet?

Platform: Windows 10
/Milo

**Comment by luboslenco** [comment]
I think it should work for c++ / c (hashlink) / ios / android targets, not yet for krom.

(Related: https://github.com/Kode/khamake/issues/86)

**Comment by sh-dave** [comment]
Did you add an `ICO` or `PNG` file? Koremake uses a `PNG` that it will convert (and i think it also has to be named `icon.png`).

**Comment by MiloHX** [comment]
@sh-dave, I used ICO before. Changed to PNG and test once just now, I got the same result (empty icon image).
Actually I thought Armory will converted the ICO to PNG and put it in root folder automatically.

**Comment by luboslenco** [comment]
I changed the description from `Icon` to `Icon (PNG)` to make it clearer. Will try to do auto-conversion eventually.

Not sure why you get the same result with png though. I tested with the image below and that seems to work.

![20436620](https://user-images.githubusercontent.com/3685704/44399267-3d081100-a547-11e8-9a73-e38d57d48fee.png)

**Comment by MiloHX** [comment]
@luboslenco 
In the end, it is windows 10 didn't want to show the icon correctly. Maybe I need to refresh windows icon cache to make it work.
![image](https://user-images.githubusercontent.com/17811339/44400463-d05c3900-a57d-11e8-850a-7ed725432077.png)

**Comment by luboslenco** [comment]
Added a note at https://armory3d.org/manual/#/deploy/windows, for Krom icon has to be changed manually.
