### ISSUE TITLE
Write Storage node - could not open file default.kha

### ISSUE THREAD

**Issue by Redfill** [armory3d/armory#833]
when using the Write Storage node there's a message saying that it couldn't open a file "Could not open file default.kha."

[write node issu.zip](https://github.com/armory3d/armory/files/2300023/write.node.issu.zip)
![image](https://user-images.githubusercontent.com/18517879/44305013-0cec2280-a33b-11e8-9a85-9c2322dafd67.png)

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/Kode/Krom/pull/107.

**Comment by luboslenco** [comment]
Fixed in 0.6alpha.
