### ISSUE TITLE
Cannot enlarge memory arrays error when doing a raycast

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#835]
My game froze after several minutes and I got the error below
Seems it happened when doing raycast. Not sure if it is a Kha, Armory or Bullet problem. This is the 2nd time I got this message, and seems it happens randomly,  I don't know exactly how to trigger this.
![image](https://user-images.githubusercontent.com/17811339/44324153-429e2200-a487-11e8-853f-32144e2fa38a.png)

The memory usage is not that high.
![image](https://user-images.githubusercontent.com/17811339/44324257-af192100-a487-11e8-9ebc-d81683080201.png)

I cannot share the blend file, but I may make a testing file to see if I can reproduce this error.
Unlike the https://github.com/armory3d/armory/issues/805, I didn't check the "Animated" checkbox. So I decided to make another bug report.

System: Windows 10
GPU: GTX1070 Max-Q

/Milo

**Comment by MiloHX** [comment]
I did a test which was doing 1000 raycast per frame, the game died very quickly. I though raycast, OR the physics module that the raycast is using, is the cause of this memory leak.
Test File:  [Ray_cast.zip](https://github.com/armory3d/armory/files/2301734/Ray_cast.zip)

**Comment by KosLooney** [comment]
It looks like a leak in bullets BtVector3 class.
There is no error when destroying the BtVector3 objects manually.

```
/*File*/
armory\trait\physics\bullet\PhysicsWorld.hx

public function rayCast(from:Vec4, to:Vec4):RigidBody {
		
	var rayFrom = BtVector3.create(from.x, from.y, from.z);
	var rayTo = BtVector3.create(to.x, to.y, to.z);
		
	var rayCallback = ClosestRayResultCallback.create(rayFrom, rayTo);
	world.rayTest(rayFrom, rayTo, rayCallback);

	Ammo.destroy(rayTo);
	Ammo.destroy(rayFrom);

	if (rayCallback.hasHit()) {
			
		#if js
			var co = rayCallback.get_m_collisionObject();
			var body = untyped Ammo.btRigidBody.prototype.upcast(co);
			var hit = rayCallback.get_m_hitPointWorld();
			hitPointWorld.set(hit.x(), hit.y(), hit.z());
			Ammo.destroy(hit);
			var userIndex = rbMap.get(untyped body.userIndex);
			Ammo.destroy(rayCallback);
			return userIndex;
		#elseif cpp
			var hit = rayCallback.m_hitPointWorld;
			hitPointWorld.set(hit.x(), hit.y(), hit.z());
			Ammo.destroy(hit);
			var userIndex = rbMap.get(rayCallback.m_collisionObject.getUserIndex());
			Ammo.destroy(rayCallback);
			return userIndex;
		#end
			
	}
	Ammo.destroy(rayCallback);
	return null;
}
```

**Comment by MiloHX** [comment]
@KosLooney, nice find! BtVector3 is all over the places...so eventually any game enabling physics will just die. @luboslenco I think this is a critical bug.

**Comment by MiloHX** [comment]
@luboslenco After the update today, I run the 1000 raycast per frame test for several minutes without error (before the update it prompt memory leak in < 5 sec). At least for this specific case, the problem is fixed.

**Comment by luboslenco** [comment]
Phew, this should be over now!
