### ISSUE TITLE
C++ Runtime type not working.

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#84]
In the "Armory Play" panel under render, selecting C++ as the runtime method and then pressing the play button does nothing. It does technically replace the button with a stop button for a few seconds as if it were to present me with a quick run of my game but it doesn't. This gives me the perception that code does occur in the background but that it does nothing. No error log is generated as far as I know with this bug.

**Comment by luboslenco** [comment]
There should to be something in the console output, can you paste that? Do you have C++ compiler installed on your machine? (Visual Studio Community 2015 will do)

**Comment by George-the-1st** [comment]
The console output was this: 
![capture](https://cloud.githubusercontent.com/assets/15915424/21059908/c6bc5988-be12-11e6-976f-2d13a1492541.JPG) Oh, and you didn't update the version to version 4 that is why it reads that way but it IS the latest version I assure you. As for the C++ compiler, I have Microsoft Visual C++ 2015 Redistributable so I should be good on that front.

**Comment by luboslenco** [comment]
- To see current Armory version check *Armory Project - Advanced - Armory v.*, currently 16.12. Not sure where the 'version 3 imported' comes from. Good idea though, will log current armory version to console.
- For C++ compiler get: https://www.visualstudio.com/vs/community/, (Redistributable will not do for compiling code)
- I have to fix those Haxe errors first:)

**Comment by luboslenco** [comment]
Should now work when Visual Studio is installed. Also Armory version is now being print to build log.
