### ISSUE TITLE
removeChild keepTransform not working as expected?

### ISSUE THREAD

**Issue by kenthinson** [armory3d/armory#840]
Possible bug not 100% sure. 
I added a spinning cube to the Scene. Then I added a animated Sphere as it's child. Every few frames I add another Sphere child. That is the first example in the video. The child spins with it's parent cube without issue. 

The second example I try to remove the child and keep it's transform after a small timer has completed. This I would expect would keep it's rotation and I would end up with many Spheres going in different directions as I remove them from the parent. Instead they seem to be reverting back to the original rotation. I have attached a video to help explain. If you need more information @luboslenco please let me know :)

https://drive.google.com/file/d/1le2uPAMBrDFon7R-p_vTJ94Ue4h1DnIs/view?usp=sharing

**Comment by luboslenco** [comment]
Appears to work nowadays.
