### ISSUE TITLE
MS Edge black screen and Render Path Presets

### ISSUE THREAD

**Issue by nassosyian** [armory3d/armory#841]
In the Endless runner sample 
when using the "Deferred" Render Path Preset 
i'm getting a black screen in MS Edge (v16.16299) browser 
and in the console log there is the following error:

```
 SystemImpl.hx:316: Could not initialize WebGL 2, falling back to WebGL.
kha.js (21332,3)

 SCRIPT5022: Error: Could not compile shader:
Shader compilation errors
(2, 1): Required extension GL_EXT_draw_buffers is not supported
(2, 41): Internal compiler error
kha.js (39494,3)
```
--------------
switching to "Forward" render path gives the following error:

```
SystemImpl.hx:316: Could not initialize WebGL 2, falling back to WebGL.
SCRIPT5022: Error: Could not compile shader:
Shader compilation errors
(2, 1): Required extension GL_EXT_shader_texture_lod is not supported
(2, 47): Internal compiler error
kha.js (39617,4)
```
--------------
disabling "Generate radiance textures" option, gives the following error:

```
SystemImpl.hx:316: Could not initialize WebGL 2, falling back to WebGL.
kha.js (21463,3)

 SCRIPT5022: Error: Could not compile shader:
Shader compilation errors
(36, 22): Incompatible index expression. For non-uniforms, the index must be an expression formed of the loop_index and integer constants. For uniforms, the index must be an integer constant.
kha.js (39616,3)
```
--------------

switching to "Low" render path preset (with radiance textures off) seems to work (!!!)
but i get the following warning:

 ```
SystemImpl.hx:316: Could not initialize WebGL 2, falling back to WebGL.
kha.js (21205,3)

6 WEBGL11157: INVALID_OPERATION: texImage2D: Invalid texture target and format combination
kha.js (37256,6)
```

[Request]

Could you please make change the "Low" render path to have "Generate radiance textures" OFF by default?

thanks.

**Comment by luboslenco** [comment]
Turned "Generate radiance textures" off for "Low" preset like suggested, hopefully that runs out of the box now. Will focus on better MS Edge support once they ship webgl2, which is currently listed as under consideration.
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webgl20/?q=webgl
