### ISSUE TITLE
Problem when switching from a scene with rigidbody to another scene

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#846]
**_NOTE: this is a newly introduced bug, it works before the recent update_**
Switching from a Scene with rigidbody to whatever scene will cause the "trap!" error from Ammo.js:
![image](https://user-images.githubusercontent.com/17811339/44599476-095c0e00-a809-11e8-8557-0955274d38f8.png)

I think it is caused by the memory leak fix.

Test file (Press space bar to switch scene):
[Scene_Switching.zip](https://github.com/armory3d/armory/files/2319338/Scene_Switching.zip)

**Comment by luboslenco** [comment]
Armory attempted to delete the rigid body twice on scene switch, fixed now. 🐛
