### ISSUE TITLE
Getting the exact same physics in Armory?

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#847]
I am trying to do some manipulation and simulate some soft body objects in a game-like environment. For this purpose, it looks like Armory is the best framework I can use as of now. However, it seems that Armory uses Bullet as the physics engine. I know the decision to use Bullet might have only been taken because of speed but I wonder if it's possible to replace Bullet with the built-in physics soft body engine? I know this might be very slow but this is something I need.

**Comment by zauberparacelsus** [comment]
Blender actually uses Bullet for its built-in physics, but the difference is that armory will presumably have it configured more for realtime physics simulation.

**Comment by Amir-Arsalan** [comment]
@zauberparacelsus Blender uses Bullet for its rigid body physics simulations. I know Bullet also has a soft body simulator but since it is designed to be used in real-time games it is pretty unrealistic. However, the built-in soft body physics '`softbody.c`' is more accurate but is also much slower. Here you can find a .blend file I used in Amory to do some soft body simulation. When you run the game however, the softbody physics do not match the soft body physics you get when you do `Alt + A`. Let me know what you think.

http://pasteall.org/blend/index.php?id=50227

**Comment by Amir-Arsalan** [comment]
@zauberparacelsus At least, it would be great if you can provide an option to switch between Bullet physics and Blender's built-in physics. Do you think that would be possible?

**Comment by zauberparacelsus** [comment]
I'm not a dev, so I don't know how much work would be involved.  At the very least though, doing so would mean borrowing code from blender, which is licensed GPL, so implementing the option would mean changing the licensing from zlib/libpng to GPL.

**Comment by luboslenco** [comment]
Physics engine in Armory is swappable but there would be licensing issues like mentioned.:/ If GPL is not an issue for you, then `softbody.c` would have to be ported first into a 'stand-alone' source file.
