### ISSUE TITLE
Detailed console log

### ISSUE THREAD

**Issue by Tymonrare** [armory3d/armory#852]
Hi. Right now i had pretty simple error that took too much time to fix it:
I've tested "playground" scene and after some manipulations (Resave i guess) i've lost script "SpawnBox" and project began to fail on build.

So issue isn't about loosing parts of project but about console log. All info i had was: `Type not found : arm.SpawnBox`. And clearly i had no idea what is "SpawnBox" and where to find it. I suggest to print whole information about error like:

```
{scene_name}: {object_name} ({context_type}, {property_name}) - {error_message}
```
because now it's impossible to find any error if you don't know project itself

**Comment by luboslenco** [comment]
Latest git armory will show more detailed info now, including scene name, object name, trait file. Thanks for suggestion!
