### ISSUE TITLE
Quat.fromTo() altering the input vector

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#853]
in `Quat.fromTo(v1, v2)`, this line: `var dot = v1.dot(v2)` will alter v1, which caused a bug for me before. Should it be `v1.clone().dot(v2)`?

Also I found the `v1.normalize()` and `v2.normalize()` are commented out, so I have to do it manually outside the function. May I know the reason?

**Comment by luboslenco** [comment]
Hm, `.dot` should not alter the vector, check here: https://github.com/armory3d/iron/blob/master/Sources/iron/math/Vec4.hx#L91. What is the code causing issues?

The reason for not auto-normalizing every time is to save some cpu cycles (when you already have normalized vector beforehand).

**Comment by MiloHX** [comment]
@luboslenco Ah sorry, maybe my memory got problem, yes there is no issue here, should be something else.
I understand why normalize() doesn't get included now, thanks.
