### ISSUE TITLE
Mesh does not export correctly - requires triangulation

### ISSUE THREAD

**Issue by donalffons** [armory3d/armory#855]
In Blender:
![image](https://user-images.githubusercontent.com/33040347/44833018-014b0680-ac2d-11e8-9d47-3786a64393d5.png)

In Armory:
![image](https://user-images.githubusercontent.com/33040347/44833045-1d4ea800-ac2d-11e8-8712-525aff89d3bc.png)

(using a triangulate modifier solves the issue)

[mirror-edge-bake.zip](https://github.com/armory3d/armory/files/2334802/mirror-edge-bake.zip)

**Comment by luboslenco** [comment]
The meshes are triangulated on export(so there is no need for additional processing during game init), this is likely some weird bug.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/1215.
