### ISSUE TITLE
Batch meshes + translucent/discard shadows broken

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#856]
I was thinking this issue was solved .. whereas i can't get transparent shadows working. Tranlucency is set to on, discard is checked in material. 
![transparent shadows](https://user-images.githubusercontent.com/7542691/44851209-d75f0780-ac5f-11e8-8aea-2f3544e74f5b.jpg)
[grass1.zip](https://github.com/armory3d/armory/files/2336107/grass1.zip)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Pushed some fixes at https://github.com/armory3d/iron/commit/b59c3f713878b4a7a905220e6fa217c797caeb64.
