### ISSUE TITLE
Rigid body issue

### ISSUE THREAD

**Issue by mistajuliax** [armory3d/armory#857]
Hi, i have an issue with my setup. To sum up the rig : There a ground, a grass strand, a character collider, a plant collider, a plant suspender and two empties. The grassis parented to a bone with an ik constraint target to the plant collider. The plant suspender is parented to an empty. This empty has a generic spring targeted to suspender and plant collider. The grass empty has a generic spring too targeted the ground and the plant collider. Suspender has rigid body passive, plant collider has rigid body active and animated and character collider has rigid body passive too. Here is the blend. Play in blender you will see what is expected. Play in krom nothing work ... I really don't if the issue caome from rigid body set as dynamic, or from rigid body spring constraint. As i ask here i am not aware of what work, and what doesn't at the moment. 
[grass_collision1.zip](https://github.com/armory3d/armory/files/2336320/grass_collision1.zip)
http://forums.armory3d.org/t/rigid-body-soft-body-cloth-etc-what-works-what-doesnt/1698 
*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/62.
