### ISSUE TITLE
Enabling lens flare and volumetric fog together causes the game fail to build.

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#858]
As captioned. 
Test File: [Lens_Flare.zip](https://github.com/armory3d/armory/files/2336557/Lens_Flare.zip)
![image](https://user-images.githubusercontent.com/17811339/44858128-e2d42200-aca3-11e8-9f54-2187544d2844.png)

**Comment by luboslenco** [comment]
Fixed, thanks! https://github.com/armory3d/armory/commit/8bb14e766a36a6fa2243858f402ee9dff8729c77

**Comment by mistajuliax** [comment]
@MiloHX How do you setup lens flare ?

**Comment by MiloHX** [comment]
@mistajuliax just enabled it, I don't see any setting:
![image](https://user-images.githubusercontent.com/17811339/45067153-6357b000-b0f4-11e8-8126-a4c0fcad1aea.png)

**Comment by mistajuliax** [comment]
Ok, i was thinking a lens texture was needed ...
