### ISSUE TITLE
[FEATURE REQUEST]: frame rate logger/benchmark

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#86]
I would like to be able to log the framerate history of my play testing session in Armory. I would like to be able to have these logs dumped out in a visual format (overwhelmingly likely to be a graph) in order to compare the data and use this as a tool for future testing and game development. I would also like the same visual format that the data is dumped out in, to include the minimum average and maximum framerate achieved during the time period that the log was running and I would like it to be well marked (Minimum: Average: Maximum: and then the number, all of this right below the graph for example). Thank you for your consideration on this request.

**Comment by luboslenco** [comment]
Linking this to *Better debug console* issue to keep it connected, will continue at https://github.com/armory3d/armory/issues/85.
