### ISSUE TITLE
The problem with exporting to html5 (v0.5)

### ISSUE THREAD

**Issue by kaiwas** [armory3d/armory#861]
When exporting to xml5, it displays errors and displays a black screen:

    Sampler gbufferD not found
    Uniform textSize not found

in the Krom scene is displayed well
https://youtu.be/tRNq112GB3Q

[219A.zip](https://github.com/armory3d/armory/files/2352147/219A.zip)

**Comment by luboslenco** [comment]
Thanks for report. Hm, Chrome on Windows seems ok. What OS/browser are you on? Will try to reproduce there and fix.

Any more errors messages? `Sampler/Uniform not found` itself should not cause black screen.

![1](https://user-images.githubusercontent.com/3685704/45085513-247c2700-b101-11e8-8122-8f974240ebb6.PNG)

**Comment by luboslenco** [comment]
Sorry I missed the video link, will check it out on Linux.

**Comment by kaiwas** [comment]
manjaro Linux
FireFox 61.0.2 (64-bit) & Chrome 67.0.3396.99  don`t work

**Comment by kaiwas** [comment]
output from console 
[bug-1.zip](https://github.com/armory3d/armory/files/2352248/bug-1.zip)

**Comment by kaiwas** [comment]
I'll take an opportunity to ask about the bump of procedural textures. is it possible? The pupil is interested in procedural brick in Armory)

**Comment by luboslenco** [comment]
Will give priority to further improve material nodes in 0.6. 🙂 (tag https://github.com/armory3d/armory/issues/284)

**Comment by kaiwas** [comment]
Thank you!!!

**Comment by kaiwas** [comment]
PS/ in the alpha version 0.5 everything worked fine

**Comment by luboslenco** [comment]
I tested on manjaro + firefox 61.0.2 (64bit) and it's ok here for some reason. Will try to test on another machine. Can you spot any errors in `firefox menu - web developer - browser console`?

![screenshot_2018-09-05_15-48-31](https://user-images.githubusercontent.com/3685704/45091528-06b7bd80-b113-11e8-9ba0-5a3fc64178bd.png)

**Comment by kaiwas** [comment]
```
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
kha.js:1:519092
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
kha.js:1:525863
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. kha.js:1:523469
[Показать/скрыть детали сообщения.] TypeError: Argument 6 is not valid for any of the 6-argument overloads of WebGL2RenderingContext.texImage2D. kha.js:1:519731
PipelineState.hx:92: Warning: Uniform texSize not found. kha.js:1:424525
PipelineState.hx:111: Warning: Sampler gbufferD not found.
```

Chrome - don`t work.

**Comment by kaiwas** [comment]
Checked on another system. Win7

Everything is working. I will look for the cause of the problem at home.

**Comment by kaiwas** [comment]
found the reason.
In the renderer settings, if the "deferred" button is active, it does not work.
If you put "forward" - it works
