### ISSUE TITLE
Krom missing dll on Windows 7

### ISSUE THREAD

**Issue by antomicek** [armory3d/armory#862]
Windows 7
-happens after I downloaded 0.5ver
-I tried reinstall MS VisualC++2015
![krom](https://user-images.githubusercontent.com/42112273/45144815-75eaeb80-b1bf-11e8-8f24-69bf27bd09ed.jpg)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Any luck with [Visual C++ Redistributable for Visual Studio 2017](https://go.microsoft.com/fwlink/?LinkId=746572)? Updating docs asap.

**Comment by antomicek** [comment]
Sorry..Still the same

**Comment by kaiwas** [comment]
the same problem arose. 
The reinstallation for VS2017 did not help. 
Requires a lot if you manually add one.

**Comment by luboslenco** [comment]
I updated the `Armory_05_win64` build on itch.io with a fix attempt, please let me know if you get to try it. At least the missing dll errors should be gone.

(Alternatively Krom binaries can also be downloaded from [github](https://github.com/armory3d/Krom_bin).)

**Comment by kaiwas** [comment]
Everything works fine. Thank you!

**Comment by luboslenco** [comment]
Wohoo!
