### ISSUE TITLE
Using tiff/tga throws error

### ISSUE THREAD

**Issue by gamergamesz** [armory3d/armory#863]
win10, 960m nvidia
![screenshot 84](https://user-images.githubusercontent.com/13883739/45173758-be89bf80-b226-11e8-92a0-884b725af6be.png)
![screenshot 85](https://user-images.githubusercontent.com/13883739/45173797-d3665300-b226-11e8-9b77-e8fbcf5905be.png)

**Comment by luboslenco** [comment]
Hm it works like usual for me, do you get this in all projects? Is b2.79 version ok?

**Comment by gamergamesz** [comment]
I get this even in new project, i haven't tried b27

**Comment by gamergamesz** [comment]
i want to correct my statement as this is happens when i  plug .tga or .tiff texture in principle bsdf. for the hdr i was using wrong dimension.
jpg and png works fine

**Comment by luboslenco** [comment]
Looks ok now.
