### ISSUE TITLE
Animation pb - when 2+ armatures in NLA

### ISSUE THREAD

**Issue by Didiercode** [armory3d/armory#865]
It seems that when we have 2 or more armatures (with an object parented to it) placed into the NLA , when playing we get an error similar as this one in the firefox browser (even if the animation with the Timeline is perfect) 

![image](https://user-images.githubusercontent.com/20455592/45219192-63011580-b2aa-11e8-988e-f2173b534521.png)

Deleting the Armature(s) (keeping only one) and things are ok.
Making more tests, it seems that it is the parenting of an object with the bone of the armature which creates the error during the play, but doing a weigth parenting with the armature bone is ok.

**Comment by luboslenco** [comment]
Continues at https://github.com/armory3d/armory/issues/972.
