### ISSUE TITLE
play action nodes

### ISSUE THREAD

**Issue by djgraphics** [armory3d/armory#866]
I have setup an animated cube and the play action node is not working. I am unsure if this is because there is a bug or if something else is required. I have two actions setup and saved as a fake user.

![node](https://user-images.githubusercontent.com/9562016/45249917-95d0fb00-b2f6-11e8-8181-e8802fd653b3.jpg)

*(drag & drop zipped .blend file here)*

**Comment by luboslenco** [comment]
Everything looks ok from the picture, it's likely a bug but would need to inspect the file.
