### ISSUE TITLE
Cannot Get transparency to work!

### ISSUE THREAD

**Issue by JeannotLandry** [armory3d/armory#87]
Here is a screenshot (using the latest version and running the provided blender). It looks great however, the transparency doesn't work for me, not too sure why. I did try many many things, but I just can't get it to work. I get either no transparency at all (solid leaf with white around) or this see through leaf.
![armoryr4_transparencynotworking](https://cloud.githubusercontent.com/assets/14031486/21060183/83e4c190-be1c-11e6-9dcf-f133cb9bc274.jpg)

and here is the .blend
[test.zip](https://github.com/armory3d/armory/files/642893/test.zip)

**Comment by luboslenco** [comment]
Attached blend should now finally run as expected!
