### ISSUE TITLE
copy location delay issue

### ISSUE THREAD

**Issue by MiloHX** [armory3d/armory#872]
Keep a record for a discord question. Not sure if it is a bug or a limitation:

Rigid body object A, and I am using script  `setLinearVelocity `to move it around
normal object B, I am trying to make it copy location of object A by script
I have put it to `lateUpdate()` but I still got delay
![delay](https://user-images.githubusercontent.com/17811339/45437624-bd093d00-b6e7-11e8-99c9-3d06aa760438.gif)
you can see the ball (object B) is wobbling inside the cube (object A)
Test File: 
[Copy_Location.zip](https://github.com/armory3d/armory/files/2376113/Copy_Location.zip)

/Milo

**Comment by MiloHX** [comment]
Test file is updated to uncheck the "force deactivation" on the rigidbody

**Comment by KosLooney** [comment]
Iron updates traits without a set priority at the moment. It syncs fine when spawning the icosphere after the start of the scene.

File with spawned icosphere:
[Copy_Location.zip](https://github.com/armory3d/armory/files/2376431/Copy_Location.zip)

**Comment by MiloHX** [comment]
@KosLooney Thansk! It works. Hopefully there will be a official way to do it soon.

**Comment by MiloHX** [comment]
@KosLooney @luboslenco Hey I found an alternative (better?) solution, that is don't put `notifyOnLateUpdate()` in `new()`, but put it inside the function added to `notifyOnInit()`, so that the physic update has chance to be added to the queue before the copy location:
```
	public function new() {
		super();
		notifyOnInit(init);
	}

	public function init() {
		obj = Scene.active.getChild("Cube");
		rb  = obj.getTrait(RigidBody);
		notifyOnLateUpdate(function() {
			object.transform.loc.setFrom(rb.transform.loc);
			object.transform.buildMatrix();
		});
	}
```
[Copy_Location_ALT.zip](https://github.com/armory3d/armory/files/2377921/Copy_Location_ALT.zip)

**Comment by luboslenco** [comment]
Thanks for the file! Should be fixed, `lateUpdate` is guaranteed to be called after physics update now. https://github.com/armory3d/armory/commit/78906238b59c0f1578818a4932f96c6519013a49
