### ISSUE TITLE
Compiling Armory as a Python module

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#875]
I am currently using Blender as a Python module in my work. For most of the project that I'm working on I do not need to see the results visually.  All I need is to have access to Blender and Armory Python API to setup my scene/nodes etc. So I wonder if it is possible to compile the Blender equipped with Armory as a Python module as well?

**Comment by Amir-Arsalan** [comment]
@luboslenco  I'm not entirely sure, but does installing Armory as a addon would still provide all the functionalities that I am looking for? Here's what I want: I want to write a game entirely using Blender's Python API and use the functionalities that the Armory's Python API provides to create logic nodes etc. Then I want to compile this game and run it on the web. I don't need to see anything visually until after the compilation.

**Comment by luboslenco** [comment]
Armory-as-an-addon has everything apart from the built-in viewport player, that is the only difference.

**Comment by Amir-Arsalan** [comment]
@luboslenco That's heart-warming :smile:
