### ISSUE TITLE
How to get the vector of its own axis in armory？

### ISSUE THREAD

**Issue by haizhou37** [armory3d/armory#876]
I want to implement the ability to apply force according to the object's own axis vector direction, but armory does not seem to provide this node. Is there any other method that can be implemented in the node editor?
我想实现根据物体自身坐标系方向施加力的效果，可是armory中找不到获取自身坐标系向量的这个节点。那么有其它办法实现这个效果吗，要在节点编辑器中实现

**Comment by luboslenco** [comment]
Is `Vector From Transform` node what you are looking for? Example can be found in the tanks tutorial.
- https://armory3d.org/manual/#/getting_started/tanks
- https://github.com/armory3d/armory_tutorials/tree/master/tanks

Please let me know if you have something different in mind.
