### ISSUE TITLE
How to compile an Armory game after installing the Armory addon?

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#878]
I downloaded Blender 2.79b in a freshly-installed Ubuntu 16.04 and followed the instructions given [here](https://armory3d.org/manual/#/getting_started/setup?id=using-armory-as-add-on) to install the Armory addon in Blender. When I click on _Play_
I get the following errors:

![image](https://user-images.githubusercontent.com/6061721/45599760-7d7c7280-b9bf-11e8-9238-b0fde29ad95f.png)

My guess is that Armory is looking for some dependencies to be able to compile the game but I don't know what those dependencies are (sorry I'm pretty new to Armory). Can someone (especially @luboslenco) tell me what I need to do to be able to compile my games? Note that in the future, I am going to compile my games in the background (I won't be able to use a GUI on our servers). So it would be great if you can take that into consideration when responding.

**Comment by sh-dave** [comment]
If you install it via addon, you need to clone the [full armory sdk](https://github.com/armory3d/armsdk) and set the path via user preferences.

**Comment by Amir-Arsalan** [comment]
@sh-dave Thank you so much! What do you mean by setting the path via user preferences? Setting what path?

**Comment by luboslenco** [comment]
There are two ways to obtain the SDK:
- [Downloading Armory build from itch.io](https://armory3d.org/manual/#/getting_started/setup?id=using-armory-as-add-on)
- [Cloning form GitHub](https://armory3d.org/manual/#/dev/gitversion?id=manual-clone)

Afterwards the `armory.py` add-on is installed and pointed to the `armsdk` directory in the user preferences, like Dave shows above. In your screenshot it looks like the sdk path is not pointed to that?

To set the path via python instead: https://github.com/armory3d/armory/issues/879
