### ISSUE TITLE
python script issue

### ISSUE THREAD

**Issue by RedFrostGames** [armory3d/armory#88]
I'm using the rotate.py script that comes with scene1.blend. I get the following error:
![capture](https://cloud.githubusercontent.com/assets/23486940/21081491/20656f36-bf96-11e6-8a2e-0e02cddc7388.PNG)

**Comment by luboslenco** [comment]
Fixed in https://github.com/armory3d/armory/commit/15fe673b48ea59a8792c84e19cff09e827b621fb, will be up in next build. Error I got was worded a bit differently, will do more testing and wait till new build is out(next week) to be sure.
