### ISSUE TITLE
SoftBody.hx does not use more than 1 thread

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#881]
After increasing the solver iterations to a fairly high number in`Sources/armory/trait/physics/bullet/SoftBody.hx`, the simulation slows down considerably. I noticed that the physics simulator does not use multi-threading and everything is running on a single thread. I thought I should let you know about this, just in case you would like to work on this. I think even using 2 threads would greatly improve the simulation speeds

**Comment by luboslenco** [comment]
I am not sure if bullet 2.x allows this in a feasible way. Probably better to keep focus on the core stuff for now.
