### ISSUE TITLE
Soft body physics simulation solver never stops calculating

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#883]
I just made an Armory game in which I do some simple soft body physics simulation. I noticed that even after everything is still in the scene the CPU is still doing calculations. I wonder, how can I stop the physics when things are not moving/interacting that much anymore?

**Comment by luboslenco** [comment]
To manually stop the physics update: `PhysicsWorld.active.timeScale = 0.0;`
To resume: `PhysicsWorld.active.timeScale = 1.0;`
Otherwise bullet should eventually put the body into sleep.
