### ISSUE TITLE
build error for c++-projects (missing libs)

### ISSUE THREAD

**Issue by Nos-** [armory3d/armory#887]
Hi,
I tried Armory 0.5 on fresh installed (and fully updated) Ferdora 28 Linux ans Debian "stretch" Linux.
If I want to build my project in Blender (the bundled version 2.79 ans 2.8 which comes with armory) I got an compilation error with c++ (with Krom or Webbrowser it works fine).

Solution: There were missing libs which are required. Under Fedora this are:
* libXinerama-devel
* alsa-lib-devel
* libstdc++ and libstdc++-devel

**Comment by luboslenco** [comment]
There is also a mention at the https://armory3d.org/manual/#/platforms/linux?id=native-c, still not that obvious though. 🙈
