### ISSUE TITLE
Armory2D Textboxes Cannot Be Typed In on Linux

### ISSUE THREAD

**Issue by Nos-** [armory3d/armory#888]
I tried the basic [[https://armory3d.org/manual/#/getting_started/playground Playground]]-tutorial but I can't edit Textinputfields (e.g.  the text for textelements or the value of their width). Keypress seems to be ignored except for space and backspace.
I tried it several times on two computers (Debian "stretch" and Fedora 28, both fully updated) with the current Armory-versions (version 0.5 with the bundled Blender 2.79 and 2.8).

**Comment by bflanagin** [comment]
I can confirm the bug is affecting Ubuntu 18.04 distributions as well.

**Comment by dukejib** [comment]
Yes, unable to change the text value of any control in Ubuntu 18.04

**Comment by zicklag** [comment]
I have this issue on Ubuntu 16.04. I had opened in issue in the Armory2D repo, but it seems to be an issue with Zui.

**Comment by luboslenco** [comment]
Fix incoming at https://github.com/Kode/Kore/pull/325.
