### ISSUE TITLE
Voxel AO is too slow

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#890]
Ge Force 960 Win 7 

The rendering is set to 
- FXAA
- Filmic tone mapping
- Voxel AO with low settings ( 3 cones, 128 res, 0.25 z) 

The third person template in a 1080 window , it's too much slow.

While the fps template , same settings Voxel AO, deactivating  bloom and  motion blurr, it runs smoothly.
Or the toon shading template with grass runs fine in 1080p.

IS there some issues with the third person template or it is Voxel AO ?

**Comment by luboslenco** [comment]
twin_stick template is better configured, but voxels are still heavy. There will be option to use probes in 0.6.
