### ISSUE TITLE
Linux case-sensitive keys, keys getting stuck

### ISSUE THREAD

**Issue by piokud84** [armory3d/armory#891]
Hi

I have created simple node setup to spin objects around given axis.
a to spin left
d to spin right
keyboard node is case sensitive so it does not work with Caps Lock on.
I can spin objects again by holding Shift + a or d, problem appears when 
I release Shift first and direction key after, then objects keep spinning
until i press Shift + direction and release them in reversed order.

[update]

first person template with no Caps Lock can lock
movement direction in case when you hold w + Shift, 
release w, release  shift...

[update 2]

Everything works well on Windows 10 Pro, no case sensitivity,
no key locks...

OS: Linux Ubuntu 18.04 64bit
Software: stock Armory3D v05_b28
Runtime: Krom
RenderPath: Low
CPU: Intel i5-4690S
GPU: iGPU Intel HD 4600
[003.blend.zip](https://github.com/armory3d/armory/files/2407912/003.blend.zip)

**Comment by luboslenco** [comment]
Hey, should be finally good now. Patch at https://github.com/Kode/Kore/pull/366.
