### ISSUE TITLE
Why it is not easy to get soft body physics to work?

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#894]
I am trying to build a very simple scene with an sphere and a flat surface. However, it looks like it is not straight-forward to get the soft body physics to work even for such a simple scene. From what I have noticed, it is not easy to use small shapes when doing soft body simulation. For instance, if I scale the sphere or cubes in the attached .blend files 5 times then the simulation starts working. Otherwise the sphere or the cube behaves very weirdly, even if the soft body solver iteration is set to a high number. Is that an Armory bug/limitation or am I doing something wrong? 

Irrelevant to the physics stuff, the shadows of objects in the scene are wrong. Why is that?

[softbody.zip](https://github.com/armory3d/armory/files/2409098/softbody.zip)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/874.
