### ISSUE TITLE
Clone object doesn't duplicate child objects

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#899]
In twin stick shooter, select Player object and try duplicate it with "Shift" "D"
Only the first child object  is duplicated all others are not duplicated (armature and camera).

**Comment by luboslenco** [comment]
Please post Armory specific issues only, this is related to Blender itself.
See https://blender.stackexchange.com/questions/27715/what-is-the-quickest-best-way-of-duplicating-an-object-with-children-so-that
