### ISSUE TITLE
Triplanar Mapping Unsupported

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#90]
Triplanar Mapping, a way to blend a texture onto a 3D surface, is unsupported in Armory.

It is supported in blender through the Image Texture node, where you change "Flat" to "Box", and then set a blend value.

**Comment by marcclintdion** [comment]
Just a thought.  I wonder if Twitter would make a good feature request site...  Someone could start a #boxMapping keyword then others can "follow"  it.  
The number of followers of a particular hashtag would give a good indication of features to prioritize since that would act as a vote.  Now feature requests wouldn't become so easily buried in a random hard to find web-page unless everyone dropped the issue.

**Comment by zauberparacelsus** [comment]
@marcclintdion That's going off-topic.  It'd be better to post something like that to a separate issue report or to the armory forums.

**Comment by SolarLune** [comment]
Also, GitHub has categories that could be added, to my knowledge, for each issue (so you can filter to just Feature Requests). You can also check the number of subscribers or participants to understand how desirable a feature request is.

That being said, I wouldn't even worry about it for awhile - the engine doesn't seem stable enough to have new features be added. Stability and flexibility would probably be the first thing to focus on at the moment.

**Comment by luboslenco** [comment]
Labels solution like suggested by SolarLune will hopefully do for now, just click on the `feature request` label and it will filter everything out.

**Comment by marcclintdion** [comment]
I was actually hoping to filter them out.  :)

**Comment by SolarLune** [comment]
You can put a dash before the "label" text in the search box. 

An easy way to filter out Feature Requests would be to hit a Feature Request label to search for them, then type a - before "label" and search for that. Not as nicely usable, but there's also not a lot of issues.

[Here's a read-up on GitHub's search abilities.](https://help.github.com/articles/searching-issues/)

**Comment by zauberparacelsus** [comment]
Giving this a little bump.  Triplanar/Box texture mapping will be essential for adding smooth terrain to the voxel world module.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/armory/issues/1292.
