### ISSUE TITLE
Navmesh can't bake multiple objects

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#900]
Open "twin stick shooter", select floor and click on "generate navmesh"

It will generate a navmesh for the floor only, it doesn't take account other static objects.

Should Armory get some "static" tag for objects, to get navmesh know what should be static objects to bake navmesh ?

**Comment by luboslenco** [comment]
Add desired navmesh objects to a separate layer, then select all and click `Generate Navmesh`.
