### ISSUE TITLE
Multiple nodes per object

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#901]
We can only select one node visual scripting for one object.

Able to select multiple nodes for the object can have advantages.

For example share the same node for multiple objects, while each object could have some more specific nodes.

**Comment by luboslenco** [comment]
You can attach multiple logic node trees per object in the `Armory Traits` panel.

Go through the tutorial first - creating logic node tree:
https://armory3d.org/manual/#/getting_started/playground?id=logic-nodes

Tanks game uses multiple logic node trees per object:
https://armory3d.org/manual/#/getting_started/tanks
