### ISSUE TITLE
Soft Body issue: why simple shapes fly away?

### ISSUE THREAD

**Issue by Amir-Arsalan** [armory3d/armory#902]
I've had this issue for a while and haven't been able to resolve it. The only way that this gets resolved partially is by increasing the mass of the object to an unrealistically high number (more than 15kg for instance). Or I have to make the shape more complex which is undesirable for my settings as the soft body physics in Armory is pretty unreliable as of now. Here's a gif showing that happens:

![aa](https://user-images.githubusercontent.com/6061721/46163665-c81cab00-c259-11e8-8eb3-aad0932dd922.gif)

Why is that? How can I resolve this?

[objectFly.blend.zip](https://github.com/armory3d/armory/files/2425205/objectFly.blend.zip)

**Comment by luboslenco** [comment]
> Why is that?

The soft body physics simply need more work / contributions. There is no other solution to that, someone has to invest time into it. 🙂 

Linking to the existing forum topic at http://forums.armory3d.org/t/soft-body-issue-why-simple-shapes-fly-away/1832.

**Comment by sh-dave** [comment]
Just something i stumbled upon some time ago, not sure what status it is in or usable at all: https://github.com/michaelapfelbeck/jellyPhysics

**Comment by DevMagicLord** [comment]
It works.
You need to "smooth faces" to get soft body work.

[http://forums.armory3d.org/t/tutorial-soft-body-and-cloth-physics-working/2201](url)

**Comment by Amir-Arsalan** [comment]
@DevMagicLord I have done that already. This does not resolve the issues.
