### ISSUE TITLE
colorramp problem b0.5 2.8

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#905]
These two colorramps should be the same, but one of them is glitching out.
![b1](https://user-images.githubusercontent.com/30187223/46242046-b6efad80-c3c3-11e8-9961-12b0e9c7112a.PNG)
![b2](https://user-images.githubusercontent.com/30187223/46242049-bc4cf800-c3c3-11e8-8dcf-03e480a68d21.PNG)

[colorramp.zip](https://github.com/armory3d/armory/files/2430352/colorramp.zip)

**Comment by AFWSI** [comment]
Might be the second one causing it.

@luboslenco 
I also discovered a issue with the color ramp. The node setup in this thread on my reply works in 0.4 ,but not 0.5b.

http://forums.armory3d.org/t/black-texture-error/1779/7

In version 0.4 it gives color ,but version 0.5 it just shows up as white and black.

**Comment by Simonrazer** [comment]
@AFWSI no it is not, it is still broken with the second one removed
