### ISSUE TITLE
Adding Vec4 to transform.loc: 2 +2 = "22" 

### ISSUE THREAD

**Issue by jesuCarrasco** [armory3d/armory#907]
If a iron.math.Vec4 type is defined and added a new Vec4 works as expected
```
var testVec:Vec4 = new Vec4(2, 0, 0, 1);
testVec.add(new Vec4(2, 0, 0, 0));
trace(testVec);
```
results:
> (4, 0, 0, 1)

If the same thing applied to a transform.loc, treats values as string (even though 'loc' is a Vec4 type) 
```
object.transform.loc.add(new Vec4(2, 0, 0, 0));
trace(object.transform.loc);
```
results:

> (22, 0, 0, 1)

Strangely, substraction works as expected

**Comment by jesuCarrasco** [comment]
Tried to fix the iron.math.Vec4 lerp function code with a 
```

inline public function lerp(from:Vec4, to:Vec4, s:FastFloat):Vec4 {
	x = Std.parseFloat(from.x + (to.x - from.x) * s);
	y = Std.parseFloat(from.y + (to.y - from.y) * s);
	z = Std.parseFloat(from.z + (to.z - from.z) * s);
	return this;
}

```
And got:

> Armory\armsdk\iron\Sources/iron/math/Vec4.hx:114: characters 22-50 : Float should be String

String ???

**Comment by jesuCarrasco** [comment]
Ok. Found the issue.
If the values are initialized from a parsed Json, all values are treated as string

**Comment by sh-dave** [comment]
Json has a `number` type, so i guess your files are wrong? Use `{ "x": 42 }` instead of `{ "x": "42" }` to make `x` a number instead of a string.
