### ISSUE TITLE
Array and Bool node color

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#909]
Array and Bool node color are similar and would be good if they can be easily differentiate.
For example: bool -> yellow, Array -> orange or pink or whatever.

**Comment by AFWSI** [comment]
Actually you can change this fairly easy. Looks like several inputs uses blender's default node socket colors ,but array has a custom color.


Change line 48 from
`
return (0.8, 0.8, 0.3, 1)
`


to this, to change it to a orange color
`
return (0.8, 0.4, 0.0, 1)
`


This is the file
https://github.com/armory3d/armory/blob/master/blender/arm/logicnode/arm_nodes.py#L48

**Comment by BlackGoku36** [comment]
I know you can do it, i am saying to so colour settings are applied to official build so, other users don't have to do that

**Comment by luboslenco** [comment]
If you have a spare minute you can create a pull request, happy to apply it. 🙂

**Comment by luboslenco** [comment]
Fixed via https://github.com/armory3d/armory/pull/914.
