### ISSUE TITLE
Threaded Compile

### ISSUE THREAD

**Issue by zauberparacelsus** [armory3d/armory#91]
I noticed that during the build process when I do Play in Viewport, only one CPU core is used.  Would it be possible to make the build process threaded?  That would allow it to build larger projects much faster.

Caching or re-using the compiled binaries for unchanged files may also provide a speed boost for the build process.

**Comment by luboslenco** [comment]
Armory 0.5 has a new `Khamake Threads` option in add-on preferences. Speeds up the asset export and shader compiling considerably - will enable by default in 0.6.
