### ISSUE TITLE
Instanciated objects invisible when Scene.active.spawnObject called

### ISSUE THREAD

**Issue by FuriouZz** [armory3d/armory#910]
I got a problem with Scene.active.spawnObject. Objects seem to be instanced but they do not appear. When I enable the debug and select them, they appear. 

https://imgur.com/a/Hfdyu7p

[infinity-armory.zip](https://github.com/armory3d/armory/files/2431872/infinity-armory.zip)

Armory 0.5
Blender 2.79b

**Comment by FuriouZz** [comment]
I fixed the problem when I toggled `Instanced children` from `Off` to `Loc` then `Off`.

I made another test with every `Instanced children` options. When I set `Loc + Scale` or `Loc + Rot + Scale`, the spaceship disappear.

**Comment by luboslenco** [comment]
Hm maybe this got fixed, spaceship no longer disappears here.
