### ISSUE TITLE
Displacement connection causes undefined identifier use

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#911]
With tessellation 
```
ERROR: ice_mesh.tese.glsl:66: 'n' : undeclared identifier
ERROR: ice_mesh.tese.glsl:66: '=' :  cannot convert from ' temp float' to ' temp 3-component vector of float'
ERROR: ice_mesh.tese.glsl:66: '' : compilation terminated
``` 

With Vertex displacement

```
ERROR: ice_mesh.vert.glsl:46: 'n' : undeclared identifier
ERROR: ice_mesh.vert.glsl:46: '=' :  cannot convert from ' temp float' to ' temp 3-component vector of float'
ERROR: ice_mesh.vert.glsl:46: '' : compilation terminated
```

It tries to assign a variable to `n` but `n` isn't declared at all. Both for tessellation and vertex 

[ice.zip](https://github.com/armory3d/armory/files/2432173/ice.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/9122dcc6e1231f68d7ae749ff9726181dcb9da46. There is a missing normal map image but after filling that it seems to run.
