### ISSUE TITLE
Linux Armory_05_linux64_b28 runs only with terminal

### ISSUE THREAD

**Issue by AndreaMonzini** [armory3d/armory#912]
Hello,
no big deal for me ( i usually run Armory from terminal ) but i cannot run Armory_05_linux64_b28 ( Armor5_05_B)  with double click as application. 
Using `./blender` from terminal it works.
Elementary Os 5.0 Ryzen 1700, Rx 580 Mesa drivers.

![screenshot from 2018-10-01 15-02-09](https://user-images.githubusercontent.com/12413409/46290081-21067f00-c58b-11e8-9bb7-02bf87efaa8d.png)

**Comment by bflanagin** [comment]
This might be an elementary OS or gnome issue. There was talk about removing the ability to launch binary files from the file browser. However if you edit the blender.desktop file to point to the blender within the armory directory you can launch it from there. That's how I solved the issue in Pop!_OS

**Comment by AttSee** [comment]
open terminal  ---> armory  path  
 ./blender

**Comment by AndreaMonzini** [comment]
Thank you for the suggestions, but it doesn't work.
I tried to modify the .desktop file or change the permissions.
I can open Armory 0.5 Blender 2.7 in the same system with double click:  

![screenshot from 2018-11-16 18-42-24](https://user-images.githubusercontent.com/12413409/48637999-a1643080-e9cf-11e8-985f-7b8a438ef1a8.png)

**Comment by AttSee** [comment]
edit the armory.desktop


open terminal ---> armory path

run

`sudo chmod +x blender`

`cd ~/.local/share/applications/`

 sudo vim Armory.desktop`


[Desktop Entry]
Encoding=UTF-8
Version=0.5
Name=Armory
Comment=Create different games
Exec=/home/attia/Progarm/Armory/blender     ! # this is my  armory path  Changed to your path
Icon=/home/attia/Progarm/Armory/Logo.png    !# this is my  armory path  Changed to your path 
Terminal=false
Type=Application
Categories=Development; Games;
Name[en_US]=Armory
GenericName[en_US]=Game development platform
Comment[en_US]=Create different games!


to save 
:wq

this icon  :) 
![logo](https://user-images.githubusercontent.com/22094152/48666407-e10f4300-eac9-11e8-8846-a84afe8cd146.png)

put in armory path 
![2018-11-18-003811_1366x768_scrot](https://user-images.githubusercontent.com/22094152/48666422-49f6bb00-eaca-11e8-8f55-69db3707a402.png)

**Comment by AttSee** [comment]
@luboslenco  we need   terminal to trace errors like windows

**Comment by AttSee** [comment]
@luboslenco  put in doc

**Comment by AndreaMonzini** [comment]
Thank you @AttSee but i follow all passages and stil does not work.
`blender` is still a x-sharedlib.

**Comment by AttSee** [comment]
should  work  i use lubuntu 

@AndreaMonzini  Try again 

I modified the script.
Don't put comments

and install
`sudo apt-get install libglu1`

**Comment by AttSee** [comment]
this is blender-2.80  not  Armory is  work  
![2018-11-18-012213_1366x768_scrot](https://user-images.githubusercontent.com/22094152/48666747-6a297880-ead0-11e8-9b07-9a95d456591f.png)

**Comment by AndreaMonzini** [comment]
Blender 2.8 works for me too.
For this reason it could be an issue with compiler for some distro.

**Comment by luboslenco** [comment]
Should be non-issue now in 0.6 (using standard Blender).
