### ISSUE TITLE
Emission broken

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#913]
I noticed that in both forward and deferred shading on Intel CPU/GPU systems it requires a light source to shine. So if you have your world lighting set to black and then no lights and an emission shader you will not see it. Here's an example:
![screenshot from 2018-10-01 16-29-09](https://user-images.githubusercontent.com/25536957/46319992-83ff1280-c599-11e8-8ca2-117ba1e88d16.png)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/521.
