### ISSUE TITLE
Using .png as world background in b28 - Image.save_render api change

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#916]
I found a bug. If you use a .png image file as the world shader background texture it will give you lots of errors and fail to compile. .hdr and .jpg both work as expected.

![armory env map error](https://user-images.githubusercontent.com/25536957/46380738-ac057900-c660-11e8-9fc5-b29e2e4dbf13.png)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/f78878cd89284159e278d70eb2b49ac6be0fff45.
