### ISSUE TITLE
Reflections completely broken in forward rendering

### ISSUE THREAD

**Issue by TriVoxel** [armory3d/armory#917]
In forward rendering, neither the world background nor SSR effect reflections whatsoever. Leaves everything looking diffuse. See [my .blend file](https://playlso.page.link/git) for an example.

**Comment by luboslenco** [comment]
It's a bug, will be fixed in 0.6. Armory is designed to be render-path independent.

**Comment by luboslenco** [comment]
Should be a bit less completely broken now, ssr can be enabled for forward path. https://github.com/armory3d/armory/commit/68b5e1bb3ba377726d1ac6efb728ef572d85b929
