### ISSUE TITLE
bring consistency to Armory version numbers

### ISSUE THREAD

**Issue by killarny** [armory3d/armory#918]
Armory seems to report it's version differently depending on which version display you look at in the Blender UI. 

In my case, looking at the Armory version in the Addons panel in User Prefs shows version `15.0.0`: 

![image](https://user-images.githubusercontent.com/29001/46434532-de2adf80-c721-11e8-84de-ea5fec54120b.png)

However, looking under Render -> Armory Project and then scrolling all the way to the bottom of that panel, it shows `Armory v0.6`:

![image](https://user-images.githubusercontent.com/29001/46434579-03b7e900-c722-11e8-8d25-c54ed59f80c3.png)

It isn't clear why these two numbers are different, or which one I should be paying attention to if I haven't checked the releases page in a while.

Making it even more confusing, I checked the releases listing here on github, trying to make some sense of the version numbers listed in Blender. The github releases show `0.5a` as the latest (along with another version tag of `18.09a`; I'm not sure how/if that is even related):

![image](https://user-images.githubusercontent.com/29001/46434512-cce1d300-c721-11e8-8e66-33230a48b084.png)

Next, I checked the website and followed the download links over to an itch.io listing that shows yet another version number:

![image](https://user-images.githubusercontent.com/29001/46434687-52fe1980-c722-11e8-8ab5-40ba924e526f.png)

Presumably, the github release for 0.5b wasn't tagged, and that's why it doesn't show up on the releases page there.

---

Anyhow, I'm sure there is a good reason for why some of these version numbers are following different numbering schemes, but it's a bit confusing. Especially so when even in Blender itself the Armory version is reported inconsistently as either version `15.0.0` or `0.6` depending on where one looks.

**Comment by luboslenco** [comment]
`v0.6` - Armory Updater was likely used which jumps to dev version.

`15.0.0` shown in add-on preferences - this is probably causing the main confusion.:/ It's something like 'startup script' version - will get rid of that. (It's due to`armory.py` add-on being a separate thing which lets one install Armory into standard Blender,)

**Comment by luboslenco** [comment]
Upcoming build will now also show v0.6 in add-on preferences.
