### ISSUE TITLE
hide "Install Git" button if git already installed

### ISSUE THREAD

**Issue by killarny** [armory3d/armory#919]
The addon preferences panel shows the "Install Git" button all the time. Hiding this button when git is already installed would make this panel more intuitive.

![image](https://user-images.githubusercontent.com/29001/46435407-47abed80-c724-11e8-9337-45fc060a9216.png)

**Comment by slapin** [comment]
Also I think this button should either be removed on Linux or should provide instruction for user to install git from their distro tools.

**Comment by luboslenco** [comment]
`Help` button will be displayed now instead, pointing to the manual. https://github.com/armory3d/armory/commit/f6eefcca9f90294a5529f5291ac3a3b6f2f71a31
