### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by breebee** [armory3d/armory#92]
I just downloaded the windows 64 bit and linux 64 bit zip files and for windows it just hangs ith black screen no error. On ubuntu yaketty 16 i run into a couple situations. For the blender within the zip file it wont start so when i throw the blender application into the terminal i receive " error while loading shared libraries: libboost_locale.so.1.58.0: cannot open shared object file: No such file or directory " 

Also when i run a fresh download of blender 2.78a and install the addon and link the SDK i try to click run at the bottom but then i am confronted with 

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
AL lib: (WW) ALCjackBackendFactory_init: jack_client_open() failed, 0x11
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
addon_utils.disable: armory not disabled.
Modules Installed from '/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory.py' into '/root/.config/blender/2.78/scripts/addons' (armory)
/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/nodes_renderpath.py:892: UserWarning: load: '/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/data/data.blend' does not contain node_groups["deferred_path_high"]
  data_to.node_groups = data_refs
trying to save userpref at /root/.config/blender/2.78/config/userpref.blend ok
trying to save userpref at /root/.config/blender/2.78/config/userpref.blend ok
trying to save userpref at /root/.config/blender/2.78/config/userpref.blend ok
Info: Total files 1 | Changed 1 | Failed 0
/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/nodes_renderpath.py:871: UserWarning: load: '/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/data/data.blend' does not contain node_groups["deferred_path_high"]
  data_to.node_groups = data_refs
Traceback (most recent call last):
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/props_ui.py", line 431, in execute
    nodes_renderpath.check_default()
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/nodes_renderpath.py", line 854, in check_default
    make_renderer.make_renderer(bpy.data.cameras[0])
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/make_renderer.py", line 20, in make_renderer
    nodes_renderpath.load_library('deferred_path_high', 'armory_default')
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory/armsdk/armory/blender/nodes_renderpath.py", line 874, in load_library
    ref.use_fake_user = True
AttributeError: 'NoneType' object has no attribute 'use_fake_user'

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by luboslenco** [comment]
Heyo,

- Which version of Windows & GPU do you run?
- Can you paste command line output after the black screen appears?
- In Properties - Render panel - Armory Play, does it work if you select 'Browser' runtime and hit play?
- Selecting camera and going into Properties - Camera data - Armory Props, does it work if you select 'forward_low' render path?

On Linux, it is unable to import node groups from 'Armory_preview/armsdk/armory/blender/data/data.blend' file for some reason.
- Could anything block this? Is that file present? Any add-on that could interfere with this?

Will then also investigate shared libraries issues (likely has to be installed manually but want to prevent that).

Thanks for report!

**Comment by breebee** [comment]
Using windows 10  920m nvidia for a laptop i throw blender into the cmd and after pressing run i see all the assets export and all the shaders compile right after which it says 

Done.
Image brdf.png
Image noise8.png
Uniform envmapStrength not found.

For Linux desktop running nvidia 970gtx I do not know of what could block this, all the files are present in the log (data.blend, props ui,node rendepath , make renderpth). I dont think any addon would conflict because I used a fresh install, and the provided install in your zip, and i uninstalled everything and tried again from the zips.

**Comment by luboslenco** [comment]
No trouble with HW power then.

For Windows, did you still get black screen after changing to 'forward_low' path? (then we know wether it's not working at all or it has troubles with some features)
Does it run in Browser and Krom runtimes from Armory Play panel? Is the black screen even for default cube scene?

For Linux - can you paste your SDK path setting? Is there '/' at the end? I fixed this only recently, was causing issues in some cases, maybe it's at fault here?
<img width="615" alt="pref" src="https://cloud.githubusercontent.com/assets/3685704/21246795/37e0e5e4-c32b-11e6-9457-c3a9794ec1d7.png">

If this is not the case - when you select File - Append - *Armory/armsdk/armory/blender/data/data.blend/NodeTree/* in Blender, can you spot 'deferred_path_high' in your setup?
<img width="172" alt="nodes" src="https://cloud.githubusercontent.com/assets/3685704/21246905/d326587c-c32b-11e6-989f-a8ad64f0965c.png">

**Comment by breebee** [comment]
When i select File - Append - Armory/armsdk/armory/blender/data/data.blend/NodeTree/ I do see forward path and all the node trees. It seems blender is not allowing me to add the / at the end of the sdk file path this must be the issue. No matter what i try the path always removes the last /

For windows it does work with default cube scene switching to browser

Will there be another release with this sdk path fix soon?

**Comment by luboslenco** [comment]
Yeah, packaging new build this week (and then focusing on fixes for the rest of the year).

About running the packaged Blender build on Linux and " error while loading shared libraries: libboost_locale.so", would you mind doing `apt-get install libboost-all-dev` to see if that moves it further?

For Windows, can you paste these lines into python console in Blender and check the output?
`import bgl`
`bgl.glGetString(bgl.GL_SHADING_LANGUAGE_VERSION)`

Several people now reported problems with built-in player on Windows, so definitely have some work to do there.

**Comment by breebee** [comment]
So for linux i tried to install liboost-all-dev to no success as well as other dependencies I found other people installing online after that didnt work, and now i just compiled a newer library from source version 1.63 to see if that would help but i assume its not working because the original library is still being linked i guess. I will test the windows version tomorrow when i have access to the computer and see what the shading language version results from the python terminal. If theres anything else i can do let me know I am glad to help debug the situation and finally test out the engine.

**Comment by breebee** [comment]
On windows i press run script and receive bpy.ops.text.run_sript() with nothing. I now realize even if the laptop has cuda installed its not being recognized from belnder for gpu rendering which might be the situation.

On linux i figured out the shared libraries issue, it seems the newer version of ubuntu 16.10 yakkety does not keep its boost libraries in /usr/lib/ so i just manually copied the files from the compiled verion of 1.63 and the zipped blender version of your zip file now boots with 


Traceback (most recent call last):
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory//armsdk//armory/blender/props_ui.py", line 450, in execute
    nodes_renderpath.check_default()
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory//armsdk//armory/blender/nodes_renderpath.py", line 854, in check_default
    make_renderer.make_renderer(bpy.data.cameras[0])
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory//armsdk//armory/blender/make_renderer.py", line 20, in make_renderer
    nodes_renderpath.load_library('deferred_path_high', 'armory_default')
  File "/home/onek8/Downloads/Armory_preview04_linux64/Armory//armsdk//armory/blender/nodes_renderpath.py", line 874, in load_library
    ref.use_fake_user = True
AttributeError: 'NoneType' object has no attribute 'use_fake_user'

location: <unknown location>:-1

location: <unknown location>:-1



I do believe the unknown location is due to the / being stripped from the sdk path. If theres anything else i can test please let me know.

**Comment by luboslenco** [comment]
Awesome, this really helps a ton! Putting focus on the Windows issue now and releasing a new build then - will keep this post updated.

**Comment by bibleuspro** [comment]
I had similar problem, brand new to this, but managed to get past basic play test now after figuring out some things not obvious to first time users.

In manual this fails.
"To verify everything is working correctly, save your .blend file and hit Play in viewport button, located in the 3D view header."
http://armory3d.org/manual/getting_started/setup.html

Newish to blender (used only for what I have needed, following tutorials...less than 100 hours in it), coming from Unity 3D...I don't know what is assumed. I think that means this right?
![image](https://cloud.githubusercontent.com/assets/19825051/21554896/a1a85d86-cdd0-11e6-9152-b40da2f97a12.png)

Either way the suggestion "In Properties - Render panel - Armory Play, does it work if you select 'Browser' runtime and hit play?" got me on right track, don't even need to use browser can still use krom...seems I followed docs/manual wrong first go. Lets update them?
https://github.com/armory3d/armory/issues/92#issuecomment-267190191
![image](https://cloud.githubusercontent.com/assets/19825051/21554857/5575261a-cdd0-11e6-8d6a-177fd5c04baf.png)

**Comment by luboslenco** [comment]
I highlighted the Play in Viewport button in manual so it should be a bit clearer now. :)

@breebee fixed several issues on Linux, can you try on Build 8?
