### ISSUE TITLE
provide visual feedback for updating Armory through Blender

### ISSUE THREAD

**Issue by killarny** [armory3d/armory#920]
Until today, I didn't realize that one needs to have the system console window toggled on in order to see what is going on when pressing the "Update SDK" button. I had just assumed it was broken because nothing seemed to happen when I pushed it in the past.

Perhaps showing some sort of spinning indicator, or a line of text that shows a rough status of the update ("Updating with git, please wait..", "Finished updating.", etc) would improve the usability of this part of the addon preferences panel.

![image](https://user-images.githubusercontent.com/29001/46435594-b25d2900-c724-11e8-8ac9-88bf682102e1.png)

**Comment by luboslenco** [comment]
There should be `Updating, check console for details..` message shown in the Blender header, did that not show up for you? Or perhaps it's not flashy enough to be noticed?

Showing a more robust progress bar in Blender tends to be hacky, maybe that changes in b2.8.

**Comment by killarny** [comment]
Oh, I do see that in the header of the main blender window, which is obscured by the popup location of User Preferences for me. I never noticed that before.

I wonder if it's possible to mirror that information directly in a text field in that Armory Updater section. Perhaps the control that currently shows the "Please restart Blender after successful SDK update." text?

**Comment by luboslenco** [comment]
Fixed, will now show that info in the Armory Updater section as well.
