### ISSUE TITLE
GetRotation, SetRotation,LookAt

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#921]
Those doesn't work.

1) I used the node LookAt giving it 
- origin
- destination (origin + vector direction * length)
LookAt  outputs a rotation i connect to SetRoation, but the projectile doesn't follow the direction.

I tried node GetRotation from a parent object and connect to setRotation node for projectile but it also doesn't work and doesn't follow the same orientation.

The bug can be on GetRotation, SetRotation or LookAt nodes.

Either bug fix, or make some oriented projectile example would be greatly appreciated as orienting to a direction is something heavily used in games.

**Comment by DevMagicLord** [comment]
I will definitively use the logic pack with LookingAt, it's a great new logic node.
It must be included in Armory directly.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/43acf28fc8f377cbdcb5b4b832ec7f80cdafc7d6.
