### ISSUE TITLE
Continuous collision detection

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#922]
Armory needs a continuous collision detection option for objects moving fast.

Otherwise objects with high velocity will pass through other objects.

For example twin stick shooter, when continuously shooting balls pass through the other character capsule collision most of the time.

**Comment by DevMagicLord** [comment]
The player controller si not the issue, it uses correctly physics with SetLinearVelocity.

The issue is there is no continuous collision detection to prevent physic objects passing through others.

Good physic based gameplay on Armory is not possible.

I tried timeline animation with physics, or a kinematic object using translateObject function, other 3D physic objects can pass trough those physics objects moving.
[http://forums.armory3d.org/t/timeline-with-physics/2050/3](url)

**Comment by DevMagicLord** [comment]
Great  : )

**Comment by DevMagicLord** [comment]
> 
> 
> I noticed that I could no longer use the "Get First Contact" node to detect collisions with objects when I enabled this. Does anybody know why?

I use GetContacts.
Should Get First Contact be deprecated ? 
I would like new options for GetContacts : 

- output boolean : At least one contact 
- contact index 
- output index contact object

**Comment by zicklag** [comment]
I'll probably look into that, then. Might be able to consolidate the contact nodes.

**Comment by luboslenco** [comment]
Reopened to investigate. 😈

**Comment by DevMagicLord** [comment]
Many issues in forum thread
[http://forums.armory3d.org/t/continuous-collision-detection/2126/12](url)

**Comment by DevMagicLord** [comment]
Continuous Collision Detection seem to work well.
Gravity does not work is a different bug.

**Comment by DevMagicLord** [comment]
Gravity works well on nighty, it seems it's resolved :+1:
