### ISSUE TITLE
Armory traits display bugs

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#925]
There is many display issues with armory traits.

https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/traitsdisplaybug.jpg?raw=true

For example on sample "navmesh" : 
1) select player , click on Bundled, you will have two scripts Navagent and NavigateTree
2)  select follower ,  click on haxe, you'll get two empty line on traits with a checkbox on.
3) click on "plane.001", there is three empty lines with check box on if you select nodes.

Instead it should only display lines only when there is nodes if you click on nodes , only display lines script when there is scripts on the object.

**Comment by luboslenco** [comment]
If I understand this correctly you are changing trait types but do not assign script/nodes afterwards. You will get similar behavior with materials, once you un-assign the material there is an empty slot.
![capture1](https://user-images.githubusercontent.com/3685704/46569432-3695f300-c955-11e8-8f61-edad8952520e.PNG)
