### ISSUE TITLE
Crash when refrence script not found

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#926]
I import an asset from another Blender file in the Armory 3D scene.

The imported model references an haxe script that does not have been imported.
When the game is luanched it crashes.
If i delete the Armory trait reference the game runs without crash.

Some security options would be appreciated : 
- no crash when there is reference to a script or nodes that are missing 
- display at game start a dialog box saying references are missing

**Comment by luboslenco** [comment]
Should print a `Referenced trait file not found` error with details into console now.
