### ISSUE TITLE
Armory_05_linux64_b28z in manjaro7.1.12 (currently the latest version，desktop environment：gnome ) cannot be run with a mouse click

### ISSUE THREAD

**Issue by haizhou37** [armory3d/armory#928]
After I click and run with the mouse, the mouse will show a busy state for a while, but it will not respond, I can't open the software.But it can run via the terminal command line. 
I tested that version of 2.79, but It's ok.
Below is the output of the command line：
`Color management: using fallback mode for management
Read prefs: /home/z/.config/blender/2.80/config/userpref.blend
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
Received X11 Error:
	error code:   167
	request code: 152
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   167
	request code: 152
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   167
	request code: 152
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   167
	request code: 152
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   167
	request code: 152
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   167
	request code: 152
	minor code:   34
	error text:   GLXBadFBConfig
Received X11 Error:
	error code:   8
	request code: 152
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 152
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 152
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 152
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 152
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
Received X11 Error:
	error code:   8
	request code: 152
	minor code:   34
	error text:   BadMatch (invalid parameter attributes)
found bundled python: /home/z/下载/Armory_05_linux64_b28/Armory/2.80/python
Traceback (most recent call last):
  File "/home/z/下载/Armory_05_linux64_b28/Armory/2.80/scripts/modules/addon_utils.py", line 383, in enable
    raise Exception(f"Add-on '{module_name:s}' has not been upgraded to 2.8, ignoring")
Exception: Add-on 'io_curve_svg' has not been upgraded to 2.8, ignoring
Warning: class ArmoryAddonPreferences contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/2.80/scripts/addons/armory.py:446
    make field: ArmoryAddonPreferences.sdk_bundled
    make field: ArmoryAddonPreferences.sdk_path
    make field: ArmoryAddonPreferences.show_advanced
    make field: ArmoryAddonPreferences.player_gapi_win
    make field: ArmoryAddonPreferences.player_gapi_linux
    make field: ArmoryAddonPreferences.player_gapi_mac
    make field: ArmoryAddonPreferences.code_editor
    make field: ArmoryAddonPreferences.ui_scale
    make field: ArmoryAddonPreferences.khamake_threads
    make field: ArmoryAddonPreferences.renderdoc_path
    make field: ArmoryAddonPreferences.ffmpeg_path
    make field: ArmoryAddonPreferences.save_on_build
    make field: ArmoryAddonPreferences.legacy_shaders
    make field: ArmoryAddonPreferences.relative_paths
    make field: ArmoryAddonPreferences.viewport_controls
    make field: ArmoryAddonPreferences.skip_update
Warning: class ArmNodeSocketObject contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:249
    make field: ArmNodeSocketObject.default_value
Warning: class ARM_OT_node_eyedrop contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:250
    make field: ARM_OT_node_eyedrop.socket_index
Warning: class ArmNodeSocketAnimAction contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:251
    make field: ArmNodeSocketAnimAction.default_value
Warning: class ARM_OT_node_add_input contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:252
    make field: ARM_OT_node_add_input.node_index
    make field: ARM_OT_node_add_input.socket_type
Warning: class ARM_OT_node_add_input_value contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:253
    make field: ARM_OT_node_add_input_value.node_index
    make field: ARM_OT_node_add_input_value.socket_type
Warning: class ARM_OT_node_remove_input contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:254
    make field: ARM_OT_node_remove_input.node_index
Warning: class ARM_OT_node_remove_input_value contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:255
    make field: ARM_OT_node_remove_input_value.node_index
Warning: class ARM_OT_node_add_output contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:256
    make field: ARM_OT_node_add_output.node_index
    make field: ARM_OT_node_add_output.socket_type
Warning: class ARM_OT_node_remove_output contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:257
    make field: ARM_OT_node_remove_output.node_index
Warning: class ARM_OT_node_add_input_output contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:258
    make field: ARM_OT_node_add_input_output.node_index
    make field: ARM_OT_node_add_input_output.in_socket_type
    make field: ARM_OT_node_add_input_output.out_socket_type
    make field: ARM_OT_node_add_input_output.in_name_format
    make field: ARM_OT_node_add_input_output.out_name_format
    make field: ARM_OT_node_add_input_output.in_index_name_offset
Warning: class ARM_OT_node_remove_input_output contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/logicnode/arm_nodes.py:259
    make field: ARM_OT_node_remove_input_output.node_index
Warning: class ArmTraitParamListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits_params.py:164
    make field: ArmTraitParamListItem.name
Warning: class ARM_TRAITPARAMSLIST_OT_new_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits_params.py:166
    make field: ARM_TRAITPARAMSLIST_OT_new_item.is_object
Warning: class ARM_TRAITPARAMSLIST_OT_delete_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits_params.py:167
    make field: ARM_TRAITPARAMSLIST_OT_delete_item.is_object
Warning: class ARM_TRAITPARAMSLIST_OT_move_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits_params.py:168
    make field: ARM_TRAITPARAMSLIST_OT_move_item.direction
    make field: ARM_TRAITPARAMSLIST_OT_move_item.is_object
Warning: class ArmTraitPropListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits_props.py:38
    make field: ArmTraitPropListItem.name
    make field: ArmTraitPropListItem.value
Warning: class ArmTraitListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:567
    make field: ArmTraitListItem.name
    make field: ArmTraitListItem.enabled_prop
    make field: ArmTraitListItem.type_prop
    make field: ArmTraitListItem.class_name_prop
    make field: ArmTraitListItem.canvas_name_prop
    make field: ArmTraitListItem.webassembly_prop
    make field: ArmTraitListItem.nodes_name_prop
    make field: ArmTraitListItem.arm_traitparamslist
    make field: ArmTraitListItem.arm_traitparamslist_index
    make field: ArmTraitListItem.arm_traitpropslist
    make field: ArmTraitListItem.arm_traitpropslist_index
Warning: class ARM_TRAITLIST_OT_new_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:569
    make field: ARM_TRAITLIST_OT_new_item.is_object
Warning: class ARM_TRAITLIST_OT_delete_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:570
    make field: ARM_TRAITLIST_OT_delete_item.is_object
Warning: class ARM_TRAITLIST_OT_delete_item_scene contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:571
    make field: ARM_TRAITLIST_OT_delete_item_scene.is_object
Warning: class ARM_TRAITLIST_OT_move_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:572
    make field: ARM_TRAITLIST_OT_move_item.direction
    make field: ARM_TRAITLIST_OT_move_item.is_object
Warning: class ARM_OT_edit_script contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:573
    make field: ARM_OT_edit_script.is_object
Warning: class ARM_OT_edit_bundled_script contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:574
    make field: ARM_OT_edit_bundled_script.is_object
Warning: class ARM_OT_edit_canvas contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:575
    make field: ARM_OT_edit_canvas.is_object
Warning: class ARM_OT_new_script contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:576
    make field: ARM_OT_new_script.is_object
    make field: ARM_OT_new_script.class_name
Warning: class ARM_OT_new_canvas contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_traits.py:577
    make field: ARM_OT_new_canvas.is_object
    make field: ARM_OT_new_canvas.canvas_name
Warning: class ArmLodListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_lod.py:98
    make field: ArmLodListItem.name
    make field: ArmLodListItem.enabled_prop
    make field: ArmLodListItem.screen_size_prop
Warning: class ArmTilesheetActionListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_tilesheet.py:255
    make field: ArmTilesheetActionListItem.name
    make field: ArmTilesheetActionListItem.start_prop
    make field: ArmTilesheetActionListItem.end_prop
    make field: ArmTilesheetActionListItem.loop_prop
Warning: class ARM_TILESHEETACTIONLIST_OT_move_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_tilesheet.py:259
    make field: ARM_TILESHEETACTIONLIST_OT_move_item.direction
Warning: class ArmTilesheetListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_tilesheet.py:261
    make field: ArmTilesheetListItem.name
    make field: ArmTilesheetListItem.tilesx_prop
    make field: ArmTilesheetListItem.tilesy_prop
    make field: ArmTilesheetListItem.framerate_prop
    make field: ArmTilesheetListItem.arm_tilesheetactionlist
    make field: ArmTilesheetListItem.arm_tilesheetactionlist_index
Warning: class ARM_TILESHEETLIST_OT_move_item contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_tilesheet.py:265
    make field: ARM_TILESHEETLIST_OT_move_item.direction
Warning: class ArmExporterListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_exporter.py:224
    make field: ArmExporterListItem.name
    make field: ArmExporterListItem.arm_project_rp
    make field: ArmExporterListItem.arm_project_scene
    make field: ArmExporterListItem.arm_project_target
    make field: ArmExporterListItem.arm_gapi_win
    make field: ArmExporterListItem.arm_gapi_winapp
    make field: ArmExporterListItem.arm_gapi_linux
    make field: ArmExporterListItem.arm_gapi_android
    make field: ArmExporterListItem.arm_gapi_mac
    make field: ArmExporterListItem.arm_gapi_ios
    make field: ArmExporterListItem.arm_gapi_html5
Warning: class ArmBakeListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_bake.py:315
    make field: ArmBakeListItem.object_name
    make field: ArmBakeListItem.res_x
    make field: ArmBakeListItem.res_y
Warning: class ArmRPListItem contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/props_renderpath.py:709
    make field: ArmRPListItem.name
    make field: ArmRPListItem.rp_driver_list
    make field: ArmRPListItem.rp_driver
    make field: ArmRPListItem.rp_renderer
    make field: ArmRPListItem.rp_depthprepass
    make field: ArmRPListItem.rp_hdr
    make field: ArmRPListItem.rp_render_to_texture
    make field: ArmRPListItem.rp_background
    make field: ArmRPListItem.arm_irradiance
    make field: ArmRPListItem.arm_radiance
    make field: ArmRPListItem.arm_radiance_size
    make field: ArmRPListItem.arm_radiance_sky
    make field: ArmRPListItem.rp_autoexposure
    make field: ArmRPListItem.rp_compositornodes
    make field: ArmRPListItem.rp_shadowmap
    make field: ArmRPListItem.rp_shadowmap_cascades
    make field: ArmRPListItem.arm_pcfsize
    make field: ArmRPListItem.rp_supersampling
    make field: ArmRPListItem.rp_antialiasing
    make field: ArmRPListItem.rp_volumetriclight
    make field: ArmRPListItem.rp_ssr
    make field: ArmRPListItem.rp_ssgi
    make field: ArmRPListItem.rp_dfao
    make field: ArmRPListItem.rp_dfrs
    make field: ArmRPListItem.rp_dfgi
    make field: ArmRPListItem.rp_bloom
    make field: ArmRPListItem.rp_eyeadapt
    make field: ArmRPListItem.rp_motionblur
    make field: ArmRPListItem.rp_translucency
    make field: ArmRPListItem.rp_translucency_state
    make field: ArmRPListItem.rp_decals
    make field: ArmRPListItem.rp_decals_state
    make field: ArmRPListItem.rp_overlays
    make field: ArmRPListItem.rp_overlays_state
    make field: ArmRPListItem.rp_sss
    make field: ArmRPListItem.rp_sss_state
    make field: ArmRPListItem.rp_blending
    make field: ArmRPListItem.rp_blending_state
    make field: ArmRPListItem.rp_draw_order
    make field: ArmRPListItem.rp_stereo
    make field: ArmRPListItem.rp_greasepencil
    make field: ArmRPListItem.rp_ocean
    make field: ArmRPListItem.rp_gi
    make field: ArmRPListItem.rp_voxelgi_resolution
    make field: ArmRPListItem.rp_voxelgi_resolution_z
    make field: ArmRPListItem.arm_clouds
    make field: ArmRPListItem.arm_soft_shadows
    make field: ArmRPListItem.arm_soft_shadows_penumbra
    make field: ArmRPListItem.arm_soft_shadows_distance
    make field: ArmRPListItem.arm_ssrs
    make field: ArmRPListItem.arm_texture_filter
    make field: ArmRPListItem.arm_material_model
    make field: ArmRPListItem.arm_diffuse_model
    make field: ArmRPListItem.arm_rp_displacement
    make field: ArmRPListItem.arm_tess_mesh_inner
    make field: ArmRPListItem.arm_tess_mesh_outer
    make field: ArmRPListItem.arm_tess_shadows_inner
    make field: ArmRPListItem.arm_tess_shadows_outer
    make field: ArmRPListItem.arm_rp_resolution
    make field: ArmRPListItem.arm_rp_resolution_size
    make field: ArmRPListItem.arm_rp_resolution_filter
    make field: ArmRPListItem.rp_dynres
    make field: ArmRPListItem.arm_ssr_half_res
    make field: ArmRPListItem.rp_ssr_z_only
    make field: ArmRPListItem.rp_voxelgi_hdr
    make field: ArmRPListItem.rp_voxelgi_relight
    make field: ArmRPListItem.arm_voxelgi_dimensions
    make field: ArmRPListItem.arm_voxelgi_revoxelize
    make field: ArmRPListItem.arm_voxelgi_temporal
    make field: ArmRPListItem.arm_voxelgi_bounces
    make field: ArmRPListItem.arm_voxelgi_camera
    make field: ArmRPListItem.arm_voxelgi_shadows
    make field: ArmRPListItem.arm_voxelgi_refraction
    make field: ArmRPListItem.arm_samples_per_pixel
    make field: ArmRPListItem.arm_ssao_half_res
    make field: ArmRPListItem.arm_voxelgi_diff
    make field: ArmRPListItem.arm_voxelgi_cones
    make field: ArmRPListItem.arm_voxelgi_spec
    make field: ArmRPListItem.arm_voxelgi_occ
    make field: ArmRPListItem.arm_voxelgi_env
    make field: ArmRPListItem.arm_voxelgi_step
    make field: ArmRPListItem.arm_voxelgi_offset
    make field: ArmRPListItem.arm_voxelgi_range
    make field: ArmRPListItem.arm_sss_width
    make field: ArmRPListItem.arm_clouds_density
    make field: ArmRPListItem.arm_clouds_size
    make field: ArmRPListItem.arm_clouds_lower
    make field: ArmRPListItem.arm_clouds_upper
    make field: ArmRPListItem.arm_clouds_wind
    make field: ArmRPListItem.arm_clouds_secondary
    make field: ArmRPListItem.arm_clouds_precipitation
    make field: ArmRPListItem.arm_clouds_eccentricity
    make field: ArmRPListItem.arm_ocean_base_color
    make field: ArmRPListItem.arm_ocean_water_color
    make field: ArmRPListItem.arm_ocean_level
    make field: ArmRPListItem.arm_ocean_amplitude
    make field: ArmRPListItem.arm_ocean_height
    make field: ArmRPListItem.arm_ocean_choppy
    make field: ArmRPListItem.arm_ocean_speed
    make field: ArmRPListItem.arm_ocean_freq
    make field: ArmRPListItem.arm_ocean_fade
    make field: ArmRPListItem.arm_ssgi_strength
    make field: ArmRPListItem.arm_ssgi_step
    make field: ArmRPListItem.arm_ssgi_max_steps
    make field: ArmRPListItem.arm_ssgi_rays
    make field: ArmRPListItem.arm_bloom_threshold
    make field: ArmRPListItem.arm_bloom_strength
    make field: ArmRPListItem.arm_bloom_radius
    make field: ArmRPListItem.arm_motion_blur_intensity
    make field: ArmRPListItem.arm_ssr_ray_step
    make field: ArmRPListItem.arm_ssr_min_ray_step
    make field: ArmRPListItem.arm_ssr_search_dist
    make field: ArmRPListItem.arm_ssr_falloff_exp
    make field: ArmRPListItem.arm_ssr_jitter
    make field: ArmRPListItem.arm_volumetric_light_air_turbidity
    make field: ArmRPListItem.arm_volumetric_light_air_color
    make field: ArmRPListItem.arm_volumetric_light_steps
    make field: ArmRPListItem.arm_shadowmap_split
    make field: ArmRPListItem.arm_shadowmap_bounds
    make field: ArmRPListItem.arm_autoexposure_strength
    make field: ArmRPListItem.arm_ssrs_ray_step
    make field: ArmRPListItem.arm_letterbox
    make field: ArmRPListItem.arm_letterbox_size
    make field: ArmRPListItem.arm_grain
    make field: ArmRPListItem.arm_grain_strength
    make field: ArmRPListItem.arm_sharpen
    make field: ArmRPListItem.arm_sharpen_strength
    make field: ArmRPListItem.arm_fog
    make field: ArmRPListItem.arm_fog_color
    make field: ArmRPListItem.arm_fog_amounta
    make field: ArmRPListItem.arm_fog_amountb
    make field: ArmRPListItem.arm_tonemap
    make field: ArmRPListItem.arm_lens_texture
    make field: ArmRPListItem.arm_fisheye
    make field: ArmRPListItem.arm_vignette
    make field: ArmRPListItem.arm_lensflare
    make field: ArmRPListItem.arm_lut_texture
    make field: ArmRPListItem.arm_skin
    make field: ArmRPListItem.arm_skin_max_bones_auto
    make field: ArmRPListItem.arm_skin_max_bones
    make field: ArmRPListItem.arm_particles
    make field: ArmRPListItem.arm_culling
    make field: ArmRPListItem.arm_two_sided_area_light
Warning: class LNSurfaceNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNSurfaceNode.property0
Warning: class LNMathNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMathNode.property0
    make field: LNMathNode.property1_
Warning: class LNMeshNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMeshNode.property0
Warning: class LNKeyboardNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNKeyboardNode.property0
    make field: LNKeyboardNode.property1
Warning: class LNOnVolumeTriggerNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnVolumeTriggerNode.property0
Warning: class LNGetChildNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNGetChildNode.property0
Warning: class LNOnVirtualButtonNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnVirtualButtonNode.property0
    make field: LNOnVirtualButtonNode.property1
Warning: class LNOnContactNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnContactNode.property0
Warning: class LNOnSurfaceNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnSurfaceNode.property0
Warning: class LNMixNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMixNode.property0
    make field: LNMixNode.property1
    make field: LNMixNode.property2_
Warning: class LNExpressionNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNExpressionNode.property0
Warning: class LNCompareNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNCompareNode.property0
Warning: class LNOnKeyboardNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnKeyboardNode.property0
    make field: LNOnKeyboardNode.property1
Warning: class LNOnEventNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnEventNode.property0
Warning: class LNVolumeTriggerNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVolumeTriggerNode.property0
Warning: class LNMouseNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMouseNode.property0
    make field: LNMouseNode.property1
Warning: class LNVectorFromTransformNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVectorFromTransformNode.property0
Warning: class LNGroupNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNGroupNode.property0
Warning: class LNPlaySoundRawNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNPlaySoundRawNode.property0
Warning: class LNTraitNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNTraitNode.property0
Warning: class LNContainsStringNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNContainsStringNode.property0
Warning: class LNVectorMathNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVectorMathNode.property0
Warning: class LNOnMouseNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnMouseNode.property0
    make field: LNOnMouseNode.property1
Warning: class LNScriptNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNScriptNode.property0_
Warning: class LNSceneNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNSceneNode.property0
Warning: class LNMatrixMathNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMatrixMathNode.property0
Warning: class LNOnGamepadNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnGamepadNode.property0
    make field: LNOnGamepadNode.property1
Warning: class LNGamepadNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNGamepadNode.property0
    make field: LNGamepadNode.property1
Warning: class LNCallGroupNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNCallGroupNode.property0_
Warning: class LNMaterialNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMaterialNode.property0
Warning: class LNGateNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNGateNode.property0
    make field: LNGateNode.property1
Warning: class LNVectorMixNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVectorMixNode.property0
    make field: LNVectorMixNode.property1
    make field: LNVectorMixNode.property2_
Warning: class LNVirtualButtonNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVirtualButtonNode.property0
    make field: LNVirtualButtonNode.property1
Warning: class LNSurfaceNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNSurfaceNode.property0
Warning: class LNMathNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMathNode.property0
    make field: LNMathNode.property1_
Warning: class LNMeshNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMeshNode.property0
Warning: class LNKeyboardNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNKeyboardNode.property0
    make field: LNKeyboardNode.property1
Warning: class LNOnVolumeTriggerNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnVolumeTriggerNode.property0
Warning: class LNGetChildNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNGetChildNode.property0
Warning: class LNOnVirtualButtonNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnVirtualButtonNode.property0
    make field: LNOnVirtualButtonNode.property1
Warning: class LNOnContactNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnContactNode.property0
Warning: class LNOnSurfaceNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnSurfaceNode.property0
Warning: class LNMixNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMixNode.property0
    make field: LNMixNode.property1
    make field: LNMixNode.property2_
Warning: class LNExpressionNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNExpressionNode.property0
Warning: class LNCompareNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNCompareNode.property0
Warning: class LNOnKeyboardNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnKeyboardNode.property0
    make field: LNOnKeyboardNode.property1
Warning: class LNOnEventNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNOnEventNode.property0
Warning: class LNVolumeTriggerNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVolumeTriggerNode.property0
Warning: class LNMouseNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNMouseNode.property0
    make field: LNMouseNode.property1
Warning: class LNVectorFromTransformNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNVectorFromTransformNode.property0
Warning: class LNGroupNode contains a properties which should be a field!
/home/z/下载/Armory_05_linux64_b28/Armory/armsdk//armory/blender/arm/nodes_logic.py:31
    make field: LNGroupNode.property0
Warning: class LNPlaySoundRawNode contains a properties whic
`

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/912.
