### ISSUE TITLE
last of us style light mapping 

### ISSUE THREAD

**Issue by dener3id** [armory3d/armory#930]
http://miciwan.com/SIGGRAPH2013/Lighting%20Technology%20of%20The%20Last%20Of%20Us.pdf
*(drag & drop zipped .blend file here)*

**Comment by DevMagicLord** [comment]
Lightmapping a complex scene can take hours or days until this is made on GPU and you have a powerfull PC.
While voxel is not as precise, it bakes in some milliseconds.

**Comment by luboslenco** [comment]
Thanks, bookmarked! Will keep improving the light map support.

**Comment by dener3id** [comment]
If you care I could try to send you my attempt at it from BGE a few years
ago might make your job essayer.
