### ISSUE TITLE
Play button on top menu 

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#931]
Most of the time , we need to quickly check in play mode.
Unfortunatelly in Armory the "play" button in on the long list in the render tab.

It would greatly improve Armory to have like most 3D engines, the "play" button on the editor top menu.

**Comment by luboslenco** [comment]
Use `F5` keyboard shortcut to play, that will work all the time regardless of the current Blender layout. The shortcut is also visible in the  `Play` button tooltip.

**Comment by DevMagicLord** [comment]
I mean make it like most 3D engines, easy to pick up for newcomers and for those not using key shortcuts.
