### ISSUE TITLE
Template crash

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#933]
I added a navigation and bot follower with nodes and navmesh functions.

The template crash and there is no errors output.

The project download
https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/twin_stick.zip

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/927.

**Comment by DevMagicLord** [comment]
But i don't see any navmesh in the scene hierarchy.
It is in some cache ?
