### ISSUE TITLE
Animation events for melee games

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#937]
Animation events "start attack" and "end attack" allow to know the interval for attack to be possible during animation.

Player will only do damage one time when the punch overlap with other character, 
and only when the animation playing is between those animation events.

**Comment by luboslenco** [comment]
You could use animation markers and tag the "start attack" and "end attack" frames. See Blender manual:
https://docs.blender.org/manual/en/dev/animation/markers.html

The marker is also used in this example:
https://github.com/armory3d/armory_examples/tree/master/animation_actions
