### ISSUE TITLE
Fresnel Node Issues

### ISSUE THREAD

**Issue by zaethan** [armory3d/armory#939]
When using this setup with the standard Fresnel node, it looks ok.
![image](https://user-images.githubusercontent.com/39460066/46617327-c508a100-cb1c-11e8-9a1e-821af21821b9.png)

However, changing the IOR to some higher value decreases the rainbow frequency in cycles but increases it in armory.
![image](https://user-images.githubusercontent.com/39460066/46617410-000ad480-cb1d-11e8-9b0c-53cbf97028f9.png)

And the Normal input is not used at all.
![image](https://user-images.githubusercontent.com/39460066/46617486-26307480-cb1d-11e8-907f-773e0f0da7b3.png)

Looking for a fix, I searched through blenders source files in a github mirror and found what I think is their way of implementing fresnel:
https://github.com/sobotka/blender/blob/master/intern/cycles/kernel/shaders/node_fresnel.osl
https://github.com/sobotka/blender/blob/master/intern/cycles/kernel/shaders/node_fresnel.h

It also seems like the Layer Weight node also has a fresnel output which is being computed differently than the fresnel node itself and is not using its normal input as well.
Again, here's blenders implementation of this:
https://github.com/sobotka/blender/blob/master/intern/cycles/kernel/shaders/node_layer_weight.osl

**Comment by luboslenco** [comment]
Thanks, fixed now.
