### ISSUE TITLE
Full translation of logic editor to node based logic editor

### ISSUE THREAD

**Issue by George-the-1st** [armory3d/armory#94]
An easy way for more games to be made using Armory Engine is to make it easier for people to take advantage of the huge amount of resources already out in the world. I would suggest making it so that the system for the logic editor in Blender can be replicated in the new node based logic editor in Armory. It doesn't have to be a perfect one to one but the same things capable of happening in one should be capable in the other. It would be an easy way to add support in a fashion that would really be beneficial to the engine. I STRONGLY suggest this particular feature and suggest it early as it allows someone to use the structure of Armory's node system with the intuitiveness and already known nature of BGE. With this, you also have the list of nodes/features you need to add in a pre-existing list in the logic editor. Adding this early and even going as far as doing it before you continue to add cycles nodes compatibility will allow this engine to make games early and get more feedback and community activity/support rather than focus on graphics and then put game creation ability second.

The current system in BGE doesn't work in Armory and, even if it did, it is a linear system that makes you look through lists rather then a layout to try to get an understanding of what is going on. Again, this feature or something like it will be heavily useful in getting the ball rolling on actual game development rather than graphical quality.

**Comment by luboslenco** [comment]
Planning for more logic/scripting stuff as soon as build 5 is out.
Continuing at https://github.com/armory3d/armory/issues/47
