### ISSUE TITLE
Ace tone maping

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#940]
The best tone maping is Ace.
Armory ones are cool , but they are not the best.

**Comment by Naxela** [comment]
Armory already uses that. Although I think that's the one designated as Filmic 2 in the options: https://github.com/armory3d/armory/blob/master/Shaders/std/tonemap.glsl#L27

**Comment by luboslenco** [comment]
What is Ace? Do you mean ACES Filmic Tone Mapping?

**Comment by adriansnetlis** [comment]
In my ecperience ACES is oversaturated and has acidic cyans. It does not feel natural. It may depend on screen calibration, but for typical sRGB calibration ACES makes no sense.
