### ISSUE TITLE
Probably Haxe-Error in the Playground tutorial

### ISSUE THREAD

**Issue by Nos-** [armory3d/armory#941]
During the basic "Playground"-tutorial i got the following error message:
> armory.trait.physics.RigidBody has no field syncTransform

![image](https://user-images.githubusercontent.com/6155874/46628752-f09c8300-cb3e-11e8-926d-0afd49bc171a.png)

**Comment by luboslenco** [comment]
Hm, is `Armory Project - Modules - Physics` set to `Auto` or `Enabled` in Blender? (it should be `Auto` by default)

**Comment by Nos-** [comment]
> Hm, is `Armory Project - Modules - Physics` set to `Auto` or `Enabled` in Blender? (it should be `Auto` by default)

![image](https://user-images.githubusercontent.com/6155874/46631224-1af23e80-cb47-11e8-9e6e-ecfc19b3b1e1.png)

Can you find the information you asked for?

**Comment by luboslenco** [comment]
Here:
![capture](https://user-images.githubusercontent.com/3685704/46632536-51ca5380-cb4b-11e8-8c16-1798043851a8.PNG)

But I guess this is not it then. Does it fail out of the box when you download the playground tutorial blend?
https://github.com/armory3d/armory_tutorials/releases

**Comment by Nos-** [comment]
I tried with an empty example and the default settings (Physics set to Auto like in the screenshot above).

**Comment by widapraponco** [comment]
I have the same problem, there is no field syncTransform in Rigidbody, even I change Physics to "Enabled"

FYI: I didnt download the tutorial release, just created from the begining
![image](https://user-images.githubusercontent.com/10349235/47061348-45a15e80-d1fb-11e8-979b-7c1e21f66c6c.png)

**Comment by sh-dave** [comment]
Can you show the contents of the generated `khafile.js`, it should include the following 2 lines somewhere in it?
```
project.addDefine('arm_physics');
project.addDefine('arm_bullet');
```
