### ISSUE TITLE
[Materials] Redefinition of variable after adding dotproduct node operating on same vector

### ISSUE THREAD

**Issue by Disar** [armory3d/armory#942]
In this material if you look at the Flowmap node you see a `Mask` output. After adding this and using it Armory redefines a variable and can't compile.

I tried to simplify it it by using the `Mask` output only but that compiles, using the `uv1` and `uv2` causes the error. Not sure exactly what is causing it but didn't happen until I added the `Mask` output.

[flowmap.zip](https://github.com/armory3d/armory/files/2462660/flowmap.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/ef1d4bdbb45ba5e059f682ca8db2149c70fbb0c5.
