### ISSUE TITLE
Option to not render mesh

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#943]
I use primitives shapes object to create and adjust collisions, those object are attached to dynamic objects or static ones for level environment collisions.

The issue is we can't hide those "collision" objects.

Armory needs an option to not render meshes of some object.

**Comment by luboslenco** [comment]
See https://docs.blender.org/manual/en/latest/editors/outliner.html#object-level-restrictions.

> Rendering (camera icon)
> This will still keep the object visible in the scene, but it will be ignored by the renderer. R will toggle this property for any objects that are selected in the Outliner.
