### ISSUE TITLE
Weird physics

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#947]
It looks like gravity doesn't work well.

I already posted details here :  
[http://forums.armory3d.org/t/armory-weird-physics/1980](url)

Download the demo 
[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/B/motocyclerider.zip](url)

Controls :  

"C" and "B" to turn
"V" to move forward.

Then press "SPACE" some time to rotate the object on Y axis, and watch the object stuck on rotation unable to get Gravity correctly applied.

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/831.
