### ISSUE TITLE
Spawn linked object

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#948]
An object is linked as child of a parent object, also parented them.

When i spawn the parent it doesn't spawn the child object.

Or is there another way to spawn some prefab made of parent and child objects ?

**Comment by luboslenco** [comment]
- Nodes - children should be spawned with `Children` socket enabled on the `Spawn Object` node
- Haxe - children should be spawned with `spawnChildren` enabled for the `spawnObject()` call
