### ISSUE TITLE
Material Params - only one change per frame (?)

### ISSUE THREAD

**Issue by Simonrazer** [armory3d/armory#949]
The texture is supposed to be going sideways when you are holding A+D at the same time, but it only goes in the direction of the last pressed key. Also sometimes it jumps to a different location when releasing A/D.

[texturemove.zip](https://github.com/armory3d/armory/files/2476550/texturemove.zip)

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/b424b058bb90f293f59d847be12cd0f926fcd047, thanks.
