### ISSUE TITLE
Input.getKeyboard().started() / released() firing multiple times on Linux

### ISSUE THREAD

**Issue by StuffBySpencer** [armory3d/armory#950]
**_The Issue:_** In my [script](https://pastebin.com/EPkKZrpC), I watch for when the spacebar is `started` & `released`. However, the code runs more than it should. It behaves like the `down` method. Also, the bug tends to get fixed when pressing another key while holding down spacebar [ _so, if I just press and hold spacebar, `started` and `released` constantly return true. BUT, if I press another key, they seem to get reset to their proper values ]

**_Quick link to script in question:_** https://pastebin.com/EPkKZrpC

**_My OS:_** Linux Mint
**_Blender Version:_** 2.79
**_Armory Version:_** 0.5

***

**_More Info:_** So, when using `Keyboard.started()` or `Keyboard.released()` in my code, they will continue to fire off even though, according to the docs, they should only fire once [ _when pressed and when released, respectively_ ].

In this gif, you can see the issue. **Note:** I'm holding down the spacebar in this gif, but the trace keeps getting called as though I'm rapidly pressing it.
![keyboard_bug](https://user-images.githubusercontent.com/6043600/46937339-0aeacb00-d02f-11e8-9e6f-cc13c8c17409.gif)

***

**_Blender File:_**
[spaceyMcspaceface.blend.zip](https://github.com/armory3d/armory/files/2477861/spaceyMcspaceface.blend.zip)

**Comment by trsh** [comment]
Still there:
```
package arm;

import iron.system.Input;

class RotateReleased extends iron.Trait {
    var kb = Input.getKeyboard();

    public function new() {
        super();
        notifyOnUpdate(function() {
            if (kb.released("right")) {
                trace("Right - released"); // fires even not released
            }
        });
    }
}
```

**Comment by TheStarvingOne** [comment]
I confirm as above, both started() and released().

KDE Neon 5.14 Linux 4.15.0-45-generic
Intel Core2 Quad Q8300
Radeon RX580
8GB RAM

**Comment by luboslenco** [comment]
Patched at https://github.com/Kode/Kore/pull/366.
