### ISSUE TITLE
Read and write storage crashes in Armory

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#951]
Its appear that Read and write storage node make armory crash.

Issue was found by GWEN and he doesnt have an github account so, I am posting it here.
Below is link to forum GWEN made.
[http://forums.armory3d.org/t/save-score-so-that-it-can-retrieve-that-data-when-program-run-again/1991/4](url)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/833.
