### ISSUE TITLE
Game Freezes 

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#952]
Holding shoot button on enemy will freeze the game.No errors on both krom and HTML and show error in c++
Here of what happening when my game crashes (I don’t know much of C++, so i don’t understand it).
![capture3](https://user-images.githubusercontent.com/36535717/46952651-1975c880-d0a9-11e8-9186-e749656c51c5.JPG)

Here my .zip file -> [SpaceShooter.zip](https://github.com/armory3d/armory/files/2478811/SpaceShooter.zip)

**Comment by luboslenco** [comment]
In `Astroid.hx`: `object.getTrait(PlayerController).scoreInc(100);`

Astroid object has no PlayerController trait. It's then unable to call the `scoreInc` function.

Use `iron.Scene.active.getChild("SpaceShip")` or similar to retrieve object.
