### ISSUE TITLE
Navmesh doesn't work

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#954]
I followed the navmesh example, but the character doesn't move when i left click on terrain mesh.

Project zip file 

[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/B/actiongameBug.zip](url)

**Comment by luboslenco** [comment]
- In the navmesh example `Player` has `NavAgent` trait attached
- For `Character` trait ensure `idle` and `run` actions exist, as specified in parameters

Will improve the navmesh docs & functionality in 0.6.

**Comment by DevMagicLord** [comment]
Thanks
