### ISSUE TITLE
Read/write json files anywhere

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#956]
Armory needs to be able to read and write json files anywhere.

Json advantages : 
- it's simple to read, less bloated than XML
- it's structured and works great with game data

There is many usages from ASCII maps , to player and game data to save and load.

We should be able to choose to  :   
- save and read from a relative path to the game installation directory instead of a system directory
- choose to use encryption or not (better crypt player stats and data save to prevent easy cheating)

**Comment by luboslenco** [comment]
See related docs:
https://api.haxe.org/haxe/Json.html
https://api.haxe.org/Xml.html
https://api.haxe.org/haxe/crypto/index.html
http://api.kha.tech/kha/Assets.html
