### ISSUE TITLE
Lightmap Z fighting issues

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#958]
I baked lightmap with 64*64 textures, and used Armory PBR for the models materials.

When the game is running there is Z fighting issues.

[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/B/Zissues.gif?raw=true](url)

**Comment by luboslenco** [comment]
It's z fighting in the blender viewport as well, you can adjust that face to get rid of it.
