### ISSUE TITLE
Logic nodes read/write json files anywhere

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#959]
Following this issue https://github.com/armory3d/armory/issues/956

Logic nodes should propose to read and write json files anywhere for game saves or game data save.
With node options like relative path to game installation and encryption.

A game using only logic nodes should be possible.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/780d072fbdfe5cf9b7cb821c2b3cb352712ea25b.
- https://github.com/armory3d/armory_examples/tree/master/file_write
- https://github.com/armory3d/armory_examples/tree/master/file_read
- https://github.com/armory3d/armory_examples/tree/master/file_storage
