### ISSUE TITLE
HAXE Compiler Error

### ISSUE THREAD

**Issue by breebee** [armory3d/armory#96]
Thanks for the new build preview 5! Here is the console log on my linux ubuntu 16.10 desktop using the packaged SDK and blender

Armory v16.12.1
Scene built in 0.0021042823791503906
Creating Kha project.
Exporting asset 1 of 1 (blur_edge_pass_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (compositor_pass_EnvCol_SSAO_SMAA_CompoTonemap.arm).
Exporting asset 1 of 1 (deferred_indirect_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (deferred_light_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_blend_weight_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_edge_detect_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (smaa_neighborhood_blend_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (ssao_pass_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (world_EnvCol_SSAO_SMAA.arm).
Exporting asset 1 of 1 (__default_data.arm).
Exporting asset 1 of 1 (Scene.arm).
Exporting asset 1 of 1 (World_irradiance.arm).
Exporting asset 1 of 1 (World_material.arm).
Exporting asset 1 of 1 (mesh_Cube.arm).
Exporting asset 1 of 1 (armory_default.arm).
Compiling shader 1 of 1 (__default_mesh.frag.glsl).
Compiling shader 1 of 1 (__default_mesh.vert.glsl).
Compiling shader 1 of 1 (__default_shadowmap.frag.glsl).
Compiling shader 1 of 1 (__default_shadowmap.vert.glsl).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (blur_edge_pass_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_SMAA_CompoTonemap.frag.glsl).
Compiling shader 1 of 1 (compositor_pass_EnvCol_SSAO_SMAA_CompoTonemap.vert.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_indirect_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (deferred_light_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_blend_weight_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_edge_detect_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (smaa_neighborhood_blend_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (ssao_pass_EnvCol_SSAO_SMAA.vert.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO_SMAA.frag.glsl).
Compiling shader 1 of 1 (world_EnvCol_SSAO_SMAA.vert.glsl).
/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:87: characters 34-60 : Class<kha.Shaders> has no field painter_image_frag

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:88: characters 32-58 : Class<kha.Shaders> has no field painter_image_vert

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:322: characters 34-62 : Class<kha.Shaders> has no field painter_colored_frag

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:323: characters 32-60 : Class<kha.Shaders> has no field painter_colored_vert

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:586: characters 34-59 : Class<kha.Shaders> has no field painter_text_frag

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:587: characters 32-57 : Class<kha.Shaders> has no field painter_text_vert

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:816: characters 34-60 : Class<kha.Shaders> has no field painter_video_frag

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/graphics4/Graphics2.hx:817: characters 32-58 : Class<kha.Shaders> has no field painter_video_vert

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/vr/VrInterfaceEmulated.hx:308: characters 26-52 : Class<kha.Shaders> has no field painter_image_vert

/home/onek8/Downloads/Armory_p05_linux64 (2)/Armory/armsdk/linux64/Kha/Sources/kha/vr/VrInterfaceEmulated.hx:309: characters 28-54 : Class<kha.Shaders> has no field painter_image_frag

Haxe compiler error.
Build failed, check console

**Comment by SolarLune** [comment]
Same issue using Solus OS 1.2.1, 64-bit with the Armory Add-on. 
GPU is a GTX 660.

**Comment by luboslenco** [comment]
Been messing with Kha path to make it shorter,  probably causing this. Investigating tomorrow when I am back to work. Will setup automated build testing early next year to prevent this:)

**Comment by breebee** [comment]
Yaaas! Like nightly builds? Super cool :dancer:

**Comment by MagicalPaladin** [comment]
Can't wait to see that ^^

**Comment by luboslenco** [comment]
Think I found the culprit, can you try to rename SDK folder from `Armory_p05_linux64 (2)` to something like `Armory_p05_linux64_2`?

Special characters like `()` in path seem to cause troubles. Will need some digging in Kha itself to check how to fix this. Adding a warning message for this in the meantime.

**Comment by luboslenco** [comment]
Build 6 will warn if special characters in the SDK path are detected, which should prevent this for now.

Continuing at https://github.com/Kode/khamake/issues/93.
