### ISSUE TITLE
Setting an object RigidBody as passive make Krom(debug build) white

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#961]
Assingning rigidbody to object as passive make screen white.
I know that setting it to Active and unchecking dynamic will work, so is passive supported or something or not because it will confuse lot of people.

**Comment by luboslenco** [comment]
Seems to be ok here, what is the error? Can you paste the project?

**Comment by BlackGoku36** [comment]
Sorry, really werid, just yesterday its show white screen and now it completely ok.
