### ISSUE TITLE
Ocean issues

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#965]
![image](https://user-images.githubusercontent.com/6423934/47151672-1239ff00-d2e3-11e8-9e09-0ac279b4d140.png)
On the right you can see what settings I use for ocean. But the settings affect only bottom color. At grazing angles it's always ugly green. The ocean shader seems to work a bit better at 2.79b. Any idea to what could be causing this odd behaviour?

Another good thing to have would be ocean reacting to sky light and SSR.

**Comment by AFWSI** [comment]
Yeah, I have spent hours trying to get good looking water with no success. I noticed the same thing with the color. From low angles it looks like little to no color. If you look at it from the air, it starts to show color ,but doesn't look that great and doesn't even look like the colors selected.


Wish we could create water(with foamy look) that looks similar to this. Can't tell from photos ,but you can see through the water to the ground.

![20181007061845_1](https://user-images.githubusercontent.com/24877571/47157770-adb17c80-d2af-11e8-8bb7-86d339654a23.jpg)

![20181007062032_1](https://user-images.githubusercontent.com/24877571/47157806-c6219700-d2af-11e8-9198-c9ba3ac75e11.jpg)

**Comment by adriansnetlis** [comment]
Well, it's possible to create geometric shader. Why I liked the idea of using the built-in ocean shader is because it's post-process based and thus has very low cost to it.

**Comment by luboslenco** [comment]
Reworked the shader into scrolling normal maps for better perf and customization. Still running as a post-process pass. Enabled water at https://github.com/armory3d/armory_templates/tree/master/third_person_terrain.

Normal maps have to be replaced manually at https://github.com/armory3d/armory/tree/master/Assets for now.
