### ISSUE TITLE
Normal Map Textures Not Working

### ISSUE THREAD

**Issue by adriansnetlis** [armory3d/armory#966]
`ERROR: /home/adriansnetlis/Documents/Armory/Projects/ShipGame/build_ShipGame/compiled/Shaders/Ocean_mesh.frag.glsl:27: 'Math_Value_res' : undeclared identifier 
ERROR: /home/adriansnetlis/Documents/Armory/Projects/ShipGame/build_ShipGame/compiled/Shaders/Ocean_mesh.frag.glsl:27: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

SPIR-V is not generated for failed compile or link
`
This is the error that I get when trying to use normal map in Armory 0.5b 2.8. Without any texture plugged in Normal Map node it works fine. Once I plug the texture in, shader failes to compile. The texture is common 8-bit RGBA png normal map.

The same behaviour confirmed in 2.79b version.

System:
OS: Antergos Linux (4.18.12-arch)
CPU: Ryzen 5 1600
GPU: GTX 1060 6GB
RAM: 16GB DDR4-2666

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/armory/commit/e11761016277c56a2377bc8b34ee6b845f34047e.
