### ISSUE TITLE
Proposal for Trait panel

### ISSUE THREAD

**Issue by DoubleZZ** [armory3d/armory#967]
![armoryuibis](https://user-images.githubusercontent.com/6493170/47181711-09b5e880-d324-11e8-9062-c0dbeb681c32.png)

A small proposal for the Trait Panel : 
- The Trait type is defined when you create a new one ("+" button)
- Trait type can't be changed anymore after being created. The previous model looks like an issue as you can set up multiple data on different types but only activate one (and sometime don't noticing it)
- Dynamic icons depend on the trait type (The original script commented about it)
- Custom icons (Haxe and Webassembly)

**Comment by DevMagicLord** [comment]
The actual one is confusing.
+1.

**Comment by DoubleZZ** [comment]
BTW, here's the file with the modified trait panel : 
https://www.dropbox.com/s/wuz2e2od8uy17ze/prop_traits.zip?dl=0

I really would like to use the git one but I have trouble with git and, without modification, I couldn't properly use armory with the armsdk provided on github.

**Comment by luboslenco** [comment]
Big thanks, it's in!
