### ISSUE TITLE
Normal map not working

### ISSUE THREAD

**Issue by MagicalPaladin** [armory3d/armory#97]
When i connect to normal map texture, "build failed"

**Comment by luboslenco** [comment]
Hi,

Did you add normal map node? Or is this for armory PBR node? Blend or screen of node setup would come handy:)

**Comment by MagicalPaladin** [comment]
Armory PBR node, will send here a screen cap when i can

**Comment by luboslenco** [comment]
For Armory PBR, connect Image Texture directly without going through 'Normal Map' node.

Added a new doc on materials with some examples: http://armory3d.org/manual/getting_started/scene4.html

Let me know if this was the case or something else is wrong.
