### ISSUE TITLE
Linux Krom Build Broken With Git Version

### ISSUE THREAD

**Issue by zicklag** [armory3d/armory#970]
Krom on Linux is currently broken with the git version of Armory. After the latest change made for armory3d/iron#48 the compile errors were fixed, but now this happens ( no console output ):

![image](https://user-images.githubusercontent.com/25393315/47260006-d0db5800-d478-11e8-9c1f-592067d9b815.png)

Reverting to kode/kha@0eab549, and kode/khamake@c5e924c will allow games to run again.

**Comment by zicklag** [comment]
I was able to build Kode/krom@a3616a1 ( master ) from source and that was part of the issue, but you also need the latest Kode/kha@2a96259 ( master ) merged with Kode/kha@30919e5 ( krom_api_1 ) before it works.

So it looks like you just need the **absolute** latest version of everything ( with an extra patch ). :smile:

**Comment by luboslenco** [comment]
Should be all good now, everything updated! 🎉
