### ISSUE TITLE
Mac "Show Mouse" / "Set Mouse Lock" not working

### ISSUE THREAD

**Issue by Sanchest9** [armory3d/armory#971]
Hey there! I am running ### macOS Mojave 10.14 & using **Armory0.5**. While I tried creating a **first-person game**, I wanted to **lock** & **hide** the mouse. Although I connected all the nodes correctly & made it fullscreen, the mouse **doesn't** seem to lock nor hide. 
_Not sure if only I encounter this problem or anybody else too._

[fpGame.blend.zip](https://github.com/armory3d/armory/files/2498623/fpGame.blend.zip)

**Comment by luboslenco** [comment]
Thanks for report! Fix finally incoming at https://github.com/Kode/Kore/pull/361.
