### ISSUE TITLE
Continuous collison detection needed

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#974]
The player controller is not the issue, it uses correctly physics with SetLinearVelocity.

The issue is there is there is no continuous collision detection to prevent physic objects passing through others.
 [http://forums.armory3d.org/t/timeline-with-physics/2050/3](url)

I made a level test.
Blue platform physics object uses timeline animation , while the blue moving cube uses translate function.
Player controller and it's weapon projectiles can pass through other physics objects.

https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/B/fps%20Zelda.zip

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/922.
