### ISSUE TITLE
[Usability] Play Action node options

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#979]
Logic node "Play Action" needs options : 
- Speed
- Loop animation
- Ping pong animation loop

**Comment by luboslenco** [comment]
Chain `Play Action` node with `Set Action Speed` or `Pause Action` nodes. `Set Action Speed` set to -1 will play in reverse.

**Comment by DevMagicLord** [comment]
This is an improvement, to avoid spaghetti code :+1: 

Most of the time you'll set speed and loop mode in the "¨may action"

Loop , ping pong, non loop play mode is missing.

**Comment by luboslenco** [comment]
The problem is there will be multiple ways of doing the same thing, which will eventually hamper the learning curve. Nodes will end up with tons of sockets instead of being modular. It will be possible to use node groups for better organization once implemented.
