### ISSUE TITLE
Animation and rendering bug

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#980]
The issues : 

1) The character animations play correctly  Blender Dope Sheet.
When the game runs , the animation is very buggy.

2) In Blender 3D view the character is rendered correctly, in game many polygons are not visible.

Project download : 
[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/B/animation%20issue.zip](url)

**Comment by luboslenco** [comment]
Continues at https://github.com/armory3d/armory/issues/972.
