### ISSUE TITLE
Values for unchanged animation channels generate NaN

### ISSUE THREAD

**Issue by robknopf** [armory3d/armory#981]
Created simple path follow, baked action and assigned it.  Animated object didn't appear in scene during play (and generates NaN values in inspector).  

Removing unchanged channels, sampling all keys, or setting channel extrapolation to constant is a workaround.

Blend file (2.79):
[orbit.zip](https://github.com/armory3d/armory/files/2517674/orbit.zip)

**Comment by luboslenco** [comment]
Appears to work now using the `ArmorySDK-2019-08`, thanks for report.
