### ISSUE TITLE
Materials functions 

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#985]
Some useful material functions to modify a materials using Haxe code or logic nodes.

SetMaterialAlbedoColor
SetMaterialAlbedoTexture
SetMaterialNormalTexture
SetMaterialRoughnessValue
SetMaterialRoughnessTexture
SetMaterialEmissiveColor
SetMaterialEmissiveTexture

And the ability to send parameters to shader nodes using Haxe code or logic nodes.
SendParameter(name, float value)
SendParameter(name, Vector3)

**Comment by luboslenco** [comment]
See manual [here](https://armory3d.org/manual/#/graphics/materials?id=material-parameters).
