### ISSUE TITLE
Object with no UV render bug

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#986]
Steps to reproduce
- open some template controller
- add a cube
- assign new material to cube
- copy and paste and existing Armory pbr material with textures to the cube

When the game runs the cube is rendering very buggy.

**Comment by luboslenco** [comment]
> copy and paste and existing Armory pbr material with textures to the cube

You should get `Armory Warning: Geometry Cube is missing UV map` in the console. If you want to sample textures using the UV map then the UV map needs to come from somewhere.

Unless I am misunderstanding you, if that is the case please paste the blend.
