### ISSUE TITLE
GI should not bake dynamic objects

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#987]
When global illumination is enabled without relight (too much slow) , 
Armory bakes dynamic physics objects in the global illumination.

It's not good because when dynamic objects moves there is global illumination that should not be where the objects was.

**Comment by luboslenco** [comment]
Fix at https://github.com/armory3d/iron/commit/c7aac375e07474d8fdecd9eefc2aab9972d31eb9.
(Works for objects with `Properties - Object - Armory Props - Mobile` flag enabled.)
