### ISSUE TITLE
Cannot play parented animation

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#988]
Armory can't play an animation correctly when armature has parented bones.

Discussion thread
[http://forums.armory3d.org/t/animation-with-parented-bones/2093](url)

Project download
[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/C/animationBug.zip](url)

**Comment by luboslenco** [comment]
Continues at https://github.com/armory3d/armory/issues/972.
