### ISSUE TITLE
Wrong rendering

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#989]
The material renders well on Godot 3.
In armory with same textures it does not render metal and roughness.

Discussion thread
http://forums.armory3d.org/t/rendering-bug/2105

To try it 
[https://github.com/DevMagicLord/Godot3/blob/master/Armory/bugs/C/model.zip](url)

**Comment by luboslenco** [comment]
Link to https://github.com/armory3d/armory/issues/624.
