### ISSUE TITLE
Prefab system and Blender

### ISSUE THREAD

**Issue by DevMagicLord** [armory3d/armory#993]
There can't be two objects with their child object with same name.

Enemy has a child empty object named "position projectile", duplicate enemy object but it's child object can't have the same name (Blender rename it to "position projectile.001")

So child objects can't be referenced by name when some object is duplicated.

Prefabs are not possible in Armory or Blender until some packaged prefab system is made.
Blender would only display an object on hierarchy and would not display child objects.

**Comment by luboslenco** [comment]
See manual [here](https://armory3d.org/manual/#/essentials/multiuser).
Link to https://github.com/armory3d/armory/issues/436.

**Comment by DevMagicLord** [comment]
Full discussion here :
http://forums.armory3d.org/t/armory-prefabs-discussion/2133/10
