### ISSUE TITLE
Continuous Collosion Detections

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory#996]
There are tons of request for this feature from both forum and discord.
We are planning on making doom clone, where doom is fast-paced, without CCD it just have no point.
and yeah, I see CCD option in rigid bodies tab, but it doesn't work.
So, when will this be solved?

**Comment by luboslenco** [comment]
Keep in mind we have limited resources and managing the project is not an easy task. Please don't make it even more difficult by creating duplicate issues, in the end that only slows down the development for everyone. Post at https://github.com/armory3d/armory/issues/922 instead.

CCD option was already implemented and seems to work fine for the templates. More details on what 'doesn't work' can help to improve this feature.
